import type { Master } from "../types";

export const adrenal: Master[] = [
  {
    id: "adrenal-anatomy",
    topicId: "adrenal",
    title: "Adrenal anatomy, embryology and cortical hormone synthesis",
    highYield: true,
    gold: true,
    tags: ["adrenal anatomy", "steroidogenesis", "CYP11B", "zones"],
    exams: [
      { session: "Dec", year: 2011, marks: "5+5", stem: "Describe the anatomy of the adrenal gland. Draw a diagram showing the steps in production of adrenal cortical hormones." },
      { session: "Dec", year: 2015, marks: "5+5", stem: "Surgical anatomy of the adrenal glands and clinical indications for adrenalectomy." },
      { session: "June", year: 2022, marks: "5+5", stem: "Discuss the embryology and development of the adrenal gland. Discuss the evaluation and management of a patient who presents with Pheochromocytoma." },
    ],
    related: ["raas", "pheo", "incidentaloma", "conn"],
    references: [
      "Campbell-Walsh-Wein, Adrenal anatomy and physiology",
      "Hinman Atlas",
      "Miller / White — steroidogenic pathway",
      "EAU / AUA adrenal guidelines",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Draw: right adrenal (pyramidal, on IVC, retrocaval arterial twigs) vs left (crescentic, related to pancreas/splenic vein). Three arteries, one vein. Cortex mesoderm / medulla neural crest. Steroid pathway from cholesterol to aldosterone/cortisol/androgens with enzyme names." },
      { t: "h", v: "Embryology (June 22)" },
      { t: "ul", v: [
        "Cortex: coelomic intermediate mesoderm (urogenital ridge) from week 4–5. Fetal zone (huge, DHEA-S for placenta) involutes after birth; definitive zone becomes glomerulosa/fasciculata/reticularis (reticularis last, by 1–3 years). SF-1, DAX-1, ACTH drive development. Congenital adrenal hyperplasia (21-hydroxylase) is a fetal-zone androgen storm.",
        "Medulla: neural-crest sympathochromaffin cells migrate along the adrenal vein / central vein into the medial cortex (week 6–7). This is why extra-adrenal paraganglia exist (Zuckerkandl, organ of Zuckerkandl at IMA, bladder, thorax) and why a pheo can be extra-adrenal. Glucocorticoid from the surrounding cortex induces PNMT → adrenaline (epinephrine) is almost exclusive to intra-adrenal medulla; extra-adrenal paraganglia make noradrenaline.",
        "The gland is retroperitoneal, inside Gerota, with its own tarry areolar plane (not truly inside the same fascia as the kidney at the superomedial cusp — relevant to partial adrenal-sparing and to remaining adrenal rest tissue).",
      ]},
      { t: "h", v: "Surgical anatomy" },
      { t: "tbl", h: ["", "Right", "Left"], r: [
        ["Shape", "Pyramidal / triangular", "Crescentic / semilunar"],
        ["Relations", "IVC (medial, short vein — the danger), liver (bare area), kidney, duodenum, right crus", "Aorta, pancreas/splenic vessels (anterior, the laparoscopic danger), stomach, kidney, left crus, spleen"],
        ["Vein", "Short 1–5 mm right adrenal vein → posterior IVC (rarely hepatic). Tearing here is the classic catastrophe.", "Longer left adrenal vein → left renal vein, often joined by inferior phrenic. Clip twice."],
        ["Arteries (both, 3)", "Superior (inferior phrenic), middle (aorta), inferior (renal artery). Multiple tiny capsular twigs — no single pedicle to chase except the vein.", "Same"],
        ["Lymph", "Para-aortic, renal hilar, IVC. Not a first-echelon pelvic drainage.", "Same"],
        ["Access", "Laparoscopic transperitoneal subhepatic; retroperitoneoscopic (Walz) especially for small lesions and re-do; open thoracoabdominal for giant / IVC thrombus pheo/ACC.", "Lap transperitoneal after taking splenocolic; retroperitoneoscopic."],
      ]},
      { t: "p", v: "Each gland 4–6 g, 3–5 cm. Golden cortex, brown-red medulla. The right vein is the anatomic reason right lap adrenalectomy is harder; the left pancreas is why left adrenalectomy gets a pancreatic fistula if you wander." },
      { t: "h", v: "Cortical hormone steps (draw as a cascade)" },
      { t: "ul", n: true, v: [
        "Cholesterol (LDL + de novo, StAR protein shuttles into mitochondria) → pregnenolone (CYP11A1, side-chain cleavage, rate-limiting).",
        "Pregnenolone ⇄ progesterone (3β-HSD).",
        "Mineralocorticoid (zona glomerulosa, angiotensin-II / K+ driven, no 17α-hydroxylase): progesterone → 11-deoxycorticosterone (CYP21A2) → corticosterone (CYP11B2 / aldosterone synthase, 11β) → 18-OH-corticosterone → aldosterone (CYP11B2). Glomerulosa lacks CYP17, so it cannot make cortisol or androgens.",
        "Glucocorticoid (zona fasciculata, ACTH / CRH, circadian): 17α-hydroxypregnenolone / 17α-hydroxyprogesterone (CYP17A1 17α-hydroxylase) → 11-deoxycortisol (CYP21A2) → cortisol (CYP11B1). 11β-HSD2 in kidney converts cortisol → cortisone so the MR is not flooded.",
        "Androgen (zona reticularis, ACTH, DHEAS rises at adrenarche): CYP17 17,20-lyase → DHEA → DHEA-S (SULT2A1) → androstenedione. Peripheral conversion to T/oestrogen.",
        "Medulla (separate): tyrosine → DOPA (tyrosine hydroxylase, rate-limit) → dopamine → noradrenaline (vesicular) → adrenaline (PNMT, cortisol-induced).",
      ]},
      { t: "tbl", c: "CAH one-liners if they ask a branch", h: ["Block", "Build-up", "Clinical"], r: [
        ["21-OH (CYP21A2) — 95% of CAH", "17-OHP, androgens; salt-wasting if both aldosterone and cortisol gone", "Virilisation, salt-wasting crisis, high 17-OHP"],
        ["11β-OH (CYP11B1)", "11-deoxycortisol, DOC (mineralocorticoid)", "Virilisation + hypertension / low K"],
        ["17α-OH", "DOC, corticosterone; no sex steroids", "Hypertension, delayed puberty"],
        ["Aldosterone synthase", "Corticosterone", "Salt wasting without virilisation"],
      ]},
      { t: "h", v: "Indications for adrenalectomy (Dec 15)" },
      { t: "ul", v: [
        "Functioning: pheo/paraganglioma, unilateral APA (Conn), Cushing's ACTH-independent (adenoma, selected AIMAH after careful work-up), selected virilising/feminising tumours.",
        "Non-functioning: size (traditionally ≥4 cm, or ≥3–4 cm with suspicious imaging), growth, HU >10 / poor washout / heterogeneity / necrosis / calcification pattern of ACC, oncocytic, resectable isolated metastasis (lung, kidney, melanoma — after PET and after ruling out pheo).",
        "ACC: open en-bloc, do not morcellate, do not spill. Adjacent kidney/spleen/IVC as required.",
        "Not: myelolipoma unless huge/symptomatic, simple cyst, proven adenoma <4 cm with benign imaging and no function, bilateral ‘incidentalomas’ that are macronodular without function (observe / medical).",
        "Always exclude pheo biochemically BEFORE biopsy or incision — a biopsy of an unblocked pheo is an examination offence.",
      ]},
    ],
  },
  {
    id: "raas",
    topicId: "adrenal",
    title: "Adrenal cortical zones, RAAS and mineralocorticoids",
    highYield: true,
    gold: true,
    tags: ["RAAS", "aldosterone", "zona glomerulosa", "ACE"],
    exams: [
      { session: "Dec", year: 2021, marks: "2+4+4", stem: "What are the zones of adrenal cortex? What are the hormones produced by each zone? Describe the renin-angiotensin-aldosterone-system." },
      { session: "Dec", year: 2014, marks: "10", stem: "Physiology of Renin-Angiotensin-Aldosterone-System (RAAS)." },
      { session: "Dec", year: 2020, marks: "2+4+4", stem: "What are different zones of adrenal gland cortex? What is the role of each zone? What are the primary effects and site of action of mineralo-corticoids?" },
    ],
    related: ["adrenal-anatomy", "conn", "incidentaloma"],
    references: [
      "Campbell-Walsh-Wein, Adrenal physiology",
      "Guyton / Ganong RAAS",
      "Endocrine Society primary aldosteronism guideline",
    ],
    answer: [
      { t: "tbl", c: "Zonae (GFR — salt, sugar, sex)", h: ["Zone", "Product", "Regulator", "Role"], r: [
        ["Glomerulosa (outer, 15%)", "Aldosterone (mineralocorticoid)", "Angiotensin-II, K+, (ACTH acute only)", "Na+ retention, K+/H+ excretion, volume, BP"],
        ["Fasciculata (middle, 75%)", "Cortisol (glucocorticoid)", "ACTH (CRH, circadian, stress)", "Gluconeogenesis, anti-inflammatory, vascular tone, peri-op survival"],
        ["Reticularis (inner, 10%)", "DHEA / DHEA-S / androstenedione", "ACTH, adrenarche programming", "Peripheral androgen/oestrogen precursor"],
        ["Medulla (not cortex)", "Adrenaline > noradrenaline, dopamine", "Preganglionic sympathetic (ACh), cortisol-induced PNMT", "Fight-or-flight"],
      ]},
      { t: "h", v: "RAAS — the loop to write as a flowchart in prose" },
      { t: "ul", n: true, v: [
        "Juxtaglomerular (afferent arteriolar granular) cells release renin (an aspartyl protease) in response to: (a) renal hypoperfusion (baroreceptor), (b) low NaCl at the macula densa (TAL), (c) β1-sympathetic. Inhibitors: ANP, high Na, AT-II feedback.",
        "Renin cleaves hepatic angiotensinogen → angiotensin I (decapeptide, inactive).",
        "ACE (pulmonary and renal endothelium, also the brush border) converts AT-I → angiotensin II (octapeptide). ACE also degrades bradykinin (ACE-I cough / angioedema).",
        "AT-II via AT1 receptors: arteriolar vasoconstriction (efferent > afferent in the glomerulus — preserves GFR in low perfusion), thirst, ADH, proximal Na+ reabsorption, aldosterone secretion, cardiac/vascular hypertrophy, sympathetic facilitation.",
        "Aldosterone (zona glomerulosa, minutes to hours): genomic MR effects in principal cells of cortical collecting duct — ↑ENaC, ↑Na/K-ATPase, ↑ROMK → Na+ (and water) in, K+ and H+ out. Non-genomic vascular effects exist.",
        "Negative feedback: volume restoration shuts off renin; AT-II and K+ modulate; ANP opposes.",
      ]},
      { t: "h", v: "Mineralocorticoids — primary effects and site" },
      { t: "ul", v: [
        "Principal site: principal cells of the late distal tubule and cortical collecting duct (kidney). Also colon, salivary/sweat glands (hence cystic-fibrosis-like salt loss if MR blocked), hippocampus, heart, vessels.",
        "Effects: expansion of ECF and plasma volume, hypertension if autonomous, hypokalaemia, metabolic alkalosis (H+ loss via H-ATPase of intercalated cells and K+ depletion).",
        "Cortisol circulates at 100–1000× aldosterone and binds MR, but 11β-HSD2 in the kidney inactivates cortisol → cortisone. Liquorice / apparent mineralocorticoid excess / severe Cushing overwhelm this shuttle — mineralocorticoid hypertension without high aldosterone.",
        "Pharmacology: ACE-I / ARB / renin-I interrupt the loop; spironolactone / eplerenone / finerenone block MR (Conn medical therapy, HF); amiloride blocks ENaC.",
      ]},
      { t: "tip", k: "gold", v: "GFR = salt, sugar, sex. Renin (JG) → AT-I → ACE → AT-II → aldosterone (ENaC in CCD). 11β-HSD2 is why cortisol does not normally act as aldosterone." },
    ],
  },
  {
    id: "incidentaloma",
    topicId: "adrenal",
    title: "Adrenal incidentaloma — evaluation and management algorithm",
    highYield: true,
    gold: true,
    tags: ["incidentaloma", "HU", "washout", "1 mg DST", "ARR"],
    exams: [
      { session: "Dec", year: 2022, marks: "10", stem: "Algorithm for diagnosis and management of incidentaloma of adrenal gland." },
      { session: "Dec", year: 2017, marks: "10", stem: "Provide an algorithm for evaluation of an adrenal mass." },
      { session: "Jun", year: 2020, marks: "5+5", stem: "How will you evaluate a case of adrenal incidentaloma? Management algorithm for incidentaloma of adrenal." },
      { session: "Dec", year: 2014, marks: "3+4+3", stem: "Classification, evaluation and management algorithm of adrenal incidentaloma." },
    ],
    related: ["pheo", "conn", "myelolipoma", "adrenal-anatomy"],
    references: [
      "NIH 2002 incidentaloma state-of-the-science",
      "AACE/AAES; ESE/ENSAT 2016 and 2023 updates",
      "EAU / AUA adrenal incidentaloma",
      "Campbell-Walsh-Wein",
    ],
    answer: [
      { t: "p", v: "Incidentaloma = an adrenal mass ≥1 cm detected on imaging done for another reason. Prevalence ~3% of CT, higher with age. Two questions only: (1) is it functioning? (2) is it malignant (primary ACC vs metastasis)? Size and imaging phenotype answer (2); biochemistry answers (1). Never biopsy until pheo is excluded." },
      { t: "h", v: "Classification" },
      { t: "ul", v: [
        "Non-functioning adenoma (~75%).",
        "Autonomous cortisol secretion / subclinical Cushing (5–30% depending on definition).",
        "Phaeochromocytoma (~5%).",
        "Aldosteronoma (~1–2% of all incidentalomas, higher if hypertensive).",
        "ACC (<5% of incidentalomas, but 50%+ of masses >6 cm).",
        "Metastasis (lung, kidney, breast, melanoma, lymphoma — higher if extra-adrenal cancer history).",
        "Myelolipoma, cyst, ganglioneuroma, haemorrhage, TB, histoplasmosis.",
      ]},
      { t: "h", v: "Imaging phenotype" },
      { t: "tbl", h: ["Feature", "Benign adenoma", "Worry (ACC / pheo / met)"], r: [
        ["Size", "<4 cm", ">4–6 cm (ACC risk rises; 4 cm is the usual surgical discuss-line)"],
        ["Native HU", "≤10 HU = lipid-rich adenoma (almost excludes ACC/pheo/met)", ">10 HU — indeterminate"],
        ["Contrast washout (if HU 10–30)", "APW ≥60% and RPW ≥40% at 15 min = adenoma", "Poor washout: ACC / met / pheo"],
        ["Shape", "Homogeneous, smooth, round", "Heterogeneous, necrosis, haemorrhage, calcification irregular, local invasion, thrombus"],
        ["Growth", "Stable", ">5 mm/year or 20% volume — resect"],
        ["MRI", "Chemical-shift drop-out (lipid)", "No drop-out; T2 bright pheo (‘light-bulb’) is supportive not diagnostic"],
        ["FDG-PET", "Low", "High SUV — met/ACC; pheo also avid (not specific)"],
      ]},
      { t: "h", v: "Biochemical panel — every incidentaloma" },
      { t: "ul", v: [
        "1 mg overnight dexamethasone suppression test (DST): cortisol ≤1.8 µg/dL (50 nmol/L) excludes autonomous cortisol. 1.8–5 = possible; >5 = autonomous. Confirm with ACTH, 24-h UFC or late-night salivary as needed. (ESE 2023 still wants a DST on all.)",
        "Plasma free metanephrines (supine, canulated) or 24-h urinary fractionated metanephrines — all patients. Do this before any biopsy, FNA, or surgery.",
        "Aldosterone:renin ratio if hypertension or unexplained hypokalaemia. Correct K+, hold spironolactone 4–6 weeks.",
        "Androgens / oestradiol only if virilisation, feminisation, or obvious ACC.",
        "If cancer history and non-functioning indeterminate mass: PET, and FNA only after pheo excluded — to confirm metastasis if it would change systemic therapy, not ‘to see what it is’ before a clearly indicated adrenalectomy.",
      ]},
      { t: "flow", title: "Incidentaloma algorithm", nodes: [
        { id: "a", kind: "start", label: "Adrenal mass ≥1 cm, incidental", to: ["b"] },
        { id: "b", kind: "action", label: "History/exam (HTN, spells, Cushing, extra-adrenal cancer). HU, washout, size. DST + metanephrines ± ARR", to: ["c"] },
        { id: "c", kind: "decision", label: "Pheo biochem + ?", to: ["d", "e"] },
        { id: "d", kind: "end", label: "α-block then laparoscopic adrenalectomy (see pheo card). Never biopsy." },
        { id: "e", kind: "decision", label: "Cushing / APA / sex-steroid autonomous?", to: ["f", "g"] },
        { id: "f", kind: "end", label: "Unilateral: laparoscopic adrenalectomy after AVS for Conn if >35 y / bilateral nodules. Cortisol: peri-op glucocorticoid cover." },
        { id: "g", kind: "decision", label: "Non-functioning. HU ≤10 and <4 cm and homogeneous?", to: ["h", "i"] },
        { id: "h", kind: "end", label: "Observe. Repeat imaging 6–12 months then stop if stable (ESE 2023 liberal). Repeat biochem if clinical change." },
        { id: "i", kind: "decision", label: "≥4 cm or HU >10 / poor washout / growth / cancer history with no other primary?", to: ["j"] },
        { id: "j", kind: "end", label: "Adrenalectomy (lap if clearly resectable and not obviously ACC; open if ACC suspected). FNA only for suspected met after pheo ruled out, if result changes care." },
      ]},
      { t: "tip", k: "gold", v: "Function? Malignant? DST + metanephrines ± ARR on everyone. HU ≤10 and <4 cm observe. ≥4 cm or ugly or functioning — out. Never biopsy a possible pheo." },
    ],
  },
  {
    id: "pheo",
    topicId: "adrenal",
    title: "Phaeochromocytoma — biochemistry, prep, bilateral, extra-adrenal, metastatic",
    highYield: true,
    gold: true,
    tags: ["pheo", "metanephrines", "phenoxybenzamine", "SDHB", "MIBG"],
    exams: [
      { session: "June", year: 2022, marks: "5", stem: "Evaluation and management of a patient who presents with Pheochromocytoma." },
      { session: "Jun", year: 2019, marks: "5+5", stem: "Evaluation and management of bilateral pheochromocytoma." },
      { session: "Dec", year: 2012, marks: "5+5", stem: "Describe the biochemical and imaging investigations used in evaluating a suspected pheochromocytoma." },
      { session: "Jun", year: 2018, marks: "5+5", stem: "Investigative work up in suspected Pheochromocytoma and preoperative preparation of a diagnosed case." },
      { session: "Dec", year: 2021, marks: "6+4", stem: "Pheochromocytoma: medical preparation before the surgery. Metastatic pheochromocytoma." },
      { session: "Jun", year: 2019, marks: "2+3+5", stem: "Possible locations, diagnosis and outline of management of extra-adrenal pheochromocytoma." },
      { session: "Dec", year: 2016, marks: "3+3+4", stem: "Clinical presentation, diagnosis and peri-operative management of extra-adrenal pheochromocytoma." },
      { session: "Dec", year: 2013, marks: "5+5", stem: "Describe pre-operative and intra-operative management of a patient of pheochromocytoma." },
    ],
    related: ["adrenal-anatomy", "incidentaloma", "neuroblastoma"],
    references: [
      "Endocrine Society Pheochromocytoma/Paraganglioma Guideline 2014",
      "EAU / AUA adrenal",
      "Campbell-Walsh-Wein, Pheochromocytoma",
      "WHO: PPGL (phaeochromocytoma and paraganglioma)",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "Rule of 10s is outdated (more like 30% extra-adrenal, 30% familial, 10% malignant, 10% bilateral, 10% children, 10% extra-abdominal). 40%+ harbour a germline mutation — everyone gets genetic testing. α-block BEFORE β-block. Never biopsy." },
      { t: "h", v: "Clinical" },
      { t: "ul", v: [
        "Classic triad: headache, palpitations, diaphoresis — with hypertension (paroxysmal or sustained). The 5 Ps: Pressure, Pain (head), Perspiration, Palpitation, Pallor.",
        "Spells, orthostatic hypotension (volume contraction), lactic acidosis, cardiomyopathy (Takotsubo-like), hyperglycaemia, unexpected anaesthetic crisis, incidentaloma.",
        "Syndromes: MEN2 (RET, medullary thyroid, hyperPTH — pheo bilateral, adrenal, adrenaline-secreting), VHL type 2, NF1, SDHB/C/D/A/AF2 (paraganglioma, SDHB = malignant risk), TMEM127, MAX, FH.",
      ]},
      { t: "h", v: "Biochemistry (do this first)" },
      { t: "ul", v: [
        "Plasma free metanephrines (supine 20 min, drawn from a dwelling cannula) — highest sensitivity. 24-h urinary fractionated metanephrines and catecholamines — equivalent if collection is complete. Do NOT use random plasma catecholamines (too noisy).",
        "Interpretation: >3× ULN is almost diagnostic. 1–3×: repeat, stop confounding drugs (β-blockers, TCA, antipsychotics, levodopa, acetaminophen in some assays, sympathomimetics, withdrawal from clonidine), consider clonidine suppression (fails to suppress in pheo).",
        "Chromogranin A — non-specific. Methoxytyramine: SDHB and extra-adrenal, dopamine-secreting (may not be hypertensive — still α-block).",
        "Always biochemically prove before you image for a ‘possible pheo’ in a hypertensive (except the life-threatening crisis already in ICU).",
      ]},
      { t: "h", v: "Imaging" },
      { t: "ul", v: [
        "CT abdomen (non-contrast HU typically >10, avid enhancement, delayed washout — do not use washout to exclude pheo) or MRI (T2 bright, no radiation — preferred in children, pregnancy, extra-adrenal hunt).",
        "If extra-adrenal / bilateral / metastatic / SDHB / occult after CT: 68Ga-DOTATATE PET-CT is the current best functional study; 123I-MIBG if DOTATATE unavailable or if planning 131I-MIBG therapy; 18F-FDG for SDHB metastatic. 131I-MIBG diagnostic scans are outdated (poor image, high dose).",
        "Never FNA. If a radiologist already did, α-block and treat the crisis.",
      ]},
      { t: "h", v: "Pre-operative medical preparation (the 6-mark ritual)" },
      { t: "ul", n: true, v: [
        "α-blockade first, 7–14 days: non-competitive phenoxybenzamine 10 mg BD titrate to 1 mg/kg/d (stuffy nose, postural drop = adequate) OR competitive doxazosin / prazosin (shorter, less post-op hypotension — both acceptable, RCTs mixed). Goal: BP <130/80 seated, >90 systolic standing, no spells.",
        "THEN β-block if tachycardic (propranolol / atenolol / metoprolol). Never β first — unopposed α → crisis.",
        "Calcium-channel blocker (amlodipine / nicardipine) as adjunct or if α not tolerated. Metyrosine (tyrosine-hydroxylase inhibitor) for unresectable / very high levels.",
        "Volume: high-salt diet + liberal fluids once α-blocked, or 1–2 L saline the night before — they are volume-contracted. Iron if needed.",
        "VTE, glucose, echo if cardiomyopathy, ICU / invasive arterial line booked, vasodilators (SNP, phentolamine, nicardipine, Mg) and pressors (NA) drawn up, avoid droperidol, metoclopramide, desflurane-histamine, atropine excess. Sugammadex/rocuronium fine. No glucagon as a diagnostic test.",
      ]},
      { t: "h", v: "Intra-operative" },
      { t: "ul", v: [
        "Lap / retroperitoneoscopic for most intra-adrenal <6–8 cm; open for extra-adrenal large, hostile, or ACC-uncertain. Early vein ligation is traditional dogma — modern view is gentle dissection and communication with anaesthesia matters more (the vein is short on the right; do not avulse it in a hurry).",
        "Hypertensive spikes during handling: deepen anaesthesia, SNP/phentolamine/nicardipine/Mg, pause surgery.",
        "After the vein is taken: precipitous hypotension — volume, NA infusion, stop vasodilators. Hypoglycaemia post-op (rebound insulin) — monitor.",
        "Cortical-sparing (partial) adrenalectomy for bilateral / hereditary (MEN2, VHL) to avoid lifelong Addisonian crisis — 5–15% recurrence, accept it. Leave 1/3 of a gland. Steroid cover if bilateral total.",
      ]},
      { t: "h", v: "Bilateral pheo (Jun 19)" },
      { t: "p", v: "Think hereditary until genetics return. Staged or synchronous cortical-sparing laparoscopic adrenalectomies, the larger / more active side first. Peri-op steroid if both residual cortices look doubtful. Educate in sick-day rules, MedicAlert. Screen thyroid (calcitonin/CEA/US) for MEN2 before you miss an MTC. Annual metanephrines lifelong." },
      { t: "h", v: "Extra-adrenal paraganglioma" },
      { t: "ul", v: [
        "Locations: organ of Zuckerkandl (origin of IMA), para-aortic, thorax, head and neck (carotid, jugular — often non-secretory, SDHD), bladder (micturition spells), pelvis, mediastinum. SDHB is the malignancy gene.",
        "Diagnosis: same biochemistry (head-and-neck may be silent — DOTATATE), whole-body functional imaging mandatory (multifocal).",
        "Management: α-block even if ‘normotensive’ secretory, complete resection with vascular control (Zuckerkandl sits on aorta/IMA), bladder PGL may need partial cystectomy. Higher malignant risk than adrenal pheo — follow-up intense.",
      ]},
      { t: "h", v: "Metastatic pheo (Dec 21)" },
      { t: "p", v: "Malignancy is defined by mets (bone, lymph, lung, liver), not by histology (PASS/GAPP scores are imperfect). SDHB the strongest predictor. No curative chemo standard." },
      { t: "ul", v: [
        "Resect the primary and oligometastases if possible (reduces catecholamine burden). α-block lifelong if residual secretory disease.",
        "131I-MIBG therapy if the deposit is MIBG-avid. 177Lu-DOTATATE (PRRT) if SSTR-avid — expanding.",
        "CVD (cyclophosphamide, vincristine, dacarbazine) or temozolomide (especially SDHB, MGMT-low). Sunitinib / cabozantinib (anti-angiogenic) off-label / trials.",
        "Bone: XRT, denosumab/zoledronate. Ablation, embolisation of liver. Watch QT on some anti-emetics.",
        "Prognosis measured in years; SDHB worse. Genetics for the family.",
      ]},
      { t: "tip", k: "gold", v: "Plasma free metanephrines → image → α then β then volume → laparoscopic / cortical-sparing if hereditary bilateral. Extra-adrenal = paraganglioma, whole-body DOTATATE, SDHB. Metastatic = surgery + MIBG/PRRT + CVD/sunitinib." },
    ],
  },
  {
    id: "conn",
    topicId: "adrenal",
    title: "Conn syndrome (primary aldosteronism)",
    highYield: true,
    gold: false,
    tags: ["APA", "ARR", "AVS", "spironolactone"],
    exams: [
      { session: "Dec", year: 2018, marks: "10", stem: "Conn’s syndrome." },
    ],
    related: ["raas", "incidentaloma", "adrenal-anatomy"],
    references: [
      "Endocrine Society Primary Aldosteronism Guideline 2016",
      "Campbell-Walsh-Wein, Hyperaldosteronism",
      "AVS expertise: Young / Funder",
    ],
    answer: [
      { t: "p", v: "Conn syndrome strictly = aldosterone-producing adenoma (APA). Primary aldosteronism (PA) is the broader, modern term: autonomous aldosterone (APA, bilateral idiopathic hyperaldosteronism / BAH, familial FH-I to IV, rare carcinoma). PA is 5–10% of hypertension and 20% of resistant hypertension — not a zebra. Hypokalaemia is present in <50%; normokalaemic PA is the rule." },
      { t: "h", v: "When to screen (ARR)" },
      { t: "ul", v: [
        "Sustained BP >150/100, resistant HTN (≥3 drugs), controlled on ≥4, hypertension + hypokalaemia (spontaneous or diuretic), hypertension + adrenal incidentaloma, hypertension + sleep apnoea / AF / family early HTN or CVA <40, first-degree relative of PA.",
        "ARR: morning paired aldosterone and plasma renin activity (or direct renin). Positive typically aldosterone ≥10–15 ng/dL with suppressed renin and ARR above local cut-off (e.g. 20–30 SI/conventional — quote your lab). Hold spironolactone/eplerenone 4–6 weeks; β-blockers suppress renin (false +); ACE-I raise renin (false −). Correct K+ first.",
        "Confirmatory: saline suppression, captopril challenge, fludrocortisone-dexamethasone, oral salt loading — pick one. Not needed if spontaneous hypokalaemia + undetectable renin + aldosterone >20 ng/dL.",
      ]},
      { t: "h", v: "Subtype: adenoma vs bilateral" },
      { t: "ul", v: [
        "CT adrenals: a 1 cm lipid-rich nodule in a young (<35) patient with florid PA may go straight to laparoscopic adrenalectomy. Everyone else who wants surgery: adrenal venous sampling (AVS) — the gold standard to lateralise. CT lies (incidentalomas in 35-year-olds+).",
        "AVS: simultaneous or sequential adrenal veins + IVC, with or without ACTH infusion, compare aldosterone/cortisol ratios. Lateralisation index ≥4 (with ACTH) = unilateral. Cannulating the right adrenal vein is the hard part.",
        "Adrenal NP-59 scintigraphy is historical. 11C-metomidate PET is emerging.",
      ]},
      { t: "h", v: "Management" },
      { t: "tbl", h: ["Subtype", "Treatment", "Outcome"], r: [
        ["Unilateral APA / unilateral hyperplasia", "Laparoscopic adrenalectomy (after K+ and BP controlled on MR-antagonist which is then stopped post-op)", "HTN cured in 30–60% (young, short duration, fewer drugs); biochemically cured in ~90%. Residual HTN = essential component."],
        ["Bilateral IHA / patient declines surgery / failed AVS", "MR-antagonist: spironolactone 12.5–100 mg (gynaecomastia, impotence) or eplerenone (cleaner, dearer, BD). Amiloride if intolerant. Usual antihypertensives. K+ supplements stop.", "Target: renin no longer suppressed, K+ normal, BP at goal. This is disease-modifying vs mere BP drugs — it reduces AF/HF risk."],
        ["FH-I (glucocorticoid-remediable, chimeric CYP11B1/B2)", "Low-dose dexamethasone or MR-antagonist", "Family screen"],
        ["ACC secreting aldosterone", "Open oncologic adrenalectomy, staging", "Rare"],
      ]},
      { t: "p", v: "Pre-op: spironolactone until the day of surgery, K+ >3.5, peri-op hypotension is less a pheo-story (no α-block needed). Post-op: K+ can rebound high; renin/aldo recover in weeks; sick-day steroid only if the contralateral was suppressed and you fear hypoaldosteronism (rare, transient)." },
      { t: "tip", k: "gold", v: "Screen with ARR, confirm, AVS unless young + obvious adenoma, laparoscopic adrenalectomy for unilateral, spironolactone for bilateral. Hypokalaemia is optional; resistant hypertension is not." },
    ],
  },
  {
    id: "neuroblastoma",
    topicId: "adrenal",
    title: "Neuroblastoma — evaluation and management",
    highYield: true,
    gold: false,
    tags: ["MYCN", "INSS", "INRG", "MIBG", "adrenal medulla"],
    exams: [
      { session: "Dec", year: 2018, marks: "10", stem: "Evaluation and management of neuroblastoma." },
    ],
    related: ["pheo", "adrenal-anatomy"],
    references: [
      "COG / SIOPEN neuroblastoma protocols",
      "INRG staging 2009; INSS",
      "Campbell-Walsh-Wein, Paediatric adrenal",
      "WHO paediatric tumours",
    ],
    answer: [
      { t: "p", v: "Neuroblastoma is a neural-crest malignancy of the sympathetic chain / adrenal medulla — the commonest extracranial solid tumour of childhood (peak <2 years). Distinct from pheo (chromaffin, older, does not usually make VMA in the same diagnostic frame) and from ganglioneuroma (mature, benign). Heterogeneous: 4S/MS infants can spontaneously regress; MYCN-amplified stage 4 dies without intensive therapy." },
      { t: "h", v: "Presentation" },
      { t: "ul", v: [
        "Abdominal mass (adrenal / retroperitoneal), racoon-eye (orbital mets), blueberry-muffin skin, bone pain, limp, fever, failure to thrive, opsoclonus-myoclonus-ataxia (paraneoplastic, better oncologic prognosis, worse neuro), watery diarrhoea (VIP), Horner (stellate/cervical), cord compression (dumbbell), heterochromia, hypertension uncommon.",
        "Age <18 months is a favourable cut-off; >18 months worse.",
      ]},
      { t: "h", v: "Evaluation" },
      { t: "ul", v: [
        "US then MRI/CT of primary. MIBG scan (90% avid) for staging; FDG-PET if MIBG-negative. Bone marrow trephines (bilateral). Bone scan if MIBG unclear.",
        "Urine VMA/HVA (catecholamine metabolites) — diagnosis + follow-up. Ferritin, LDH, NSE.",
        "Biopsy: histology (neuroblastoma / ganglioneuroblastoma / ganglioneuroma, Shimada / INPC favourable vs unfavourable), MYCN, DNA ploidy, ALK, segmental chromosomal aberrations (1p, 11q). Do not up-front mutilate a 4S infant for a complete resection if biology is favourable.",
        "INSS (surgical): 1 localised complete; 2 incomplete, ipsilateral nodes; 3 unresectable midline / contralateral; 4 distant; 4S infant <12 months, skin/liver/marrow (<10%) with small primary.",
        "INRGSS (pre-treatment, image-defined risk factors): L1, L2, M, MS. Combined with age, MYCN, histology, ploidy → very-low / low / intermediate / high risk.",
      ]},
      { t: "h", v: "Management by risk (COG/SIOPEN distilled)" },
      { t: "tbl", h: ["Risk", "Who", "Treatment"], r: [
        ["Very low / low", "L1 resected, infants MS without MYCN, favourable histology", "Surgery alone or observation (MS / perinatal adrenal masses in selected). Survival >95%."],
        ["Intermediate", "Unfavourable histology but no MYCN, age/stage mix", "Moderate chemo (carboplatin/etoposide/cyclophosphamide/doxorubicin variants) + surgery to residual. Survival ~80–90%."],
        ["High", "MYCN amplified any stage (except rare), or metastatic >18 months", "Induction chemo, surgery to primary, myeloablative chemo + ASCT (or tandem), radiotherapy to primary ± MIBG therapy, anti-GD2 immunotherapy (dinutuximab) + isotretinoin. Survival 40–60% and climbing with GD2."],
        ["MS / 4S", "Infant, skin/liver/marrow, no MYCN", "Observe if well; supportive; low-dose chemo / XRT to liver if compartment syndrome (Pepper syndrome)."],
        ["Cord compression / periorbital", "Emergency", "Chemo usually preferred over laminectomy in a growing child; steroids."],
      ]},
      { t: "p", v: "Surgery: midline / transverse abdominal, adrenal primary often resected at delayed primary operation after shrinkage; spinal tumours need neurosurgery. Nephrectomy is not required if the kidney can be spared. Urologists see these as ‘adrenal masses in toddlers’ — do not treat them as adult pheo (no α-block ritual unless truly a secretory pheo, which this is not). Fertility, hearing (platinum), renal, second cancers — survivorship." },
      { t: "tip", k: "gold", v: "Toddler adrenal mass + racoon eyes + VMA = neuroblastoma. Risk-adapted: observe MS, chemo+GD2 for high-risk MYCN. Not an adult pheo operation." },
    ],
  },
  {
    id: "myelolipoma",
    topicId: "adrenal",
    title: "Adrenal myelolipoma",
    highYield: false,
    gold: false,
    tags: ["myelolipoma", "fat HU", "incidentaloma"],
    exams: [
      { session: "Dec", year: 2016, marks: "2+3+2+3", stem: "Pathogenesis, presentation, diagnosis and management of adrenal myelolipoma." },
    ],
    related: ["incidentaloma", "adrenal-anatomy"],
    references: [
      "Campbell-Walsh-Wein, Adrenal incidentaloma",
      "ESE incidentaloma guidelines",
      "Kenney / Gierke myelolipoma series",
    ],
    answer: [
      { t: "p", v: "Adrenal myelolipoma is a benign, non-functioning tumour of mature adipose tissue plus trilineage haematopoietic marrow elements, usually in the adrenal cortex. 2–4% of adrenal incidentalomas. Not a source of extra-medullary haematopoiesis in the myelofibrosis sense (though rare associations exist)." },
      { t: "h", v: "Pathogenesis" },
      { t: "ul", v: [
        "Metaplasia of adrenocortical cells (or residual mesenchymal rests) under chronic ACTH / stress — supported by association with CAH, Cushing, obesity. Clonality studies mixed.",
        "Not a pheo, not ACC. Can coexist with an adenoma (collision). Giant myelolipomas in poorly controlled CAH — treat the CAH.",
      ]},
      { t: "h", v: "Presentation" },
      { t: "ul", v: [
        "Incidental on CT. Occasional loin pain, mass, rupture / retroperitoneal haemorrhage (more if >7–10 cm). Endocrine symptoms imply a collision tumour or CAH, not the fat itself.",
        "Age 50–70, right slightly more, can be bilateral, can be extra-adrenal (presacral — differential of liposarcoma).",
      ]},
      { t: "h", v: "Diagnosis" },
      { t: "ul", v: [
        "CT: macroscopic fat (HU −30 to −90) mixed with soft-tissue marrow islands, well-circumscribed, may have haemorrhage/calcification. Pathognomonic in the adrenal — do not FNA a classic lesion.",
        "MRI: fat-sat drop-out. If fat-poor, it falls into the incidentaloma algorithm (exclude pheo/function, discuss resection).",
        "Still run the incidentaloma biochemical panel once — collision tumours happen. A ‘myelolipoma’ with HU not fat is not a myelolipoma.",
      ]},
      { t: "h", v: "Management" },
      { t: "ul", v: [
        "Observe the typical small (<4–6 cm) asymptomatic lesion — no serial imaging mandate beyond a confirmatory scan.",
        "Resect (laparoscopic adrenalectomy) if symptomatic, ruptured, ≥6–7 cm (haemorrhage risk, also to exclude a missed liposarcoma / collision ACC), growth, or diagnostic doubt.",
        "Bilateral: spare cortex if operating. CAH: optimise glucocorticoid before blaming the mass.",
      ]},
      { t: "tip", k: "exam", v: "Fat + marrow, pathognomonic CT, non-functioning. Watch small; operate large, painful, or atypical. Still exclude pheo once if the imaging is not textbook fat." },
    ],
  },
];
