import type { Master } from "../types";

export const basics: Master[] = [
  {
    id: "pod",
    topicId: "basics",
    title: "Post-obstructive diuresis",
    highYield: true,
    gold: true,
    tags: ["physiology", "obstruction", "fluids", "POD"],
    exams: [
      { session: "Dec", year: 2022, marks: "5+5", stem: "Pathophysiology of post-obstructive diuresis. Management with special emphasis on fluid management." },
      { session: "Jun", year: 2021, marks: "4+6", stem: "What is post-obstructive diuresis? How do you manage it?" },
      { session: "Jun", year: 2020, marks: "3+3+4", stem: "Define post-obstructive diuresis, its mechanism and clinical management." },
      { session: "Dec", year: 2019, marks: "4+3+3", stem: "Physiology of post-obstructive diuresis. Principles of prevention and treatment." },
      { session: "Dec", year: 2011, marks: "4+6", stem: "What is post obstructive diuresis? What are the principles in managing it?" },
    ],
    related: ["obstructive-uropathy", "hyponatremia", "urine-concentration"],
    references: [
      "Campbell-Walsh-Wein Urology, 12th ed. Ch. Pathophysiology of Urinary Tract Obstruction",
      "Vaughan ED, Gillenwater JY. J Urol 1973 — classic POD series",
      "AUA / EAU Upper Tract Obstruction chapters",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map (10 marks)", v: "Definition 1 · Physiology 3–4 · Who is at risk 1 · Monitoring 2 · Fluids/electrolytes 2–3 · When to stop 1. Draw the nephron and label where salt and urea are lost." },
      { t: "h", v: "Definition" },
      { t: "p", v: "Post-obstructive diuresis (POD) is a physiologic or pathologic polyuria that follows relief of bilateral ureteric obstruction or obstruction of a solitary functioning kidney. Practical threshold used in answers: urine output >200 mL/h for ≥2 consecutive hours, or >3000 mL/24 h, after decompression." },
      { t: "ul", v: [
        "Physiologic POD: excretion of retained water, urea and natriuretic substances; self-limited (24–48 h); patient remains euvolaemic.",
        "Pathologic POD: inappropriate salt-wasting and impaired concentrating ability that continues after euvolaemia is restored; risk of hypovolaemia, shock and death if replacement is naive.",
      ]},
      { t: "h", v: "Pathophysiology (write as a cascade)" },
      { t: "p", v: "Chronic obstruction raises tubular pressure → falls in GFR and medullary blood flow → down-regulation of Na/K-ATPase, NKCC2 (thick ascending limb), ENaC and aquaporin-2. Urea and natriuretic peptide (ANP/BNP) accumulate. After sudden decompression:" },
      { t: "ul", n: true, v: [
        "Osmotic (urea) diuresis — the dominant early driver. Filtered urea that was retained now acts as a non-reabsorbable osmole.",
        "Salt wasting — damaged TAL and collecting duct cannot reclaim NaCl; secondary hyperaldosteronism is blunted.",
        "Water diuresis — AQP2 and concentrating gradient (urea recycling, thick-limb NaCl) are lost; ADH resistance (down-regulated V2 effect).",
        "Atrial natriuretic peptide remains high until volume is corrected, perpetuating natriuresis.",
        "Bicarbonate and potassium wasting follow increased distal flow and secondary hyperaldosteronism once volume is replaced.",
      ]},
      { t: "tbl", c: "Physiologic vs pathologic POD", h: ["Feature", "Physiologic", "Pathologic"], r: [
        ["Duration", "24–48 h", ">48–72 h, or continues after euvolaemia"],
        ["Urine Na", "Usually <40 mEq/L once volume restored", "Often >40–70 mEq/L persistently"],
        ["Urine osmolality", "Approaches plasma as urea falls", "Remains isosthenuric"],
        ["Volume status", "Euvolaemic; weight falls to dry weight", "Hypovolaemic if not replaced"],
        ["Trigger", "Solute load clearance", "Tubular injury + ANP + concentrating defect"],
      ]},
      { t: "h", v: "Who is at risk — list this" },
      { t: "ul", v: [
        "Chronic (not acute) obstruction; bilateral or solitary kidney.",
        "Azotaemia (urea is the osmolar load), oedema, congestive failure, hypertension.",
        "Massive bladder residual after chronic retention (BPH, stricture, neurogenic).",
        "Poor concentrating ability already (CKD, lithium, interstitial disease).",
      ]},
      { t: "h", v: "Clinical management — gold sequence" },
      { t: "flow", title: "POD after catheterisation / nephrostomy", nodes: [
        { id: "a", kind: "start", label: "Relieve obstruction (catheter, PCN, stents)", to: ["b"] },
        { id: "b", kind: "action", label: "Admit HDU if Cr high / solitary kidney / frail", to: ["c"] },
        { id: "c", kind: "action", label: "Strict I/O, hourly UO, daily weight, postural vitals", to: ["d"] },
        { id: "d", kind: "action", label: "Labs q4–6h: Na, K, Mg, PO4, HCO3, urea, Cr, osmolality (serum + urine)", to: ["e"] },
        { id: "e", kind: "decision", label: "UO >200 mL/h × 2 h?", to: ["f", "g"] },
        { id: "f", kind: "action", label: "Replace 50–75% of previous hour's UO with 0.45% NaCl (or matched to urine Na)", note: "Do NOT 1:1 replace once euvolaemic" },
        { id: "g", kind: "end", label: "Observe; oral fluids if taking diet" },
      ]},
      { t: "h", v: "Fluid rules the examiner wants" },
      { t: "ul", v: [
        "Initial 12 h: replace ~75% of output with hypotonic saline (0.45%) ± KCl as labs dictate. Goal is to match the urine electrolyte composition, not to chase every millilitre.",
        "After euvolaemia (JVP normal, no postural drop, weight at estimated dry weight): cut replacement to 50% then stop; allow oral auto-regulation.",
        "Never replace 1:1 indefinitely — that iatrogenically perpetuates the diuresis.",
        "Potassium: urinary K often 20–40 mEq/L; add 20–40 mEq KCl/L replacement once anuric-phase hyperkalaemia has fallen.",
        "Watch Mg and PO4 (refeeding / diuretic washout). Correct symptomatic hypocalcaemia if present.",
        "If hypotensive and urine Na high → pathologic salt wasting: switch to 0.9% NaCl boluses until perfusion restored, then hypotonic.",
        "Daily weight is the single best volume compass. Falling weight + rising urea + tachycardia = under-replacement.",
      ]},
      { t: "tip", k: "gold", title: "Gold line", v: "“POD is urea-driven first, salt-driven later. Replace the deficit, not the diuresis. Pathologic POD is diagnosed only after the patient is euvolaemic and still polyuric.”" },
      { t: "h", v: "Prevention" },
      { t: "ul", v: [
        "Staged decompression in chronic massive retention is not evidence-based; a single gentle catheter is standard. The ‘clamping’ ritual is obsolete.",
        "Identify high-risk patients before TURP/PCN: urea, oedema, solitary kidney.",
        "Avoid overzealous free water in the anuric phase (hyponatraemia) and overzealous saline after relief (perpetuated POD).",
      ]},
    ],
  },
  {
    id: "obstructive-uropathy",
    topicId: "basics",
    title: "Obstructive uropathy — causes, evaluation, treatment",
    highYield: true,
    gold: false,
    tags: ["obstruction", "hydronephrosis", "CKD"],
    exams: [
      { session: "Jun", year: 2016, marks: "2+4+4", stem: "Enumerate the causes of obstructive uropathy. Evaluation and treatment of patients with obstructive uropathy." },
    ],
    related: ["pod", "pujo", "puv"],
    references: ["Campbell-Walsh-Wein, Urinary Tract Obstruction", "EAU Urolithiasis / Upper Urinary Tract Obstruction"],
    answer: [
      { t: "h", v: "Causes — classify, do not dump a list" },
      { t: "tbl", h: ["Level", "Intrinsic", "Extrinsic"], r: [
        ["PUJ / kidney", "PUJO, stone, tumour, sloughed papilla, clot", "Crossing vessel, retrocaval ureter, retroperitoneal fibrosis, LN, AAA"],
        ["Ureter", "Stone, stricture (TB, iatrogenic), TCC, congenital megaureter", "Cervix/prostate cancer, pregnancy, endometriosis, Crohn, iliac aneurysm"],
        ["Bladder outlet", "BPH, stricture, PUV, stone, tumour, detrusor–sphincter dyssynergia", "Pelvic mass, uterine prolapse, faecal impaction"],
      ]},
      { t: "h", v: "Evaluation" },
      { t: "ul", v: [
        "Life first: sepsis + obstruction = emergency decompression (PCN or stent) before fancy imaging.",
        "Labs: CBC, creatinine/eGFR, K, VBG, cultures, PSA if relevant, urine cytology if tumour suspected.",
        "US: hydronephrosis, residual, stones, prostate. Normal US does not exclude early obstruction (forniceal rupture, dehydration, retroperitoneal fibrosis with non-dilated obstruction).",
        "NCCT KUB: gold standard for stone. CECT urography for tumour/stricture.",
        "Diuretic renogram (MAG3 + F−15/F+10): obstruction vs dilated non-obstructed; split function.",
        "Whitaker test: rarely, equivocal renogram.",
        "Cystoscopy + RGP / ureteroscopy: define level and biopsy.",
      ]},
      { t: "h", v: "Treatment principles" },
      { t: "ul", n: true, v: [
        "Resuscitate: ABC, treat hyperkalaemia, infective source control.",
        "Decompress the threatened kidney (stent vs PCN — PCN if sepsis, unbridgeable obstruction, or planned PCNL).",
        "Treat the cause (stone, prostate, stricture, malignancy, RPF steroids/stents).",
        "Nephron salvage: pyeloplasty, uretero-ureterostomy, Boari, ileal ureter, diversion.",
        "If split function <10–15% and contralateral kidney healthy: nephrectomy after confirming unrecoverable function (delayed MAG3).",
      ]},
    ],
  },
  {
    id: "micturition-neuro",
    topicId: "basics",
    title: "Functional neuroanatomy of micturition",
    highYield: true,
    gold: true,
    tags: ["neurourology", "micturition", "anatomy"],
    exams: [
      { session: "Jun", year: 2018, marks: "10", stem: "Functional neuro anatomy of micturition." },
    ],
    related: ["micturition-phys", "ngb-sci", "oab"],
    references: ["de Groat WC. Nat Rev Neurosci / Campbell Neurourology", "ICS Standardisation", "Wein & Barrett"],
    answer: [
      { t: "tip", k: "exam", v: "Draw: cortex → PMC (Barrington, pontine micturition centre) → spinal cord (T10–L2 sympathetic, S2–4 parasympathetic and pudendal) → ganglia → detrusor/sphincter. Label Onuf's nucleus." },
      { t: "h", v: "Peripheral innervation" },
      { t: "tbl", h: ["System", "Origin", "Nerve", "Receptor / effector", "Function"], r: [
        ["Parasympathetic", "S2–S4 intermediolateral", "Pelvic nerves", "M3 (detrusor) > M2", "Emptying contraction"],
        ["Sympathetic", "T10–L2", "Hypogastric", "β3 detrusor relax; α1 bladder neck", "Storage"],
        ["Somatic", "Onuf nucleus S2–4", "Pudendal", "Nicotinic striated sphincter", "Guarding reflex"],
        ["Sensory", "Aδ (fullness), C (noxious)", "Pelvic / pudendal / hypogastric", "TRPV1, P2X3", "Urge / pain"],
      ]},
      { t: "h", v: "Central organisation" },
      { t: "ul", v: [
        "Periaqueductal grey (PAG) is the switchboard: receives bladder afferents, gates PMC when the cortex permits.",
        "Pontine micturition centre (M-region, Barrington): coordinated detrusor contraction + sphincter relaxation via GABA/glycine to Onuf and glutamate to sacral parasympathetic nucleus.",
        "Pontine storage centre (L-region): ongoing sphincter excitation during filling.",
        "Cerebral cortex (medial prefrontal, anterior cingulate, insula): social permission, awareness of desire. Lesions (stroke, NPH, frontal tumour) → urge incontinence with preserved coordination.",
        "Cerebellum and basal ganglia (Parkinson): timing and suppression of unwanted contractions.",
      ]},
      { t: "h", v: "Two reflexes to name" },
      { t: "ul", v: [
        "Guarding reflex: increasing sphincter EMG as bladder fills (spinobulbospinal).",
        "Spinobulbospinal micturition reflex: once PMC fires, sphincter silent period precedes detrusor rise by ~1–2 s — this latency is lost in DSD.",
      ]},
      { t: "dia", id: "micturition", cap: "Storage vs voiding switch (PAG–PMC)" },
      { t: "tip", k: "gold", v: "Suprapontine lesion = urge + coordinated sphincter. Infrapontine / suprasacral cord = DSD + high pressure. Sacral / cauda = acontractile detrusor ± open sphincter." },
    ],
  },
  {
    id: "hyponatremia",
    topicId: "basics",
    title: "Hyponatraemia in urological practice",
    highYield: true,
    gold: true,
    tags: ["electrolyte", "TURP syndrome", "fluids"],
    exams: [
      { session: "Jun", year: 2021, marks: "3+3+4", stem: "Enumerate the causes of Hyponatremia. Describe clinical features and outline the management." },
      { session: "Jun", year: 2016, marks: "1+2+3+4", stem: "Define Hyponatremia. Various types, clinical manifestation and treatment of Hyponatremia." },
      { session: "Dec", year: 2017, marks: "5+5", stem: "What are the causes of Hyponatremia in Urological practice? How is it managed?" },
    ],
    related: ["pod", "turp-syndrome", "neobladder-metabolic"],
    references: ["European Hyponatraemia Guidelines 2014", "Campbell TURP / Metabolic complications of diversion", "Adrogué–Madias NEJM"],
    answer: [
      { t: "p", v: "Hyponatraemia = serum Na <135 mEq/L. Severe <125; symptomatic risk rises steeply <120. Always interpret with osmolality and volume status." },
      { t: "h", v: "Urologic causes — the list they want" },
      { t: "tbl", h: ["Setting", "Mechanism", "Typical picture"], r: [
        ["TURP / HoLEP / bipolar (less) syndrome", "Absorption of hypotonic irrigant (1.5% glycine, 3% sorbitol) via opened venous sinuses", "Intra/early post-op confusion, visual, bradycardia, HTN then collapse"],
        ["Glycine toxicity", "Glycine → ammonia + serine; NMDA; transient blindness", "Visual + Na fall may be modest"],
        ["Ileal conduit / neobladder", "Na/HCO3 loss across ileal mucosa; ADH from hypovolaemia", "Hyperchloraemic metabolic acidosis + hyponatraemia"],
        ["POD / salt wasting", "Urinary Na loss after decompression", "High UO, high urine Na"],
        ["SIADH", "Pain, nausea, morphine, small-cell / pulmonary mets, Ca prostate rare", "Euvolaemic, high urine Na, high Uosm"],
        ["Adrenal failure / ketoconazole / mitotane / abiraterone (if no prednisone)", "Mineralocorticoid lack", "Hyperkalaemia + hyponatraemia + hypotension"],
        ["Water intoxication / psychogenic polydipsia / hypotonic IV fluids", "Free water excess", "Low Uosm"],
        ["Thiazides, SSRIs, cyclophosphamide (rare in GU chemo)", "Renal Na loss / SIADH", "Drug history"],
      ]},
      { t: "h", v: "Clinical features" },
      { t: "ul", v: [
        "Mild: nausea, headache, malaise, anorexia.",
        "Moderate: confusion, vomiting, muscle cramps, gait, falls.",
        "Severe: seizures, respiratory arrest, herniation — acute (<48 h) more dangerous than chronic.",
        "TURP-specific: hypertension, reflex bradycardia, wide QRS, visual loss (glycine), hypothermia, coagulopathy.",
      ]},
      { t: "h", v: "Work-up in 4 numbers" },
      { t: "ul", v: ["Serum osmolality (hypotonic vs iso/hyper from glycine/mannitol/hyperglycaemia)", "Urine osmolality (ADH activity)", "Urine Na (renal vs extra-renal loss)", "Volume exam + cortisol/TSH if euvolaemic"] },
      { t: "h", v: "Management" },
      { t: "ul", v: [
        "Severe symptoms (seizure/coma): 100–150 mL 3% hypertonic saline over 10–20 min; repeat ×2 if needed. Target +5 mEq rise to stop symptoms.",
        "Thereafter: 4–6 (max 8) mEq/L in 24 h if chronic; 10–12 if truly acute TURP. Osmotic demyelination if overcorrected in alcoholics, malnourished, liver disease.",
        "TURP: stop resection, frusemide if overloaded, hypertonic saline if Na <120 or neuro symptoms, ITU, check ammonia. Bipolar TURP in saline largely prevents classic TURP syndrome but volume overload still occurs.",
        "Hypovolaemic: 0.9% NaCl. Hypervolaemic (HF, nephrosis): fluid restrict + loop diuretic. SIADH: fluid restrict 800–1000 mL, urea/vaptan/demeclocycline if persistent, treat cause.",
        "Neobladder: salt + bicarbonate, catheterise residual, treat acidosis.",
      ]},
      { t: "tip", k: "gold", v: "Quote Adrogué–Madias: change in Na ≈ (infusate Na + infusate K − serum Na) / (TBW + 1). TBW = 0.6 × wt (men)." },
    ],
  },
  {
    id: "hypercalcemia",
    topicId: "basics",
    title: "Hypercalcaemia — manifestations and medical treatment",
    highYield: true,
    gold: false,
    tags: ["electrolyte", "RCC", "PTHrP", "bones"],
    exams: [
      { session: "Jun", year: 2017, marks: "4+6", stem: "What are the clinical manifestations of hypercalcemia? What are the medical measures to treat hypercalcemia?" },
    ],
    related: ["rcc-paraneoplastic", "stones-hyperpara", "bisphosphonates"],
    references: ["Campbell RCC paraneoplastic", "Endocrine Society / AACE hypercalcaemia", "Weinman — bones, stones, groans, psychiatric overtones"],
    answer: [
      { t: "p", v: "Corrected Ca = measured + 0.8 × (4 − albumin). Ionised Ca is gold in critically ill. Severe: >14 mg/dL (3.5 mmol/L) or symptomatic." },
      { t: "h", v: "Manifestations" },
      { t: "ul", v: [
        "Bones: osteitis fibrosa, pain, pathologic fracture (1° HPT / lytic mets).",
        "Stones: calcium phosphate / oxalate, nephrocalcinosis, polyuria (nephrogenic DI).",
        "Groans: constipation, PUD, pancreatitis, anorexia.",
        "Psychiatric overtones: depression, confusion, coma.",
        "Cardiac: short QT, bradycardia, digitalis sensitivity.",
        "Urologic paraneoplastic: PTHrP in clear-cell RCC (also bladder TCC, NHL); osteolytic Ca prostate / RCC mets; 1,25-(OH)2D in some lymphomas.",
      ]},
      { t: "h", v: "Medical measures (write as a ladder)" },
      { t: "ul", n: true, v: [
        "Volume: 0.9% NaCl 200–300 mL/h (after assessing heart) — calciuresis needs GFR.",
        "Loop diuretic only after euvolaemia (frusemide 20–40 mg) — not first-line in 2020s answers unless overload.",
        "IV bisphosphonate: zoledronate 4 mg over 15 min (onset 24–48 h, lasts weeks). Reduce dose in GFR <30; risk of jaw osteonecrosis / ATN.",
        "Calcitonin 4 IU/kg SC q12h: onset 2–4 h, tachyphylaxis by 48 h — bridge until bisphosphonate works.",
        "Denosumab 120 mg SC if bisphosphonate contraindicated (CKD) — RANKL antibody.",
        "Steroids: granulomatous disease, myeloma, 1,25-D mediated, some lymphomas.",
        "Dialysis (low-calcium bath) if oliguric CKD, severe neuro, Ca >18.",
        "Cinacalcet for parathyroid carcinoma / inoperable HPT; treat the tumour (nephrectomy for PTHrP-RCC often aborts the paraneoplastic Ca).",
      ]},
    ],
  },
  {
    id: "gfr",
    topicId: "basics",
    title: "GFR — definition, methods, donor evaluation",
    highYield: true,
    gold: true,
    tags: ["GFR", "donor", "CKD", "nuclear"],
    exams: [
      { session: "Dec", year: 2021, marks: "3+3+4", stem: "Define glomerular filtration rate. Enumerate clinical methods of estimation of GFR. Briefly describe advantages and fallacies of each." },
      { session: "Dec", year: 2015, marks: "10", stem: "Mention the different methods of GFR estimation and their importance in the urological practice." },
      { session: "Jun", year: 2020, marks: "10", stem: "Describe methods to estimate GFR in prospective renal donor with advantages and limitations of each." },
    ],
    related: ["ckd", "donor-eval", "contrast-cin"],
    references: ["KDIGO CKD 2024", "NICE / British Transplantation Society living-donor guidelines", "Campbell Donor evaluation"],
    answer: [
      { t: "p", v: "GFR is the volume of plasma filtered by glomeruli per unit time (normal ~120–130 mL/min/1.73 m² in young adults; falls ~1 mL/min/year after 40). It is the best global index of excretory function." },
      { t: "tbl", c: "Methods — learn advantages and fallacies cold", h: ["Method", "What it measures", "Advantage", "Fallacy / limit"], r: [
        ["Serum creatinine", "Muscle-derived marker", "Cheap, universal", "Rises only after ~50% nephron loss; muscle mass, diet, drugs (trimethoprim, cimetidine, cobicistat)"],
        ["Cockcroft–Gault", "eCrCl", "Drug dosing heritage", "Uses weight; overestimates in obese; not indexed to 1.73 m²"],
        ["CKD-EPI creatinine (2021 race-free)", "eGFR", "Best creatinine equation; staging CKD", "Inaccurate if unusual muscle, amputation, pregnancy, AKI, vegetarian, high GFR (donors)"],
        ["CKD-EPI cystatin C / combined", "eGFR", "Less muscle-dependent; better in elderly / low muscle", "Cost; thyroid, steroids, inflammation affect cystatin"],
        ["24-h creatinine clearance", "Measured CrCl", "No equation assumptions", "Overestimates GFR (tubular Cr secretion); incomplete collection"],
        ["DTPA / 51Cr-EDTA plasma slope", "Measured GFR", "Reference for donors in many units", "Extracellular tracers; underestimate if oedema; 2–4 blood samples; radiation"],
        ["Iohexol / inulin clearance", "True GFR", "Gold standard (inulin)", "Inulin unavailable; iohexol is the modern reference"],
        ["MAG3 / DMSA split function", "Relative, not absolute GFR", "Surgical laterality, PUJO, donor side", "MAG3 is ERPF not GFR; need a plasma GFR to convert to absolute split"],
      ]},
      { t: "h", v: "Urologic importance" },
      { t: "ul", v: [
        "Oncology: cisplatin / IO eligibility, nephron-sparing decision (eGFR, split, complexity).",
        "Endourology: contrast, PCNL risk in CKD, obstruction vs CKD on MAG3.",
        "BPH with obstructive uropathy: recoverability after catheter.",
        "Living donor: KDIGO — measured GFR preferred when eGFR is borderline (usually <90 or >70 depending on age). Absolute mGFR ≥80–90 mL/min typically acceptable in young donors; age-adjusted thresholds in older donors. Always pair with split function (DMSA/MAG3) to choose laterality (leave the better kidney).",
        "CKD staging (KDIGO G1–G5 × A1–A3 albuminuria) for prognosis after nephrectomy.",
      ]},
      { t: "tip", k: "gold", v: "Donor answer structure: (1) eGFR CKD-EPI as screen (2) measured GFR (iohexol/51Cr-EDTA/DTPA) if eGFR <90 or age >50 (3) split function (4) never donate if predicted post-donation GFR leaves the donor in G3b–G4." },
    ],
  },
  {
    id: "urine-concentration",
    topicId: "basics",
    title: "Renal mechanism of urine concentration",
    highYield: false,
    gold: false,
    tags: ["physiology", "ADH", "countercurrent"],
    exams: [
      { session: "Jun", year: 2017, marks: "10", stem: "Explain the renal mechanism for concentration of urine." },
    ],
    related: ["pod", "gfr"],
    references: ["Boron & Boulpaep / Guyton", "Campbell Physiology of the urinary tract"],
    answer: [
      { t: "p", v: "Maximum Uosm in man ~1200 mOsm/kg; minimum ~50. Concentration requires (i) a hypertonic medullary interstitium and (ii) ADH-dependent water permeability of the collecting duct." },
      { t: "h", v: "Countercurrent multiplier (loop of Henle)" },
      { t: "ul", v: [
        "Thin descending limb: AQP1, impermeable to salt → water exits into hypertonic medulla, tubular fluid concentrates.",
        "Thin ascending limb: passive NaCl efflux, impermeable to water.",
        "Thick ascending limb (diluting segment): NKCC2 actively pumps NaK2Cl; impermeable to water → tubular fluid hypotonic (‘single effect’ of 200 mOsm at each level).",
        "Hairpin geometry multiplies the single effect to 1200 mOsm at the papilla. Urea recycling (UT-A1/A3 in inner medullary CD, UT-A2 in thin descending) contributes ~50% of inner medullary tonicity.",
      ]},
      { t: "h", v: "Countercurrent exchanger (vasa recta)" },
      { t: "p", v: "Slow hairpin blood flow prevents washout of the gradient. Trap urea and NaCl in the medulla." },
      { t: "h", v: "ADH (vasopressin) action" },
      { t: "ul", v: [
        "V2 receptor (basolateral principal cell) → Gs → cAMP → PKA → AQP2 insertion into apical membrane.",
        "Also increases UT-A1 urea permeability and NKCC2 activity (long-term).",
        "Without ADH: CD impermeable to water → dilute urine (central or nephrogenic DI).",
      ]},
      { t: "tip", k: "exam", v: "Urologic relevance: obstruction, lithium, hypercalcaemia, hypokalaemia, loop diuretics, CKD — all flatten the gradient → isosthenuria and polyuria (links to POD answers)." },
    ],
  },
  {
    id: "bt",
    topicId: "basics",
    title: "Blood transfusion — indications, drawbacks, complications",
    highYield: false,
    gold: false,
    tags: ["transfusion", "perioperative"],
    exams: [
      { session: "Jun", year: 2017, marks: "4+6", stem: "Enumerate indications of blood transfusion (BT). What are the drawbacks and complications of BT?" },
    ],
    related: ["eras", "pcnl-bleeding"],
    references: ["AABB / NICE NG24", "TRICC / TRISS restrictive transfusion trials", "Campbell peri-operative care"],
    answer: [
      { t: "h", v: "Indications (restrictive era)" },
      { t: "ul", v: [
        "Hb <7 g/dL in haemodynamically stable adults (TRICC).",
        "Hb <8 in cardiac ischaemia / significant CAD.",
        "Acute haemorrhage with shock not responding to crystalloid — transfuse for perfusion, not a number.",
        "Symptomatic anaemia (ischaemic ECG, failure, rest dyspnoea) irrespective of exact Hb.",
        "Massive transfusion protocol: 1:1:1 RBC:plasma:platelets in exsanguinating PCNL / trauma / ruptured angiomyolipoma.",
        "Exchange in sickle crisis, TTP (plasma) — rare in GU.",
      ]},
      { t: "h", v: "Drawbacks and complications — classify" },
      { t: "tbl", h: ["Category", "Examples", "Notes for urology"], r: [
        ["Immunologic acute", "ABO haemolysis, febrile non-haemolytic, TRALI, anaphylaxis (IgA)", "Check identity at TURP recovery; TRALI vs TACO"],
        ["Immunologic delayed", "Delayed haemolysis, alloimmunisation, TA-GvHD, HLA sensitisation", "Sensitisation ruins future transplant"],
        ["Infectious", "HBV, HCV, HIV, HTLV, CMV, bacteria, malaria, prions", "Nucleic-acid testing; bacterial risk highest with platelets"],
        ["Volume / metabolic", "TACO, hyperkalaemia, citrate hypocalcaemia, hypothermia, acidosis", "Massive transfusion in PCNL"],
        ["Storage lesion / quality", "Decreased 2,3-DPG, haemolysis", "Older units in massive bleed"],
        ["Oncologic / outcome", "Possible increase in RCC/bladder recurrence and infection (immunomodulation)", "Prefer cell salvage / restrictive / iron in elective cystectomy"],
      ]},
      { t: "tip", k: "gold", v: "Mention Patient Blood Management: treat iron, stop antiplatelets rationally, cell salvage in cystectomy, tranexamic acid (WOMAN/CRASH-2 logic; use in TURP/PN with caution for thrombosis)." },
    ],
  },
  {
    id: "pneumoperitoneum",
    topicId: "basics",
    title: "Physiologic effects of pneumoperitoneum",
    highYield: true,
    gold: true,
    tags: ["laparoscopy", "physiology", "anaesthesia"],
    exams: [
      { session: "Dec", year: 2018, marks: "10", stem: "Cardiovascular, respiratory, renal and Acid–Base metabolic effects of Pneumoperitoneum during laparoscopy." },
      { session: "Jun", year: 2016, marks: "5+5", stem: "Metabolic and physiologic effects of pneumoperitoneum in laparoscopy." },
      { session: "Dec", year: 2012, marks: "10", stem: "Describe physiological changes during creation of pneumoperitoneum (Laparoscopy)." },
    ],
    related: ["lap-nephrectomy", "eras"],
    references: ["Campbell Minimally Invasive Surgery", "Miller Anaesthesia — laparoscopy chapter", "EAU laparoscopy guidelines"],
    answer: [
      { t: "p", v: "Standard: CO₂ insufflation 10–15 mmHg. Effects scale with pressure, duration, head-up/head-down, and hypercarbia. Write four organ systems plus metabolic." },
      { t: "tbl", h: ["System", "Effect", "Mechanism", "Clinical"], r: [
        ["CVS", "↑ SVR, ↑ MAP, ↓ venous return, ↓ CO (variable)", "IAP compresses IVC; hypercarbia → sympathetic surge; reverse Trendelenburg worsens VR", "Caution in hypovolaemia, cardiomyopathy. Arrhythmia from hypercarbia / peritoneal stretch (vagal)."],
        ["Respiratory", "↓ compliance, ↑ airway pressure, cephalad diaphragm, V/Q mismatch, hypercarbia, ↓ FRC", "IAP + Trendelenburg (pelvic cases)", "ETCO2 lags PaCO2 in COPD. Subcutaneous emphysema, capnothorax, gas embolism (millwheel)."],
        ["Renal", "↓ RBF, ↓ GFR, oliguria, ↑ ADH/aldosterone/renin", "Direct compression + ↓ CO + neuroendocrine", "Intra-op oliguria is expected; do not drown the patient. Recovers after desufflation."],
        ["Splanchnic / hepatic", "↓ portal flow", "Compression", "Rarely clinically relevant at 12 mmHg"],
        ["Neuro / ICP", "↑ ICP, ↑ intraocular pressure", "Hypercarbia + impaired venous drainage", "Avoid in VP shunt / glaucoma for prolonged pelvic cases"],
        ["Metabolic / acid–base", "Respiratory acidosis from CO2 absorption; later metabolic acidosis if hypoperfusion", "Peritoneal absorption of CO2; dead space", "Increase minute ventilation 15–30%. Insufflation hypothermia."],
      ]},
      { t: "h", v: "Special events to mention" },
      { t: "ul", v: [
        "Gas embolism: sudden ETCO2 fall, mill-wheel murmur, head-down left-lateral, aspirate central line.",
        "Hypercarbia refractory: desufflate, resume low pressure, rule out subcutaneous CO2.",
        "Paediatric / obese / COPD: use lowest effective IAP (8–10 mmHg), helium rarely if hypercarbia intolerable (no diathermy with helium/hydrogen).",
      ]},
    ],
  },
  {
    id: "eras",
    topicId: "basics",
    title: "ERAS protocol in urology",
    highYield: true,
    gold: false,
    tags: ["ERAS", "perioperative", "cystectomy"],
    exams: [
      { session: "Dec", year: 2016, marks: "5+5", stem: "Principles of Enhanced recovery after surgery (ERAS) Protocol. Cryopreservation of sperm: Indications & techniques." },
    ],
    related: ["sperm-cryo", "cystectomy-diversion"],
    references: ["ERAS Society cystectomy guidelines (Cerantola et al. Clin Nutr 2013; updates)", "EAU MIBC peri-operative"],
    answer: [
      { t: "p", v: "ERAS is a multimodal, evidence-based peri-operative pathway that reduces surgical stress, ileus and LOS. Best data in radical cystectomy; principles apply to PN, RALP, RPLND." },
      { t: "tbl", h: ["Phase", "Intervention", "Why"], r: [
        ["Pre-op", "Counselling, smoking/alcohol stop, anaemia/iron, nutrition (NRS-2002), no prolonged fast (solids 6 h, clears 2 h), carbohydrate drink, avoid mechanical bowel prep, VTE risk, stoma siting", "Glycogen, insulin resistance, microbiome"],
        ["Intra-op", "Thoracic epidural or TAP/rectus, opioid-sparing, goal-directed fluid, prevent hypothermia, mini-invasive where appropriate, no routine NG, avoid drains if possible", "Sympathetic block, ileus"],
        ["Post-op", "Early oral (chewing gum, diet POD0–1), mobilisation POD0, omit or early remove NG, remove drain/catheter by protocol, nausea prophylaxis, glycemic control, VTE 4 weeks after pelvic cancer surgery", "Atropine/opioid ileus is the enemy"],
      ]},
      { t: "tip", k: "exam", v: "Quote cystectomy ERAS: LOS reduction ~2–5 days, fewer complications in meta-analyses, no increase in readmission when the whole bundle (not cherry-picked items) is used." },
    ],
  },
  {
    id: "immuno-checkpoint-urothelial",
    topicId: "basics",
    title: "Immune checkpoint targeting in urothelial malignancy",
    highYield: true,
    gold: true,
    tags: ["IO", "bladder", "PD-1", "Pembrolizumab"],
    exams: [
      { session: "Dec", year: 2019, marks: "5+5", stem: "Discuss mechanism of immune check point targeting for urothelial malignancy. Discuss current role of drugs used for immune check point targeting for urothelial malignancy." },
    ],
    related: ["nmibc-bcg", "mibc-nac", "rcc-io"],
    references: ["KEYNOTE-045, KEYNOTE-052, IMvigor130, CheckMate-901, EV-302", "EAU MIBC 2024/25", "Campbell Urothelial carcinoma systemic therapy"],
    answer: [
      { t: "h", v: "Mechanism" },
      { t: "p", v: "T-cell activation needs TCR–MHC plus co-stimulation (CD28–B7). Tumours hijack inhibitory checkpoints:" },
      { t: "ul", v: [
        "CTLA-4 (ipilimumab): competes with CD28 for B7 at the priming synapse in lymph nodes.",
        "PD-1 (pembrolizumab, nivolumab) on T cells / PD-L1 (atezolizumab, avelumab, durvalumab) on tumour and myeloid cells: shuts down effector T cells in the peripheral tumour bed.",
        "Blocking the axis restores cytotoxic CD8 activity. Urothelial carcinoma is mutagenic (tobacco, ERCC2, APOBEC) → high neoantigen load → IO-responsive.",
      ]},
      { t: "h", v: "Current roles (write the trial name)" },
      { t: "tbl", h: ["Setting", "Drug / trial", "Role"], r: [
        ["1L metastatic, cisplatin-eligible", "Enfortumab vedotin + pembrolizumab (EV-302) — new standard; gem-cis + nivo (CheckMate-901)", "EV+pembro OS 31.5 vs 16.1 mo; displaced platinum as default 1L in many guidelines"],
        ["1L cisplatin-ineligible", "EV+pembro; or carbo-gem then avelumab switch (JAVELIN Bladder 100) if no EV access", "Avelumab maintenance after platinum SD/PR — OS benefit"],
        ["2L after platinum", "Pembrolizumab (KEYNOTE-045) OS vs taxane", "Classic 10-mark answer; now often used earlier"],
        ["Adjuvant MIBC / UTUC ypT2–4 or pN+ after NAC, or pT3–4/N+ without NAC", "Nivolumab 1 y (CheckMate-274)", "DFS benefit; OS emerging"],
        ["BCG-unresponsive NMIBC (CIS ± Ta/T1)", "Pembrolizumab (KEYNOTE-057); nadofaragene; Anktiva (IL-15) — know names", "Bladder-sparing when RC declined"],
        ["PD-L1 testing", "CPS / TAP assays", "Less gatekeeping than in 2017; still used for some 1L IO-alone licences"],
      ]},
      { t: "tip", k: "warn", title: "Toxicities to list", v: "Immune-related: dermatitis, colitis, hepatitis, pneumonitis, thyroid, hypophysitis, adrenal, T1DM, myocarditis, nephritis. Treat with hold + steroids 1–2 mg/kg; infliximab for refractory colitis. Never start IO without a cortisol plan." },
    ],
  },
  {
    id: "angiogenesis",
    topicId: "basics",
    title: "Tumour angiogenesis — activators and inhibitors",
    highYield: true,
    gold: false,
    tags: ["VEGF", "RCC", "VHL"],
    exams: [
      { session: "Jun", year: 2016, marks: "1+(4+5)", stem: "Define angiogenesis. What are the activators and inhibitors of tumour angiogenesis?" },
      { session: "Jun", year: 2019, marks: "2+4+4", stem: "Define angiogenesis. Specify the activators and inhibitors of tumour angiogenesis used in urological diseases. Mention important adverse effects." },
    ],
    related: ["rcc-targeted", "vhl"],
    references: ["Folkman J. NEJM 1971", "Campbell RCC molecular biology", "Escudier / Motzer reviews"],
    answer: [
      { t: "p", v: "Angiogenesis is the sprouting of new capillaries from existing vessels. Tumours cannot grow beyond ~1–2 mm without it (Folkman). The angiogenic switch is the local imbalance of activators over inhibitors." },
      { t: "tbl", h: ["Activators", "Inhibitors"], r: [
        ["VEGF-A (VEGFR-2), VEGF-C/D (lymphangiogenesis)", "Thrombospondin-1, angiostatin, endostatin"],
        ["FGF-1/2, PDGF, EGF, TGF-β (context), angiopoietin-2 + VEGF", "Angiopoietin-1–Tie2 (stabilisation), TIMPs"],
        ["Hypoxia → HIF-1α → VEGF (VHL loss in ccRCC)", "Interferon-α (historic RCC)"],
        ["Integrins αvβ3, MMPs (matrix invasion)", "Tissue inhibitors; endogenous fragments of collagen XVIII (endostatin)"],
      ]},
      { t: "h", v: "Urologic drugs" },
      { t: "ul", v: [
        "TKIs vs VEGFR: sunitinib, pazopanib, cabozantinib (also MET/AXL), axitinib, tivozanib, lenvatinib (+ everolimus).",
        "VEGF ligand antibody: bevacizumab (with IFN historically; with atezolizumab in IMmotion151).",
        "mTOR (HIF translation): everolimus, temsirolimus.",
        "AE: hypertension, proteinuria, wound dehiscence (delay elective surgery 4–6 wk), haemorrhage, hypothyroidism, HFS, diarrhoea, QTc, fistula, PRES. mTOR: stomatitis, hyperglycaemia, pneumonitis, poor wound healing.",
      ]},
    ],
  },
  {
    id: "car-t",
    topicId: "basics",
    title: "CAR-T cells in cancer",
    highYield: false,
    gold: false,
    tags: ["immunotherapy", "cellular"],
    exams: [
      { session: "Dec", year: 2017, marks: "6+4", stem: "What are CAR-T cells? How are they used in treatment of cancers?" },
    ],
    related: ["immuno-checkpoint-urothelial"],
    references: ["June CH. NEJM CAR-T reviews", "Early GU trials: PSMA CAR-T, NKG2D"],
    answer: [
      { t: "p", v: "Chimeric antigen receptor T cells are autologous T cells genetically engineered to express a synthetic receptor: extracellular antibody-derived scFv + hinge + transmembrane + intracellular signalling (CD3ζ ± co-stim CD28 or 4-1BB). They recognise surface antigen independently of MHC." },
      { t: "ul", n: true, v: [
        "Leukapheresis → viral (lentiviral) transduction → expansion → lymphodepleting chemo (flu/cy) → infusion.",
        "Licensed: CD19 (ALL, NHL, MCL) and BCMA (myeloma) — axi-cel, tisa-cel, cilta-cel.",
        "GU: experimental PSMA CAR-T in mCRPC, carbonic anhydrase IX in ccRCC (on-target off-tumour bile-duct toxicity historically). Solid-tumour barriers: antigen heterogeneity, TME, trafficking.",
        "Toxicities: CRS (IL-6; tocilizumab), ICANS, cytopenias, B-cell aplasia / hypogammaglobulinaemia, infection.",
      ]},
    ],
  },
  {
    id: "mrna-ctc",
    topicId: "basics",
    title: "mRNA and circulating tumour cells in urology",
    highYield: false,
    gold: false,
    tags: ["biomarker", "liquid biopsy"],
    exams: [
      { session: "Dec", year: 2017, marks: "5+5", stem: "What are m-RNAs? What is their role in urology?" },
      { session: "Jun", year: 2015, marks: "10", stem: "Circulating cancer cells." },
    ],
    related: ["liquid-biopsy", "pca-markers"],
    references: ["CellSearch FDA CTC", "Decipher / Prolaris / Oncotype GPS", "EAU PCa biomarkers"],
    answer: [
      { t: "h", v: "mRNA" },
      { t: "p", v: "Messenger RNA is the transcribed coding RNA translated into protein. In urology it is used as (i) a biomarker (tissue or urine) and (ii) a therapeutic platform (mRNA vaccines)." },
      { t: "ul", v: [
        "Urine PCA3 (DD3) — prostate-specific non-coding RNA, FDA score for repeat biopsy.",
        "SelectMDx (HOXC6, DLX1 mRNA), ExoDx (PCA3, ERG, SPDEF exosomal RNA), TMPRSS2–ERG fusion transcripts.",
        "Tissue genomic classifiers (Decipher — 22-gene RNA; GPS; Prolaris cell-cycle) for adjuvant RT after RP.",
        "BCG response / bladder: Cxbladder (CDC2, HOXA13, MDK, IGFBP5, CXCR2).",
        "Therapeutic: personalised neoantigen mRNA vaccines in trials (RCC KEYNOTE-603 / IMAGINE); COVID-era platform.",
      ]},
      { t: "h", v: "Circulating tumour cells (CTCs)" },
      { t: "p", v: "Cells shed into blood from solid tumours. Captured by EpCAM-based immunomagnetic assays (CellSearch — FDA cleared in mCRPC: ≥5 CTC/7.5 mL poor prognosis) or size/microfluidic chips (Parsortix)." },
      { t: "ul", v: [
        "Prognosis in mCRPC, mRCC, urothelial carcinoma — dynamic fall with therapy is favourable.",
        "AR-V7 splice in CTCs predicted poor ABI/ENZA response (Antonarakis) — not routinely used after PROPHECY mixed data.",
        "Limits: epithelial–mesenchymal transition loses EpCAM; rare-event statistics; cost. ctDNA (liquid biopsy of mutant DNA) has largely overtaken CTC counts for genotyping.",
      ]},
    ],
  },
  {
    id: "psma-lu",
    topicId: "basics",
    title: "Ga-PSMA-PET-CT and ¹⁷⁷Lu-PSMA therapy",
    highYield: true,
    gold: true,
    tags: ["PSMA", "theranostics", "prostate"],
    exams: [
      { session: "Jun", year: 2021, marks: "5+5", stem: "Ga-PSMA-PET-CT. Lu-therapy." },
    ],
    related: ["pca-imaging", "crpc"],
    references: ["EAU PCa imaging", "proPSMA (Hofman Lancet 2020)", "VISION (Sartor NEJM 2021)", "PSMAfore, TheraP"],
    answer: [
      { t: "h", v: "Ga-PSMA-PET-CT" },
      { t: "p", v: "Prostate-specific membrane antigen (FOLH1, glutamate carboxypeptidase II) is a transmembrane enzyme massively overexpressed on prostate cancer cells (and neovascular endothelium of other tumours). ⁶⁸Ga-PSMA-11 or ¹⁸F-DCFPyL / ¹⁸F-PSMA-1007 bind the extracellular domain; PET detects disease at PSA levels far below bone-scan/CT sensitivity." },
      { t: "ul", v: [
        "Indications: (1) staging high-risk / unfavourable intermediate before treatment (proPSMA — 27% accuracy gain vs conventional), (2) biochemical recurrence (EAU: PSA ≥0.2 after RP; any PSA rise after RT), (3) select patients for metastasis-directed therapy, (4) confirm PSMA-avidity before Lu therapy.",
        "Physiologic uptake: lacrimal, salivary, liver, spleen, kidney, small bowel, ganglia, bladder (¹¹C less bladder). ¹⁸F-1007 less urinary excretion — better for fossa recurrence.",
        "Pitfalls: ganglia vs nodes, rib fractures, sarcoid, RCC/TCC/thyroid can be PSMA+, neuroendocrine PCa is PSMA-negative (use FDG).",
      ]},
      { t: "h", v: "¹⁷⁷Lu-PSMA radioligand therapy" },
      { t: "p", v: "β-emitter lutetium-177 chelated to PSMA-617 (Pluvicto). Cross-fire of ~1 mm kills neighbouring cells. Typical: 7.4 GBq q6 wk × 4–6." },
      { t: "ul", v: [
        "VISION: mCRPC after ARPI + taxane; rPFS 8.7 vs 3.4 mo, OS 15.3 vs 11.3. PSMAfore: pre-taxane after ARPI.",
        "TheraP: vs cabazitaxel — higher PSA50, less toxicity.",
        "Eligibility: PSMA-positive lesions, no PSMA-neg / FDG-pos mismatch.",
        "Toxicity: xerostomia, fatigue, myelosuppression, renal (tubular), rare penthode of dry eye. Nephroprotective hydration; salivary ice packs limited evidence.",
        "²²⁵Ac-PSMA (α) — salvage, more xerostomia.",
      ]},
    ],
  },
];
