import type { Master } from "../types";

export const bladder: Master[] = [
  {
    id: "bladder-embryology",
    topicId: "bladder",
    title: "Embryology of the urinary bladder",
    highYield: false,
    gold: false,
    tags: ["embryology", "cloaca", "urogenital sinus", "urachus"],
    exams: [
      { session: "Dec", year: 2011, marks: "10", stem: "Describe the embryology of the urinary bladder." },
    ],
    related: ["urachus", "exstrophy-adult", "urethral-dev-flaps"],
    references: ["Campbell-Walsh-Wein, Embryology of the GU tract", "Hinman Atlas", "Moore Clinically Oriented Embryology"],
    answer: [
      { t: "p", v: "The bladder is an endodermal organ with a trigone of mixed mesodermal contribution, derived from the cloaca after partitioning by the urorectal septum, and connected to the allantois via the urachus." },
      { t: "ul", n: true, v: [
        "Week 3–4: cloaca is the common endodermal chamber receiving allantois (ventral) and hindgut (dorsal), closed by the cloacal membrane.",
        "Urorectal septum (Tourneux fold + Rathke plicae) divides cloaca into ventral urogenital sinus and dorsal anorectal canal (~week 6–7). Failure → persistent cloaca / anorectal malformation.",
        "UG sinus cranial (vesical) part + surrounding splanchnic mesoderm = bladder. The allantois involutes to urachus → median umbilical ligament.",
        "Caudal UG sinus: pelvic part → prostatic / membranous urethra (male) or entire urethra (female); phallic part → penile urethra / vestibule.",
        "Trigone: common view is absorption of the Wolffian (mesonephric) ducts into the posterior wall, bringing the ureteric orifices; the trigone mesenchyme is mesodermal. Ureteric budding from Wolffian duct (Weigert–Meyer if duplex).",
        "Muscle: detrusor from splanchnic mesoderm; urothelium from endoderm (trigone epithelium debated).",
        "Ascent of the bladder out of the pelvis in childhood; urachus obliterates by late fetal life.",
        "Bladder plate / cloacal membrane rupture too early → bladder exstrophy–epispadias complex (see dedicated answer).",
      ]},
      { t: "tip", k: "exam", v: "Draw cloaca → urorectal septum → UG sinus + rectum; label allantois/urachus, Wolffian ducts, ureteric buds, Müllerian tubercle." },
    ],
  },
  {
    id: "urachus",
    topicId: "bladder",
    title: "Urachus — embryology, anomalies and management",
    highYield: true,
    gold: false,
    tags: ["urachus", "patent urachus", "urachal cyst", "adenocarcinoma"],
    exams: [
      { session: "Jun", year: 2019, marks: "3+2+5", stem: "Describe embryology of urachus, mention its various anomalies and briefly outline their management." },
    ],
    related: ["bladder-embryology", "benign-bladder-masses"],
    references: ["Campbell Pediatric anomalies / Urachal carcinoma", "EAU Urothelial / rare tumours"],
    answer: [
      { t: "p", v: "The urachus is the obliterated allantois, a three-layered tube (transitional epithelium, connective tissue, muscle) running in the extraperitoneal space of Retzius from the bladder dome to the umbilicus, becoming the median umbilical ligament." },
      { t: "tbl", h: ["Anomaly", "Anatomy", "Presentation", "Management"], r: [
        ["Patent urachus", "Complete lumen", "Neonatal urine from umbilicus, omphalitis", "Excise entire tract + cuff of bladder after infection settled; confirm no lower obstruction (PUV)"],
        ["Urachal cyst", "Both ends closed, mid-cyst", "Midline infra-umbilical mass, infection (Staph), rupture", "Antibiotics then delayed complete excision (lap / open); do not simple-drain as definitive"],
        ["Urachal sinus", "Umbilical end open", "Umbilical discharge", "Excise tract"],
        ["Vesicourachal diverticulum", "Bladder end open", "Stone, UTI, incidental; adult cancer risk", "Excise if symptomatic / atypical / not emptying"],
        ["Alternating sinus", "Cyst that drains either way", "Intermittent discharge", "Complete excision"],
      ]},
      { t: "ul", v: [
        "Diagnosis: US first in children; CT/MRI in adults if mass / cancer concern; sinogram / VUCG; cystoscopy for the dome pit.",
        "Adult urachal remnant + haematuria / calcified dome mass = urachal adenocarcinoma until excised. Staged as Sheldon or Mayo. Partial cystectomy with en-bloc umbilicus, posterior rectus fascia and remnant (extended partial) is the operation; mucinous histology, poor chemo-responsiveness vs urothelial Ca.",
        "Do not leave a cuff of remnant — that is the point of the operation.",
      ]},
      { t: "tip", k: "gold", v: "Infected urachal cyst: drain/antibiotics then complete excision including a bladder cuff. Adult dome adenocarcinoma is urachal until proven otherwise." },
    ],
  },
  {
    id: "bladder-nerve-ambuds",
    topicId: "bladder",
    title: "Nerve supply of the bladder, micturition reflex and ambulatory UDS",
    highYield: true,
    gold: false,
    tags: ["innervation", "micturition", "ambulatory UDS"],
    exams: [
      { session: "Jun", year: 2018, marks: "4+3+3", stem: "Describe the nerve supply of the bladder. Discuss the micturition reflex. Write a short note on Ambulatory Urodynamics." },
    ],
    related: ["micturition-neuro", "micturition-nocturia", "uds-boo-pfs", "oab"],
    references: ["de Groat WC", "ICS ambulatory urodynamic standards", "Campbell Neurourology"],
    answer: [
      { t: "tbl", h: ["System", "Origin", "Nerve", "Effector", "Function"], r: [
        ["Parasympathetic", "S2–S4 IML", "Pelvic splanchnic (nervi erigentes) via pelvic plexus", "M3 detrusor (M2 numerically more)", "Voiding contraction; afferent from bladder body"],
        ["Sympathetic", "T10–L2", "Hypogastric (presacral)", "β3 body relax; α1 BN / prostate contract", "Storage"],
        ["Somatic", "Onuf S2–4", "Pudendal", "Nicotinic rhabdosphincter, pelvic floor", "Guarding"],
        ["Afferent", "Aδ / C", "Pelvic > hypogastric / pudendal", "TRPV1, P2X3, distension / pain", "Urgency, pain, reflex"],
      ]},
      { t: "p", v: "Pelvic plexus sits lateral to rectum (danger in APR / radical hysterectomy / RPLND). Cavernous nerves run with the prostatic neurovascular bundle — relevant to RP, not bladder motor innervation per se." },
      { t: "h", v: "Micturition reflex" },
      { t: "ul", v: [
        "Storage: sympathetic + pudendal on, PMC off, guarding reflex (sphincter EMG rises with fill).",
        "At a socially permitted volume, PAG gates the PMC (Barrington). Sphincter silent period → BN opens → detrusor contraction (spinobulbospinal loop).",
        "Suprapontine lesions: urge, coordinated sphincter. Infrapontine suprasacral: NDO + DSD. Sacral: acontractile.",
      ]},
      { t: "h", v: "Ambulatory urodynamics" },
      { t: "ul", v: [
        "Natural-fill, portable Pves/Pabd (± EMG, leak sensor) over hours while the patient is mobile, with a diary of events.",
        "Indications: mismatch between conventional UDS and symptoms (especially suspected DO that was not captured), incontinence not demonstrated, neurogenic patients, research, before complex reconstruction.",
        "Advantages: physiologic fill, fewer artefacts of rapid fill / laboratory inhibition of DO, better correlation with leak.",
        "Disadvantages: labour, artefact (catheter kick, movement), interpretation experience, infection, cost. Not first-line. ICS has a standardisation report — mention quality control (cough tests, subtraction).",
      ]},
    ],
  },
  {
    id: "benign-bladder-masses",
    topicId: "bladder",
    title: "Benign tumours and masses of the urinary bladder",
    highYield: false,
    gold: false,
    tags: ["leiomyoma", "endometriosis", "nephrogenic adenoma", "pheochromocytoma"],
    exams: [
      { session: "Jun", year: 2017, marks: "10", stem: "Benign tumors (masses) of urinary bladder." },
    ],
    related: ["urachus", "tcc-risk-nac"],
    references: ["WHO GU tumours", "Campbell Bladder: non-urothelial and benign"],
    answer: [
      { t: "tbl", h: ["Lesion", "Key facts", "Management"], r: [
        ["Leiomyoma", "Commonest benign neoplasm; women; filling defect / LUTS", "Transurethral or partial cystectomy if large; confirm histology"],
        ["Nephrogenic adenoma", "Metaplasia after trauma/infection; not true neoplasm; can mimic TCC", "TUR; observe; associated with diversion / stones"],
        ["Cystitis cystica / glandularis (typical)", "Metaplasia; intestinal-type / pelvic lipomatosis association", "Treat cause; atypical intestinal type is a cancer-risk debate"],
        ["Inverted papilloma", "Endophytic urothelial; usually benign; 1–5% harbour Ca", "Complete TUR; surveillance because of coexistence"],
        ["Paraganglioma / bladder pheo", "Submucosal, zellballen, catecholamine spells on voiding / TUR", "Blockade then partial cystectomy; never biopsy blindly if suspected"],
        ["Haemangioma, neurofibroma, GIST, inflammatory myofibroblastic tumour", "Rare; IMT ALK+", "Complete but conservative excision"],
        ["Endometriosis", "Cyclical haematuria, premenopausal", "Hormonal ± partial cystectomy"],
        ["Amyloid, malakoplakia, TB, schisto, urachal cyst, diverticulum with stone, endometriosis, ectopic prostate", "Mass-like", "Cause-specific"],
        ["Papillary urothelial neoplasm of low malignant potential (PUNLMP)", "WHO/ISUP — borderline", "TUR + surveillance as NMIBC-lite"],
      ]},
      { t: "tip", k: "exam", v: "Lead with ‘most “benign masses” are metaplasias until the pathologist says neoplasm’. Mention bladder pheo so you do not resect untreated." },
    ],
  },
  {
    id: "tcc-risk-nac",
    topicId: "bladder",
    title: "TCC risk factors, NAC and radical TURBT",
    highYield: true,
    gold: true,
    tags: ["TCC", "NAC", "ddMVAC", "radical TURBT", "MIBC"],
    exams: [
      { session: "June", year: 2022, marks: "4+3+3", stem: "Describe the risk factors that are associated with the development and progression of TCC bladder. Discuss the role of neoadjuvant chemotherapy in Ca Bladder. Briefly discuss radical TURBT." },
    ],
    related: ["nmibc-bcg", "t1g3", "plnd-bladder", "io-bladder", "qol-small-mibc"],
    references: [
      "EAU MIBC 2024/25",
      "SWOG 8710 (Grossman NEJM) NAC MVAC",
      "BA06 30894 / ABC meta-analysis",
      "Vesper / VESPER ddMVAC vs GC",
      "Campbell Urothelial carcinoma",
    ],
    answer: [
      { t: "h", v: "Risk factors — development vs progression" },
      { t: "tbl", h: ["", "Development of TCC", "Progression (NMIBC → MIBC / death)"], r: [
        ["Exposure", "Tobacco (50–65% male cases; aromatic amines), occupational (aniline, benzidine, 2-naphthylamine, PAH, rubber, dye, leather), cyclophosphamide, phenacetin, pelvic RT, aristolochic acid, schisto (SCC > TCC), chronic catheter (SCC), arsenic, Lynch / upper tract", "Not the same list — tumour biology dominates"],
        ["Host", "Age, male, Balkan nephropathy / UTUC, delayed haematuria work-up", "EORTC/CUETO: T1, HG, CIS, size >3 cm, multifocal, EAU2021 very-high-risk group, variants, LVI, residual T1 on re-TUR"],
        ["Molecular", "FGFR3 / HRAS — papillary NMIBC pathway; TP53 / RB / ERBB2 — CIS / MIBC pathway (two-pathway model)", "TP53, MDM2, Ki-67, variant histology, PD-L1 not a progression tool yet"],
      ]},
      { t: "h", v: "Neoadjuvant chemotherapy in MIBC" },
      { t: "ul", v: [
        "Why neoadjuvant not adjuvant as default: pathologic down-staging (pT0 ~30–40% with ddMVAC), in vivo chemosensitivity, patients actually receive it (adjuvant often dropped after RC), micrometastases treated while performance status is best.",
        "Evidence: SWOG 8710 MVAC + RC vs RC: pT0 38 vs 15%, median OS 77 vs 46 mo. ABC meta-analysis: 5% absolute 5-y OS benefit with cisplatin-based NAC. GC extrapolated from metastatic data; VESPER: ddMVAC improved PFS vs GC in NAC (toxicity higher).",
        "Candidates: cT2–T4a N0 M0, cisplatin-eligible (Galsky: ECOG 0–1, CrCl ≥60, no NYHA III–IV, no grade ≥2 neuropathy / hearing loss).",
        "Ineligible: go to RC ± adjuvant nivo (CheckMate-274) or consider IO/clinical trial; carboplatin is not an adequate NAC substitute.",
        "Down-staging to pT0 is the strongest prognostic marker. Delay to RC should be <12 weeks from completion; if NAC is refused, do not delay RC for indecision.",
      ]},
      { t: "h", v: "Radical TURBT" },
      { t: "p", v: "Maximal / radical TURBT is complete endoscopic resection of all visible tumour including muscle, used (1) as the therapeutic TURBT in NMIBC and (2) as part of bladder-sparing trimodality therapy (TMT: maximal TURBT + radiosensitising chemo-RT) for selected MIBC. It is not a substitute for RC in a surgical candidate with residual T2 after incomplete resection." },
      { t: "ul", v: [
        "Technique: general / spinal, bimanual exam under anaesthesia (3D T-stage), white light ± PDD/NBI, resect exophytic then base separately with muscle in the specimen, biopsy any CIS-looking mucosa, control ureteric orifices, loop vs bipolar, avoid perforation in TMT candidates if possible (but get muscle).",
        "TMT selection: solitary cT2, no hydronephrosis, no extensive CIS, good bladder function, complete visual resection possible.",
        "Re-TURBT at 2–6 weeks for T1 HG / no muscle in first specimen (EAU).",
      ]},
      { t: "tip", k: "gold", v: "Cisplatin-eligible MIBC: NAC then RC is the default. Carboplatin is not NAC. Radical TURBT is a TMT verb, not an excuse to skip cystectomy." },
    ],
  },
  {
    id: "optical-imaging-bladder",
    topicId: "bladder",
    title: "Optical imaging and OCT in bladder cancer",
    highYield: false,
    gold: false,
    tags: ["PDD", "NBI", "OCT", "Cysview"],
    exams: [
      { session: "Dec", year: 2015, marks: "10", stem: "Various optical imaging techniques in high grade bladder cancer." },
      { session: "Dec", year: 2011, marks: "5+5", stem: "What is optical coherence tomography? What is its potential role in managing bladder carcinoma?" },
    ],
    related: ["nmibc-bcg", "t1g3", "tcc-markers"],
    references: [
      "EAU NMIBC — PDD / NBI",
      "Photocure / HEXVIX PHOENIX trials",
      "ICS / SPIE OCT reviews",
      "Campbell Optical imaging",
    ],
    answer: [
      { t: "tbl", h: ["Modality", "Principle", "Use in HG / CIS", "Limitation"], r: [
        ["White-light cystoscopy", "Standard", "Misses flat CIS (~20–30%)", "Operator"],
        ["PDD / HAL blue-light (hexaminolevulinate)", "PpIX in tumours fluoresces red under 375–440 nm", "Improves CIS detection; reduces residual tumour and recurrence (meta-analysis)", "False + after BCG / inflammation; needs dark / special scope; cost"],
        ["NBI", "Narrow 415/540 nm absorbed by Hb — vascular contrast without dye", "Better Ta/CIS detection; no drug", "False + inflammation; similar to PDD in some RCTs"],
        ["OCT", "Near-IR interferometry, ~2 mm depth, 10–20 µm resolution — ‘optical biopsy’ of layers", "May distinguish Ta vs T1 vs T2 by integrity of lamina / muscle; guide biopsy", "Limited field, inflammation artefact, not standard of care"],
        ["CLE (probe confocal)", "Fluorescein cellular imaging", "CIS vs inflammation research", "Point sampling"],
        ["Raman / autofluorescence / AI cystoscopy", "Molecular / computer vision", "Emerging", "Research"],
      ]},
      { t: "h", v: "OCT specifically" },
      { t: "p", v: "Optical coherence tomography uses low-coherence near-infrared light and Michelson interferometry to produce cross-sectional images of mucosa, lamina propria and superficial muscle in real time, analogous to B-mode US but at light wavelengths. In bladder cancer it can, in expert hands, show disruption of the lamina propria (T1) or muscle (T2) and help target biopsies / decide restaging. It has not replaced histopathology, cannot see deep muscle / nodes, and is not in EAU as a required tool." },
      { t: "tip", k: "exam", v: "For HG/CIS: name PDD (HAL) and NBI with the evidence (better detection, less residual). OCT is depth staging research." },
    ],
  },
  {
    id: "tcc-markers",
    topicId: "bladder",
    title: "Tumour markers in TCC bladder",
    highYield: false,
    gold: false,
    tags: ["NMP22", "UroVysion", "BTA", "cytology"],
    exams: [
      { session: "Jun", year: 2016, marks: "2+4+4", stem: "Enlist the tumour markers in TCC urinary bladder. Advantages and disadvantages in using them for surveillance." },
    ],
    related: ["nmibc-bcg", "optical-imaging-bladder"],
    references: ["EAU NMIBC", "FDA-approved urinary markers", "Campbell NMIBC follow-up"],
    answer: [
      { t: "p", v: "No marker replaces cystoscopy. Cytology remains the reference adjunct for high-grade / CIS. FDA-cleared urinary tests are adjuncts when cytology is equivocal or to space cystoscopy in selected low-risk surveillance — they have not been adopted as stand-alone." },
      { t: "tbl", h: ["Marker", "What", "Advantage", "Disadvantage"], r: [
        ["Cytology", "Morphology, Paris system", "High specificity for HG/CIS (~90%)", "Poor sensitivity for LG; operator; BCG artefact"],
        ["NMP22 / BladderChek", "Nuclear mitotic protein", "Point of care, cheap", "False + with inflammation, stones, BCG; modest specificity"],
        ["BTA stat / TRAK", "Complement factor H related", "Office dipstick", "Same false +; haematuria"],
        ["UroVysion FISH", "Aneuploidy 3,7,17 and 9p21", "Better HG sensitivity; may predict BCG failure / anticipate cystoscopic recurrence", "Cost, equivocal, false + after BCG/RT"],
        ["ImmunoCyt / uCyt+", "Mucin / CEA IF on cytology", "Sensitivity boost", "Lab-heavy; withdrawn in some markets"],
        ["Cxbladder, Xpert Bladder, ADXBLADDER (MCM5), UroMark", "mRNA / MCM5 panels", "Rule-out tests with high NPV in haematuria / surveillance research", "Cost, not universal guideline first-line"],
        ["FGFR3 / TERT urine DNA", "Mutation tracking", "LG surveillance research", "Not routine"],
      ]},
      { t: "p", v: "Surveillance use: may reduce cystoscopy frequency in low-risk TaLG with a negative high-NPV test (selected protocols). In HG they cannot replace cystoscopy + cytology. Always interpret against infection, stones, recent instrumentation." },
    ],
  },
  {
    id: "t1g3",
    topicId: "bladder",
    title: "T1G3 bladder cancer and intravesical drug toxicity",
    highYield: true,
    gold: true,
    tags: ["T1HG", "re-TURBT", "BCG", "MMC", "EAU risk"],
    exams: [
      { session: "June", year: 2022, marks: "7+3", stem: "Discuss the management of T1G3 bladder tumors. Discuss the side effects of various drugs used in the intravesical treatment of superficial bladder tumors." },
      { session: "Dec", year: 2021, marks: "4+6", stem: "Describe TNM staging of TCC urinary bladder. Discuss optimal management of T1G3 TCC urinary bladder in a 65 year old male." },
    ],
    related: ["nmibc-bcg", "tcc-risk-nac", "histologic-variants-uc", "io-bladder"],
    references: [
      "EAU NMIBC 2024 — T1 / very high risk",
      "AUA/SUO NMIBC",
      "TNM 8th / AJCC",
      "Campbell NMIBC",
    ],
    answer: [
      { t: "h", v: "TNM 8th (write the T's)" },
      { t: "tbl", h: ["T", "Definition"], r: [
        ["Ta", "Non-invasive papillary"],
        ["Tis", "CIS (‘flat’ HG)"],
        ["T1", "Lamina propria (subepithelial connective tissue)"],
        ["T2a / T2b", "Inner / outer half of detrusor"],
        ["T3a / T3b", "Microscopic / macroscopic perivesical fat"],
        ["T4a / T4b", "Prostate stroma / uterus / vagina ; pelvic wall / abdominal wall"],
        ["N1 / N2 / N3", "Single true pelvis ; multiple true pelvis ; common iliac"],
        ["M1a / M1b", "Non-regional nodes ; distant"],
      ]},
      { t: "p", v: "G3 in old WHO 1973 ≈ high-grade in WHO 2004/2016/2022. T1G3 is never ‘superficial’ in behaviour — 10–20% already have missed muscle invasion, 20–40% progress." },
      { t: "h", v: "Management of T1G3 / T1HG in a 65-year-old" },
      { t: "ul", n: true, v: [
        "Confirm: re-TURBT at 2–6 weeks (mandatory if no muscle in first specimen or residual) — residual T1 upstages a substantial fraction. EUA bimanual. CTU / MR urogram for upper tracts. Variant histology / LVI / deep T1 (T1b/c) / CIS / multifocality / prostatic urethra status.",
        "EAU 2021 risk: many T1HG land in high-risk or very-high-risk (T1HG plus CIS, LVI, variant, prostatic stromal, multiple large T1). Very-high-risk: discuss immediate RC.",
        "Bladder-sparing default for high-risk without very-high-risk features: BCG induction (6) + maintenance (SWOG 8507: 3-week mini-cycles at 3,6,12,18,24,30,36 months — 3 years). Full dose.",
        "Immediate RC: very-high-risk, variant (micropapillary, plasmacytoid, sarcomatoid, nested), residual T1 after re-TUR, BCG-unresponsive, non-compliant with surveillance, hydronephrosis, young with long horizon — 65 is not a contraindication to RC if fit.",
        "BCG-unresponsive: RC is gold standard; pembrolizumab (KEYNOTE-057), nadofaragene firadenovec, Anktiva (nogapendekin alfa inbakicept) + BCG, clinical trial, or radical if fit.",
        "Follow-up if spared: cystoscopy + cytology every 3 months for 2 y, then 6 months, then annually; upper tracts periodically.",
      ]},
      { t: "h", v: "Intravesical drug adverse effects" },
      { t: "tbl", h: ["Drug", "Common", "Serious / unique"], r: [
        ["MMC / hyperthermic MMC / EMDA", "Chemical cystitis, rash, myelosuppression if extravasated", "Never give if perforation; hold 1 h; 40 mg; alkaline urine debate"],
        ["Epirubicin / doxorubicin", "Cystitis, haematuria", "Less used; similar caveats"],
        ["Gemcitabine 2 g", "Dysuria, well tolerated", "Salvage / alternative when BCG shortage"],
        ["BCG", "Cystitis 70%, fever <48 h, haematuria, granulomatous prostatitis, epididymo-orchitis", "BCG sepsis / miliary (isoniazid + rifampin + ethambutol ± cycloserine / fluoroquinolone debate; steroids if hypersensitivity; never restart). Hepatitis, pneumonitis, reactive arthritis, contracted bladder. Hold if traumatic catheter / UTI / gross haematuria."],
      ]},
      { t: "tip", k: "gold", v: "T1G3 = re-TUR then BCG maintenance, unless very-high-risk / variant / residual T1, in which case RC. MMC after perforation is a disaster question." },
    ],
  },
  {
    id: "nmibc-bcg",
    topicId: "bladder",
    title: "NMIBC risk stratification and BCG",
    highYield: true,
    gold: true,
    tags: ["NMIBC", "BCG", "EORTC", "BCG-unresponsive", "SWOG 8507"],
    exams: [
      { session: "Jun", year: 2017, marks: "5+5", stem: "Intravesical therapy for management of non-muscle invasive urothelial carcinoma of bladder. Pre-requisites and the preparation for intravesical mitomycin instillation." },
      { session: "Dec", year: 2022, marks: "4+2+4", stem: "Risk stratification for NMIBC. Quantify risk of recurrence and progression after TURBT in different risk groups. Strategies used to reduce risk of recurrence after TURBT." },
      { session: "Jun", year: 2021, marks: "6+4", stem: "What is low risk, intermediate risk and high risk NMIBC? Describe the complications of intra-vesical BCG." },
      { session: "Dec", year: 2016, marks: "5+5", stem: "Classify risk stratification of NMIBC. Outline the management of a BCG refractory case of NMIBC." },
      { session: "Dec", year: 2013, marks: "5+5", stem: "Describe the molecular basis of use of BCG in NMIBC. Describe WHO grading of common toxicities of BCG." },
      { session: "Dec", year: 2011, marks: "6+4", stem: "Describe the role of BCG in superficial bladder transitional cell carcinoma. What are the steps taken to minimize its complications?" },
      { session: "Dec", year: 2021, marks: "4+6", stem: "Describe various indications of intravesical BCG therapy and its schedule. Discuss the toxicities of intravesical BCG therapy." },
      { session: "Jun", year: 2020, marks: "4+6", stem: "BCG failure in the treatment of TCC bladder and discuss the management of BCG failure." },
      { session: "Dec", year: 2020, marks: "4+2+4", stem: "What is the mechanism of action of intravesical BCG in bladder cancer? What are its indications? What are the complications of intravesical BCG?" },
      { session: "Jun", year: 2018, marks: "10", stem: "Intra-vesical therapy for non-muscle invasive bladder cancer." },
    ],
    related: ["t1g3", "io-bladder", "tcc-risk-nac", "optical-imaging-bladder"],
    references: [
      "EAU NMIBC 2024",
      "EORTC 63711 / 30911; CUETO; EAU 2021 risk tables",
      "SWOG 8507 Lamm maintenance BCG",
      "IARC / Morales 1976",
      "FDA BCG-unresponsive definition",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "Risk table 2 · Recurrence/progression numbers 1 · Immediate chemo + quality of TURBT 2 · BCG mechanism + schedule 2 · Toxicity / how to give 2 · Failure definitions + next step 1." },
      { t: "h", v: "EAU risk groups (2021, WHO 2004/2016 HG/LG)" },
      { t: "tbl", h: ["Group", "Who (simplified)", "5-y recurrence / progression (order of magnitude)"], r: [
        ["Low", "Primary, solitary TaLG <3 cm, no CIS", "Recurrence ~30%; progression ~1%"],
        ["Intermediate", "All not low or high (recurrent / multiple / large TaLG)", "Recurrence ~50%; progression ~5%"],
        ["High", "T1, HG/G3, CIS, multiple large recurrent TaHG", "Recurrence ~60%; progression ~10–15%"],
        ["Very high", "T1HG plus CIS / LVI / variant / multiple large T1 etc.", "Progression 20–40% — RC discussion"],
      ]},
      { t: "p", v: "Older EORTC Sylvester tables (WHO 1973, 6 clinicopathologic factors) are still quoteable: recurrence score 0–17, progression 0–23. CUETO predicts on BCG-treated patients (lower progression than EORTC)." },
      { t: "h", v: "Strategies to cut recurrence after TURBT" },
      { t: "ul", v: [
        "Quality TURBT: complete, muscle in specimen, PDD/NBI for CIS, bimanual EUA.",
        "Re-TURBT for T1 / no muscle / incomplete.",
        "Immediate postoperative instillation of chemo (IPOP): MMC 40 mg or gemcitabine 2 g within 6 h if no perforation / deep resection / bleeding — reduces recurrence ~10–15% absolute in low/intermediate (not if obvious residual / T1/CIS).",
        "Induction + maintenance BCG for high-risk; chemo induction for intermediate if BCG not chosen.",
        "Stop smoking. Enhanced cystoscopy. Random biopsies only if positive cytology / planned cystectomy mapping.",
      ]},
      { t: "h", v: "MMC preparation (Jun 17 part b)" },
      { t: "ul", v: ["Exclude perforation, raw resection, thrombocytopenia, pregnancy", "Empty bladder, confirm haemostasis, 40 mg in 20–40 mL, dwell 60 min, rotate positions, alkaline urine (sodium bicarbonate) used in some protocols", "Staff PPE, closed system, treat spill as chemo", "Weekly induction 6–8 then maintenance monthly if used as primary intermediate-risk therapy"] },
      { t: "h", v: "BCG mechanism" },
      { t: "p", v: "Live attenuated Mycobacterium bovis binds fibronectin (FAP) on urothelium → internalised by tumour / APC → Th1 cascade (IL-2, IFN-γ, IL-12, TRAIL) → NK, CD8, BCG-activated killer cells. Requires intact immune system and direct contact. Not a simple chemo." },
      { t: "h", v: "Indications and schedule" },
      { t: "ul", v: [
        "High-risk NMIBC (T1, HG, CIS) after complete TUR / re-TUR. Intermediate-risk as an option. Not low-risk. Not MIBC (except as part of trials / TMT adjunct historically).",
        "Contraindications: traumatic catheterisation that day, UTI, gross haematuria, immunodeficiency, active TB, total incontinence (cannot hold), 2 weeks after TUR (risk of sepsis).",
        "Morales induction: weekly × 6 starting 2–4 weeks post TUR. Maintenance (SWOG 8507): 3 weekly instillations at 3, 6, 12, 18, 24, 30, 36 months (3 years) for high-risk. Intermediate: 1 year. Full dose; reduced dose if toxicity.",
      ]},
      { t: "h", v: "WHO / EAU toxicity (Lamm grades — write a ladder)" },
      { t: "tbl", h: ["Grade (conceptual)", "Example", "Action"], r: [
        ["1 mild local", "Dysuria <48 h, low fever", "Analgesia, delay next dose"],
        ["2 moderate", "Prolonged cystitis, haematuria, fever 48–72 h", "Hold, quinolone / INH in some protocols, reduce dose"],
        ["3 severe local / systemic", "Epididymo-orchitis, contracted bladder, hepatitis, pneumonitis, reactive arthritis", "Stop BCG permanently in many; anti-TB ± steroid"],
        ["4 BCG sepsis / miliary", "Hypotension, DIC, ARDS after traumatic instillation", "Resuscitate, full anti-TB (INH+RIF+ETH ±), high-dose steroid if hypersensitivity picture, never restart"],
      ]},
      { t: "h", v: "Minimise complications" },
      { t: "ul", v: ["Wait ≥2 weeks after TUR; abort if traumatic Foley or UTI; empty residual; no high-pressure instillation; staff education; fluoroquinolone not routinely for prevention (resistance, and may kill BCG); INH prophylaxis not standard"] },
      { t: "h", v: "BCG failure — use FDA words" },
      { t: "ul", v: [
        "BCG-unresponsive: HG T1 at first evaluation after induction; or recurrent HG Ta/Tis after adequate BCG (adequate = ≥5/6 induction + ≥2/3 of first maintenance, or 2 inductions); or persistent Tis after adequate BCG. RC is standard.",
        "BCG-refractory / relapsing / intolerant: older terms — still used in older papers.",
        "Options if RC declined / unfit: pembrolizumab (KEYNOTE-057, 40% 3-month CR in CIS), nadofaragene firadenovec (Ad-IFNα), Anktiva + BCG, gemcitabine/docetaxel sequential, hyperthermic MMC, clinical trial, TMT rarely.",
      ]},
      { t: "tip", k: "gold", v: "High-risk NMIBC: complete TUR, re-TUR if T1, then 6+3-year SWOG BCG. Unresponsive HG T1 = cystectomy. Never instil BCG through a bloody traumatic catheter." },
    ],
  },
  {
    id: "io-bladder",
    topicId: "bladder",
    title: "Immune checkpoint blockade in bladder cancer",
    highYield: true,
    gold: true,
    tags: ["pembrolizumab", "nivolumab", "EV-302", "KEYNOTE", "CheckMate"],
    exams: [
      { session: "Dec", year: 2022, marks: "4+6", stem: "Discuss safety and adverse events with immune check-point inhibitor therapy. Role of immune check-point blockade for management of bladder cancer." },
    ],
    related: ["immuno-checkpoint-urothelial", "nmibc-bcg", "tcc-risk-nac", "t1g3"],
    references: [
      "KEYNOTE-045 / 052 / 057",
      "CheckMate-274 / 901",
      "JAVELIN Bladder 100",
      "EV-302",
      "EAU MIBC 2025",
    ],
    answer: [
      { t: "h", v: "Role by setting (write the trial)" },
      { t: "tbl", h: ["Setting", "Regimen / trial", "Take-home"], r: [
        ["1L metastatic", "Enfortumab vedotin + pembrolizumab (EV-302) OS 31.5 vs 16.1 mo", "New default if available"],
        ["1L cisplatin-eligible (alternative)", "Gem-cis + nivo (CheckMate-901)", "OS benefit vs gem-cis"],
        ["Maintenance after platinum SD/PR", "Avelumab (JAVELIN Bladder 100)", "OS benefit; switch-maintenance"],
        ["2L post-platinum", "Pembrolizumab (KEYNOTE-045)", "Classic OS vs taxane"],
        ["Cisplatin-ineligible 1L historic", "Pembro / atezo if PD-L1+ (KEYNOTE-052) — shrinking role after EV", "Know for older papers"],
        ["Adjuvant after RC", "Nivo 1 y (CheckMate-274) if ypT2–4 or pN+ post-NAC, or pT3–4/N+ without NAC", "DFS benefit"],
        ["BCG-unresponsive CIS", "Pembro (KEYNOTE-057)", "Bladder-sparing option"],
      ]},
      { t: "h", v: "Safety — immune-related AE (irAE)" },
      { t: "p", v: "Checkpoint blockade unmasks autoimmunity. Timing: weeks to months, can be after stopping. Any organ. CTLA-4 (ipi) worse than PD-1; combinations worst. Grade with CTCAE." },
      { t: "ul", v: [
        "Common: fatigue, rash, pruritus, hypothyroidism (~15%), diarrhoea / colitis, hepatitis, pneumonitis.",
        "Endocrine: hypoT4 (replace, can continue drug), adrenalitis / hypophysitis (hold, steroids, lifelong replacement — board favourite).",
        "Serious: pneumonitis, colitis (rule out infection then high-dose steroid ± infliximab), hepatitis, myocarditis, encephalitis, T1DM.",
        "Grade 1: supportive, continue. Grade 2: hold, prednisone 0.5–1 mg/kg. Grade ≥3: permanently discontinue most, 1–2 mg/kg methylpred, endocrinology / organ specialist. Do not use infliximab in hepatitis.",
        "Urologic pearls: not a contraindication in stable autoimmune disease always — individualise; transplant patients may reject; BCG + systemic IO is a research question not standard together.",
        "EV-specific (if combination): rash, neuropathy, hyperglycaemia, ocular — not irAE but must mention if quoting EV-302.",
      ]},
      { t: "tip", k: "gold", v: "Name EV-302 for 1L, JAVELIN for maintenance, CheckMate-274 adjuvant, KEYNOTE-045 2L, KEYNOTE-057 BCG-unresponsive. irAE = steroids, not antibiotics." },
    ],
  },
  {
    id: "diversion-segments",
    topicId: "bladder",
    title: "Urinary diversion after RC and intestinal segments",
    highYield: true,
    gold: true,
    tags: ["conduit", "neobladder", "colon", "ileum", "ERAS"],
    exams: [
      { session: "June", year: 2022, marks: "5+5", stem: "Discuss the various urinary diversion used after Radical cystectomy. Discuss the advantages and disadvantages of use of different intestinal segments." },
    ],
    related: ["ileal-neobladder", "continent-pouch", "augmentation-cystoplasty", "eras"],
    references: [
      "EAU MIBC — urinary diversion",
      "Campbell Urinary diversion",
      "Hautmann / Studer / Bricker",
      "ERAS cystectomy",
    ],
    answer: [
      { t: "h", v: "Menu after RC" },
      { t: "tbl", h: ["Class", "Examples", "Needs"], r: [
        ["Incontinent cutaneous", "Ileal conduit (Bricker), colon conduit, cutaneous ureterostomy", "Stoma appliance; simplest; default in frail / unmotivated / CKD / urethral disease"],
        ["Continent cutaneous", "Indiana (ileocaecal), Mainz I, Kock, Mitrofanoff/Monti to pouch", "CIC of stoma; competence of nipple / plicated ileocaecal valve"],
        ["Orthotopic neobladder", "Studer, Hautmann W, T-pouch, Padua, Y-pouch", "Urethra with negative frozen margin, motivated CIC backup, eGFR usually >40–50, no IBD / unprepared bowel, no dense urethral stricture"],
        ["Rectosigmoid / ureterosigmoidostomy", "Mainz II, classic USG", "Almost historic: pyelo, cancer at anastomosis, hyperchloraemic acidosis — know to condemn except rare TQT"],
      ]},
      { t: "h", v: "Bowel segments — physiology table" },
      { t: "tbl", h: ["Segment", "Advantage", "Disadvantage / metabolic"], r: [
        ["Distal ileum (15–20 cm conduit; 40–55 cm neobladder)", "Mobile, reliable blood (ileal arcade), compliant when detubularised", "B12 / bile-salt / fat after long loss; hypokalaemic hyperchloraemic metabolic acidosis (NaCl in, HCO3 out); mucus"],
        ["Ileocaecal (Indiana)", "Built-in continence valve, large capacity", "Lose IC valve → diarrhoea, B12; too much colon in pouch → more mucus / contraction if not detubularised"],
        ["Right / transverse colon", "When ileum irradiated", "Bulk, mucus, less compliant if tubular"],
        ["Sigmoid", "Pelvic, good calibre", "Diverticula, cancer risk, less distensible, worse acidosis than ileum sometimes"],
        ["Stomach (gastrocystoplasty)", "Acid kills bacteria, less mucus, use if no small bowel", "Haematuria-dysuria syndrome, hyponatraemic hypochloraemic alkalosis, ulcer, malignancy — rarely first choice"],
        ["Jejunum", "Last resort", "Severe hyponatraemic hyperkalaemic acidosis — avoid"],
      ]},
      { t: "p", v: "Detubularisation (Laplace: P = T / r for a cylinder; for a sphere P = 2T/r) increases radius, drops pressure, kills peristaltic peaks. Always mention Laplace in this paper (see neobladder answer)." },
      { t: "ul", v: [
        "Selection: cancer stage / urethra / prostate invasion, renal function, age, dexterity, prior RT / IBD, preference after counselling (not surgeon vanity).",
        "Conduit remains the most reproducible diversion worldwide. Neobladder is not oncologically superior; it is a QOL choice in the right patient.",
        "ERAS: no mechanical bowel prep as routine, early feeding, stoma therapist pre-op.",
      ]},
      { t: "tip", k: "gold", v: "Match the patient to the diversion, not the other way round. Ileum is default bowel; jejunum is metabolic poison; stomach is a salvage segment. Detubularise or do not bother." },
    ],
  },
  {
    id: "ileal-neobladder",
    topicId: "bladder",
    title: "Ileal neobladder (Studer) — Laplace, metabolism, long-term sequelae",
    highYield: true,
    gold: true,
    tags: ["Studer", "Hautmann", "Laplace", "acidosis", "night-time incontinence"],
    exams: [
      { session: "Dec", year: 2022, marks: "10", stem: "Briefly describe long-term sequelae and their management in ileal neo bladder." },
      { session: "Jun", year: 2021, marks: "4+6", stem: "Describe Studer's neo-bladder. Describe the possible short term and long term complications with management." },
      { session: "Dec", year: 2019, marks: "4+3+3", stem: "Application of Laplace law for use of bowel in Urology. Discuss metabolic complications and management of ileal neo bladder." },
      { session: "Jun", year: 2020, marks: "4+6", stem: "Advantages and disadvantages of Studer neo-bladder." },
      { session: "Jun", year: 2017, marks: "10", stem: "Long term complications of orthotopic neo-bladder after radical cystectomy." },
      { session: "Jun", year: 2016, marks: "5+2+3", stem: "Technique, results and complications of Orthotopic bladder substitute." },
      { session: "Dec", year: 2013, marks: "4+3+3", stem: "What is the basis of supplementing soda-bicarb in a patient with Orthotopic neobladder? What is the mechanism of night time incontinence in the patient? Can mucus production be minimized and how?" },
    ],
    related: ["diversion-segments", "continent-pouch", "hyponatremia", "eras"],
    references: [
      "Studer UE. BJU Int / Campbell Orthotopic diversion",
      "Hautmann series",
      "EAU MIBC diversion",
      "Laplace’s law applications in urology",
    ],
    answer: [
      { t: "h", v: "Studer neobladder — the construct" },
      { t: "ul", v: [
        "~54 cm of preterminal ileum, 25 cm from IC valve (preserve B12 terminal ileum). Distal 40–44 cm opened antimesenteric and folded as a U (or similar) to form a spherical, detubularised pouch; proximal 14–16 cm left intact as an afferent isoperistaltic tubular limb for ureteric implantation (reflux-reducing, easy ureteroileal anastomosis).",
        "Urethral anastomosis at the most dependent dependent dependent? dependent point of the pouch. Ureters spatulated into the afferent limb (Nesbit / Wallace).",
        "Contrast Hautmann W (60–70 cm, no long afferent tube, ureters into pouch) and T-pouch (anti-reflux T-limb).",
      ]},
      { t: "h", v: "Laplace’s law" },
      { t: "p", v: "Wall tension T relates to pressure P and radius r. Cylinder: P = T/r (or T = P·r). Sphere: P = 2T/r. Detubularising bowel and rearranging it into a large-radius sphere drops luminal pressure for a given wall tension, increases capacity, and ablates coordinated peristaltic pressure peaks that would leak and reflux. This is why a tubular ileal segment is a terrible reservoir and a folded ileal sphere is a good one. The same law explains why a chronically full pouch (large r) can still leak at modest tension at night, and why over-distension risks rupture as T rises." },
      { t: "tbl", c: "Studer — advantages vs disadvantages", h: ["Advantages", "Disadvantages"], r: [
        ["Void via urethra; body image; potentially better sexual / body QOL in selected", "Night leak 20–40%; day leak 10%; need to CIC in 10–30% (women more)"],
        ["Afferent limb: simple ureteric join, some reflux protection", "Not anti-reflux bulletproof; pyelo still occurs"],
        ["Ileum available, reliable blood supply", "Contraindicated if urethra +ve, CKD, unmotivated, IBD, prior extensive ileum, hepatic failure"],
        ["Oncologic equivalence to conduit if margins negative", "Longer surgery, more early bowel complications than conduit in some series"],
      ]},
      { t: "h", v: "Metabolic complications and soda-bicarb" },
      { t: "p", v: "Ileal mucosa in contact with urine exchanges NaCl absorption for HCO3 secretion (and some ammonium absorption). Net: hyperchloraemic metabolic acidosis, often with hyponatraemia, dehydration, and hyperammonaemia if liver is frail. Chronic acidosis leaches bone (osteomalacia). Renal impairment worsens it because the kidney cannot compensate. Sodium bicarbonate (or citrate) replenishes HCO3, corrects acidosis, and the sodium helps volume. Patients are also taught salt liberalisation and timed voiding / CIC so urine does not dwell all night on the mucosa." },
      { t: "h", v: "Night-time incontinence — mechanisms" },
      { t: "ul", v: [
        "Loss of the guarding reflex / pelvic-floor tone in sleep.",
        "Increased nocturnal urine (third-spacing, ileal secretion, fluid shifts) into a pouch that has no detrusor-sphincter coordination.",
        "Pouch contractions (if poorly detubularised) plus a sphincter that was damaged at RC (rhabdosphincter, pudendal, neural).",
        "Over-capacity overflow if the patient does not wake to empty.",
        "Management: alarm / timed night void or CIC, reduce evening fluid, treat acidosis, pelvic floor, exclude residual / infection / pouch stones; AUS rarely; do not promise dryness at night in counselling.",
      ]},
      { t: "h", v: "Mucus" },
      { t: "p", v: "Goblet cells continue to secrete; mucus plugs CIC catheters, causes retention and stones. Minimise: regular void / CIC, high fluid, daily pouch irrigation with saline if CIC-dependent, N-acetylcysteine irrigant in some units. Mucus declines over years as villous atrophy develops but never zero. Oral mucolytics are weakly evidence-based." },
      { t: "h", v: "Short-term complications" },
      { t: "ul", v: ["Urine leak at urethroileal or ureteroileal anastomosis", "Ileus / SBO / anastomotic bowel leak", "UTI, pyelo, metabolic acidosis early", "Retention from mucus / oedema — leave a catheter 2–3 weeks", "PE / DVT (pelvic cancer)", "Rectal / vascular injury from the RC, not the pouch"] },
      { t: "h", v: "Long-term sequelae and management" },
      { t: "tbl", h: ["Sequela", "Management"], r: [
        ["Day / night incontinence", "PFMT, timed void, CIC, AUS selected; night alarm"],
        ["Hyperchloraemic acidosis, B12 deficiency after 3–5 y, bone loss", "NaHCO3, salt, B12 monitor/replace, DEXA / vitamin D"],
        ["Pouch stones (infection / mucus / staples)", "Endoscopic / percutaneous; irrigate; treat UTI"],
        ["Ureteroileal stricture", "Stent, balloon, open revision; left more than right"],
        ["Pouch-urethral anastomotic stricture", "Gentle dilation / DVIU; avoid aggressive TUR of the join"],
        ["Retention / failure to empty (especially women, after hernia, after urethral angle change)", "CIC lifelong if needed — a success, not a failure"],
        ["UTI / pyelo / reflux", "CIC, treat obstruction, antibiotics selected"],
        ["Pouch rupture (trauma, forgotten CIC)", "Catheter, laparotomy if intraperitoneal leak"],
        ["Second malignancy (rare, less than ureterosigmoidostomy)", "Investigate haematuria; not routine pouch-oscopy for all"],
        ["Sexual dysfunction, hernia, incisional issues", "Standard"],
      ]},
      { t: "tip", k: "gold", v: "Detubularise (Laplace). Acidosis = ileal Cl/HCO3 exchange, treat with salt + bicarb + emptying. Night leak is expected physiology, not always a failed sphincter. CIC after neobladder is a valid emptying method." },
    ],
  },
  {
    id: "histologic-variants-uc",
    topicId: "bladder",
    title: "Histologic variants of urothelial carcinoma",
    highYield: true,
    gold: false,
    tags: ["micropapillary", "plasmacytoid", "nested", "sarcomatoid", "SCC"],
    exams: [
      { session: "Dec", year: 2020, marks: "5+5", stem: "What are the histologic variants of urothelial cancers? What are their clinical relevance in bladder cancer?" },
    ],
    related: ["t1g3", "nmibc-bcg", "tcc-risk-nac"],
    references: ["WHO GU 2022", "EAU NMIBC / MIBC variant statements", "Campbell Pathology of bladder cancer"],
    answer: [
      { t: "tbl", h: ["Variant", "Pathology cue", "Clinical relevance"], r: [
        ["Micropapillary", "Small tight clusters in lacunae, like ovarian MPSC", "Early LVI/N+; BCG unreliable; low threshold for RC even if ‘T1’"],
        ["Plasmacytoid", "Discohesive CDH1/E-cadherin loss, signet-like", "Locally infiltrative, peritoneal spread, +margin; dismal; RC early; chemo mixed"],
        ["Nested / large nested", "Bland nests mimicking von Brunn", "Looks deceptively low-grade; behaves as HG invasive"],
        ["Sarcomatoid / carcinosarcoma", "Spindle + epithelial", "Aggressive; NAC/RC; poor OS"],
        ["Squamous differentiation", "Keratin, intercellular bridges", "Commonest ‘divergent’; still treat as UC if mixed; pure SCC (schisto, catheter) is a different algorithm (RC, little NAC benefit)"],
        ["Glandular / adenocarcinoma (including urachal, enteric)", "Glands, mucin", "Urachal → extended partial; enteric metastatic from colon must be excluded"],
        ["Lymphoepithelioma-like", "EBV-like syncytial with lymphoid stroma", "Chemosensitive; relatively better"],
        ["Small-cell / neuroendocrine", "Synaptophysin, high Ki-67", "Treat like lung small-cell: platinum-etoposide ± RC/RT; brain uncommon vs lung"],
        ["Lipid-rich, microcystic, giant-cell, clear-cell", "Rare", "Generally HG biology"],
        ["LVI / divergent differentiation extent", "Report %", "NAC still used for mixed UC; pure non-UC often NAC-poor"],
      ]},
      { t: "tip", k: "gold", v: "Variant histology on a T1 chip is a cystectomy conversation, not a BCG conversation, especially micropapillary and plasmacytoid." },
    ],
  },
  {
    id: "plnd-bladder",
    topicId: "bladder",
    title: "Pelvic lymph-node anatomy and PLND templates at cystectomy",
    highYield: true,
    gold: true,
    tags: ["PLND", "extended template", "Cloquet", "NAC"],
    exams: [
      { session: "Jun", year: 2019, marks: "5+5", stem: "Describe the anatomy of pelvic lymph nodes. Define the extent of standard and extended pelvic lymph node dissection for management of invasive TCC of urinary bladder." },
      { session: "Dec", year: 2012, marks: "10", stem: "Discuss surgical anatomy of pelvic lymph node relevant to pelvic lymphadenectomy for invasive TCC of urinary bladder." },
      { session: "Jun", year: 2014, marks: "10", stem: "Describe the pros and cons of extended lymph node dissection in the management of muscle invasive carcinoma of urinary bladder." },
      { session: "Dec", year: 2016, marks: "6+4", stem: "Types of pelvic lymph node dissection during radical cystectomy for MIBC. Critical appraisal of the practice of neo-adjuvant chemotherapy in MIBC." },
    ],
    related: ["tcc-risk-nac", "io-bladder", "qol-small-mibc"],
    references: [
      "EAU MIBC — lymphadenectomy",
      "LEA AUO trial; Gschwend",
      "Campbell Radical cystectomy",
      "SWOG 8710 NAC",
    ],
    answer: [
      { t: "h", v: "Anatomy — primary landing sites" },
      { t: "p", v: "Bladder drainage is to the external iliac, obturator, internal iliac (hypogastric) and presacral nodes, then common iliac, then para-aortic. Superficial inguinal is not a primary bladder landing site (unlike penis)." },
      { t: "ul", v: [
        "External iliac: lateral to artery, between artery and vein, medial to vein (Cloquet at the femoral canal is the distal limit of many templates).",
        "Obturator: around obturator nerve, between external iliac and hypogastric — the commonest positive pelvic node.",
        "Internal iliac: along the hypogastric, including presacral / presciatic (internal pudendal, inferior gluteal — the ‘fossa of Marcille’ discussion).",
        "Common iliac and distal aorta / vena cava: secondary.",
        "Skip metastases to common iliac without obturator disease occur but are uncommon.",
      ]},
      { t: "h", v: "Templates" },
      { t: "tbl", h: ["Template", "Limits", "Yield"], r: [
        ["Limited / obturator only", "Obturator fossa", "Inadequate staging — do not write this as cancer surgery"],
        ["Standard", "Genitofemoral n. laterally, Cloquet / circumflex iliac distally, internal iliac medially, bifurcation of common iliac proximally; includes obturator + external + internal iliac", "Historic RC standard"],
        ["Extended", "Standard PLUS common iliac to aortic bifurcation, presacral, and often fossa of Marcille; some include distal para-aortic to IMA", "Higher node count (20–40), better staging, possible therapeutic in N1"],
        ["Super-extended", "To IMA or higher", "More morbidity, no proven OS in RCTs"],
      ]},
      { t: "h", v: "Extended PLND — pros and cons" },
      { t: "ul", v: [
        "Pros: accurate N-stage (adjuvant nivo / chemo decisions), more complete removal of micromets, observational series with better CSS when node count high, removes the true landing sites of bladder cancer.",
        "Cons: longer, more lymphocoele, venous injury, autonomic nerve injury (continence / erection if neobladder), no unequivocal OS benefit in the German LEA AUO randomised trial of extended vs limited (underpowered, both arms more than ‘obturator only’). EAU still recommends at least standard, preferably extended.",
        "Minimum: bilateral, named template, node count reported. Frozen nodes no longer gate the cystectomy.",
      ]},
      { t: "h", v: "NAC appraisal (Dec 16 part b)" },
      { t: "p", v: "Level-1 OS benefit (SWOG 8710, ABC meta-analysis ~5% at 5 y) with cisplatin-based NAC in cT2–T4a. Down-staging to pT0 is prognostic. Under-used because of delay fears, cisplatin-ineligibility, and surgeon preference. Carboplatin is not a substitute. Do not delay RC >3 months if the patient will not get NAC. Adjuvant nivo now covers many who did not get NAC or who remain ypN+/T3–4." },
      { t: "tip", k: "gold", v: "Name genitofemoral, Cloquet, obturator nerve, aortic bifurcation. Extended PLND is staging gold; OS benefit is suggested not proven. NAC is proven — PLND extent is not an excuse to skip it." },
    ],
  },
  {
    id: "qol-small-mibc",
    topicId: "bladder",
    title: "QOL strategies in small-volume MIBC",
    highYield: false,
    gold: false,
    tags: ["TMT", "bladder sparing", "partial cystectomy", "QoL"],
    exams: [
      { session: "Dec", year: 2011, marks: "10", stem: "What are the various strategies used to improve the quality of life in men with small volume, muscle invasive transitional cell carcinoma of urinary bladder?" },
    ],
    related: ["tcc-risk-nac", "ileal-neobladder", "plnd-bladder"],
    references: ["EAU MIBC bladder-sparing", "RTOG TMT protocols", "Campbell Conservative therapy of MIBC"],
    answer: [
      { t: "p", v: "Small-volume, solitary cT2, no hydronephrosis, no extensive CIS, good bladder — the patient in whom QOL-preserving options can be offered alongside RC + neobladder, not instead of counselling RC." },
      { t: "ul", v: [
        "Orthotopic neobladder after RC (nerve-sparing in selected) — still the oncologic standard with best local control.",
        "Trimodality therapy: maximal TURBT + external RT + concurrent radiosensitiser (cisplatin or 5-FU/MMC or gemcitabine). Salvage RC for residual. 5-y OS approaching selected RC series in trials; 20–30% salvage cystectomy. Requires a working bladder.",
        "Partial cystectomy ± PLND: dome / urachal / diverticular solitary tumours with generous margin and no CIS — uncommon but QOL-excellent if chosen honestly.",
        "NAC then restage; exceptional pT0 may enter surveillance trials (not standard off-trial).",
        "Sexual-preserving RC (prostate-sparing / capsule-sparing / seminal-sparing) in highly selected young men with no bladder-neck / prostate TCC — oncologic caution, mention as controversial.",
        "ERAS, minimally invasive RC, continent diversion, penile rehab, stoma therapy if conduit — QOL is peri-operative too.",
        "Supportive: continence physiotherapy, fertility / sperm store, psychological, smoking cessation.",
      ]},
      { t: "tip", k: "exam", v: "Lead with ‘RC + orthotopic pouch is a QOL operation’. Then TMT and highly selected partial. Do not sell TURBT alone for MIBC." },
    ],
  },
  {
    id: "bladder-trauma",
    topicId: "bladder",
    title: "Bladder trauma and pelvic-fracture urologic injuries",
    highYield: true,
    gold: true,
    tags: ["AAST", "extraperitoneal", "intraperitoneal", "pelvic fracture", "PFUI"],
    exams: [
      { session: "Jun", year: 2019, marks: "5+5", stem: "Diagnosis and management options of urinary bladder injuries following blunt abdominal trauma." },
      { session: "Dec", year: 2011, marks: "10", stem: "Briefly outline the management of a patient who presents to the emergency after a road traffic crash with hematuria." },
      { session: "Jun", year: 2018, marks: "3+7", stem: "Classify bladder injury and describe its management." },
      { session: "Dec", year: 2014, marks: "10", stem: "Urological management of a 24 year old man with a road traffic accident and fracture pelvis." },
      { session: "Jun", year: 2015, marks: "2+4+4", stem: "Enumerate the urological injuries associated with fracture of the pelvis. Diagnosis and management of extra-peritoneal rupture of urinary bladder." },
    ],
    related: ["posterior-urethral-injury", "perineal-extravasation", "dvt-pelvic"],
    references: [
      "EAU Urological Trauma",
      "AAST bladder injury grades",
      "Campbell Trauma",
      "AUA Urotrauma",
    ],
    answer: [
      { t: "tip", k: "exam", v: "ABC, pelvic binder, blood, then decide if the haematuria is upper tract, bladder, or urethra. Do NOT pass a Foley blindly if blood at meatus — RGU first." },
      { t: "h", v: "Pelvic fracture urologic injuries" },
      { t: "ul", v: ["Bladder rupture (extra- >> intraperitoneal in pelvic fracture; both can coexist)", "Posterior urethral injury (PFUDD / PFUI) ~10% of pelvic fractures, men >> women", "Bladder neck laceration (more in children / women — needs repair)", "Ureter (rare in blunt)", "External genitalia, rectum, vagina"] },
      { t: "h", v: "Haematuria after RTC — sequence" },
      { t: "flow", title: "Trauma haematuria", nodes: [
        { id: "a", kind: "start", label: "ATLS: airway, chest, pelvis binder, transfusion, FAST", to: ["b"] },
        { id: "b", kind: "decision", label: "Blood at meatus / unable to void / high-riding prostate / perineal butterfly?", to: ["c", "d"] },
        { id: "c", kind: "action", label: "RGU ± flexible cystoscopy; SPC if disrupted urethra; do not make a complete disruption complete", to: ["e"] },
        { id: "d", kind: "action", label: "Gentle Foley if no urethral signs", to: ["e"] },
        { id: "e", kind: "action", label: "Stable: trauma CT with delayed urographic phase + CT cystography (300 mL dilute contrast, post-drain film)", to: ["f"] },
        { id: "f", kind: "end", label: "Unstable to OT: on-table cystotomy, SPC, do not embark on delayed urethral reconstruction" },
      ]},
      { t: "h", v: "Bladder injury classification (AAST / anatomic)" },
      { t: "tbl", h: ["Type", "Mechanism / image", "Management"], r: [
        ["Contusion (AAST I)", "Haematuria, intact bladder", "Catheter short period"],
        ["Extraperitoneal rupture", "Pelvic-fracture shearing; flame-shaped contrast in Retzius / scrotum / perineum, not outlining bowel", "Foley 7–14 d; follow-up cystogram. Immediate repair if: bone spike in bladder, rectal/vaginal injury, bladder neck, open pelvis, laparotomy for other reason, failed drainage, clots"],
        ["Intraperitoneal rupture", "Dome burst from full bladder (seatbelt); contrast outlines loops / paracolic gutters", "Always surgical repair in 1–2 layers, absorbable, leak test, drain, Foley ± SPC"],
        ["Combined / bladder neck / trigonal", "High-energy", "Repair; reimplant ureter if orifice involved"],
        ["Penetrating", "GSW / stab", "Explore, repair, exclude rectal injury"],
      ]},
      { t: "h", v: "Extraperitoneal rupture — diagnosis and management (the dedicated stem)" },
      { t: "ul", v: [
        "Suspect: pelvic fracture + haematuria. Diagnosis is CT cystography, not a clamped-Foley ‘excretory’ CT (underfills).",
        "Standard: large-bore Foley, 10–14 days, antibiotics peri-catheter, cystogram before removal.",
        "Operate if the list above. At repair, remove bone spicules, close from inside, do not hunt every pelvic haematoma (open-book pelvis bleeds).",
        "Complications: fistula, stricture at BN, residual leak, infection of pelvic haematoma, missed urethral injury.",
      ]},
      { t: "h", v: "The 24-year-old with fracture pelvis" },
      { t: "p", v: "Resuscitate, binder, ortho/trauma. Urethra algorithm (RGU). Bladder as above. If PFUI: realign gently over a wire if easy (endoscopic primary realignment) or SPC and delayed anastomotic urethroplasty at 3 months (see urethra). DVT prophylaxis once haemostasis allows. Rehab, continence, ED counselling from day 1." },
      { t: "tip", k: "gold", v: "Intraperitoneal bladder = operate. Extraperitoneal = catheter unless bone, neck, rectum, or laparotomy. Meatal blood = RGU, not a triumphant Foley." },
    ],
  },
  {
    id: "exstrophy-adult",
    topicId: "bladder",
    title: "Exstrophy–epispadias complex in the adult",
    highYield: false,
    gold: false,
    tags: ["exstrophy", "epispadias", "adult reconstruction"],
    exams: [
      { session: "Dec", year: 2019, marks: "5+5", stem: "Describe anatomy in exstrophy-epispadias complex. Discuss surgical options in an adult." },
    ],
    related: ["female-epispadias", "bladder-embryology", "continent-pouch", "augmentation-cystoplasty"],
    references: ["Campbell Exstrophy", "Gearhart / Jeffs modern staged repair", "EAU Paediatric"],
    answer: [
      { t: "h", v: "Anatomy of the complex" },
      { t: "ul", v: [
        "Failed cloacal membrane reinforcement → ruptured abdominal wall, open bladder plate, open pelvic ring (pubic diastasis), short anterior perineum, anus anterior, diverging levators.",
        "Male: complete epispadias, dorsal chordee, short urethral plate, splayed corpora attached to the separated pubic rami, prostate and bladder neck open, vas/veru on the plate.",
        "Female: bifid clitoris, short vagina, open BN, uterine anomalies sometimes, mons separated.",
        "Upper tracts usually normal at birth; adult untreated → squamous metaplasia, chronic infection, adenocarcinoma / SCC risk of the plate, renal damage from incompetence and scarring.",
        "Associated: inguinal hernia, rectal prolapse, uterine prolapse later, short bowel rarely in cloacal exstrophy (OEIS).",
      ]},
      { t: "h", v: "Adult surgical options" },
      { t: "p", v: "Adults present untreated (rare), with failed childhood reconstruction (incontinence, stones, fistula, malignancy, sexual dysfunction), or for undiversion / QOL." },
      { t: "ul", v: [
        "Work-up: renal function, imaging, cystoscopy of the plate / residual bladder, fertility, psychosexual, cancer surveillance of remnants.",
        "If a small, hostile residual bladder: cystectomy (cancer risk) + incontinent conduit or continent pouch (Indiana) — often the honest adult operation.",
        "If a reasonable capacity bladder after childhood closure but wet: augmentation + BN reconstruction / sling / AUS ± Mitrofanoff. Success is lower than in well-staged childhood repairs.",
        "Male genitalia: epispadias repair (Modified Cantwell–Ransley / Mitchell complete penile disassembly) for direction of stream and appearance; ED is common (corporal disproportion); prosthesis later.",
        "Female: epispadias / BN repair, vaginoplasty, monsplasty, uterine suspension if prolapse.",
        "Orthopaedic osteotomy is a childhood tool; rarely useful in stiff adult pelvis.",
        "Malignancy: inspect / biopsy any remnant; lifelong.",
      ]},
      { t: "tip", k: "exam", v: "Adult exstrophy is often a diversion + genital reconstruction problem, not a primary CPRE problem. Mention cancer of the plate." },
    ],
  },
  {
    id: "martius-vvf",
    topicId: "bladder",
    title: "Grafts, flaps and the Martius flap for trigonal VVF",
    highYield: true,
    gold: false,
    tags: ["VVF", "Martius", "flap", "graft"],
    exams: [
      { session: "Jun", year: 2017, marks: "2+8", stem: "Define grafts and flaps? Explain briefly the rationale and technique of harvesting Martius (labial) flap in the management of trigonal VVF." },
    ],
    related: ["bmg", "augmentation-urethroplasty", "bladder-trauma"],
    references: ["Campbell Fistula", "EAU iatrogenic trauma", "Martius H. 1928"],
    answer: [
      { t: "p", v: "A graft is tissue transferred without its own blood supply, surviving by imbibition then inosculation (e.g. buccal mucosa). A flap is tissue transferred with its own arterial inflow (and venous outflow) — random (subdermal plexus) or axial (named vessel)." },
      { t: "h", v: "Why an interposition flap in trigonal VVF" },
      { t: "ul", v: [
        "Trigonal / juxtacervical obstetric or post-hysterectomy fistulae have a scarred, poorly vascular, often radiated or infected bed and sit where bladder and vagina share a thin septum. Interposition brings blood, fills dead space, and separates suture lines so they do not stack.",
        "Martius (modified): fibrofatty labial pad on an axial/random supply from posterior labial branches of internal pudendal (posterior pedicle) or external pudendal (anterior). For trigonal / mid-vaginal VVF the posterior-pedicled Martius is the workhorse of a vaginal repair.",
      ]},
      { t: "h", v: "Harvest — steps" },
      { t: "ul", n: true, v: [
        "Lithotomy, fistula defined (cystoscopy, ureteric catheters if close to orifices — trigonal VVF often is).",
        "Vaginal incision, flaps, fistula dissection, bladder closed without tension in 1–2 layers, absorbable, watertight.",
        "Vertical incision over labium majus. Develop a fat pad from labial fat/bulbocavernosus, preserving the posterior pedicle (or anterior if needed for distal vagina / urethra).",
        "Tunnel the pad beneath the vaginal wall into the fistula field; tack over the bladder closure without compressing the pedicle.",
        "Close vagina; close labial incision over a small drain; leave a Foley 10–14 d; oestrogen if postmenopausal; sexual rest.",
      ]},
      { t: "p", v: "Alternatives: peritoneal flap (transabdominal O’Connor), omentum, gracilis (large / radiated), gluteal. Abdominal approach if ureteric reimplant needed, small vagina, or high / radiation fistula." },
      { t: "tip", k: "gold", v: "Graft = no blood supply. Flap = blood supply. Martius is a labial fat flap on a pudendal pedicle that keeps bladder and vaginal suture lines apart." },
    ],
  },
  {
    id: "continent-pouch",
    topicId: "bladder",
    title: "Continent catheterising pouches — general techniques",
    highYield: true,
    gold: false,
    tags: ["Indiana", "Mitrofanoff", "Kock", "Mainz"],
    exams: [
      { session: "Jun", year: 2015, marks: "10", stem: "Various general techniques employed to create a continent catheterizing pouch." },
    ],
    related: ["ileal-neobladder", "diversion-segments", "augmentation-cystoplasty"],
    references: ["Campbell Continent diversion", "Indiana / Kock / Mainz / Mitrofanoff original descriptions", "EAU diversion"],
    answer: [
      { t: "p", v: "A continent catheterisable pouch needs (1) a low-pressure detubularised reservoir, (2) an anti-reflux or at least a safe upper-tract join, (3) a continent, catheterisable efferent limb, (4) a site the patient can see and reach." },
      { t: "h", v: "Reservoir techniques" },
      { t: "ul", v: ["Detubularise ileum / colon / ileocaecum (Laplace)", "Folding: Heineke–Mikulicz, Studer U, Hautmann W, Indiana caecum + plicated ileum", "Serous-lined extraserosal tunnel (Abol-Enein) for ureters / efferent"] },
      { t: "h", v: "Continence / efferent mechanisms" },
      { t: "tbl", h: ["Mechanism", "Example", "How it stays dry"], r: [
        ["Ileocaecal valve + plicated terminal ileum", "Indiana, Mainz I", "Native valve reinforced by Lembert plication / stapler; 12–14F CIC"],
        ["Intussuscepted nipple", "Kock pouch", "Nipple valve — historic, desusception / stones on staples"],
        ["Mitrofanoff principle", "Appendix / Monti / Yang-Monti / spiral Monti to bladder or pouch, tunnelled submucosally", "Flap-valve: as pouch fills, tunnel compresses the tube (like a ureteric reimplant)"],
        ["Benchekroun hydraulic valve, tapered ileum (Casale)", "Variants", "Know names"],
        ["Urethra as outlet", "Orthotopic neobladder", "Native sphincter — not a ‘catheterising’ pouch unless CIC used"],
      ]},
      { t: "ul", v: [
        "Ureteric implantation: Nesbit, Wallace, Le Duc, afferent isoperistaltic limb, extraserosal tunnel, split-nipple.",
        "Stoma: umbilical (hidden, shorter appendix) vs right iliac fossa (easier in obese / wheelchair). Flush, catheterisable, not stenosed (V-flap skin).",
        "Complications: stomal stenosis (commonest long-term), incontinence of stoma, pouch stones, rupture, metabolic (same as segment used), difficulty CIC (false passage).",
      ]},
      { t: "tip", k: "gold", v: "Three parts: sphere (detubularised bowel), tunnel or valve (continence), and a stoma the patient can hit with a catheter at 2 a.m. Mitrofanoff = flap-valve; Indiana = ileocaecal valve." },
    ],
  },
  {
    id: "augmentation-cystoplasty",
    topicId: "bladder",
    title: "Augmentation cystoplasty",
    highYield: true,
    gold: true,
    tags: ["clam ileocystoplasty", "NGB", "MMC", "metabolic"],
    exams: [
      { session: "Dec", year: 2014, marks: "2+4+4", stem: "Contemporary indications, technique and long term complications of augmentation cystoplasty." },
    ],
    related: ["ileal-neobladder", "lpp-mmc", "sci-ngb", "continent-pouch", "compliance-dlpp"],
    references: ["EAU Neuro-Urology", "Campbell Bladder augmentation", "ICCS paediatric"],
    answer: [
      { t: "h", v: "Contemporary indications" },
      { t: "ul", v: [
        "Hostile NGB (MMC, SCI) with poor compliance / DLPP >40 / hydronephrosis failing CIC + drugs + Botox.",
        "Incontinence from a small non-compliant bladder when the outlet will be addressed in the same sitting or is competent.",
        "TB / schisto contracted bladder after disease control, with salvageable urethra / kidneys.",
        "Selected inflammatory (IC/BPS) last-line — declining.",
        "Undiversion. Not first-line idiopathic OAB (SNM/Botox).",
      ]},
      { t: "h", v: "Technique (clam ileocystoplasty)" },
      { t: "ul", n: true, v: [
        "CIC training and consent for mucus, stones, perforation, B12, cancer surveillance, pregnancy.",
        "25–30 cm of preterminal ileum on a reliable pedicle, bowel continuity restored.",
        "Bladder opened in the coronal (or sagittal) plane from one ureteric orifice vicinity to the other — a true clam, otherwise a diverticulum forms.",
        "Ileum detubularised, folded, sewn to bladder as a patch with absorbable suture. Ureteric reimplant if reflux / obstruction. Mitrofanoff / sling as needed.",
        "Suprapubic + urethral catheters, irrigate mucus, cystogram at 3 weeks.",
      ]},
      { t: "h", v: "Long-term complications" },
      { t: "ul", v: ["Mucus, stones, UTI, CIC dependence (almost universal in NGB)", "Metabolic hyperchloraemic acidosis, B12, bone", "Perforation (often intraperitoneal, during CIC — an emergency)", "Incontinence if outlet ignored", "BPO / mucus retention", "Malignancy (adenocarcinoma of patch — long latency; investigate haematuria; routine endoscopy controversial after 10 y)", "Bowel disturbance, B12", "Failure of compliance if patch too small or not detubularised"] },
      { t: "tip", k: "gold", v: "Clam the bladder, detubularise the bowel, teach CIC, warn about perforation. Augmentation without an emptying plan is a high-pressure time-bomb." },
    ],
  },
];
