import type { Master } from "../types";

export const drugs: Master[] = [
  {
    id: "antimuscarinics",
    topicId: "drugs",
    title: "Antimuscarinics and M3 blockade in urology",
    highYield: true,
    gold: true,
    tags: ["OAB", "M3", "darifenacin", "solifenacin"],
    exams: [
      { session: "Jun", year: 2017, marks: "2+3+2+3", stem: "What are M-3 receptor blockers? What are their indications, dosage and side effects?" },
      { session: "Dec", year: 2022, marks: "3+2+5", stem: "Indications for anti-muscarinic drugs in Urology. Which muscarinic receptors predominate in human bladder and which are most relevant? Side effects and contemporary alternatives." },
    ],
    related: ["mirabegron", "oab", "bcg-toxicity"],
    references: ["EAU Non-neurogenic Male / Female LUTS", "Andersson KE. Pharmacol Rev", "Campbell OAB pharmacology"],
    answer: [
      { t: "p", v: "Five muscarinic receptor subtypes (M1–M5). Human detrusor: M2 numerically predominant (~70–80%) but M3 is the functionally relevant receptor for contraction (phospholipase C → IP3 → Ca²⁺). M2 may inhibit β-adrenergic relaxation (Gi). Urothelium and afferent nerves also carry M2/M3 — afferent modulation explains sensory benefit." },
      { t: "h", v: "Indications" },
      { t: "ul", v: ["Idiopathic OAB / urgency incontinence", "Neurogenic detrusor overactivity (NDO) — SCI, MS (often + CIC)", "BOO with storage symptoms after α-blocker (caution residual)", "Night-time incontinence in NGB if Pdet high", "Bladder spasm after TURBT/TURP (short course)"] },
      { t: "tbl", c: "Agents — doses examiners expect", h: ["Drug", "Selectivity", "Dose", "Pearl"], r: [
        ["Oxybutynin IR / ER / patch / gel", "Non-selective + direct muscle relaxant", "IR 2.5–5 mg TDS; ER 5–15 mg OD; patch 3.9 mg/d", "Cheapest; worst CNS/dry mouth. Patch avoids first-pass."],
        ["Tolterodine", "Non-selective, bladder-preferring PK", "2 mg BD or ER 4 mg", "Classic comparator in trials"],
        ["Solifenacin", "M3-preferring", "5–10 mg OD", "FLEX / STAR trials"],
        ["Darifenacin", "Most M3-selective", "7.5–15 mg OD", "Less M1 → theoretically less cognitive hit"],
        ["Fesoterodine", "Prodrug → 5-HMT (same as tolterodine)", "4–8 mg OD", "Flexible dose"],
        ["Trospium", "Quaternary amine, non-selective", "20 mg BD or XR 60 mg", "Does not cross BBB — elderly / CNS"],
        ["Propiverine", "Mixed", "30 mg OD", "Used in NDO in some regions"],
      ]},
      { t: "h", v: "Side effects & cautions" },
      { t: "ul", v: ["Dry mouth, constipation, blurred vision, GERD, tachycardia", "Cognitive impairment / delirium — tertiary amines in elderly (Beers); prefer trospium / mirabegron / vibegron", "Retention if PVR high or frail men with BOO — check PVR", "Contraindicated: untreated narrow-angle glaucoma, myasthenia, severe UC/toxic megacolon, gastric retention", "CYP3A4 interactions (solifenacin, darifenacin)"] },
      { t: "h", v: "Contemporary alternatives (Dec 22 part c)" },
      { t: "ul", v: ["β3 agonists: mirabegron 50 mg, vibegron 75 mg — similar efficacy, better dry-mouth profile; watch BP (mirabegron)", "Combination solifenacin + mirabegron (BESIDE, SYNERGY) for incomplete responders", "Intradetrusor botulinum A 100 U idiopathic / 200 U NDO", "PTNS, sacral neuromodulation (ROSETTA)", "Desmopressin melt for nocturnal polyuria (Na monitor)", "Lifestyle, caffeine, weight, pelvic floor — always first"] },
    ],
  },
  {
    id: "mirabegron",
    topicId: "drugs",
    title: "Mirabegron — pharmacotherapeutics",
    highYield: true,
    gold: false,
    tags: ["OAB", "beta3"],
    exams: [
      { session: "Jun", year: 2016, marks: "2+8", stem: "What is Mirabegron? Discuss its pharmaco therapeutics." },
      { session: "Dec", year: 2021, marks: "3+2", stem: "Pharmacokinetics of mirabegron, uses and side effects. European-Australian phase 3 trial on mirabegron." },
    ],
    related: ["antimuscarinics", "oab"],
    references: ["SCORPIO / ARIES / CAPRICORN phase 3", "BESIDE combination", "EAU Female LUTS"],
    answer: [
      { t: "p", v: "Mirabegron is an oral selective β3-adrenoceptor agonist. β3 receptors dominate human detrusor sympathetic relaxation (cAMP–PKA → decrease intracellular Ca, plus BK channel). Storage-phase relaxation without blocking the M3 voiding contraction — theoretically safer for PVR than antimuscarinics." },
      { t: "ul", v: [
        "PK: oral bioavailability ~29–35%, t½ ~50 h, steady state day 7, hepatic CYP3A4/2D6 + renal. Dose 25–50 mg OD (25 mg if CrCl 15–29 or strong CYP3A4 inhibitor).",
        "Efficacy: −1.0 to −1.5 micturitions and −0.4 incontinence episodes vs placebo; comparable to tolterodine 4 mg with less dry mouth (SCORPIO).",
        "AE: hypertension (monitor BP; avoid in severe uncontrolled HTN ≥180/110), tachycardia, UTI, nasopharyngitis, rare QT, angioedema. CYP2D6 inhibitor → metoprolol, desipramine levels.",
        "Uses: OAB wet/dry, NDO off-label / emerging, combination with solifenacin, men on α-blocker.",
      ]},
    ],
  },
  {
    id: "furosemide",
    topicId: "drugs",
    title: "Furosemide in urology",
    highYield: false,
    gold: false,
    tags: ["diuretic", "renogram", "hyperK"],
    exams: [
      { session: "Jun", year: 2019, marks: "4+6", stem: "Furosemide: Elaborate on its mode of action. Specify its uses in Urology along with dosage." },
    ],
    related: ["diuretic-renogram", "hyperkalemia", "hypercalcemia"],
    references: ["Goodman & Gilman", "O'Reilly diuretic renogram protocol"],
    answer: [
      { t: "p", v: "Loop diuretic: secretes into proximal tubule (OAT1) then blocks NKCC2 on TAL thick ascending limb → abolishes the cortico-medullary gradient, massive natriuresis, increased PGE2, venodilation (even before diuresis)." },
      { t: "tbl", h: ["Use", "Dose / protocol", "Note"], r: [
        ["F−15 / F+0 / F+10 MAG3 renogram", "0.5 mg/kg IV (adult 20–40 mg; max 40 if normal GFR, higher in CKD)", "O'Reilly: F−15 most specific for obstruction"],
        ["Hyperkalaemia (after Ca gluconate / insulin)", "40–80 mg IV", "Needs residual GFR"],
        ["Hypercalcaemia after volume", "20–40 mg IV", "Not first-line"],
        ["SIADH / TURP overload / nephrotic", "variable", "Free-water clearance"],
        ["Forced diuresis in rhabdomyolysis / tumour lysis (selected)", "titrate to UO 200 mL/h", "Evidence mixed"],
        ["Cirrhotic / HF peri-op oedema", "oral 20–80 mg", "Watch K, Mg"],
      ]},
      { t: "p", v: "AE: hypokalaemia, hypomagnesaemia, metabolic alkalosis, ototoxicity (rapid IV), sulphonamide allergy (rare cross), interstitial nephritis, precipitating gout / lithiasis (volume contraction raises urine Ca but loops are calciuric — unlike thiazides)." },
    ],
  },
  {
    id: "stewardship",
    topicId: "drugs",
    title: "Antibiotic stewardship and surgical prophylaxis",
    highYield: true,
    gold: true,
    tags: ["antibiotics", "cystoscopy", "biopsy", "CAUTI"],
    exams: [
      { session: "Dec", year: 2022, marks: "5+5", stem: "Discuss Antibiotic stewardship in Urology. Recommended surgical prophylaxis for office cystoscopy and prostate biopsy." },
      { session: "Jun", year: 2019, marks: "3+2+3+2", stem: "Antimicrobial prophylaxis in elective urological surgery: Concept, importance, recommendations and outcome." },
    ],
    related: ["imipenem", "cauti", "uti-pregnancy"],
    references: ["EAU Urological Infections 2024", "AUA Best Practice Antimicrobial Prophylaxis", "WHO stewardship"],
    answer: [
      { t: "p", v: "Stewardship = right drug, dose, duration, de-escalation, to maximise cure and minimise resistance, C. difficile and cost. Urology is a high-volume antibiotic specialty (prophylaxis, ASB misuse, fluoroquinolone residual)." },
      { t: "ul", v: [
        "Never treat asymptomatic bacteriuria except: pregnancy, before urologic instrumentation that breaches mucosa, neutropenia / transplant immediate peri-op.",
        "Culture before treatment in complicated UTI / pyelo / prostatitis; 7 days usually enough for pyelo if responding (EAU); 14 days prostatitis acute, 4–6 wk chronic.",
        "Avoid FQ as default (FDA/EMA warnings: tendon, aneurysm, neuropathy) — especially biopsy prophylaxis after the 2016–18 resistance spike.",
        "Local antibiogram drives empiric choice (Dec 22 sepsis paper).",
        "IV-to-oral switch, stop-date on every chart, audit + feedback.",
      ]},
      { t: "tbl", c: "Prophylaxis (EAU / AUA distilled)", h: ["Procedure", "Risk class", "Prophylaxis?"], r: [
        ["Office cystoscopy, UDS, removal of catheter", "Clean-contaminated, intact mucosa", "No, if urine sterile. Yes if ABU + forthcoming mucosal breach / neutropenia / prosthetic valve per local policy"],
        ["Cystoscopy + biopsy / Fulguration", "Mucosal breach", "Single dose (aminoglycoside or co-amox or peri-procedure TMP-SMX)"],
        ["TRUS biopsy (historical)", "High infection", "FQ 1–3 doses — now discouraged as monotherapy"],
        ["Transperineal biopsy (current preferred)", "Low sepsis (<1%)", "Often none or single IV dose; EAU favours transperineal"],
        ["TRUS if still used", "Targeted", "Rectal swab targeted prophylaxis OR augmented (aminoglycoside + β-lactam) OR fosfomycin 3 g PO × 2"],
        ["TURP / TURBT", "Clean-contaminated", "Single dose at induction covering enteric Gram-negatives ± enterococcus"],
        ["PCNL / URS", "Infected stones possible", "Culture-directed; continue if struvite / infection stone"],
        ["Clean (orchidopexy, circumcision)", "Clean", "No"],
        ["Implants (IPP, AUS, mesh)", "Clean + foreign body", "Peri-op Gram+ and Gram− cover; some use rifampin-soaked devices"],
      ]},
      { t: "tip", k: "gold", v: "Outcome data: single-dose = multiple-dose for TURP infection prevention; transperineal biopsy sepsis ~0.1–0.5% vs TRUS 1–3% in FQ-resistance era. Stewardship cuts FQ use without raising sepsis when biopsy route changes." },
    ],
  },
  {
    id: "imipenem",
    topicId: "drugs",
    title: "Imipenem — dosage, indications, limitations",
    highYield: false,
    gold: false,
    tags: ["carbapenem", "ESBL", "sepsis"],
    exams: [
      { session: "Dec", year: 2016, marks: "2+4+4", stem: "Dosage, indications and limitations of the use of imipenem." },
    ],
    related: ["septic-shock", "esbl"],
    references: ["Sanford Guide", "EAU Infections — MDRO", "IDSA 2023 Gram-neg resistance"],
    answer: [
      { t: "p", v: "Imipenem is a carbapenem, always co-formulated with cilastatin (DHP-1 inhibitor that otherwise hydrolyses imipenem in the proximal tubule and causes nephrotoxicity)." },
      { t: "ul", v: [
        "Dose: 500 mg–1 g IV q6h (max 4 g/d). Infuse 30 min. Reduce in CKD (CrCl <70). Not oral.",
        "Spectrum: ESBL Enterobacterales, anaerobes, MSSA, streptococci, many Pseudomonas (less reliable than meropenem/doripenem). No MRSA, no Stenotrophomonas, no Enterococcus faecium, weak Proteus/Morganella (prefer meropenem).",
        "Urologic indications: severe ESBL urosepsis, emphysematous pyelonephritis, Fournier polymicrobial, post-PCNL septic shock pending cultures. De-escalate at 48 h.",
        "Limitations: seizures (especially high dose + renal failure + CNS lesions — imipenem worse than meropenem), cilastatin cost, selects carbapenemases (NDM, KPC, OXA-48) — last-resort stewardship, no dual Pseudomonas cover routinely, anaphylaxis if severe penicillin allergy (rate ~1%).",
      ]},
    ],
  },
];
