import type { Master } from "../types";

export const functional: Master[] = [
  {
    id: "sui-slings",
    topicId: "functional",
    title: "SUI surgery, mid-urethral slings and complications",
    highYield: true,
    gold: true,
    tags: ["SUI", "MUS", "TOT", "TVT", "injectables", "BOO"],
    exams: [
      { session: "Dec", year: 2022, marks: "4+6", stem: "Enlist surgical options for stress incontinence in females. Enumerate complications of mid-urethral sling surgery and their prevention." },
      { session: "Jun", year: 2016, marks: "2+3+5", stem: "Define Stress Urinary Incontinence (SUI). List the surgical management for SUI. Future of injectables for SUI." },
      { session: "Dec", year: 2020, marks: "6+4", stem: "What is the rationale of mid-urethral slings and pubovaginal slings in women with stress-urinary incontinence? What are different types of midurethral sling procedures?" },
      { session: "Jun", year: 2017, marks: "4+6", stem: "Concept behind the mid-urethral sling in the management of SUI. Technique of placement of Transobturator tape (TOT)." },
      { session: "Jun", year: 2018, marks: "10", stem: "Mid urethral slings." },
      { session: "Dec", year: 2014, marks: "10", stem: "Current status of mid urethral slings in female incontinence." },
      { session: "Jun", year: 2014, marks: "6+4", stem: "Merits and demerits of various urethral slings used in the management of SUI. How would you manage bladder outlet obstruction following sling procedure?" },
    ],
    related: ["continence-mechanism", "incontinence-eval-female", "lpp-mmc", "ppi"],
    references: [
      "ICS / IUGA terminology",
      "EAU Non-neurogenic Female LUTS / Urinary Incontinence",
      "AUA/SUFU SUI guideline",
      "Ulmsten TVT; Delorme TOT; Petros–Ulmsten integral theory",
      "Campbell-Walsh-Wein, Surgery for SUI",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map (10 marks)", v: "ICS definition 1 · Continence theories / why mid-urethra 2 · Menu of operations 2 · MUS types and TOT steps 2 · Complications + prevention 2 · BOO after sling 1. Draw the three-level DeLancey support and the TOT needle path (protected by the obturator internus / levator)." },
      { t: "h", v: "Definition (ICS)" },
      { t: "p", v: "Stress urinary incontinence is the complaint of involuntary leakage on effort or exertion, or on sneezing or coughing. Urodynamic SUI is the observation of involuntary leakage during filling cystometry, associated with increased intra-abdominal pressure, in the absence of a detrusor contraction." },
      { t: "h", v: "Rationale — why a sling at all" },
      { t: "ul", v: [
        "DeLancey: three levels of vaginal support. Level III (perineal membrane / distal urethra) and the mid-urethral hammock (pubocervical fascia, pubourethral ligaments) fail in SUI.",
        "Integral theory (Petros–Ulmsten): mid-urethra is the fulcrum; a tension-free tape recreates the pubourethral ligament so the urethra kinks against a firm backboard during cough.",
        "McGuire / ISD: a poorly functioning sphincter (VLPP <60 cm H2O, open bladder neck at rest, radiation, neurogenic, prior surgery) needs more compression — classic indication for a tight pubovaginal fascial sling rather than a tension-free MUS.",
        "Pubovaginal sling (autologous rectus / fascia lata) sits at bladder neck, is compressive, and is the salvage / ISD / mesh-avoidance operation.",
        "MUS sits at mid-urethra, is tension-free at rest, and supports only when abdominal pressure rises.",
      ]},
      { t: "tbl", c: "Surgical menu — write this table", h: ["Operation", "Mechanism", "Best for", "Caveat"], r: [
        ["Mid-urethral sling (retropubic TVT / TOT / mini-sling)", "Tension-free mid-urethral support", "Hypermobility, primary SUI, VLPP usually >60", "Mesh era; avoid in ISD, radiation, fistula, low-pressure urethra"],
        ["Autologous pubovaginal sling", "Bladder-neck compression", "ISD, mesh complications, neurogenic, failed MUS", "Voiding dysfunction, harvest morbidity"],
        ["Burch / laparoscopic / robotic colposuspension", "Elevates paraurethral vagina to Cooper ligament", "Need for concomitant open/lap prolapse or mesh-averse", "Less used as primary; GSI-92 showed TVT non-inferior"],
        ["Bulking (bulkamid, macroplastique, carbon-coated Zr)", "Coaptation of urethra", "Frail, ISD, anaesthetic risk, temporising", "Repeat injections; inferior durability"],
        ["AUS (female, selected)", "Circumferential compression", "Catastrophic ISD after multiple failures", "Erosion in radiated / neurogenic"],
        ["Artificial / adjustable slings, MMK (historical)", "—", "Know names only", "MMK abandoned (osteitis, obstruction)"],
      ]},
      { t: "h", v: "Types of mid-urethral sling" },
      { t: "ul", v: [
        "Retropubic bottom-up (TVT, Ulmsten 1996): trocars through retropubic space to suprapubic skin. Highest efficacy; highest bladder / bowel / major-vessel risk.",
        "Retropubic top-down (SPARC): opposite needle direction; similar mechanics.",
        "Transobturator outside-in (TOT, Delorme): around the ischiopubic ramus through obturator foramen. Less bladder injury; more groin pain / obturator neuralgia.",
        "Transobturator inside-out (TVT-O, de Leval): helical passer from vagina out.",
        "Single-incision mini-slings (SIMS): shorter tape, no exit wounds. Meta-analyses: slightly lower subjective cure than full-length MUS; reserved / evolving.",
      ]},
      { t: "h", v: "TOT — steps the examiner wants" },
      { t: "ul", n: true, v: [
        "Lithotomy, antibiotic, empty bladder, weighted speculum, local ± GA/spinal.",
        "Anterior vaginal incision at mid-urethra (~1.5 cm), periurethral tunnels to inferior pubic ramus.",
        "Skin stab over obturator foramen: 1 cm lateral to the ischiopubic ramus, at the level of the clitoris (genitofemoral crease) — not too lateral (obturator nerve) and not too medial (urethra).",
        "Helical passer hugs the ramus, exits in the vaginal tunnel (outside-in) or reverse (inside-out). Tape lies flat, tension-free: a scissors or 8F Hegar between tape and urethra; cough test if awake.",
        "Cystoscopy is mandatory after retropubic MUS; still wise after TOT (rare perforation). Cut vaginal mucosa, close without including tape, leave a catheter overnight.",
      ]},
      { t: "h", v: "Complications of MUS and prevention" },
      { t: "tbl", h: ["Complication", "Prevention / recognition", "Treatment"], r: [
        ["Bladder / urethral perforation", "Empty bladder, cystoscopy, retropubic > TOT", "Reposition; abort if urethral injury; catheter 5–14 d"],
        ["Vascular (retropubic venous plexus, external iliac)", "Stay on bone, no wandering laterad", "Packing, exploration rare; know Corona mortis"],
        ["Bowel injury (retropubic, prior incision)", "Avoid RP MUS after extensive lower abdominal surgery", "Laparotomy — disaster if missed"],
        ["Obturator neuralgia / groin pain (TOT)", "Hug ramus, avoid too-lateral exit", "NSAIDs, injections, tape-cut / explant"],
        ["Voiding dysfunction / BOO (2–8%)", "Tension-free; avoid over-elevation", "See algorithm below"],
        ["De novo urgency (5–15%)", "Exclude pre-op OAB; do not obstruct", "Antimuscarinic / mirabegron / later tape-lysis"],
        ["Vaginal extrusion / urethral erosion", "Full-thickness vaginal flaps, delayed sex 6 wk, no infected field", "Local excision vs complete explant"],
        ["UTI, haematoma, dyspareunia, mesh litigation", "Sterile kit, counselling (FDA / MHRA mesh pause)", "Document consent; autologous alternative"],
      ]},
      { t: "h", v: "BOO after sling" },
      { t: "flow", title: "Sling obstruction", nodes: [
        { id: "a", kind: "start", label: "Poor stream / retention / high PVR after MUS", to: ["b"] },
        { id: "b", kind: "action", label: "Catheter, exclude haematoma / perforation, trial of void 3–7 d, α-blocker ± CIC", to: ["c"] },
        { id: "c", kind: "decision", label: "Still obstructed at 7–14 d?", to: ["d", "e"] },
        { id: "d", kind: "action", label: "Early tape loosening / midline cut (office or OT) if <2–3 wk and tape not scarred", to: ["f"] },
        { id: "e", kind: "end", label: "Resolved — observe SUI recurrence (~20–30% after cut)" },
        { id: "f", kind: "decision", label: "Late BOO (months) / failed loosening?", to: ["g"] },
        { id: "g", kind: "action", label: "UDS: high Pdet, low Qmax, hanging urethra. Urethrolysis ± tape excision ± later autologous sling if SUI returns", to: ["h"] },
        { id: "h", kind: "end", label: "Do not do bladder-neck incision as first move in a woman" },
      ]},
      { t: "h", v: "Injectables — current status" },
      { t: "ul", v: [
        "Mechanism: increase urethral coaptation. Best modest ISD, not hypermobility.",
        "Materials: polyacrylamide hydrogel (Bulkamid), polydimethylsiloxane (Macroplastique), carbon-coated zirconium, historical collagen / Teflon (migration).",
        "Future / present: office, local anaesthetic, repeatable; cure ~30–50% and decays. Not a replacement for sling in a fit woman with hypermobility. Useful after radiation, with AUS, or when mesh is declined.",
      ]},
      { t: "h", v: "Current status of MUS (the Dec 14 / mesh-era paragraph)" },
      { t: "p", v: "MUS remains the most studied anti-incontinence operation (TVT vs Burch, TOMUS RP vs TO). Subjective cure ~80% at 1 year, ~60–70% at 5 years. Regulatory mesh alerts (FDA 2011, UK pause) apply mainly to transvaginal prolapse mesh; MUS is still guideline-supported after documented counselling, but many Indian / UK units now default to autologous fascial sling when patients decline mesh. Mini-slings have not displaced full-length MUS." },
      { t: "tip", k: "gold", title: "Gold line", v: "Tension-free mid-urethra for hypermobility; compressive bladder-neck fascia for ISD. Cystoscope every retropubic tape. BOO after sling is cut early, urethrolyse late — never TUR the female bladder neck first." },
    ],
  },
  {
    id: "continence-mechanism",
    topicId: "functional",
    title: "Male and female continence mechanism and SUI pathophysiology",
    highYield: true,
    gold: true,
    tags: ["continence", "DeLancey", "ISD", "hypermobility", "rhabdosphincter"],
    exams: [
      { session: "Jun", year: 2021, marks: "5+5", stem: "Describe urinary continence mechanism in male and female. Discuss pathophysiology of stress incontinence in female." },
      { session: "Dec", year: 2012, marks: "4+6", stem: "Describe urinary continence mechanism in females. Discuss pathophysiology of stress urinary incontinence." },
    ],
    related: ["sui-slings", "ppi", "micturition-neuro", "lpp-mmc"],
    references: [
      "DeLancey JO. Am J Obstet Gynecol — three levels of support",
      "ICS Standardisation",
      "Campbell-Walsh-Wein, Physiology of micturition / Incontinence",
      "EAU Female LUTS",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Draw: (1) male rhabdosphincter as a horseshoe around membranous urethra with posterior fibrous raphe (why nerve-sparing and urethral-length preservation matter after RP); (2) female hammock / pubourethral ligaments / compressor urethrae. Then two-path SUI: hypermobility vs ISD." },
      { t: "h", v: "Shared building blocks" },
      { t: "ul", v: [
        "Bladder: low-pressure filling (compliance, viscoelasticity, β3 sympathetic relaxation) so detrusor pressure stays below outlet resistance.",
        "Bladder neck / internal sphincter: circular smooth muscle, α1-adrenergic, closed during storage (more important in the male).",
        "External urethral sphincter (rhabdosphincter): slow-twitch fibres, Onuf nucleus S2–4 via pudendal and intramural somatic fibres, guarding reflex.",
        "Urethral mucosa and vascular cushion: a mucosal seal; oestrogen-sensitive in women.",
        "Pelvic floor (levator ani, especially pubococcygeus / puborectalis): reflex contraction with cough (L1–S4).",
        "Neural switch: PMC off, pontine storage centre on; intact Onuf.",
      ]},
      { t: "h", v: "Male-specific" },
      { t: "tbl", h: ["Structure", "Role", "Surgical pearl"], r: [
        ["Bladder neck / pre-prostatic sphincter", "Smooth-muscle continence; antegrade ejaculation", "Lost after TURP / bladder-neck reconstruction — stress leak uncommon if rhabdosphincter intact"],
        ["Prostate and prostatic urethra", "Passive resistance", "BPH can mask sphincteric weakness"],
        ["Membranous rhabdosphincter", "Primary continence after prostatectomy; omega-shaped, deficient posteriorly", "Preserve urethral length, puboprostatic ligaments, nerves (NVB), and reconstruct posterior rhabdosphincter (Rocco)"],
        ["Bulbar urethra / corpus spongiosum", "Secondary seal", "Not a true sphincter"],
        ["Levator / puboperinealis", "Support and reflex", "Nerve-sparing and avoiding levator trauma"],
      ]},
      { t: "h", v: "Female-specific (DeLancey)" },
      { t: "ul", v: [
        "Level I: cardinal–uterosacral complex suspends the vaginal apex. Failure → vault / uterine prolapse, not isolated SUI.",
        "Level II: paravaginal attachments of pubocervical fascia to arcus tendineus fascia pelvis. Failure → cystocoele.",
        "Level III: perineal membrane, distal vagina, urethral supports. Failure → urethral hypermobility and SUI.",
        "Hammock hypothesis: urethra is compressed against a firm anterior vaginal wall during intra-abdominal pressure rise. If the hammock is lax, force is not converted into closing pressure.",
        "Pubourethral ligaments (mid-urethra) are the surgical target of MUS.",
        "Compressor urethrae and urethrovaginal sphincter (deep perineal pouch) add distal tone.",
        "Intrinsic urethral function: smooth muscle, striated sphincter, mucosa, vascular plexus — the ‘seal’.",
      ]},
      { t: "h", v: "Pathophysiology of female SUI" },
      { t: "p", v: "Two overlapping mechanisms (McGuire). Most women have a mixture." },
      { t: "tbl", h: ["", "Hypermobility (anatomic SUI)", "Intrinsic sphincter deficiency"], r: [
        ["Cause", "Loss of hammock / pubourethral support (parity, ageing, connective tissue, chronic strain)", "Open, poorly coapting urethra (prior surgery, radiation, neurogenic, hypo-oestrogen, myelodysplasia)"],
        ["Q-tip / exam", "Hypermobile urethra >30°, often cystocoele", "Pipe-stem, fixed, pale urethra; leak with minimal effort"],
        ["VLPP", "Usually >90 cm H2O", "<60 cm H2O; 60–90 grey zone"],
        ["Video UDS", "Descent of BN and urethra; BN may be closed at rest", "BN open at rest, little descent"],
        ["Operation", "MUS / Burch / colposuspension", "Pubovaginal sling, bulking, AUS"],
      ]},
      { t: "ul", v: [
        "Risk factors: vaginal delivery (levator avulsion, pudendal stretch), parity, age, obesity, chronic cough / constipation, collagen disorders, smoking, hysterectomy (debated), first-degree relatives.",
        "Urethral length, closing pressure (MUCP) and abdominal pressure transmission (ΔUrethral / ΔAbdominal ≥1) all fall.",
        "Do not forget mixed incontinence: OAB plus SUI is the commonest real-world picture — treat the bother-dominant symptom first, never sling a woman with untreated high-pressure DO or retention.",
      ]},
      { t: "tip", k: "gold", v: "Male continence after RP is rhabdosphincter + functional urethral length. Female SUI is hammock failure ± ISD. VLPP <60 and a fixed empty urethra = ISD until proven otherwise." },
    ],
  },
  {
    id: "incontinence-eval-female",
    topicId: "functional",
    title: "Evaluation of a 30-year-old woman with incontinence",
    highYield: true,
    gold: false,
    tags: ["incontinence", "evaluation", "UDS", "ICS"],
    exams: [
      { session: "Dec", year: 2017, marks: "10", stem: "Evaluation of a 30 year old woman presenting with urinary incontinence of 1 year duration." },
    ],
    related: ["sui-slings", "continence-mechanism", "oab", "lpp-mmc"],
    references: ["EAU Female LUTS", "ICS Good Urodynamic Practices", "NICE NG123", "Campbell Incontinence evaluation"],
    answer: [
      { t: "tip", k: "exam", v: "Age 30 changes the differential: fistula after obstructed labour / LSCS, occult neurogenic (spina bifida occulta), fistula vs SUI vs OAB vs overflow, not just ‘do a sling’. Write a sequence, not a dump." },
      { t: "h", v: "History — classify the leak" },
      { t: "ul", v: [
        "ICS categories: stress, urgency, mixed, postural, insensible, coital, nocturnal enuresis, continuous (think fistula or ectopic ureter).",
        "Obstetric: deliveries, tears, forceps, prolonged labour, LSCS, vesicovaginal fistula, Gartner cyst, prior pelvic surgery.",
        "Storage vs voiding vs post-micturition; pads / hour; fluid, caffeine, constipation, UTI, haematuria, pain, prolapse bulge, faecal incontinence, sexual function.",
        "Red flags: continuous leak from childhood (ectopic ureter in duplex), neurological symptoms, recurrent UTI, pelvic surgery / radiation, haematuria, voiding difficulty.",
        "Questionnaires: ICIQ-UI SF, UDI-6, 3-day bladder diary with volumes (nocturnal polyuria, functional capacity).",
      ]},
      { t: "h", v: "Examination" },
      { t: "ul", v: [
        "BMI, gait, spine (sacral dimple, hair tuft), lower-limb neurology, sacral sensation, anal tone, bulbocavernosus reflex.",
        "Abdomen: distended bladder (overflow), scars.",
        "Pelvic (empty then full bladder): POP-Q, cough / Valsalva leak, Q-tip if used, fistula speculum (methylene blue / tampon test), urethral diverticulum, atrophy (less at 30), pelvic floor strength (Oxford).",
      ]},
      { t: "h", v: "Investigations — stratified" },
      { t: "tbl", h: ["Always", "Selective (this age often yes)", "Rare / specialist"], r: [
        ["Dipstick + culture, PVR, diary, pad test if quantifying", "Uroflow if voiding symptoms; renal US if recurrent UTI / fistula / neuro; creatinine", "Videourodynamics, MRI spine, CT/MR urogram for duplex/ectopic, cystoscopy + exam under anaesthesia for fistula"],
      ]},
      { t: "p", v: "UDS indications (EAU / NICE): voiding difficulty, neurogenic suspicion, prior incontinence / prolapse surgery, mismatch of history and exam, considering invasive treatment in mixed incontinence, continuous leak. A straightforward primary SUI with hypermobility and no red flags does not mandate UDS before MUS (NICE), but many Indian teaching units still do it — say so." },
      { t: "h", v: "UDS package if done" },
      { t: "ul", v: ["Free flow + PVR", "Filling CMG: sensation, compliance, capacity, DO, VLPP / ALPP, leak", "Voiding PFS (PdetQmax, Qmax, BOOI — female nomograms, not Abrams–Griffiths)", "EMG if neurogenic / DSD suspected", "Video if fistula, reflux, open BN, ectopic suspected"] },
      { t: "flow", title: "30-year-old incontinent woman", nodes: [
        { id: "a", kind: "start", label: "History + exam + diary + PVR + urine", to: ["b"] },
        { id: "b", kind: "decision", label: "Continuous leak?", to: ["c", "d"] },
        { id: "c", kind: "action", label: "Fistula / ectopic work-up (dye tests, cystoscopy, MR urogram)", to: ["e"] },
        { id: "d", kind: "decision", label: "Neuro signs / high PVR / childhood issues?", to: ["f", "g"] },
        { id: "f", kind: "action", label: "MRI spine + video UDS → NGB pathway", to: ["e"] },
        { id: "g", kind: "action", label: "Stress vs urgency vs mixed algorithm; treat reversible causes; pelvic floor; then sling / OAB Rx", to: ["e"] },
        { id: "e", kind: "end", label: "Never operate on uncharacterised continuous incontinence" },
      ]},
      { t: "tip", k: "gold", v: "At 30, first exclude fistula and ectopic ureter, then neurogenic bladder, then classify ICS type. Surgery without a diary and a PVR is an incomplete answer." },
    ],
  },
  {
    id: "lpp-mmc",
    topicId: "functional",
    title: "Leak point pressures and MMC bladder",
    highYield: true,
    gold: true,
    tags: ["DLPP", "VLPP", "MMC", "spina bifida", "McGuire"],
    exams: [
      { session: "Dec", year: 2022, marks: "4+6", stem: "Leak point pressures and their clinical implications. Management of a 20-year-female with meningomyelocele, urinary leaks and bilateral hydroureteronephrosis." },
    ],
    related: ["compliance-dlpp", "spina-bifida-lut", "sci-ngb", "sui-slings", "augmentation-cystoplasty"],
    references: [
      "McGuire EJ. J Urol 1981 — DLPP 40 cm H2O",
      "ICS Good Urodynamic Practices",
      "EAU Neuro-Urology",
      "Campbell Myelodysplasia / Meningomyelocele",
    ],
    answer: [
      { t: "h", v: "Leak point pressures — three numbers, two meanings" },
      { t: "tbl", h: ["", "Detrusor LPP (DLPP)", "Abdominal / Valsalva LPP (ALPP, VLPP)", "Cough LPP"], r: [
        ["Definition", "Lowest detrusor pressure at which leak occurs in the absence of a detrusor contraction or rise in Pabd (storage, typically neurogenic)", "Lowest Pabd (or Pves) at which leak occurs with Valsalva, no detrusor contraction", "Same with cough; more artefactual"],
        ["What it tests", "Outlet resistance against a poorly compliant / high-pressure bladder — upper-tract risk", "Sphincter quality in SUI (ISD vs hypermobility)", "SUI screening"],
        ["How", "Filling CMG, no strain; note Pdet at first leak; report filled volume", "Bladder ~200–300 mL; Valsalva; 7F catheter slightly overestimates vs 4F / rectal only", "Same"],
        ["Cut-offs", "McGuire: DLPP >40 cm H2O → hydronephrosis / VUR risk in MMC", "VLPP <60 ISD; >90 hypermobility; 60–90 mixed", "Not standardised as well"],
      ]},
      { t: "ul", v: [
        "DLPP is a storage safety metric. ALPP is a stress-continence metric. Do not mix them in the answer.",
        "A woman can leak at low ALPP (weak sphincter) and still have a deadly DLPP if you stop her leak with a tight sling without treating compliance.",
        "If the patient never leaks, DLPP cannot be measured — use end-fill Pdet, compliance (ΔV/ΔPdet), and the ‘safe’ pressure <40 cm H2O.",
        "Technique pitfalls: too-fast fill, 8F catheter obstructing, abdominal straining misread as detrusor, reporting Pves instead of Pdet.",
      ]},
      { t: "h", v: "The 20-year-old MMC woman — think ‘hostile bladder + incompetent outlet + threatened kidneys’" },
      { t: "p", v: "Classic host: sacral / lumbosacral dysraphism, often acontractile or poorly compliant bladder, open bladder neck, chronic retention with leak (overflow + stress), reflux and hydronephrosis from storage pressures, recurrent UTI, possible latex allergy, possible VP shunt, fertility / pregnancy issues, chronic kidney disease." },
      { t: "h", v: "Investigation" },
      { t: "ul", v: [
        "Labs: creatinine / eGFR, CBC, culture, bicarbonate (acidosis from reflux nephropathy).",
        "US + DMSA / MAG3: hydronephrosis, scars, split function.",
        "Video UDS: capacity, compliance, DLPP, DO, VUR grade, bladder neck, leak, residual. This single test drives surgery.",
        "Cystoscopy: stones, trabeculation, shunt if any, CIC trauma.",
        "Spine MRI if not recently imaged; latex protocol; bone / pressure-sore / wheelchair context.",
      ]},
      { t: "h", v: "Goals (EAU neuro-urology)" },
      { t: "ul", n: true, v: [
        "Protect the upper tracts (storage Pdet <40 cm H2O, treat VUR).",
        "Social continence.",
        "Preserve QOL, fertility, independence (CIC ability of hands / cognition).",
        "Avoid making a high-pressure system continent without first making it safe.",
      ]},
      { t: "flow", title: "MMC woman with leak + bilateral HDUN", nodes: [
        { id: "a", kind: "start", label: "Treat UTI, start CIC (or SPC if hands poor), antimuscarinic / mirabegron, low-pressure drainage", to: ["b"] },
        { id: "b", kind: "action", label: "Video UDS + upper tract imaging + GFR", to: ["c"] },
        { id: "c", kind: "decision", label: "Hostile storage (poor compliance / DLPP >40 / VUR) despite CIC + drugs?", to: ["d", "e"] },
        { id: "d", kind: "action", label: "Intradetrusor Botox 200 U (trial) or go to augmentation cystoplasty ± ureteric reimplant", to: ["f"] },
        { id: "e", kind: "action", label: "Safe storage but leaks from open BN / ISD → autologous sling, BN reconstruction, or AUS; never isolated BN closure without a catheterisable stoma", to: ["f"] },
        { id: "f", kind: "decision", label: "Kidneys still threatened / non-compliance with CIC?", to: ["g", "h"] },
        { id: "g", kind: "end", label: "Ileal conduit / incontinent diversion as kidney-salvage, especially if CKD progressing toward transplant" },
        { id: "h", kind: "end", label: "Continent catheterisable pouch (Mitrofanoff) if urethra unusable" },
      ]},
      { t: "ul", v: [
        "Do not put a mid-urethral mesh sling in MMC — poor tissue, wheelchair, CIC, high erosion, and you may convert leak to silent high pressure.",
        "Pregnancy later: counsel; augmentation and CIC are compatible; avoid mesh.",
        "Lifelong follow-up: annual US + creatinine; UDS if method of emptying or symptoms change.",
      ]},
      { t: "tip", k: "gold", v: "McGuire 40 cm H2O is the number. Continence surgery on an unsafe bladder is how MMC patients lose kidneys. CIC + low storage pressure first, dryness second." },
    ],
  },
  {
    id: "uds-boo-pfs",
    topicId: "functional",
    title: "Urodynamic tests for BOO and male vs female pressure-flow",
    highYield: true,
    gold: true,
    tags: ["UDS", "PFS", "BOO", "Abrams-Griffiths", "Blaivas-Groutz"],
    exams: [
      { session: "Dec", year: 2022, marks: "5+5", stem: "Enumerate Urodynamic tests that can be used to assess bladder outflow obstruction. Discuss differences between pressure-flow relations in males versus females." },
    ],
    related: ["underactive-detrusor", "female-bno", "bph-complications", "compliance-dlpp"],
    references: [
      "ICS Good Urodynamic Practices / ICS-SUFU nomograms",
      "Abrams–Griffiths / Schäfer / ICS BOOI",
      "Blaivas–Groutz female BOO nomogram",
      "EAU Male LUTS / Non-neurogenic Female LUTS",
      "Campbell Urodynamics",
    ],
    answer: [
      { t: "h", v: "Tests that assess BOO — from simple to invasive" },
      { t: "tbl", h: ["Test", "What it shows", "Limitation"], r: [
        ["Free uroflow + PVR (twice)", "Qmax, pattern (plateau = stricture / BN; intermittent = strain / underactive)", "Cannot separate obstruction from detrusor underactivity"],
        ["Non-invasive: penile-cuff, condom catheter, NIRS, dp/dt of stop-test, ultrasound-estimated BWT / IPP / PV", "Research / adjunct to predict BOO", "Not a replacement for PFS when the answer changes surgery"],
        ["Pdet/Q pressure-flow study (ICS standard)", "Gold standard: PdetQmax vs Qmax plotted on a nomogram", "Invasive, artefacts, 7F catheter itself obstructs slightly"],
        ["Video PFS", "Localises obstruction (BN vs prostate vs sphincter vs urethra) and shows VUR / diverticulum", "Radiation, cost"],
        ["Micturitional urethral pressure profile (MUPP, Whitaker analogue)", "Pressure drop along urethra localises the lesion", "Rarely done"],
        ["EMG ± fluoroscopy", "Functional obstruction (DSD, non-relaxing sphincter, Fowler)", "Needle EMG specialist"],
        ["Urethral calibration / cystoscopy / RGU-MCU", "Anatomic obstruction", "Anatomy ≠ urodynamic obstruction"],
      ]},
      { t: "h", v: "Male pressure-flow" },
      { t: "ul", v: [
        "Voiding is through a long, high-resistance tube (prostate). Normal male voids with PdetQmax ~40–60 cm H2O and Qmax >15 mL/s.",
        "ICS BOOI (Abrams–Griffiths number) = PdetQmax − 2 Qmax. >40 obstructed, <20 unobstructed, 20–40 equivocal.",
        "Schäfer nomogram: LINPURR bands 0–VI; grade II+ is obstruction. Also grades detrusor contractility (very weak → strong).",
        "BCI (bladder contractility index) = PdetQmax + 5 Qmax. >150 strong, 100–150 normal, <100 weak.",
        "Bladder voiding efficiency BVE = voided / (voided + PVR) × 100.",
        "PIP / projected isovolumetric pressure for contractility without a stop test.",
        "Clinical use: failed medical therapy, Qmax >10 with doubt, neurologic overlay, young men, before redo TURP, to avoid operating on underactive detrusor.",
      ]},
      { t: "h", v: "Female pressure-flow — do not use male nomograms" },
      { t: "ul", v: [
        "Short, low-resistance urethra. A woman can empty with Pdet near 0 using pelvic-floor relaxation and a small abdominal increment. Low Pdet + good Qmax is normal, not ‘underactive’ by male BCI.",
        "Obstruction is uncommon (~2–8% of women with LUTS): iatrogenic (sling, prolapse surgery), prolapse kinking, primary bladder-neck obstruction, Fowler’s syndrome, stricture, DYSD.",
        "Blaivas–Groutz nomogram: plots PdetQmax against Qmax; four zones (no, mild, moderate, severe BOO). Over-diagnoses obstruction — use with caution.",
        "Solomon–Greenwell / IFWU and Nitti videourodynamic criteria: radiographic obstruction at BN or urethra with relatively high Pdet and low flow; Nitti: Qmax ≤15 and PdetQmax ≥20 in the presence of radiographic obstruction is a practical threshold (cut-offs vary; quote a range).",
        "BOOI formula is not validated in women.",
        "Prolapse: reduce the prolapse and repeat flow / PFS (occult SUI, unkinked urethra).",
      ]},
      { t: "tbl", c: "Male vs female PFS — the comparison table", h: ["Feature", "Male", "Female"], r: [
        ["Normal PdetQmax", "40–60 cm H2O", "Often 10–30; can be <10"],
        ["Normal Qmax", ">15 mL/s (age-dependent)", ">20 mL/s typical if voided volume adequate"],
        ["Obstruction nomogram", "ICS / Schäfer / AG", "Blaivas–Groutz / video Nitti — no ICS BOOI"],
        ["Common cause of low Qmax", "BPH / stricture", "Underactivity, dysfunctional voiding, prolapse, iatrogenic"],
        ["Abdominal straining", "Inefficient if prostate obstructs", "Often used; may be physiologic"],
        ["Contractility index", "BCI well used", "BCI over-calls weakness"],
      ]},
      { t: "tip", k: "gold", v: "BOO is a pressure-flow diagnosis, not a flow-rate diagnosis. Never apply Abrams–Griffiths to a woman. In men, always report BOOI and BCI together so you do not TURP a weak bladder." },
    ],
  },
  {
    id: "sci-ngb",
    topicId: "functional",
    title: "Neurogenic bladder after SCI (D12 / T11 and upper tracts)",
    highYield: true,
    gold: true,
    tags: ["SCI", "NGB", "DSD", "upper tracts", "CIC"],
    exams: [
      { session: "Dec", year: 2021, marks: "3+4+3", stem: "A 24 year male fell down from a tree, fractured D12 vertebra and developed traumatic paraplegia. Describe the various types of possible urinary bladder involvement. How will you investigate? Outlines of its management." },
      { session: "Dec", year: 2019, marks: "4+6", stem: "Factors affecting upper tract changes after acute spinal cord injury at T11 level. Discuss goal directed management." },
      { session: "Jun", year: 2018, marks: "10", stem: "Neurogenic bladder in spinal cord injury patients." },
    ],
    related: ["dsd", "compliance-dlpp", "spina-bifida-lut", "micturition-nocturia", "snm"],
    references: [
      "EAU Neuro-Urology",
      "ICS/AUA NGB guidelines",
      "Weld & Dmochowski — urodynamic patterns after SCI",
      "Campbell Traumatic spinal cord injury",
      "McGuire DLPP work",
    ],
    answer: [
      { t: "tip", k: "exam", v: "D12 / T11 is the grey zone between typical suprasacral (T10 and above: NDO + DSD) and conus / epiconus (mixed, may be acontractile). Do not blindly write ‘UMNB’. Spinal shock first, then UDS after it ends (~6–12 wk)." },
      { t: "h", v: "Phases" },
      { t: "ul", v: [
        "Spinal shock (hours to 6–12 weeks): acontractile, areflexic detrusor, closed or incompetent neck, overflow leak, flaccid somatic below the level. Drain the bladder immediately (CIC if possible, else Foley; avoid prolonged indwelling).",
        "Recovery of reflex activity: pattern depends on the exact lesion relative to the sacral micturition centre (S2–4, conus at L1–2 vertebral level). T11–L1 vertebral fractures threaten the conus.",
      ]},
      { t: "h", v: "Possible bladder patterns after D12 / T11 (Weld)" },
      { t: "tbl", h: ["Lesion", "Detrusor", "Sphincter", "Clinical"], r: [
        ["Suprasacral (cord intact below, S2–4 isolated from PMC)", "Neurogenic DO", "DSD (smooth and/or striated)", "High pressure, incomplete emptying, AD if above T6"],
        ["Epiconus / mixed T12–L1", "DO or mixed or underactive", "Dyssynergic or fixed or incompetent", "Unpredictable — UDS mandatory"],
        ["Conus / cauda (sacral)", "Acontractile / underactive", "Fixed striated or denervated (open)", "Retention, overflow SUI, low pressure unless poorly compliant with time"],
        ["Late untreated", "Pan-cystitis, fibrosis, low compliance", "Any", "The dangerous ‘low-capacity high-pressure’ bladder"],
      ]},
      { t: "h", v: "Why T11 threatens the upper tracts" },
      { t: "ul", v: [
        "DSD → functional BOO against NDO → high Pdet, high DLPP, trabeculation, diverticula, VUR, hydronephrosis, stones, infection, CKD.",
        "Poor compliance from chronic over-distension, infection, and neural decentralisation of sympathetic pathways around T10–L2 (hypogastric outflow sits here — bladder-neck competence is unpredictable).",
        "Indwelling catheters, stones, high residual, recurrent febrile UTI.",
        "Autonomic dysreflexia if the lesion is at or above T6 (less typical for isolated T11 but possible with a long syrinx / incomplete map).",
        "Delay to CIC, high filling volumes, and failure to monitor UDS are the modifiable factors.",
      ]},
      { t: "h", v: "Investigation" },
      { t: "ul", v: [
        "Acute: ABC, spinal stability, renal function, US (hydronephrosis, clot), start drainage.",
        "Baseline US + creatinine. Video UDS after spinal shock: DO, DSD (EMG or fluoro BN), compliance, DLPP, VUR, capacity, leak.",
        "Cystoscopy if haematuria, stones, or before augmentation.",
        "DMSA / MAG3 if HDUN. Annual surveillance thereafter (EAU: US ± labs; UDS when management changes or upper tracts new).",
        "Latex, fertility, bowel, sexual function, pressure sores — one-line mention scores marks.",
      ]},
      { t: "h", v: "Goal-directed management (EAU)" },
      { t: "kpi", items: [
        { k: "Storage pressure", v: "Pdet <40 cm H2O; DLPP <40" },
        { k: "Emptying", v: "CIC residual < few hundred mL; avoid high-pressure Credé" },
        { k: "Continence", v: "Social dryness without sacrificing safety" },
        { k: "UTI / stones", v: "Low residual, no indwelling if avoidable" },
        { k: "QOL / AD", v: "No dysreflexia storms; independence" },
      ]},
      { t: "ul", n: true, v: [
        "CIC is the gold-standard emptying method (4–6/day). Teach early.",
        "Antimuscarinics (high dose, sometimes combination) ± mirabegron to suppress NDO.",
        "Intradetrusor Botox 200 U (onabotulinumtoxinA) when drugs fail — NDO licence; needs CIC.",
        "α-blockers may lower BN resistance; do not treat DSD reliably.",
        "Sphincterotomy / BN stent / BN incision: for the tetraplegic who cannot CIC and has reflex voiding into a condom — last resort, hypotonic leak.",
        "Augmentation cystoplasty ± sling / AUS / BN closure + Mitrofanoff when conservative measures fail to achieve a safe, socially dry bladder.",
        "Suprapubic catheter if CIC impossible — better than a chronic urethral Foley (strictures, splits, prostatitis).",
        "Never reflex voiding against DSD as a planned long-term strategy.",
      ]},
      { t: "tip", k: "gold", v: "Spinal shock = drain. After shock, UDS not the vertebral level decides treatment. Upper tracts die from storage pressure and DSD, not from the fracture itself." },
    ],
  },
  {
    id: "dsd",
    topicId: "functional",
    title: "Detrusor–sphincter dyssynergia",
    highYield: true,
    gold: true,
    tags: ["DSD", "SCI", "EMG", "sphincterotomy"],
    exams: [
      { session: "Dec", year: 2020, marks: "4+3+3", stem: "What are the types of detrusor-sphincter dyssynergia? Discuss neurological presentation in a man with supra-sacral spinal cord injury. What is the management?" },
      { session: "Dec", year: 2016, marks: "3+3+4", stem: "Aetiology, classification and management of Detrusor sphincter dyssynergia." },
    ],
    related: ["sci-ngb", "compliance-dlpp", "snm"],
    references: [
      "Blaivas JG. J Urol — DSD types",
      "EAU Neuro-Urology",
      "ICS terminology",
      "Campbell Neurourology",
    ],
    answer: [
      { t: "p", v: "DSD is a detrusor contraction concurrent with an involuntary contraction of the urethral and/or periurethral striated muscle (ICS). It is a hallmark of suprasacral infracollicular (infrapontine) lesions — the PMC can no longer coordinate sphincter silence with detrusor firing. It is not a feature of isolated suprapontine lesions (Parkinson, stroke, MS cerebrum) which cause DO with synergistic sphincters." },
      { t: "h", v: "Aetiology" },
      { t: "ul", v: ["Traumatic SCI (cervical and thoracic)", "Non-traumatic myelopathy: MS, transverse myelitis, tumour, NMO, infection, vascular", "Spina bifida (variable)", "Never a ‘psychogenic’ diagnosis — if EMG shows true DSD, image the cord"] },
      { t: "h", v: "Classification (Blaivas)" },
      { t: "tbl", h: ["Type", "EMG / fluoro pattern", "Clinical note"], r: [
        ["Type 1", "EMG crescendos during detrusor rise then silences at peak Pdet — voiding occurs at the peak", "Better emptying, still high pressure"],
        ["Type 2", "Clonic bursts of sphincter activity throughout the detrusor contraction", "Intermittent flow, very high Pdet"],
        ["Type 3", "Sustained sphincter contraction for the whole detrusor contraction", "Worst emptying and pressure"],
      ]},
      { t: "p", v: "Also distinguish striated DSD (rhabdosphincter, EMG) from smooth-sphincter dyssynergia (bladder neck, video; sympathetic decentralisation / T10–L2). A man with suprasacral SCI often has both." },
      { t: "h", v: "Neurological presentation of suprasacral SCI (male)" },
      { t: "ul", v: [
        "Spinal shock then reflex bladder: NDO + DSD, incomplete emptying, incontinence between CIC, UTI, stones.",
        "Spastic paraplegia / tetraplegia, hyperreflexia, upgoing plantars, sensory level.",
        "Autonomic dysreflexia if T6 or above: headache, hypertension, sweating triggered by bladder distension / DSD / instrumentation — treat by emptying the bladder, nifedipine / GTN, never ignore.",
        "Sexual: reflex erection possible if sacral cord intact; emission / ejaculation often impaired.",
        "Bowel: reflex emptying. Fertility: poor ejaculation, electroejaculation / PVS later.",
      ]},
      { t: "h", v: "Diagnosis" },
      { t: "ul", v: ["Video UDS + surface or needle EMG of periurethral / anal sphincter", "Fluoro: spinning-top urethra, closed membranous urethra during detrusor rise, golf-hole BN if chronic", "Do not diagnose DSD on flow pattern alone (interrupted flow is also Valsalva / underactivity)"] },
      { t: "h", v: "Management" },
      { t: "ul", v: [
        "Primary: CIC + detrusor suppression (antimuscarinic, mirabegron, Botox 200 U) so the patient never voids against the sphincter.",
        "α-blockers for BN (smooth) component.",
        "Baclofen (oral / intrathecal) may reduce striated spasticity; incomplete for DSD.",
        "External sphincterotomy (12 o’clock cold knife / laser) or membranous urethral stent: for men committed to condom drainage who cannot / will not CIC. Complications: haemorrhage, stricture, incomplete, hypotonic leak, need for revision.",
        "BN incision if video shows BN dyssynergia.",
        "Augmentation ± AUS if high pressure persists or for continence after sphincterotomy leak.",
        "Never Credé / tapping as definitive therapy in DSD — it is a recipe for reflux.",
      ]},
      { t: "tip", k: "gold", v: "DSD = infrapontine suprasacral. Type it on EMG, treat it by not voiding through it (CIC + Botox). Sphincterotomy is a condom-drainage operation, not a continence operation." },
    ],
  },
  {
    id: "micturition-nocturia",
    topicId: "functional",
    title: "Physiology of micturition and nocturia",
    highYield: true,
    gold: true,
    tags: ["micturition", "PMC", "nocturia", "ICS", "NP"],
    exams: [
      { session: "Dec", year: 2021, marks: "5+2+3", stem: "Describe the physiology of micturition. Nocturia and its management." },
    ],
    related: ["micturition-neuro", "oab", "polydipsia-polyuria", "compliance-dlpp"],
    references: [
      "de Groat WC. Nat Rev Neurosci",
      "ICS terminology of nocturia / ICI-RS",
      "EAU Non-neurogenic Male LUTS — nocturia",
      "Campbell Physiology of the lower urinary tract",
    ],
    answer: [
      { t: "h", v: "Physiology of micturition — storage then voiding" },
      { t: "p", v: "The bladder spends 99% of life in storage. Switch to voiding is a spinobulbospinal reflex gated by the periaqueductal grey and authorised by the prefrontal cortex, executed by Barrington’s pontine micturition centre." },
      { t: "tbl", h: ["Phase", "Peripheral", "Spinal / brain", "Effect"], r: [
        ["Storage", "β3 detrusor relax (hypogastric T10–L2); α1 BN contract; pudendal nicotinic rhabdosphincter (Onuf)", "Pontine storage (L) region; guarding reflex; PAG not switching", "Low Pves, high outlet, filling sensation via Aδ"],
        ["Voiding", "Pelvic parasympathetic M3 detrusor; BN opens (sympathetic off); sphincter silent period", "PMC (M region) → GABA/glycine to Onuf + glutamate to sacral parasympathetic", "Coordinated empty at low pressure"],
      ]},
      { t: "ul", v: [
        "Afferents: Aδ (fullness, myelinated) and C fibres (silent, become active in inflammation / NGB — the C-fibre bladder of SCI).",
        "Urothelium is a sensory organ (ATP, NO, ACh, NGF) talking to suburothelial afferents — the modern OAB story.",
        "Latency: sphincter EMG silences 1–2 s before Pdet rises. Loss of this latency is DSD.",
        "Normal numbers: first sensation ~150–200 mL, FDV ~300–400, strong desire / capacity ~400–600 mL, Pdet storage <15 cm H2O, compliance >30–40 mL/cm H2O, Qmax male >15, female >20.",
      ]},
      { t: "h", v: "Nocturia — ICS" },
      { t: "p", v: "Waking to pass urine during the main sleep period, each void preceded and followed by sleep. ≥1 episode is the definition; bother and comorbidity rise at ≥2. It is a symptom, not a diagnosis." },
      { t: "h", v: "Four pathophysiologic bins (use the bladder diary)" },
      { t: "tbl", h: ["Bin", "Diary signature", "Causes", "First treatment"], r: [
        ["Global polyuria", "24-h urine >40 mL/kg", "Diabetes mellitus / insipidus, primary polydipsia, drugs", "Treat cause; water deprivation / copeptin / OGTT"],
        ["Nocturnal polyuria (NP)", "NPi >20% young or >33% >65 y of 24-h urine (ICS); or NUV >90 mL/h", "OSA, HF, CKD, venous stasis, evening fluids, high ANP, loss of nocturnal ADH peak", "Legs up, afternoon diuretic, CPAP, desmopressin (Na monitor)"],
        ["Reduced nocturnal bladder capacity", "Nocturnal voids of small volume, low NBC index", "OAB, BPH, NGB, cancer, stones, learned frequency", "OAB / BOO pathway"],
        ["Sleep disorder / mixed", "Wakes for other reasons then voids", "OSA, insomnia, pain, depression", "Sleep clinic; still treat NP if present"],
      ]},
      { t: "h", v: "Management ladder" },
      { t: "ul", n: true, v: [
        "Diary is mandatory. No diary, no desmopressin.",
        "Lifestyle: fluid timing, caffeine/alcohol, afternoon exercise, compression stockings, treat oedema, elevate legs 2 h before bed.",
        "Treat OSA (CPAP reduces NP), HF, hyperglycaemia.",
        "BPH / OAB drugs if reduced capacity (α-blocker, antimuscarinic, mirabegron) — modest effect on nocturia specifically.",
        "Timed diuretic (furosemide 6 h before bed) for NP from third-spacing.",
        "Desmopressin: low-dose melt 25 µg women / 50 µg men (NOCTURNAL / CS40); check Na at baseline, day 3–7, 1 month; stop if Na <130. Contraindicated in HF, moderate CKD, hyponatraemia, polydipsia.",
        "Rare: SNM, prostate surgery — nocturia is the LUTS least likely to recover after TURP if NP was the driver.",
      ]},
      { t: "tip", k: "gold", v: "Quote the diary bins. TURP does not fix nocturnal polyuria. Desmopressin without a sodium plan is a dangerous answer in the elderly." },
    ],
  },
  {
    id: "oab",
    topicId: "functional",
    title: "Overactive bladder — pathophysiology, diagnosis, non-surgical treatment",
    highYield: true,
    gold: true,
    tags: ["OAB", "DO", "antimuscarinic", "mirabegron", "PTNS"],
    exams: [
      { session: "Dec", year: 2021, marks: "3+3+4", stem: "Overactive bladder: Pathophysiology. Diagnosis. Non-surgical management." },
      { session: "Jun", year: 2019, marks: "3+4+3", stem: "Overactive bladder (OAB): Diagnosis, outline of management and outcome of treatment." },
      { session: "Dec", year: 2012, marks: "1+3+6", stem: "Define overactive bladder. Etiology of overactive bladder. Outline management of overactive bladder." },
      { session: "Dec", year: 2015, marks: "4+2+4", stem: "Mode of action, dosages and effectiveness of anti-muscarinic agents in overactive bladder." },
    ],
    related: ["antimuscarinics", "mirabegron", "snm", "botox-urology", "dm-parkinson-neuro"],
    references: [
      "ICS terminology",
      "EAU Non-neurogenic Male / Female LUTS",
      "AUA/SUFU OAB guideline",
      "SCORPIO / BESIDE / SYNERGY / ROSETTA",
      "Campbell OAB",
    ],
    answer: [
      { t: "p", v: "ICS: overactive bladder is urinary urgency, usually with frequency and nocturia, with or without urgency incontinence, in the absence of UTI or other obvious pathology. It is a symptom syndrome. Detrusor overactivity is a urodynamic observation (involuntary detrusor contraction during filling) — present in ~50–70% of OAB, not required for the diagnosis." },
      { t: "h", v: "Pathophysiology — three overlapping theories" },
      { t: "ul", v: [
        "Myogenic: denervation supersensitivity, increased gap junctions, micromotions; partial BOO is the classic animal model (men with BPH).",
        "Urothelial / afferent: increased ATP, ACh, NGF, TRPV1, P2X3 signalling from a leaky, inflamed or aged urothelium; C-fibre sprouting.",
        "Neurogenic / central: reduced cortical / PAG suppression of PMC (stroke, MS, Parkinson, white-matter disease); spinal loss of inhibition.",
        "Urethrogenic: urine in a incompetent BN stimulates urethrovesical reflex.",
        "Metabolic: metabolic syndrome, ischaemia, gut–bladder axis — mention one line.",
        "Phenotypes: OAB-wet vs dry; with BOO; with underactivity (DHIC in elderly); neurogenic vs idiopathic.",
      ]},
      { t: "h", v: "Diagnosis" },
      { t: "ul", v: [
        "History + ICIQ-OAB + 3-day diary (frequency ≥8, urgency episodes, leaks, volumes).",
        "Exam: PVR, prostate / prolapse, neurology, atrophic vaginitis, oedema.",
        "Dipstick / culture; cytology / cystoscopy if haematuria, pain, risk of tumour (AUA unremarkable OAB does not all need cystoscopy, but Indian 10-mark answers usually include it if red flags).",
        "Uroflow + PVR in men and in women with voiding symptoms.",
        "UDS not first-line for straightforward idiopathic OAB; indicated if neurogenic, failed 2nd-line drugs, mixed picture, high PVR, before Botox/SNM in some pathways.",
      ]},
      { t: "h", v: "Non-surgical management (AUA/EAU ladder)" },
      { t: "ul", n: true, v: [
        "1st line: education, bladder training, timed voiding, pelvic-floor muscle training (urge-suppression), fluid/caffeine/weight, treat constipation, stop diuretics at night if possible.",
        "2nd line: antimuscarinics or β3-agonist. Fail / intolerant → switch class or combine (BESIDE: solifenacin + mirabegron).",
        "3rd line (minimally invasive, still ‘non-surgical’ in many papers): intradetrusor Botox 100 U idiopathic (200 U NDO), PTNS (30 min × 12 weeks), SNM (see dedicated answer).",
        "Treat BOO in men first or in parallel (α-blocker) — do not start an antimuscarinic with PVR 300 mL.",
      ]},
      { t: "tbl", c: "Antimuscarinics — action, dose, effect size", h: ["Drug", "Dose", "Selectivity", "Notes"], r: [
        ["Oxybutynin IR/ER/patch", "2.5–5 mg TDS; ER 5–15 mg; patch 3.9 mg/d", "Non-selective + relaxant", "Cheapest; worst dry mouth / CNS"],
        ["Tolterodine ER", "4 mg OD", "Non-selective, bladder PK", "Classic trial comparator"],
        ["Solifenacin", "5–10 mg OD", "M3-preferring", "FLEX/STAR; combine with mirabegron"],
        ["Darifenacin", "7.5–15 mg OD", "Most M3-selective", "Less M1 cognition theoretically"],
        ["Fesoterodine", "4–8 mg OD", "Prodrug → 5-HMT", "Flexible dose"],
        ["Trospium", "20 mg BD / XR 60", "Quaternary, no BBB", "Elderly"],
      ]},
      { t: "p", v: "Mechanism: block M3 (and afferent M2/M3) → less urgency. Efficacy: ~1–1.5 fewer voids and ~0.5–1 fewer leaks vs placebo; dry-mouth NNH ~5–7 for oxybutynin IR. Placebo is large in OAB trials — say so. Mirabegron 50 mg: similar efficacy, less dry mouth; watch BP. Outcomes: 30–50% persist on drugs at 1 year because of side effects / unmet expectation; Botox 60–70% responder at 100 U, repeat 6–12 monthly; SNM ~50–80% in highly selected." },
      { t: "tip", k: "gold", v: "OAB is a syndrome; DO is a UDS finding. Ladder: behaviour → drug (or combination) → Botox / PTNS / SNM. Check PVR before every antimuscarinic in men." },
    ],
  },
  {
    id: "dm-parkinson-neuro",
    topicId: "functional",
    title: "Neurourology of diabetes and Parkinson disease",
    highYield: true,
    gold: false,
    tags: ["diabetes", "Parkinson", "DHIC", "MSA"],
    exams: [
      { session: "Jun", year: 2020, marks: "5+5", stem: "Neuro-urological manifestations of: Diabetes mellitus. Parkinson’s disease." },
      { session: "Dec", year: 2019, marks: "5+5", stem: "Evaluation and management of lower urinary tract symptoms in Parkinson's disease." },
      { session: "Jun", year: 2017, marks: "4+6", stem: "How does diabetes mellitus cause lower urinary tract symptoms (LUTS)? What could be the Urodynamic abnormalities in patients with diabetes mellitus?" },
    ],
    related: ["oab", "underactive-detrusor", "sci-ngb", "uds-boo-pfs"],
    references: [
      "EAU Neuro-Urology",
      "Campbell Diabetic cystopathy / Parkinson",
      "ICS standardisation",
      "NICE Parkinson LUTS",
    ],
    answer: [
      { t: "h", v: "Diabetes mellitus" },
      { t: "p", v: "Diabetic cystopathy is a spectrum, not only the textbook ‘sensory atonic bladder’. It coexists with BPH, OAB, infection, osmotic polyuria and autonomic neuropathy." },
      { t: "ul", v: [
        "Pathogenesis: hyperglycaemia → polyol / oxidative / microvascular injury of autonomic and somatic nerves; urothelial ATP signalling altered; myogenic detrusor myopathy; osmotic diuresis from glycosuria; recurrent UTI from glycosuria and residual; concomitant atherosclerosis of bladder arteries.",
        "Time course: early — often DO / urgency (afferent irritation). Late — impaired sensation, increased capacity, underactive / acontractile detrusor, high residual (classic cystopathy, ~25–40% of long-standing DM in older series).",
        "UDS patterns: (1) DO ± incontinence (2) impaired sensation + large capacity + underactivity (3) DHIC — detrusor hyperactivity with impaired contractility (4) BOO from BPH plus any of the above (5) poor compliance rare unless chronic retention / infection.",
        "Other GU: ED, retrograde ejaculation, emphysematous infections, papillary necrosis, UTI, Fournier, CKD — one-line list.",
        "Management: glycaemic control, timed voiding / double void, CIC if PVR high, antimuscarinic only if PVR low, treat BOO carefully (TURP in acontractile bladder fails), Botox cautious, antibiotics for UTI, never ignore overflow CKD.",
      ]},
      { t: "h", v: "Parkinson disease (PD) vs MSA — examiners love this trap" },
      { t: "tbl", h: ["", "Idiopathic PD", "MSA (Shy–Drager)"], r: [
        ["LUTS timing", "Usually after motor diagnosis", "Often before or with early ED / incontinence"],
        ["UDS", "DO with synergistic sphincter; residual modest", "DO + open BN / sphincter denervation; high residual, true NGB"],
        ["Sphincter EMG", "Normal", "Denervation of Onuf (classic)"],
        ["Surgery", "TURP may help selected BOO after UDS", "TURP often worsens incontinence — avoid"],
        ["Other", "Response to levodopa variable for LUTS", "Orthostatic hypotension, cerebellar / pyramidal signs"],
      ]},
      { t: "ul", v: [
        "PD LUTS in 50–70%: nocturia (commonest), urgency, frequency, urgency incontinence; later hesitancy / incomplete emptying from bradykinesia of the sphincter / pelvic floor, not classic DSD.",
        "Pathophysiology: dopamine loss in basal ganglia removes inhibition of the micturition reflex; frontal / cingulate circuits; constipation and pelvic-floor rigidity; nocturnal polyuria from recumbency / MSA overlap / drugs.",
        "Evaluation: diary (NP vs small nocturnal volumes), PVR every visit, uroflow, UDS if considering prostate surgery or atypical features (early severe incontinence, high PVR, impotence before diagnosis → think MSA). Medications review (anticholinergic burden of trihexyphenidyl).",
        "Management: behavioural, treat constipation, mirabegron preferred over antimuscarinics (cognition, confusion with existing anticholinergics), solifenacin / trospium if needed, desmopressin carefully, PTNS, Botox if PVR allows, SNM limited evidence. Optimise dopaminergic therapy. Avoid TURP unless PFS proves BOO and MSA is excluded.",
      ]},
      { t: "tip", k: "gold", v: "DM: early wet, late silent residual. PD: DO with a working sphincter. Early incontinence + ED + open BN = MSA until proven otherwise — do not TURP." },
    ],
  },
  {
    id: "polydipsia-polyuria",
    topicId: "functional",
    title: "Compulsive polydipsia–polyuria syndrome",
    highYield: false,
    gold: false,
    tags: ["polyuria", "DI", "polydipsia", "nocturia"],
    exams: [
      { session: "Jun", year: 2020, marks: "4+3+3", stem: "Compulsive polydipsia-polyuria syndrome—when to suspect, how to investigate and how to manage?" },
    ],
    related: ["micturition-nocturia", "gfr", "oab"],
    references: [
      "ICS polyuria / nocturia terminology",
      "Endocrine Society DI guidelines",
      "Campbell Voiding diary interpretation",
    ],
    answer: [
      { t: "p", v: "Polyuria is 24-h urine >40 mL/kg (typically >3 L). Compulsive (primary) polydipsia is excessive intake that drives the polyuria, as opposed to diabetes insipidus (DI) where polyuria drives thirst. The urologist sees these patients labelled as OAB or ‘prostate’." },
      { t: "h", v: "When to suspect" },
      { t: "ul", v: [
        "Diary: frequent large-volume voids day and night, 24-h output >3 L, no urgency (or urgency only because the bladder is always full).",
        "Psychiatric comorbidity (schizophrenia, anorexia), health-fad water drinking, dry mouth from drugs.",
        "No glycosuria, normal kidneys, low–normal plasma Na or frank hyponatraemia (clue vs DI, where Na is high-normal).",
        "Must distinguish from central DI, nephrogenic DI (lithium, hypercalcaemia, CKD, lithium, demeclocycline, post-obstructive), osmotic diuresis (glucose, urea, mannitol).",
      ]},
      { t: "h", v: "Investigation" },
      { t: "ul", n: true, v: [
        "3-day frequency–volume chart with intake. Spot and 24-h osmolality.",
        "Plasma Na, K, Ca, glucose, urea, eGFR. Lithium level if relevant.",
        "Morning paired plasma and urine osmolality. Uosm >600 with high intake ≈ primary polydipsia (kidney can concentrate).",
        "Water-deprivation test (endocrinology): in primary polydipsia, Uosm rises >600 and plasma osmolality stays normal; in DI, plasma osmolality rises >300 and Uosm stays <300 until desmopressin (central) or not (nephrogenic).",
        "Copeptin / ADH assays where available. MRI pituitary if central DI.",
        "Psychiatry review. Exclude OSA and HF if the story is mainly nocturnal.",
      ]},
      { t: "h", v: "Management" },
      { t: "ul", v: [
        "Primary polydipsia: behavioural water restriction, psychiatry, chew ice, treat dry mouth. Do NOT give desmopressin — hyponatraemic seizures.",
        "Central DI: desmopressin.",
        "Nephrogenic DI: stop lithium if possible, thiazide + amiloride, NSAID (indomethacin), salt restriction, treat hypercalcaemia / hypokalaemia.",
        "Urologic: stop chasing OAB drugs; protect from hyponatraemia if they reach hospital with water intoxication.",
      ]},
      { t: "tip", k: "gold", v: "Large-volume diary + low-normal Na = polydipsia until the deprivation test says otherwise. Desmopressin is contraindicated." },
    ],
  },
  {
    id: "spina-bifida-lut",
    topicId: "functional",
    title: "Spina bifida and the lower urinary tract",
    highYield: true,
    gold: false,
    tags: ["MMC", "spina bifida", "NGB", "CIC"],
    exams: [
      { session: "Dec", year: 2018, marks: "10", stem: "Neuropathic changes in lower urinary tract associated with spina bifida: diagnosis and treatment." },
    ],
    related: ["lpp-mmc", "sci-ngb", "compliance-dlpp", "augmentation-cystoplasty", "dysraphism-recipient"],
    references: [
      "EAU Paediatric / Neuro-Urology",
      "ICCS / CDC spina bifida urologic guidelines",
      "Campbell Myelodysplasia",
      "McGuire DLPP",
    ],
    answer: [
      { t: "p", v: "Open myelomeningocele and occult dysraphism disrupt the sacral cord / roots variably. Unlike traumatic SCI, the lesion is mixed, evolves with growth, tethering and puberty, and always threatens kidneys from birth." },
      { t: "h", v: "LUT patterns (not predicted reliably by vertebral level)" },
      { t: "ul", v: [
        "Hostile: poor compliance, NDO, DSD, DLPP >40, VUR — the kidney-killing combination.",
        "Safe but wet: large acontractile bladder, open BN, overflow / stress leak — kidneys safer, social disaster.",
        "Mixed / changing with tethering: new incontinence, scoliosis, pain, rising creatinine.",
        "Fixed striated sphincter vs denervated perineum (sacral sparing assessment).",
      ]},
      { t: "h", v: "Diagnosis" },
      { t: "ul", v: [
        "At birth: start CIC in most open MMC protocols; US kidneys, residual, spine closure team, latex-free.",
        "UDS in infancy (timing varies by centre: early vs at 2–3 months) — do not wait for hydronephrosis.",
        "Lifelong: US + creatinine regularly; DMSA if scars; video UDS when method fails, before reconstruction, at puberty, if tethering suspected.",
        "MRI spine if new neuro change. Assess hands, cognition, family for CIC / Mitrofanoff planning.",
      ]},
      { t: "h", v: "Treatment principles" },
      { t: "ul", n: true, v: [
        "CIC + anticholinergic from infancy if any hostility. Overnight drainage if night-time filling unsafe.",
        "Botox as a bridge in children / teens.",
        "Augmentation ileocystoplasty ± ureteric reimplant ± BN procedure (sling, Leadbetter, artificial sphincter) ± Mitrofanoff when conservative therapy fails.",
        "Incontinent diversion if kidneys dying and compliance with CIC is impossible.",
        "Bowel programme in every patient. Sexual / fertility / pregnancy counselling in adolescents. Renal transplant is possible after a safe low-pressure reservoir (see dysraphism-recipient).",
        "Tethered-cord release is neurosurgical; urologic gain is modest if the bladder is already fibrotic.",
      ]},
      { t: "tip", k: "gold", v: "Spina bifida urology is kidney first, dryness second, reconstruction third. Level of lesion does not replace UDS." },
    ],
  },
  {
    id: "underactive-detrusor",
    topicId: "functional",
    title: "Underactive detrusor / underactive bladder and PFS",
    highYield: true,
    gold: false,
    tags: ["UAB", "DU", "BCI", "CIC", "PFS"],
    exams: [
      { session: "Dec", year: 2018, marks: "2+3+5", stem: "Underactive Detrusor- Etiology, diagnosis and treatment." },
      { session: "Jun", year: 2014, marks: "2+4+4", stem: "What is pressure flow study (PFS)? Describe the indications and interpretation of various findings of PFS. Outline the management of underactive bladder." },
    ],
    related: ["uds-boo-pfs", "dm-parkinson-neuro", "sci-ngb", "female-bno"],
    references: [
      "ICS underactive bladder / detrusor underactivity consensus",
      "EAU Male LUTS",
      "Chapple / Osman UAB reviews",
      "Campbell Urodynamics",
    ],
    answer: [
      { t: "p", v: "Detrusor underactivity (DU) is a urodynamic diagnosis: a contraction of reduced strength and/or duration, resulting in prolonged bladder emptying and/or failure to achieve complete emptying within a normal time span (ICS). Underactive bladder (UAB) is the symptom complex (hesitancy, interrupted stream, straining, incomplete emptying) that may accompany it. They are not interchangeable — BOO can mimic UAB symptoms." },
      { t: "h", v: "Etiology" },
      { t: "ul", v: [
        "Neurogenic: DM, SCI/conus, MS, Parkinson/MSA, pelvic surgery / EBRT, herpes, Guillain–Barré, disc, B12.",
        "Myogenic: chronic BOO (the decompensated BPH bladder), ageing, ischaemia, fibrosis.",
        "Pharmacologic: antimuscarinics, opioids, antipsychotics, α-agonists.",
        "Idiopathic (including Fowler’s in young women — a different sphincter problem that secondarily impairs voiding).",
        "DHIC in the frail elderly: DO in storage, weak voiding — wet and residual together.",
      ]},
      { t: "h", v: "Pressure-flow study — definition, indications, interpretation" },
      { t: "p", v: "PFS is simultaneous recording of vesical pressure, abdominal pressure (hence Pdet = Pves − Pabd) and flow during voiding. It is the only way to separate BOO from DU." },
      { t: "ul", v: [
        "Indications: LUTS not explained by flow/PVR, before prostate surgery when Qmax is equivocal (>10) or patient is young / neurologic / diabetic / redo, to diagnose female voiding dysfunction, neurogenic bladder, failed TURP.",
        "Male interpretation: plot PdetQmax vs Qmax on ICS/Schäfer. BOOI >40 = BOO. BCI <100 = weak contractility. Equivocal zone needs clinical judgement / video / repeat.",
        "Female: low Pdet is normal; diagnose DU only with incomplete emptying and a weak, poorly sustained Pdet without straining success. Do not use BCI blindly.",
        "Stop-test / PIP to estimate isovolumetric Pdet (Pisv) if needed.",
        "Pitfalls: straining artefact, catheter kick, aborted void, low volume, abdominal contribution.",
      ]},
      { t: "h", v: "Treatment of UAB / DU — honest answer" },
      { t: "ul", v: [
        "No drug reliably restores detrusor power. Bethanechol is obsolete / ineffective in RCTs. α-blockers if concomitant BOO. Stop offending drugs.",
        "Behaviour: timed void, double void, double-tap, pelvic-floor relaxation (biofeedback), avoid heroic straining (reflux, haemorrhoids).",
        "CIC is the standard for high residual / infections / hydronephrosis. Indwelling / SPC if CIC impossible.",
        "Relieve BOO if dual pathology (BOO + DU): selected men still benefit from TURP but counsel modest success (voiding trial may fail).",
        "SNM: option in non-obstructive retention (Fowler, idiopathic) after a successful PNE/tined-lead trial — not for atonic neurogenic bladders of long standing.",
        "Intradetrusor Botox has no role for DU. Reduction cystoplasty / latissimus dorsi detrusor myoplasty — historical / experimental.",
        "Treat the upper tracts and infections; do not chase Qmax.",
      ]},
      { t: "tip", k: "gold", v: "UAB is symptoms; DU is PFS. The treatment with an evidence base is CIC, not bethanechol. Never TURP on a flow rate alone in a diabetic 80-year-old." },
    ],
  },
  {
    id: "female-bno",
    topicId: "functional",
    title: "Functional bladder-neck obstruction in women",
    highYield: false,
    gold: false,
    tags: ["PBNO", "female BOO", "video UDS", "BNI"],
    exams: [
      { session: "Dec", year: 2013, marks: "10", stem: "How will you confirm your diagnosis of functional bladder neck obstruction in a 35 year old female who presents with voiding lower urinary tract symptoms?" },
    ],
    related: ["uds-boo-pfs", "underactive-detrusor", "sui-slings"],
    references: [
      "Nitti / Blaivas female BOO criteria",
      "EAU Female LUTS",
      "Campbell Primary bladder neck obstruction",
    ],
    answer: [
      { t: "p", v: "Primary / functional bladder-neck obstruction (PBNO) is a failure of the bladder neck to open adequately during detrusor contraction, without stricture, prolapse, or neurologic disease. It is uncommon in women and is a diagnosis of video-urodynamic exclusion." },
      { t: "h", v: "Differential of female voiding LUTS at 35" },
      { t: "ul", v: ["Dysfunctional voiding (pelvic-floor non-relaxation, learned)", "Fowler’s syndrome (EMG complex repetitive discharges, retention, PCOS)", "Urethral stricture / stenosis, meatal stenosis", "Prolapse kinking, urethral diverticulum, previous anti-incontinence surgery", "Neurogenic (MS, occult dysraphism)", "DU / drugs", "PBNO (Marion’s disease analogue)"] },
      { t: "h", v: "Confirmation — you cannot confirm it on history" },
      { t: "ul", n: true, v: [
        "Exclude UTI, neurologic signs, drugs, pelvic exam (no prolapse, no scarred urethra), PVR, free flow (plateau / low Qmax).",
        "Cystoscopy: no stricture; the BN may look high / prominent but appearance is not diagnostic.",
        "MRI spine if any red flag.",
        "Video PFS is the gold standard: sustained detrusor contraction with incomplete BN opening on fluoro, narrow BN, proximal urethral filling delayed, relatively high Pdet and low Qmax, quiet EMG (to exclude dysfunctional voiding / DSD). Nitti: radiographic obstruction at BN + Qmax ≤15 mL/s and PdetQmax ≥20 cm H2O is a commonly quoted package.",
        "EMG silent during voiding distinguishes PBNO from dysfunctional voiding (EMG active) and Fowler (classic EMG).",
        "A trial of α-blocker (tamsulosin / alfuzosin) with repeat flow is supportive but not confirmatory.",
      ]},
      { t: "h", v: "Once confirmed" },
      { t: "ul", v: ["α-blocker first-line (counselling on incontinence / retrograde ejaculation N/A; postural hypotension, incontinence risk)", "CIC if residuals dangerous", "Bladder-neck incision (unilateral 12 or 5–7 o’clock, conservative) if drugs fail — risk of SUI is the reason you must be certain of the diagnosis", "Do not do a TURBN as for a man"] },
      { t: "tip", k: "gold", v: "Functional BN obstruction in a woman is a video-UDS diagnosis with a quiet EMG. If the sphincter is firing, it is dysfunctional voiding, not PBNO, and cutting the neck is malpractice." },
    ],
  },
  {
    id: "snm",
    topicId: "functional",
    title: "Sacral neuromodulation",
    highYield: true,
    gold: false,
    tags: ["SNM", "InterStim", "OAB", "retention", "Fowler"],
    exams: [
      { session: "Dec", year: 2015, marks: "10", stem: "Sacral neuro-modulation in the urological practice." },
      { session: "Dec", year: 2011, marks: "10", stem: "Outline the mechanism of sacral neuro-modulation in bladder dysfunction." },
    ],
    related: ["oab", "underactive-detrusor", "neuromod-metallic", "botox-urology"],
    references: [
      "EAU / AUA OAB and neuro-urology guidelines",
      "ROSETTA trial (SNM vs Botox)",
      "Schmidt / Tanagho; InterStim",
      "Campbell Neuromodulation",
    ],
    answer: [
      { t: "p", v: "Sacral neuromodulation (SNM) delivers low-amplitude electrical stimulation to a sacral spinal nerve (almost always S3) via a tined lead and implantable pulse generator (InterStim / Axonics rechargeable). It is a reversible, trialable neuromodulation of the sacral afferent / spinal gating circuitry — not a bladder pacemaker that makes the detrusor squeeze." },
      { t: "h", v: "Mechanism" },
      { t: "ul", v: [
        "S3 mixed nerve carries pelvic and pudendal afferents. Stimulation modulates C-fibre and Aδ input in the dorsal horn, up-regulates inhibitory pathways to the PMC, and ‘resets’ pelvic-floor motoneurons.",
        "In OAB / urgency incontinence: restores cortical / PAG gating, reduces DO and urgency.",
        "In non-obstructive retention (Fowler): may relax a pathologically overactive urethral sphincter and allow the voiding reflex to fire — it does not strengthen a dead detrusor.",
        "Also used for faecal incontinence and selected pelvic pain (less evidence).",
        "It is not DSD therapy and not a substitute for CIC in acontractile neurogenic bladders of SCI.",
      ]},
      { t: "h", v: "Indications (licensed / guideline)" },
      { t: "ul", v: ["Refractory idiopathic OAB (wet or dry) after drugs", "Non-obstructive urinary retention / Fowler", "Faecal incontinence", "Selected interstitial cystitis / BPS (off-label, modest data)", "Some incomplete neurogenic lesions (MS) — case-by-case"] },
      { t: "h", v: "Technique" },
      { t: "ul", n: true, v: [
        "Stage 1: percutaneous nerve evaluation (PNE, temporary wire 3–7 d) or, preferred, tined-lead staged implant under fluoro. S3 landmarks: sciatic notch, 2 cm cephalad to sacral margin, 2 cm off midline. Motor: bellows (levator) + ipsilateral great-toe plantar flexion. Sensory: vaginal / rectal / scrotal paraesthesia.",
        "Successful trial: ≥50% improvement in diary (leaks, voids, or catheterised volumes in retention).",
        "Stage 2: IPG in upper buttock subcutaneous pocket. Programming (amplitude, PW, rate, cycling). MRI-conditional devices now standard.",
        "Complications: lead migration, pain at IPG, infection (~3–5%, explant), battery depletion, loss of efficacy, need for revision (~20–30% at 5 y).",
      ]},
      { t: "h", v: "Outcomes and place vs Botox / PTNS" },
      { t: "ul", v: ["~70–80% of trial-success patients keep a durable benefit", "ROSETTA: Botox 200 U had slightly better 6-month symptom reduction than SNM but more UTI and CIC; SNM avoids CIC risk", "PTNS is a less invasive tibial afferent analogue, weekly office, weaker but safer", "Contraindications: need for ongoing MRI (older devices), active infection, poor compliance with programming, complete SCI"] },
      { t: "tip", k: "gold", v: "SNM is S3 afferent modulation, trialled before implanted. Best for refractory idiopathic OAB and Fowler retention. It will not empty an acontractile SCI bladder." },
    ],
  },
  {
    id: "compliance-dlpp",
    topicId: "functional",
    title: "Bladder compliance and detrusor leak point pressure",
    highYield: true,
    gold: true,
    tags: ["compliance", "DLPP", "McGuire", "NGB"],
    exams: [
      { session: "Dec", year: 2016, marks: "4+6", stem: "Compliance of urinary bladder. Detrusor leak point pressure and its significance." },
    ],
    related: ["lpp-mmc", "sci-ngb", "augmentation-cystoplasty", "uds-boo-pfs"],
    references: [
      "ICS Good Urodynamic Practices",
      "McGuire EJ. J Urol 1981",
      "EAU Neuro-Urology",
      "Campbell Urodynamics",
    ],
    answer: [
      { t: "h", v: "Compliance" },
      { t: "p", v: "Bladder compliance = ΔV / ΔPdet (mL/cm H2O), measured during filling cystometry from empty (or start of fill) to cystometric capacity, excluding detrusor contractions. ICS: report the actual number and the tracing, not only ‘poor’. A practical normal is >30–40 mL/cm H2O in adults; many neurogenic units flag <20 as hostile. End-fill Pdet >15–20 cm H2O at physiologic fill rates is already concerning." },
      { t: "ul", v: [
        "Determinants: viscoelastic properties of collagen / elastin / detrusor, neural sympathetic β3 tone, filling rate, inflammation, fibrosis, chronic infection, radiation, TB, augmentation status, neurologic decentralisation.",
        "Low compliance is a storage failure: pressure rises linearly with volume → hydronephrosis, VUR, incontinence, renal failure.",
        "Artefacts: too-fast fill (use ≤20 mL/min or 10% of expected capacity/min in NGB), patient talking / straining (Pabd), leaked volume not counted, DO misread as compliance.",
        "Two shapes: (1) linear hostile rise from the start (fibrotic wall) (2) delayed drop in compliance at a critical volume (neural). Both matter.",
      ]},
      { t: "h", v: "DLPP and its significance" },
      { t: "p", v: "Detrusor leak point pressure is the lowest Pdet at which leakage occurs in the absence of a detrusor contraction or abdominal strain. McGuire’s myelodysplasia series: children with DLPP ≥40 cm H2O developed VUR and hydronephrosis. That threshold remains the most quoted safety number in neurourology." },
      { t: "ul", v: [
        "Significance: DLPP is a measure of the outlet’s resistance to a poorly compliant or high-pressure bladder. A high DLPP means the kidneys see that pressure until leak ‘pops off’.",
        "A low DLPP (incompetent BN) protects kidneys but makes the patient wet — do not ‘cure’ the leak with a sling without first fixing compliance (augmentation / Botox / CIC).",
        "If the patient does not leak, DLPP is undefined; use end-fill Pdet and compliance instead.",
        "Clinical use: titrate CIC volumes so that the patient never reaches the hostile portion of the curve; decide on augmentation; decide whether a continence procedure is safe.",
        "Contrast with VLPP / ALPP (SUI, ISD) — different test, different disease.",
      ]},
      { t: "tip", k: "gold", v: "Compliance is ΔV/ΔPdet. DLPP ≥40 cm H2O is McGuire’s red line for the upper tracts. Never make a high-DLPP bladder continent without making it compliant." },
    ],
  },
];
