import type { Master } from "../types";

export const infections: Master[] = [
  {
    id: "septic-shock",
    topicId: "infections",
    title: "Septic shock and the antibiogram",
    highYield: true,
    gold: true,
    tags: ["sepsis-3", "SOFA", "SSC", "noradrenaline", "antibiogram"],
    exams: [
      { session: "June", year: 2022, marks: "5+5", stem: "Describe the etiopathogenesis, evaluation and management of Septic shock syndrome. What is antibiogram and how is it interpreted?" },
      { session: "Jun", year: 2021, marks: "5+5", stem: "Define the pathophysiology of septic shock. Enumerate the characteristics for diagnosis and management." },
      { session: "Jun", year: 2014, marks: "4+3+3", stem: "Describe the pathophysiology and diagnosis of septic shock. Outline the management of septic shock." },
    ],
    related: ["furs-single-use-sepsis", "bacterial-resistance-esbl", "epn", "fournier"],
    references: [
      "SSC Hour-1 Bundle 2021; Sepsis-3 (JAMA 2016)",
      "Campbell-Walsh-Wein 12e, Urosepsis",
      "EAU Urological infections guideline",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "Sepsis-3 definitions 2 · Pathophysiology cascade 2 · Urologic sources 1 · Hour-1 bundle + source control 3 · Antibiogram 2. Write noradrenaline not dopamine as first vasopressor." },
      { t: "h", v: "Definitions (Sepsis-3)" },
      { t: "ul", v: [
        "Sepsis: life-threatening organ dysfunction caused by a dysregulated host response to infection. Organ dysfunction = acute rise in SOFA ≥2.",
        "Septic shock: subset with circulatory and cellular/metabolic abnormalities so profound that mortality is ~40%+. Operational: vasopressors to keep MAP ≥65 AND lactate >2 mmol/L after adequate volume.",
        "qSOFA (bedside screen, not diagnosis): RR ≥22, altered mentation, SBP ≤100 — 2 of 3 prompts full SOFA and cultures. Urosepsis is sepsis from a urinary source (obstructed pyelo, after URS/PCNL, infected stent, prostatic abscess, Fournier).",
      ]},
      { t: "h", v: "Pathophysiology" },
      { t: "p", v: "Pathogen-associated molecular patterns (LPS of Gram-negatives — the classic urologic trigger; lipoteichoic acid of Gram-positives) bind TLR4/2 → NF-κB → storm of TNF-α, IL-1, IL-6. Endothelium activates, nitric oxide explodes, capillaries leak, APC/coagulation tilt to DIC, mitochondria fail (cytopathic hypoxia — lactate despite oxygen delivery). Macrocirculation: distributive shock (low SVR, high then low CO). Microcirculation: shunting. Kidneys: ATN + cytokine. The obstructed infected kidney continuously seeds endotoxin until it is drained — antibiotics without PCN/stent fail." },
      { t: "ul", v: [
        "Hyperdynamic warm shock → cold hypodynamic if untreated.",
        "Relative cortisol deficiency, vasopressin depletion — rationale for adding vasopressin and (in refractory shock) hydrocortisone.",
      ]},
      { t: "h", v: "Diagnosis / evaluation" },
      { t: "ul", v: [
        "ABC, lactate, VBG, CBC, Cr, INR, platelets, bilirubin (SOFA inputs), procalcitonin adjunct.",
        "Cultures before antibiotics if <45 min delay: two blood sets, urine, stent/PCN fluid, pus. Do not delay drugs for a difficult culture.",
        "Source hunt: US/NCCT for obstructed kidney, gas (EPN), collection; DRE/scrotal exam; post-URS history.",
        "Exclude mimics: cardiogenic, haemorrhage, PE, adrenal crisis, TURP syndrome.",
      ]},
      { t: "h", v: "Management (SSC Hour-1)" },
      { t: "flow", title: "Uroseptic shock", nodes: [
        { id: "a", kind: "start", label: "Oxygen/airway; two large IVs; monitors; ICU", to: ["b"] },
        { id: "b", kind: "action", label: "Lactate; cultures; broad IV antibiotics within 1 h", to: ["c"] },
        { id: "c", kind: "action", label: "30 mL/kg crystalloid if hypotensive or lactate ≥4 (caution HF/CKD — reassess)", to: ["d"] },
        { id: "d", kind: "decision", label: "MAP still <65?", to: ["e", "f"] },
        { id: "e", kind: "action", label: "Noradrenaline first-line; add vasopressin; consider hydrocortisone 200 mg/d if refractory", to: ["f"] },
        { id: "f", kind: "warn", label: "SOURCE CONTROL same hour: PCN or stent for obstructed pyelo; debride Fournier; pull infected catheter", to: ["g"] },
        { id: "g", kind: "end", label: "De-escalate to culture; 7–14 d typically after control; glucose <180; VTE/stress-ulcer" },
      ]},
      { t: "ul", v: [
        "Empiric urosepsis (community): piperacillin-tazobactam or ceftriaxone ± amikacin per local ESBL rate; add meropenem if prior ESBL/hospital. Cover enterococcus only if risk. MRSA: add vancomycin if devices/hospital.",
        "Steroids: hydrocortisone for refractory shock, not for every sepsis.",
        "Do not give dopamine for renal dose. Do not give bicarbonate for hypoperfusion lactate.",
      ]},
      { t: "h", v: "Antibiogram" },
      { t: "p", v: "An antibiogram is a periodic cumulative report of percent-susceptible isolates from a laboratory/hospital (CLSI/EUCAST rules), stratified by organism and sometimes by ward (ICU vs community). It is not a single patient’s sensitivity report (that is an antibiogram-of-one / cumulative vs individual)." },
      { t: "ul", v: [
        "Interpretation: if E. coli urine isolates are 70% susceptible to ciprofloxacin, empiric cipro for pyelonephritis is unsound (want ≥80–90% for empiric monotherapy of severe disease).",
        "Use: choose empiric regimens, track ESBL/CRE trends, stewardship (restrict carbapenems if not needed), compare with national data.",
        "Pitfalls: duplicate isolates inflate resistance; colonisers vs pathogens; urine vs blood breakpoints differ; do not apply ICU antibiogram to a first cystitis.",
      ]},
      { t: "tip", k: "gold", v: "Drain the kidney. Noradrenaline. Antibiotics in 60 minutes. Antibiogram = unit-level %S, not the patient’s culture printout." },
    ],
  },
  {
    id: "bacterial-virulence",
    topicId: "infections",
    title: "Bacterial virulence, adherence, host defence and UTI vaccines",
    highYield: true,
    gold: false,
    tags: ["type-1 pili", "PapG", "FimH", "biofilm", "OM-89"],
    exams: [
      { session: "Dec", year: 2014, marks: "10", stem: "Explain in brief bacterial virulence and bacterial adherence. Discuss their role in pathogenesis of urinary tract infections." },
      { session: "June", year: 2022, marks: "4+2+2+2", stem: "Describe bacterial virulence and bacterial adherence. Discuss their role in pathogenesis in UTI. Describe the natural defence mechanisms in UTI. What is the current role of vaccines that are being used in UTI?" },
    ],
    related: ["uti-pregnancy-cauti", "bacterial-resistance-esbl", "septic-shock"],
    references: [
      "Campbell-Walsh-Wein 12e, Infections of the urinary tract",
      "EAU Urological infections — prevention / immunoactive prophylaxis",
      "Mobley / Schaeffer virulence reviews",
    ],
    answer: [
      { t: "h", v: "Virulence vs adherence" },
      { t: "p", v: "Virulence factors are microbial products that damage the host or evade killing. Adherence is the subset that lets uropathogens stick to uroplakin-covered epithelium against urine flow — the essential first step of UTI (except in obstruction/foreign body where stasis suffices)." },
      { t: "tbl", h: ["Factor", "Gene / structure", "Role in UTI"], r: [
        ["Type 1 pili (FimH adhesin)", "fim operon, phase ON/OFF", "Bind mannosylated uroplakin Ia on bladder; invasion of umbrella cells; intracellular bacterial communities (IBC) → recurrence"],
        ["P pili (PapG)", "pap", "Bind Galα1-4Gal on P-blood-group glycolipids of kidney — pyelonephritis"],
        ["S / F1C / Dr adhesins", "Various", "Binding variants; pregnancy pyelo association with Dr"],
        ["Flagella", "fliC", "Ascent from urethra to kidney"],
        ["LPS (O antigen), capsule (K)", "Gram-neg envelope", "Serum resistance, shock (LPS–TLR4)"],
        ["Siderophores (enterobactin, yersiniabactin, aerobactin)", "iron acquisition", "Grow in iron-poor urine"],
        ["Toxins: HlyA haemolysin, CNF-1", "hly, cnf1", "Lyse cells, cytoskeletal damage"],
        ["Urease", "Proteus, Klebsiella, Ureaplasma", "NH3, high pH, struvite, ammonia injury"],
        ["Biofilm / PIA", "catheters, stones, stents", "Antibiotic failure, CAUTI"],
        ["AMPC / ESBL / carbapenemase", "plasmids", "Not classic ‘virulence’ but decide outcome"],
      ]},
      { t: "h", v: "Pathogenetic sequence" },
      { t: "ul", n: true, v: [
        "Periurethral colonisation (women: short urethra, sex, spermicide; men: uncircumcised, obstruction).",
        "Adherence (FimH) despite Tamm–Horsfall (uromodulin) which binds type-1 pili as a soluble decoy.",
        "Invasion and IBC in bladder; quiescence in cells → relapse with the same strain.",
        "Ascent via flagella; P pili lock onto renal tubular cells; cytokine storm, neutrophil influx, possible bacteraemia via fornices.",
      ]},
      { t: "h", v: "Natural defence" },
      { t: "ul", v: [
        "Mechanical: antegrade flow, complete emptying, ureteric peristalsis, urethral length (male), Tamm–Horsfall, secretory IgA.",
        "Chemical: acidic urine, urea, high osmolality, lactoferrin, cathelicidin (LL-37), defensins, lipocalin-2.",
        "Cellular: uroplakin barrier, neutrophil influx, cytokine (IL-6/8), adaptive IgA.",
        "Commensals: vaginal lactobacilli (H2O2, lactic acid) — antibiotics and oestrogen deficiency disrupt.",
        "Circumcision reduces periurethral E. coli in boys.",
      ]},
      { t: "h", v: "Vaccines / immunoactive prophylaxis (current role)" },
      { t: "ul", v: [
        "OM-89 (Uro-Vaxom): lyophilised E. coli membrane proteins PO — EAU: consider for recurrent uncomplicated cystitis in women (meta-analyses reduce recurrences). Not a substitute for investigating complicated UTI.",
        "MV140 (sublingual inactivated whole bacteria) — emerging RCTs positive; availability variable.",
        "Parenteral heat-killed (Solco-Urovac) mixed data.",
        "FimH adhesin vaccines, capsule conjugates, exotoxin vaccines — investigational.",
        "Not ‘vaccines’ but related: vaginal oestrogen in post-menopause, cranberry PAC evidence modest, D-mannose as FimH competitive inhibitor (data mixed), methenamine hippurate (ALTAR).",
        "There is no licensed vaccine that replaces antimicrobial treatment of acute pyelonephritis.",
      ]},
      { t: "tip", k: "gold", v: "Type-1 pili = cystitis (FimH–uroplakin). P pili = pyelonephritis (PapG–P blood group). Uromodulin is the host decoy. OM-89 is the vaccine name to write." },
    ],
  },
  {
    id: "bacterial-resistance-esbl",
    topicId: "infections",
    title: "Bacterial resistance and ESBL",
    highYield: true,
    gold: true,
    tags: ["ESBL", "CTX-M", "carbapenemase", "NDM", "stewardship"],
    exams: [
      { session: "Dec", year: 2016, marks: "2+8", stem: "Define bacterial resistance. How is it mediated?" },
      { session: "Dec", year: 2015, marks: "10", stem: "Define bacterial resistance. How is it mediated?" },
      { session: "Dec", year: 2013, marks: "3+3+4", stem: "What is ESBL? Describe the mechanism of bacterial resistance and mechanism to overcome them." },
    ],
    related: ["septic-shock", "bacterial-virulence", "uti-pregnancy-cauti"],
    references: [
      "EAU Urological infections; IDSA ESBL/CRE guidance 2020/2023",
      "Campbell-Walsh-Wein 12e",
      "CLSI / EUCAST; WHO priority pathogens",
    ],
    answer: [
      { t: "h", v: "Definition" },
      { t: "p", v: "Bacterial resistance is the ability of a bacterium to grow at antibiotic concentrations that kill or inhibit the wild-type population — microbiologically a MIC above the breakpoint, clinically a higher chance of therapeutic failure. Intrinsic (species always resistant — enterococci vs cephalosporins) vs acquired (mutation or horizontal gene transfer)." },
      { t: "h", v: "How resistance is mediated" },
      { t: "tbl", h: ["Mechanism", "Example in GU pathogens"], r: [
        ["Enzymatic destruction / modification", "β-lactamases (TEM, SHV, CTX-M ESBL; AmpC; KPC/NDM/OXA-48 carbapenemases); aminoglycoside-modifying enzymes; chloramphenicol acetyltransferase"],
        ["Target alteration", "MRSA mecA (PBP2a); VRE vanA (D-ala-D-lac); QRDR mutations gyrA/parC (fluoroquinolones); ribosomal methylation"],
        ["Reduced permeability", "Porin loss (OmpK36) in Klebsiella + carbapenemase = high-level CRE"],
        ["Efflux pumps", "MexAB-OprM Pseudomonas; tetracycline efflux"],
        ["Bypass / overproduction", "Folic-acid pathway overproduction vs TMP-SMX; hyper-AmpC"],
        ["Biofilm / phenotypic tolerance", "Stent, struvite — not genotypic resistance but failure"],
        ["Horizontal transfer", "Plasmids, transposons, integrons, phage — ESBL and NDM ride plasmids across Enterobacterales"],
      ]},
      { t: "h", v: "ESBL" },
      { t: "p", v: "Extended-spectrum β-lactamases are plasmid-mediated enzymes (class A: CTX-M now dominant, TEM, SHV) that hydrolyse penicillins, 3rd/4th-generation cephalosporins and aztreonam, but are inhibited by clavulanate/tazobactam in vitro. They do NOT hydrolyse carbapenems (that is carbapenemase). Laboratory: cephalosporin MIC high + clavulanate synergy (combined-disc). Co-resistance to quinolones and TMP-SMX is common — urine ‘oral options’ often collapse to fosfomycin / nitrofurantoin (cystitis only) or carbapenem (pyelo/sepsis)." },
      { t: "h", v: "Overcoming resistance" },
      { t: "ul", v: [
        "Stewardship: right drug, dose, duration; no treating ASB (except pregnancy and before urologic mucosal breach); local antibiogram; de-escalation.",
        "Source control: remove stent/catheter, drain abscess, relieve obstruction — more important than a 5th antibiotic.",
        "ESBL cystitis: nitrofurantoin if susceptible, fosfomycin 3 g (E. coli), pivmecillinam (if available), TMP-SMX if S.",
        "ESBL pyelo/bacteraemia: carbapenem (ertapenem if no Pseudomonas; meropenem if sick). Piperacillin-tazobactam is inferior for ESBL bacteraemia (MERINO) — do not use for shock. Once stable, selected BL/BLI or ciprofloxacin if proven S.",
        "AmpC (Enterobacter, Serratia, Citrobacter): cefepime or carbapenem; avoid 3rd-gen ceph (induction).",
        "CRE: ceftazidime-avibactam (KPC/OXA-48, not NDM), meropenem-vaborbactam (KPC), cefiderocol, aztreonam+avibactam (NDM), colistin last-resort. NDM is endemic in South Asia — name it.",
        "PK/PD: high-dose extended-infusion β-lactams, amikacin once-daily, never underdose in sepsis.",
        "Infection control: contact precautions, isolate CRE, stop empirical cipro for ‘every UTI’.",
      ]},
      { t: "tip", k: "gold", v: "ESBL = CTX-M until proven otherwise; treat invasive ESBL with a carbapenem (MERINO). NDM ≠ CZA monotherapy. Biofilm is not an MIC problem — pull the stent." },
    ],
  },
  {
    id: "chyluria",
    topicId: "infections",
    title: "Chyluria — pathophysiology, diet and surgical remedies",
    highYield: true,
    gold: true,
    tags: ["chyluria", "filaria", "Wuchereria", "sclerotherapy", "pyelolymphatic"],
    exams: [
      { session: "June", year: 2022, marks: "5+5", stem: "Describe chyluria and its management. Describe the surgical remedies for the complicated and resistant chyluria." },
      { session: "Jun", year: 2020, marks: "2+3+5", stem: "Etiopathogenesis, clinical features and management of chyluria." },
      { session: "Dec", year: 2018, marks: "3+3+4", stem: "Chyluria — causes, diagnosis and treatment." },
      { session: "Jun", year: 2017, marks: "4+6", stem: "Clinical manifestations and management of chyluria." },
      { session: "Dec", year: 2014, marks: "3+3+4", stem: "Pathology, clinical features and treatment of chyluria." },
      { session: "Dec", year: 2013, marks: "3+4+3", stem: "Describe the pathophysiology of primary chyluria. How does chyle reach urine and what is the basis of dietary treatment?" },
    ],
    related: ["icg-urology", "gutb", "haemostatic-devices"],
    references: [
      "Campbell-Walsh-Wein 12e, Tropical urology / filariasis",
      "WHO lymphatic filariasis; Indian series on povidone sclerotherapy (Goel / Dalela)",
      "Hinman Atlas — chyluria disconnection",
    ],
    answer: [
      { t: "tip", k: "exam", v: "This stem is recycled relentlessly. Write: filarial pyelolymphatic fistula, ether/triglyceride test, cystoscopy side, MCT diet, instillation, then laparoscopic disconnection. Draw cisterna chyli → renal lymphatics." },
      { t: "h", v: "Definition and causes" },
      { t: "p", v: "Chyluria is passage of intestinal chyle into the urinary tract, producing milky urine that may clot. Primary / parasitic (India, far-east): Wuchereria bancrofti disrupting retroperitoneal lymphatics. Non-parasitic: trauma, surgery (especially PN/RPLND/aortic), malignancy, TB, congenital lymphangiectasia, pregnancy, filarial-endemic ‘burnt-out’ disease years after infection." },
      { t: "h", v: "How chyle reaches urine (pathophysiology of primary chyluria)" },
      { t: "ul", n: true, v: [
        "Adult filariae in lymphatic trunks + host inflammation → valvular incompetence and obstruction of lumbar/retroperitoneal lymphatics and cisterna chyli.",
        "Collateral flow regurgitates intestinal chyle (normally thoracic duct → left subclavian) retrograde into renal hilar and capsular lymphatics.",
        "Rupture of dilated fornical/pyelocalyceal lymphatics → pyelolymphatic (or ureterolymphatic) fistulae. Chyle = chylomicrons (triglyceride), lymphocytes, albumin.",
        "High intestinal fat load increases chylomicron volume → clinical flares after fatty meals. This is the basis of diet.",
      ]},
      { t: "h", v: "Clinical features" },
      { t: "ul", v: [
        "Milky urine, worse after meals, often intermittent; haematochyluria; chylous clots → colic, retention.",
        "Weight loss, lymphocytopenia, hypoalbuminaemia, oedema, malnutrition in severe chronic disease; filarial hydrocele / elephantiasis may coexist.",
        "Not painful unless clot colic or UTI.",
      ]},
      { t: "h", v: "Diagnosis" },
      { t: "ul", v: [
        "Bedside: urine standing → cream layer; ether dissolves the fat (milky → clear); Sudan III stains chylomicrons.",
        "Lab: urine triglyceride (diagnostic if elevated, often >15–20 mg/dL) and chylomicrons on lipoprotein electrophoresis. Rule out phosphaturia (clears with acetic acid) and pyuria.",
        "Night-blood smear / ICT filarial antigen: often negative in chronic chyluria (worms long dead).",
        "Cystoscopy after a fatty meal: milky efflux localises the side (essential before unilateral surgery).",
        "Imaging: RGP may show pyelolymphatic backflow; lymphoscintigraphy / MRI lymphangiography / ICG for mapping in refractory cases. CT to exclude mass.",
      ]},
      { t: "h", v: "Dietary treatment — why it works" },
      { t: "p", v: "Long-chain triglycerides (LCT) are absorbed as chylomicrons into intestinal lacteals → thoracic duct. Medium-chain triglycerides (MCT, C8–C12) are absorbed directly into portal blood, bypassing lymphatics. An MCT-rich, LCT-poor, high-protein diet therefore reduces chyle volume and allows fistulae to close in 30–70% of mild cases. Fat-soluble vitamin supplements. Trial 4–6 weeks with bed rest during flares." },
      { t: "h", v: "Step-up management" },
      { t: "ul", v: [
        "DEC (diethylcarbamazine) 6 mg/kg/d × 12–21 d ± doxycycline (Wolbachia) if microfilaria/antigen positive — limited effect on established fistulae but treat active filariasis.",
        "Sclerotherapy: retrograde ureteric catheter, renal pelvis instillation of 0.5–1% silver nitrate (classic, chemical pyelitis risk) or 0.2–1% povidone-iodine (safer, Indian standard), 5–10 mL with position change, 3 weekly sessions. Success 60–80% first course; recurrence 20–40%. Fever, pain, anuria (bilateral oedema) — do one side at a time.",
        "Failed / complicated (clot retention, severe hypoalbuminaemia, unrelenting): surgery.",
      ]},
      { t: "h", v: "Surgical remedies for resistant / complicated chyluria" },
      { t: "tbl", h: ["Operation", "Note"], r: [
        ["Renal pedicle lymphatic disconnection + nephrolysis (chyle ligation)", "Strip all hilar lymphatics, disconnect kidney from surrounding fat; laparoscopic/robotic is current; ICG maps leaks. Gold for unilateral refractory disease."],
        ["Capsule stripping / fasciectomy", "With disconnection"],
        ["Omental wrap / nephropexy", "Adjuncts to cover raw hilum"],
        ["Endoscopic coagulation of fistulae", "If seen on RIRS — adjunct, not durable alone"],
        ["Lymphovenous anastomosis / microsurgery at groin or hilum", "Selected high-volume lymphatic centres"],
        ["Nephrectomy", "Last resort destroyed kidney, life-threatening malnutrition from one side only"],
        ["Shunts / thoracic duct interventions", "Rare, interventional radiology"],
      ]},
      { t: "tip", k: "gold", v: "Chyle = LCT in lymph. MCT diet bypasses lacteals. Localise the side at cystoscopy after a buttered meal before you disconnect a hilum. Povidone instillation before surgery in most Indian patients." },
    ],
  },
  {
    id: "uti-pregnancy-cauti",
    topicId: "infections",
    title: "UTI in pregnancy, ASB and CAUTI",
    highYield: true,
    gold: true,
    tags: ["ASB", "CAUTI", "pregnancy", "nitrofurantoin", "pyelonephritis"],
    exams: [
      { session: "Jun", year: 2015, marks: "5+5", stem: "Natural defence mechanisms against UTI. Physiological changes in urinary tracts during pregnancy." },
      { session: "Dec", year: 2020, marks: "5+5", stem: "Why is UTI more common in pregnancy? What are the differences in the management of UTI in pregnant and non-pregnant females?" },
      { session: "Jun", year: 2020, marks: "5+5", stem: "Is treatment of asymptomatic bacteriuria in pregnancy necessary? Describe the rationale for and against treatment. How do you treat a pregnant woman with symptomatic febrile urinary infection?" },
      { session: "Dec", year: 2011, marks: "3+7", stem: "What is complicated UTI? Outline the management of asymptomatic bacteriuria in pregnancy." },
      { session: "Dec", year: 2021, marks: "3+2+5", stem: "Define CAUTI and catheter associated bacteriuria. Enumerate various methods of preventing CAUTI. Briefly describe the management of bacteriuria and UTI in pregnancy." },
    ],
    related: ["bacterial-virulence", "bacterial-resistance-esbl", "septic-shock"],
    references: [
      "EAU Urological infections; IDSA ASB 2019; CDC CAUTI",
      "Campbell-Walsh-Wein 12e, UTI / pregnancy",
      "USPTF screening ASB in pregnancy",
    ],
    answer: [
      { t: "h", v: "Complicated UTI" },
      { t: "p", v: "UTI in a host with a structural/functional abnormality or a modifying comorbidity that makes failure/complication more likely: obstruction, stones, catheter, NGB, transplant, CKD, poorly controlled diabetes, male sex (EAU still treats most male UTIs as complicated), pregnancy (physiologically complicated), recent instrumentation, MDR organism. Uncomplicated = otherwise healthy non-pregnant woman with cystitis/pyelo." },
      { t: "h", v: "Why UTI is more common in pregnancy + physiologic changes" },
      { t: "ul", v: [
        "Progesterone → ureteric smooth-muscle relaxation and decreased peristalsis.",
        "Mechanical compression of ureters at pelvic brim by the gravid uterus (right > left) → physiologic hydronephrosis in 80%, starts T1, peaks T3.",
        "Bladder: decreased tone, increased capacity, incomplete emptying, vesicoureteric reflux more likely.",
        "Glycosuria (filtered load) and aminoaciduria feed bacteria; mild immunosuppression of pregnancy.",
        "Short female urethra + mechanical factors of sex/hygiene unchanged.",
        "Result: ASB in 2–10% (similar to sexually active non-pregnant) but 20–40% of untreated ASB progresses to pyelonephritis vs ~1–2% if treated. Pyelo → preterm labour, ARDS, sepsis, anaemia.",
      ]},
      { t: "h", v: "ASB in pregnancy — treat or not?" },
      { t: "p", v: "ASB = ≥10⁵ CFU/mL of a uropathogen on two consecutive (or one catheter) specimens without symptoms. IDSA/EAU/USPTF: YES, screen once in early pregnancy (12–16 weeks) and treat. Rationale for: RCTs (classic Kass/Nicolle era) reduced pyelo from ~20–30% to ~3% and reduced preterm/LBW in older trials. Rationale against / caveats: some modern observational data question the preterm-labour benefit; overtreatment drives resistance and C. difficile; a single dipstick is not enough. Current standard remains: treat ASB in pregnancy. Do NOT treat ASB in non-pregnant women, diabetics, elderly, or catheterised patients (IDSA 2019) except before urologic procedures that breach mucosa." },
      { t: "h", v: "Treatment differences: pregnant vs non-pregnant" },
      { t: "tbl", h: ["", "Non-pregnant uncomplicated cystitis", "Pregnancy"], r: [
        ["ASB", "Do not treat", "Treat 4–7 d; confirm clearance"],
        ["Cystitis", "Nitrofurantoin 5 d, fosfomycin 1 dose, pivmecillinam, TMP-SMX 3 d", "Nitrofurantoin 5–7 d (avoid at term — haemolysis if G6PD / neonatal), cephalexin, amox-clav, fosfomycin. Avoid FQ. Avoid TMP-SMX T1 (folate) and near term (kernicterus)."],
        ["Pyelo / febrile", "Outpatient FQ or IV then oral if mild", "ADMIT. IV 3rd-gen ceph or piperacillin-tazobactam until afebrile 24–48 h then oral to complete 7–14 d. No FQ, no aminoglycoside unless life-threatening. Hydronephrosis + fever: consider stent/PCN if not settling 48–72 h (obstructed pyelo). Fetal monitoring."],
        ["Imaging", "US then CT if needed", "US first; MRI without gadolinium if needed; CT only if mother at risk"],
        ["Follow-up", "None routinely", "Monthly cultures; suppress if recurrent (cephalexin/nitrofurantoin nocte)"],
      ]},
      { t: "h", v: "CAUTI vs catheter-associated bacteriuria" },
      { t: "p", v: "CDC: CAUTI = UTI in a patient with an indwelling catheter (or within 48 h of removal) with symptoms/signs and ≥10³ CFU/mL (NHSN uses ≥10⁵ with a matching organism). Catheter-associated asymptomatic bacteriuria (CA-ASB) = bacteriuria without symptoms — nearly universal after 30 days of catheterisation. Do not treat CA-ASB (except pregnancy or before urologic surgery)." },
      { t: "h", v: "Preventing CAUTI" },
      { t: "ul", v: [
        "Avoid the catheter: HOUDINI/nurse-protocol removal, condom catheters, CIC, SPT if long-term.",
        "Aseptic insertion, closed drainage, bag below bladder, no kinks, meatal hygiene (not daily antiseptic ointments).",
        "Do not change bags on a schedule; do not irrigate routinely; do not use prophylactic antibiotics for the life of a catheter (resistance).",
        "Silver/antibiotic-coated catheters: modest delay of bacteriuria, not recommended as a CAUTI panacea (EAU).",
        "Screen-and-treat before prosthesis/endourology; replace the catheter and send a fresh specimen if treating CAUTI.",
      ]},
      { t: "tip", k: "gold", v: "Pregnancy ASB is the great exception — screen and treat. Catheter ASB is the great non-exception — do not treat. Pyelo in pregnancy is an inpatient IV-cephalosporin disease." },
    ],
  },
  {
    id: "fungal-uti",
    topicId: "infections",
    title: "Fungal UTI and candidal cystitis",
    highYield: false,
    gold: false,
    tags: ["Candida", "funguria", "fluconazole", "bezoar"],
    exams: [
      { session: "Dec", year: 2018, marks: "3+3+4", stem: "Fungal UTI — risk factors, diagnosis and treatment of candidial cystitis." },
    ],
    related: ["uti-pregnancy-cauti", "mycotic-mucor", "bacterial-resistance-esbl"],
    references: [
      "IDSA Clinical Practice Guideline for Candidiasis 2016",
      "EAU Urological infections — Candida",
      "Campbell-Walsh-Wein 12e",
    ],
    answer: [
      { t: "h", v: "Risk factors" },
      { t: "ul", v: ["Indwelling catheter / stent / PCN", "Broad-spectrum antibiotics", "Diabetes, immunosuppression, neutropenia, transplant, steroids", "ICU, parenteral nutrition, central lines (candidaemia source may be the line, not the bladder)", "Obstruction, stones, ileal conduit, enterovesical fistula", "Candida albicans commonest; C. glabrata (fluconazole-less-S) in diabetics/elderly; C. auris emerging"] },
      { t: "h", v: "Diagnosis — colonisation vs infection" },
      { t: "p", v: "Candiduria is usually colonisation. Infection (candidal cystitis / pyelo / bezoar / candidaemia) needs a compatible host plus symptoms, pyuria, or imaging (fungus ball in pelvis/bladder). Blood cultures if septic. Species ID and fluconazole MIC. Do not treat asymptomatic candiduria except: (1) neonates/neutropenic at high risk, (2) urologic procedure, (3) maybe renal transplant peri-op — IDSA does not even treat ASB candiduria in most catheterised patients; remove the catheter first (clears 30–40%)." },
      { t: "h", v: "Candidal cystitis — treatment" },
      { t: "ul", v: [
        "Remove / replace catheter. Control glucose. Stop unnecessary antibacterials.",
        "Fluconazole 200 mg (400 mg if upper tract) PO/IV daily × 14 d for C. albicans cystitis — it achieves high urine levels. Not echinocandins (poor urine). Not liposomal AmB as first-line for cystitis.",
        "C. glabrata: higher-dose fluconazole if S-DD, or AmB deoxycholate 0.3–0.6 mg/kg × 1–7 d, or flucytosine. Echinocandin for candidaemia, not for isolated cystitis.",
        "Bladder irrigation with AmB deoxycholate is a temporising option for persistent cystitis / bezoar adjunct — recurrences high if the catheter stays.",
        "Fungus ball: surgical/endoscopic removal + antifungal + drainage (stent/PCN). Obstructing bezoar is a source-control problem.",
        "Candidaemia: echinocandin then step down; always ophthalmology exam; pull lines; image for abscess.",
      ]},
      { t: "tip", k: "exam", v: "Asymptomatic candiduria = pull Foley, do not reflex-fluconazole. Fluconazole is the urine drug; caspofungin is not." },
    ],
  },
  {
    id: "epn",
    topicId: "infections",
    title: "Emphysematous pyelonephritis",
    highYield: true,
    gold: true,
    tags: ["EPN", "Huang-Tseng", "diabetes", "gas", "PCN"],
    exams: [
      { session: "June", year: 2022, marks: "5+5", stem: "Describe the etiopathogenesis, evaluation and classification of Emphysematous Pyelonephritis. Discuss the management of bilateral EPN in a diabetic female with serum creatinine 3.5 mg%." },
      { session: "Jun", year: 2019, marks: "2+3+3+2", stem: "Emphysematous Pyelonephritis — risk factors, diagnosis, outline of management and prognostic markers." },
      { session: "Jun", year: 2018, marks: "5+5", stem: "Enumerate urogenital complications of diabetes mellitus. Detail the management of emphysematous Pyelonephritis." },
      { session: "Jun", year: 2015, marks: "4+6", stem: "Risk factors of emphysematous Pyelonephritis. Prognostic indicators in emphysematous Pyelonephritis." },
    ],
    related: ["xgp", "septic-shock", "gutb"],
    references: [
      "Huang & Tseng classification (J Urol / Arch Surg)",
      "Campbell-Walsh-Wein 12e; EAU Urological infections",
      "Kapoor / Aswathaman Indian series — PCN salvage",
    ],
    answer: [
      { t: "h", v: "Definition and etiopathogenesis" },
      { t: "p", v: "EPN is an acute necrotising infection of the renal parenchyma and peri-nephric tissues producing gas within the kidney. ~90% are diabetics (high tissue glucose = substrate for mixed-acid fermentation by Enterobacterales). E. coli (majority), Klebsiella, rarely Proteus, Clostridium, Candida. Obstruction (stone) coexists in 20–40%. Gas is CO2 + H2 from fermentation, not a clostridial monopoly." },
      { t: "h", v: "UG complications of diabetes (Jun 18 part a)" },
      { t: "ul", v: ["UTI, ASB, pyelonephritis, EPN, papillary necrosis, perinephric abscess", "Emphysematous cystitis / pyelitis", "XGP overlap rare", "Candida UTI, Fournier, balanoposthitis", "Diabetic cystopathy (atonic bladder, residual)", "Infertility / ED / retrograde ejaculation", "Nephropathy / CKD compounding contrast and sepsis", "Increased SSI and emphysematous prostatitis rare"] },
      { t: "h", v: "Risk factors" },
      { t: "ul", v: ["Diabetes (uncontrolled)", "Obstruction / stone / papillary necrosis", "Female sex (3–6:1)", "Immunosuppression, CKD", "E. coli UTI untreated"] },
      { t: "h", v: "Diagnosis" },
      { t: "ul", v: ["Toxic diabetic with loin pain, fever, vomiting, AKI, sometimes crepitus, pneumaturia if also cystitis. DKA may coexist.", "KUB: mottled gas over renal fossa. US: dirty shadowing. CT (non-contrast first if AKI) is gold — locates gas in parenchyma vs collecting system (emphysematous pyelitis is a milder cousin) vs peri-nephric / pararenal."] },
      { t: "tbl", c: "Huang–Tseng CT classification", h: ["Class", "CT finding"], r: [
        ["1", "Gas in collecting system only (emphysematous pyelitis)"],
        ["2", "Parenchymal gas, no extra-renal extension"],
        ["3a", "Extension to peri-nephric space"],
        ["3b", "Extension to pararenal space"],
        ["4", "Bilateral EPN or EPN in a solitary kidney"],
      ]},
      { t: "h", v: "Prognostic markers (poor)" },
      { t: "ul", v: ["Shock, thrombocytopenia, altered sensorium, AKI / Cr >1.4–2.5 (series-dependent)", "Hyponatraemia, hypoalbuminaemia", "Class 3–4, need for emergency nephrectomy after failed drainage", "Need for haemodialysis", "Wan / Huang: type I (dry, streaky gas, no fluid — fulminant) worse than type II (fluid collections + mottled gas)"] },
      { t: "h", v: "Management — including bilateral + Cr 3.5" },
      { t: "flow", title: "EPN", nodes: [
        { id: "a", kind: "start", label: "Resuscitate; cultures; IV carbapenem/pip-tazo + amikacin per antibiogram; insulin; ICU", to: ["b"] },
        { id: "b", kind: "action", label: "Urgent CT; relieve obstruction (PCN ± stent). PCN into collections.", to: ["c"] },
        { id: "c", kind: "decision", label: "Class 1–2, stable after drainage?", to: ["d", "e"] },
        { id: "d", kind: "end", label: "Continue medical + PCN; delayed stone surgery" },
        { id: "e", kind: "decision", label: "Class 3–4 or shock / failed 24–48 h drainage?", to: ["f", "g"] },
        { id: "f", kind: "warn", label: "Emergency nephrectomy if unilateral and dying despite PCN", to: ["g"] },
        { id: "g", kind: "end", label: "Bilateral / solitary / Cr 3.5: NEVER emergency bilateral nephrectomy — maximise bilateral PCN + medical; dialysis bridge; delayed nephrectomy of a destroyed side only" },
      ]},
      { t: "p", v: "The June 22 bilateral diabetic with Cr 3.5 is Huang class 4. Mortality of heroic bilateral nephrectomy is dialysis + sepsis. Answer: ICU, dual drainage, culture-guided drugs, medical optimisation, nephrology for RRT, salvage nephrectomy later only for a non-functioning persistently septic kidney once the contralateral side and the patient have stabilised." },
      { t: "tip", k: "gold", v: "EPN is gas-forming pyelonephritis of the diabetic kidney. PCN first; nephrectomy for the dying unilateral patient. Bilateral = drain both, do not extirpate both." },
    ],
  },
  {
    id: "xgp",
    topicId: "infections",
    title: "Xanthogranulomatous pyelonephritis",
    highYield: true,
    gold: false,
    tags: ["XGP", "bear-paw", "Proteus", "foam cells", "nephrectomy"],
    exams: [
      { session: "Dec", year: 2019, marks: "2+2+3+3", stem: "Etiology, clinical features, diagnosis and treatment of Xanthogranulomatous Pyelonephritis." },
    ],
    related: ["epn", "gutb", "septic-shock"],
    references: [
      "Campbell-Walsh-Wein 12e, Chronic pyelonephritis / XGP",
      "Malek & Elder staging; EAU infections",
    ],
    answer: [
      { t: "p", v: "XGP is a chronic destructive granulomatous pyelonephritis in which the parenchyma is replaced by lipid-laden foamy macrophages (xanthoma cells), plasma cells and fibrosis. It mimics RCC and TB. Typically a middle-aged woman with a poorly functioning kidney, staghorn, and Proteus or E. coli." },
      { t: "h", v: "Etiology" },
      { t: "ul", v: ["Obstruction + infection (staghorn struvite, UPJO, tumour)", "Proteus mirabilis (urease, high pH) > E. coli", "Impaired bacterial clearance → macrophage ingestion of lipid from bacterial and cellular debris", "Diabetes, stones, prior surgery as co-factors"] },
      { t: "h", v: "Clinical features" },
      { t: "ul", v: ["Flank pain, low-grade fever, malaise, weight loss, anaemia of chronic disease — not always acute sepsis", "Recurrent UTI, discharging flank sinus (renocutaneous), psoas abscess, fistulae to colon/duodenum/pleura", "Rare bilateral. Children: often focal XGP."] },
      { t: "h", v: "Diagnosis" },
      { t: "ul", v: [
        "Labs: anaemia, raised ESR/CRP, deranged Cr if contralateral disease, urine culture Proteus/E. coli, sterile pyuria if antibiotics.",
        "CT: enlarged non-functioning kidney, central staghorn, contracted pelvis, dilated calyces with enhancing rims = bear-paw sign; perinephric stranding, psoas involvement. Differential: RCC with thrombus (XGP can invade IVC rarely — still usually nephrectomy), TB (putty, calcification pattern), malakoplakia (Michaelis–Gutmann, usually bladder).",
        "Malek stages: I renal only; II peri-nephric Gerota; III pararenal / retroperitoneal.",
        "DMSA/MAG3: usually <10% function. Biopsy only if a focal mass in a functioning kidney (focal XGP vs tumour).",
      ]},
      { t: "h", v: "Treatment" },
      { t: "ul", v: [
        "Antibiotics to cool the field (cover Proteus). Drain abscesses.",
        "Definitive: nephrectomy (often open because of frozen hilum and fistulae; lap/robot in selected). Difficult: subcapsular plane, adjacent organ injury. Send the whole kidney to exclude coincidental RCC/TB.",
        "Focal XGP in a functioning kidney: partial nephrectomy or even prolonged antibiotics in a child — exception, not the rule.",
        "Counsel: the operation is for a chronic inflammatory mass, not a simple pyelo.",
      ]},
      { t: "tip", k: "gold", v: "Bear-paw + staghorn + non-functioning kidney + foamy macrophages. Treat like a chronic phlegmon: antibiotics then nephrectomy." },
    ],
  },
  {
    id: "mycotic-mucor",
    topicId: "infections",
    title: "Mycotic GU infections and COVID-associated mucormycosis",
    highYield: true,
    gold: false,
    tags: ["mucor", "Candida", "Aspergillus", "COVID", "amphotericin"],
    exams: [
      { session: "Jun", year: 2021, marks: "4+3+3", stem: "What are the Mycotic infections of importance in Urology? Define medications available. Why patients are more prone to Mucormycosis in COVID?" },
    ],
    related: ["fungal-uti", "epn", "fournier"],
    references: [
      "IDSA Mucor / Candida / Aspergillus guidelines",
      "Campbell-Walsh-Wein 12e",
      "Indian COVID-Mucor reports 2021 (steroid + diabetes + oxygen)",
    ],
    answer: [
      { t: "h", v: "Mycotic infections of urologic importance" },
      { t: "tbl", h: ["Organism", "GU syndrome"], r: [
        ["Candida spp.", "Candiduria, cystitis, bezoar, candidaemia, urethritis, prosthesis infection"],
        ["Aspergillus", "Renal aspergillosis, fungal ball, infarcts in neutropenic; rare prostatic"],
        ["Mucorales (Rhizopus, Mucor, Lichtheimia)", "Rhino-orbito-cerebral (not primarily GU) but renal infarcts, transplant kidney, isolated renal mucor, Fournier-like necrotising perineum"],
        ["Cryptococcus", "Prostate reservoir in HIV, cryptococcuria, meningitis from prostatic focus"],
        ["Histoplasma / Blastomyces / Coccidioides", "Epididymo-orchitis, prostatic, adrenal destruction (histo), endemic mycoses"],
        ["Dermatophytes / Candida", "Balanitis, tinea cruris — office urology"],
      ]},
      { t: "h", v: "Medications" },
      { t: "tbl", h: ["Class", "Agents / GU pearls"], r: [
        ["Triazoles", "Fluconazole (Candida albicans, high urine). Voriconazole (Aspergillus, not mucor, not urine). Itraconazole (histo). Isavuconazole / posaconazole (mucor step-down)."],
        ["Polyenes", "Amphotericin B deoxycholate (nephrotoxic) and liposomal AmB (standard for mucor 5–10 mg/kg). Bladder irrigation: deoxycholate only."],
        ["Echinocandins", "Caspofungin, micafungin, anidulafungin — candidaemia; not urine, not mucor, not crypto."],
        ["Flucytosine", "Combo for crypto / selected Candida; marrow/GI toxicity; resistance rapid as mono."],
        ["Adjuncts", "Surgical debridement (mucor — non-negotiable), reverse neutropenia, stop steroids, control diabetes, G-CSF, rarely interferon"],
      ]},
      { t: "h", v: "Why COVID predisposed to mucormycosis" },
      { t: "ul", v: [
        "Uncontrolled diabetes and stress hyperglycaemia — Mucorales have a ketone-reductase and thrive in high glucose; free iron from acidosis (ferritin, DKA) is the growth fuel (Rhizopus loves iron).",
        "High-dose corticosteroids for COVID pneumonia — impair neutrophil/macrophage killing of spores.",
        "Tocilizumab / other immunomodulators in some protocols.",
        "ICU: hypoxia, mechanical ventilation, nosocomial spores (humidifiers, construction), prolonged stay.",
        "Endothelial injury of COVID + thrombosis → infarcts that mucor (angioinvasive) colonises.",
        "Industrial oxygen / unsanitary tubing hypotheses in the Indian 2021 wave — possible contributor, not the sole cause.",
        "Result: rhino-orbito-cerebral epidemic; GU involvement less common but renal infarct, allograft mucor, and perineal necrotising disease occurred. Treatment: liposomal AmB + radical debridement + stop steroids + correct DKA. Mortality remains high." ,
      ]},
      { t: "tip", k: "gold", v: "Mucor = iron + glucose + no neutrophils. Liposomal amphotericin plus cut-to-bleeding debridement. Voriconazole is for Aspergillus, not Mucor." },
    ],
  },
  {
    id: "gutb",
    topicId: "infections",
    title: "Genito-urinary tuberculosis",
    highYield: true,
    gold: true,
    tags: ["GUTB", "GeneXpert", "ATT", "thimble bladder", "golf-hole"],
    exams: [
      { session: "Dec", year: 2011, marks: "5+5", stem: "Describe the pathologic findings in renal tuberculosis. Briefly describe the mechanism of action of five important anti-tubercular drugs." },
      { session: "Jun", year: 2020, marks: "5+5", stem: "What are the major and minor criteria for the diagnosis of genito-urinary tuberculosis? Name the first line drugs used in the treatment of GUTB with doses, duration and common side effects." },
      { session: "Jun", year: 2014, marks: "4+3+3", stem: "Describe the clinical features of genito-urinary tuberculosis. List the possible investigations. Briefly mention the advantages of each investigation." },
      { session: "Jun", year: 2019, marks: "2+8", stem: "Define goals of management for a 15-year-old girl with solitary functioning right kidney, contracted urinary bladder (capacity 25–30 ml) and nadir serum creatinine 1.5 mg/dl who completed ATT for GU tuberculosis one year back. Discuss the various options of management with pros and cons of each." },
      { session: "Dec", year: 2018, marks: "10", stem: "Newer diagnostic tools used in GU tuberculosis." },
    ],
    related: ["chyluria", "xgp", "puv-valve-bladder"],
    references: [
      "Campbell-Walsh-Wein 12e, Genitourinary tuberculosis",
      "WHO / NTEP India TB guidelines; EAU Urological infections — GUTB",
      "Gupta / Nayak Indian GUTB diagnostic criteria",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Pathology cascade from cortex to bladder 3 · Criteria + GeneXpert 2 · HRZE table 3 · Reconstruction of the thimble bladder in a solitary kidney 2." },
      { t: "h", v: "Renal pathology" },
      { t: "p", v: "Haematogenous seeding of M. tuberculosis (usually from a remote pulmonary primary) lodges in glomerular capillaries. Medullary reactivation years later → papillitis, ulcerocavernous cavities, infundibular strictures, autonephrectomy with putty (caseous + calcification) kidney. Caseating granulomas with Langhans giant cells; AFB may be scarce. Down the ureter: beading, corkscrew, stricture (VUJ commonest) → golf-hole orifice, reflux. Bladder: cystitis, then fibrosis → thimble bladder. Prostate, seminal vesicles, epididymis (beaded vas, cold abscess) complete the GU map. Kidney is almost always the source of lower-tract GUTB." },
      { t: "ul", v: ["Healing by fibrosis during ATT can unmask strictures — image during and after treatment, not only at diagnosis.", "Calcification: amorphous putty vs stone."] },
      { t: "h", v: "Clinical features" },
      { t: "ul", v: ["Sterile pyuria, frequency, urgency, haematuria, loin pain, recurrent ‘cystitis’ failing short antibiotics", "Constitutional: fever, night sweats, weight loss — often absent in isolated GUTB", "Epididymal hard nodule, draining scrotal sinus, haemospermia, infertility", "CKD, hypertension, sinus in the loin"] },
      { t: "h", v: "Major / minor diagnostic criteria (use a published Indian set)" },
      { t: "p", v: "There is no single WHO ‘major/minor’ list; examiners expect a composite (Gupta / clinically used): Major: (1) AFB or Mtb culture / GeneXpert from urine or tissue, (2) granulomatous histology with or without AFB, (3) typical radiology (moth-eaten calyx, infundibular stenosis, autonephrectomy, thimble bladder) plus response. Minor: sterile pyuria, haematuria, past TB, positive IGRA/Mantoux, cystoscopic golf-hole, beaded vas, calcified prostate. Diagnosis = 1 major, or 1 radiologic major + 2 minor, etc. Always try to get microbiology before ATT." },
      { t: "h", v: "Investigations — advantages" },
      { t: "tbl", h: ["Test", "Advantage / limit"], r: [
        ["3–5 early-morning urine AFB smear", "Cheap; low sensitivity (~30–40%)"],
        ["LJ / MGIT culture", "Gold for drug susceptibility; slow (2–8 weeks)"],
        ["NAAT / GeneXpert MTB/RIF (Ultra) on urine or biopsy", "Fast, rpoB resistance; urine sensitivity moderate (~50–70%); still the newer tool to name"],
        ["IGRA / Mantoux", "Exposure, not site-specific; false − in immunosuppression"],
        ["IVU / CTU", "Moth-eaten calyx, phantom calyx, pipe-stem ureter, thimble bladder — anatomic map for reconstruction"],
        ["US", "Hydronephrosis, epididymal mass, residual"],
        ["Cystoscopy + biopsy", "Golf-hole, capacity, histology; avoid biopsy of a badly inflamed bladder carelessly"],
        ["DMSA/MAG3", "Split function before nephrectomy"],
        ["CXR / GeneXpert sputum", "Concurrent pulmonary disease"],
        ["MRI", "Epididymis / spinal if needed, no contrast in AKI"],
      ]},
      { t: "h", v: "Newer diagnostic tools (Dec 18)" },
      { t: "ul", v: ["Xpert MTB/RIF Ultra, TrueNat (India)", "Line-probe assays (first- and second-line drugs)", "Urine LAM (more for HIV disseminated TB than classic GUTB)", "Targeted NGS for resistance", "Contrast-enhanced voiding US research", "Multiplex PCR panels on urine"] },
      { t: "h", v: "First-line ATT" },
      { t: "tbl", h: ["Drug", "Adult dose", "Action", "Side effects"], r: [
        ["Isoniazid (H)", "5 mg/kg (max 300) OD", "Bactericidal, cell-wall mycolic acid (InhA/KatG)", "Hepatitis, neuropathy (give pyridoxine), lupus"],
        ["Rifampicin (R)", "10 mg/kg (max 600) OD", "Bactericidal, RNA polymerase rpoB", "Hepatitis, orange fluids, CYP induction (drugs, calcineurin in transplant)"],
        ["Pyrazinamide (Z)", "25 mg/kg OD", "Bactericidal in acid phagosome", "Hepatitis, hyperuricaemia, arthralgia"],
        ["Ethambutol (E)", "15 mg/kg OD", "Bacteriostatic, arabinosyl transferase", "Optic neuritis — colour vision"],
        ["Streptomycin (S) (alternative first-line injectable, older lists)", "15 mg/kg IM", "30S, bactericidal", "Ototoxicity, nephrotoxicity"],
      ]},
      { t: "p", v: "NTEP/WHO: 2 HRZE + 4 HR (6 months) for most GUTB. Extend if slow response, extensive cavity, or bone. Never start a single drug. Reconstruct after 4–6 weeks of ATT when the patient is converting, not on day 0 (except emergency diversion)." },
      { t: "h", v: "The 15-year-old girl — solitary functioning kidney, thimble bladder 25–30 mL, Cr 1.5, ATT completed" },
      { t: "p", v: "Goals: (1) protect the solitary kidney from high storage pressure and reflux, (2) restore a socially continent, catheterisable low-pressure reservoir of adequate capacity, (3) plan for CKD progression / future transplant into that reservoir, (4) fertility/pregnancy counselling, (5) metabolic and compliance reality of a teenager." },
      { t: "tbl", h: ["Option", "Pros", "Cons"], r: [
        ["CIC + anticholinergic / botox into native bladder", "No bowel anastomosis; reversible", "Capacity 25 mL — will not work as sole Rx; kidneys still see high pressure"],
        ["Augmentation cystoplasty (ileum / ileocaecal) ± Mitrofanoff", "Low-pressure volume; uses native continence if sphincter OK; transplant-friendly if compliant CIC", "Mucus, stones, metabolic acidosis (bad with Cr 1.5), B12, perforation, malignancy decades, need reliable CIC; ileum preferred over colon in CKD (less Cl absorption than colon? — actually both have issues; stomach historically for CKD but haematuria-dysuria)"],
        ["Gastric augment (gastrocystoplasty)", "Less hyperchloraemic acidosis — theoretically kinder to CKD", "Haematuria-dysuria, ulcer, malignancy, hypochloraemic alkalosis"],
        ["Ileal chimney / cutaneous diversion (ileal conduit)", "Simple, low pressure if well constructed, protects kidney", "Stoma lifelong at 15; body image; still stones/acidosis; not continent"],
        ["Continent cutaneous pouch (Indiana, Mainz)", "Continent stoma", "More reoperations, stones, need CIC, metabolic load"],
        ["Orthotopic neobladder", "Void per urethra", "Need good sphincter and urethra; CIC still likely; not first in a 25 mL TB bladder with CKD"],
        ["Pre-transplant native diversion then later transplant into pouch/conduit", "If eGFR sliding to ESRD", "Two-stage; Cr 1.5 may remain stable years if pressures fall"],
      ]},
      { t: "p", v: "Practical exam plan: urodynamics (compliance, reflux, residual sphincter), MAG3 of the solitary kidney, counsel CIC for life, ileocystoplasty + Mitrofanoff in a centre that does adolescent reconstruction, nephrology (bicarbonate, CKD-MBD), delay transplant until the reservoir is proven low-pressure. Conduit if she will not CIC. Do not leave a 30 mL bladder attached to a solitary kidney." },
      { t: "tip", k: "gold", v: "GUTB heals by stricture. ATT first, reconstruct later. GeneXpert on urine is the newer test. A thimble bladder on a solitary kidney needs volume, not hope." },
    ],
  },
  {
    id: "fournier",
    topicId: "infections",
    title: "Fournier gangrene",
    highYield: true,
    gold: true,
    tags: ["Fournier", "necrotising fasciitis", "LRINEC", "debridement"],
    exams: [
      { session: "Dec", year: 2020, marks: "2+3+5", stem: "What is Fournier gangrene? What is its clinical presentation? How do you treat Fournier gangrene?" },
      { session: "Dec", year: 2016, marks: "2+4+4", stem: "Definition, aetio-pathogenesis and management of Fournier’s gangrene." },
      { session: "Jun", year: 2014, marks: "4+6", stem: "Describe the aetio-pathogenesis and management of Fournier's gangrene." },
    ],
    related: ["septic-shock", "epn", "mycotic-mucor"],
    references: [
      "Campbell-Walsh-Wein 12e, Infections of the external genitalia",
      "EAU Urological infections / EAU Emergency urology",
      "Fournier Gangrene Severity Index (Laor); LRINEC",
    ],
    answer: [
      { t: "h", v: "Definition" },
      { t: "p", v: "Fournier gangrene is a polymicrobial necrotising fasciitis of the perineum, genitalia and abdominal wall, originating from a urogenital, anorectal or cutaneous source. It is a surgical emergency, not an antibiotic-only cellulitis. Named after Jean-Alfred Fournier (1883). Testes are usually spared (gonadal artery from aorta, not perineal vessels)." },
      { t: "h", v: "Aetio-pathogenesis" },
      { t: "ul", v: [
        "Synergistic aerobes + anaerobes: E. coli, Klebsiella, streptococci, staphylococci, Bacteroides, Clostridium, Peptostreptococcus. Gas from mixed fermentation.",
        "Portal: perianal abscess, ischiorectal, urethral stricture with extravasation, periurethral glands, scrotal skin, colorectal perforation, iatrogenic (injection, surgery), rare intra-abdominal.",
        "Host: diabetes (most important), alcohol, immunosuppression, obesity, CKD, HIV, malignancy, alcohol, neglected hygiene.",
        "Pathology: obliterative endarteritis, subcutaneous necrosis along Colles’, Dartos, Scarpa’s fascia — hence rapid abdominal-wall spread. Deep myonecrosis if clostridial.",
      ]},
      { t: "h", v: "Clinical presentation" },
      { t: "ul", v: [
        "Pain out of proportion, oedema, erythema, then bronze/blue skin, crepitus, dishwater discharge, foul odour, anaesthesia of necrotic skin.",
        "Systemic: fever, tachycardia, shock, MODS — the skin findings can lag behind toxicity.",
        "LRINEC score (CRP, WBC, Hb, Na, Cr, glucose) adjunct, not a rule-out. FGSI (Laor) prognostic. CT/MRI if diagnosis doubtful (gas along fascia) but do not delay theatre for imaging in the obvious case.",
      ]},
      { t: "h", v: "Treatment" },
      { t: "flow", title: "Fournier", nodes: [
        { id: "a", kind: "start", label: "ABC, cultures, lactate, insulin, ICU", to: ["b"] },
        { id: "b", kind: "action", label: "Immediate broad IV: piperacillin-tazobactam or carbapenem + clindamycin (toxin) ± vancomycin", to: ["c"] },
        { id: "c", kind: "warn", label: "Emergency radical debridement to bleeding viable tissue; repeat look 24–48 h (often several trips)", to: ["d"] },
        { id: "d", kind: "action", label: "Divert urine (SPC) ± faeces (colostomy) if sphincter/anus involved", to: ["e"] },
        { id: "e", kind: "action", label: "Orchidopexy of exposed testes into thigh; rarely orchiectomy", to: ["f"] },
        { id: "f", kind: "end", label: "HBO adjunct in stable patients; NPWT; delayed reconstruction (STSG, flaps); nutrition" },
      ]},
      { t: "ul", v: [
        "Antibiotics without surgery = death. Clindamycin for streptococcal/clostridial toxin suppression.",
        "Hyperbaric oxygen: adjunct, never a reason to delay debridement.",
        "Reconstruction after a clean granulating bed: split-skin grafts, pudendal/gracilis flaps. Involve plastics.",
        "Mortality 10–40% — shock, delay, anorectal source, FGSI high.",
      ]},
      { t: "tip", k: "gold", v: "Cut until it bleeds, come back tomorrow, spare the testes, divert the stream. Cellulitis protocols kill these patients." },
    ],
  },
];
