import type { Master } from "../types";

export const infertility: Master[] = [
  {
    id: "oat",
    topicId: "infertility",
    title: "Oligoasthenoteratozoospermia and sperm cryopreservation",
    highYield: true,
    gold: true,
    tags: ["OAT", "WHO semen", "cryopreservation", "ICSI"],
    exams: [
      { session: "June", year: 2022, marks: "7+3", stem: "Discuss the etiopathogenesis, evaluation and management of a person who is diagnosed with Oligo-astheno-zoospermia. Sperm cryopreservation." },
      { session: "Dec", year: 2016, marks: "5+5", stem: "Principles of Enhanced recovery after surgery (ERAS) Protocol. Cryopreservation of sperm: Indications & techniques." },
    ],
    related: ["who-semen", "sperm-retrieval", "ivf-semen-processing", "genetic-male-infertility"],
    references: [
      "Campbell-Walsh-Wein, 12th ed. Male Infertility",
      "WHO Laboratory Manual for the Examination and Processing of Human Semen, 6th ed. 2021",
      "EAU Male Infertility Guidelines",
      "AUA/ASRM Male Infertility Guideline 2020/21",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map (10 marks)", v: "Define OAT with WHO 6th numbers 1 · Causes classified 2 · Evaluation algorithm 2 · Medical vs surgical vs ART 3 · Cryopreservation indications + technique 2. Quote 16 million/mL, 30% PR, 4% morphology." },
      { t: "h", v: "Definition (WHO 6th, 2021 — 5th percentile of fertile men)" },
      { t: "p", v: "Oligoasthenoteratozoospermia (OAT) is the combination of oligozoospermia (concentration <16 × 10^6/mL), asthenozoospermia (progressive motility <30%) and teratozoospermia (strict Kruger normal forms <4%). Isolated OA (oligoasthenozoospermia) is the same without the morphology clause. Confirm on two samples after 2–7 days abstinence; a single abnormal sample is not a diagnosis." },
      { t: "h", v: "Etiopathogenesis — classify, do not dump" },
      { t: "tbl", h: ["Category", "Examples", "How it produces OAT"], r: [
        ["Pre-testicular", "Hypogonadotropic hypogonadism (Kallmann, pituitary, opioids, steroids), hyperprolactinaemia, thyroid, obesity/metabolic syndrome", "Low FSH/LH → impaired spermatogenesis and T"],
        ["Testicular", "Varicocele, cryptorchidism, orchitis (mumps), torsion, gonadotoxins (chemo, XRT, heat, smoking, pesticides), Klinefelter mosaic, AZFc microdeletion, idiopathic", "Hypospermatogenesis, DNA fragmentation, ROS"],
        ["Post-testicular / ductal", "Partial obstruction, epididymitis, Young's syndrome, EDO partial, antisperm antibodies after trauma/vasectomy", "Stasis, oxidative stress, motility kill"],
        ["Ejaculatory / accessory", "Prostatitis, seminal vesiculitis, drugs (SSRI, α-blockers, finasteride, calcium-channel, colchicine, sulfasalazine)", "Volume, motility, morphology hit"],
        ["Lifestyle / iatrogenic", "Fever last 3 months, hot baths, cycling, cannabis, anabolic AAS, obesity, uncontrolled diabetes", "Reversible; always list these"],
      ]},
      { t: "p", v: "Final common pathway is oxidative stress (ROS from leukocytes and immature sperm) → lipid peroxidation of midpiece membranes, motility loss, DNA fragmentation (SDF). Varicocele and idiopathic OAT share this mechanism." },
      { t: "h", v: "Evaluation" },
      { t: "ul", n: true, v: [
        "History: duration, coital frequency/timing, prior paternity, cryptorchidism/orchidopexy, mumps, hernia, TB, STD, chemo/XRT, drugs, smoking, heat, occupation, anosmia, galactorrhoea, androgen abuse.",
        "Female factor in parallel (age is the dominant prognostic) — never delay the partner work-up.",
        "Exam: habitus, gynaecomastia, hair, smell, secondary sexuals. Testicular volume (Prader; ≥12–15 mL adult), consistency, phallus, meatus, vas palpable both sides, epididymis, varicocele (standing, Valsalva), DRE.",
        "Semen ×2: WHO 6th, round cells, MAR/immunobead if agglutination, fructose/pH if volume low. SDF (TUNEL/SCSA/Comet) if unexplained, recurrent miscarriage, or IVF failure — EAU optional.",
        "Labs: morning total T, FSH, LH; add prolactin if T low or sexual symptoms; TSH; HbA1c if indicated. High FSH = testicular failure. Low FSH/LH + low T = hypogonadotropic (treatable).",
        "Genetics if concentration <5 × 10^6/mL: karyotype + Y-microdeletion. CFTR if CBAVD or unexplained OA with low volume.",
        "Scrotal US/Doppler: volume, microlithiasis, occult varicocele only if exam equivocal (treat palpable disease, not US-only subclinical — AUA/EAU).",
        "TRUS if volume <1.4 mL, acidic pH, no fructose → EDO/SV pathology.",
      ]},
      { t: "h", v: "Management — etiology-wise" },
      { t: "tbl", h: ["Cause", "First-line", "If that fails"], r: [
        ["Hypogonadotropic hypogonadism", "hCG ± rFSH (or hMG); pulsatile GnRH if hypothalamic; stop AAS and wait 6–12 months ± SERM/hCG", "TESE/ICSI if no recovery"],
        ["Varicocele + OAT + infertility", "Microsurgical subinguinal ligation (artery + lymph sparing)", "ART if female age high or no semen improvement at 6–9 months"],
        ["Infection / MAGI", "Culture-directed; 2–6 weeks; treat prostatitis properly", "ART"],
        ["EDO", "TURED", "PESA/TESA + ICSI"],
        ["Idiopathic OAT", "Lifestyle (weight, smoking, heat); antioxidants have weak/mixed RCT data (EAU: cannot be routinely recommended as monotherapy)", "IUI if total motile ≥5–10 M; else ICSI. Empiric clomiphene/letrozole/hCG only if T low-normal and FSH not high — counsel off-label"],
        ["AZFc / severe OA", "Do not waste time on empiric drugs", "ICSI ± TESE if cryptozoospermia fluctuates; cryopreserve any sperm found"],
        ["Oncologic / before gonadotoxin", "See cryopreservation below", "Micro-TESE later if azoospermic post-chemo"],
      ]},
      { t: "tip", k: "gold", title: "Gold line", v: "Female age drives the clock. If the partner is ≥35 years, move to ICSI rather than 12 months of empiric therapy. Treat the reversible male factor (varicocele, HH, obstruction, fever, AAS) whenever time allows." },
      { t: "h", v: "Sperm cryopreservation — indications" },
      { t: "ul", v: [
        "Before gonadotoxic chemotherapy, radiotherapy or retroperitoneal surgery (testis, lymphoma, sarcoma, RPLND risk of anejaculation).",
        "Before orchidectomy if the contralateral testis is compromised or the patient is azoospermic/cryptozoospermic on the remaining side (always try a pre-orchidectomy sample; intra-operative TESE if azoospermic).",
        "Before vasectomy (not first-line counselling, but offered), before gender-affirming hormone/surgery, before extensive testicular surgery.",
        "Severe OAT / cryptozoospermia — bank any usable sample because counts fluctuate to zero (virtual azoospermia).",
        "After surgical sperm retrieval (MESA/TESE/micro-TESE) — freeze supernumerary so a second retrieval is avoided.",
        "ART backup on the day of oocyte pick-up if production is unreliable.",
        "Posthumous / occupational high-risk (debate + legal consent).",
      ]},
      { t: "h", v: "Technique" },
      { t: "ul", v: [
        "Sample: 2–7 days abstinence, complete ejaculate into a sterile non-spermicidal container. Infectious screen (HIV, HBV, HCV) before long-term bank — quarantine vials.",
        "Analyse, dilute 1:1 with cryoprotectant (typically TEST-yolk or human-serum-albumin buffer + 5–10% glycerol ± egg yolk). Equilibrate 10–15 min.",
        "Slow programmable freeze: +1 to −5 °C then seed, ramp to −80 °C, plunge into LN2 (−196 °C). Vapour-phase storage accepted in modern banks. Vitrification is used more for surgically retrieved small numbers / oocytes; ejaculated sperm still commonly slow-frozen.",
        "Store in 2–3 physically separate tanks (split straws). Label, dual identification, written consent including duration, posthumous use, and discard rules.",
        "Thaw: 37 °C water bath, wash cryoprotectant, re-analyse. Expect ~25–50% motility loss; ICSI rescues almost all banks. DNA integrity is reduced but clinically acceptable.",
        "No absolute expiry — live births reported after >20 years. Re-consent at intervals per local law.",
      ]},
      { t: "tip", k: "exam", v: "ERAS was the other half of Dec 2016 — do not spend the sperm half of the answer on ERAS. For cryopreservation write: indications, glycerol slow-freeze, LN2, split straws, ICSI after thaw." },
    ],
  },
  {
    id: "sperm-retrieval",
    topicId: "infertility",
    title: "Sperm retrieval techniques and sperm banking",
    highYield: true,
    gold: true,
    tags: ["PESA", "TESA", "TESE", "micro-TESE", "MESA", "IVF"],
    exams: [
      { session: "Dec", year: 2022, marks: "8+2", stem: "Discuss briefly techniques of sperm retrieval for IVF with their indications. Indications for sperm banking and procedures." },
      { session: "Jun", year: 2019, marks: "5+5", stem: "What are the various sperm retrieval techniques and their role in management of male infertility?" },
      { session: "Dec", year: 2012, marks: "3+(3+4)", stem: "Enumerate various assisted reproductive techniques for male infertility. Discuss percutaneous sperm aspiration and testicular sperm extraction." },
    ],
    related: ["oat", "obstructive-azoospermia", "noa-genetics", "ivf-semen-processing"],
    references: [
      "Campbell-Walsh-Wein, Surgical sperm retrieval",
      "Schlegel PN. J Urol — microdissection TESE",
      "EAU Male Infertility / EAU Sexual and Reproductive Health",
      "WHO 6th semen manual — processing and cryopreservation",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "Classify OA vs NOA first. Percutaneous for OA, micro-TESE for NOA. Table of PESA/MESA/TESA/TESE/mTESE with success, morbidity, anaesthesia. Banking = freeze what you retrieve." },
      { t: "h", v: "ART menu the stem wants listed (Dec 12 part a)" },
      { t: "ul", v: [
        "IUI — washed motile ejaculated sperm; needs patent tubes and adequate TMSC.",
        "IVF-ET — insemination in dish; needs ~50–100,000 motile sperm/oocyte historically.",
        "ICSI — single spermatozoon into ooplasm; the workhorse for male-factor, surgical sperm, cryptozoospermia, SDF, globozoospermia (with AOA).",
        "IMSI / PICSI / MACS — adjuncts; evidence modest.",
        "Donor sperm / adoption / remaining child-free — always counsel.",
      ]},
      { t: "h", v: "Principles before any needle" },
      { t: "ul", v: [
        "Confirm azoospermia on centrifuged pellet (two samples).",
        "OA vs NOA decides the procedure: FSH, testicular volume, history of vasectomy/CBAVD/hernia, fructose/pH.",
        "Genetics first in NOA (karyotype, Y-microdeletion) — AZFa or complete AZFb = do not retrieve.",
        "Partner work-up and ICSI slot booked the same cycle, or freeze-all retrieval.",
        "Antibiotic, scrotal support, stop antiplatelet if possible. LA for PESA/TESA; SA or GA for micro-TESE.",
      ]},
      { t: "tbl", c: "Retrieval techniques", h: ["Technique", "How", "Best indication", "Yield / pearls"], r: [
        ["PESA", "21–23 G butterfly into caput epididymis, aspirate, contralateral if dry", "OA: CBAVD, post-vasectomy, failed VV", "Simple, LA, repeatable. Blood contamination. Does not map the testis. Lower numbers than MESA."],
        ["PESAs / percutaneous epididymal", "As above", "OA", "Success 80–100% in true OA"],
        ["MESA", "Scrotal exploration, optical magnification, micropuncture of a dilated epididymal tubule, microsurgical haemostasis", "OA when large numbers needed for freeze, or PESA dry", "Cleanest, highest motile yield, best for banking. Needs microsurgeon. Adhesions next time."],
        ["TESA / TEFNA", "Percutaneous fine-needle (18–21 G) multi-site testicular aspiration", "OA if epididymis empty; diagnostic in suspected NOA (but inferior to TESE)", "Cheap; haematoma; misses focal spermatogenesis in NOA (retrieval ~10–30% vs 40–60% mTESE)."],
        ["cTESE (conventional)", "Scrotal/inguinal, one or more open biopsies, tunica closed", "NOA if no microscope; also simultaneous with orchidectomy for GCT", "Blind; more tissue excised; higher testosterone drop if large/multiple."],
        ["micro-TESE (Schlegel 1999)", "Wide equatorial tunical incision, 15–25× microscope, sample dilated opaque tubules, immediate wet prep", "NOA gold standard (EAU)", "Retrieval 40–60% overall (higher in hypospermatogenesis, lower in SCOS/MA). Less tissue, better T preservation. 2–3 h case. Freeze leftover."],
        ["Onco-TESE", "Micro or conventional at orchidectomy from the tumour-bearing or contralateral testis", "GCT with azoospermia / solitary testis", "Do not delay cancer surgery for a 2-week bank if azoospermic — retrieve on table."],
        ["SSR from urine", "Alkalinise, retrieve from post-orgasm urine", "Retrograde ejaculation", "See retrograde-ejaculation card"],
      ]},
      { t: "flow", title: "Which retrieval?", nodes: [
        { id: "a", kind: "start", label: "Azoospermia confirmed", to: ["b"] },
        { id: "b", kind: "decision", label: "OA (normal FSH, normal volume, dilated epididymis / vasectomy / CBAVD)?", to: ["c", "d"] },
        { id: "c", kind: "action", label: "PESA first; MESA if freeze-all desired or PESA dry; TESA/TESE if epididymis empty", to: ["e"] },
        { id: "d", kind: "decision", label: "NOA — AZFa or complete AZFb?", to: ["f", "g"] },
        { id: "f", kind: "end", label: "No retrieval. Donor / adoption counselling" },
        { id: "g", kind: "action", label: "micro-TESE ± simultaneous contralateral if tiny testes. Cryopreserve all sperm", to: ["e"] },
        { id: "e", kind: "end", label: "ICSI same cycle or freeze-all" },
      ]},
      { t: "h", v: "Sperm banking with retrieval (Dec 22 part b)" },
      { t: "ul", v: [
        "Indications: any surgical sperm (avoid repeat TESE — each attempt drops T and success), cryptozoospermia, pre-gonadotoxin, gender-affirming care, posthumous with prior consent.",
        "Surgically retrieved sperm are few and often immotile — ICSI is mandatory; pentoxifylline / theophylline / laser touch used to identify viable sperm.",
        "Freeze in multiple straws (one straw ≈ one ICSI cycle). Document motility/viability pre-freeze.",
      ]},
      { t: "tip", k: "gold", v: "Write this sentence: “In OA almost any method works; the argument is morbidity and number frozen. In NOA only micro-TESE is first-line because spermatogenesis is focal.”" },
    ],
  },
  {
    id: "who-semen",
    topicId: "infertility",
    title: "WHO semen parameters (6th edition)",
    highYield: true,
    gold: true,
    tags: ["WHO 6th", "semen analysis", "CASA"],
    exams: [
      { session: "Jun", year: 2018, marks: "10", stem: "WHO criteria for normal seminal parameters." },
    ],
    related: ["oat", "low-volume-ejaculate", "primary-infertility-eval"],
    references: [
      "WHO Laboratory Manual for the Examination and Processing of Human Semen, 6th ed. 2021",
      "WHO 5th ed. 2010 (know the deltas — older papers quote 5th)",
      "Campbell-Walsh-Wein, Evaluation of the infertile male",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Trap", v: "Jun 18 was set on WHO 5th (2010). Current answers must present 6th (2021) and mention 5th numbers in a comparison table. These are 5th-percentile reference limits of fertile men, NOT pass/fail ‘normal’." },
      { t: "h", v: "Collection rules (write these first — easy marks)" },
      { t: "ul", v: [
        "2–7 days abstinence (WHO 6th emphasises recording the exact interval).",
        "Masturbation into a wide-mouth sterile non-toxic container; complete ejaculate; no lubricant / saliva.",
        "At the lab if possible; if home, keep at body temperature, deliver <30–60 min.",
        "Two samples a few weeks apart if the first is abnormal. Fever, drugs, incomplete collection invalidate.",
        "Physical: liquefaction ≤30 min (failure → prostate enzyme lack), viscosity, appearance, pH ≥7.2, volume.",
      ]},
      { t: "tbl", c: "Lower reference limits — WHO 5th vs 6th", h: ["Parameter", "WHO 5th (2010)", "WHO 6th (2021)", "Comment"], r: [
        ["Volume (mL)", "1.5", "1.4", "Low volume → incomplete, hypoandrogen, EDO, CBAVD, retrograde"],
        ["Sperm concentration (10⁶/mL)", "15", "16", "Oligozoospermia below this"],
        ["Total sperm number (10⁶/ejaculate)", "39", "39", "Better than concentration alone"],
        ["Progressive motility PR (%)", "32", "30", "PR = WHO a+b"],
        ["Total motility PR+NP (%)", "40", "42", "Asthenozoospermia"],
        ["Vitality (% live)", "58", "54", "Eosin-nigrosin; needed if motility <40% to distinguish necrozoospermia"],
        ["Normal forms (%)", "4", "4", "Kruger strict. Teratozoospermia. Do not quote older 30%/15%"],
        ["pH", "≥7.2", "≥7.2", "Acidic + azoo + low volume = SV/ED/CBAVD"],
        ["Leukocytes (10⁶/mL)", "<1.0 peroxidase+", "<1.0", "Pyospermia; confirm peroxidase — immature germ cells look similar"],
        ["MAR / immunobead", "<50% coated", "unchanged concept", "Antibodies"],
      ]},
      { t: "h", v: "Nomenclature the examiner ticks" },
      { t: "ul", v: [
        "Azoospermia — no sperm after centrifugation of the complete ejaculate.",
        "Cryptozoospermia — rare sperm only after centrifuge.",
        "Oligo / astheno / terato / necro / globo / leucocyto-zoospermia as above.",
        "Normozoospermia — all reference limits met (does not prove fertility).",
        "Aspermia — no antegrade ejaculate (distinct from azoospermia).",
      ]},
      { t: "h", v: "Extended / advanced tests (WHO 6th new emphasis)" },
      { t: "ul", v: [
        "SDF (sperm DNA fragmentation) — SCSA, TUNEL, SCD, Comet. Indications: unexplained infertility, RPL, IVF/ICSI failure, varicocele counselling. No universal cut-off (often DFI >20–30%).",
        "ROS / oxidation-reduction potential.",
        "CASA for motility; strict morphology still manual.",
        "Biochemistry: fructose (SV), zinc/acid phosphatase (prostate), neutral α-glucosidase (epididymis) — useful in low-volume / OA work-up.",
        "Computer and home devices are screening only.",
      ]},
      { t: "tip", k: "gold", v: "A semen analysis is a description of one sample, not a diagnosis of infertility. Always interpret with history, exam and the female partner. Quote: ‘reference limit ≠ fertile/infertile cut-point’." },
    ],
  },
  {
    id: "retrograde-ejaculation",
    topicId: "infertility",
    title: "Retrograde ejaculation and infertility",
    highYield: true,
    gold: false,
    tags: ["ejaculation", "bladder neck", "aspermia"],
    exams: [
      { session: "Dec", year: 2020, marks: "3+7", stem: "What are the causes of retrograde ejaculation? How do you manage a case of infertility due to retrograde ejaculation?" },
    ],
    related: ["anejaculation", "low-volume-ejaculate", "edo"],
    references: [
      "Campbell-Walsh-Wein, Disorders of ejaculation",
      "EAU Sexual and Reproductive Health",
      "ISSM ejaculatory disorders recommendations",
    ],
    answer: [
      { t: "p", v: "Retrograde ejaculation (RE) is the propulsion of semen backwards through an incompetent bladder neck into the bladder, with little or no antegrade ejaculate (low-volume or dry orgasm). Orgasm is preserved — that is how it differs from anejaculation and anorgasmia." },
      { t: "h", v: "Causes" },
      { t: "tbl", h: ["Group", "Examples"], r: [
        ["Anatomic / surgical", "TURP, TUIP, bladder-neck incision, open prostatectomy, Y-V plasty, retroperitoneal / aortic surgery injuring sympathetic chains, RPLND (more often anejaculation), colorectal resection"],
        ["Neurologic", "Diabetic autonomic neuropathy (commonest medical cause), SCI, MS, spina bifida, idiopathic"],
        ["Pharmacologic", "α1-blockers (tamsulosin, silodosin ≫ alfuzosin), antipsychotics, antihypertensives, antidepressants"],
        ["Congenital", "Bladder exstrophy/epispadias, posterior urethral valves residual, congenital BN incompetence"],
        ["Idiopathic / endocrine", "Idiopathic RE; severe testosterone deficiency rarely"],
      ]},
      { t: "h", v: "Diagnosis" },
      { t: "ul", v: [
        "History: cloudy post-orgasm urine, dry orgasm after TURP or in a long-standing diabetic, drugs.",
        "Post-orgasm urine: void or catheterise immediately after orgasm. Centrifuge. Sperm in urine confirms RE. (Azoospermic pellet in urine + dry orgasm → anejaculation / failure of emission.)",
        "Semen: volume <1.0–1.4 mL, often acidic, few sperm; fructose may be low because the sample is urine-diluted.",
        "Do not miss EDO, CBAVD, incomplete collection — the differential of low volume.",
      ]},
      { t: "h", v: "Management of infertility" },
      { t: "ul", n: true, v: [
        "Stop reversible drugs (tamsulosin → switch to alfuzosin or 5-ARI if LUTS allow).",
        "Medical restoration of antegrade ejaculation (needs some sympathetic tone and a BN that can close): sympathomimetics — pseudoephedrine 60 mg QID or 120 mg ER, imipramine 25–50 mg BD, midodrine, ephedrine. Trial 7–14 days before a planned semen sample. Watch BP, especially in diabetics. Success 20–50%, best in diabetic/idiopathic, poor after TURP.",
        "If antegrade semen becomes usable → timed intercourse / IUI.",
        "Sperm retrieval from urine for IUI/ICSI: alkalinise urine (sodium bicarbonate 1–1.5 g the night before and morning of; or potassium citrate) to pH 7.0–7.4; limit fluids to concentrate; masturbate; void immediately into sterile buffer / sperm wash medium; centrifuge, wash, use immediately or freeze. Catheterise if the patient cannot void. Avoid lidocaine jelly (spermicidal) — use sperm-friendly lubricant or none.",
        "If urine retrieval fails or sperm quality poor → PESA/TESA + ICSI (OA-type retrieval; testes are usually normal).",
        "Surgical BN reconstruction is almost never done for fertility.",
      ]},
      { t: "tip", k: "gold", v: "Alkalinised post-orgasm urine + immediate wash is the high-yield practical answer. Imipramine/pseudoephedrine for restoration; TESA/ICSI as the reliable backstop." },
    ],
  },
  {
    id: "azoospermia-workup",
    topicId: "infertility",
    title: "Azoospermia — causes, work-up pathway, management",
    highYield: true,
    gold: true,
    tags: ["azoospermia", "OA", "NOA", "FSH"],
    exams: [
      { session: "Dec", year: 2020, marks: "3+4+3", stem: "Causes of azoospermia. Flow pathway for work-up to decide etiology. Etiology-wise steps of management." },
    ],
    related: ["obstructive-azoospermia", "noa-genetics", "who-semen", "klinefelter"],
    references: [
      "Campbell-Walsh-Wein, Azoospermia",
      "EAU Male Infertility Guidelines",
      "AUA/ASRM Diagnosis and Treatment of Infertility in Men 2020",
    ],
    answer: [
      { t: "p", v: "Azoospermia = no spermatozoa in the centrifuged pellet of two complete ejaculates. Prevalence ~1% of men, 10–15% of infertile men. Split immediately into obstructive (OA, ~40%) vs non-obstructive (NOA, ~60%) — management is opposite." },
      { t: "h", v: "Causes" },
      { t: "tbl", h: ["", "Obstructive (OA)", "Non-obstructive (NOA)"], r: [
        ["Pre-testicular", "—", "HH: Kallmann, pituitary tumour/infiltrative, iron overload, opioids, AAS, dual suppression"],
        ["Testicular", "—", "Klinefelter, Y-microdeletion, SCOS, maturation arrest, cryptorchidism, gonadotoxins, torsion/orchitis, idiopathic, 46XX testicular DSD"],
        ["Post-testicular", "CBAVD/CUAVD, Young's, infection (gonorrhoea, TB, filaria), vasectomy, iatrogenic (hernia, orchidopexy), EDO, ejaculatory failure (SCI, RPLND) — the last is emission failure rather than duct block", "—"],
      ]},
      { t: "h", v: "Work-up flow" },
      { t: "flow", title: "Azoospermia algorithm", nodes: [
        { id: "a", kind: "start", label: "Azoospermia ×2 centrifuged samples", to: ["b"] },
        { id: "b", kind: "action", label: "History, exam (volume, vas, epididymis, varicocele), morning T/FSH/LH, semen volume + pH + fructose", to: ["c"] },
        { id: "c", kind: "decision", label: "Vas absent?", to: ["d", "e"] },
        { id: "d", kind: "action", label: "CBAVD/CUAVD: CFTR couple testing; renal US if unilateral", to: ["p"] },
        { id: "e", kind: "decision", label: "Volume <1.4 mL, pH <7.2, fructose low?", to: ["f", "g"] },
        { id: "f", kind: "action", label: "TRUS ± MRI: EDO / SV agenesis. TURED if dilated ducts / midline cyst", to: ["p"] },
        { id: "g", kind: "decision", label: "FSH high and/or testes small/soft?", to: ["h", "i"] },
        { id: "h", kind: "action", label: "NOA pathway: karyotype + Y-microdeletion. Treat HH if FSH/LH low. micro-TESE if genetics allow", to: ["p"] },
        { id: "i", kind: "action", label: "Likely OA (normal FSH, normal testes, full epididymis): scrotal exploration ± vasography, reconstruct or PESA/MESA", to: ["p"] },
        { id: "p", kind: "end", label: "ICSI with ejaculated / retrieved / donor sperm; fertility counselling" },
      ]},
      { t: "kpi", items: [
        { k: "OA phenotype", v: "FSH normal, testes ≥15 mL, epididymis full, vas ± absent" },
        { k: "NOA phenotype", v: "FSH ↑, testes small/soft, epididymis flat" },
        { k: "EDO phenotype", v: "Low volume, acidic, no fructose, dilated SV on TRUS" },
        { k: "HH phenotype", v: "Low T + low/inappropriately normal FSH/LH, ± anosmia" },
      ]},
      { t: "tip", k: "warn", title: "Do not biopsy to ‘classify’", v: "Diagnostic testicular biopsy as a standalone procedure is obsolete. If you open the testis, retrieve sperm (onco-TESE / micro-TESE) and freeze. Isolated histology without ICSI intent does not help the couple." },
      { t: "h", v: "Etiology-wise management" },
      { t: "ul", v: [
        "HH: hCG 1500–2000 IU 2–3×/week until T normalises, then add rFSH 75–150 IU 3×/week (or hMG). Spermatogenesis may take 6–24 months. Cryopreserve when sperm appear. Very treatable — do not jump to TESE.",
        "Klinefelter: see dedicated card. micro-TESE + ICSI + genetic counselling. T replacement after retrieval (exogenous T suppresses remaining spermatogenesis — stop 6 months before TESE, bridge with hCG/SERM).",
        "AZFc: micro-TESE reasonable. AZFa or complete AZFb: no TESE.",
        "SCOS / MA: micro-TESE only hope of autologous sperm; counsel 20–40% retrieval.",
        "OA reconstructable (vasectomy, iatrogenic, epididymal blow-out): microsurgical VV / VE if female age allows and numbers of children desired; otherwise PESA + ICSI. Both can be combined (reconstruct + freeze epididymal sperm).",
        "CBAVD: PESA/MESA + ICSI after CFTR of both partners; PGD if both carriers.",
        "EDO: TURED; if fails, PESA/TESA.",
        "Idiopathic NOA: micro-TESE. Optimise T if low (hCG/SERM, not exogenous T). Varicocele repair controversial in azoospermia — may return rare sperm in selected men with palpable varicocele and hypospermatogenesis; do not delay ART if female age high.",
        "Always: donor sperm, adoption, remaining child-free as equal options — document counselling.",
      ]},
    ],
  },
  {
    id: "obstructive-azoospermia",
    topicId: "infertility",
    title: "Obstructive azoospermia — evaluation and surgery",
    highYield: true,
    gold: true,
    tags: ["OA", "vasoepididymostomy", "vasovasostomy", "PESA"],
    exams: [
      { session: "Dec", year: 2020, marks: "5+5", stem: "Evaluation and management of obstructive azoospermia. Describe surgical techniques." },
      { session: "Dec", year: 2018, marks: "5+5", stem: "Evaluation and management of obstructive azoospermia." },
    ],
    related: ["azoospermia-workup", "sperm-retrieval", "edo", "epididymis-vv", "cuavd"],
    references: [
      "Campbell-Walsh-Wein, Surgery of male infertility",
      "Silber / Belker / Goldstein vasectomy-reversal series",
      "EAU Male Infertility — OA",
    ],
    answer: [
      { t: "h", v: "Evaluation specific to OA" },
      { t: "ul", v: [
        "Clinical: normal androgenisation, testicular volume typically normal, epididymis indurated/full, vas present or absent, scrotal surgical scars, DRE (midline cyst, SV).",
        "Semen: azoospermia, volume ≥1.4 mL and pH ≥7.2 if obstruction is at epididymis/vas (seminal vesicles contribute volume). Low volume + acidic + no fructose = EDO or SV agenesis / CBAVD.",
        "Hormones: FSH normal (may be high-normal). T normal.",
        "CFTR + partner screen if CBAVD or idiopathic bilateral vas absence. Renal US in unilateral vas absence (mesonephric, not CF).",
        "TRUS / pelvic MRI if EDO suspected: dilated ejaculatory ducts >2.3 mm, dilated SV >15 mm AP, midline utricle cyst.",
        "Vasography: only intra-operative at the time of reconstruction — never a standalone outpatient puncture (risk of iatrogenic stricture).",
        "Testicular biopsy is not required if the OA phenotype is classic; if in doubt, a wet-prep biopsy at reconstruction confirms sperm production.",
      ]},
      { t: "h", v: "Site of obstruction — surgical map" },
      { t: "tbl", h: ["Level", "Typical cause", "Operation"], r: [
        ["Intratesticular / rete", "Young's, idiopathic rete block", "TESA/TESE + ICSI (not reconstructable)"],
        ["Epididymis", "Post-infection, post-vasectomy blow-out, idiopathic", "Vasoepididymostomy (VE)"],
        ["Vas (mid-scrotal)", "Vasectomy, hernia mesh, orchidopexy", "Vasovasostomy (VV)"],
        ["Inguinal vas", "Hernia repair, orchidopexy", "Inguinal VV; crossed VV if one side unusable"],
        ["Ejaculatory duct", "Congenital cyst, calcification, TB", "TURED"],
        ["Vas aplasia", "CBAVD", "PESA/MESA + ICSI; no reconstruction"],
      ]},
      { t: "h", v: "Vasovasostomy — steps the examiner wants" },
      { t: "ul", n: true, v: [
        "High scrotal incision, deliver testis, identify both ends, spatulate, confirm proximal fluid.",
        "Examine vasal fluid: copious clear/opalescent with sperm (or sperm heads) → VV. Thick toothpaste without sperm → epididymal blow-out → convert to VE. Silber law.",
        "Microscope 16–25×, 9-0/10-0 nylon. Modified one-layer (full-thickness 10-0 at 4–6 points + 9-0 muscularis) vs two-layer (mucosa 10-0, muscularis 9-0). Microdot (Goldstein) for precise mucosal alignment. Both valid if mucosa is coapted watertight and tension-free.",
        "Stents are not used. Layered closure, scrotal support, ejaculatory abstinence 2–4 weeks, semen analysis at 6–8 weeks then 3-monthly for a year.",
        "Patency 70–95% depending on obstructive interval (<3 years best, >15 years poorer), presence of sperm in vasal fluid, surgeon volume. Pregnancy 30–75%. Antisperm antibodies possible but ICSI still works.",
      ]},
      { t: "h", v: "Vasoepididymostomy" },
      { t: "ul", v: [
        "End-to-side intussusception: 2-suture (Berger triangulation / Marmar) or 4-suture (Goldstein) 10-0 through a single epididymal tubule into the vas lumen, then 9-0 muscularis.",
        "Choose the lowest (caudal) level of the epididymis that still has sperm on micropuncture — preserves length and uses more mature sperm.",
        "Patency 40–80%; pregnancy lower than VV. Always freeze epididymal/testicular sperm at the same operation (salvage if anastomosis fails).",
      ]},
      { t: "h", v: "TURED (for EDO)" },
      { t: "p", v: "Resect the verumontanum in the midline (12–5 o'clock, 3–4 mm depth) until cloudy efflux from both ducts; unroof midline cysts. Loop or holmium. Risks: reflux of urine into ducts (epididymitis), incontinence (too proximal), rectal injury (too deep), secondary RE. Success: volume and sperm return in 50–70% of cystic EDO, poorer in calcific/inflammatory." },
      { t: "h", v: "When to skip reconstruction and go to PESA/ICSI" },
      { t: "ul", v: ["Female age ≥35 or diminished ovarian reserve", "Need for donor oocytes anyway", "Prior failed reversal", "CBAVD", "Surgeon without microsurgical volume", "Couple preference after cost/time counselling"] },
      { t: "tip", k: "gold", v: "Never do vasography as a diagnostic day-case. Never reconstruct without the microscope and a plan to freeze sperm. Silber: ‘no sperm in vasal fluid → VE, not a tighter VV’." },
    ],
  },
  {
    id: "noa-genetics",
    topicId: "infertility",
    title: "Non-obstructive azoospermia — genetic basis and counselling",
    highYield: true,
    gold: true,
    tags: ["NOA", "AZF", "Klinefelter", "CFTR"],
    exams: [
      { session: "Dec", year: 2016, marks: "3+3+4", stem: "Causes of non-obstructive azoospermia, its genetic basis and counseling the patients for its management." },
    ],
    related: ["genetic-male-infertility", "klinefelter", "sertoli-only", "azoospermia-workup"],
    references: [
      "Campbell-Walsh-Wein, Genetics of male infertility",
      "EAU Male Infertility — genetic testing",
      "AUA/ASRM: karyotype and Y-microdeletion when sperm concentration <5 × 10⁶/mL",
    ],
    answer: [
      { t: "h", v: "Causes of NOA" },
      { t: "ul", v: [
        "Genetic: Klinefelter (47,XXY — commonest chromosomal), other karyotype (47,XYY, 46,XX testicular DSD, translocations, mixed gonadal dysgenesis), Y-chromosome AZF microdeletions, congenital HH (Kallmann — KAL1/ANOS1, FGFR1, PROK2, CHD7), TEX11, NR5A1, congenital anorchia.",
        "Developmental: bilateral cryptorchidism, testicular dysgenesis syndrome.",
        "Acquired testicular: chemo (alkylators worst), XRT, bilateral torsion, mumps orchitis, trauma, idiopathic primary testicular failure, late-onset SCOS.",
        "Endocrine: adult-onset HH, haemochromatosis, pituitary, exogenous androgens/steroids (reversible).",
        "Unclassified idiopathic — still the largest bucket; many are cryptic monogenic.",
      ]},
      { t: "h", v: "Genetic tests that change management" },
      { t: "tbl", h: ["Test", "Who", "Finding → action"], r: [
        ["Karyotype", "All NOA and sperm conc. <5–10 × 10⁶/mL (EAU <5)", "47,XXY → micro-TESE counselling, T care, PGT discussion. Robertsonian/reciprocal translocation → PGT-SR. 46,XX male → no TESE (usually SRY+ SCOS)."],
        ["Y microdeletion (STS PCR: AZFa, b, c)", "Same as karyotype; also before TESE", "AZFa or complete AZFb: retrieval ≈ 0 — do not operate. AZFc: 50–70% retrieval, sperm may be in ejaculate later; sons inherit the deletion. Partial AZFb/c: case-by-case."],
        ["CFTR sequencing + 5T/polyT", "CBAVD, idiopathic OA, partner of known carrier — not classic NOA", "If both partners pathogenic → 25% CF / risk of CBAVD in sons; offer PGT-M."],
        ["Kallmann / CHH panel", "HH + anosmia / delayed puberty", "Treat with gonadotrophins — fertility often restorable; inheritance counselling."],
        ["NGS infertility panels / WES", "Idiopathic NOA, familial", "Emerging; TEX11 X-linked MA. Not yet routine in every Indian lab — mention as advancing."],
      ]},
      { t: "h", v: "AZF anatomy (draw the Yq11 map)" },
      { t: "p", v: "AZFa (USP9Y, DDX3Y) — SCOS, no sperm. AZFb (RBMY, PRY) — maturation arrest at spermatocyte. AZFc (DAZ copies, CDY1) — hypospermatogenesis / oligozoospermia, most amenable to TESE/ICSI. Deletions arise by homologous recombination between palindromes. Do not offer TESE for complete AZFa or AZFb; document this in the consent." },
      { t: "h", v: "Counselling — write as a checklist" },
      { t: "ul", n: true, v: [
        "Explain OA vs NOA and that NOA is a retrieval probability, not a guarantee. Quote centre micro-TESE rates (overall ~40–60%; SCOS ~20–40%; MA ~30–50%; hypospermatogenesis ~80%).",
        "Genetics of the child: AZFc sons will be infertile; Klinefelter ICSI offspring are usually 46,XY but sex-chromosome aneuploidy is increased — offer PGT-A, amniocentesis.",
        "CFTR: both partners before ICSI in CBAVD.",
        "Testosterone: many NOA men are hypogonadal or will become so after TESE. Plan TRT after sperm is banked, not before.",
        "Repeat TESE: success falls; freeze everything the first time.",
        "Alternatives with equal dignity: donor sperm IUI/ICSI, adoption, remaining child-free. Avoid coercing the female partner into repeated COS for a low-probability TESE.",
        "Psychological support — azoospermia is a grief diagnosis.",
        "Cancer: rare TP53/other syndromes; do not miss an occult GCT (US both testes).",
      ]},
      { t: "tip", k: "gold", v: "The genetic result that forbids surgery is complete AZFa or AZFb. Everything else is a probability conversation plus ICSI/PGT." },
    ],
  },
  {
    id: "edo",
    topicId: "infertility",
    title: "Ejaculatory duct obstruction",
    highYield: true,
    gold: false,
    tags: ["EDO", "TURED", "TRUS", "low volume"],
    exams: [
      { session: "Dec", year: 2013, marks: "5+5", stem: "How will you confirm the diagnosis of ejaculatory duct obstruction and how will you manage that?" },
    ],
    related: ["low-volume-ejaculate", "obstructive-azoospermia", "retrograde-ejaculation"],
    references: [
      "Campbell-Walsh-Wein, Ejaculatory duct obstruction",
      "EAU Male Infertility",
      "Turek / Jarow TURED series",
    ],
    answer: [
      { t: "p", v: "EDO is blockage of one or both ejaculatory ducts (intraprostatic wolffian + SV contribution) causing infertility ± painful ejaculation, haematospermia, or perineal pain. May be complete (azoospermia, very low volume) or partial (OAT, low volume)." },
      { t: "h", v: "Causes" },
      { t: "ul", v: [
        "Congenital: midline prostatic utricle / Müllerian cyst, Wolffian cysts, atresia.",
        "Acquired: post-inflammatory (prostatitis, TB, STD), calculus of the duct, iatrogenic (TURP too distal — rare), trauma.",
        "Functional (pseudo-EDO): poor emission, SV atony — TRUS looks dilated but TURED fails.",
      ]},
      { t: "h", v: "How to confirm diagnosis" },
      { t: "ul", n: true, v: [
        "Semen: volume ≤1.0–1.4 mL, pH <7.2, fructose absent/low, azoospermia or severe OAT. (Partial EDO may have borderline volume.)",
        "Post-ejaculate urine negative (excludes RE).",
        "Vasa palpable, testes normal, FSH normal — OA phenotype.",
        "TRUS (7–10 MHz, empty bladder or semi-full): SV AP diameter >15 mm, ejaculatory duct >2.3 mm, midline cyst, calcifications at the veru. Unilateral dilated SV suggests ipsilateral duct block.",
        "MRI pelvis if TRUS equivocal (T2 bright cysts).",
        "SV aspiration under TRUS: sperm in SV + dilated ducts is confirmatory and the sperm can be used for ICSI the same day.",
        "SV vesiculography / chromotubation (methylene blue via vas or TRUS needle) at the time of TURED — dye should efflux at the veru after resection.",
        "Do not rely on vasography alone as a day-case.",
      ]},
      { t: "h", v: "Management" },
      { t: "tbl", h: ["Option", "Detail"], r: [
        ["TURED", "First-line for cystic / short-segment EDO. Lithotomy, 24–27 Fr resectoscope, resect veru in the midline until both ducts geyser. Holmium unroofing of cysts is equivalent. Catheter overnight. Semen analysis 4–6 weeks. Repeat TRUS if no improvement."],
        ["Transurethral incision of cyst (not deep resection)", "Large midline utricle cysts — unroof, do not excavate towards rectum."],
        ["PESA / TESA + ICSI", "If TURED fails, calcific long-segment EDO, or female age high. Also freeze SV-aspirated sperm."],
        ["Open / laparoscopic SV surgery", "Rare: large symptomatic cysts, stones, malignancy."],
      ]},
      { t: "h", v: "Complications of TURED" },
      { t: "ul", v: ["Urinary reflux into SV/epididymis → recurrent epididymitis (counsel, treat as OA thereafter)", "Watery ejaculate", "Secondary RE / BN incompetence if resection too proximal", "Incontinence (external sphincter) if too distal/deep", "Rectal injury — rarer with holmium", "Fibrotic re-occlusion"] },
      { t: "tip", k: "exam", v: "Diagnostic triad: low volume + acidic/fructose-negative semen + dilated SV/ED on TRUS, with negative post-orgasm urine. Treatment: TURED, with PESA/ICSI as the safety net." },
    ],
  },
  {
    id: "pe-pharma",
    topicId: "infertility",
    title: "Pharmacological management of premature ejaculation",
    highYield: true,
    gold: false,
    tags: ["PE", "dapoxetine", "SSRI", "ISSM"],
    exams: [
      { session: "Dec", year: 2016, marks: "4+6", stem: "Current concepts and advances in the pharmacological management of premature ejaculation." },
    ],
    related: ["ejaculatory-disorders", "unconsummated-marriage"],
    references: [
      "ISSM Guidelines for the Diagnosis and Treatment of Premature Ejaculation",
      "EAU Sexual and Reproductive Health — PE",
      "Campbell-Walsh-Wein, Disorders of orgasm and ejaculation",
      "McMahon CG. dapoxetine / SSRI evidence",
    ],
    answer: [
      { t: "p", v: "ISSM: PE is a male sexual dysfunction with (1) ejaculation that always or nearly always occurs before or within ~1 min of penetration (lifelong) or a clinically significant reduction to ≤3 min (acquired), (2) inability to delay ejaculation on all or nearly all penetrations, (3) negative personal consequences (distress, bother, avoidance). Stopwatch IELT is a research tool; history is enough clinically. Prevalence ~20–30% self-report, true ISSM PE ~5%." },
      { t: "h", v: "Pathophysiology relevant to drugs" },
      { t: "ul", v: [
        "Serotonin (5-HT) via 5-HT1B/1D and 5-HT2C delays ejaculation; 5-HT1A facilitates. SSRIs exploit this.",
        "Lifelong PE: neurobiological (5-HT receptor polymorphism, hyperexcitable ejaculatory reflex, penile hypersensitivity); acquired: ED, prostatitis, thyroid, relationship, opioid withdrawal.",
        "Treat comorbid ED first (PDE5) — ISSM/EAU. Anxiety and PE feed each other; drugs plus behavioural therapy beat either alone.",
      ]},
      { t: "tbl", c: "Pharmacotherapy — what to write", h: ["Drug", "Dose / timing", "IELT fold-increase", "Pearls / AE"], r: [
        ["Dapoxetine (only on-demand licensed SSRI in many regions)", "30 mg 1–3 h pre-sex; 60 mg if needed. Not if liver disease, MAOI, strong CYP3A4.", "2.5–3×", "Short t½ ~1.5 h, low accumulation. Nausea, dizziness, syncope (counsel hydration, skip PDE5 caution). Not marketed in some countries — still the exam ‘advance’."],
        ["Paroxetine", "10–40 mg daily; or 10–20 mg 3–4 h on-demand after 3 weeks daily loading", "8× daily (best SSRI)", "Best efficacy. AE: drowsiness, xerostomia, anorgasmia, fertility/sperm hit with chronic SSRI, suicidal ideation young adults, taper to stop."],
        ["Sertraline", "50–200 mg daily", "5×", "Common Indian alternative"],
        ["Fluoxetine", "20–40 mg daily", "5×", "Long t½"],
        ["Clomipramine (TCA)", "12.5–50 mg daily or 25 mg on-demand 4–6 h pre-sex", "4–6×", "Anticholinergic AE; on-demand option if SSRI not tolerated"],
        ["Topical eutectic lidocaine–prilocaine (EMLA / PSD502 / TEMPE spray)", "Spray 5–10 min before, wipe; cream 10–20 min with condom to protect partner", "4–6×", "Numbness, transfer to partner, contact dermatitis. First-line alternative to SSRI (EAU)."],
        ["Tramadol", "25–50 mg 1–2 h on-demand", "4×", "μ-opioid + 5-HT/NA reuptake. Off-label. Seizure, dependence, serotonin syndrome with SSRI. Not first-line."],
        ["PDE5 inhibitors", "Tadalafil 5 mg daily or on-demand sildenafil", "Modest IELT; better control scores", "Mandatory if ED + PE. Reduce performance anxiety, second-erection window."],
        ["α1-blockers (silodosin 4–8 mg)", "Off-label", "Some IELT gain", "RE / anejaculation as the mechanism — not ideal if fertility desired"],
        ["Intraprostatic botulinum / dorsal neurectomy / glans hyaluronic acid", "Experimental / not guideline", "—", "Do not recommend in a DrNB answer except as ‘investigational’"],
      ]},
      { t: "h", v: "Algorithm" },
      { t: "ul", n: true, v: [
        "Lifelong PE, no ED: dapoxetine on-demand or daily SSRI (paroxetine) or topical anaesthetic. Combine with start–stop / squeeze (Masters & Johnson) and CBT.",
        "Acquired PE: treat the cause (ED, prostatitis, hyperthyroid, relationship).",
        "PE + ED: PDE5 ± dapoxetine (watch syncope) or topical.",
        "Fertility desired: prefer topical or behavioural; chronic SSRI impairs motility/SDF. Silodosin causes RE.",
        "Review 4–6 weeks; if one class fails, switch or combine topical + SSRI.",
      ]},
      { t: "tip", k: "gold", v: "Licensed on-demand = dapoxetine. Most effective daily = paroxetine. Always treat ED first. Behavioural therapy is not optional window-dressing." },
    ],
  },
  {
    id: "low-volume-ejaculate",
    topicId: "infertility",
    title: "Low-volume ejaculate (1 mL) in a 25-year-old",
    highYield: true,
    gold: false,
    tags: ["hypospermia", "EDO", "retrograde", "CBAVD"],
    exams: [
      { session: "Jun", year: 2017, marks: "10", stem: "How do you evaluate a 25 year male with primary infertility having semen (ejaculate) volume 1 ml?" },
    ],
    related: ["who-semen", "edo", "retrograde-ejaculation", "cuavd", "primary-infertility-eval"],
    references: [
      "WHO 6th semen manual",
      "Campbell-Walsh-Wein, Low ejaculate volume",
      "EAU Male Infertility",
    ],
    answer: [
      { t: "p", v: "WHO 6th lower reference for volume is 1.4 mL. A 1 mL ejaculate is hypospermia and in a man with primary infertility is a classic ‘site-of-lesion’ stem. Volume comes mostly from seminal vesicles (~70%, alkaline, fructose) and prostate (~20–30%); testes contribute <10%. Low volume therefore points to SV/ED/BN/androgen/collection problems — not to spermatogenic failure per se." },
      { t: "h", v: "Differential of volume ≈ 1 mL" },
      { t: "tbl", h: ["Cause", "Clues"], r: [
        ["Incomplete collection / short abstinence / spill", "History; repeat with 2–7 days abstinence at the lab"],
        ["Retrograde ejaculation", "Dry-ish orgasm, TURP/diabetes/α-blocker, sperm in post-orgasm urine"],
        ["EDO (complete or partial)", "Acidic pH, no fructose, azoo/OAT, dilated SV on TRUS, painful ejaculation/haematospermia"],
        ["CBAVD / SV agenesis", "Vas not palpable, acidic, no fructose; CFTR; kidneys OK bilaterally"],
        ["Hypogonadism / androgen lack", "Small volume + poor libido, low T, delayed secondary sexuals"],
        ["Sympathetic emission failure (SCI, RPLND, α-blocker, antidepressant)", "Orgasm ±; little emission; urine without sperm → anejaculation not RE"],
        ["Urethral stricture / meatal stenosis / hypospadias (spillage)", "LUTS, stream, exam"],
        ["Repeated ejaculation / collection in a condom (spermicide)", "History"],
      ]},
      { t: "h", v: "Stepwise evaluation of this 25-year-old" },
      { t: "ul", n: true, v: [
        "Repeat semen at the lab: abstinence, complete collection, record volume, pH, fructose, concentration, motility, morphology, round cells. Two samples.",
        "History: drugs (tamsulosin, silodosin, psychotropics), diabetes, TUR/urologic surgery, RPLND, SCI, TB, STD, haematospermia, painful ejaculation, anosmia, childhood hernia/orchidopexy, CF family.",
        "Exam: habitus, testes, epididymis, both vasa (the single most important physical sign), BN/prostate, meatus, hypospadias.",
        "Post-orgasm urine for sperm (RE vs true low-volume antegrade).",
        "Morning T, FSH, LH.",
        "If vas absent → CFTR couple + renal US (if unilateral).",
        "If vas present, pH <7.2, fructose negative, urine negative → TRUS for EDO.",
        "If hormones hypogonadal → treat HH / stop AAS.",
        "If all normal and sperm present but 1 mL — may still be partial EDO or idiopathic hypospermia; total sperm number (concentration × volume) decides ART, not volume alone.",
      ]},
      { t: "flow", title: "1 mL ejaculate", nodes: [
        { id: "a", kind: "start", label: "Confirm 1 mL on proper sample", to: ["b"] },
        { id: "b", kind: "decision", label: "Sperm in post-orgasm urine?", to: ["c", "d"] },
        { id: "c", kind: "end", label: "RE pathway (alkalise, sympathomimetic, urine retrieval, ICSI)" },
        { id: "d", kind: "decision", label: "Vas palpable both sides?", to: ["e", "f"] },
        { id: "f", kind: "end", label: "CBAVD/CUAVD pathway (CFTR, PESA/ICSI)" },
        { id: "e", kind: "decision", label: "pH <7.2, fructose −, azoo/OAT?", to: ["g", "h"] },
        { id: "g", kind: "end", label: "TRUS → TURED or PESA" },
        { id: "h", kind: "end", label: "Androgen lack / emission failure / idiopathic; treat cause, ART on total motile count" },
      ]},
      { t: "tip", k: "gold", v: "Palpate the vasa, measure pH/fructose, check post-orgasm urine. Those three manoeuvres split CBAVD vs EDO vs RE vs everything else." },
    ],
  },
  {
    id: "primary-infertility-eval",
    topicId: "infertility",
    title: "Evaluation of a 30-year-old man with primary infertility",
    highYield: true,
    gold: true,
    tags: ["work-up", "history", "semen", "WHO"],
    exams: [
      { session: "Dec", year: 2017, marks: "10", stem: "Evaluation of 30 years old male presenting 2 years after marriage with infertility." },
    ],
    related: ["who-semen", "azoospermia-workup", "oat", "genetic-male-infertility"],
    references: [
      "WHO 6th semen manual",
      "EAU Sexual and Reproductive Health / Male Infertility",
      "AUA/ASRM Male Infertility Guideline",
      "Campbell-Walsh-Wein, Evaluation of infertile male",
    ],
    answer: [
      { t: "p", v: "Infertility = failure to conceive after 12 months of regular unprotected intercourse (6 months if the female partner is ≥35). Primary = no prior conception. Male factor contributes ~50% (sole 20–30%, combined 20–30%). Evaluation of the man is indicated now — he is already at 2 years." },
      { t: "h", v: "Couple as the unit" },
      { t: "ul", v: [
        "See both partners. Female age, cycles, pelvic surgery, galactorrhoea, prior pregnancy, BMI. Parallel gynaecology referral — never serialise the woman after a year of ‘waiting for semen to improve’ if she is ≥32–35.",
        "Coital frequency, timing (LH kits), dyspareunia, unconsummated marriage, lubrication, erectile/ejaculatory function.",
        "Previous semen analyses, treatments, ART cycles.",
      ]},
      { t: "h", v: "Male history — the headings" },
      { t: "ul", v: [
        "Developmental: testicular descent, age of puberty, gynaecomastia, hypospadias, anosmia (Kallmann).",
        "Medical: mumps orchitis, STD, TB, epididymitis, diabetes, cystic fibrosis family, cancer, chronic disease, fever last 3 months.",
        "Surgical: orchidopexy, hernia (mesh), hydrocele, torsion, TUR, RPLND, pituitary.",
        "Drugs/toxins: AAS, testosterone, opioids, SSRI, α-blockers, 5-ARI, sulfasalazine, colchicine, chemo, pesticides, heat, sitting, laptop, tight clothing, cannabis, tobacco, alcohol.",
        "Occupational / thermal / radiation.",
        "Sexual: ED, PE, RE, libido, orgasm.",
        "Family: infertility, CF, Klinefelter phenotype, consanguinity.",
      ]},
      { t: "h", v: "Examination" },
      { t: "ul", v: [
        "BMI, BP, virilisation, gynaecomastia, smell, visual fields if HH suspected.",
        "Phallus, meatus, chordee, Peyronie.",
        "Testes: Prader orchidometer, lie, consistency. Adult mean ~18–20 mL; <12–15 mL suggests impaired spermatogenesis.",
        "Epididymis (full vs flat vs indurated), both vasa, varicocele (standing, Valsalva — Dubin–Amelar I–III), scars.",
        "DRE: prostate, midline cyst, SV.",
        "Secondary sexual characteristics and genital stage.",
      ]},
      { t: "h", v: "Investigations — tiered" },
      { t: "tbl", h: ["Tier", "Test", "When"], r: [
        ["1 — all men", "Semen analysis ×1–2 (WHO 6th)", "Always"],
        ["1", "Morning total testosterone, FSH ± LH", "Always in azoospermia/OA or if sexual symptoms; EAU: hormones if abnormal semen"],
        ["2", "Prolactin, TSH, HbA1c, iron studies", "Low T, symptoms, HH"],
        ["2", "Scrotal US ± Doppler", "Difficult exam, mass, volume discrepancy, suspected occult tumour; not to hunt subclinical varicocele"],
        ["2", "Karyotype + Y-microdeletion", "Azoospermia or concentration <5 × 10⁶/mL"],
        ["2", "CFTR + partner", "CBAVD, idiopathic OA, family CF"],
        ["2", "Post-ejaculate urine, TRUS", "Volume <1.4 mL"],
        ["3", "SDF, ROS, antisperm antibodies", "Unexplained, RPL, IVF failure, agglutination"],
        ["3", "Pituitary MRI", "HH, very high prolactin, visual symptoms"],
      ]},
      { t: "h", v: "What not to do" },
      { t: "ul", v: ["Routine diagnostic testicular biopsy", "Treating US-only varicocele", "Starting empiric testosterone (will azoospermise him)", "Ignoring the partner’s age", "Repeating semen weekly"] },
      { t: "tip", k: "exam", v: "Structure the 10 marks as: definition 1, history 2, exam 2, semen + hormones 2, second-line tests 2, counselling/next step 1. Mention WHO 6th numbers once." },
    ],
  },
  {
    id: "ivf-semen-processing",
    topicId: "infertility",
    title: "Prerequisites and semen processing for IVF",
    highYield: false,
    gold: false,
    tags: ["IVF", "swim-up", "density gradient", "ICSI"],
    exams: [
      { session: "Jun", year: 2014, marks: "4+6", stem: "Describe the prerequisites and semen processing for in-vitro fertilization (IVF)." },
    ],
    related: ["sperm-retrieval", "who-semen", "oat"],
    references: [
      "WHO 6th ed. — sperm preparation techniques",
      "Campbell-Walsh-Wein, ART for the urologist",
      "ESHRE / ASRM laboratory guidelines",
    ],
    answer: [
      { t: "h", v: "Prerequisites" },
      { t: "ul", v: [
        "Couple work-up complete: female age/AMH/AFC/tubes/uterus; male semen ×2, exam, indicated genetics (karyotype/Y/CFTR before ICSI in severe OA/NOA/CBAVD).",
        "Infectious screen of both (HIV, HBV, HCV, syphilis, ± HTLV) — legal/lab requirement for gamete handling; serodiscordant protocols exist.",
        "Informed consent: IVF vs ICSI, OHSS, multiple pregnancy, genetic risks, cryostorage, unused embryo fate, success rates by age.",
        "Optimise modifiable male factor first if time: varicocele, fever washout 74 days, stop AAS/T, treat infection, cryopreserve backup in cryptozoospermia.",
        "Abstinence 2–3 days (not 7 — SDF rises with long abstinence). Produce on-site 1–2 h before insemination / ICSI.",
        "Lab: WHO-compliant andrology, laminar flow, 37 °C, 6% CO2 incubators, identity double-witnessing (or electronic witnessing) to prevent mix-ups.",
        "Female: COS protocol, trigger, oocyte pick-up; luteal support — urologist should know the sperm must be ready the same morning.",
      ]},
      { t: "h", v: "Why process semen at all?" },
      { t: "p", v: "Raw semen contains seminal plasma (prostaglandins, zinc, decapacitation factors), debris, round cells, bacteria, ROS, dead sperm and non-sperm cells that impair capacitation, acrosome reaction and fertilisation, and are toxic in the dish. Processing selects motile, morphologically better spermatozoa, removes prostaglandins (which cause uterine cramps if used for IUI) and concentrates the pellet." },
      { t: "tbl", c: "Processing methods", h: ["Method", "How", "Best for", "Limitation"], r: [
        ["Dilution and wash (simple centrifugation)", "Mix with medium, spin 200–300 g, resuspend pellet", "Surgical samples with few sperm", "Does not select motile; pellets ROS-producing dead cells — avoid high-speed spin"],
        ["Swim-up", "Layer medium over washed pellet or liquefied semen; motile sperm swim into supernatant 30–60 min, 37 °C", "Normozoospermia, IUI/IVF with good motility", "Low yield; not for severe OA"],
        ["Density-gradient centrifugation (Puresperm / Isolate; Percoll obsolete medically)", "45/90% discontinuous silica-colloid; spin; collect pellet of mature dense sperm", "OAT, IUI, IVF workhorse", "Loss of some sperm; silica remnants if poorly washed"],
        ["Magnetic-activated cell sorting (MACS)", "Annexin-V beads bind apoptotic (PS-externalising) sperm", "High SDF, RPL, repeated ICSI failure", "Add-on; evidence mixed"],
        ["PICSI / hyaluronan binding", "Mature sperm bind hyaluronan", "Add-on for ICSI", "Not proven in all RCTs"],
        ["Electrophoretic / microfluidic chips", "Select low-SDF motile sperm without centrifugation", "Emerging", "Cost, availability"],
        ["Pentoxifylline / theophylline", "PDE inhibitor to induce motility in immotile surgical sperm", "TESE sperm for ICSI", "Use then wash; possible chromosomal concerns if overused"],
      ]},
      { t: "h", v: "IVF vs ICSI sperm prep" },
      { t: "ul", v: [
        "Conventional IVF: aim 50–100 × 10³ motile sperm per oocyte in microdrop; needs decent morphology/motility. Gradient ± swim-up.",
        "ICSI: a single viable spermatozoon. Immotile TESE sperm — hypo-osmotic swelling, pentoxifylline, or laser touch to pick a live one. For globozoospermia add oocyte activation (calcium ionophore).",
        "Surgically retrieved: wash in HEPES/G-MOPS, ICSI the same day or vitrify/slow-freeze in multiple straws.",
        "HIV+ male: gradient + swim-up (double wash) + ICSI, undetectable viral load — seroconversion of female extremely rare in experienced centres.",
      ]},
      { t: "tip", k: "exam", v: "Prerequisites = couple evaluation, infection screen, consent, lab identity checks. Processing = wash, swim-up, density gradient. ICSI when counts/motility/morphology/surgical sperm demand it." },
    ],
  },
  {
    id: "genetic-male-infertility",
    topicId: "infertility",
    title: "Genetic causes of male infertility — enumerate and classify",
    highYield: true,
    gold: true,
    tags: ["karyotype", "AZF", "CFTR", "Kallmann"],
    exams: [
      { session: "Dec", year: 2011, marks: "10", stem: "What are the genetic causes of male infertility? Enumerate and classify." },
    ],
    related: ["noa-genetics", "klinefelter", "cuavd"],
    references: [
      "Campbell-Walsh-Wein, Genetics of male infertility",
      "EAU Male Infertility Guidelines",
      "WHO / AUA-ASRM genetic testing statements",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Classify by: (1) chromosomal numerical / structural, (2) Y-microdeletion, (3) single-gene (CFTR, CHH, androgen receptor, myotonic dystrophy), (4) syndromic / DSD, (5) mitochondrial / polygenic. Quote that 15–30% of azoospermia/severe OA has a detectable genetic cause." },
      { t: "h", v: "Chromosomal — numerical" },
      { t: "tbl", h: ["Karyotype", "Phenotype", "Fertility note"], r: [
        ["47,XXY Klinefelter (and mosaics 46,XY/47,XXY)", "Small firm testes, hypergonadotropic hypogonadism, ± tall, gynaecomastia, metabolic syndrome, germ-cell tumour risk slight", "Commonest genetic cause of NOA. micro-TESE + ICSI. Mosaic better."],
        ["47,XYY", "Often normal / tall; variable semen", "Usually preserved fertility; slightly more OA"],
        ["46,XX testicular DSD (SRY+ usually)", "Male phenotype, SCOS, very small testes", "No autologous sperm. Do not TESE."],
        ["45,X/46,XY mixed gonadal dysgenesis", "Ambiguous to male, streak/dysgenetic gonad, tumour risk", "Streak gonadectomy; fertility poor"],
        ["47,XXY variants / 48,XXXY etc.", "More severe", "TESE almost never"],
      ]},
      { t: "h", v: "Chromosomal — structural" },
      { t: "ul", v: [
        "Robertsonian translocations (13;14, 14;21) — oligozoospermia, recurrent miscarriage, unbalanced offspring → PGT-SR.",
        "Reciprocal translocations and inversions — similar.",
        "Y-autosome translocations, ring Y — often NOA.",
      ]},
      { t: "h", v: "Y-chromosome microdeletions (AZF)" },
      { t: "p", v: "See NOA card. AZFa / complete AZFb = no TESE. AZFc = TESE/ICSI possible; 100% transmission to sons. Screen all NOA and concentration <5 × 10^6/mL." },
      { t: "h", v: "Single-gene / monogenic" },
      { t: "tbl", h: ["Gene / condition", "Inheritance", "Urologic picture"], r: [
        ["CFTR (including 5T / R117H)", "AR", "CBAVD ± mild CF; semen acidic, SV atretic; testes normal. Partner testing mandatory."],
        ["ADGRG2", "X-linked", "CBAVD CFTR-negative"],
        ["ANOS1 (KAL1), FGFR1, PROKR2, CHD7, TAC3…", "X-L / AD / AR", "Kallmann / CHH — treatable with gonadotrophins"],
        ["AR (androgen receptor) — AIS, Kennedy SBMA", "X-linked", "Phenotype from CAIS female to infertile male; Kennedy: adult OA + neurology. CAG repeats."],
        ["INSL3 / RXFP2", "AD variable", "Cryptorchidism"],
        ["NR5A1 (SF1), WT1, SRY", "AD / Y", "DSD, NOA, tumour risk"],
        ["TEX11", "X-linked", "Maturation arrest NOA"],
        ["AURKC, DPY19L2, SPATA16", "AR", "Macrozoospermia, globozoospermia — ICSI ± AOA, PGT"],
        ["DNAH / CCDC (PCD genes)", "AR", "Primary ciliary dyskinesia / Kartagener — immotile sperm, ICSI"],
        ["DMPK (myotonic dystrophy 1)", "AD CTG repeat", "OA, hypogonadism; anticipate anaesthetic issues"],
        ["FSH/LH receptor, FSHβ", "AR", "Isolated spermatogenic failure / HH"],
      ]},
      { t: "h", v: "Syndromic / developmental" },
      { t: "ul", v: [
        "Kartagener / PCD — dextrocardia, sinusitis, immotile sperm.",
        "Prune belly, exstrophy, prune-belly vas anomalies.",
        "Prader–Willi — HH.",
        "Noonan, Bardet–Biedl, persistent Müllerian duct (AMH/AMHR2) — azoospermia and need to remove Müllerian remnants carefully (vass hug the remnant).",
        "Mitochondrial deletions — rare asthenozoospermia (sperm midpiece mitochondria).",
      ]},
      { t: "tip", k: "gold", v: "Routine tests: karyotype + AZF in NOA/severe OA; CFTR in CBAVD. Everything else is phenotype-directed. Genetic diagnosis exists to (1) avoid futile TESE, (2) protect offspring, (3) find treatable CHH." },
    ],
  },
  {
    id: "klinefelter",
    topicId: "infertility",
    title: "Klinefelter syndrome — fertility issues and management",
    highYield: true,
    gold: true,
    tags: ["47XXY", "micro-TESE", "hypogonadism"],
    exams: [
      { session: "Jun", year: 2016, marks: "4+6", stem: "Fertility issues in Klinefelter's syndrome and their management options." },
    ],
    related: ["noa-genetics", "genetic-male-infertility", "sperm-retrieval"],
    references: [
      "Campbell-Walsh-Wein, Klinefelter",
      "EAU Male Infertility",
      "Aksglaede / Groth reviews; Plotton / Corona micro-TESE series",
    ],
    answer: [
      { t: "p", v: "Klinefelter syndrome (KS) = extra X in a phenotypic male, classically 47,XXY (~80–90%); remainder mosaics (46,XY/47,XXY) or higher-grade aneuploidy. Incidence ~1:600 males; many are diagnosed only at infertility clinic. It is the commonest chromosomal cause of NOA." },
      { t: "h", v: "Why they are infertile" },
      { t: "ul", v: [
        "Germ-cell loss accelerates at puberty; adult histology is SCOS ± focal spermatogenesis in a minority of tubules (the 46,XY clones).",
        "Hypergonadotropic hypogonadism: high FSH/LH, T low or low-normal, INSL3/inhibin B low, AMH low after puberty.",
        "Testes small (<4–6 mL), firm (hyalinised tubules, Leydig hyperplasia).",
        "Non-mosaic adults: azoospermia in ~90%+; mosaic and younger men may have crypto/oligozoospermia.",
        "Sperm that exist have a higher (but still low absolute) rate of sex-chromosome aneuploidy.",
      ]},
      { t: "h", v: "Fertility options" },
      { t: "tbl", h: ["Option", "Who", "Notes"], r: [
        ["Ejaculated sperm + ICSI", "Rare adults with cryptozoospermia; adolescents during the brief pubertal window", "Bank any sperm found — counts vanish with age"],
        ["micro-TESE + ICSI", "Azoospermic KS desiring biological paternity", "Retrieval 30–50% in experienced centres (range 20–70%). Better if mosaic, younger, higher baseline T, not on long-term TRT. Conventional TESE inferior."],
        ["TESE before starting TRT, or after 6 months off TRT bridged with hCG ± SERM/aromatase inhibitor", "Hypogonadal KS on testosterone", "Exogenous T suppresses residual spermatogenesis — stop it"],
        ["Adolescent / peri-pubertal TESE or semen banking", "Controversial", "Some centres offer at 15–18 if sperm appear; EAU: discuss, do not mandate. Fertility preservation evidence still evolving."],
        ["Donor sperm / adoption / child-free", "Retrieval fails, or couple choice", "Must be offered before the TESE cycle"],
        ["PGT-A / prenatal diagnosis", "All ICSI pregnancies in KS", "Most offspring 46,XY or 46,XX; residual aneuploidy risk — counsel honestly, not alarmist"],
      ]},
      { t: "h", v: "Non-fertility management the urologist co-owns" },
      { t: "ul", v: [
        "TRT after sperm is secured — lifelong, for bone, muscle, mood, metabolic, sexual function.",
        "Metabolic syndrome, insulin resistance, VTE, breast cancer (still rare) / gynaecomastia (mastectomy if needed), osteoporosis (DEXA), varicose veins.",
        "Slight increase in mediastinal GCT and breast carcinoma — examine, low threshold for imaging.",
        "Psychosocial, language, learning — refer.",
        "Genetic counselling of the man and of a future pregnancy.",
      ]},
      { t: "tip", k: "gold", v: "Do not start testosterone until the fertility plan is clear. micro-TESE (not TESA) is the retrieval of choice. Quote a 40% chance of sperm, ICSI pregnancy thereafter similar to other NOA once sperm are found." },
    ],
  },
  {
    id: "unconsummated-marriage",
    topicId: "infertility",
    title: "Unconsummated marriage — evaluation and management",
    highYield: false,
    gold: false,
    tags: ["UCM", "vaginismus", "ED", "PE"],
    exams: [
      { session: "Dec", year: 2017, marks: "5+5", stem: "Unconsummated marriage (UCM) - Evaluation and management." },
    ],
    related: ["pe-pharma", "ejaculatory-disorders", "erection-hemodynamics", "hypospadias"],
    references: [
      "ISSM / EAU Sexual Medicine",
      "Campbell-Walsh-Wein, Sexual dysfunction",
      "Masters & Johnson; Indian series on UCM (Ghanem, Zargooshi, cultural context)",
    ],
    answer: [
      { t: "p", v: "Unconsummated marriage (UCM) is the inability of a couple to achieve penile–vaginal penetration despite desire to do so, typically presenting after weeks to years of marriage. In Indian exam practice it is a couple diagnosis, not a male diagnosis: male ED/PE/anatomic and female vaginismus/unruptured hymen/anatomic are equally common, often combined with performance anxiety and cultural silence." },
      { t: "h", v: "Evaluation — see them together and separately" },
      { t: "ul", v: [
        "Confidential sexual history from each partner: desire, arousal, erection rigidity (and morning erections), ejaculation timing, pain, fear, prior trauma, pornography-only arousal, same-sex attraction, gender dysphoria, religious/cultural beliefs, family pressure.",
        "Is it never-consummated vs early then stopped? Lifelong vs acquired ED/PE?",
        "Male exam: phallus size buried in fat, hypospadias, chordee, Peyronie, phimosis, tight frenulum, meatal stenosis, epispadias, micropenis (stretched length <7–8 cm), testes/T Tanner stage.",
        "Female exam (gynaecologist): vaginismus (involuntary levator spasm), imperforate/microperforate/rigid hymen, vaginal septum, Mayer–Rokitansky (absent vagina — rare but must not be missed), lichen sclerosus, infection.",
        "Labs as indicated: morning T if ED/low desire, glucose, TSH. NPT or PDE5 trial if psychogenic vs organic ED unclear.",
        "Validated scores: IIEF-5, PEDT, Female Sexual Function Index — optional but look scholarly.",
      ]},
      { t: "tbl", h: ["Cause cluster", "Typical story", "First moves"], r: [
        ["Psychogenic ED / performance anxiety", "Good morning erections, fails on wedding night, spectatoring", "Education, PDE5 on-demand, sensate-focus, delay penetrative goal"],
        ["Lifelong PE", "Ejaculation on crowning or before entry", "Topical anaesthetic + SSRI/dapoxetine + start–stop; PDE5 if erection lost after ejaculation"],
        ["Organic ED", "Diabetic, pelvic trauma, no morning erections", "Standard ED pathway"],
        ["Phimosis / frenulum breve / buried penis / severe chordee / hypospadias", "Pain, buckling, missing the introitus", "Circumcision/frenuloplasty, weight loss + escutcheon, chordee correction"],
        ["Female vaginismus / fear", "Cannot tolerate tampon or exam; pelvic floor brick", "Pelvic-floor PT, dilators, CBT, topical anaesthetic, rarely Botox under anaesthesia; never forced examination"],
        ["Hymenal rigidity / septum", "Anatomic stop", "Hymenectomy / septum resection after counselling"],
        ["MRKH / DSD / micropenis / uncorrected proximal hypospadias", "Anatomic impossibility of PIV as currently constructed", "Honest reconstructive / fertility counselling; do not coerce gender or surgery"],
      ]},
      { t: "h", v: "Management principles" },
      { t: "ul", n: true, v: [
        "Treat as a couple. Ban ‘blame the man/woman’ language. Stop family-imposed deadlines.",
        "Sex education (anatomy, that first-night bleeding is not mandatory, lubrication).",
        "Sensate-focus (Masters & Johnson) — non-demand touching, then genital, then penetration last.",
        "Male drugs as above (PDE5, PE pharmacotherapy).",
        "Female: vaginal dilators in graded sizes, pelvic physiotherapy, treat infection/dermatosis, surgery only for a defined anatomic lesion.",
        "Fertility: if the only goal is conception and penetration remains impossible in the short term — IUI/IVF without waiting years. UCM is not a reason to deny ART. Also offer semen analysis now — some men have never ejaculated vaginally and have OAT/RE independently.",
        "Psychiatry/sex therapy when trauma, phobia, severe anxiety, or couple conflict dominate. SSRIs may worsen ED/PE — coordinate.",
        "Do not offer virginity-restoration surgery or hymenoplasty as a fertility treatment.",
      ]},
      { t: "tip", k: "exam", v: "Marks split naturally: male causes / female causes / psychogenic / investigations / multidisciplinary treatment. Mention PDE5, dapoxetine/topical, dilators, and that ART is legitimate if time is being lost." },
    ],
  },
];
