import type { Master } from "../types";

export const laparoscopy: Master[] = [
  {
    id: "ann-robotic-ar",
    topicId: "laparoscopy",
    title: "ANN in urology, robotic systems and augmented reality",
    highYield: true,
    gold: true,
    tags: ["ANN", "AI", "robotics", "AR", "Hugo", "da Vinci"],
    exams: [
      { session: "June", year: 2022, marks: "4+3+3", stem: "Discuss the application of Artificial Neural Networks in Urology (ANN). Describe the various robotic systems that are available in Urology. Augmented reality." },
    ],
    related: ["davinci", "robotic-surgery-role", "vr-ar-navigation"],
    references: [
      "Campbell-Walsh-Wein 12e, Surgical robotics / New technologies",
      "Glenn's Urologic Surgery; Hinman Atlas",
      "EAU Guidelines — robotic surgery sections; Tewari / Menon historical ANN-PCa papers",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map (10 marks)", v: "ANN definition + 4 GU applications 4 · Named robotic platforms (not only da Vinci) 3 · AR definition + intra-op uses 3." },
      { t: "h", v: "Artificial neural networks" },
      { t: "p", v: "An ANN is a computational model of layered ‘neurons’ (input → hidden layer(s) → output) whose connection weights are trained on labelled data by backpropagation. It models non-linear relationships that logistic regression may miss. Overfitting, black-box lack of interpretability, and the need for external validation are the examiner’s caveats." },
      { t: "ul", v: [
        "Prostate cancer: historical ANN nomograms (PCa diagnosis from PSA/DRE/TRUS; staging vs Partin; biochemical-recurrence prediction — Tewari, Babaian). Now largely superseded by multivariable Cox nomograms, MRI (PI-RADS), and modern ML/deep learning on mpMRI and digital pathology.",
        "Stones: SWL success prediction, PCNL stone-free and bleeding risk, ureteroscopy outcomes.",
        "Oncology: bladder CIS/recurrence risk, RCC subtype/radiomics, testis marker kinetics, PSMA-PET lesion detection (CNNs — convolutional nets, a modern ANN family).",
        "Transplant: delayed graft function prediction; donor–recipient matching research.",
        "Administrative: triage of haematuria, automatic report coding, workflow.",
        "Limitations: garbage-in/garbage-out, calibration drift across populations, medicolegal opacity, must not replace clinical judgement. Quote: ANN is a tool for prediction, not a pathophysiologic explanation.",
      ]},
      { t: "h", v: "Robotic systems available in urology" },
      { t: "tbl", h: ["Platform", "Configuration", "Urologic note"], r: [
        ["da Vinci Xi / X (Intuitive)", "Multiport master–slave, 3–4 arms, 8 mm, Firefly ICG, Table Motion", "Dominant evidence base (RARP, RAPN, RARC)"],
        ["da Vinci SP", "Single 2.5 cm port, articulating 3-instrument + camera", "Selected RARP, RAPN, perineal, paediatric niche"],
        ["Hugo RAS (Medtronic)", "Modular open consoles, pistol grips, 5 mm/8 mm", "CE/select markets; early RARP series"],
        ["Versius (CMR)", "Bedside modular arms, open console, 5 mm", "Re-dock friendly; emerging GU"],
        ["Senhance (Asensus)", "Eye-tracking camera, reusable 5 mm, haptic feedback", "Limited GU penetration"],
        ["Revo-i, Hinotori, Avatera, Revo, KangDuo, Toumai", "Regional systems (Korea, Japan, Germany, China)", "Name two — shows you know da Vinci is not a monopoly"],
        ["Classic: AESOP, ZEUS, PROBOT, URobotics", "Historical camera holders / transurethral robots", "One-line history if asked ‘evolution’"],
      ]},
      { t: "h", v: "Augmented reality" },
      { t: "p", v: "AR overlays computer-generated imaging onto the real operative field in real time (vs VR, which replaces the field). Registration of a preoperative 3D CT/MRI model to the live laparoscopic/robotic view, or to the patient surface, is the hard step (rigid vs deformable registration of kidney with pneumoperitoneum and artery clamp)." },
      { t: "ul", v: [
        "RAPN: arterial tree + tumour + collecting system overlay to plan clamp strategy and resection margin (TilePro / third-party INSIGHT, Visible Patient).",
        "RARP: overlay of neurovascular bundles / frozen-section maps (NeuroSAFE research).",
        "PCNL access: iPad/HoloLens puncture guidance; fluoro-less targeting research.",
        "Training and patient counselling: holographic anatomy.",
        "Limits: deformation after mobilisation, ischaemia colour change, latency, cost, lack of Level-1 outcome benefit as of current EAU. Do not claim AR reduces PSM in routine practice.",
      ]},
      { t: "tip", k: "gold", v: "ANN predicts; robots telemanipulate; AR annotates. None of them replace haptics, anatomic knowledge or a plan for conversion." },
    ],
  },
  {
    id: "davinci",
    topicId: "laparoscopy",
    title: "da Vinci robotic platform — components, functions, limitations",
    highYield: true,
    gold: true,
    tags: ["da Vinci", "Xi", "EndoWrist", "Firefly", "robotics"],
    exams: [
      { session: "Jun", year: 2019, marks: "6+4", stem: "Describe functions and limitations of DaVinci robotic surgical platform." },
      { session: "Jun", year: 2016, marks: "2+4+4", stem: "What is DaVinci Robot Surgical System? Write in brief the main components of Robot Surgical System. Current status of DaVinci Robot in Urology." },
    ],
    related: ["ann-robotic-ar", "robotic-surgery-role", "haemostatic-devices"],
    references: [
      "Campbell-Walsh-Wein 12e, Robotic urologic surgery",
      "Hinman Atlas of Urologic Surgery",
      "Intuitive surgical system manuals; EAU RARP/RAPN chapters",
    ],
    answer: [
      { t: "p", v: "The da Vinci is a master–slave telemanipulator, not an autonomous robot. The surgeon’s console motions are scaled, tremor-filtered and transmitted to wristed instruments at the bedside cart. FDA 2000; urology (RARP) drove global adoption. Generations: Standard → S → Si → Xi/X → SP." },
      { t: "h", v: "Three hardware components" },
      { t: "ul", n: true, v: [
        "Surgeon console: stereoscopic 3D HD viewer (Si 1080p; Xi 3D HD), master grips, finger clutches, foot pedals (camera, energy, swap, monopolar/bipolar), optional dual console for teaching.",
        "Patient-side cart: 3–4 boom-mounted arms (Xi rotating boom, targeting; X is a slimmer Xi). 8 mm EndoWrist instruments with 7 degrees of freedom (yaw, pitch, roll, grip + insertion + two wrist).",
        "Vision cart: dual illuminators, image processing, insufflator interface, energy, Firefly near-infrared (ICG), TilePro multi-input (US, Flex, C-arm).",
      ]},
      { t: "h", v: "Functions / kinematic advantages" },
      { t: "ul", v: [
        "3D magnified (10–15×) stable vision; surgeon controls camera (no tired assistant).",
        "EndoWrist 7-dof vs laparoscopic 4-dof — suturing of urethra, UPJ, collecting system, NVB dissection.",
        "Motion scaling 1:1 to 5:1 and tremor filtration.",
        "Ergonomics: sit-down surgery; dual console mentoring.",
        "Xi extras: slimmer arms, 8 mm endoscope in any port (port hopping), integrated table motion, longer instruments, SP single-port access.",
        "Firefly ICG: perfusion of bowel/conduit, renal remnant, sentinel nodes, fluorescence cholangiography analogue for ureter (off-label IR dyes).",
      ]},
      { t: "h", v: "Limitations (write as a list — this is half the marks in Jun 19)" },
      { t: "ul", v: [
        "No true haptics — visual cues only; suture breakage and tissue tear are real.",
        "Capital cost, per-case consumables, service contract; opportunity cost vs trained laparoscopy.",
        "Setup / docking time; undocking delay in catastrophe (vascular injury) — bedside surgeon with open set is mandatory.",
        "Bulk; Xi better but still clashes in paediatric / small abdomen; limited working space after prior mesh/radiation.",
        "Loss of laparoscopic ‘table-side’ teamwork; communication through console.",
        "Instrument collisions, limited field if camera dirty, energy delay.",
        "Not autonomous — outcomes follow surgeon volume (RARP learning curve 100–300 cases for PSM/continence plateau in classic series).",
        "SP: instrument crowding, triangulation via elbow, not a panacea.",
        "Evidence: RARP vs open — less blood, shorter stay, similar long-term oncologic/continence/erectile outcomes when volume-matched (systematic reviews; ProtecT is not a robotic trial).",
      ]},
      { t: "h", v: "Current status in urology" },
      { t: "tbl", h: ["Procedure", "Status"], r: [
        ["RARP", "Standard in high-resource centres; most common robotic operation worldwide"],
        ["RAPN", "Preferred MIS for complex nephrometry when expertise exists; off-clamp / selective clamp / ICG"],
        ["RARC + intracorporeal diversion", "Growing; iROC RCT (UK) — recovery benefit vs open; still high-volume centres"],
        ["Pyeloplasty, ureteric reimplant, sacrocolpopexy", "Excellent MIS indications"],
        ["Donor nephrectomy", "Lap still gold in many units; robotic in selected"],
        ["RPLND, adrenal, simple prostatectomy, fistula", "Selected, expertise-dependent"],
      ]},
      { t: "tip", k: "gold", v: "da Vinci is a suturing and dissection enhancer with 3D vision. Quote limitations first if asked ‘functions and limitations’ — examiners punish uncritical marketing." },
    ],
  },
  {
    id: "robotic-surgery-role",
    topicId: "laparoscopy",
    title: "Role of robotic vs laparoscopic urologic surgery",
    highYield: true,
    gold: false,
    tags: ["RARP", "RAPN", "RARC", "laparoscopy", "evidence"],
    exams: [
      { session: "Jun", year: 2018, marks: "10", stem: "Role of robotic surgery in urology." },
      { session: "Jun", year: 2015, marks: "10", stem: "Role of Robotic Assisted Urological surgery vis-à-vis that of laparoscopic surgery." },
    ],
    related: ["davinci", "ann-robotic-ar", "paediatric-robotics", "3d-laparoscopy"],
    references: [
      "EAU Prostate / RCC / MIBC guidelines",
      "iROC trial (RARC vs open); Yaxley Lancet RARP vs open",
      "Campbell-Walsh-Wein 12e; Glenn's",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Organ-wise table of robot vs lap vs open. Do not claim oncologic superiority. Cost and access in India is a valid closing paragraph." },
      { t: "h", v: "Where the robot adds most versus laparoscopy" },
      { t: "p", v: "Robotics preserves MIS benefits (magnification, less blood, shorter stay) and restores degrees of freedom lost at laparoscopy — specifically intracorporeal suturing and working in a deep narrow pelvis. Procedures that are already easy laparoscopically (simple nephrectomy, straightforward donor) gain less." },
      { t: "tbl", h: ["Domain", "Robot vs laparoscopy", "Caveat"], r: [
        ["Radical prostatectomy", "Shorter learning curve than pure lap RP; 3D + wrists for anastomosis and NVB. Dominant MIS platform.", "Yaxley RCT vs open: early sexual/urinary similar at 12 wk when both high-volume; PSM not better automatically"],
        ["Partial nephrectomy", "Easier collecting-system repair, WIT often shorter after learning curve, complex (hilar, endophytic) more feasible", "Off-clamp/zero-ischaemia is a strategy, not a robot monopoly; lap PN still excellent in expert hands"],
        ["Radical cystectomy", "Intracorporeal diversion suturing; iROC: more days alive and out of hospital vs open", "OR time, cost; diversion complications still dominate; lap cystectomy never widely adopted"],
        ["Pyeloplasty / ureter / reimplant / Boari", "Suturing benefit clear in pelvis and UPJ", "Lap pyeloplasty already gold with equivalent success"],
        ["Nephrectomy / adrenal / donor", "Marginal vs conventional lap; SP marketing", "Lap donor remains reference; cost hard to justify"],
        ["RPLND / retroperitoneal", "Post-chemo selected high-volume centres", "Open remains standard for complex post-chemo"],
        ["Female pelvic / sacrocolpopexy / fistula", "Deep pelvis suturing", "Mesh/fistula expertise > platform"],
        ["Paediatric", "Pyeloplasty, selected reimplant", "Port size, cost, working space — see paediatric master"],
      ]},
      { t: "h", v: "Shared MIS advantages (robot AND lap vs open)" },
      { t: "ul", v: ["Less blood loss and transfusion", "Shorter LOS, less pain, hernia/wound benefit", "Magnified anatomy", "Equivalent cancer control when principles (template, margins, lymph nodes) are respected"] },
      { t: "h", v: "Shared and robot-specific disadvantages" },
      { t: "ul", v: [
        "Cost (robot >> lap), theatre time during learning curve, training access.",
        "Loss of haptics (worse than lap, where some tactile feedback remains).",
        "Conversion pathway must be rehearsed; bedside assistant is not optional.",
        "Health-system: concentrating cases in robotic centres vs deskilling open surgery for catastrophe and resource-poor settings.",
      ]},
      { t: "tip", k: "gold", v: "Robot > laparoscopy when the operation is suture-intensive in a deep hole (RARP anastomosis, RAPN, intracorporeal neobladder). Laparoscopy remains enough for extirpative kidney surgery in expert hands." },
    ],
  },
  {
    id: "3d-laparoscopy",
    topicId: "laparoscopy",
    title: "3-D vision laparoscopy — advantages and limitations",
    highYield: false,
    gold: false,
    tags: ["3D", "laparoscopy", "stereopsis", "ergonomics"],
    exams: [
      { session: "Jun", year: 2017, marks: "10", stem: "3-D Vision Laparoscopy: Advantages and limitations." },
    ],
    related: ["davinci", "robotic-surgery-role", "simulators-urology"],
    references: [
      "Campbell-Walsh-Wein 12e, Laparoscopic surgery",
      "Hinman Atlas; EAES 3D laparoscopy consensus",
    ],
    answer: [
      { t: "p", v: "3D laparoscopy uses a stereoscopic (dual-channel or dual-chip) laparoscope and a 3D monitor ± polarised glasses to restore binocular depth perception lost in conventional 2D laparoscopy. It sits between 2D lap and robotic 3D console vision in cost and capability — wrists are still straight laparoscopic instruments." },
      { t: "h", v: "Advantages" },
      { t: "ul", v: [
        "Stereopsis: improved depth judgement for suturing (pyeloplasty, PN, vesicourethral anastomosis), lymph-node dissection, and working near vessels.",
        "Shorter task time and fewer errors in box-trainer and clinical studies, especially for novices and for intracorporeal suturing; experts benefit less (they already reconstruct depth from 2D cues: shadow, motion parallax, relative size).",
        "Lower capital cost than a robot; uses standard ports and instruments; easier to deploy in Indian teaching hospitals.",
        "Teaching: assistants and trainees see the same 3D field (unlike early robotic systems without dual console).",
        "4K-3D stacks further improve resolution.",
      ]},
      { t: "h", v: "Limitations" },
      { t: "ul", v: [
        "Does not add degrees of freedom — still stick instruments, fulcrum effect, assistant-dependent camera.",
        "Glasses (polarised/active shutter): fogging, headache, nausea, visual fatigue in 10–30%; not all surgeons have good stereopsis (stereo-blind ~5%).",
        "Camera: 3D scopes are bulkier (10 mm typical), fog more, require precise horizon; loss of 3D if one channel soils.",
        "Cost still higher than 2D HD; evidence of better hard clinical endpoints (PSM, WIT, complications) is mixed/absent — most gains are ergonomic and technical.",
        "Does not fix poor triangulation, obesity, or adhesions.",
      ]},
      { t: "tip", k: "exam", v: "One-liner: 3D laparoscopy buys robotic-like vision without robotic wrists. Use it as the answer to ‘poor man’s robot’ only with that caveat." },
    ],
  },
  {
    id: "simulators-urology",
    topicId: "laparoscopy",
    title: "Simulators in urology",
    highYield: false,
    gold: false,
    tags: ["simulation", "VR", "box trainer", "GEARS", "OSATS"],
    exams: [
      { session: "Jun", year: 2014, marks: "10", stem: "Write short note on Simulator in Urology." },
    ],
    related: ["vr-ar-navigation", "davinci", "3d-laparoscopy"],
    references: [
      "Campbell-Walsh-Wein 12e, Surgical education",
      "AUA / EAU education papers; Satava / Gallagher simulation framework",
      "GEARS, OSATS, GOALS validation literature",
    ],
    answer: [
      { t: "p", v: "A simulator is a device or environment that reproduces tasks of a real operation so that skills can be acquired, measured and rehearsed without patient risk. In urology this spans bench models, animal/cadaver labs, high-fidelity VR, and full-team crisis simulation (TURP syndrome, laparoscopic gas embolism)." },
      { t: "h", v: "Classification" },
      { t: "tbl", h: ["Type", "Examples", "What it trains"], r: [
        ["Low-fidelity bench / box", "Pelvic trainer, laparoscopic peg transfer, suturing pads, Uro-Scopic trainer, K-box for fURS", "Psychomotor: pegs, cutting, knot-tying, scope navigation"],
        ["Hybrid / physical high-fidelity", "C-arm PCNL models, 3D-printed kidneys, prostate phantoms, SimPORTAL", "Fluoro targeting, access, resection feel"],
        ["VR / computer", "LAP Mentor, UroMentor, TURP sim, dV-Trainer, Mimic FlexVR, da Vinci SimNow, Simbionix", "Procedure rehearsal, energy, metrics, robotic skills"],
        ["Animal / cadaver / fresh-frozen", "Porcine lap nephrectomy, human cadaver RARP", "True tissue, team, but cost/ethics"],
        ["Team / non-technical", "OR crisis scenarios, WHO checklist drills", "Communication, conversion, bleeding"],
      ]},
      { t: "h", v: "Validity (quote these words)" },
      { t: "ul", v: [
        "Face and content validity: looks and feels relevant to experts.",
        "Construct validity: distinguishes novice vs expert.",
        "Concurrent / predictive validity: scores correlate with OR performance.",
        "Proficiency-based progression (Gallagher): train to a criterion, not to a time-on-simulator. Warm-up before lists has evidence for robotic skills.",
      ]},
      { t: "h", v: "Assessment tools" },
      { t: "ul", v: ["OSATS — Objective Structured Assessment of Technical Skills", "GOALS — Global Operative Assessment of Laparoscopic Skills", "GEARS — Global Evaluative Assessment of Robotic Skills (depth, bimanual, efficiency, force, autonomy, camera)", "Likert global rating + procedure-specific checklists"] },
      { t: "h", v: "Urologic curriculum sketch" },
      { t: "ul", v: [
        "Endourology: UroMentor / K-box before independent URS; PCNL VR + printed kidney before fluoro access.",
        "TURP simulators reduce resection errors in trainees.",
        "Laparoscopy: FLS-like box → supervised lap nephrectomy.",
        "Robotics: dual-console + SimNow modules (camera, energy, suturing) before console time; 10–20 h VR common in fellowships.",
      ]},
      { t: "tip", k: "gold", v: "Simulation is for deliberate practice with feedback. Hours on a VR box without coaching do not equal competence." },
    ],
  },
  {
    id: "less-notes",
    topicId: "laparoscopy",
    title: "LESS, NOTES and related MIS advances",
    highYield: true,
    gold: false,
    tags: ["LESS", "NOTES", "single port", "SP", "minimally invasive"],
    exams: [
      { session: "Dec", year: 2012, marks: "2+2+3+3", stem: "Briefly describe the following advances in minimally invasive renal surgery: LESS, NOTES, Virtual reality and Intra-operative fluorescence." },
      { session: "Dec", year: 2015, marks: "2+2+6", stem: "Define Natural Orifice Trans-luminal Endoscopic Surgery (NOTES). Enumerate the different routes used for NOTES. Limitations of NOTES in relation to urological practice." },
    ],
    related: ["vr-ar-navigation", "icg-urology", "davinci", "ann-robotic-ar"],
    references: [
      "Campbell-Walsh-Wein 12e, LESS and NOTES",
      "Gettman / Clayman / Kaouk early NOTES and LESS series",
      "Hinman Atlas; Glenn's",
    ],
    answer: [
      { t: "h", v: "LESS — laparoendoscopic single-site surgery" },
      { t: "p", v: "LESS uses one skin incision (usually umbilicus) with a multichannel port (TriPort, GelPOINT, SILS, R-port) so that camera and instruments share a coaxial corridor. Cosmesis and one-hernia-site logic drove it; robotics (da Vinci SP) is the current reincarnation." },
      { t: "ul", v: [
        "GU uses: nephrectomy (simple > radical), donor (selected), pyeloplasty, adrenal, ureterolithotomy, renal cyst, orchidopexy/orchiectomy.",
        "Problems: loss of triangulation, instrument clashing, in-line viewing, need for articulating/crossed instruments and a bariatric-length camera, steep learning curve. Conversion to reduced-port or conventional lap is not a failure.",
        "Evidence: equivalent complications in expert series; no oncologic advantage; hernia at the large umbilical extraction site is not zero. Largely niche after the 2007–2013 enthusiasm.",
      ]},
      { t: "h", v: "NOTES — definition and routes" },
      { t: "p", v: "Natural Orifice Transluminal Endoscopic Surgery: peritoneal or retroperitoneal operations performed through a natural viscus without (or with only an assisting) skin incision. Pure NOTES = no transabdominal ports; hybrid NOTES = transvisceral + one or more laparoscopic ports (the usual GU reality)." },
      { t: "tbl", h: ["Route", "GU examples / comments"], r: [
        ["Transvaginal", "Most used in women: nephrectomy extraction, hybrid NOTES nephrectomy (Gettman 2002 animal; clinical hybrid series). Colpotomy closure critical."],
        ["Transgastric", "General-surgery heritage (Kalloo); poor for kidney retrieval; contamination; closure of gastrotomy is the Achilles heel."],
        ["Transvesical", "Lima / Gettman lab work; bladder as a sterile portal for peritoneoscopy, lymphadenectomy research. Limited by calibre and closure."],
        ["Transrectal / transcolonic", "TEO/TAMIS heritage; contamination risk high; not standard GU."],
        ["Transurethral", "Not classic NOTES but conceptual cousin: transurethral NOTES-like prostate/bladder; HOLEP is endoscopic not NOTES."],
        ["Transoesophageal", "Not urologic."],
      ]},
      { t: "h", v: "Limitations of NOTES in urology (Dec 15 part c — 6 marks)" },
      { t: "ul", v: [
        "Solid organs (kidney) need a large extraction path — defeats ‘no scar’ unless vagina is used in multiparous women.",
        "Reliable viscerotomy closure (gastric, vesical, rectal) not standardised; leak = peritonitis / fistula.",
        "Orientation, retraction, haemostasis and suturing with flexible tools are inferior to laparoscopy/robot.",
        "Infection, viscus-specific morbidity (dyspareunia after colpotomy, bladder dysfunction), lack of dedicated GU energy/stapler tools.",
        "Steep learning, ethics, and no Level-1 benefit over conventional MIS. Hybrid NOTES is a cosmetic extraction strategy, not a new cancer operation.",
        "Oncologic specimen integrity (bag) harder. Male patients lack the best extraction orifice.",
      ]},
      { t: "h", v: "VR and intra-operative fluorescence (the other Dec 12 limbs)" },
      { t: "ul", v: [
        "VR: preoperative rehearsal on patient-specific 3D CT (vessel anatomy for RAPN), and VR simulators for skills — see simulators and VR/AR masters.",
        "Intra-operative fluorescence: ICG–NIR (Firefly) for arterial mapping, perfusion of remnant, tumour hypofluorescence in some RCC, biliary/ureter research, conduit perfusion. Fluorescein, methylene blue, 5-ALA are other fluorophores.",
      ]},
      { t: "tip", k: "gold", v: "LESS = one skin hole, still laparoscopic physics. NOTES = hole through a viscus. Hybrid transvaginal extraction after lap nephrectomy is the only NOTES variant most urologists will ever do." },
    ],
  },
  {
    id: "haemostatic-devices",
    topicId: "laparoscopy",
    title: "Haemostatic devices and agents in lap and robotic urology",
    highYield: true,
    gold: false,
    tags: ["Harmonic", "LigaSure", "Hem-o-lok", "Floseal", "energy"],
    exams: [
      { session: "Jun", year: 2017, marks: "10", stem: "Haemostatic devices and agents during laparoscopy & Robot assisted urological surgery." },
    ],
    related: ["davinci", "robotic-surgery-role", "less-notes"],
    references: [
      "Campbell-Walsh-Wein 12e, Haemostasis / laparoscopic nephrectomy",
      "Hinman Atlas; manufacturer IFUs for vessel sealers",
      "EAU / AUA intraoperative bleeding chapters",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Divide into: (1) mechanical, (2) energy devices, (3) topical agents, (4) systemic. Add a renal-hilum protocol." },
      { t: "h", v: "Mechanical" },
      { t: "tbl", h: ["Device", "Use / limit"], r: [
        ["Weck Hem-o-lok (non-absorbable polymer)", "Renal artery/vein, ureter; two clips artery proximal. NEVER for live-donor artery (FDA/donor deaths from clip dislodgement) — use stapler on donor artery."],
        ["Titanium clips (Ligaclip)", "Small vessels; can cut through; poor on thick pedicles"],
        ["Endo GIA / endoscopic stapler (vascular load 2.5 mm)", "Hilar transection, bowel, ileal conduit; know fail-to-fire drill"],
        ["Suture: Hem-o-lok on Vicryl, barbed (V-Loc, Stratafix), sliding-clip renorrhaphy (Benway)", "PN inner collecting system + outer parenchyma"],
        ["Bulldog / Satinsky / Rummel / laparoscopic tourniquet", "Hilar clamp for PN; robotic bulldogs"],
      ]},
      { t: "h", v: "Energy devices" },
      { t: "tbl", h: ["Device", "Mechanism", "Seal rating / pearl"], r: [
        ["Monopolar scissors / hook / PK", "RF cutting/coag", "Lateral thermal spread 2–5 mm; insulation failure risk; avoid near bowel/ureter"],
        ["Bipolar fenestrated / Maryland", "RF between jaws", "Precise; workhorse at console"],
        ["LigaSure / Covidien vessel sealer", "RF + pressure, impedance-controlled", "Seals arteries ≤7 mm; good for mesentery, packet, simple nephrectomy"],
        ["Harmonic ACE (ultrasonic shears)", "55.5 kHz mechanical + heat", "Low lateral spread (~1–2 mm); cuts and seals ≤5 mm; blade stays hot after use"],
        ["Thunderbeat", "Ultrasonic + bipolar in one jaw", "Fast cut + seal"],
        ["Enseal / VesselSealer robotic", "Bipolar with I-beam compression", "Robotic 8 mm sealer"],
        ["Argon beam / spray coag", "Ionised argon RF", "Surface raw PN bed, bladder; watch overpressure / gas embolism — vent always"],
        ["Laser (rarely at lap PN)", "Photothermal", "Not first-line haemostasis"],
      ]},
      { t: "h", v: "Topical haemostatic agents" },
      { t: "ul", v: [
        "Oxidised regenerated cellulose: Surgicel / Fibrillar — scaffold, pack PN crater.",
        "Gelatin sponge: Gelfoam.",
        "Gelatin-thrombin matrix: Floseal, Surgiflo — flowable in PN bed after inner suture.",
        "Fibrin sealant: Tisseel, Evicel — mix thrombin + fibrinogen; also used as suture-line ‘glue’ and for chyle leak.",
        "Polyethylene glycol: Coseal, Progel — synthetic sealant (collecting system / dura analogue).",
        "Cyanoacrylate: limited intra-abdominal use.",
        "Do not inject flowable agents into open vessels (thromboembolism). Allow 2 minutes of undisturbed contact.",
      ]},
      { t: "h", v: "Systemic adjuncts" },
      { t: "ul", v: ["Correct hypothermia, acidosis, hypocalcaemia, platelets, INR", "Tranexamic acid in selected bleeding (evidence stronger in prostatectomy/TURP than RAPN)", "Reversal of anticoagulants; cell saver in selected open/salvage", "Angioembolisation as a postoperative rescue for PN bleed"] },
      { t: "flow", title: "Hilar control for lap/robot nephrectomy", nodes: [
        { id: "a", kind: "start", label: "Complete hilar dissection; identify artery then vein", to: ["b"] },
        { id: "b", kind: "decision", label: "Live donor?", to: ["c", "d"] },
        { id: "c", kind: "action", label: "Vascular stapler on artery AND vein; never Hem-o-lok on donor artery", to: ["e"] },
        { id: "d", kind: "action", label: "Two Hem-o-loks + one transfixion or stapler on artery; vein clips/stapler", to: ["e"] },
        { id: "e", kind: "warn", label: "If stapler misfires: laparoscopic pressure, additional clips if visible, low threshold to convert / Satinsky", to: ["f"] },
        { id: "f", kind: "end", label: "Confirm haemostasis at 5 mmHg to unmask venous bleed" },
      ]},
      { t: "tip", k: "warn", v: "Donor artery + Hem-o-lok is a never-event. Name it." },
    ],
  },
  {
    id: "vr-ar-navigation",
    topicId: "laparoscopy",
    title: "Virtual reality and augmented reality surgical navigation",
    highYield: false,
    gold: false,
    tags: ["VR", "AR", "navigation", "ICG", "fluorescence"],
    exams: [
      { session: "Jun", year: 2016, marks: "5+5", stem: "Virtual reality and augmented reality as used in surgical navigation." },
      { session: "Dec", year: 2012, marks: "2+2+3+3", stem: "Briefly describe the following advances in minimally invasive renal surgery: LESS, NOTES, Virtual reality and Intra-operative fluorescence." },
    ],
    related: ["ann-robotic-ar", "simulators-urology", "icg-urology", "less-notes"],
    references: [
      "Campbell-Walsh-Wein 12e, Image-guided surgery",
      "Ukimura / Gill / Teber AR-PN papers",
      "Hinman Atlas",
    ],
    answer: [
      { t: "tbl", h: ["", "Virtual reality", "Augmented reality"], r: [
        ["Definition", "Immersive computer world; real field is replaced", "Computer graphics superimposed on the real field"],
        ["Navigation use", "Pre-op rehearsal of patient-specific 3D CT (vessel/tumour); VR simulators", "Intra-op overlay of CT/MRI model on lap/robot view or patient skin"],
        ["Training use", "dV-Trainer, SimNow, UroMentor", "HoloLens anatomy teaching"],
      ]},
      { t: "h", v: "Surgical navigation pipeline" },
      { t: "ul", n: true, v: [
        "Acquire high-quality multiphase CT/MRI.",
        "Segment kidney, tumour, arteries, veins, collecting system (manual or AI).",
        "Register model to live image (optical/fiducial/surface matching). Deformable registration after mobilisation and pneumoperitoneum is the unsolved problem.",
        "Display: TilePro, 3D monitor, HoloLens, projector.",
        "Update with live US or ICG when the overlay drifts.",
      ]},
      { t: "h", v: "Urologic applications" },
      { t: "ul", v: [
        "RAPN / lap PN: locate endophytic tumour, colour-code feeding arteries, plan clamp and renorrhaphy. Intra-op US remains the workhorse when overlay fails.",
        "PCNL: puncture guidance (fluoro fusion, electromagnetic, iPad AR) — reduces attempts in research series.",
        "Prostate: mpMRI–US fusion biopsy is the mature ‘navigation’ success; AR-RARP NVB overlay is experimental.",
        "Adrenal / RPLND: vascular maps in re-operative fields.",
      ]},
      { t: "h", v: "Intra-operative fluorescence (navigation adjunct)" },
      { t: "ul", v: [
        "ICG–NIR (Firefly, IMAGE1 S): arterial phase seconds, parenchymal perfusion, hypofluorescent tumour in many clear-cell RCCs, bowel/conduit ischaemia, chyle leak mapping, sentinel node (penile, prostate research).",
        "5-ALA / hexaminolevulinate: photodynamic diagnosis of NMIBC — not AR but ‘optical navigation’.",
        "Limits of fluorescence: timing, dose (2.5–7.5 mg ICG typical), bile/urine excretion, not a substitute for oncologic margin.",
      ]},
      { t: "tip", k: "gold", v: "Navigation is only as good as registration. If the kidney is rotated, the pretty overlay is a lie — confirm with US and anatomy." },
    ],
  },
];
