import type { Master } from "../types";

export const lasers: Master[] = [
  {
    id: "laser-principles",
    topicId: "lasers",
    title: "Laser principles, urologic types and complications",
    highYield: true,
    gold: true,
    tags: ["laser", "Ho:YAG", "Tm:YAG", "KTP", "physics"],
    exams: [
      { session: "June", year: 2022, marks: "4+3+3", stem: "Discuss the basic principles of laser. Describe the various lasers that are used in urological practice. Discuss the various complications of different types of lasers." },
    ],
    related: ["pulsed-cw-thulium", "lasers-bph", "greenlight", "soft-tissue-lasers"],
    references: [
      "Campbell-Walsh-Wein 12e, Surgical Foundations / Energy sources",
      "Smith's Textbook of Endourology, 4e — Lasers",
      "EAU Urolithiasis and Non-neurogenic Male LUTS guidelines",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map (10 marks)", v: "Physics 4 (stimulated emission, cavity, wavelength–chromophore, pulsed vs CW) · Named lasers with λ and use 3 · Complications by laser 3. Draw the absorption curves of water vs haemoglobin." },
      { t: "h", v: "Definition and physics" },
      { t: "p", v: "LASER = Light Amplification by Stimulated Emission of Radiation. A photon interacting with an excited electron stimulates emission of a second photon identical in wavelength, phase and direction (Einstein 1917). A gain medium between two mirrors (optical resonator) plus a pump source produces a collimated, coherent, monochromatic beam." },
      { t: "ul", v: [
        "Four properties: monochromaticity, coherence (temporal + spatial), collimation, high irradiance.",
        "Active media: solid-state crystal (Ho:YAG, Tm:YAG, Nd:YAG, KTP), fibre (thulium fibre laser, TFL), semiconductor (diode), gas (CO2).",
        "Pump: flashlamp or diode. Output characterised by wavelength (nm), pulse energy (J), pulse duration (µs–ms), frequency (Hz), peak and average power (W), fluence (J/cm²), fibre core (µm).",
        "Tissue interaction depends on optical absorption of the chromophore (water 1.9–2.1 µm; haemoglobin 532 nm; melanin) plus scatter. Thermal relaxation time of the target dictates pulse width.",
      ]},
      { t: "h", v: "Four interaction regimes (write this table)" },
      { t: "tbl", h: ["Regime", "Pulse / power", "Effect", "Urologic example"], r: [
        ["Photothermal", "CW or long pulse", "Vaporisation, coagulation, incision", "GreenLight PVP, Tm:YAG vapoenucleation, CO2"],
        ["Photomechanical / photothermal (short pulse)", "µs pulsed high peak power", "Cavitation bubble, retropulsion, fragmentation", "Ho:YAG lithotripsy, TFL"],
        ["Photochemical", "Low power, specific λ", "ROS after photosensitiser", "PDT (ALA, Tookad) — limited GU use"],
        ["Photodisruption", "fs–ns, plasma", "Optical breakdown", "Not used in routine GU"],
      ]},
      { t: "h", v: "Lasers in urologic practice" },
      { t: "tbl", c: "Wavelength, chromophore and role", h: ["Laser", "λ (nm)", "Mode", "Chromophore", "Principal uses"], r: [
        ["Ho:YAG", "2100–2140", "Pulsed (250–350 µs)", "Water", "Lithotripsy, HoLEP, incision of stricture/PUJO, ablation of tumours"],
        ["Tm:YAG", "2013", "CW (or pulsed)", "Water", "ThuVEP / ThuLEP, bladder tumour, stricture"],
        ["TFL (Tm fibre)", "1940 / 1908", "Quasi-CW / pulsed", "Water (4× Ho absorption)", "Dusting lithotripsy, emerging BPH"],
        ["KTP / LBO (GreenLight)", "532", "Quasi-CW, Q-switched", "Hb (oxyhaemoglobin)", "PVP of prostate (80/120/180 W XPS)"],
        ["Nd:YAG", "1064", "CW / pulsed", "Nonspecific (deep scatter)", "Historical prostate/tumour coag; still as KTP parent"],
        ["Diode 980 / 1470", "980, 1470", "CW", "Hb + water", "DiLEP, interstitial, circumcision in some units"],
        ["CO2", "10600", "CW / pulsed", "Water (very high)", "Penile / glans lesions, condyloma; poor fibre transmission (need articulated arm / hollow fibre)"],
        ["Ho:YAG + Moses / pulse modulation", "2100", "Modulated pulse", "Water", "Reduced retropulsion, contact lithotripsy"],
      ]},
      { t: "h", v: "Complications — by laser, not a dump list" },
      { t: "tbl", h: ["Laser / setting", "Specific hazards", "Prevention"], r: [
        ["Ho:YAG lithotripsy", "Ureteric perforation, submucosal stone, stricture, steinstrasse, sepsis, fibre fracture / broken fibre in kidney", "Safety wire, access sheath, low pressure, inspect fibre, exit stent if trauma"],
        ["HoLEP / ThuLEP", "Capsular perforation, transient incontinence (10–20% early), urethral stricture / BNC, bladder injury during morcellation, delayed bleed", "Morcellate in bladder with good distension; 26–28 F scope; energy discipline at apex"],
        ["GreenLight PVP", "Dysuria / storage symptoms, delayed haemorrhage (slough, days 7–14), capsule perforation, ureteric orifice injury, conversion if large gland / anticoagulated poorly selected", "MoXy fibre distance 0.5–1 mm; avoid overtreatment of bladder neck"],
        ["Nd:YAG (historical)", "Deep coagulative necrosis, delayed slough, fistula", "Largely abandoned for prostate"],
        ["CO2 / surface", "Airway fire if open O2, hypertrophic scar", "Wet field, smoke evacuation"],
        ["All", "Eye injury (wavelength-specific goggles), drape fire, plume (HPV/viral), fibre-tip ignition of gas in bladder (H2/air — never use air irrigation)", "Laser safety officer, wavelength-matched eyewear, saline irrigation only"],
      ]},
      { t: "tip", k: "warn", title: "Laser safety (always write 3 lines)", v: "Nominal ocular hazard distance, window covers, dedicated keys, wet drapes, smoke evacuator. Holmium/thulium: water-absorption goggles (OD appropriate at 2 µm). GreenLight: orange 532 nm goggles — NOT interchangeable." },
      { t: "tip", k: "gold", title: "Gold line", v: "Match wavelength to chromophore: 2 µm water lasers cut/fragment in a bloodless aqueous field; 532 nm needs haemoglobin so it vaporises vascular prostate and is relatively ‘blind’ in a pale/fibrotic gland." },
    ],
  },
  {
    id: "pulsed-cw-thulium",
    topicId: "lasers",
    title: "Pulsed vs continuous-wave lasers and Thulium:YAG",
    highYield: true,
    gold: false,
    tags: ["Tm:YAG", "TFL", "pulsed", "CW", "ThuLEP"],
    exams: [
      { session: "Dec", year: 2020, marks: "3+4+3", stem: "What are the differences between pulsed and continuous wave lasers? What are the types of lasers used in Urology? Describe Thulium:YAG laser in detail." },
    ],
    related: ["laser-principles", "lasers-bph", "soft-tissue-lasers"],
    references: [
      "Smith's Endourology — Laser–tissue interaction",
      "Bach T et al. Thulium:YAG vapoenucleation — Eur Urol / World J Urol reviews",
      "Campbell-Walsh-Wein 12e, BPH surgical therapy",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Part a table 3 · Named lasers 4 · Tm:YAG physics + ThuVEP/ThuLEP technique + vs HoLEP 3." },
      { t: "h", v: "Pulsed versus continuous-wave" },
      { t: "tbl", h: ["Feature", "Pulsed", "Continuous-wave (CW)"], r: [
        ["Emission", "Discrete packets; peak power ≫ average power", "Uninterrupted beam; peak = average power"],
        ["Typical peak power", "kW range (Ho:YAG 2–10 kW)", "Tens to a few hundred W"],
        ["Dominant tissue effect", "Photomechanical cavitation + local photothermal (lithotripsy); precise if pulse < thermal relaxation time", "Pure photothermal vaporisation / coagulation / cutting"],
        ["Thermal damage zone", "Narrow if short pulse (Ho ~0.4 mm)", "Broader coagulative rim (Tm:YAG 0.2–2 mm depending on technique)"],
        ["Haemostasis", "Modest (Ho) unless long-pulse / coag setting", "Excellent (Tm, diode, GreenLight quasi-CW)"],
        ["Stone use", "Yes — bubble collapse fragments stone", "No efficient lithotripsy (TFL is quasi-CW but pulsed at high frequency for dusting)"],
        ["Examples", "Ho:YAG, pulsed dye (historical), TFL in pulsed mode, KTP Q-switched train", "Tm:YAG 2013 nm, diode, CO2, Nd:YAG"],
      ]},
      { t: "p", v: "GreenLight is technically a high-repetition Q-switched KTP/LBO train that behaves as quasi-continuous photothermal vaporisation — classify it with CW-like soft-tissue lasers, not as a lithotripter." },
      { t: "h", v: "Types used in urology (list with one use each)" },
      { t: "ul", v: [
        "Ho:YAG 2100 nm pulsed — stones, HoLEP, incision.",
        "Tm:YAG 2013 nm CW — prostate vapoenucleation, bladder tumours, strictures.",
        "Thulium fibre laser 1940 nm — super-pulse dusting; BPH emerging.",
        "KTP/LBO 532 nm — PVP.",
        "Diode 980/1470 — DiLEP / interstitial.",
        "Nd:YAG 1064 — historical deep coag; still the pump for KTP.",
        "CO2 10.6 µm — external genitalia, glans resurfacing.",
        "Holmium with pulse modulation (Moses, Virtual Basket) — contact lithotripsy.",
      ]},
      { t: "h", v: "Thulium:YAG in detail" },
      { t: "p", v: "Tm:YAG is a continuous-wave solid-state laser at 2013 nm. Absorption coefficient in water is ~4-fold higher than Ho:YAG → optical penetration ~0.25 mm vs ~0.4 mm. Energy is delivered through 200–800 µm silica fibres. Because output is CW, the surgeon controls effect by moving speed and standoff: slow contact = incision/enucleation plane; near-contact painting = vaporisation; defocused = coagulation." },
      { t: "ul", v: [
        "Generators: 70–200 W (RevoLix, Cyber TM). 2 µm fibre compatible with flexible URS and resectoscope laser bridges.",
        "ThuVEP (vapoenucleation): blunt/energy dissection of adenoma in the plane, vaporising the face of the lobe; morcellation of remaining tissue.",
        "ThuLEP: true enucleation analogous to HoLEP, using the beak + energy to find the capsule.",
        "ThuVARP / vaporesection: resectoscope-like chips, no morcellator — useful if morcellator unavailable, slower for large glands.",
        "Soft tissue besides prostate: NMIBC en bloc, urethral/ureteric stricture incision, PUJO endopyelotomy, condyloma (less ideal than CO2).",
        "Haemostasis superior to holmium → attractive on anticoagulants (still hold antiplatelets if possible).",
        "No lithotripsy capability (unlike Ho:YAG / TFL) — a genuine limitation if stones coexist.",
      ]},
      { t: "tbl", c: "Tm:YAG vs Ho:YAG for BPH", h: ["", "Tm:YAG CW", "Ho:YAG pulsed"], r: [
        ["Plane finding", "Vaporizes capsule risk if inexperienced", "Mechanical enucleation more tactile"],
        ["Bleed", "Less", "More at perforators — coagulate separately"],
        ["Morcellation", "Yes (ThuVEP/ThuLEP)", "Yes"],
        ["Tissue for histology", "Yes if enucleated", "Yes"],
        ["Learning curve", "Shorter for vaporesection", "Steeper for HoLEP"],
        ["RCT signal", "Similar Qmax/IPSS; maybe less Hb drop", "Gilling/Gilling-equivalent long-term durability gold standard"],
      ]},
      { t: "tip", k: "gold", v: "Do not confuse Tm:YAG (2013 nm CW crystal) with TFL (1940 nm fibre, super-pulse). Examiners treat TFL as a stone laser first; Tm:YAG as a prostate/soft-tissue laser." },
    ],
  },
  {
    id: "lasers-bph",
    topicId: "lasers",
    title: "Lasers for BPH — comparative prostatectomy",
    highYield: true,
    gold: true,
    tags: ["BPH", "HoLEP", "ThuLEP", "PVP", "GreenLight"],
    exams: [
      { session: "Dec", year: 2015, marks: "10", stem: "Different types of LASER used in the management of benign prostatic hyperplasia." },
      { session: "Dec", year: 2014, marks: "10", stem: "Make a comparative study of different LASERs used for prostatectomy." },
    ],
    related: ["greenlight", "laser-principles", "pulsed-cw-thulium", "soft-tissue-lasers"],
    references: [
      "EAU Male LUTS / AUA BPH guideline",
      "Gilling P — HoLEP long-term series; Goliath trial (GreenLight XPS vs TURP)",
      "Campbell-Walsh-Wein 12e, Minimally invasive and laser BPH",
      "Smith's Endourology",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "Classify by action (enucleate / vaporise / resect) not by brand. Table of λ, gland size, anticoagulants, tissue for histology, reoperation. Quote GOLIATH, HoLEP vs TURP meta-analysis." },
      { t: "h", v: "Classification by surgical principle" },
      { t: "tbl", h: ["Principle", "Lasers", "What is removed"], r: [
        ["Enucleation (anatomical)", "HoLEP, ThuLEP, DiLEP (diode enucleation)", "Entire transition-zone adenoma; morcellated"],
        ["Vaporisation", "GreenLight PVP (KTP/LBO), diode vaporisation, Tm vaporisation", "Adenoma turned to vapour; little tissue"],
        ["Vaporesection / vapoenucleation", "ThuVARP, ThuVEP", "Hybrid chips or enucleated+vaporised face"],
        ["Coagulation / interstitial (historical)", "ILC Nd:YAG, VLAP", "Slough over weeks — obsolete"],
      ]},
      { t: "h", v: "Comparative table (write this in the paper)" },
      { t: "tbl", c: "Laser prostatectomy comparison", h: ["", "HoLEP", "Tm:YAG (ThuLEP/VEP)", "GreenLight XPS 180 W", "Diode 980/1470"], r: [
        ["λ / mode", "2140 nm pulsed", "2013 nm CW", "532 nm quasi-CW", "980/1470 CW"],
        ["Chromophore", "Water", "Water", "Hb", "Hb + water"],
        ["Ideal gland", "Any size; gold for >80–100 g", "Any size", "30–80 g; XPS can do larger", "Moderate"],
        ["Anticoagulation", "Safer than TURP; still pause if possible", "Excellent haemostasis", "Designed for anticoagulated", "Good haemostasis; deep char risk"],
        ["Histology", "Yes", "Yes if enucleated", "No (vaporised)", "No / limited"],
        ["Catheter time", "1–2 d", "1–2 d", "Day-case possible", "Short"],
        ["Reoperation / durability", "Lowest (TURP-equivalent at 10 y)", "Similar mid-term", "Higher retreatment if incomplete vaporisation of large gland", "Variable; deep necrosis → slough/stricture"],
        ["Specific Cx", "Morcellator bladder injury, early SUI", "Capsule vaporisation", "Storage LUTS, delayed bleed d7–14", "Necrotic slough, sphincter injury if 980 deep"],
        ["Capital + fibre cost", "High generator; reusable fibres", "High", "High; single-use MoXy", "Lower generator"],
      ]},
      { t: "h", v: "Evidence the examiner expects" },
      { t: "ul", v: [
        "HoLEP vs TURP/open: equivalent IPSS/Qmax, less blood, shorter catheter/stay, more early incontinence that largely resolves; durable to 10–18 y (Gilling). EAU: alternative to TURP independent of size.",
        "GOLIATH (non-inferiority RCT): GreenLight XPS vs TURP — non-inferior IPSS at 6–24 months; shorter catheterisation; more storage symptoms; retreatment slightly higher.",
        "Tm:YAG vs TURP/HoLEP: similar functional outcomes; less haemoglobin drop in several series.",
        "Size rule of thumb: vaporisation inefficient and incomplete >80–100 g → enucleation. Vaporisation preferred if small–moderate gland + anticoagulation + no need for histology (PSA worked up).",
        "Tissue diagnosis: if prostate cancer not excluded, prefer enucleation/TURP over pure PVP.",
      ]},
      { t: "h", v: "Complications common to all laser prostatectomy" },
      { t: "ul", v: ["Urethral stricture / bladder-neck contracture (large sheaths, energy at neck)", "Transient stress incontinence (sphincter stretch / energy at veru)", "Need for secondary morcellation / residual adenoma", "Sepsis, TUR-like absorption if perforation (saline — no glycine syndrome but volume overload)", "Retrograde ejaculation (almost universal after enucleation; less after bladder-neck-sparing PVP)"] },
      { t: "flow", title: "Choosing a laser for BPH", nodes: [
        { id: "a", kind: "start", label: "BPH surgery indicated (AUA/EAU after failed medical Rx)", to: ["b"] },
        { id: "b", kind: "decision", label: "Gland >80–100 g or obstruction + stones / diverticulum?", to: ["c", "d"] },
        { id: "c", kind: "action", label: "Enucleation: HoLEP or ThuLEP (± open/lap/robot simple prostatectomy)", to: ["e"] },
        { id: "d", kind: "decision", label: "On anticoagulation / need day-case / small–moderate gland?", to: ["f", "g"] },
        { id: "f", kind: "action", label: "GreenLight XPS PVP (or bipolar TURP)", to: ["e"] },
        { id: "g", kind: "action", label: "Bipolar TURP or HoLEP/ThuLEP if histology wanted", to: ["e"] },
        { id: "e", kind: "end", label: "Counsel retrograde ejaculation, SUI risk, cancer still possible in remnant" },
      ]},
      { t: "tip", k: "gold", v: "‘Enucleation is size-independent TURP; vaporisation is a haemostatic TURP for the moderate gland. Do not vaporise a 150 g prostate and call it modern.’" },
    ],
  },
  {
    id: "greenlight",
    topicId: "lasers",
    title: "GreenLight (KTP/LBO) laser and BPH",
    highYield: true,
    gold: false,
    tags: ["GreenLight", "KTP", "PVP", "532", "BPH"],
    exams: [
      { session: "Dec", year: 2011, marks: "5+5", stem: "What is a ‘Green Light’ Laser? What is its mode of action on BPH?" },
    ],
    related: ["lasers-bph", "laser-principles", "soft-tissue-lasers"],
    references: [
      "Campbell-Walsh-Wein 12e, Photoselective vaporisation",
      "GOLIATH trial — Eur Urol 2015/2016",
      "Smith's Endourology; AUA BPH guideline",
    ],
    answer: [
      { t: "h", v: "What is GreenLight?" },
      { t: "p", v: "GreenLight is a frequency-doubled Nd:YAG laser. Passing 1064 nm light through a potassium titanyl phosphate (KTP) or lithium triborate (LBO) crystal halves the wavelength to 532 nm, which is in the green visible band. Contemporary platform: GreenLight XPS 180 W with the MoXy liquid-cooled 750 µm side-firing fibre (earlier: 80 W KTP, 120 W HPS)." },
      { t: "ul", v: [
        "Quasi-continuous high-repetition Q-switched pulse train — behaves as photothermal vaporisation, not lithotripsy.",
        "Chromophore: oxyhaemoglobin (peak absorption near 532 nm). Optical penetration in vascular prostate ~0.8 mm; coagulation rim ~1–2 mm — hence ‘photoselective’ (selects blood-rich adenoma, relatively spares poorly vascular capsule/neurovascular bundles if energy is disciplined).",
        "Side-fire fibre at 70°; working distance 0.5–1 mm. Contact causes fibre degradation and carbonisation.",
      ]},
      { t: "h", v: "Mode of action on BPH" },
      { t: "ul", n: true, v: [
        "Photothermal vaporisation: intracellular water boils → steam bubbles explode cells → tissue instantly converted to vapour and small bubbles (no chips).",
        "Simultaneous coagulation of feeding vessels in the 1–2 mm rim → intraoperative haemostasis even on antiplatelet agents.",
        "Creates a TUR-like cavity by painting the lateral lobes, floor and median lobe systematically (Malek / ISON technique: bladder neck → lateral lobes → apical tissue last, respecting veru).",
        "Slough of coagulated residual tissue over 1–4 weeks explains delayed haematuria and prolonged storage symptoms.",
        "No specimen: preoperative PSA, DRE, and imaging/biopsy pathway must already have addressed cancer risk.",
      ]},
      { t: "h", v: "Technique pearls" },
      { t: "ul", v: [
        "Room-temperature saline; 23–26 F continuous-flow cystoscope; 30° lens.",
        "MoXy fibre: keep red aiming beam moving; if fibre cap overheats, pause. XPS TruCoag setting for bleeders.",
        "Endpoint: unobstructed view of bladder from veru, glistening capsule fibres, triangular cavity.",
        "Catheter 12–24 h typical; alpha-blocker may be continued briefly for storage LUTS.",
      ]},
      { t: "h", v: "Outcomes and limitations" },
      { t: "ul", v: [
        "IPSS and Qmax improve in the TURP range for glands 30–80 mL (GOLIATH non-inferior).",
        "Advantages: saline, less TUR syndrome, catheter-free early, usable on anticoagulation (still risk delayed bleed), day-case.",
        "Limitations: inefficient in very large glands; fibrotic / post-TUR / post-radiation pale glands absorb poorly; capsular perforation if energy parked; ureteric orifice injury with large median lobe; cost of single-use fibre; no histology; retreatment 5–15% at 5 y if under-vaporised.",
      ]},
      { t: "tip", k: "gold", v: "GreenLight is haemoglobin-seeking vaporisation, not enucleation. If the gland is pale, huge, or you need tissue, it is the wrong energy." },
    ],
  },
  {
    id: "soft-tissue-lasers",
    topicId: "lasers",
    title: "Soft-tissue lasers in urology — pros and cons",
    highYield: true,
    gold: false,
    tags: ["soft tissue", "Ho:YAG", "Tm:YAG", "CO2", "Nd:YAG", "diode"],
    exams: [
      { session: "Dec", year: 2016, marks: "2+8", stem: "What are the Lasers available for soft tissue application in urology? Their pros and cons." },
    ],
    related: ["laser-principles", "lasers-bph", "greenlight", "pulsed-cw-thulium"],
    references: [
      "Smith's Textbook of Endourology",
      "Campbell-Walsh-Wein 12e",
      "EAU NMIBC / Urethral strictures / Penile cancer chapters",
    ],
    answer: [
      { t: "p", v: "Soft-tissue GU applications: prostate, bladder tumour (en bloc), urethral/ureteric stricture and PUJO incision, endopyelotomy, PUVs historically, penile intra-epithelial neoplasia / glans resurfacing, condyloma, partial nephrectomy cut surface (rare), incision of ureterocoele. Stones are NOT ‘soft tissue’ — mention Ho/TFL only for their dual-use advantage." },
      { t: "tbl", c: "Soft-tissue lasers — trade-offs", h: ["Laser", "Pros", "Cons"], r: [
        ["Ho:YAG 2140 nm pulsed", "One platform for stones + soft tissue; precise incision in water; fibre through flexible URS; HoLEP evidence base", "Less haemostasis than CW 2 µm; vibration/retropulsion; fibre wear; morcellator needed for prostate"],
        ["Tm:YAG 2013 nm CW", "Smooth cut, excellent coag, vapour-enucleation, thin fibres, less projectile tissue", "No lithotripsy; can vaporise through capsule; less long-term RCT than HoLEP"],
        ["KTP/LBO 532 nm", "Haemostatic PVP on anticoagulants; day-case", "Needs vascular tissue; no histology; delayed slough; single-use fibre cost"],
        ["Nd:YAG 1064 nm", "Deep coag, haemostasis, historical VLAP/ILC", "Unpredictable depth, delayed fistula/slough — largely abandoned for endoscopic prostate"],
        ["Diode 980 / 1470 nm", "Cheap, portable, good coag, DiLEP series", "980 nm deep penetration → sphincter/necrosis risk; histology lost if vaporising; weaker evidence"],
        ["CO2 10.6 µm", "Exquisite superficial cut, char-free at pulsed superpulse; gold for glans/skin/PIN", "No standard wet-endoscopic fibre (articulated arm); airway fire; not for stones or BPH"],
        ["TFL 1940 nm", "Fine dusting + emerging soft-tissue cut; small fibres", "BPH evidence still maturing; generator cost"],
      ]},
      { t: "h", v: "Match laser to job" },
      { t: "ul", v: [
        "Bladder tumour en bloc: Ho or Tm — staged specimen, lower seeding theoretically; avoid if CIS (use resection + enhanced cystoscopy).",
        "Stricture / VIU / endopyelotomy: Ho at 1 J × 10 Hz contact; cold knife remains an option; laser does not improve long-term vs knife for short bulbar strictures (EAU).",
        "Penile CIS / PeIN: CO2 resurfacing or glans resurfacing with skin graft — oncologic follow-up mandatory.",
        "Condyloma: CO2 or Nd:YAG; treat urethra with care (stricture).",
        "Prostate: see lasers-bph master — do not use Nd:YAG VLAP in a 2020s answer.",
      ]},
      { t: "tip", k: "book", v: "Smith: absorption length determines precision; coagulation depth determines haemostasis and collateral damage. You cannot maximise both with one wavelength." },
    ],
  },
  {
    id: "holep-technique",
    topicId: "lasers",
    title: "HoLEP — technique, outcomes and complications",
    highYield: true,
    gold: false,
    tags: ["HoLEP", "enucleation", "morcellation", "BPH"],
    exams: [
      { session: "Dec", year: 2015, marks: "10", stem: "Different types of LASER used in the management of benign prostatic hyperplasia." },
      { session: "Dec", year: 2014, marks: "10", stem: "Make a comparative study of different LASERs used for prostatectomy." },
    ],
    related: ["lasers-bph", "laser-principles", "pulsed-cw-thulium"],
    references: [
      "Gilling PJ. HoLEP technique and long-term results",
      "EAU Male LUTS guideline",
      "Campbell-Walsh-Wein 12e",
    ],
    answer: [
      { t: "p", v: "Holmium laser enucleation of the prostate (Gilling) uses the 2140 nm pulsed Ho:YAG as a precise ‘hot knife’ to enter the surgical capsule plane, detach the transition-zone adenoma in 1–3 lobes, push lobes into the bladder and morcellate. It is the laser procedure with the strongest durability data and is size-independent." },
      { t: "h", v: "Equipment and energy" },
      { t: "ul", v: [
        "100 W class holmium (or high-power 120–150 W); 550 µm end-firing fibre; 26–28 F continuous-flow laser resectoscope; offset nephroscope + morcellator (Piranha, VersaCut).",
        "Enucleation settings typically 2 J × 50 Hz (100 W) or 1.5–2 J × 30–40 Hz; coagulate bleeders at lower energy / longer pulse if available.",
        "Saline irrigation; two inflows during morcellation.",
      ]},
      { t: "h", v: "Steps (3-lobe as the classic answer)" },
      { t: "ul", n: true, v: [
        "Bilateral bladder-neck grooves at 5 and 7 o’clock to veru, joining distally anterior to veru — isolate median lobe.",
        "Retrograde enucleation of median lobe off capsule into bladder; coagulate perforators.",
        "Lateral lobe: anterior commissure incision 12 o’clock down to capsule; circumferential release; apical mucosal strip at sphincter last.",
        "Inspect fossa; three-lobe vs en-bloc / two-lobe modifications (Scoffone en-bloc, early apical release) — name one.",
        "Morcellate with bladder full, oscillating morcellator under vision; never bite unseen mucosa.",
        "Catheter 12–24 h; trial of void next day. Send all morcellated tissue.",
      ]},
      { t: "kpi", items: [
        { k: "Qmax gain", v: "+15–20 mL/s typical" },
        { k: "PSA drop", v: "~80% (surrogate of completeness)" },
        { k: "Transfusion", v: "<1–2%" },
        { k: "Early SUI", v: "10–20%, <1–3% persistent" },
        { k: "Retreatment 10 y", v: "<5%" },
      ]},
      { t: "h", v: "Complications to list" },
      { t: "ul", v: ["Morcellator injury (bladder) — the feared intraoperative event", "Capsular perforation and fluid absorption", "Urethral stricture / BNC", "Transient SUI — counsel, pelvic floor, usually resolved by 3 months", "Ureteric orifice injury if large median lobe", "Incomplete morcellation → second look"] },
      { t: "tip", k: "exam", v: "If the stem is ‘comparative lasers for prostatectomy’, HoLEP is the reference standard against which PVP and Tm techniques are judged." },
    ],
  },
  {
    id: "laser-lithotripsy",
    topicId: "lasers",
    title: "Holmium and thulium-fibre lithotripsy",
    highYield: true,
    gold: false,
    tags: ["Ho:YAG", "TFL", "dusting", "popcorning", "Moses"],
    exams: [
      { session: "June", year: 2022, marks: "4+3+3", stem: "Discuss the basic principles of laser. Describe the various lasers that are used in urological practice. Discuss the various complications of different types of lasers." },
      { session: "Dec", year: 2020, marks: "3+4+3", stem: "What are the differences between pulsed and continuous wave lasers? What are the types of lasers used in Urology? Describe Thulium:YAG laser in detail." },
    ],
    related: ["laser-principles", "pulsed-cw-thulium", "furs-single-use-sepsis"],
    references: [
      "Smith's Endourology — Intracorporeal lithotripsy",
      "EAU Urolithiasis guideline",
      "Traxer O, Keller EX — TFL reviews",
    ],
    answer: [
      { t: "p", v: "Ho:YAG remains the gold-standard intracorporeal lithotripter. Super-pulse TFL is the principal challenger. Fragmentation is photothermal (vapour channel into stone) plus photomechanical (cavitation bubble collapse). Pulse energy, frequency, pulse width and fibre size determine dust vs fragment." },
      { t: "tbl", h: ["Strategy", "Typical Ho settings", "Use"], r: [
        ["Dusting", "0.2–0.5 J × 20–80 Hz, long pulse", "Long operative time, fewer baskets, residual dust"],
        ["Fragmentation / basketing", "0.8–1.2 J × 8–15 Hz, short pulse", "Hard stones, retrieve pieces"],
        ["Popcorning / pop-dusting", "0.5 J × 40–80 Hz, fibre hovering in calyx", "Clear fragments in a dependent calyx"],
        ["Contact (Moses / modulation)", "0.4–0.8 J modulated", "Less retropulsion, energy delivered through vapour bubble"],
      ]},
      { t: "ul", v: [
        "TFL 1940 nm: higher water absorption, smaller fibres (50–150 µm) preserve deflection, very high frequency (up to 2000 Hz) → fine dust, less retropulsion; watch heat at high power in a low-flow ureter.",
        "Heat: maintain irrigation; access sheath reduces intrarenal pressure and temperature. Sepsis is a pressure/time problem as much as a laser problem.",
        "Fibre: strip and cleave; 200–272 µm flexible; 365–550 µm semi-rigid. Never fire without aiming at stone — perforation in <1 s at contact on mucosa.",
      ]},
      { t: "tip", k: "warn", v: "High-power dusting without a sheath in an infected system is a sepsis setup. Culture, decompress, low pressure, exit stent." },
    ],
  },
];
