import type { Master } from "../types";

export const nephrology: Master[] = [
  {
    id: "endocrine-kidney-osteodystrophy",
    topicId: "nephrology",
    title: "Endocrine kidney and renal osteodystrophy",
    highYield: true,
    gold: true,
    tags: ["CKD-MBD", "PTH", "vitamin D", "FGF23", "osteodystrophy"],
    exams: [
      { session: "Dec", year: 2016, marks: "5+5", stem: "Endocrine functions of kidney. Pathogenesis of renal osteodystrophy." },
      { session: "Dec", year: 2013, marks: "4+3+3", stem: "Describe the mechanism of renal osteodystrophy in Chronic Kidney Disease (CKD) and its treatment and prophylaxis." },
      { session: "Jun", year: 2020, marks: "5+5", stem: "Pathogenesis of bony changes in patients with chronic kidney disease. Methods to reduce/reverse these changes." },
    ],
    related: ["ckd-classification-anaemia", "hyperparathyroidism-stones", "bisphosphonates"],
    references: [
      "Campbell-Walsh-Wein — Renal Physiology / CKD",
      "KDIGO CKD-MBD 2017 update",
      "Brenner & Rector's The Kidney",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "Endocrine list with hormone/site/action 5 · CKD-MBD cascade (PO4–FGF23–1,25D–PTH–bone) 3 · Histologic types 1 · Treatment/prophylaxis 2. Draw the cascade." },
      { t: "h", v: "Endocrine functions of the kidney" },
      { t: "tbl", h: ["Hormone / product", "Site", "Stimulus", "Action"], r: [
        ["1,25-dihydroxyvitamin D (calcitriol)", "Proximal tubule 1α-hydroxylase (CYP27B1)", "PTH ↑, hypophosphataemia, low FGF23", "GI Ca/PO4 absorption, bone mineralisation, PTH suppression"],
        ["Erythropoietin", "Peritubular interstitial fibroblasts (cortical)", "Hypoxia (HIF-2α)", "CFU-E survival; deficiency = normocytic anaemia of CKD"],
        ["Renin", "JG apparatus (afferent arteriolar granular cells)", "Low afferent pressure, low NaCl at macula densa, sympathetic β1", "RAAS → angiotensin II, aldosterone; BP and Na"],
        ["Klotho / FGF23 axis", "Distal tubule klotho is co-receptor for bone FGF23", "Phosphate load", "Phosphaturia, 1α-hydroxylase suppression"],
        ["Prostaglandins (PGE2, PGI2)", "Medullary interstitium, glomerulus", "Ang II, bradykinin, NSAID-sensitive COX", "Afferent dilatation, renin release, medullary blood flow"],
        ["Kallikrein–kinin", "Connecting tubule", "Aldosterone", "Natriuresis, renin modulation"],
        ["Urodilatin (local ANP analogue)", "Distal nephron", "Volume", "Natriuresis"],
        ["Thrombopoietin (minor)", "Proximal tubule", "—", "Platelet lineage (liver dominates)"],
      ]},
      { t: "p", v: "The kidney is also the clearance organ for insulin, PTH fragments, gastrin and β2-microglobulin (dialysis amyloid). Catabolism of these peptides fails in CKD." },
      { t: "h", v: "Pathogenesis of renal osteodystrophy (CKD-MBD)" },
      { t: "p", v: "KDIGO term is Chronic Kidney Disease–Mineral and Bone Disorder: lab abnormalities (Ca, PO4, PTH, FGF23, vitamin D) + bone disease + extra-skeletal calcification. Osteodystrophy is the bone component." },
      { t: "flow", title: "CKD-MBD cascade", nodes: [
        { id: "a", kind: "start", label: "Falling GFR → phosphate retention", to: ["b"] },
        { id: "b", kind: "action", label: "Osteocyte FGF23 rises (earliest marker)", to: ["c"] },
        { id: "c", kind: "action", label: "FGF23 suppresses 1α-hydroxylase → calcitriol falls", to: ["d"] },
        { id: "d", kind: "action", label: "Low calcitriol + high PO4 + low Ca → parathyroid hyperplasia, PTH ↑", to: ["e"] },
        { id: "e", kind: "action", label: "Secondary (then tertiary) hyperparathyroidism", to: ["f"] },
        { id: "f", kind: "end", label: "High-turnover osteitis fibrosa OR adynamic bone if over-suppressed; vascular calcification" },
      ]},
      { t: "ul", v: [
        "Phosphate retention is the initiating event, not hypocalcaemia (the old trade-off hypothesis is incomplete).",
        "FGF23: phosphaturic, but also directly suppresses 1α-hydroxylase and is independently associated with LVH and mortality.",
        "Calcitriol deficiency: ↓ gut Ca absorption, loss of genomic PTH suppression, immune and muscle effects.",
        "PTH: high-turnover bone — increased osteoclast/osteoblast, marrow fibrosis (osteitis fibrosa cystica, brown tumours, salt-and-pepper skull).",
        "Over-treatment with calcium binders / calcitriol / over-dialysis of calcium → adynamic bone disease (low PTH, low alkaline phosphatase, fractures + extra-skeletal calcification because bone cannot buffer Ca).",
        "Osteomalacia: aluminium (historical dialysate) or severe vitamin D deficiency — unmineralised osteoid.",
        "Mixed uraemic osteodystrophy: high turnover + mineralisation defect.",
        "β2-microglobulin amyloid (dialysis-related): carpal tunnel, cystic bone lesions, not strictly MBD but quoted in long-term dialysis patients.",
      ]},
      { t: "tbl", c: "Histologic types (TMV classification: turnover, mineralisation, volume)", h: ["Type", "PTH", "Turnover", "Clinical"], r: [
        ["Osteitis fibrosa", "Very high", "High", "Pain, brown tumour, high ALP"],
        ["Adynamic", "Low (<100–150)", "Low", "Fracture, vascular calcification"],
        ["Osteomalacia", "Variable", "Low, unmineralised", "Looser zones, aluminium history"],
        ["Mixed", "High", "High + defect", "Common on bone biopsy"],
        ["Osteoporosis overlay", "Any", "Low volume", "Age, steroids, heparin, acidosis"],
      ]},
      { t: "h", v: "Treatment and prophylaxis" },
      { t: "ul", v: [
        "KDIGO: treat the axis, not a single number. Targets are trend-based; classic exam numbers: keep PO4 towards normal, Ca normal, PTH 2–9× upper limit in dialysis (not ‘normal’).",
        "Dietary phosphate restriction (800–1000 mg/d) + adequate protein. Avoid processed foods (inorganic phosphate additives).",
        "Phosphate binders with meals: calcium acetate/carbonate (limit elemental Ca <1.5 g/d — vascular calcification); non-calcium: sevelamer, lanthanum, sucroferric oxyhydroxide, ferric citrate (also treats iron deficiency).",
        "Vitamin D: replete 25-OH D (cholecalciferol). Active vitamin D analogues (calcitriol, alfacalcidol, paricalcitol) if PTH remains high — watch Ca/PO4 product.",
        "Calcimimetics (cinacalcet, etelcalcetide): allosteric CaSR agonists — lower PTH, Ca, PO4; useful before considering parathyroidectomy.",
        "Parathyroidectomy (subtotal or total + autotransplant) for refractory tertiary HPT: persistent PTH with hypercalcaemia, calciphylaxis, progressive extra-skeletal calcification, bone pain/fracture.",
        "Dialysis: adequate dose; avoid chronic positive calcium balance. Cinacalcet/etelcalcetide on HD.",
        "Acidosis correction (bicarbonate) improves bone buffering. Avoid aluminium binders. Bisphosphonates only if adynamic bone excluded (they worsen it).",
        "Transplant is the definitive reversal of the endocrine failure; hungry-bone and persistent tertiary HPT still need watching.",
      ]},
      { t: "tip", k: "gold", v: "FGF23 rises first, calcitriol falls, then PTH. High-turnover bone is PTH; low-turnover bone is over-treatment. Bind phosphate without loading calcium." },
    ],
  },
  {
    id: "aki-arf-urology",
    topicId: "nephrology",
    title: "AKI/ARF in urology, hyperkalaemia and clinical GFR",
    highYield: true,
    gold: true,
    tags: ["AKI", "hyperK", "GFR", "obstruction", "CKD"],
    exams: [
      {
        session: "June",
        year: 2022,
        marks: "4+3+3",
        stem: "Discuss the various causes of Acute on Chronic renal failure that is seen in clinical practice by a urologist. Discuss in detail the evaluation and management of Hyperkalemia. Discuss in brief the various methods to find out GFR clinically (Not Radiologically).",
      },
      {
        session: "Jun",
        year: 2019,
        marks: "4+2+4",
        stem: "Acute renal failure in urological practice: Pathophysiology, diagnosis and outline of management.",
      },
    ],
    related: ["pod", "obstructive-uropathy", "arf-calculous", "contrast-locm-hocm"],
    references: [
      "KDIGO AKI 2012 / KDIGO CKD 2024",
      "Campbell-Walsh-Wein — Urinary Tract Obstruction, AKI",
      "AHA / EAU Peri-operative care — hyperkalaemia",
    ],
    answer: [
      { t: "tip", k: "exam", v: "ARF definition + urologic causes 4 · HyperK ECG-first algorithm 3 · Clinical GFR methods with fallacies 3. Always open with pre/renal/post." },
      { t: "h", v: "Definitions" },
      { t: "ul", v: [
        "AKI (KDIGO): ↑SCr ≥0.3 mg/dL in 48 h, or ≥1.5× baseline in 7 d, or UO <0.5 mL/kg/h for 6 h. Stages 1–3 by Cr/UO.",
        "ARF is the older term for severe AKI (often Stage 3 / need for RRT).",
        "Acute on chronic: AKI superimposed on known or occult CKD (baseline Cr elevated, small kidneys, anaemia, high PTH, low Ca).",
      ]},
      { t: "h", v: "Pathophysiology (urologic lens)" },
      { t: "tbl", h: ["Compartment", "Mechanism", "Urologic examples"], r: [
        ["Pre-renal", "↓ effective perfusion; FENa <1%, Uosm >500 if intact tubules", "Sepsis, haemorrhage (PCNL/trauma), third-space (peritonitis, urinoma), ACE-i/ARB + NSAID, RAS/Goldblatt, hepatorenal in advanced malignancy"],
        ["Intrinsic renal", "ATN (ischaemic or toxic), AIN, acute GN, vascular", "Aminoglycosides, amphotericin, cisplatin, contrast, rhabdomyolysis after lithotomy positioning, pigment from clot, cholesterol emboli post-angio, pyelonephritis/abscess, TMA"],
        ["Post-renal", "Raised tubular pressure → ↓ net filtration pressure, afferent vasoconstriction (thromboxane, Ang II), tubular apoptosis", "Bilateral ureteric stones / obstruction of solitary kidney, BPH/stricture/PUV, clots, ligated ureters, retroperitoneal fibrosis, sloughed papillae, blocked stents/PCN"],
      ]},
      { t: "h", v: "Acute-on-chronic causes a urologist actually sees" },
      { t: "ul", v: [
        "Obstruction on background CKD: BPH, stricture, neurogenic bladder, bilateral stones, malignant adenopathy, RPF.",
        "Infection: pyelonephritis, pyonephrosis, emphysematous PN, urosepsis after URS/PCNL/stent.",
        "Iatrogenic: ACE-i + diuretic + NSAID (‘triple whammy’), aminoglycosides, contrast (CIN), phosphate bowel prep, TURP syndrome (volume/glycine), high intra-abdominal pressure laparoscopy.",
        "Haemodynamic: bleeding after PCNL/PN/RN, cardiorenal in elderly TURP, abdominal compartment after ileal conduit leak.",
        "Progression of obstructive nephropathy, reflux nephropathy, ADPKD haemorrhage/infection, ischaemic nephropathy.",
        "Drugs in stone formers: excess calcium/vitamin D, high-dose vitamin C (oxalate), chemotherapy (TLS, methotrexate).",
      ]},
      { t: "h", v: "Diagnosis" },
      { t: "ul", v: [
        "Life threats first: K, pH, volume, sepsis, obstruction (bladder scan + US / NCCT).",
        "History: residual, stones, drugs, contrast, diarrhoea/vomiting, recent instrumentation.",
        "Labs: CBC, smear, CK, urine microscopy (muddy brown ATN, WBC casts AIN/pyelo, dysmorphic RBCs/RBC casts GN), FENa / FEUrea (if on diuretic), VBG, cultures.",
        "Imaging: US for hydronephrosis and kidney size (small = CKD). NCCT if stone. Doppler resistive index / MAG3 if needed. Do not wait for MAG3 in an obstructed infected kidney.",
      ]},
      { t: "h", v: "Management outline" },
      { t: "ul", n: true, v: [
        "ABC, oxygen, large-bore access, stop nephrotoxins, treat sepsis (hour-1 bundle).",
        "Relieve obstruction immediately: catheter for BOO; stent or PCN for upper tract (PCN if sepsis, unbridgeable ureter, or planned PCNL).",
        "Volume: crystalloid if pre-renal; avoid overload in anuric ATN/CKD.",
        "Hyperkalaemia, acidosis, pulmonary oedema — see below; RRT if refractory.",
        "Cause-specific: stone, prostate, stricture, pyonephrosis drainage, withhold ACE-i.",
        "POD after decompression: expect and manage (see POD master).",
      ]},
      { t: "h", v: "Hyperkalaemia — evaluation and management" },
      { t: "p", v: "K >5.0 mmol/L (severe >6.5 or any ECG change). Urologic settings: obstructive uropathy, ACE-i/ARB/spironolactone, type-4 RTA, rhabdomyolysis, tumour lysis, transfusion, succinylcholine in denervated (SCI), K-sparing in CKD, missed dialysis." },
      { t: "tbl", h: ["ECG", "K (typical)"], r: [
        ["Peaked T, short QT", "6–7"],
        ["PR long, P flat, QRS wide", "7–8"],
        ["Sine wave, VF, asystole", ">8"],
      ]},
      { t: "p", v: "ECG underestimates — treat the number and the patient, not the tracing alone." },
      { t: "flow", title: "HyperK sequence (never skip membrane stabilisation if ECG changes)", nodes: [
        { id: "a", kind: "start", label: "IV access, monitor, repeat K, ECG", to: ["b"] },
        { id: "b", kind: "decision", label: "ECG change or K ≥6.5?", to: ["c", "d"] },
        { id: "c", kind: "action", label: "Ca gluconate 10 mL 10% over 5–10 min (repeat ×2); CaCl2 if arrest", to: ["d"] },
        { id: "d", kind: "action", label: "Shift: insulin 10 U + 25 g glucose; nebulised salbutamol 10–20 mg; NaHCO3 only if pH <7.2", to: ["e"] },
        { id: "e", kind: "action", label: "Remove: loop diuretic if residual urine; potassium binders (patiromer / SZC / SPS); dialysis if oliguric CKD/AKI", to: ["f"] },
        { id: "f", kind: "end", label: "Fix cause: decompress, stop ACE-i, fludrocortisone if type-4 RTA" },
      ]},
      { t: "ul", v: [
        "Calcium buys 30–60 min of membrane stability — it does not lower K.",
        "Insulin/glucose onset 15–30 min, lasts 4–6 h; watch delayed hypoglycaemia.",
        "SPS (Kayexalate) is slow and has colonic necrosis risk (especially post-op); newer binders preferred.",
        "Dialysis indications (AEIOU): Acidosis, Electrolytes (refractory K), Intoxication, Overload, Uraemia (pericarditis, encephalopathy).",
      ]},
      { t: "h", v: "Clinical (non-radiologic) GFR methods" },
      { t: "tbl", h: ["Method", "How", "Advantage", "Fallacy"], r: [
        ["Serum creatinine", "Jaffe / enzymatic", "Cheap, universal", "Rises only after 50% GFR loss; muscle mass, diet, trimethoprim, cimetidine; lag in AKI"],
        ["Cockcroft–Gault", "(140−age)×wt×(0.85 if ♀) / (72×Cr)", "Drug dosing historically", "Uses weight not BSA; overestimates in obese; not for AKI"],
        ["MDRD 4-variable", "Cr, age, sex, race", "eGFR reporting", "Inaccurate >60 mL/min; race coefficient abandoned"],
        ["CKD-EPI (Cr, 2021 race-free)", "Current lab default", "Better at higher GFR", "Still creatinine-based; not for AKI, pregnancy, extremes of muscle"],
        ["CKD-EPI Cr–cystatin C", "Combined", "Best equation accuracy", "Cystatin not universally available; steroids/thyroid affect cystatin"],
        ["24-h creatinine clearance", "UCr×V / PCr", "No isotope; useful in extremes", "Incomplete collection; tubular Cr secretion overestimates GFR (cimetidine block sometimes used)"],
        ["Cystatin C alone", "All nucleated cells, freely filtered", "Less muscle-dependent", "Cost, extra-renal influences"],
        ["Inulin / 51Cr-EDTA / iohexol plasma clearance", "Gold-standard clearance", "Donor evaluation, research", "The question said NOT radiologic; inulin is physiologic gold but impractical. Iohexol is a contrast but plasma-clearance is a kinetic not an imaging test — mention and move on."],
      ]},
      { t: "tip", k: "gold", v: "Urologic AKI is obstruction and sepsis until proven otherwise. HyperK: calcium → shift → remove. Quote KDIGO for AKI, CKD-EPI for eGFR, and never use an equation in the acute unstable patient." },
    ],
  },
  {
    id: "acid-base-rta",
    topicId: "nephrology",
    title: "Renal acid–base handling and renal tubular acidosis",
    highYield: true,
    gold: true,
    tags: ["RTA", "acid-base", "hypocitraturia", "stones"],
    exams: [
      { session: "Jun", year: 2014, marks: "6+4", stem: "What are the acid-base balance mechanisms of kidney? Discuss in brief the types of renal tubular acidosis." },
      { session: "Dec", year: 2015, marks: "6+4", stem: "Renal tubular acidosis: Tabular overview of types. Principles of management." },
      { session: "Dec", year: 2020, marks: "4+3+3", stem: "Etiology, diagnosis, and treatment of type-1 renal tubular acidosis." },
    ],
    related: ["caox-citrate", "metabolic-evaluation", "struvite-stones"],
    references: [
      "Brenner & Rector — Acid–base",
      "Campbell — Urolithiasis / RTA",
      "EAU Urolithiasis — hypocitraturia and dRTA",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Three renal acid–base jobs (reclaim HCO3, excrete titratable acid, generate new HCO3 via ammoniagenesis) 6 · RTA table 4. Type-1 gets extra depth: stones, nephrocalcinosis, alkali + K + K-citrate." },
      { t: "h", v: "Renal acid–base mechanisms" },
      { t: "ul", n: true, v: [
        "Reabsorption of filtered bicarbonate (~4000 mmol/d). 80–90% in proximal tubule: luminal NHE3 secretes H+, which with CA IV forms CO2; intracellular CA II regenerates HCO3 which exits via NBCe1 (basolateral). Loop and distal segments reclaim the rest (pendrin, H-ATPase).",
        "Excretion of titratable acid (~10–40 mmol/d): filtered phosphate (HPO4²⁻ → H2PO4⁻) is the main buffer; creatinine and urate contribute.",
        "Ammoniagenesis (the expandable limb, 30–40 mmol/d, can rise 10-fold in acidosis): proximal tubule glutamine → NH4+ + HCO3 (glutaminase, glutamate dehydrogenase). NH4+ is recycled in TAL (NKCC2) and secreted in collecting duct (Rh glycoproteins). Each NH4+ excreted = one new HCO3 to blood.",
        "Distal H+ secretion: intercalated cells — α-cell H-ATPase and H/K-ATPase (acidosis, hypokalaemia); β-cell pendrin for HCO3 secretion (alkalosis).",
        "Aldosterone / principal cells: ENaC-driven lumen-negativity favours H+ and K+ secretion — links type-4 RTA to hypoaldosteronism.",
        "Respiratory compensation is lungs; kidney takes 24–48 h to generate/consume HCO3 (Winters’ formula is for the respiratory side).",
      ]},
      { t: "h", v: "RTA — tabular overview" },
      { t: "tbl", c: "All four for 10 marks", h: ["", "Type 1 (distal)", "Type 2 (proximal)", "Type 4 (hyperK)", "Type 3 (mixed, rare)"], r: [
        ["Defect", "α-intercalated H-ATPase / AE1; cannot acidify urine", "Proximal HCO3 reclaim (NHE3/CA II/NBCe1)", "Hypoaldosteronism or resistance → ↓ H+ and K+ secretion", "CA II deficiency (osteopetrosis)"],
        ["Urine pH in acidosis", ">5.5 (cannot fall)", "<5.5 once HCO3 below threshold", "<5.5", ">5.5"],
        ["Plasma K", "Low (or normal)", "Low", "High", "Low"],
        ["Plasma HCO3", "Often <10–15", "Usually 15–18 (threshold)", "Mild 15–20", "Variable"],
        ["FE-HCO3", "<5%", ">15% during HCO3 load", "<5%", "Intermediate"],
        ["Citrate / stones", "Hypocitraturia, hypercalciuria → CaP stones, nephrocalcinosis", "Usually no stones (citrate relatively preserved)", "No stones", "Nephrocalcinosis"],
        ["Causes", "Primary (genetic ATP6V1B1, ATP6V0A4, SLC4A1); Sjögren, SLE, amphotericin, lithium, ifosfamide, toluene, obstruction, transplant rejection, sickle cell, cirrhosis", "Fanconi (cystinosis, Wilson, tenofovir, ifosfamide, acetazolamide, topiramate, outdated tetracycline), isolated", "Diabetic hyporeninaemic hypoaldosteronism, ACE-i/ARB, heparin, NSAID, K-sparing, Gordon, obstruction, Addison, PHA type 1", "CA2 mutation"],
        ["Other", "Deafness in some ATP6; bone disease", "Osteomalacia, Fanconi package (PO4, urate, glucose, amino acids)", "Mild acidosis, dangerous K", "Brain calcification"],
      ]},
      { t: "h", v: "Type-1 (distal) RTA — etiology, diagnosis, treatment (Dec 20)" },
      { t: "ul", v: [
        "Etiology: as table. In urology: chronic obstruction, reflux nephropathy, medullary sponge, transplant, amphotericin, toluene (glue), autoimmune (Sjögren — always ask dry eyes).",
        "Diagnosis: normal anion-gap hyperchloraemic metabolic acidosis + hypokalaemia + urine pH >5.5 despite acidaemia. Confirm with NH4Cl or furosemide–fludrocortisone test (urine pH stays >5.3). Urine anion gap positive (low NH4+). Hypocitraturia (<1.5 mmol/d), hypercalciuria. Stones: calcium phosphate, nephrocalcinosis on CT. Genetic testing in children / familial.",
        "Differentiate: diarrhoea (urine AG negative), type 2 (urine pH can fall, FE-HCO3 high, Fanconi), type 4 (high K, mild acidosis), UTI with urea-splitters (urine pH high but systemic acidosis absent unless struvite sepsis).",
        "Treatment: alkali 1–2 mEq/kg/d adults (up to 5–10 in children) as potassium citrate preferred (treats K, citrate, and CaP risk) or NaHCO3/Na citrate. Correct K before pushing alkali (insulin-like shift). Treat cause (steroids for Sjögren AIN, relieve obstruction). Thiazide if hypercalciuria persists. Stone measures: high fluid, citrate; avoid acetazolamide/topiramate. Follow pH, HCO3, K, citrate, bone density.",
      ]},
      { t: "h", v: "Principles of management (all types)" },
      { t: "ul", v: [
        "Type 2: alkali doses large (10–15 mEq/kg) because of bicarbonaturia; potassium; treat Fanconi (phosphate, vitamin D). Thiazide / low-salt to enhance proximal reclaim. Stones uncommon.",
        "Type 4: stop offending drugs; fludrocortisone if hypoaldosteronism; loop diuretic + dietary K restriction; oral bicarbonate for acidosis; avoid spironolactone.",
        "All: protect bones, screen stones in type 1, genetic counsel.",
      ]},
      { t: "tip", k: "gold", v: "Type 1 = cannot lower urine pH, low K, CaP stones. Type 2 = Fanconi, can acidify once HCO3 is below threshold. Type 4 = high K, diabetic, drugs. Potassium citrate is the urologist’s alkali." },
    ],
  },
  {
    id: "obstructive-nephropathy-iron-calcium",
    topicId: "nephrology",
    title: "Chronic obstructive nephropathy; iron and calcium in CKD",
    highYield: false,
    gold: false,
    tags: ["obstruction", "CKD", "iron", "calcium", "fibrosis"],
    exams: [
      {
        session: "Dec",
        year: 2013,
        marks: "5+5",
        stem: "Describe the changes in nephrons and interstitium in chronic obstructive nephropathy. What is the role of supplementing iron and Calcium in CKD?",
      },
    ],
    related: ["pod", "endocrine-kidney-osteodystrophy", "anaemia-ckd", "ckd-classification-anaemia"],
    references: [
      "Campbell — Pathophysiology of Urinary Tract Obstruction",
      "KDIGO Anaemia in CKD / CKD-MBD",
    ],
    answer: [
      { t: "h", v: "Nephron and interstitial changes in chronic obstruction" },
      { t: "ul", v: [
        "Haemodynamic: early afferent dilatation (PGE2) then vasoconstriction (thromboxane A2, Ang II, ET-1) → fall in GFR and renal blood flow. Post-obstructive RBF may not recover fully.",
        "Tubules: flattening, loss of brush border, down-regulation of Na/K-ATPase, NKCC2, ENaC, AQP2 → salt wasting, concentrating defect, acidification defect (acquired dRTA). Apoptosis of tubular cells (Fas, caspase, oxidative stress).",
        "Interstitium: macrophage infiltrate (MCP-1), myofibroblast activation, TGF-β1 / Smad, epithelial–mesenchymal transdifferentiation (debated), collagen I/III deposition → irreversible tubulo-interstitial fibrosis. Peritubular capillary rarefaction.",
        "Glomeruli: initially spared; later secondary FSGS from hyperfiltration of remaining nephrons and transmitted pressure.",
        "Collecting system: muscular hypertrophy then atony, forniceal rupture possible in acute-on-chronic.",
        "Recovery potential: weeks of obstruction — partial; months — residual concentrating defect and reduced GFR. Split function <10–15% rarely recovers usefully.",
      ]},
      { t: "h", v: "Iron supplementation in CKD" },
      { t: "ul", v: [
        "Anaemia of CKD = EPO deficiency + iron-restricted erythropoiesis (hepcidin high → ferroportin internalised → iron trapped in stores, low TSAT despite high ferritin).",
        "KDIGO: consider iron if TSAT ≤30% and ferritin ≤500 ng/mL (dialysis) when an ESA is planned or Hb not at target. Absolute iron deficiency: ferritin <100 (ND-CKD) or <200 (dialysis) + TSAT <20%.",
        "IV iron preferred in HD (iron sucrose, ferric carboxymaltose, ferumoxytol, ferric citrate also binds phosphate). Oral in ND-CKD if tolerated (GI side effects, hepcidin blocks absorption).",
        "Benefits: raise Hb, spare ESA dose, fewer transfusions (HLA sensitisation matters for transplant).",
        "Risks: anaphylactoid (historically high-MW iron dextran), oxidative stress, infection signal (free iron, withhold in active sepsis), phosphate fall with FCM (FGF23).",
      ]},
      { t: "h", v: "Calcium supplementation in CKD" },
      { t: "ul", v: [
        "Goals: treat symptomatic hypocalcaemia, provide a phosphate binder (calcium acetate/carbonate), and substrate for bone if truly deficient.",
        "KDIGO cautions against hypercalcaemia and large positive Ca balance — vascular calcification, adynamic bone. Limit elemental Ca from binders.",
        "Correct acidosis first (increases ionised Ca). Replete 25-OH vitamin D. Active vitamin D analogues if PTH high, not calcium alone.",
        "Do not give calcium empirically ‘for bones’ in dialysis patients with high-normal Ca and high Ca×PO4.",
        "Post-parathyroidectomy hungry-bone: large IV/oral Ca + calcitriol is mandatory.",
      ]},
      { t: "tip", k: "gold", v: "Chronic obstruction kills the tubulo-interstitium via TGF-β and ischaemia, not the glomerulus first. Iron is for hepcidin-locked stores; calcium is not a vitamin — it calcifies vessels if you overshoot." },
    ],
  },
  {
    id: "proteinuria",
    topicId: "nephrology",
    title: "Proteinuria — surgical vs medical causes and evaluation",
    highYield: false,
    gold: false,
    tags: ["proteinuria", "nephrotic", "overflow", "orthostatic"],
    exams: [
      {
        session: "Dec",
        year: 2015,
        marks: "5+5",
        stem: "Mention the surgical and medical causes of Proteinuria? How would you evaluate a case of proteinuria?",
      },
    ],
    related: ["adpkd", "ckd-classification-anaemia", "papillary-necrosis"],
    references: ["KDIGO Glomerular Diseases 2021", "Campbell — Medical aspects of urology"],
    answer: [
      { t: "h", v: "Classification by mechanism" },
      { t: "tbl", h: ["Type", "Mechanism", "Typical protein"], r: [
        ["Glomerular", "Charge/size barrier failure", "Albumin dominant; nephrotic if ≥3.5 g/d"],
        ["Tubular", "Failed proximal reuptake of filtered LMW proteins", "β2-microglobulin, RBP, light chains (modest 1–2 g)"],
        ["Overflow", "Overproduction exceeds reabsorption", "Light chains (myeloma), myoglobin, haemoglobin"],
        ["Post-renal / secretory", "Inflammation, tumour, stones, blood", "Tamm–Horsfall, IgA, blood proteins"],
        ["Orthostatic", "Adolescent, daytime only", "Albumin, <1.5 g; night-time sample normal"],
      ]},
      { t: "h", v: "Medical causes" },
      { t: "ul", v: [
        "Nephrotic: MCD, FSGS, membranous (including anti-PLA2R, malignancy, NSAID, HBV), diabetic nephropathy, amyloid, MPGN, lupus.",
        "Nephritic / mixed: IgA, post-strep, anti-GBM, ANCA, MPGN.",
        "Tubular: ATN recovery, AIN, Fanconi, heavy metals, tenofovir, cystinosis.",
        "Overflow: myeloma, rhabdomyolysis, intravascular haemolysis.",
        "Functional / transient: fever, exercise, CCF, pregnancy (up to 300 mg), uncontrolled HTN.",
      ]},
      { t: "h", v: "Surgical / urologic causes" },
      { t: "ul", v: [
        "Fever and inflammation: pyelonephritis, renal abscess, TB, infected hydronephrosis.",
        "Stones, clots, tumours (RCC, TCC) — often dipstick ‘protein’ is actually blood.",
        "Reflux nephropathy and chronic obstruction — secondary FSGS of remnant nephrons.",
        "Renal vein thrombosis (nephrotic as cause or consequence; RCC thrombus).",
        "After instrumentation, cystitis, BPH with residual, ileal conduit mucus (false positive).",
        "Solitary kidney / hyperfiltration after nephrectomy, morbid obesity, horseshoe with scarring.",
        "Preeclampsia in the obstetric-urology interface.",
      ]},
      { t: "h", v: "Evaluation" },
      { t: "ul", n: true, v: [
        "Confirm: repeat dipstick; SSA/turbidimetry if light chains suspected (dipstick misses Bence Jones). Ratio: PCR or ACR on spot morning sample; 24-h collection if nephrotic or discordant.",
        "Quantify and characterise: ACR (albumin) vs PCR (total). Microalbuminuria 30–300 mg/d (diabetic/CKD staging). Nephrotic ≥3.5 g/d + hypoalbuminaemia ± oedema ± hyperlipidaemia.",
        "Urine microscopy: dysmorphic RBC/RBC casts = glomerular; WBC casts = interstitial/pyelo; oval fat bodies = nephrotic; crystals.",
        "Orthostatic test in young thin patient: split day/night collections.",
        "Blood: Cr/eGFR, albumin, lipids, HbA1c, ANA/dsDNA, complement, ANCA, anti-GBM, ASO, HBV/HCV/HIV, PLA2R, SPEP/UPEP/FLC, ASO.",
        "Imaging: US kidneys (size, scars, obstruction, thrombus Doppler). CT/cystoscopy if urologic bleeding/tumour suspected.",
        "Biopsy: unexplained glomerular proteinuria, especially nephrotic (except typical diabetic, typical MCD child, or overflow myeloma already diagnosed).",
      ]},
      { t: "tip", k: "gold", v: "Dipstick = albumin. Light chains need SSA/FLC. Urologic proteinuria is blood, infection or hyperfiltration until a nephrologist proves a glomerulopathy." },
    ],
  },
  {
    id: "ischaemic-nephropathy",
    topicId: "nephrology",
    title: "Ischaemic nephropathy",
    highYield: true,
    gold: false,
    tags: ["RAS", "atherosclerosis", "renovascular"],
    exams: [
      {
        session: "Jun",
        year: 2016,
        marks: "2+4+4",
        stem: "Define ischaemic nephropathy. Pathophysiology and management of ischaemic nephropathy.",
      },
    ],
    related: ["renovascular-hypertension", "aki-arf-urology"],
    references: [
      "Campbell — Renovascular Hypertension and Ischaemic Nephropathy",
      "ASTRAL, CORAL trials",
      "KDIGO / AHA renovascular disease",
    ],
    answer: [
      { t: "p", v: "Ischaemic nephropathy is chronic, haemodynamically significant reduction of renal perfusion — usually atherosclerotic renal-artery stenosis (ARAS), often bilateral or in a solitary kidney — producing a fall in GFR that is out of proportion to hypertensive nephrosclerosis alone. It is a cause of CKD and flash pulmonary oedema, not merely of hypertension." },
      { t: "h", v: "Pathophysiology" },
      { t: "ul", v: [
        "Critical stenosis (~70–80% with post-stenotic dilatation or pressure drop) → activation of RAAS from the under-perfused kidney.",
        "Ang II maintains GFR by efferent constriction in the stenotic kidney; ACE-i/ARB can precipitate acute on chronic failure if the contralateral kidney is also stenosed or absent (the clinical Goldblatt 1K1C).",
        "Chronic hypoperfusion: tubular atrophy, interstitial fibrosis, microvascular rarefaction, cholesterol emboli, hypertensive damage in the contralateral kidney (the 2K1C long-term picture).",
        "Statin-era plaque is lipid + inflammation; microvascular disease may persist after the stenosis is stented — explaining negative ASTRAL/CORAL results.",
        "Pickering syndrome: bilateral RAS + severe HTN + flash pulmonary oedema (diastolic dysfunction + pressure natriuresis failure).",
      ]},
      { t: "h", v: "Management" },
      { t: "ul", v: [
        "Medical first (CORAL/ASTRAL): statin, antiplatelet, BP control (ACE-i/ARB if solitary-kidney function is watched closely), SGLT2-i/diabetes care, smoking cessation. This is the evidence-based default.",
        "Revascularisation (angioplasty ± stent, rarely bypass/endarterectomy) reserved for: progressive CKD with bilateral or solitary-kidney RAS, recurrent flash oedema, refractory HTN on ≥3 agents, ACE-i-induced AKI that recovers on stopping, documented progressive stenosis, fibromuscular dysplasia (angioplasty without stent is curative in FMD).",
        "Avoid attempting salvage of a small (<7–8 cm), non-functioning, highly resistive kidney — nephrectomy for renin-dependent HTN is occasionally indicated after captopril-renogram lateralisation.",
        "Cholesterol emboli after catheterisation: livedo, blue toes, eosinophilia, low complement — supportive.",
      ]},
      { t: "tip", k: "gold", v: "Ischaemic nephropathy is ARAS plus lost GFR. Stent the syndrome (flash oedema, progressive solitary-kidney CKD, FMD), not the angiogram. ASTRAL and CORAL killed routine stenting." },
    ],
  },
  {
    id: "renovascular-hypertension",
    topicId: "nephrology",
    title: "Renovascular hypertension — Goldblatt models, diagnosis, management",
    highYield: true,
    gold: true,
    tags: ["Goldblatt", "RAS", "captopril", "FMD", "ARAS"],
    exams: [
      { session: "Dec", year: 2019, marks: "5+5", stem: "Goldblatt experimental model for single kidney one clip and two kidneys one clip renovascular hypertension." },
      { session: "Jun", year: 2018, marks: "10", stem: "Renal artery stenosis: diagnosis and management." },
      {
        session: "June",
        year: 2022,
        marks: "4+3+3",
        stem: "Enumerate the various causes of renovascular hypertension. Describe in brief the interpretation of Captopril Renogram. Discuss the management of a patient who has unilateral renal artery stenosis due to atherosclerosis with 80% luminal block.",
      },
      { session: "Dec", year: 2018, marks: "10", stem: "Evaluation of renovascular hypertension in young male." },
      {
        session: "Dec",
        year: 2012,
        marks: "1+4+5",
        stem: "Describe renovascular hypertension. Discuss diagnostic evaluation of renovascular hypertension. Write briefly on treatment options in renovascular hypertension.",
      },
      { session: "Jun", year: 2021, marks: "4+3+3", stem: "Define pathophysiology of renal vascular hypertension. Discuss investigative and management tools." },
    ],
    related: ["ischaemic-nephropathy", "aki-arf-urology", "endocrine-kidney-osteodystrophy"],
    references: [
      "Goldblatt H et al. J Exp Med 1934",
      "Campbell — Renovascular Hypertension",
      "ASTRAL (NEJM 2009), CORAL (NEJM 2014), DRASTIC",
      "EAU / AHA hypertension guidelines",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "Define RVHTN 1 · Causes 2 · Goldblatt 2K1C vs 1K1C 2 · Captopril MAG3 2 · Young male = FMD algorithm 2 · 80% atherosclerotic unilateral = medical therapy unless a salvage indication 1. Draw both Goldblatt models." },
      { t: "h", v: "Definition and causes" },
      { t: "p", v: "Renovascular hypertension is secondary hypertension caused by renal hypoperfusion and RAAS activation, potentially curable by restoring perfusion or removing the renin source. It is not synonymous with RAS — many stenoses are incidental." },
      { t: "tbl", h: ["Cause", "Typical patient", "Lesion"], r: [
        ["Atherosclerotic RAS (90% of RAS)", "Older, smoker, CAD/PAD, CKD", "Ostial / proximal 1 cm, often aortic plaque"],
        ["Fibromuscular dysplasia (medial fibroplasia 85%)", "Young woman > man, 15–50 y; young male still FMD until proven otherwise", "Mid/distal artery ‘string of beads’; may involve extra-renal arteries"],
        ["Takayasu aorto-arteritis", "Young Asian female (male also)", "Ostial, aorta involved, bruits, high ESR/CRP"],
        ["Polyarteritis nodosa, Kawasaki, radiation, NF-1, Williams, middle-aortic syndrome", "Paediatric / syndromic", "Mid-aortic or branch stenoses"],
        ["Extrinsic: page kidney (subcapsular haematoma), tumour, ligation, transplant anastomotic stenosis, dissection, thrombosis, embolus, retroperitoneal fibrosis", "Context-specific", "Not always ‘stenosis’ on angio"],
        ["Post-transplant RAS", "Rising Cr, flash oedema, resistant HTN", "Anastomosis"],
      ]},
      { t: "h", v: "Pathophysiology — Goldblatt models (Dec 19)" },
      { t: "tbl", c: "Quote 1934; clip = renal artery constriction", h: ["Model", "Anatomy", "RAAS / volume", "BP mechanism", "ACE-i effect"], r: [
        ["2K1C (two kidneys, one clip)", "One stenotic kidney, contralateral intact", "Stenotic kidney secretes renin; contralateral natriuresis (pressure natriuresis) prevents volume expansion — renin stays high", "Ang II vasoconstriction. Contralateral kidney is damaged by hypertensive nephrosclerosis long-term", "BP falls; stenotic-kidney GFR may fall (efferent dilatation) but contralateral kidney maintains function"],
        ["1K1C (one kidney, one clip) or 2K2C", "Solitary stenotic kidney, or bilateral clips", "No contralateral natriuresis → volume expansion; renin may fall toward normal once volume is up (Goldblatt ‘volume phase’)", "Volume-dependent HTN + residual RAAS", "ACE-i / ARB can cause acute renal failure — diagnostic clue"],
      ]},
      { t: "p", v: "Human analogues: unilateral ARAS/FMD with a healthy mate = 2K1C. Bilateral RAS, RAS in a solitary/transplant kidney, or long-standing unilateral RAS with contralateral nephrosclerosis = 1K1C physiology. Page kidney is renin-driven without arterial stenosis." },
      { t: "h", v: "When to suspect (clinical clues)" },
      { t: "ul", v: [
        "Young hypertensive, especially female (FMD) or Asian (Takayasu); malignant/accelerated HTN; sudden onset or sudden worsening.",
        "Asymmetry of kidneys >1.5 cm, abdominal bruit (systolic-diastolic), flash pulmonary oedema, unexplained AKI on ACE-i, PAD/CAD, rise in Cr with diuretic + ACE-i.",
        "Secondary hyperaldosteronism (high renin, high aldo) as opposed to Conn (low renin).",
      ]},
      { t: "h", v: "Captopril renogram — interpretation (June 22)" },
      { t: "ul", v: [
        "Principle: MAG3 (or DTPA) before and after 25–50 mg captopril. ACE-i drops Ang II-mediated efferent tone in the stenotic kidney → cortical retention, delayed time-to-peak, delayed excretion, fall in relative function.",
        "Positive: (i) delayed peak >11 min on captopril, (ii) residual cortical activity at 20 min, (iii) ≥10% fall in ipsilateral function, (iv) change from a normal baseline curve to an obstructive/flattened curve.",
        "High sensitivity in 2K1C with GFR >30 and unilateral disease. False negative: 1K1C (both sides affected, no ‘control’), poor GFR, ACE-i already on board, significant obstruction, dehydration.",
        "Now largely replaced by CTA/MRA as first anatomic test; captopril scan remains a functional test when ‘is the stenosis causal?’ matters and GFR is adequate.",
      ]},
      { t: "h", v: "Diagnostic evaluation" },
      { t: "ul", v: [
        "Young male (Dec 18): exclude coarctation (radio-femoral delay, rib notching), measure plasma renin/aldosterone (off β-blockers if possible), urine metanephrines, Doppler RAS (peak systolic velocity >200–300 cm/s, renal-aortic ratio >3.5), CTA or contrast MRA (FMD string of beads is mid-distal — must image to bifurcation), catheter angio if intervention planned. ESR/CRP for Takayasu. Genetic/syndromic if paediatric (NF-1, Williams).",
        "Older atherosclerotic: duplex or CTA; conventional angio as a prelude to stent, not as screening.",
        "Duplex: operator-dependent, bowel gas; good for follow-up of FMD/stent.",
        "DSA remains gold-standard anatomy; pressure gradient >10–20 mmHg systolic confirms haemodynamic significance.",
      ]},
      { t: "h", v: "Management of unilateral 80% atherosclerotic RAS (June 22)" },
      { t: "p", v: "80% diameter is anatomically severe but CORAL/ASTRAL showed no benefit of routine stenting plus medical therapy over medical therapy alone for BP or GFR in stable patients." },
      { t: "ul", v: [
        "First line: intensive medical therapy — statin high-intensity, antiplatelet, BP to target (ACE-i/ARB are beneficial if Cr is watched; a 20–30% Cr rise that plateaus is acceptable in unilateral disease because the contralateral kidney is working), smoking cessation, diabetes/SGLT2-i, diet.",
        "Offer revascularisation only if: refractory HTN (≥3 drugs including a diuretic), progressive CKD, flash oedema, recurrent AKI on ACE-i, or a solitary functioning kidney. Then PTA + stent (ostial ARAS recoils without stent), dual antiplatelet peri-stent, watch atheroemboli.",
        "Surgery (endarterectomy, aortorenal bypass, extra-anatomic hepatorenal/splenorenal) for failed stent, complex aneurysm, or concomitant aortic surgery — rare.",
        "Nephrectomy of a small, scarred, renin-secreting unilateral kidney if BP remains renin-driven after failed revascularisation (captopril-renogram lateralises).",
        "FMD (young): angioplasty WITHOUT stent is first-line and often curative; stent only for dissection/bailout.",
      ]},
      { t: "tip", k: "gold", v: "2K1C = renin HTN with a natriuretic contralateral kidney. 1K1C = volume HTN; ACE-i may wipe GFR. Stent FMD and the unstable atherosclerotic syndromes, not every 80% ostial plaque." },
    ],
  },
  {
    id: "contrast-locm-hocm",
    topicId: "nephrology",
    title: "LOCM vs HOCM and contrast-induced nephropathy",
    highYield: true,
    gold: false,
    tags: ["CIN", "contrast", "LOCM", "HOCM", "PC-AKI"],
    exams: [
      {
        session: "June",
        year: 2022,
        marks: "5+5",
        stem: "Discuss and classify LOCM and HOCM. Contrast nephropathy and the drugs used in the treatment of this condition.",
      },
    ],
    related: ["aki-arf-urology", "ckd-classification-anaemia"],
    references: [
      "ACR / ESUR contrast media guidelines",
      "KDIGO AKI — contrast",
      "AMACING trial (NEJM 2017) — hydration",
      "Campbell — Urologic imaging",
    ],
    answer: [
      { t: "h", v: "Classification of iodinated contrast" },
      { t: "p", v: "Iodinated agents are classified by osmolality, ionicity and molecular structure (monomer vs dimer). Osmolality relative to plasma (~290 mOsm/kg) is the exam axis." },
      { t: "tbl", h: ["Class", "Osmolality", "Examples", "Notes"], r: [
        ["HOCM — high-osmolar ionic monomers", "1500–2000 mOsm/kg (~5–8× plasma)", "Diatrizoate (Urografin, Hypaque), iothalamate, metrizoate", "Cheap. High CIN, allergy, nausea, cardiac load. Obsolete intravascularly. Still used for cystography / RGP in some units (not IV)."],
        ["LOCM — low-osmolar non-ionic monomers", "600–800 mOsm/kg (~2–3× plasma)", "Iohexol (Omnipaque), iopamidol (Isovue), iopromide (Ultravist), ioversol, iomeprol", "Workhorse IV/IA agents. Still hyperosmolar to plasma despite the name ‘low’."],
        ["LOCM — low-osmolar ionic dimer", "~600 mOsm/kg", "Ioxaglate (Hexabrix)", "Ionic but dimeric so osmolality similar to non-ionic monomers. Used less."],
        ["IOCM — iso-osmolar non-ionic dimer", "~290 mOsm/kg", "Iodixanol (Visipaque)", "Iso-osmolar; more viscous. Theoretical CIN benefit not consistently proven vs LOCM if hydration is equal. Preferred by some in severe CKD / intra-arterial."],
      ]},
      { t: "p", v: "Gadolinium is not HOCM/LOCM; it is a separate nephrogenic systemic fibrosis risk at eGFR <30. Dual-energy / low-kVp and low-dose protocols reduce iodine load." },
      { t: "h", v: "Contrast-associated AKI (CA-AKI / CIN)" },
      { t: "ul", v: [
        "Definition (classic): ↑SCr ≥0.5 mg/dL or ≥25% within 48–72 h of intravascular contrast, without alternative cause. KDIGO AKI criteria also used. Modern term: CA-AKI (association) vs CI-AKI (causation) — IV LOCM risk is smaller than historically taught (AMACING).",
        "Pathophysiology: (i) intense outer-medullary vasoconstriction (adenosine, endothelin, high osmolality) with already borderline pO2; (ii) direct tubular cytotoxicity (ROS, vacuolisation); (iii) viscosity slowing tubular flow (especially IOCM dimers); (iv) osmotic diuresis and tubuloglomerular feedback.",
        "Risk: eGFR <30 (IV) or <45 (IA), AKI, diabetes + CKD, heart failure, anaemia, age, volume depletion, NSAID/ACE-i, high dose / repeated dose within 72 h, intra-arterial supra-renal injection, myeloma + dehydration (cast nephropathy — the ‘cast’ not the contrast per se).",
        "Course: Cr peaks day 2–5, oliguria uncommon, recovery 7–10 d; residual CKD possible. ATN picture with FENa variable.",
      ]},
      { t: "h", v: "Prevention (the evidence) and ‘drugs used’" },
      { t: "ul", v: [
        "Hydration is the only consistently useful measure: isotonic NaCl 1 mL/kg/h 6–12 h before and after, or 3 mL/kg/h for 1 h pre + 6 h post in inpatients. NaHCO3 is not superior to saline (trials mixed). AMACING: no prophylaxis if eGFR >30 and risk low.",
        "Use LOCM or IOCM, lowest volume, avoid repeat within 72 h, stop NSAIDs. Metformin hold is lactic-acidosis policy (eGFR <30), not CIN prevention.",
        "N-acetylcysteine: antioxidant; PROMETHEUS of CIN literature — ACT trial negative. Still written in answers as ‘optional, evidence weak’.",
        "Statins (high-dose atorvastatin/rosuvastatin peri-procedure): some PCI data; not standard for CT.",
        "Vitamin C, theophylline/aminophylline (adenosine antagonist), fenoldopam, dopamine, ANP, forced diuresis (NEPHRIC-style mannitol/furosemide): not recommended; diuretics may harm unless overload.",
        "Prophylactic haemodialysis: does not prevent CIN (contrast already injured medulla). Haemofiltration in very high-risk PCI is experimental.",
        "Treatment of established CIN: as ATN — supportive, stop nephrotoxins, volume, RRT if AEIOU. No specific antidote.",
      ]},
      { t: "tip", k: "gold", v: "HOCM = ionic monomers, 1500 mOsm, not for veins. LOCM = non-ionic monomers, the default. IOCM = iodixanol. Saline is the drug; NAC is nostalgia. Do not haemodialyse contrast ‘out’." },
    ],
  },
  {
    id: "metabolic-syndrome-urology",
    topicId: "nephrology",
    title: "Metabolic syndrome in ageing men and the kidney",
    highYield: false,
    gold: false,
    tags: ["metabolic syndrome", "stones", "BPH", "CKD", "hypogonadism"],
    exams: [
      {
        session: "Dec",
        year: 2020,
        marks: "5+5",
        stem: "What are urologic conditions associated with metabolic syndrome in aging men? Describe the various renal conditions where metabolic syndrome plays a role.",
      },
    ],
    related: ["caox-citrate", "ckd-classification-anaemia", "papillary-necrosis"],
    references: [
      "EAU Male LUTS / Urolithiasis",
      "IDF / NCEP-ATP III metabolic syndrome definitions",
      "Campbell — BPH, stones, ED",
    ],
    answer: [
      { t: "p", v: "Metabolic syndrome (MetS): central obesity + ≥2 of raised TG, low HDL, hypertension, fasting glucose/diabetes (IDF). NCEP-ATP III uses any 3 of 5. Ageing men accumulate MetS with falling testosterone, sarcopenic obesity and inactivity." },
      { t: "h", v: "Urologic associations in ageing men" },
      { t: "ul", v: [
        "LUTS/BPH: insulin resistance → sympathetic overdrive, pelvic atherosclerosis, low-grade inflammation (CRP, IL-6), larger glands, worse storage symptoms, poorer response to α-blockers. Statin/weight-loss data mixed but lifestyle is first-line with medical LUTS care.",
        "ED and hypogonadism: endothelial dysfunction, NO deficiency; MetS is a strong ED risk. Low T worsens visceral fat (vicious cycle). PDE5-i + risk-factor control.",
        "Prostate cancer: obesity associated with higher-grade disease and worse outcomes after treatment (ascertainment bias for PSA dilution); MetS–PCa link is not a screening indication.",
        "Urolithiasis: see below.",
        "Infertility / subfertility in younger MetS: spermatogenic and erectile components.",
        "Overactive bladder, stone clinic ‘uric acid stone + diabetes’ phenotype, Fournier risk (diabetes), CKD.",
      ]},
      { t: "h", v: "Renal conditions in which MetS plays a role" },
      { t: "ul", v: [
        "CKD and diabetic / obesity-related glomerulopathy: hyperfiltration, FSGS, albuminuria; SGLT2-i and weight loss slow progression.",
        "Uric acid nephrolithiasis: insulin resistance → low urinary pH (impaired glutamine ammoniagenesis) + hyperuricosuria. The classic ‘MetS stone’.",
        "Calcium stones: hypercalciuria, hypocitraturia, dietary salt/protein; oxalate with gastric-bypass (enteric hyperoxaluria) after bariatric surgery — iatrogenic MetS treatment creating stones.",
        "Hypertensive nephrosclerosis and ischaemic nephropathy (accelerated atherosclerosis of renal arteries).",
        "Gouty nephropathy / chronic urate nephropathy (now uncommon as a primary diagnosis).",
        "Simple cysts and perhaps faster ADPKD progression with obesity (emerging).",
        "AKI risk: contrast, sepsis, obstructive uropathy in diabetic cystopathy, papillary necrosis.",
        "Renal cell carcinoma: obesity is an established risk factor (clear-cell); MetS/diabetes associated with RCC incidence and peri-operative CKD after PN/RN.",
        "Kidney-transplant MetS: new-onset diabetes, graft loss.",
      ]},
      { t: "tip", k: "gold", v: "Ageing-man MetS = LUTS + ED + uric-acid stones. The renal fingerprint is acidic urine, CKD and RCC risk. Treat the syndrome, not just the PSA and the stone." },
    ],
  },
  {
    id: "papillary-necrosis",
    topicId: "nephrology",
    title: "Renal papillary necrosis — conditions and pathophysiology",
    highYield: true,
    gold: false,
    tags: ["papilla", "analgesic", "diabetes", "sickle", "obstruction"],
    exams: [
      {
        session: "Dec",
        year: 2022,
        marks: "5+5",
        stem: "List the conditions associated with renal papillary necrosis. Discuss the Patho-physiology of papillary necrosis.",
      },
    ],
    related: ["aki-arf-urology", "metabolic-syndrome-urology", "arf-calculous"],
    references: [
      "Campbell — Urinary Tract Infections / Analgesic nephropathy",
      "EAU Urological Infections",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Mnemonic POSTCARDS or NSAID. List 8–10 conditions then explain why the papilla is a watershed." },
      { t: "h", v: "Associated conditions (list)" },
      { t: "ul", v: [
        "Diabetes mellitus (most common in modern series) — infection + microvascular disease.",
        "Analgesic nephropathy — phenacetin historically; combination NSAID + paracetamol + caffeine still relevant. Often with calcified papillae and urothelial cancer risk.",
        "Sickle cell disease / trait — sickling in hypertonic, hypoxic medulla.",
        "Obstruction + infection (pyelonephritis, TB).",
        "Pyelonephritis / infection including candidiasis.",
        "Cirrhosis / alcohol, malnutrition.",
        "Transplant rejection, NSAIDs (acute haemodynamic), vasculitis (rare), calcineurin inhibitor toxicity.",
        "Acute: shock, dehydration, NSAID in a hypovolaemic patient, neonatal hypoxia.",
        "Others: haemophilia / coagulopathy with papillary bleed, radiation, calcium nephropathy.",
      ]},
      { t: "p", v: "Mnemonic POSTCARDS: Pyelonephritis, Obstruction, Sickle, TB, Cirrhosis, Analgesics/alcohol, Renal transplant/rejection, Diabetes, Systemic vasculitis. NSAID: NSAIDs, Sickle, Analgesics, Infection, Diabetes." },
      { t: "h", v: "Pathophysiology" },
      { t: "ul", v: [
        "The papilla is a watershed: vasa recta are sparse, oxygen tension is the lowest in the body (~10–20 mmHg), and the counter-current system maintains hypertonicity. Any further hit (hypoxia, infection, toxic metabolite, sickling, NSAID-induced PGE2 loss → unopposed medullary vasoconstriction) produces ischaemic coagulative necrosis of the papilla.",
        "Phenacetin/NSAID metabolites concentrate in the medulla; oxidative injury + reduced medullary blood flow.",
        "Diabetes: glomerulopathy + afferent/efferent hyalinosis + infection (gas, organisms) + osmotic diuresis dehydrating the medulla.",
        "Sickle: HbS polymerises in the hypertonic medulla → vaso-occlusion of vasa recta → ischaemic papilla; trait is enough.",
        "Infection/obstruction: raised pelvic pressure tamponades papillary blood flow; bacterial toxins.",
        "Morphology: focal (tips, often sickle) vs diffuse (analgesic). In situ necrosis → ring shadow on IVU/CT urography; sequestered papilla sloughs → filling defect, ureteric colic, obstruction (‘sloughed papilla’ is a urologic emergency in a solitary kidney). Calcification of necrotic papillae in chronic analgesic nephropathy.",
        "Clinical: haematuria, colic, sterile pyuria, rising Cr, recurrent UTI, passage of tissue. Chronic: CKD, hypertension, increased urothelial carcinoma (analgesic).",
      ]},
      { t: "p", v: "Management (expected even if not asked): culture, relieve obstruction (stent/PCN if sloughed papilla stuck), stop NSAIDs, control diabetes, fluids, treat infection. Imaging: CT urography — golf-ball-on-tee, lobster-claw, ring shadow. Do not crush a sloughed papilla thinking it is a stone without looking at history." },
      { t: "tip", k: "gold", v: "Papilla = hypoxic hypertonic dead-end of the vasa recta. POSTCARDS. Sloughed papilla = stone clinic mimic; stent it, do not SWL it." },
    ],
  },
  {
    id: "ckd-classification-anaemia",
    topicId: "nephrology",
    title: "CKD classification, anaemia, and the young woman with creatinine 3",
    highYield: true,
    gold: true,
    tags: ["CKD", "KDIGO", "anaemia", "EPO", "pregnancy"],
    exams: [
      {
        session: "Jun",
        year: 2017,
        marks: "10",
        stem: "Classify chronic kidney disease (CKD). Outline the management of a 26 year newly married female with serum creatinine 3mg/dl.",
      },
      {
        session: "Dec",
        year: 2022,
        marks: "6+4",
        stem: "Write definition and classification of chronic kidney disease. Briefly describe management of anemia in CKD.",
      },
      {
        session: "Jun",
        year: 2014,
        marks: "5+5",
        stem: "Describe the pathophysiology of anaemia in chronic kidney disease (CKD). How would you manage anaemia in CKD?",
      },
    ],
    related: ["endocrine-kidney-osteodystrophy", "adpkd", "aki-arf-urology"],
    references: [
      "KDIGO CKD 2024 / KDIGO Anaemia 2012",
      "Campbell — CKD for urologists",
      "KDIGO pregnancy and CKD reviews",
    ],
    answer: [
      { t: "h", v: "Definition (KDIGO)" },
      { t: "p", v: "CKD = abnormalities of kidney structure or function present >3 months, with implications for health. Either eGFR <60 mL/min/1.73 m² or marker of kidney damage (albuminuria ACR ≥30 mg/g, urine sediment, histology, imaging, transplant) for ≥3 months." },
      { t: "h", v: "Classification — CGA (Cause, GFR, Albuminuria)" },
      { t: "tbl", c: "GFR categories (G1–G5)", h: ["Stage", "eGFR", "Term"], r: [
        ["G1", "≥90", "Normal / high (CKD only if damage marker)"],
        ["G2", "60–89", "Mildly decreased"],
        ["G3a", "45–59", "Mild–moderate"],
        ["G3b", "30–44", "Moderate–severe"],
        ["G4", "15–29", "Severely decreased"],
        ["G5", "<15", "Kidney failure (add D if dialysis)"],
      ]},
      { t: "tbl", c: "Albuminuria (A1–A3) — the heat-map risk modifier", h: ["", "ACR"], r: [
        ["A1", "<30 mg/g (<3 mg/mmol) normal–mild"],
        ["A2", "30–300 mg/g moderately increased (microalbuminuria)"],
        ["A3", ">300 mg/g severely increased (macro)"],
      ]},
      { t: "p", v: "A 26-year-old with Cr 3 mg/dL: Cockcroft/CKD-EPI eGFR is typically ~20 mL/min (G4) depending on weight/race — not ‘just Cr 3’. Always convert to eGFR and stage with ACR." },
      { t: "h", v: "The newly married 26-year-old woman with Cr 3 mg/dL" },
      { t: "ul", n: true, v: [
        "Confirm CKD vs AKI: old labs, kidney size, anaemia, PTH, phosphate, urine output, obstruction (urologist’s first job — US/NCCT, residual, VUR, stones, TB, adynamic bladder).",
        "Cause: reflux nephropathy, PUJO, stones, ADPKD, GN (lupus in a young woman), diabetic rare at 26 unless long T1DM, HIV, drugs, pregnancy-related.",
        "Work-up: BP, ACR, immunology (ANA, dsDNA, complement, ANCA, PLA2R), SPEP not first, US ± DMSA, MAG3 if obstruction, biopsy if kidneys normal-size and diagnosis missing.",
        "Renoprotection: BP <130/80 (KDIGO 120 systolic if tolerated in some), ACE-i/ARB if albuminuric (contraindicated if planning immediate pregnancy — switch to nifedipine/labetalol/methyldopa), SGLT2-i if diabetic or proteinuric CKD (evidence evolving in non-diabetic), statin if indicated, bicarbonate if HCO3 <22, phosphate/CKD-MBD, iron/ESA for anaemia, vaccinations, avoid NSAID/contrast/aminoglycoside.",
        "Pregnancy counselling is the stem’s point: Cr 3 / eGFR ~20 = high-risk. Fertility reduced, contraception until stable. Pregnancy risks: 30–50%+ chance of GFR loss, possible need for dialysis, preeclampsia, fetal growth restriction, preterm. Referral to obstetric-nephrology. ACE-i teratogenic (stop). Transplant is the best gift before pregnancy if G4–G5 — wait usually 1 year post-transplant with stable Cr <1.5 and immunosuppression compatible (azathioprine not MMF; switch MMF to AZA before conception). If she is already pregnant: multidisciplinary, BP, growth scans, dialysis if indicated (often 6×/week in pregnancy).",
        "RRT planning: vein preservation (no PICC in the non-dominant arm), education, living-donor work-up of spouse (newly married — handle sensitively), pre-emptive transplant preferred over dialysis.",
        "Urologic jobs: correct obstruction, reflux, stones, reconstruct bladder if valve/neurogenic, nephrectomy of chronically infected kidneys before transplant.",
      ]},
      { t: "h", v: "Anaemia of CKD — pathophysiology" },
      { t: "ul", v: [
        "EPO deficiency: peritubular fibroblast loss / HIF dysregulation as GFR falls (dominant from G3b–G4).",
        "Iron-restricted erythropoiesis: high hepcidin (inflammation, reduced clearance) → ferroportin down → impaired gut absorption and reticulo-endothelial trapping. Absolute iron deficiency from blood loss (HD circuit, GI, sampling).",
        "Shortened RBC survival (uraemic toxins, hyperparathyroidism marrow fibrosis, hypersplenism).",
        "B12/folate deficiency, aluminium (historical), ACE-i (rare), haemoglobinopathy unmasked.",
        "Result: normocytic normochromic anaemia; symptoms at higher Hb than in iron deficiency because of 2,3-DPG adaptation limits in CKD.",
      ]},
      { t: "h", v: "Management of anaemia" },
      { t: "ul", v: [
        "Investigate: CBC, MCV, ferritin, TSAT, CRP, B12, folate, occult blood, PTH. Target investigation of other causes if MCV abnormal or ferritin very high.",
        "Iron first: as in the iron/CKD master. Replete before / with ESA.",
        "ESA (epoetin alfa/beta, darbepoetin, CERA): start when Hb <10 g/dL after iron replete, individualise. Target Hb 10–11.5 g/dL; do NOT chase 13 — CHOIR/CREATE/TREAT showed more stroke/thrombosis. Increase dose slowly; ESA resistance = iron lack, inflammation, PTH, ACE-i, anti-EPO pure red cell aplasia (rare).",
        "HIF-PHI (roxadustat, daprodustat, vadadustat): oral; increase endogenous EPO and improve iron handling. Emerging alternative; CV safety still scrutinised.",
        "Transfusion: avoid if transplant candidate (HLA sensitisation) except symptomatic ischaemia. Use leucodepleted.",
        "Transplant / hypoxia at altitude not therapies; treat PTH and inflammation.",
      ]},
      { t: "tip", k: "gold", v: "CKD = >3 months of damage or eGFR <60; stage by G and A. Cr 3 in a 26-year-old is G4 — counsel pregnancy, list for pre-emptive transplant, hunt obstruction. Anaemia: iron then ESA, Hb ceiling 11.5." },
    ],
  },
  {
    id: "capd-peritonitis",
    topicId: "nephrology",
    title: "CAPD peritonitis — diagnosis and management",
    highYield: false,
    gold: false,
    tags: ["CAPD", "peritonitis", "dialysis", "ISP"],
    exams: [
      {
        session: "Jun",
        year: 2014,
        marks: "10",
        stem: "Describe the diagnosis and management of CAPD (Continuous Ambulatory Peritoneal Dialysis) peritonitis.",
      },
    ],
    related: ["ckd-classification-anaemia", "aki-arf-urology"],
    references: [
      "ISPD Peritonitis recommendations 2022",
      "Campbell — Dialysis access for urologists",
    ],
    answer: [
      { t: "p", v: "CAPD peritonitis is infection of the peritoneal dialysis cavity. It is the leading cause of technique failure. Urologists meet it when placing/revising Tenckhoff catheters, after urologic instrumentation (retrograde studies can seed the peritoneum via a patent processus / female tract — rare), or when acute abdomen is confused with surgical peritonitis." },
      { t: "h", v: "Diagnosis (ISPD)" },
      { t: "p", v: "At least two of: (1) clinical — abdominal pain, cloudy bag, fever; (2) effluent WBC >100/µL after dwell ≥2 h with >50% PMN; (3) positive effluent Gram stain or culture. Cloudy bag = peritonitis until proven otherwise." },
      { t: "ul", v: [
        "Send effluent: cell count/diff, Gram stain, culture of 50 mL (inoculate blood-culture bottles), fungal/AFB if indolent.",
        "Exit-site and tunnel exam (S. aureus, Pseudomonas). Ultrasound the tunnel.",
        "Differential: chemical peritonitis (icodextrin rare), eosinophilic (early after catheter), chylous, haemoperitoneum, surgical abdomen (free air is normal after recent catheter — not diagnostic of viscus perforation; look at lactate, localisation, pneumatosis).",
      ]},
      { t: "h", v: "Microbiology" },
      { t: "ul", v: [
        "Gram-positive ~60%: coagulase-negative staph (touch contamination), S. aureus (exit site), strep.",
        "Gram-negative ~20–30%: E. coli, Klebsiella, Pseudomonas (catheter removal often needed), bowel leak if polymicrobial / anaerobic.",
        "Culture-negative ~15%: prior antibiotics, fastidious organisms, mycobacteria, fungi.",
        "Fungal: Candida — remove catheter immediately.",
      ]},
      { t: "h", v: "Management" },
      { t: "ul", n: true, v: [
        "Do not wait for culture. Empiric intraperitoneal antibiotics covering Gram + and −: e.g. IP vancomycin (or cefazolin) PLUS IP ceftazidime or aminoglycoside, dosed per ISPD (continuous or once-daily in a long dwell). Adjust for residual GFR.",
        "Heparin in bags if fibrin. Pain, antipyretics. Continue PD if the patient is well; some centres rest the peritoneum.",
        "De-escalate at 72 h to culture. Duration typically 2 weeks (CoNS, strep) or 3 weeks (S. aureus, Gram-negatives, enterococcus).",
        "Adjunctive: exit-site mupirocin/gentamicin prophylaxis is prevention; for treatment, add oral/IP as per organism.",
        "Indications for catheter removal (and temporary HD): fungal; Pseudomonas/mycobacterial that fail; refractory (no improvement 5 days); relapsing (same organism within 4 weeks of completing Rx); refractory tunnel/exit-site; bowel perforation. Remove, antibiotics ≥2 weeks, reinsert later.",
        "Surgical abdomen / polymicrobial enteric: laparotomy/laparoscopy, source control — this is not ‘just CAPD peritonitis’.",
      ]},
      { t: "tip", k: "gold", v: "Cloudy bag + effluent WBC >100 with >50% PMN = treat IP now. Fungus or refractory Pseudomonas = take the tube out. Polymicrobial = look for a hole in viscus." },
    ],
  },
  {
    id: "adpkd",
    topicId: "nephrology",
    title: "ADPKD — features, genetics, management, nephrectomy indications",
    highYield: true,
    gold: true,
    tags: ["ADPKD", "PKD1", "PKD2", "tolvaptan", "nephrectomy"],
    exams: [
      { session: "Jun", year: 2021, marks: "5+5", stem: "What are the clinical features of ADPKD? What are the principles of management of this disease?" },
      {
        session: "Dec",
        year: 2021,
        marks: "5+3+2",
        stem: "List all the clinical features of Autosomal Dominant Polycystic Kidney Disease. What are the known genetic defects associated with ADPKD? List the indications for nephrectomy in ADPKD.",
      },
    ],
    related: ["bosniak-cysts", "ckd-classification-anaemia", "renal-trauma-imaging-embolization"],
    references: [
      "Campbell-Walsh-Wein — Cystic diseases of the kidney",
      "KDIGO ADPKD controversies / EAU",
      "TEMPO 3:4 / REPRISE — tolvaptan",
      "Pei–Ravine US criteria",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Features by organ 5 · PKD1/PKD2/GANAB/DNAJB11 3 · Management including tolvaptan and transplant 2 · Nephrectomy indications as a boxed list 2." },
      { t: "h", v: "Genetics" },
      { t: "tbl", h: ["Gene", "Protein", "~%", "Phenotype"], r: [
        ["PKD1 (16p13.3)", "Polycystin-1 (cilium / cell–cell)", "78–85%", "Larger kidneys, ESRD ~54 y"],
        ["PKD2 (4q22.1)", "Polycystin-2 (TRP Ca channel)", "15%", "Milder, ESRD ~74 y"],
        ["GANAB, DNAJB11, ALG9, IFT140 (atypical)", "Maturation / cilium", "Rare", "Atypical cystic, sometimes small kidneys (DNAJB11)"],
      ]},
      { t: "p", v: "Autosomal dominant, complete penetrance, variable expressivity. Two-hit (somatic second hit) in individual tubular cells. Polycystin complex on the primary cilium senses flow; loss → cAMP ↑ (vasopressin V2) → cyst proliferation and secretion. PKD1 truncating > PKD1 non-truncating > PKD2 (PROPKD score)." },
      { t: "h", v: "Clinical features — list all" },
      { t: "tbl", h: ["System", "Features"], r: [
        ["Renal", "Bilateral cysts, loin pain, haematuria (cyst haemorrhage), cyst infection (like pyelonephritis but often sterile midstream — need PET or cyst aspiration), stones (urate, CaOx), concentrating defect / nocturia, hypertension (early, renin from compressed ischaemic parenchyma), CKD → ESRD, cystadenocarcinoma rare (RCC risk slightly increased, often sarcomatoid/unusual histology)"],
        ["Liver / GI", "Polycystic liver (most common extra-renal; F>M, pregnancy/oestrogen), pancreatic / splenic / seminal-vesicle / arachnoid cysts, colonic diverticula (ESRD), hernia"],
        ["Vascular", "Intracranial berry aneurysm 8–12% (higher if family history of aneurysm/SAH) — screen MRA if FH or pre-transplant; aortic root dilatation, mitral valve prolapse"],
        ["Cardiac", "MVP, AR"],
        ["Other", "Abdominal fullness, early satiety, infertility (male cysts in seminal vesicles), pain syndromes"],
      ]},
      { t: "p", v: "Diagnosis: Pei–Ravine US criteria by age and number of cysts if positive family history; MRI/CT volume (Mayo imaging class 1C–1E rapid progressors). Genetics when imaging equivocal, donor evaluation, or reproductive planning." },
      { t: "h", v: "Principles of management" },
      { t: "ul", v: [
        "BP: target ≤110/75 in young with preserved GFR (HALT-PKD) using ACE-i/ARB.",
        "Hydration 3 L/d (suppress vasopressin), salt restriction, avoid oestrogen excess in massive PLD, caffeine uncertain.",
        "Tolvaptan (V2 antagonist): slows eGFR decline in Mayo 1C–E or PKD1 truncating rapid progressors (TEMPO, REPRISE). Hepatotoxicity — REMS LFTs. Thirst/polyuria expected. Not for everyone.",
        "Pain: exclude stone/infection/tumour; stepwise analgesia, cyst aspiration ± sclerosis, cyst fenestration, rarely nephrectomy.",
        "Cyst infection: lipid-soluble antibiotics (ciprofloxacin, co-trimoxazole, chloramphenicol) for 4–6 weeks; drain if large abscess.",
        "Stones: as for other stone formers; PCNL/RIRS tailored to distorted anatomy.",
        "CKD-MBD, anaemia, statin, avoid contact sport if massive kidneys.",
        "Screen ICA if family history of aneurysm or occupation (pilot) or before transplant.",
        "ESRD: pre-emptive transplant. Native nephrectomy if space, infection, tumour, or uncontrolled haemorrhage — often staged.",
      ]},
      { t: "h", v: "Indications for nephrectomy in ADPKD" },
      { t: "ul", v: [
        "Insufficient abdominal space for allograft (pre-transplant, usually the ipsilateral iliac fossa side).",
        "Recurrent or intractable cyst infection / pyonephrosis.",
        "Suspected or proven malignancy.",
        "Intractable pain after conservative measures.",
        "Persistent haemorrhage / recurrent gross haematuria requiring transfusion.",
        "Early satiety / malnutrition from mass effect, or respiratory compromise.",
        "Symptomatic stones not manageable endourologically in a non-functioning kidney.",
        "Rare: severe hypertension attributed to a destroyed kidney (after RAAS blockade).",
      ]},
      { t: "p", v: "Approach: laparoscopic/hand-assisted or open (huge kidneys). Drain cysts carefully (infection). Preserve the native ureter if the bladder is needed. Bilateral simultaneous vs staged — centre preference; simultaneous increases morbidity." },
      { t: "tip", k: "gold", v: "PKD1 is earlier ESRD than PKD2. cAMP/vasopressin is the drugable axis (tolvaptan). Nephrectomy is for space, sepsis, cancer, pain or bleeding — not for cysts per se." },
    ],
  },
  {
    id: "bosniak-cysts",
    topicId: "nephrology",
    title: "Bosniak classification of renal cysts and management",
    highYield: true,
    gold: true,
    tags: ["Bosniak", "cyst", "IIf", "III", "IV", "SRM"],
    exams: [
      { session: "Dec", year: 2018, marks: "10", stem: "Bosniak classification of renal cysts and their management." },
    ],
    related: ["adpkd", "srm-management", "renal-mass-biopsy", "benign-renal-tumors-oncocytoma"],
    references: [
      "Bosniak MA. Radiology 1986; update 2005; version 2019 (Silverman / Schieda)",
      "EAU RCC guidelines — cystic masses",
      "Campbell — Cystic diseases / Incidental renal mass",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Table of I–IV with wall, septa, calcification, enhancement, ~malignant % and action. Mention Bosniak 2019 (MRI included, IIF refined). Draw a 5-row cartoon." },
      { t: "h", v: "Purpose" },
      { t: "p", v: "CT (now also MRI) system to predict malignancy in cystic renal masses and to triage surgery vs observation. Requires a dedicated contrast-enhanced study (corticomedullary + nephrographic). Ultrasound with CEUS is an emerging adjunct, not the original Bosniak tool." },
      { t: "tbl", c: "Classic Bosniak (1986/2005) — still the exam backbone", h: ["Class", "Imaging", "Malignancy", "Management"], r: [
        ["I", "Hairline wall, homogeneous water HU (−20 to +20), no septa, no calc, no enhancement", "~0%", "Ignore. Reassure."],
        ["II", "Few hairline septa; fine calcification or short segment of slightly thickened Ca; hyperdense cyst ≤3 cm (60–90 HU), no enhancement, well marginated", "~0–5%", "Ignore. Hyperdense non-enhancing ≤3 cm is benign (haemorrhagic/proteinaceous)."],
        ["IIF (F = follow)", "Multiple hairline septa; minimal smooth thickening of wall/septa that may enhance perceived; thick or nodular Ca; hyperdense >3 cm or totally intrarenal; no measurable enhancement of soft tissue", "~5–10% (modern series up to 10–15%)", "Surveillance CECT/MRI at 6–12 months then annually × 5 y. Intervene if upgrade (nodule, measurable enhancement)."],
        ["III", "Thick irregular or smooth walls/septa with measurable enhancement. No frank nodule of IV. Includes multilocular cystic neoplasm, mixed epithelial stromal tumour, cystic RCC, abscess, TB, localised cystic disease", "~50% (30–60%)", "Nephron-sparing surgery / ablation / (increasingly) biopsy or active surveillance in comorbid. Discuss 50:50 with patient."],
        ["IV", "Criteria of III plus enhancing soft-tissue nodule independent of wall/septum (mural nodule)", "~90–100%", "Treat as solid RCC: PN preferred if feasible; RN if not; ablation/AS if SRM and frail."],
      ]},
      { t: "h", v: "Bosniak v2019 pearls (quote for extra marks)" },
      { t: "ul", v: [
        "Defined well-defined vs well-circumscribed; uses MRI equally.",
        "Enhancement: clearly enhancing ≥20 HU (CT) or unequivocal MRI enhancement; 10–20 HU is ‘perceived’.",
        "IIF if many septa or ‘minimally thickened’ enhancing septa; III if thick (≥4 mm) enhancing wall/septa or irregular (≤3 mm obtuse protrusions); IV if enhancing nodule ≥4 mm with acute angles.",
        "Goal: move some III into IIF to reduce overtreatment of indolent cystic neoplasms (multilocular cystic renal neoplasm of low malignant potential).",
      ]},
      { t: "h", v: "Pitfalls" },
      { t: "ul", v: [
        "Infection (abscess, TB, hydatid) and haemorrhage mimic III–IV — clinical context, diffusion MRI, follow-up after antibiotics.",
        "Pseudoenhancement of small intra-renal cysts (beam hardening) — MRI or dual-energy CT.",
        "ADPKD cysts are Bosniak I/II; a dominant atypical cyst still needs Bosniak logic (RCC can occur).",
        "Do not Bosniak-classify solid masses or the dilated pelvicalyceal system.",
      ]},
      { t: "tip", k: "gold", v: "I–II ignore, IIF follow, III discuss (half malignant), IV operate. The 2019 update exists to stop us operating on every thickened septum." },
    ],
  },
];
