import type { Master } from "../types";

export const paediatric: Master[] = [
  {
    id: "fetal-hydronephrosis",
    topicId: "paediatric",
    title: "Antenatal hydronephrosis — postnatal protocol and fetal intervention",
    highYield: true,
    gold: true,
    tags: ["ANH", "SFU", "UTD", "PUJO", "LUTO", "vesicoamniotic shunt"],
    exams: [
      { session: "Jun", year: 2019, marks: "6+4", stem: "Outline management of foetal hydronephrosis. Mention indications for foetal intervention indicating outcome of such interventions." },
      { session: "Dec", year: 2019, marks: "5+5", stem: "Antenatally detected hydronephrosis — post-natal follow-up protocol and indications for surgical intervention." },
      { session: "Jun", year: 2014, marks: "10", stem: "How would you investigate a newborn diagnosed to have hydronephrosis on antenatal ultrasonography?" },
      { session: "Dec", year: 2011, marks: "5+5", stem: "Define an algorithm for evaluation of antenatally detected hydronephrosis bilateral in a male fetus. What is the current role of pre-natal surgical intervention in such fetuses?" },
    ],
    related: ["puv-valve-bladder", "pyeloplasty-types", "vur", "radionuclides-renogram"],
    references: [
      "Campbell-Walsh-Wein 12e, Pediatric urinary obstruction / ANH",
      "EAU / ESPU Paediatric Urology; SFU and UTD classification papers",
      "PLUTO trial — vesicoamniotic shunt (Lancet 2013)",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "Definition/grading 2 · Unilateral vs bilateral male fetus algorithm 3 · Postnatal imaging timeline 2 · Who operates 2 · Fetal intervention + PLUTO honesty 1." },
      { t: "h", v: "Definition and grading" },
      { t: "p", v: "Antenatal hydronephrosis (ANH) is dilatation of the fetal renal pelvis, reported in 1–2% of pregnancies. Measure APD (antero-posterior pelvic diameter) in the transverse plane plus calyceal/cortical/ureter/bladder/amniotic context. Isolated mild APD often resolves; the work-up is about not missing PUJO, PUV, VUR, megaureter and duplex obstruction." },
      { t: "tbl", c: "Thresholds commonly quoted", h: ["", "2nd trimester APD", "3rd trimester APD"], r: [
        ["Mild", "4–7 mm", "7–9 mm"],
        ["Moderate", "7–10 mm", "9–15 mm"],
        ["Severe", ">10 mm", ">15 mm"],
      ]},
      { t: "p", v: "SFU I–IV (pelvis only → dilated calyces → cortical thinning). UTD (urinary tract dilatation) A (antenatal) and P (postnatal) 1–3 incorporates ureter, bladder, parenchyma and amniotic fluid — preferred in contemporary answers." },
      { t: "h", v: "Bilateral HN in a male fetus (Dec 11 algorithm)" },
      { t: "flow", title: "Male fetus, bilateral hydronephrosis", nodes: [
        { id: "a", kind: "start", label: "Confirm on specialist US: APD, ureters, bladder wall/keyhole, liquor, sex, kidneys", to: ["b"] },
        { id: "b", kind: "decision", label: "Keyhole bladder + thick wall + oligohydramnios = LUTO (PUV >> prune belly, urethral atresia)?", to: ["c", "d"] },
        { id: "c", kind: "warn", label: "Counsel pulmonary hypoplasia / dysplasia. Karyotype. Vesicocentesis electrolytes. Fetal medicine review.", to: ["e"] },
        { id: "d", kind: "action", label: "No LUTO picture: bilateral PUJO / VUR / duplex. Serial US, deliver at centre, postnatal protocol.", to: ["f"] },
        { id: "e", kind: "decision", label: "Selected LUTO: vesicoamniotic shunt / fetal cystoscopy vs expectant?", to: ["f"] },
        { id: "f", kind: "end", label: "Neonatal: ABC, catheter, Cr, US after 48 h, VCUG if PUV suspected" },
      ]},
      { t: "h", v: "Postnatal follow-up protocol" },
      { t: "ul", v: [
        "Do NOT rely on a US in the first 48 h for mild unilateral disease — physiologic oliguria underestimates dilatation. Exception: bilateral, solitary kidney, oligohydramnios, suspected PUV — image immediately, catheterise, check Cr at 24–48 h.",
        "Day 2–7 (or 1–4 weeks if mild): US. If HN resolved and was mild isolated, some protocols stop; many still repeat at 6–12 weeks.",
        "CAP (amoxicillin 12–15 mg/kg nocte or cephalexin) while awaiting VCUG in high-risk (bilateral, ureter dilatation, bladder abnormality, SFU III–IV, girls with high-grade) — EAU individualises; do not CAP every SFU I boy.",
        "VCUG: suspected PUV (all bilateral male with ureter/bladder issues), dilated ureter, duplex with dilatation, breakthrough UTI, before considering pyeloplasty in infants if VUR not excluded. Not mandatory in isolated unilateral pelvic dilatation with normal ureter/bladder (risk of VUR is real but often low-grade).",
        "MAG3 (after 6–8 weeks when tubular function matures; earlier only if needed): split function and drainage in SFU III–IV / worsening APD. DMSA if scarring / pyelo.",
        "MCU/VCUG + MAG3 sequence is the classic postnatal pair for significant ANH.",
      ]},
      { t: "h", v: "Indications for postnatal surgery" },
      { t: "ul", v: [
        "PUV: early ablation once the neonate is stable (and a small cystoscope can be passed) — this is obstruction, not ‘ANH observation’.",
        "PUJO: split function <35–40% or falling >5–10%, increasing APD/SFU grade, symptoms (UTI, pain, stones), palpable mass, pyonephrosis. Observe SFU II with good function — 70%+ of mild–moderate ANH resolve.",
        "Obstructed megaureter: similar function/UTI/APD rules; temporise with stent/refluxing reimplant / cutaneous ureterostomy in small infants if needed, definitive reimplant later.",
        "Duplex: upper-moiety obstruction (ectopic/ureterocoele) — puncture ureterocoele if infected/obstructed; later reconstruction.",
      ]},
      { t: "h", v: "Fetal intervention — indications and outcomes" },
      { t: "p", v: "The only remotely established target is LUTO with oligohydramnios, ‘favourable’ fetal urine (Na <100 mEq/L, Cl <90, osmolality <200, β2-microglobulin low — serial taps), normal karyotype, and no fatal extra-renal anomaly, aiming to restore liquor for lung growth. Tools: vesicoamniotic shunt (VAS), fetal cystoscopy ± valve ablation, rarely vesicostomy. Open fetal surgery is historical." },
      { t: "ul", v: [
        "PLUTO RCT (2013): VAS vs conservative — underpowered, did not show a clear survival-with-normal-renal-function benefit; shunts dislodge, migrate, cause membrane damage, chorioamnionitis, preterm labour.",
        "Observational series: survival may improve vs historical oligohydramnios controls, but CKD/ESRD remain common because renal dysplasia is already programmed.",
        "Unilateral HN, isolated PUJO, and normal liquor: NEVER shunt. Maternal risk for unproven fetal renal benefit is unethical.",
        "Counsel: intervention is experimental, for lung not for guaranteed kidneys, at a fetal-medicine centre.",
      ]},
      { t: "tip", k: "gold", v: "Bilateral + male + thick bladder + oligo = PUV until proven otherwise. Mild unilateral ANH = delayed US and restraint. Fetal shunt is a lung procedure with disappointing kidneys (PLUTO)." },
    ],
  },
  {
    id: "puv-valve-bladder",
    topicId: "paediatric",
    title: "Posterior urethral valves and valve bladder",
    highYield: true,
    gold: true,
    tags: ["PUV", "Young", "valve bladder", "CKD", "POP"],
    exams: [
      { session: "Dec", year: 2022, marks: "3+7", stem: "A 12-year-old male with PUV ablation at 4 years, currently asymptomatic, S. creatinine 1.5 mg% with bilateral HUN: enumerate possible reasons for his CKD; how will you approach management." },
      { session: "June", year: 2022, marks: "7+3", stem: "Discuss the etiopathogenesis, evaluation and management of a newborn infant with posterior urethral valve. Discuss in brief Valve Bladder syndrome and its management." },
      { session: "Jun", year: 2016, marks: "3+3+4", stem: "Classification, pathophysiology and management of PUV." },
      { session: "Dec", year: 2020, marks: "3+3+4", stem: "Define PUV and its types. What is valve bladder syndrome and describe its management." },
      { session: "Dec", year: 2018, marks: "2+8", stem: "Posterior urethral valve — Classification and management of valve bladder syndrome." },
      { session: "Dec", year: 2016, marks: "5+5", stem: "What could be the cause of deteriorating renal function in a case of posterior urethral valve following fulguration of valve? Outline its management." },
    ],
    related: ["fetal-hydronephrosis", "vur", "spina-bifida-mmc", "urodynamics-uroflow"],
    references: [
      "Campbell-Walsh-Wein 12e, Posterior urethral valves",
      "EAU / ESPU Paediatric Urology — PUV",
      "Koff / Duckett / Glassberg — valve bladder; Young's classification",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "Young types 1 · Fetal/neonatal Rx 3 · Valve bladder physiology 3 · The 12-year-old CKD list 2 · UDS-driven management 1. Draw the keyhole urethra." },
      { t: "h", v: "Definition and classification" },
      { t: "p", v: "PUV are congenital membranous folds in the male posterior urethra causing infra-vesical obstruction from fetal life. Incidence ~1/5000–8000 boys. Young (1919): Type I — sails from veru distally to the membranous urethra (95%, the real disease); Type II — folds from veru to bladder neck (not obstructive, probably hypertrophy); Type III — a diaphragm/iris distal to veru (rare; some are Cobb's collar / syringocoele). Dewan: congenital obstructive posterior urethral membrane (COPUM) as a single entity viewed endoscopically as a membrane with a posterior pinhole." },
      { t: "h", v: "Pathophysiology" },
      { t: "ul", v: [
        "Fetal BOO → high-pressure bladder → hydroureteronephrosis, VUR (often pop-off, worse on one side), renal dysplasia (the main determinant of ESRD), oligohydramnios → pulmonary hypoplasia (Potter sequence in the severe end).",
        "Pop-off mechanisms that spare the contralateral kidney: unilateral VUR (VURD syndrome), urinoma, ascites, large bladder diverticulum — mention in the 12-year-old if one kidney is better.",
        "After ablation, obstruction is gone but the bladder may remain a high-pressure, poorly compliant, overactive then later decompensated reservoir with polyuria from concentrating failure — valve bladder.",
      ]},
      { t: "h", v: "Newborn — evaluation and management" },
      { t: "ul", n: true, v: [
        "ABC; treat pulmonary issues first. Immediate 5–8 F feeding tube (avoid balloon in urethra). If it will not pass, SPC.",
        "Labs: Cr (nadir over days–weeks is prognostic), electrolytes, VBG, culture.",
        "US: thick bladder, keyhole, HUN, dysplasia, urinoma. VCUG when stable: dilated posterior urethra, valve leaflet, trabeculation, VUR, diverticula — diagnostic.",
        "Stabilise: fluids, correct hyperK/acidosis, antibiotics if infected, nephrology.",
        "Primary valve ablation (cold knife / Bugbee / holmium / resectoscope hook) once the urethra accepts an 8–9 F instrument. If too small or septic/unstable: vesicostomy (Blocksom) as a bridge, not high diversion first-line.",
        "Circumcision reduces UTI. Post-ablation VCUG to confirm interruption of the membrane. MAG3/DMSA later for split function/scars.",
        "High diversion (ureterostomy, pyelostomy) only for persistent obstruction/infection despite a draining bladder — rare in the primary-ablation era.",
      ]},
      { t: "h", v: "Valve bladder syndrome" },
      { t: "p", v: "A post-ablation bladder that continues to threaten the kidneys. Koff: a triad of (1) polyuria (tubular concentrating defect — overnight urine can refill a ‘empty’ system), (2) persistently high storage pressure / hypocompliance and/or DO, (3) residual urine. Over years: myogenic failure, large floppy bladder, overflow, CKD progression. Glassberg stages the bladder from hypertonic to decompensated." },
      { t: "ul", v: [
        "Evaluate: diary including night volumes, US (upper tracts + PVR), VCUG/RGU for residual valve/stricture, MAG3, video-UDS (the key test), Cr/eGFR, BP, proteinuria.",
        "Management: timed voiding + double void; nocturnal bladder emptying (CIC at bedtime ± overnight catheter or alarm) because polyuria fills against a closed sphincter all night; anticholinergic / β3 for DO; CIC if PVR/high pressure; CAP if recurrent UTI; treat constipation.",
        "Failed medical: overnight drainage, then augmentation cystoplasty ± Mitrofanoff when compliance unsafe despite CIC/drugs; rarely undiversion of old ureterostomies. Transplant into a safe bladder only.",
        "Residual anatomical obstruction: re-look cystoscopy (stricture, residual valve, bladder-neck hypertrophy — incision of bladder neck is controversial, not routine).",
      ]},
      { t: "h", v: "12-year-old after ablation, Cr 1.5, silent bilateral HUN — causes of CKD" },
      { t: "ul", v: [
        "Primary renal dysplasia (programmed in utero) — the most honest cause even with a perfect ablation.",
        "Residual or recurrent obstruction: incomplete ablation, stricture, bladder-neck hypertrophy.",
        "Valve bladder: unsafe storage pressures, chronic residual, nocturnal high pressure.",
        "Persistent VUR + recurrent pyelonephritis / scarring.",
        "Polyuria stretching the system overnight.",
        "Hypertension, proteinuria (hyperfiltration of remnant nephrons), nephrotoxic drugs.",
        "Urolithiasis, obstruction from a full bladder (the boy who ‘never voids at night’).",
      ]},
      { t: "h", v: "Approach to that 12-year-old" },
      { t: "flow", title: "Late PUV with CKD", nodes: [
        { id: "a", kind: "start", label: "History: voiding, night-time output, UTI, BP meds. Exam: BP, palpable bladder, growth", to: ["b"] },
        { id: "b", kind: "action", label: "Labs: Cr, cystatin, HCO3, urine PCR, culture. US + PVR. Uroflow.", to: ["c"] },
        { id: "c", kind: "action", label: "VCUG / cystoscopy (residual valve, stricture). MAG3. Video-UDS.", to: ["d"] },
        { id: "d", kind: "decision", label: "Unsafe storage or residual BOO?", to: ["e", "f"] },
        { id: "e", kind: "action", label: "Relieve BOO; CIC + anticholinergic ± nocturnal drainage; nephrology ACEI", to: ["g"] },
        { id: "f", kind: "action", label: "Safe bladder + dysplasia only: nephrology CKD care, observe upper tracts", to: ["g"] },
        { id: "g", kind: "end", label: "Augment if still high pressure; transplant later into a protected reservoir" },
      ]},
      { t: "tip", k: "gold", v: "Ablating the valve is the easy day. The kidney’s fate is dysplasia plus overnight bladder pressure. Nadir creatinine in the first year is the best classic prognostic (nadir <0.8–1.0 mg/dL more favourable)." },
    ],
  },
  {
    id: "vur",
    topicId: "paediatric",
    title: "VUR — UVJ anatomy, scarring, grades and management",
    highYield: true,
    gold: true,
    tags: ["VUR", "IRSC", "STING", "Cohen", "RIVUR", "reflux nephropathy"],
    exams: [
      { session: "Dec", year: 2019, marks: "3+2+5", stem: "Discuss pathophysiology of renal scarring in primary VUR. Define grades of reflux in VCUG. Discuss management of grade V primary VUR in infant." },
      { session: "Jun", year: 2019, marks: "5+5", stem: "Anatomy of vesico-ureteral junction indicating its surgical importance. Describe and illustrate various grades of VUR along with schematic diagrams." },
      { session: "Jun", year: 2014, marks: "6+4", stem: "Describe the pathophysiology of VUR. Outline the management of VUR Grade IV in a 4 year old boy." },
      { session: "Dec", year: 2015, marks: "10", stem: "Use of various non autologous materials for management of vesico-ureteric reflux in children." },
    ],
    related: ["puv-valve-bladder", "fetal-hydronephrosis", "spina-bifida-mmc"],
    references: [
      "Campbell-Walsh-Wein 12e, Vesicoureteral reflux",
      "EAU / ESPU / AUA VUR guidelines; RIVUR trial; UK PREDICT",
      "O'Donnell / Puri STING; Cohen / Politano-Leadbetter / Lich-Gregoir",
    ],
    answer: [
      { t: "h", v: "UVJ anatomy and surgical importance" },
      { t: "p", v: "The anti-reflux mechanism is a passive flap-valve: the ureter tunnels obliquely through the bladder wall (intramural + submucosal segments) so that rising detrusor pressure coapts the roof against the trigone. Paquin’s rule: tunnel length : ureteric diameter ≈ 5:1. Waldeyer’s sheath (adventitia blending with detrusor) and the trigonal muscle of Bell fix the ureter. Distal ureter is supplied by a descending branch from the superior vesical — preserve peri-ureteric tissue in reimplants." },
      { t: "ul", v: [
        "Primary VUR: short tunnel, lateral ectopic orifice, duplex (upper moiety obstructs, lower moiety refluxes — Weigert–Meyer).",
        "Secondary: PUV, NGB, BOO, iatrogenic (hockey-stick ureter after Burch, para-ureteric diverticulum / Hutch).",
        "Surgical implication: lengthen the tunnel (Cohen cross-trigonal, Politano-Leadbetter, Lich-Gregoir extra-vesical, Glenn-Anderson), or bulk the orifice (STING). Do not reimplant a ureter into an unsafe high-pressure bladder — fix the bladder first.",
      ]},
      { t: "h", v: "IRSC / International grades on VCUG (draw five cartoons)" },
      { t: "tbl", h: ["Grade", "Description"], r: [
        ["I", "Ureter only"],
        ["II", "Ureter + pelvis + calyces; no dilatation; fornices sharp"],
        ["III", "Mild–moderate dilatation and blunting of fornices; no (or slight) forniceal clubbing"],
        ["IV", "Moderate dilatation, blunted angles, but most papillae still visible"],
        ["V", "Gross dilatation and tortuosity; papillary impressions lost; intra-renal reflux"],
      ]},
      { t: "h", v: "Pathophysiology of scarring (reflux nephropathy)" },
      { t: "ul", v: [
        "Not hydrostatic reflux of sterile urine alone in most children — the driver is infected urine reaching the parenchyma (pyelonephritis) via intra-renal reflux into compound papillae (polar).",
        "Bacterial adhesion (P-fimbriae), cytokines (IL-6, IL-8), complement, ischaemia of swollen papilla → interstitial nephritis → Tamm–Horsfall extravasation → focal segmental scars, overlying calyceal clubbing (Ask-Upmark analogue), renin-mediated hypertension, later hyperfiltration CKD if bilateral.",
        "Congenital dysplasia associated with high-grade fetal VUR can look like ‘scar’ on DMSA without a postnatal UTI — important in infants with grade V.",
        "Sterile high-pressure reflux (NGB, PUV) can scar without bacteria — the exception that proves the pressure rule.",
      ]},
      { t: "h", v: "Management — general principles" },
      { t: "p", v: "Goal is to prevent pyelonephritis and new scars, not to ‘cure a radiograph’. Spontaneous resolution is common (I–II > III > IV; rare in V; better if ureter not dilated, younger, male, prenatal presentation)." },
      { t: "ul", v: [
        "Everyone: treat constipation, dysfunctional voiding (urotherapy, biofeedback), circumcision discussion in boys with breakthrough UTI, culture-led Rx of UTI, BP and proteinuria surveillance.",
        "CAP: RIVUR showed TMP-SMX halves recurrence but with resistance and no scar reduction in the whole cohort. Use CAP in infants with high-grade VUR, recurrent febrile UTI, until toilet-trained / after surgical correction. Do not CAP forever in a well toilet-trained child with grade II.",
        "DMSA: for scarring / function, not required in every first UTI (NICE vs AUA — know the controversy; for grade IV–V do it).",
      ]},
      { t: "h", v: "Grade V in an infant" },
      { t: "ul", v: [
        "Exclude secondary VUR (VCUG already shows valves? UDS if NGB suspected). US for dysplasia, ureter, contralateral kidney.",
        "CAP + circumcision + aggressive UTI treatment. Many units observe the first year because reimplant on a 4 mm ureter in a 4 kg infant is hostile, and some high-grade infant VUR improves after maturation / after PUV ablation.",
        "Intervene earlier if breakthrough febrile UTI on CAP, progressive renal damage, parental preference after counselling, or associated obstruction.",
        "Infant options: STING (Deflux) even in grade V has lower success (~50–60% vs 80–90% in II–III) but is a bridge; vesicostomy if unsafe bladder; delayed Cohen/Leadbetter after 12 months / 10 kg. Extra-vesical reimplant of a megaureter risks retention if bilateral (neural plexus).",
      ]},
      { t: "h", v: "Grade IV in a 4-year-old boy" },
      { t: "ul", v: [
        "History of toilet training, constipation, uroflow + PVR. Treat BBD first — surgery fails if the child voids against a sphincter.",
        "If BBD addressed and still febrile UTI or persistent high-grade: offer endoscopic (1–2 Deflux) or open/lap/robot reimplant (success >95%). Both acceptable; endoscopic less morbid, may need repeat; open definitive.",
        "Asymptomatic persistent IV with normal DMSA after a single infant UTI: shared decision — observation off CAP is used in some EAU pathways.",
      ]},
      { t: "h", v: "Non-autologous bulking materials (Dec 15)" },
      { t: "tbl", h: ["Material", "Note"], r: [
        ["PTFE paste (Teflon) — historical Puri–O'Donnell", "Migration to nodes/lung/brain in animals; abandoned in children"],
        ["Bovine collagen (Contigen)", "Allergy testing; resorption; poor durability"],
        ["Silicone microimplants (Macroplastique)", "Stable; migration concerns lower; still used in some adult SUI/VUR"],
        ["Dextranomer/hyaluronic acid (Deflux) — current standard", "Biocompatible, mound visible on US/CT (do not call it a stone); 1–3 mL STING or HIT/double-HIT; mound calcification years later"],
        ["Polyacrylate polyalcohol (Vantris)", "Higher success in some series; obstruction risk slightly higher"],
        ["Carbon-coated beads (Durasphere)", "Limited paediatric VUR use"],
        ["Autologous (fat, chondrocytes, muscle) / stem cells", "Experimental; mention as contrast to ‘non-autologous’"],
      ]},
      { t: "p", v: "STING: submucosal injection at 6 o’clock until the orifice is a mountain with a slit. HIT: intra-ureteric. Success falls with grade, duplex, neuropathic bladder, and after failed surgery. Obstruction is rare (<1%) but real — always check post-op US." },
      { t: "tip", k: "gold", v: "Reflux plus infection plus intra-renal reflux scars kidneys. Reimplant a safe bladder. Deflux is the non-autologous agent to name; Teflon is the historical cautionary tale." },
    ],
  },
  {
    id: "dsd-ambiguous",
    topicId: "paediatric",
    title: "Newborn with ambiguous genitalia",
    highYield: true,
    gold: false,
    tags: ["DSD", "CAH", "Prader", "17-OHP", "gender"],
    exams: [
      { session: "Dec", year: 2015, marks: "5+5", stem: "Outline the evaluation and management of a newborn with ambiguous genitalia." },
    ],
    related: ["undescended-testes", "hypospadias-adult"],
    references: [
      "Campbell-Walsh-Wein 12e, Disorders of sexual development",
      "Chicago DSD consensus 2006; Endocrine Society CAH guideline",
      "EAU / ESPU Paediatric Urology",
    ],
    answer: [
      { t: "p", v: "A neonate with ambiguous genitalia is a medical and psychosocial emergency: salt-losing CAH can kill in week 1–2, and hasty sex assignment damages families. Use DSD language (46,XX DSD; 46,XY DSD; ovotesticular; sex-chromosome DSD), not obsolete hermaphrodite terms." },
      { t: "h", v: "Who is ‘ambiguous’" },
      { t: "ul", v: ["Bilateral non-palpable gonads in a ‘male’", "Unilateral undescended gonad + hypospadias", "Severe hypospadias with bifid scrotum", "Clitoromegaly / fused labia / posterior labial fusion in a ‘female’", "Discordant phenotype vs prenatal karyotype"] },
      { t: "h", v: "Immediate evaluation" },
      { t: "ul", n: true, v: [
        "History: consanguinity, family neonatal deaths, maternal androgens/drugs, prenatal US.",
        "Exam: Prader stage, phallic length, orifices (one vs two), pigmentation (CAH), gonads palpable in inguinal/labioscrotal folds (if a gonad is palpable it is almost never an ovary — 46,XY or ovotesticular). Look for Turner/Klinefelter stigmata.",
        "Life: electrolytes, glucose from day 2–3 onward until CAH excluded. 17-hydroxyprogesterone (after 48 h, not cord blood), renin/aldosterone, testosterone, LH/FSH, AMH, karyotype (urgent FISH SRY + full karyotype).",
        "Imaging: pelvic US for uterus/Müllerian structures (the single most useful imaging), adrenal size; genitogram / EUA later; MRI rarely in newborn.",
        "Multidisciplinary: neonatology, paediatric endocrinology, urology, genetics, psychology, ethics. Do not print ‘boy’ or ‘girl’ on the cot until the team and parents decide.",
      ]},
      { t: "tbl", h: ["Category", "Classic example", "Keys"], r: [
        ["46,XX DSD", "CAH 21-hydroxylase deficiency (90% of ambiguous XX)", "Salt loss, high 17-OHP, uterus present, virilised Prader 1–5"],
        ["46,XY DSD", "PAIS, 5α-reductase, testosterone biosynthesis, gonadal dysgenesis", "Palpable gonads, no uterus (AMH present if testes)"],
        ["Ovotesticular", "46,XX often", "Both ovarian + testicular tissue"],
        ["Sex chromosome", "45,X/46,XY mixed gonadal dysgenesis", "Streak + testis; tumour risk"],
      ]},
      { t: "h", v: "Management" },
      { t: "ul", v: [
        "CAH: hydrocortisone + fludrocortisone + salt; crisis = IV hydrocortisone. This is the first night’s work.",
        "Gender assignment: 46,XX CAH almost always female (fertility, uterus). 46,XY is individualised (phallic size, androgen receptor, 5α-reductase — many virilise at puberty). Chicago consensus + local law (India: multidisciplinary, parental involvement, avoid non-essential irreversible surgery in infancy when possible — evolving ethics).",
        "Surgery (timing controversial): feminising genitoplasty (clitoroplasty, vaginoplasty) in CAH historically in infancy; current trend is to defer purely cosmetic steps. Male reconstruction: hypospadias + orchidopexy. Streak gonads in 45,X/46,XY: remove because gonadoblastoma risk.",
        "Long-term: transition, fertility, tumour surveillance, psychosexual care. Document steroid emergency plan.",
      ]},
      { t: "tip", k: "warn", v: "A ‘boy’ with bilateral non-palpable gonads is CAH until electrolytes and 17-OHP say otherwise. Do not discharge on day 2." },
    ],
  },
  {
    id: "undescended-testes",
    topicId: "paediatric",
    title: "Undescended testes — embryology, complications, management",
    highYield: true,
    gold: false,
    tags: ["UDT", "cryptorchidism", "INSL3", "orchidopexy", "GCNIS"],
    exams: [
      { session: "Jun", year: 2014, marks: "5+2+3", stem: "Describe the embryological basis of undescended testes. What are the complications of undescended testes and how would you manage them?" },
    ],
    related: ["dsd-ambiguous", "hypospadias-adult"],
    references: [
      "Campbell-Walsh-Wein 12e, Cryptorchidism",
      "EAU / ESPU UDT guideline; AUA cryptorchidism",
      "Hutson embryology reviews",
    ],
    answer: [
      { t: "h", v: "Embryological basis" },
      { t: "p", v: "The testis forms on the genital ridge and must travel from the abdomen to the scrotum in two phases. Failure of either phase, of the gubernaculum, of hormonal signalling, or of the processus vaginalis explains UDT (~1% at 1 year; higher in preterms)." },
      { t: "ul", n: true, v: [
        "Transabdominal phase (10–15 weeks): INSL3 from Leydig cells acts on RXFP2 in the gubernaculum → gubernacular swelling reaction holds the testis near the internal ring as the abdomen grows. Cranial suspensory ligament regresses under androgen. Failure → intra-abdominal testis.",
        "Inguinoscrotal phase (25–35 weeks): androgen-dependent, genitofemoral nerve and CGRP-mediated gubernacular migration into the scrotum; processus vaginalis provides a peritoneal diverticulum. Failure → inguinal / high scrotal / ectopic (perineal, femoral, prepenile, crossed) testis.",
        "Acquired / ascending testis: after a normally descended neonatal exam, the testis ‘ascends’ as the spermatic cord fails to elongate with growth — often a persistent processus. Important because a single neonatal exam is not lifelong clearance.",
        "Retractile testis is not UDT: reaches scrotum and stays; cremasteric; observe.",
      ]},
      { t: "h", v: "Complications" },
      { t: "tbl", h: ["Complication", "Note / management"], r: [
        ["Infertility / subfertility", "Bilateral > unilateral; germ-cell loss after 6–12 months. Early orchidopexy is the mitigation, not a guarantee. Adult azoospermia work-up if bilateral delayed."],
        ["Malignancy (GCNIS → seminoma/nonseminoma)", "Relative risk ~3–8×; orchidopexy does not abolish risk but places the testis where self-exam is possible. Adult intra-abdominal missed testis: orchiectomy if atrophic."],
        ["Torsion", "Gubernacular attachment abnormal — treat as any torsion; higher index of suspicion"],
        ["Trauma", "Inguinal testis against pubis"],
        ["Inguinal hernia", "Patent processus — herniotomy at orchidopexy"],
        ["Psychological / empty scrotum", "Implant in adults after orchiectomy if desired"],
        ["Associated DSD / endocrine", "Bilateral non-palpable — exclude CAH (see DSD master)"],
      ]},
      { t: "h", v: "Management of UDT itself" },
      { t: "ul", v: [
        "Palpable: scrotal (Bianchi) or inguinal orchidopexy at 6–18 months (EAU: 6–12; do not wait till school age). Fix in a dartos pouch. Ligate processus.",
        "Non-palpable: diagnostic laparoscopy (gold). Blind-ending vessels = vanishing testis (remove nubbin if present for GCNIS risk small but traditional). Intra-abdominal: one-stage Fowler–Stephens vs two-stage (ligate spermatic vessels, wait 6 months, then bring on vas/gubernacular collaterals) vs primary orchidopexy if close to ring. Never close without seeing vessels.",
        "Hormonal (hCG/GnRH) not recommended as primary therapy (EAU).",
        "Post-pubertal unilateral atrophic inguinal: orchiectomy. Healthy late-presenting: orchidopexy still for exam access after counselling tumour risk.",
      ]},
      { t: "tip", k: "gold", v: "Two phases: INSL3 transabdominal, androgen inguinoscrotal. Operate at 6–18 months. Bilateral non-palpable newborn = DSD work-up, not ‘book laparoscopy in a year’ without electrolytes." },
    ],
  },
  {
    id: "hypospadias-adult",
    topicId: "paediatric",
    title: "Adult mid-penile hypospadias with chordee",
    highYield: true,
    gold: false,
    tags: ["hypospadias", "chordee", "Bracka", "BMG", "TIP"],
    exams: [
      { session: "Dec", year: 2022, marks: "5+5", stem: "Evaluation of a 23-year male with mid-penile hypospadias. Surgical options for correction of mid-penile hypospadias with chordee." },
    ],
    related: ["undescended-testes", "dsd-ambiguous", "rgu"],
    references: [
      "Campbell-Walsh-Wein 12e, Hypospadias",
      "Hinman Atlas; Bracka two-stage; Snodgrass TIP",
      "EAU Urethral strictures / Paediatric hypospadias",
    ],
    answer: [
      { t: "h", v: "Evaluation of a 23-year-old" },
      { t: "p", v: "Adult untreated or cripple hypospadias is not a paediatric TIP on a big penis. Assess urinary function, sexual function, fertility, and previous surgery (skin-hungry, hairy urethra, chordee, BXO)." },
      { t: "ul", v: [
        "History: spraying, stream, UTI, ejaculation (deposition in vagina), pain on erection, prior repairs/fistulae, circumcision status, BXO symptoms.",
        "Exam: meatal position (mid-penile), quality of urethral plate, penile skin, dartos, prepuce, glans groove, chordee (artificial erection in theatre is definitive; clinic photos), testes/UDT, scrotal transposition, prostate/DRE if LUTS.",
        "Investigations: uroflow + PVR (plateau suggests stricture), RGU ± MCU if previous surgery or obstructive flow, UA, semen analysis if fertility is the complaint, testosterone if micropenis/DSD features. Cystoscopy at surgery.",
        "Counsel: staged surgery likely, semen deposition, residual curvature, fistula 10–20%, stricture, need for BMG, no surgery is an option if voiding sitting and sex is satisfactory.",
      ]},
      { t: "h", v: "Surgical options — mid-penile + chordee" },
      { t: "p", v: "Sequence: straighten then reconstruct urethra. Never tubularise over residual ventral curvature." },
      { t: "ul", n: true, v: [
        "Artificial erection (Gittes). Deglove. Divide urethral plate if it tethers (it often does in mid-penile chordee).",
        "Chordee correction: ventral dartos/plate release; corporal lengthening (3-ventral corporotomies, grafts — SIS/tunica/dermal) if severe; dorsal plication (Baskin 12 o’clock, Nesbit) for modest residual curve — plication shortens an already short adult penis, so prefer ventral lengthening when curve is >30° after release.",
        "Urethroplasty options after a healthy straight shaft:",
      ]},
      { t: "tbl", h: ["Method", "When in this adult"], r: [
        ["Snodgrass TIP", "Only if plate is wide, healthy, unscarred and chordee was skin-deep — uncommon at 23 with true mid-penile chordee"],
        ["Onlay island flap (Duckett) / Mathieu", "If good prepuce remains and plate can stay; hair-bearing skin is a long-term disaster"],
        ["Two-stage Bracka with BMG", "Workhorse for adult mid-penile + chordee after plate transection: stage 1 graft to dartos/tunica, 6 months later tubularise"],
        ["One-stage Asopa / dorsal inlay (Snodgrass–Orkiszewski) + ventral onlay", "Selected if chordee corrected without plate loss"],
        ["Perineal urethrostomy", "Cripple, BXO, patient preference for sitting void — valid"],
        ["Staged Johanson", "Historical skin; inferior to BMG if skin is poor"],
      ]},
      { t: "ul", v: [
        "BMG: inner cheek, thin, 25 mm wide; warn of mouth tightness, avoid if oral lichen / heavy tobacco without counselling. Never harvest hair-bearing skin into the urethra of an adult.",
        "BXO (LS): complete substitution with BMG, not local skin.",
        "Coverage: dartos / tunica vaginalis flap over suture lines. SPC diversion 7–14 days. No intercourse 6 weeks.",
      ]},
      { t: "tip", k: "gold", v: "Adult mid-penile hypospadias with chordee = straighten (often plate cut) + staged BMG. TIP is a paediatric plate-preserving operation, not a default in a 23-year-old with curvature." },
    ],
  },
  {
    id: "nocturnal-enuresis",
    topicId: "paediatric",
    title: "Nocturnal enuresis",
    highYield: true,
    gold: false,
    tags: ["enuresis", "ICCS", "alarm", "desmopressin", "MNE"],
    exams: [
      { session: "Jun", year: 2018, marks: "10", stem: "Management of nocturnal enuresis in children." },
      { session: "Dec", year: 2016, marks: "5+5", stem: "Types and causes of nocturnal enuresis. Outline the management of monosymptomatic enuresis." },
    ],
    related: ["urodynamics-uroflow", "spina-bifida-mmc", "vur"],
    references: [
      "ICCS standardisation; NICE enuresis CG111",
      "EAU / ESPU Paediatric Urology",
      "Campbell-Walsh-Wein 12e, Elimination disorders",
    ],
    answer: [
      { t: "h", v: "Definitions (ICCS — write them)" },
      { t: "p", v: "Enuresis = intermittent incontinence during sleep in a child ≥5 years. Monosymptomatic (MNE): no daytime LUTS. Non-monosymptomatic (NMNE): daytime urgency, frequency, incontinence, straining. Primary: never dry 6 months. Secondary: relapse after ≥6 months dryness (look for UTI, constipation, diabetes, OSA, psychosocial, abuse)." },
      { t: "h", v: "Causes / pathophysiology of MNE" },
      { t: "ul", v: [
        "Nocturnal polyuria: lack of circadian ADH rise (the desmopressin-responsive group).",
        "Reduced nocturnal bladder capacity / nocturnal DO.",
        "Impaired arousal from sleep (the child who does not wake to a full bladder).",
        "Constipation (shared pelvic innervation; treat first).",
        "OSA / adenoids — snoring history; tonsillectomy can cure.",
        "Genetic (autosomal dominant families), delayed maturation — not laziness. Never humiliate.",
      ]},
      { t: "h", v: "Evaluation" },
      { t: "ul", v: ["History: diary 3–7 days including night volumes (weigh nappies), fluid, stools (Bristol), snoring, daytime symptoms, psychosocial", "Exam: spine, abdomen (stool, bladder), genitalia, BP, gait", "UA (glucose, infection, concentrating). US + PVR if NMNE. Uroflow if voiding symptoms. UDS almost never for simple MNE."] },
      { t: "h", v: "Management of MNE" },
      { t: "flow", title: "MNE pathway", nodes: [
        { id: "a", kind: "start", label: "Education, toilet, constipation, evening fluid, diary, treat OSA", to: ["b"] },
        { id: "b", kind: "decision", label: "Family wants active Rx (usually ≥6 y)?", to: ["c", "d"] },
        { id: "c", kind: "end", label: "Reassurance; 15%/year spontaneous resolution" },
        { id: "d", kind: "decision", label: "High night urine vs small bladder / arousal problem?", to: ["e", "f"] },
        { id: "e", kind: "action", label: "Desmopressin melt 120–240 µg at bedtime; stop if illness/drinking; Na caution", to: ["g"] },
        { id: "f", kind: "action", label: "Enuresis alarm (first-line when motivation high) 2–3 months", to: ["g"] },
        { id: "g", kind: "decision", label: "Fail monotherapy?", to: ["h"] },
        { id: "h", kind: "end", label: "Combine alarm + dDAVP; add anticholinergic if NMNE/DO; refer" },
      ]},
      { t: "ul", v: [
        "Alarm: highest long-term cure; needs motivated family; works by training arousal/inhibition.",
        "Desmopressin: rapid, good for sleepovers; high relapse when stopped; hyponatraemic seizure if water loaded — counsel no night fluids.",
        "Imipramine: third-line, cardiotoxic in overdose — rarely used now.",
        "Do not start anticholinergics in true MNE without residual/constipation check. Do not restrict daytime fluids punitively.",
      ]},
      { t: "tip", k: "gold", v: "MNE is alarm ± desmopressin after constipation and OSA are handled. Daytime symptoms = NMNE = treat the bladder first, not the bedsheet." },
    ],
  },
  {
    id: "spina-bifida-mmc",
    topicId: "paediatric",
    title: "Urologic care of spina bifida / myelomeningocoele",
    highYield: true,
    gold: true,
    tags: ["MMC", "NGB", "CIC", "compliance", "ACE", "hostility"],
    exams: [
      { session: "Jun", year: 2017, marks: "5+5", stem: "Urologic manifestations and management in children born with spina bifida and meningo-myelocele." },
    ],
    related: ["puv-valve-bladder", "vur", "urodynamics-uroflow", "nocturnal-enuresis"],
    references: [
      "Campbell-Walsh-Wein 12e, Neuropathic bladder in children",
      "EAU / ESPU Paediatric NGB; CDC spina bifida urologic protocol",
      "Bauer / Koff hostile bladder concept",
    ],
    answer: [
      { t: "p", v: "Open MMC (and closed spinal dysraphism) disrupt the sacral reflex arc and pontine pathways. >90% have a neuropathic bladder. The urologist’s job is kidney preservation first, continence second, sexuality/stones/latex third. Closure of the back is neurosurgery day 0–2; urology starts in the same admission." },
      { t: "h", v: "Manifestations" },
      { t: "tbl", h: ["Level / pattern", "Bladder / sphincter", "Risk"], r: [
        ["Suprasacral (common)", "DO + DSD (hostility)", "High Pdet, VUR, scarring, CKD"],
        ["Sacral / complete", "Acontractile detrusor + open sphincter", "Incontinence, low-pressure, safer kidneys unless chronic residual + infection"],
        ["Mixed / changing (tethered cord)", "Any combination; can convert over years", "Need lifelong surveillance"],
        ["Associated", "Constipation/soiling, latex allergy, C-curve scoliosis, VP shunt, hip/renal anomalies, sexual dysfunction, infertility (men: poor emission)", "ACE/MACE, latex-free theatre"],
      ]},
      { t: "h", v: "Evaluation timeline" },
      { t: "ul", v: [
        "Newborn: US, residual, Cr; start CIC if residual high or hydronephrosis or DSD suspected. VCUG. Baseline DMSA later.",
        "UDS within the first months (even if ‘dry’ — dry may mean high-pressure). Repeat with growth, UTI, new HN, tethering symptoms, before school, at puberty.",
        "Video-UDS: leak-point, DSD EMG, VUR, trabeculation. Safe storage: end-fill pressure <30–40 cm H2O and DLPP <40 (McGuire).",
      ]},
      { t: "h", v: "Management" },
      { t: "ul", n: true, v: [
        "CIC (parent then child) — the foundation. Latex-free catheters.",
        "Anticholinergic (oxybutynin, solifenacin) or β3; escalate to intradetrusor botulinum A if still hostile.",
        "CAP only while VUR + recurrent febrile UTI, not lifelong automatically.",
        "Bowel: diet, PEG, then ACE/MACE (Malone) / cecostomy for faecal continence — wet children are often just constipated.",
        "Failed conservative hostile bladder: augmentation cystoplasty (ileum) ± Mitrofanoff (appendicovesicostomy) ± bladder-neck procedure / sling / AUS in selected. Never augment without a CIC plan.",
        "VUR: often improves when pressures fall; STING/reimplant only after bladder is safe.",
        "Stones, metabolic acidosis after augment, B12, perforation of augment (surgical emergency in a ‘silent’ NGB abdomen), malignancy surveillance decades later.",
        "Tethered cord release if new spasticity / changing UDS — neurosurgery.",
        "Transition to adult NGB clinic; pregnancy in women with augment is possible with obstetric planning.",
      ]},
      { t: "tip", k: "gold", v: "Dry + hydronephrosis = hostile bladder until UDS disproves it. Continence operations on an unsafe reservoir steal kidneys." },
    ],
  },
  {
    id: "pyeloplasty-types",
    topicId: "paediatric",
    title: "Types of pyeloplasty and their indications",
    highYield: true,
    gold: false,
    tags: ["Anderson-Hynes", "Hellström", "Culp", "Fenger", "PUJO"],
    exams: [
      { session: "Dec", year: 2017, marks: "5+5", stem: "Types of pyeloplasty and their indications in specific situations." },
    ],
    related: ["fetal-hydronephrosis", "paediatric-robotics", "radionuclides-renogram"],
    references: [
      "Campbell-Walsh-Wein 12e, UPJ obstruction",
      "Hinman Atlas of Urologic Surgery",
      "EAU Paediatric / EAU Upper tract obstruction",
    ],
    answer: [
      { t: "p", v: "Pyeloplasty reconstructs a stenotic PUJ. Choice depends on PUJ anatomy (intrarenal pelvis, crossing vessel, long stricture, rotation) and approach (open flank, dorsal lumbotomy, lap, robotic). Success of dismembered Anderson–Hynes exceeds 95% and it is the default answer." },
      { t: "tbl", c: "Named pyeloplasties", h: ["Operation", "Principle", "Indication"], r: [
        ["Anderson–Hynes dismembered (1949)", "Excise PUJ + spatulate ureter, anastomose to a dependent pelvic flap; reduce redundant pelvis; transpose anterior to a crossing vessel", "Default for typical extrarenal PUJO ± crossing vessel"],
        ["Hellström / vascular hitch (Chapman)", "Mobilise and hitch lower-pole crossing vessels to pelvis without cutting PUJ", "Proven extrinsic crossing vessel, normal PUJ calibre, good peristalsis — confirm intra-op. Popular in children laparoscopically."],
        ["Foley Y-V", "Y incision, V advancement of pelvis into ureter", "High insertion of ureter, small pelvis, no need to transpose vessels"],
        ["Culp–DeWeerd spiral flap", "Spiral pelvic flap to bridge a long upper-ureteric defect", "Long stricture, large extrarenal pelvis"],
        ["Scardino–Prince vertical flap", "Vertical pelvic flap down the ureter", "Long defect, large pelvis"],
        ["Fenger plasty", "Heineke–Mikulicz longitudinal cut, transverse close", "Very short web; historically endoscopic analogue; inferior — rarely primary now"],
        ["Davis intubated ureterotomy", "Fillet stricture, stent, allow regeneration", "Historical long defects; replaced by flaps/buccal/ileal"],
        ["Ureterocalicostomy", "Ureter to lower-pole calyx after amputating pole", "Failed pyeloplasty, intrarenal pelvis, horseshoe lower-pole, scarred PUJ"],
        ["Ileal ureter / appendiceal onlay / BMG onlay", "Substitution", "Pan-ureteric or twice-failed"],
        ["Endopyelotomy (Acucise / Ho:YAG)", "Full-thickness lateral cut", "Selected adult secondary PUJO with good function, no crossing vessel on CT/CT angio — inferior to redo pyeloplasty in many series"],
      ]},
      { t: "h", v: "Situation-specific picks" },
      { t: "ul", v: [
        "Infant primary PUJO: Anderson–Hynes via dorsal lumbotomy or robotic/lap if expertise; stent or transanastomotic drain per surgeon.",
        "Crossing vessel without intrinsic stenosis: hitch. If in doubt, dismember — a missed intrinsic stenosis fails the hitch.",
        "Horseshoe: dismembered; ureter usually anterior; isthmus not always divided.",
        "Failed pyeloplasty: redo dismembered after 6–12 weeks vs ureterocalicostomy if pelvis obliterated.",
        "Poor function <15–20% after drainage: nephrectomy if contralateral kidney normal.",
        "Stones in the pelvis: dismembered + pyelolithotomy in one sitting.",
      ]},
      { t: "tip", k: "gold", v: "Anderson–Hynes is the Swiss Army knife. Name hitch for a pure crossing vessel and ureterocalicostomy for the wrecked redo." },
    ],
  },
  {
    id: "paediatric-robotics",
    topicId: "paediatric",
    title: "Robotics in paediatric urology — uses and limitations",
    highYield: false,
    gold: false,
    tags: ["robot", "pyeloplasty", "reimplant", "Mitrofanoff", "SP"],
    exams: [
      { session: "Dec", year: 2013, marks: "5+5", stem: "Describe the uses and limitations of robotic surgery in paediatric urology." },
    ],
    related: ["pyeloplasty-types", "davinci", "robotic-surgery-role", "vur"],
    references: [
      "Campbell-Walsh-Wein 12e, Minimally invasive paediatric urology",
      "EAU / ESPU; SAGES/robotic paediatric reviews",
      "Peters / Gundeti robotic pyeloplasty series",
    ],
    answer: [
      { t: "h", v: "Uses (where wrists help small anastomoses)" },
      { t: "ul", v: [
        "Pyeloplasty: the flagship — equivalent success to open, less dissection, cosmetic; transperitoneal Anderson–Hynes is standard.",
        "Ureteric reimplantation: extra-vesical Lich–Gregoir robotic; bilateral risk of retention. Intravesical Cohen robotic is possible but cramped.",
        "Ureteroureterostomy for duplex, megaureter tapering/reimplant, ureteric remnant.",
        "Mitrofanoff / Monti / ACE, bladder augmentation (selected high-volume), bladder-neck reconstruction — reconstructive MIS.",
        "Heminephrectomy / nephrectomy for non-function, adrenal, selected stones (niche), urachal, pelvic Müllerian remnants, selected RPLND in adolescents.",
        "Appendicovesicostomy and complex reconstruction in MMC — growing.",
      ]},
      { t: "h", v: "Limitations" },
      { t: "ul", v: [
        "Working space: infants <10 kg have a tiny pneumoperitoneum; arm clash; 8 mm ports are large on a 5 kg abdomen (5–8 mm instruments exist but Xi is still bulky). Open dorsal lumbotomy remains elegant for infant pyeloplasty.",
        "No haptics — suture can cut through infant ureters.",
        "Cost, docking time, access to dual-console training; volume-outcome.",
        "Need for a skilled bedside assistant (and anaesthetist comfortable with pneumoperitoneum, hypothermia, hidden blood loss).",
        "Not for: PUV ablation, most hypospadias, simple orchidopexy (lap is enough for intra-abdominal testis), emergency torsion.",
        "Evidence: no oncologic paediatric kidney cancer advantage; reconstructive equivalence, not superiority, vs open in RCTs (few).",
        "da Vinci SP: promising for a single incision but still adult-sized.",
      ]},
      { t: "tip", k: "exam", v: "Sell robotic pyeloplasty honestly and then spend equal ink on port size, cost and infant physiology." },
    ],
  },
];
