import type { Master } from "../types";

export const penis: Master[] = [
  {
    id: "penis-anatomy-ca",
    topicId: "penis",
    title: "Anatomy of the penis and its application in carcinoma penis",
    highYield: true,
    gold: true,
    tags: ["Buck fascia", "tunica", "lymphatics", "partial penectomy"],
    exams: [
      { session: "Jun", year: 2018, marks: "5+5", stem: "Anatomy of penis and its application in the management of carcinoma penis." },
    ],
    related: ["ca-penis-nodes", "ca-penis-organ-preserve", "erection-hemodynamics", "penis-embryology"],
    references: [
      "Hinman Atlas / Campbell-Walsh-Wein, Penile anatomy and penile cancer",
      "EAU Penile Cancer",
      "Daseler inguinal node anatomy",
    ],
    answer: [
      { t: "h", v: "Layers (superficial to deep) — write and draw" },
      { t: "ul", v: [
        "Skin → Dartos (continuous with Scarpa/Colles) → loose areolar (plane of degloving / circumcision) → Buck's (deep) fascia investing all three columns → tunica albuginea of each corpus (bilaminar in cavernosa, 2–3 mm, inner circular + outer longitudinal; thin over spongiosum) → erectile tissue.",
        "Neurovascular bundle at 11–1 o'clock: deep dorsal vein (midline), dorsal arteries, dorsal nerves (paired, lateral) — under Buck, over tunica. Nerve-spare in Peyronie/Nesbit lives here.",
        "Suspensory ligament (to pubic symphysis) and fundiform (from linea alba) — relevant to penile-lengthening and to penile-inversion vaginoplasty.",
        "Colles' fascia fuses with perineal membrane; Buck's fuses at the crus. Urine from a urethral injury deep to Buck stays penile; if Dartos/Colles is breached, butterfly perineal bruising (see fracture/urethra).",
      ]},
      { t: "h", v: "Corpora, urethra, glans" },
      { t: "ul", v: [
        "Paired cavernosa from ischial rami (crura, ischiocavernosus) to the distal cap beneath the glans. Midline septum is fenestrated — hence one-sided ICI drugs cross, and a unilateral plaque still bends the whole organ.",
        "Spongiosum: bulb (bulbospongiosus) → penile urethra → glans. Glans is the expanded spongiosum; corona and coronal sulcus are the commonest sites of penile SCC.",
        "Fossa navicularis, lacuna magna — relevant to hypospadias and to CIS of the glans (PeIN).",
      ]},
      { t: "h", v: "Blood and lymph — applied to cancer" },
      { t: "ul", v: [
        "Arteries: internal pudendal → common penile → cavernosal, dorsal, bulbourethral (see erection card). Skin from external pudendal (femoral). Glans can survive on dorsal and urethral arteries — the anatomic basis of glans-preserving surgery and of urethral-based flaps.",
        "Lymph (the money applied anatomy): skin of penis/prepuce → superficial inguinal (Daseler quadrants, especially superomedial, around saphenous–femoral junction). Glans and spongiosum → deep inguinal (Cloquet/Rosenmüller under the fascia lata at the femoral canal) and superficial inguinal. Cavernosa / proximal shaft can skip to pelvic (external iliac, obturator). Drainage is bilateral — a midline organ. Tunica/Buck is a temporary barrier: invasion of cavernosa or urethra upstages (T2/T3) and raises nodal risk.",
        "Inguinal nodes are the first-echelon; pelvic nodes are second-echelon. Skip pelvic mets without inguinal disease are rare. This is why we stage and treat groins first, and why cN0 risk-adapted groin management is the survival manoeuvre (nodes, not the primary, kill the patient).",
      ]},
      { t: "h", v: "Surgical applications in Ca penis" },
      { t: "tbl", h: ["Anatomic fact", "Surgical consequence"], r: [
        ["2 cm traditional margin is obsolete; 5 mm is enough for low-risk, 10 mm for high-grade if frozen-section used (EAU)", "Organ-sparing: glans resurfacing, glansectomy, wide local excision, distal penectomy rather than total"],
        ["Glans lymph → inguinal first", "Even T1 of glans needs a groin plan"],
        ["Bilateral drainage", "Always consider both groins in midline lesions; unilateral ILND only in strictly lateralised and selected"],
        ["Buck / tunica invasion = T2+", "MRI erect (PGE1) for local T before organ-spare"],
        ["Skin lymphatics ≠ corporal", "Circumcision / skin excision can clear preputial disease; does not address corporal T2"],
        ["Femoral triangle contents", "ILND template: sartorius, adductor longus, inguinal ligament; saphenous and fascia lata spared in modified Catalona"],
        ["Urethral artery keeps glans alive", "Glansectomy with split-skin graft onto corporal tips"],
        ["Pelvic nodes second-echelon", "Pelvic LND if ≥2 inguinal +, Cloquet +, extranodal extension, or bulky (EAU)"],
      ]},
      { t: "tip", k: "gold", v: "Penile SCC dies of inguinal disease. Anatomy tells you the first node basin is inguinal and bilateral, that 5–10 mm is a cancer margin, and that modified ILND lives inside the femoral triangle with saphenous spared." },
    ],
  },
  {
    id: "penis-embryology",
    topicId: "penis",
    title: "Embryology of the penis and preputial island flap",
    highYield: true,
    gold: false,
    tags: ["genital tubercle", "preputial flap", "hypospadias", "DHT"],
    exams: [
      { session: "Dec", year: 2021, marks: "5+5", stem: "Describe the embryological development of penis. Its blood supply and applied anatomy of prepucial island flap." },
    ],
    related: ["hypospadias", "penis-anatomy-ca", "erection-hemodynamics"],
    references: [
      "Campbell-Walsh-Wein, Embryology of the genitalia",
      "Hinman / Duckett inner-preputial island flap",
      "Baskin hypospadias anatomy",
    ],
    answer: [
      { t: "h", v: "Embryology of the penis" },
      { t: "ul", n: true, v: [
        "Weeks 4–7: sexually indifferent. Genital tubercle, inner genital folds, outer genital swellings, cloacal/urethral membrane. Distal urethral (glanular) plate is an independent endodermal/ectodermal contribution.",
        "Week 8+: SRY → testis → testosterone. Peripheral 5α-reductase type 2 in genital skin converts T → DHT, the ligand that elongates the tubercle into a phallus, fuses the folds in the midline (penile raphe) to enclose the urethra, and fuses swellings into scrotum. Without DHT (5α-reductase deficiency, AR defects) the phenotype is undervirilised / proximal hypospadias / micropenis.",
        "Urethral groove on the ventral tubercle closes proximal-to-distal as a zipper. Failure at a given station = hypospadias of that severity, with a dorsally hooded incomplete prepuce (ventral prepuce was never formed because folds did not fuse).",
        "Prepuce forms by folding of ectoderm over the glans after month 3; physiologic phimosis / incomplete separation of inner prepuce from glans is normal into childhood.",
        "Corpora: mesenchyme of the tubercle. Penile raphe, median raphe cysts, and Y-type urethral duplications are fusion-line remnants.",
        "Baskin: the neurovascular bundle is not two neat nerves — a dorsal nerve fan from 11–1 around to 5–7; the 12 o'clock plane is relatively nerve-free (used in plication). Ventral urethra in hypospadias has no spongiosum distally (hypoplastic) — hence dartos/tunica vaginalis flaps for coverage.",
      ]},
      { t: "h", v: "Blood supply of the penis (surgical)" },
      { t: "p", v: "Deep: internal pudendal → common penile → dorsal, cavernosal, bulbourethral. Superficial: superficial and deep external pudendal (femoral) supply the skin and Dartos, anastomosing across the midline and with the internal system at the corona. This dual supply is why penile skin can be degloved on a Dartos pedicle and why inner prepuce can be islanded." },
      { t: "h", v: "Preputial island flap — applied anatomy (Duckett)" },
      { t: "ul", v: [
        "Inner preputial mucosa is a hairless, supple, wet, DHT-responsive skin with a robust axial blood supply from the superficial (Dartos) fascia of the dorsal hood — branches of the superficial/dorsal penile arterial network running axially in Dartos, not randomly.",
        "Duckett transverse inner-preputial island tube: the inner prepuce is harvested as a rectangle on a Dartos pedicle from the dorsal hood, tubularised over a catheter, and anastomosed to the native urethral meatus after chordee release — one-stage repair of proximal hypospadias historically. Onlay island flap (Elder/Duckett) uses the same pedicle as a ventral onlay onto a preserved urethral plate (preferred when the plate is healthy) — lower fistula than a tube.",
        "Hodgson / Asopa / Double-faced preputial flaps: inner lining + outer skin on the same pedicle for severe skin shortage.",
        "Technical: transilluminate the Dartos to see axial vessels; do not button-hole the pedicle; tunnel or rotate ventrally without torsion; cover the suture line with a second-layer Dartos. Distal flap ischaemia = fistula/stricture.",
        "Limits: after circumcision the inner prepuce is gone — this flap is unavailable (use buccal, two-stage Bracka with inner-prepuce graft if uncircumcised, or prepuceless Byars). In the BXO/LS penis, preputial tissue is diseased — do not use it as urethra.",
        "Blood-supply exam line: flap is random-to-axial via Dartos; the glans remains on dorsal + urethral arteries; circumcision plane is the Dartos–Buck loose areolar layer.",
      ]},
      { t: "tip", k: "gold", v: "DHT fuses the folds; failure = hypospadias + hooded prepuce. Duckett island flap rides on axial Dartos vessels of that hood. Do not use LS-diseased prepuce as urethra." },
    ],
  },
  {
    id: "peyronie",
    topicId: "penis",
    title: "Peyronie's disease — etiopathogenesis, evaluation, IL therapy, surgery",
    highYield: true,
    gold: true,
    tags: ["Peyronie", "CCH", "Nesbit", "plaque", "IPP"],
    exams: [
      { session: "June", year: 2022, marks: "5+5", stem: "Discuss the etiopathogenesis, evaluation and surgical management of Peyronie's disease. Discuss the use of different drugs and modalities with limitations, in the non surgical management of Peyronie's disease." },
      { session: "Dec", year: 2020, marks: "3+4+3", stem: "How do you evaluate a man with Peyronie’s disease? What are various intra-lesional therapies? Describe their rationale." },
      { session: "Jun", year: 2021, marks: "3+3+4", stem: "Describe the pathology of Peyronie’s disease. What are the treatment options? Describe the steps of surgery for Peyronie's disease." },
      { session: "Dec", year: 2015, marks: "3+7", stem: "Pathophysiology and management of Peyronie’s disease." },
      { session: "Jun", year: 2014, marks: "4+6", stem: "What is the Aetio-pathogenesis of Peyronie's disease? Describe the management outline of Peyronie's disease." },
    ],
    related: ["erection-hemodynamics", "penile-prosthesis", "fracture-penis"],
    references: [
      "AUA Peyronie's Guideline 2015 (amended)",
      "EAU Sexual and Reproductive Health — Peyronie",
      "ISSM",
      "Campbell-Walsh-Wein, Peyronie's disease",
      "IMPRESS I/II — collagenase Clostridium histolyticum",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "Acute vs chronic 1 · TGF-β / tunica 2 · Evaluation (photos, ICI, Duplex, PDQ) 2 · Non-surgical with honest limitations 2 · Surgery algorithm (plication vs graft vs IPP) 3." },
      { t: "h", v: "Pathology and etiopathogenesis" },
      { t: "p", v: "Peyronie's disease (PD) is an acquired, localised fibrotic disorder of the tunica albuginea producing plaque, curvature, indentation, hinge, shortening and often ED. Distinct from congenital chordee (no plaque, lifelong). Prevalence 3–9% (higher with diabetes, after RP, Dupuytren, plantar fibromatosis)." },
      { t: "ul", v: [
        "Trigger: microtrauma of the erect penis (shear at the septal–tunical junction, classically dorsal) in a genetically susceptible man (Dupuytren, HLA associations, TGF-β polymorphisms).",
        "Acute (inflammatory, 6–18 months): fibrin in the tunica, macrophage/myofibroblast influx, TGF-β1 / PAI-1 / ROS → disordered collagen I/III, elastin fragmentation, calcification in some. Pain with erection is the clinical marker of activity.",
        "Chronic (stable ≥3 months, AUA: stable curve 3–6 months, pain gone): hypocellular plaque, calcification, stable deformity. Surgery only here.",
        "The inelastic plaque prevents ipsilateral expansion; the other side expands → curve towards the plaque. Hourglass / hinge from circumferential or septal plaque. ED from veno-occlusive dysfunction at the plaque and from performance anxiety / shared vascular risk.",
      ]},
      { t: "h", v: "Evaluation" },
      { t: "ul", v: [
        "History: duration, pain, stability, direction/degrees (patient photos of the erect penis are gold), shortening, indent, penetration ability, ED, Dupuytren, trauma, drugs (IFN, β-blockers weak), prostatectomy, expectations.",
        "Exam flaccid: plaque location (dorsal most), length, stretch, hinge. Dupuytren hands, Ledderhose feet.",
        "Erect assessment: home photos or in-office ICI (PGE1) with goniometer — do not operate off a flaccid exam. Doppler if ED, to plan IPP vs reconstruction.",
        "PDQ / IIEF. XR/US for calcification (predicts poor IL collagenase response). MRI rarely.",
        "Counsel natural history: 10–15% improve, 40% stable, 40% worsen in the first year. Pain almost always burns out.",
      ]},
      { t: "h", v: "Non-surgical therapy — with limitations (June 22)" },
      { t: "tbl", h: ["Modality", "Rationale", "Limitation / EAU-AUA stance"], r: [
        ["Oral: vitamin E, tamoxifen, colchicine, acetyl-L-carnitine, omega-3, POTABA", "Antioxidant / antifibrotic hypotheses", "No robust RCT benefit. AUA: do not offer vitamin E/tamoxifen/procarbazine/omega-3. POTABA poorly tolerated (GI). Do not sell oral miracle courses."],
        ["PDE5 daily (tadalafil 5 mg)", "Antifibrotic cGMP, treat ED, possible curve modest benefit", "Reasonable adjunct; evidence for curve reduction modest. Excellent for ED/PD overlap."],
        ["NSAIDs / analgesic", "Acute pain", "Does not change the plaque"],
        ["Traction / RestoreX / vacuum", "Mechanotransduction, length", "Best conservative for length; compliance-heavy. Adjunct to CCH (IMPRESS used modelling)."],
        ["ESWT", "Pain via hyperstimulation", "May help pain; does not reliably straighten. EAU: pain only."],
        ["IL verapamil", "Calcium-channel → collagenase modulation, 10 mg/2 weeks × 6–12", "Mixed RCTs; cheap; AUA: may offer. Limitation: evidence inconsistent, many injections."],
        ["IL interferon-α2b", "Myofibroblast inhibition, 5 MU fortnightly", "Modest curve benefit in one RCT vs saline. Flu-like AE. Cost. AUA: may offer."],
        ["IL collagenase C. histolyticum (CCH, Xiaflex) — the only licensed IL disease-modifier", "Degrades collagen I/III. IMPRESS protocol: 8 injections + clinician modelling + home modelling. ~17° mean improvement vs 9° placebo.", "Licensed for ≥30° stable PD with palpable plaque, not hourglass/calcified ventral in some labels. AE: bruising, swelling, corporal rupture ~0.5–1% (no sex 2 weeks). Cost, availability in India variable. Not for acute PD. Failures still need surgery."],
        ["IL steroids / hyaluronidase / PRP / stem cells", "—", "Steroids: atrophy, no. PRP/stem: investigational."],
        ["Radiotherapy", "Acute pain historically", "Not recommended — late fibrosis/ED"],
      ]},
      { t: "h", v: "Surgery — only stable disease, function-driven" },
      { t: "flow", title: "PD surgery algorithm", nodes: [
        { id: "a", kind: "start", label: "Stable ≥3 months, pain gone, cannot penetrate or distressed by deformity", to: ["b"] },
        { id: "b", kind: "decision", label: "Adequate erection with/without PDE5?", to: ["c", "d"] },
        { id: "d", kind: "end", label: "IPP ± modelling ± plaque incision. Gold for PD + ED" },
        { id: "c", kind: "decision", label: "Curve ≤60° (some 70), good length, no severe hinge?", to: ["e", "f"] },
        { id: "e", kind: "end", label: "Tunical plication (Nesbit / Yachia / 16-dot Baskin–Duckett). Shortens the long side." },
        { id: "f", kind: "end", label: "Plaque incision / partial excision + graft (vein, buccal, pericardium, collagen fleece). Length-preserving. Higher ED risk." },
      ]},
      { t: "h", v: "Steps — Nesbit (the classic they want)" },
      { t: "ul", n: true, v: [
        "ICI or saline erection to map the curve. Circumcising incision, deglove. Mobilise NVB (dorsal curve) or urethra (ventral curve) if needed.",
        "Excise an ellipse of tunica on the convex (long) side (≈1 mm per 10° as a rough Nesbit rule) or plicate without excision (Yachia Heineke–Mikulicz; 16-dot no-incision; TAP). 2-0/3-0 non-absorbable or delayed, knots buried.",
        "Re-erect, check residual <15–20°, haemostasis, circumcision closure, compressive dressing, voiding trial.",
        "Counsel: 1–2 cm shortening, palpable knots, 10–20% residual/recurrent curve, 5–15% de-novo ED, glans numbness if NVB mishandled, anorgasmia rare.",
      ]},
      { t: "p", v: "Grafting (Egydio, Lue vein, Kadioglu): H- or double-Y incision in the plaque, graft sewn into the defect. Higher ED (veno-occlusive) — pick men with strong pre-op erections. IPP modelling (Wilson): inflate, clamp tubes, bend opposite the curve 30–90 s; plaque nick if needed. Never model a recently CCH-injected penis (rupture)." },
      { t: "tip", k: "gold", v: "Operate only on a stable penis. Plication for simple curves; graft for severe/short/hinge; IPP for PD+ED. CCH is the only IL with a real RCT; orals are mostly theatre." },
    ],
  },
  {
    id: "hypospadias",
    topicId: "penis",
    title: "Hypospadias — development, GMS score, penoscrotal and adult midpenile",
    highYield: true,
    gold: true,
    tags: ["GMS", "TIP", "Bracka", "chordee", "urethral plate"],
    exams: [
      { session: "Jun", year: 2020, marks: "3+3+4", stem: "Describe the development of male urethra and the pathogenesis of Hypospadias. What is GMS (Glans Meatus Shaft) score and discuss its significance? Briefly outline the management of penoscrotal Hypospadias." },
      { session: "Dec", year: 2022, marks: "5+5", stem: "Evaluation of a 23-year male with mid-penile Hypospadias. Surgical options for correction of mid-penile Hypospadias with chordee." },
    ],
    related: ["penis-embryology", "unconsummated-marriage", "urethroplasty"],
    references: [
      "EAU Paediatric Urology — hypospadias",
      "Campbell-Walsh-Wein, Hypospadias",
      "Snodgrass TIP; Bracka two-stage; Merriman GMS score",
      "Baskin embryology",
    ],
    answer: [
      { t: "h", v: "Development of the male urethra and pathogenesis" },
      { t: "p", v: "See embryology card for the DHT-driven zipper of the urethral folds (proximal-to-distal) and the independent glanular plate. Hypospadias = arrest of that zipper + ventral skin/spongiosal hypoplasia + often chordee (asymmetric corporal cavernosa, residual fibrous dartos, short urethral plate). Associated: inguinal hernia, cryptorchidism (exclude DSD if proximal + unilateral/bilateral UDT — karyotype, electrolytes). Endocrine disruptors, familial clustering, ART conception, and low birth-weight/placental insufficiency are epidemiologic associations. Do not circumcise a hypospadiac neonate — the hood is reconstructive capital." },
      { t: "h", v: "GMS score (Merriman / Holland)" },
      { t: "p", v: "GMS is a 3-component, 1–4 severity score (total 3–12) that grades the quality of tissues rather than meatal location alone — because a distal meatus with a small glans and severe chordee behaves like a proximal case." },
      { t: "tbl", h: ["Component", "1 (favourable)", "4 (unfavourable)"], r: [
        ["G — Glans", "Large, deep groove, well-cleft", "Small, flat, no groove, poor wings"],
        ["M — Meatus", "Glanular / coronal", "Penoscrotal / scrotal / perineal"],
        ["S — Shaft (chordee / quality)", "No/minimal curve, healthy plate and skin", "Severe chordee, poor plate, skin deficiency, transposition"],
      ]},
      { t: "p", v: "Significance: high GMS predicts fistula, glans dehiscence, need for two-stage repair and reoperation. It standardises inter-observer description (better than ‘midpenile’ alone) and is useful in the 23-year-old too — a previously unoperated adult with G4 M3 S4 is not a TIP candidate." },
      { t: "h", v: "Penoscrotal hypospadias — outline (Jun 20)" },
      { t: "ul", v: [
        "Work-up: DSD screen if gonads not descended / scrotum bifid / severe proximal. Do not operate in the neonatal androgen-surge window; 6–18 months is the usual first-stage age after a single pre-op testosterone/DHT burst if the glans is tiny (evidence mixed but common practice).",
        "Goals: straight (erection test), slit glanular meatus, adequate calibre, cosmesis, standing void, later fertility/sex.",
        "Chordee first: deglove, excise ventral dartos, artificial erection. If still >30°, ventral corporotomies ± dorsal plication (12 o'clock, Baskin nerve-free zone) ± corporal grafting (SIS, tunica vaginalis) in severe curvature. Dividing a short plate is often required — that commits to two-stage.",
        "Urethra: two-stage Bracka (inner preputial or buccal graft to the ventral defect, 6 months later tubularise) is the most reproducible in penoscrotal disease. Alternatives: staged Byars flaps; one-stage Duckett tube (higher stricture); onlay / inlay TIP only if plate is supple after chordee release (uncommon at penoscrotal).",
        "Second layer: Dartos or tunica vaginalis flap. SP catheter ± urethral stent. Testis/hernia addressed. Long-term: fistula 10–30%, stricture, residual chordee, hairy urethra if scrotal skin used, ejaculatory pooling, infertility later, psychological follow-up.",
      ]},
      { t: "h", v: "23-year-old unoperated mid-penile hypospadias with chordee (Dec 22)" },
      { t: "ul", v: [
        "Evaluation: sexual function (uncosummated marriage, ED, PE), standing photos of erection, uroflow + PVR, urine culture, meatal site/calibre, plate quality, residual prepuce, LS (do not miss BXO in adults — biopsy if pale rigid meatus), semen if fertility, androgenisation, undescended testes. Counselling: adult tissues fistula more than infant TIP; goals may be straightening for sex more than a perfect glanular meatus.",
        "Chordee: deglove + erection test. Often a short plate + ventral fibrosis. Options: dorsal 16-dot/Nesbit if mild after degloving; plate transection + staged graft if severe.",
        "Urethra options in the adult midpenile: (1) TIP (Snodgrass) if plate wide and chordee mild after deglove — midline relaxing incision, tubularise over 12–14 Fr, Dartos cover, circumcision or prepucioplasty. (2) Onlay inner-preputial island if uncircumcised and plate present. (3) Two-stage Bracka with buccal (if circumcised or LS). (4) Staged preputial graft. (5) Perineal urethrostomy as an honest option if the patient wants to sit to void and avoid 2–3 operations.",
        "Do not use LS skin. Testosterone priming is less useful in adults. VTE risk, erections post-op (diazepam/amylase… — actually amyl nitrite not used; cyproterone/ketoconazole rarely; mainly dressings and PDE5 avoidance early). Follow-up flow rate lifelong — adult hypospadias cripples are a real entity if the first operation is poorly chosen.",
      ]},
      { t: "tip", k: "gold", v: "GMS scores tissues, not just the hole. Penoscrotal = chordee first, usually two-stage. Adult midpenile = photograph the erection, kill chordee, TIP only if the plate is honest, buccal Bracka if it is not." },
    ],
  },
  {
    id: "ca-penis-premalignant",
    topicId: "penis",
    title: "Premalignant lesions of the penis and HPV",
    highYield: true,
    gold: false,
    tags: ["PeIN", "HPV", "lichen sclerosus", "vaccine"],
    exams: [
      { session: "June", year: 2022, marks: "4+3+3", stem: "Discuss the premalignant conditions that are associated with Ca Penis. Discuss the anatomy of the inguinal lymph nodes in respect to surgery for Ca penis. Discuss the differences between a Classical/Radical Ilioinguinal lymph node dissection and a modified Ilioinguinal lymph node dissection." },
      { session: "Jun", year: 2017, marks: "4+6", stem: "Enumerate the premalignant lesions of Penis. Outline their management." },
      { session: "Dec", year: 2020, marks: "4+6", stem: "What is the role of Human Papilloma Virus infection in cancer penis? What are the prevention strategies?" },
    ],
    related: ["ca-penis-nodes", "ca-penis-hpv", "ca-penis-organ-preserve"],
    references: [
      "WHO GU 2022 — PeIN",
      "EAU Penile Cancer",
      "IARC HPV and penile cancer",
      "Campbell-Walsh-Wein",
    ],
    answer: [
      { t: "h", v: "Premalignant conditions" },
      { t: "tbl", h: ["Lesion", "HPV?", "Risk of SCC", "Management"], r: [
        ["PeIN (penile intraepithelial neoplasia) — undifferentiated / warty-basaloid (HPV-related) and differentiated (LS-related)", "Undifferentiated: 16/18. Differentiated: no", "High if untreated", "Biopsy. Circumcision (the whole prepuce is a field). Topical 5-FU or imiquimod. CO2 laser, glans resurfacing with split-skin graft for extensive glanular PeIN (gold for functional organ-spare). Follow-up: recurrences."],
        ["Erythroplasia of Queyrat", "Often HPV", "CIS of glans — up to 30% invasion if ignored", "Treat as PeIN of glans: resurfacing / topical / glansectomy if invasion cannot be excluded"],
        ["Bowen disease", "Often HPV", "CIS of shaft skin", "WLE, topical, circumcision if preputial"],
        ["Bowenoid papulosis", "HPV 16", "Young, multiple papules; low invasion risk", "Confirm histology. Topical/ablative. Not radical surgery. Partner HPV issues."],
        ["Lichen sclerosus (BXO)", "No — chronic inflammation pathway", "2–9% lifetime SCC; differentiated PeIN", "Circumcision is therapeutic for preputial LS. Topical clobetasol. Meatal dilatation / staged urethroplasty with buccal if urethra involved (never LS skin as graft). Lifelong look at the glans for PeIN/SCC."],
        ["Giant condyloma (Buschke–Löwenstein / verrucous)", "HPV 6/11 typically", "Locally destructive, rare invasion", "Wide local excision; not IFN-only. Histology to exclude verrucous carcinoma."],
        ["Leukoplakia, cutaneous horn, pseudoepitheliomatous keratotic and micaceous balanitis", "Variable", "Uncommon", "Excise / biopsy; circumcision"],
        ["Phimosis / chronic balanitis / smegma / poor hygiene", "Field", "The major epidemiologic cluster with HPV", "Circumcision, hygiene, treat infection"],
      ]},
      { t: "h", v: "HPV and penile cancer (Dec 20)" },
      { t: "ul", v: [
        "Two pathways: HPV-related (warty/basaloid SCC, undifferentiated PeIN; HPV 16 dominates, 18/others) vs non-HPV (keratinising SCC on LS/phimosis, differentiated PeIN). Overall HPV DNA in ~30–50% of invasive penile SCC (lower than cervix).",
        "Oncogenesis: E6/E7 inactivate p53 and Rb; p16 IHC is a surrogate of transcriptionally active HPV.",
        "Prevention: (1) Neonatal or pre-sexual circumcision reduces risk (strong epidemiology). (2) HPV vaccination (nonavalent 6/11/16/18/31/33/45/52/58) — gender-neutral adolescent programmes prevent genital warts and will reduce HPV-related penile, anal, oropharyngeal disease; catch-up of MSM. (3) Smoking cessation. (4) Treat/circumcise LS and phimosis. (5) Condoms (partial). (6) Hygiene. (7) Treat PeIN early. There is no organised screening smear equivalent; inspect high-risk groins/glans in LS follow-up.",
        "Partner: cervical screening up to date. Vaccine does not treat established invasive cancer.",
      ]},
      { t: "tip", k: "exam", v: "List PeIN (two pathways), EQ, Bowen, Bowenoid papulosis, LS, Buschke–Löwenstein. Circumcision + glans resurfacing for PeIN. HPV 16; vaccine + circumcision as prevention." },
    ],
  },
  {
    id: "ca-penis-nodes",
    topicId: "penis",
    title: "Inguinal anatomy, cN0 groin, DSLNB, palpable nodes, ILND",
    highYield: true,
    gold: true,
    tags: ["ILND", "Catalona", "DSLNB", "Cloquet", "cN0"],
    exams: [
      { session: "Jun", year: 2021, marks: "4+6", stem: "Describe the lymphatic drainage of penis. Discuss the management of clinically node negative groin in Carcinoma Penis." },
      { session: "Dec", year: 2018, marks: "10", stem: "Surgical management of palpable unilateral inguinal lymph nodes in penile carcinoma." },
      { session: "Dec", year: 2013, marks: "10", stem: "How will you manage T, high grade penile Squamous cell carcinoma with right sided palpable but mobile inguinal lymph nodes?" },
      { session: "Dec", year: 2022, marks: "4+3+3", stem: "Illustrate anatomy of the femoral triangle in relation to inguinal lymph node dissection. Enumerate indications for adjuvant chemotherapy after ilio-inguinal lymph node dissection. Dynamic sentinel lymph node biopsy in penile cancer." },
      { session: "Dec", year: 2020, marks: "5+5", stem: "After adequate control of penile cancer, describe the risk-based management of inguinal region and draw treatment algorithm." },
      { session: "June", year: 2022, marks: "4+3+3", stem: "Premalignant conditions. Anatomy of inguinal lymph nodes. Classical vs modified ILND." },
    ],
    related: ["ca-penis-staging", "ca-penis-organ-preserve", "penis-anatomy-ca"],
    references: [
      "EAU Penile Cancer 2024",
      "NCCN Penile Cancer",
      "Catalona modified ILND; Daseler; Cabanas sentinel; Leijte / Horenblas DSLNB",
      "InPACT trial (neoadjuvant)",
    ],
    answer: [
      { t: "h", v: "Lymphatic drainage and femoral triangle" },
      { t: "p", v: "Skin/prepuce → superficial inguinal; glans/spongiosum → superficial + deep inguinal; proximal cavernosa may reach pelvic. Bilateral. Superficial nodes lie in Camper's fascia, in Daseler's five quadrants around the saphenofemoral junction (superomedial is the most frequent sentinel). Deep inguinal nodes lie medial to femoral vein, under fascia lata; Cloquet (Rosenmüller) is the highest deep node in the femoral canal — the anatomic bridge to external iliac." },
      { t: "ul", v: [
        "Femoral triangle (Scarpa): inguinal ligament (superior), sartorius (lateral), adductor longus (medial). Floor: iliopsoas, pectineus, adductor longus. Contents: femoral nerve, artery, vein, lymphatics (NAVEL from lateral to medial — Nerve, Artery, Vein, empty (canal), Lymphatics). Saphenous vein joins femoral at the fossa ovalis. Femoral nerve is outside the sheath, lateral — usually not in the ILND field if you stay medial to artery, but the femoral vessels are.",
        "Draw this. The modified dissection lives in this triangle and stops at the apex; radical may go along the vessels more aggressively and include pelvis (ilio-inguinal).",
      ]},
      { t: "tbl", c: "Radical (classical) vs modified ILND (Catalona 1988)", h: ["", "Classical / radical ilio-inguinal", "Modified inguinal"], r: [
        ["Lateral bound", "Sartorius (or wider, anterior superior iliac spine)", "Femoral artery (narrower)"],
        ["Medial", "Adductor longus", "Adductor longus"],
        ["Superior", "Above inguinal ligament, may include pelvic via femoral canal / separate pelvic incision", "Inguinal ligament; no pelvic unless indicated"],
        ["Inferior / apex", "Apex of triangle, 15–20 cm down sartorius", "Shorter, fossa ovalis"],
        ["Saphenous", "Ligated", "Preserved"],
        ["Fascia lata", "Opened, deep nodes taken, sartorius transposition to cover vessels", "Often preserved; deep nodes still sampled around fossa ovalis / Cloquet"],
        ["Morbidity", "Wound 30–50%, lymphoedema 20–50%, necrosis", "Roughly halved wound/lymphoedema if negative frozen — convert to radical if frozen +"],
      ]},
      { t: "h", v: "cN0 groin — risk-adapted algorithm (the survival question)" },
      { t: "p", v: "Physical exam of both groins ± US. Palpable = cN+. Impalpable = cN0. Occult mets in 20–25% overall of invasive SCC; risk from the primary (EAU):" },
      { t: "flow", title: "cN0 after the primary is controlled", nodes: [
        { id: "a", kind: "start", label: "Invasive penile SCC, groins impalpable (cN0)", to: ["b"] },
        { id: "b", kind: "decision", label: "Low risk? (pTis/Ta/T1a G1, no LVI)", to: ["c", "d"] },
        { id: "c", kind: "end", label: "Surveillance of groins (exam ± US). Survival not improved by staging ILND" },
        { id: "d", kind: "decision", label: "Intermediate/high risk: ≥T1b or G2–3 or LVI, or T2+", to: ["e"] },
        { id: "e", kind: "action", label: "Invasive groin staging of BOTH groins: DSLNB (expert centre) OR modified/video-endoscopic ILND. Do NOT ‘watch’ high-risk cN0 — delayed ILND costs survival", to: ["f"] },
        { id: "f", kind: "decision", label: "Node positive?", to: ["g", "h"] },
        { id: "g", kind: "end", label: "Completion radical ILND that side ± pelvic LND if indicated. Cross the other groin if not already staged" },
        { id: "h", kind: "end", label: "Observe if true pN0" },
      ]},
      { t: "h", v: "DSLNB (Dec 22)" },
      { t: "p", v: "Dynamic sentinel lymph node biopsy: radiotracer (99mTc-nanocolloid) ± ICG / patent blue, injected at the primary the day before or same day, lymphoscintigraphy / SPECT-CT, gamma-probe + blue/ICG-guided excision of the hot node(s) in a cN0 groin. False-negative ~5–7% in high-volume centres (higher early in a learning curve — that is the exam caution). Only for cN0; a palpable node needs ILND/FNAC, not DSLNB. If the sentinel is positive, complete ILND. Not available everywhere in India — modified ILND is the legitimate alternative." },
      { t: "h", v: "Palpable unilateral mobile nodes (Dec 18 / Dec 13 T high-grade)" },
      { t: "ul", n: true, v: [
        "Confirm the primary is / will be controlled (partial penectomy / glansectomy for a distal high-grade T1–T2).",
        "Do not assume infection: 4–6 weeks of antibiotics then re-exam is an old pathway; current EAU prefers US-FNAC of the palpable node immediately. If FNAC negative and suspicion remains, still explore. If FNAC +, plan ILND (and staging CT/MRI ± PET for pelvic/distant).",
        "Ipsilateral radical ILND. Frozen of Cloquet / highest node. Pelvic LND if ≥2 inguinal +, extranodal extension, Cloquet +, or imaging-positive pelvis.",
        "Contralateral groin is still at risk (crossover): if clinically negative, stage it (DSLNB or modified ILND) because high-grade T with one positive groin is not ‘unilateral disease biologically’.",
        "Neoadjuvant chemo (TIP: paclitaxel, ifosfamide, cisplatin) for bulky/fixed N3 or for cN2 in trials (InPACT). Mobile unilateral N1 typically goes straight to ILND then adjuvant if indicated.",
        "Sartorius transposition, drains, stockings, peri-op Abx, DVT prophylaxis. Path: number, ENE, laterality.",
      ]},
      { t: "h", v: "Adjuvant chemotherapy after ILND (Dec 22)" },
      { t: "ul", v: [
        "pN2 (multiple inguinal), pN3 (ENE or pelvic), or ≥2–3 nodes — cisplatin-based (TIP or 5-FU/cisplatin) adjuvant. pN1 single node without ENE: benefit uncertain; discuss.",
        "Adjuvant inguinal RT for ENE / positive margin if chemo unfit — morbidity (lymphoedema) is additive with ILND.",
        "InPACT is the ongoing perioperative question — mention, do not fake results.",
      ]},
      { t: "tip", k: "gold", v: "The cN0 high-risk groin must be invasively staged (DSLNB or modified ILND), not watched. Palpable = FNAC then radical ILND + stage the other side. Modified = saphenous-sparing Catalona. Pelvis if ≥2 inguinal +, ENE, Cloquet." },
    ],
  },
  {
    id: "ca-penis-staging",
    topicId: "penis",
    title: "Carcinoma penis — presentation, staging, stage-wise management",
    highYield: true,
    gold: true,
    tags: ["TNM", "EAU risk", "partial penectomy"],
    exams: [
      { session: "Dec", year: 2015, marks: "4+6", stem: "Staging and stage wise management of carcinoma penis." },
      { session: "Jun", year: 2019, marks: "(2+2+2)+(2+2)", stem: "Describe the presenting features, diagnosis, and staging for cancer of penis. Discuss indication and options of treatment with organ preservation for a 50-year-old man with Squamous cell carcinoma of penis." },
    ],
    related: ["ca-penis-nodes", "ca-penis-organ-preserve", "ca-penis-nonsquamous"],
    references: [
      "AJCC 8th / UICC TNM",
      "EAU Penile Cancer",
      "Campbell-Walsh-Wein",
    ],
    answer: [
      { t: "h", v: "Presentation and diagnosis" },
      { t: "ul", v: [
        "Older man, uncircumcised, phimosis, delay (embarrassment). Mass, ulcer, bleeding, foul discharge, pain, LUTS if meatal, bulky groins, rarely distant. PeIN may be a red patch.",
        "Examine: primary (size, glans/coronal sulcus/prepuce/shaft, corpus invasion — palpate erect if needed), both groins, abdomen. Circumcise to expose if phimotic, biopsy the lesion (wedge, include base). MRI with PGE5/PGE1 erection if organ-spare and T-stage unclear. CT chest/abdomen/pelvis for ≥T1b / G3 / cN+. Bone scan if symptoms. Penile Doppler not a cancer test.",
        "Histology: SCC subtypes (usual, basaloid, warty, verrucous, sarcomatoid — worst), grade, LVI, PNI, p16, depth, urethral involvement.",
      ]},
      { t: "tbl", c: "TNM AJCC 8th (write this table)", h: ["T / N / M", "Definition"], r: [
        ["Tis / Ta", "PeIN / non-invasive verrucous"],
        ["T1a", "Invades subepithelial connective tissue, no LVI, not high-grade"],
        ["T1b", "LVI or perineural or high-grade (G3) in subepithelial tissue"],
        ["T2", "Corpus spongiosum ± urethra"],
        ["T3", "Corpus cavernosum ± urethra"],
        ["T4", "Adjacent structures (pubis, scrotum, prostate)"],
        ["N1", "≤2 unilateral inguinal, mobile, no ENE"],
        ["N2", "≥3 unilateral or bilateral inguinal, no ENE"],
        ["N3", "ENE of inguinal, or pelvic nodes"],
        ["M1", "Distant"],
        ["S — not used", "Unlike testis, no S-stage"],
      ]},
      { t: "h", v: "Stage-wise management (distilled EAU)" },
      { t: "tbl", h: ["Disease", "Primary", "Groins"], r: [
        ["Tis / Ta / T1a G1", "Circumcision ± topical 5-FU/imiquimod, laser, glans resurfacing, WLE", "Observe"],
        ["T1b / T2 distal", "Glansectomy + graft, or partial penectomy with 5–10 mm frozen-negative margin", "Invasive staging both groins (DSLNB or mILND)"],
        ["T3 proximal / not spareable", "Partial if stump allows upright voiding (≥2–3 cm residual); else total penectomy + perineal urethrostomy", "Invasive staging / therapeutic ILND"],
        ["T4", "Neoadjuvant chemo if fit, then surgery / palliation", "Often N+"],
        ["cN1–2 mobile", "Control primary; radical ILND ± pelvic as indications", "Neoadjuvant TIP if bulky"],
        ["cN3 fixed / pelvic", "Neoadjuvant TIP then surgery if responds; else RT/chemo-RT palliation", "InPACT"],
        ["M1", "Platinum chemo, palliation, rarely metastasectomy", "—"],
      ]},
      { t: "p", v: "50-year-old organ-preservation: see next card. Survival is a function of nodal control, not of whether he keeps 1 cm more of shaft." },
    ],
  },
  {
    id: "ca-penis-organ-preserve",
    topicId: "penis",
    title: "Organ-preserving management of penile cancer",
    highYield: true,
    gold: false,
    tags: ["glans resurfacing", "glansectomy", "brachytherapy", "5-FU"],
    exams: [
      { session: "Dec", year: 2011, marks: "6+4", stem: "What is organ preserving management of penile cancer? Which patients are most suitable for these approaches?" },
      { session: "Dec", year: 2021, marks: "5+5", stem: "Describe various organ preserving treatments in penile cancer and their results." },
      { session: "Jun", year: 2019, marks: "2+2", stem: "Indication and options of treatment with organ preservation for a 50-year-old man with Squamous cell carcinoma of penis." },
    ],
    related: ["ca-penis-staging", "ca-penis-nodes", "penis-anatomy-ca"],
    references: [
      "EAU Penile Cancer — organ-sparing",
      "Pizzocaro / Smith / Hegarty glans-resurfacing series",
      "Campbell-Walsh-Wein",
    ],
    answer: [
      { t: "p", v: "Organ preservation = complete oncologic control of the primary with reconstruction that keeps a sexually and urinarily useful phallus (glans/shaft), using a histologically negative margin that can be 5 mm (1–2 mm in selected PeIN/T1 with frozen section) rather than the historical 2 cm." },
      { t: "h", v: "Who is suitable" },
      { t: "ul", v: [
        "Tis, Ta, T1, and selected distal T2 (spongiosum of glans) where a negative frozen margin is achievable and the residual penis will function.",
        "Motivated for close follow-up (local recurrence 5–30% depending on method — salvage is usually successful if caught).",
        "Not: proximal T3 cavernosum, T4, unsalvageable phimotic wreck, non-compliant, sarcomatoid, or a man who prefers the certainty of partial penectomy.",
      ]},
      { t: "tbl", h: ["Method", "Indication", "Results / limits"], r: [
        ["Circumcision alone", "Preputial CIS/T1 confined to prepuce", "Must confirm margins; groins still risk-adapted"],
        ["Topical 5-FU 5% or imiquimod 5%", "Tis, small, non-invasive", "CR 50–70%; field recurrences; not for invasive"],
        ["Laser (CO2, Nd:YAG)", "Tis/T1a", "Local rec ~20%; operator-dependent depth"],
        ["Mohs micrographic", "Selected T1", "Rare expertise"],
        ["Glans resurfacing (total or partial)", "Extensive glanular PeIN / Tis, selected T1a", "SSG onto denuded glans. Excellent cosmesis, local control >90% if invasion excluded on pathology of the sheet"],
        ["WLE + primary closure / graft / preputial flap", "Small T1 shaft/glans", "Frozen margins"],
        ["Glansectomy + corporal-tip graft (split skin)", "Glans T1–T2 distal", "Workhorse organ-spare. Local rec ~5–10%. Sexual function often preserved. Meatal stenosis."],
        ["Distal/partial penectomy with 5–10 mm margin + reconstruction", "Distal T2/T3 if residual length ≥2–3 cm", "Still ‘organ-preserving’ vs total. Upright void, some sex"],
        ["Radiotherapy / brachytherapy (mould or interstitial)", "T1–T2 <4 cm, glans, in RT-expert centres", "Local control 70–90%. Late meatal stenosis, necrosis, pain, ED. Salvage surgery possible. EAU option if surgery refused."],
        ["Total phallic reconstruction later", "After total penectomy in a young 50-year-old who wants sex", "RFFF phalloplasty + IPP — delayed, high morbidity, mention as reconstruction not cancer therapy"],
      ]},
      { t: "p", v: "Groins are independent of organ-spare: a T1b glansectomy still needs DSLNB/mILND. Results: cancer-specific survival is comparable to amputative surgery when margins are negative and groins are staged. Local recurrence is higher than partial penectomy and is not a failure if follow-up is rigid (3-monthly year 1–2). The 50-year-old with a 1.5 cm G2 glans lesion is the ideal glansectomy + graft + DSLNB patient." },
      { t: "tip", k: "gold", v: "Organ-spare is for distal ≤T2 with frozen margins and a man who will attend clinic. Glans resurfacing and glansectomy are the modern operations. Groins still follow the risk algorithm." },
    ],
  },
  {
    id: "ca-penis-nonsquamous",
    topicId: "penis",
    title: "Non-squamous malignant neoplasms of the penis",
    highYield: false,
    gold: false,
    tags: ["sarcoma", "melanoma", "BCC", "extramammary Paget"],
    exams: [
      { session: "Dec", year: 2012, marks: "2+8", stem: "Enumerate non-squamous malignant neoplasm of penis. Discuss the management of non-squamous malignant neoplasm of penis." },
    ],
    related: ["ca-penis-staging", "penile-prosthesis"],
    references: ["WHO GU 2022", "EAU Penile Cancer (rare tumours)", "Campbell-Walsh-Wein"],
    answer: [
      { t: "p", v: "SCC is >95% of penile malignancy. Non-squamous lesions are case-report-level in exam practice — enumerate, then say management is histology-specific and usually surgical with specialised oncology." },
      { t: "tbl", h: ["Entity", "Clues", "Management"], r: [
        ["Basal-cell carcinoma", "Shaft/sun-exposed, rolled edge", "WLE, almost never nodes"],
        ["Melanoma", "Glans/meatus pigment, amelanotic trap", "WLE with melanoma margins, SLNB per cutaneous melanoma rules, staging CT/PET, checkpoint inhibitors / BRAF if advanced. Poor if delayed."],
        ["Sarcomas: leiomyosarcoma (deep cavernosa), Kaposi (HHV8, HIV, purple plaques), angiosarcoma, epithelioid sarcoma, rhabdomyosarcoma (child)", "Deep mass, HIV test for Kaposi", "Wide excision / partial-total penectomy; RT/chemo per sarcoma MDT. Kaposi: HAART ± local. RMS: paediatric protocol (COG/SIOP), not primary mutilation first."],
        ["Extramammary Paget (often scrotal/penile base)", "Weeping eczema, CK7+, look for underlying GU/GI adeno", "Map biopsies, WLE / Mohs, screen bladder/prostate/colon"],
        ["Urethral / urothelial carcinoma presenting on glans", "Central meatal", "Manage as urethral cancer (stage, urethrectomy ± penectomy, CIS of bladder)"],
        ["Metastases to penis (prostate, bladder, colon, kidney — Priapism malignant)", "Known primary, corporal infiltration", "Palliative RT, AND-blockade if prostate; rarely surgery"],
        ["Lymphoma / leukaemic infiltrate", "Bilateral, systemic", "Biopsy, systemic therapy — not penectomy"],
        ["Verrucous carcinoma (Ackerman) — a well-diff SCC variant, sometimes listed separately", "Locally destructive, rare mets", "WLE / penectomy; groins observe unless invasive usual-type mixed"],
      ]},
      { t: "tip", k: "exam", v: "Enumerate BCC, melanoma, sarcomas (incl. Kaposi), Paget, mets, lymphoma, urethral adeno. Management = histology + MDT; do not apply SCC groin algorithms blindly to BCC or lymphoma." },
    ],
  },
  {
    id: "fracture-penis",
    topicId: "penis",
    title: "Penile fracture — aetiology, diagnosis, management",
    highYield: true,
    gold: false,
    tags: ["tunica albuginea", "eggplant", "Buck fascia", "urethra"],
    exams: [
      { session: "Jun", year: 2019, marks: "(2+2+2)+4", stem: "Etiology, pathology and diagnosis of fracture penis. Discuss various options of management indicating their outcome." },
      { session: "Dec", year: 2016, marks: "4+6", stem: "Aetiology and mechanism of penile fracture. Role of diagnostic methods and surgical management of penile fracture." },
    ],
    related: ["peyronie", "penis-anatomy-ca", "erection-hemodynamics"],
    references: [
      "EAU Urological Trauma",
      "AUA Urotrauma",
      "Campbell-Walsh-Wein, Penile trauma",
    ],
    answer: [
      { t: "p", v: "Penile fracture is rupture of the tunica albuginea of one or both corpora cavernosa of the erect penis. A urologic emergency. Classic: coital trauma, a snap, immediate detumescence, pain, eggplant (aubergine) deformity, rolling sign (haematoma localised by intact Buck). Urethral injury in 10–30% (blood at meatus, inability to void, bilateral corporal rupture)." },
      { t: "h", v: "Aetiology and mechanism" },
      { t: "ul", v: [
        "Tunica thins from 2 mm flaccid to 0.25–0.5 mm erect and is then vulnerable to an abrupt lateral bend. Intracavernosal pressure of a rigid erection exceeds tunical tensile strength when sheared.",
        "Coitus: woman-on-top and rear-entry are the usual positions (penis slips out and strikes perineum/pubis). Masturbation, rolling in bed, ‘taqaandan’ (intentional bending, Middle East) — the last produces a typical ventral tear.",
        "The tear is usually transverse, 1–2 cm, distal shaft, ventrolateral (the tunica is thinner ventrally beside the urethra). Buck intact → penile haematoma; Buck breached → scrotal/perineal butterfly.",
        "False fracture: dorsal-vein rupture (no snap, slower haematoma, erection may persist) — still often explored.",
      ]},
      { t: "h", v: "Diagnosis" },
      { t: "ul", v: [
        "Clinical in the classic history — do not delay theatre for a pretty MRI if the story is textbook.",
        "US: tunical discontinuity, haematoma. Operator-dependent, useful if equivocal.",
        "MRI: gold for equivocal cases (can spare a negative exploration) — T2 tunical gap. Not mandatory.",
        "Cavernosography is obsolete (false negatives, contrast fibrosis).",
        "Urethra: if blood at meatus, haematuria, retention, or bilateral rupture → RGU before or on-table cystoscopy. Do not clamp a catheter blindly through a half-transected urethra.",
      ]},
      { t: "h", v: "Management and outcomes" },
      { t: "ul", v: [
        "Immediate surgical repair beats delayed/conservative: less ED, less Peyronie-like curve, less infected haematoma. Conservative (ice, diazepam, catheter) is reserved for truly delayed presentation with a small, already-organising defect, or refused surgery — curve/ED 30–50% vs <10–15% after prompt repair.",
        "Technique: circumferential degloving (or direct longitudinal over the defect if precisely imaged). Evacuate clot, irrigate, close tunica with buried 2-0/3-0 delayed absorbable (PDS) — watertight, no constriction. Artificial erection to find a second tear. Spare NVB. Urethral repair overlapping, spatulated, 4-0 absorbable, catheter 10–14 days if urethral injury.",
        "Post-op: compressive dressing, void, abstain 4–6 weeks, PDE5 later if ED. Counsel Peyronie-like plaque in 5–15% even after good repair.",
        "Delayed presentation (weeks): still explore if a gap is felt; otherwise treat residual curve as Peyronie once stable.",
      ]},
      { t: "tip", k: "gold", v: "Snap + detumescence + eggplant = theatre. Look at the urethra if both corpora are down or the meatus bleeds. Repair the tunica; do not send him home on diazepam." },
    ],
  },
  {
    id: "penile-prosthesis",
    topicId: "penis",
    title: "Penile prosthesis — types, three-piece IPP, biofilms",
    highYield: true,
    gold: false,
    tags: ["IPP", "malleable", "biofilm", "Wilson modelling"],
    exams: [
      { session: "Jun", year: 2017, marks: "3+3+4", stem: "Components, indications & technique of placement of three-piece penile prosthesis (inflatable)." },
      { session: "Dec", year: 2011, marks: "5+5", stem: "Describe the types of penile-prosthesis used in managing erectile dysfunction. What are bio-films with regards to urologic prostheses?" },
      { session: "Jun", year: 2015, marks: "2+4+4", stem: "Different types of penile prosthesis. Indications and complications of implantation of penile prosthesis." },
      { session: "Dec", year: 2013, marks: "5+5", stem: "Describe the mechanism and clinical outcome of inflatable penile implant." },
    ],
    related: ["vasculogenic-ed", "ed-after-rp", "peyronie", "priapism"],
    references: [
      "EAU Sexual and Reproductive Health — prosthesis",
      "ISSM / SMSNA implant best practice",
      "Wilson / Mulcahy salvage; Henry no-touch",
      "Campbell-Walsh-Wein, Penile prosthesis",
    ],
    answer: [
      { t: "h", v: "Types" },
      { t: "tbl", h: ["Type", "Examples", "Pros", "Cons"], r: [
        ["Malleable / semi-rigid (one-piece rods)", "Spectra, Genesis, AMS Spectra", "Simple, cheap, few mechanical failures, good in neurogenic / low-dexterity / salvage after infection / acute ischaemic priapism", "Permanently firm, concealment poor, erosion higher in insensate (SCI)"],
        ["Mechanical posable (Omni/Dura-II historic)", "—", "Posable", "Mostly historical"],
        ["Two-piece inflatable", "Ambicor", "Pump + cylinders, no separate reservoir — good if pelvis hostile (kidney transplant, neobladder)", "Less rigid/flaccid than 3-piece"],
        ["Three-piece inflatable (gold standard)", "AMS 700 CX/LGX, Coloplast Titan", "Best rigidity and flaccidity, patient satisfaction 80–90%+", "Reservoir complications, 3 components to fail, infection 1–3% first-time in expert hands"],
      ]},
      { t: "h", v: "Three-piece IPP — components, indications, technique" },
      { t: "ul", v: [
        "Components: paired inflatable cylinders (controlled expansion CX vs length-expanding LGX; hydrophilic Coloplast vs InhibiZone minocycline/rifampin AMS), scrotal pump with lock-out, reservoir (80–100 mL) in space of Retzius or ectopic high-submuscular (more after RP when Retzius is scarred).",
        "Indications: organic ED refractory or intolerant to PDE5/ICI/VED; PD + ED; post-priapism fibrosis; phalloplasty (delayed); selected psychogenic after failed therapy. Not a first-line 30-year-old with performance anxiety.",
        "Technique (penoscrotal, most common): dorsal lithotomy or supine, 2–3 cm raphe incision, stay sutures on tunica, corporotomies, Furlow + Brooks dilation to 8–14 mm, measure proximal/distal, choose cylinder length + rear-tip extenders, fill, seat pump in dependent scrotum, reservoir bluntly into Retzius through the inguinal ring (empty bladder!) or ectopic, isolate components, copious antibiotic irrigation, multilayer closure, leave semi-inflated 24 h. No-touch (Ehlers/Froelich/Henry): skin isolated after incision, new kit, infection <1%. Alternative infrapubic approach.",
        "PD: Wilson modelling on the inflated implant. Fibrosis (priapism, infection salvage): cavernotomes, downsized cylinders, sometimes grafting; higher perforation/erosion.",
      ]},
      { t: "h", v: "Outcomes and complications" },
      { t: "ul", v: [
        "Satisfaction 80–95% when expectations are managed (it is not a 22-year-old spontaneous penis; glans is not inflated — ‘cold glans’, use PDE5/ICI for glans if needed).",
        "Infection 1–3% virgin, 10%+ revision. Diabetes, SCI, revision are risks. Presentation: pain, fixation of pump, erosion, pus. Mulcahy salvage (remove, copious sequential antiseptic irrigation, immediate replace) success ~80% in selected. Otherwise explant, 3–6 months, re-implant into fibrotic corpora.",
        "Mechanical failure 5–15% at 10 years (tubing, aneurysm, leak) — revisable. Auto-inflation (old reservoirs without lock-out). Crossover, proximal/distal perforation (repair, rear-tip sling, abort that side if urethral).",
        "Erosion (distal, urethra) — insensate, oversized, infection. Reservoir: bladder/bowel injury, hernia, viscus erosion (rare).",
        "SST deformity, S-shaped penis, floppy glans — technique/sizing.",
      ]},
      { t: "h", v: "Biofilms on urologic prostheses (Dec 11)" },
      { t: "p", v: "A biofilm is a structured community of bacteria (or fungi) adherent to a prosthetic surface and encased in self-produced extracellular polymeric substance (EPS: polysaccharide, protein, DNA). On IPP, AUS, ureteral stents, catheters. Staphylococci (S. epidermidis, S. aureus) dominate implants; Gram-negatives and Candida in diabetics/revisions." },
      { t: "ul", v: [
        "Consequences: sessile bacteria are 100–1000× less antibiotic-susceptible (slow growth, EPS diffusion barrier, persister cells). Culture-negative ‘aseptic’ pain may be biofilm. Mechanical valves can stick.",
        "Prevention: peri-op Gram-positive + Gram-negative Abx (AUA: aminoglycoside + vancomycin or cefazolin ± gentamicin), coated/hydrophilic devices soaked in Abx, no-touch, chlorhexidine skin, glycaemic control, stop smoking, short operative time, glove change, drain optional.",
        "Treatment: planktonic Abx alone will not sterilise a mature implant biofilm — explant ± Mulcahy salvage. Sonication of explanted devices raises culture yield.",
      ]},
      { t: "tip", k: "gold", v: "Three-piece IPP is the gold standard for end-stage ED. Infection is a biofilm disease: prevention is technical, salvage is Mulcahy, antibiotics without explant are theatre." },
    ],
  },
];
