import type { Master } from "../types";

export const prostate: Master[] = [
  {
    id: "prostate-anatomy-mcneal",
    topicId: "prostate",
    title: "Embryology, McNeal zonal anatomy, arteries, lymph and PSA surrogates",
    highYield: true,
    gold: true,
    tags: ["McNeal", "TZ", "PZ", "PSA", "phi", "4K"],
    exams: [
      { session: "June", year: 2022, marks: "4+3+3", stem: "Discuss the embryology of the Prostate gland. Describe the McNeal's Zonal anatomy of the prostate. Describe the surrogate markers that can be used for the evaluation of a patient who has a PSA of 7 ng/ml." },
      { session: "Dec", year: 2012, marks: "3+4+3", stem: "Draw a diagram of zonal anatomy of prostate gland. Discuss its arterial supply and lymphatic drainage." },
      { session: "Jun", year: 2021, marks: "4+6", stem: "What are different histological and anatomical zones of prostate? How do you manage the enlarged median lobe of prostate in different surgeries for prostate?" },
      { session: "Dec", year: 2015, marks: "10", stem: "Surgical anatomy of the prostate gland as relevant to open radical prostatectomy." },
    ],
    related: ["mpmri-pirads", "molecular-markers-pca", "millin", "retzius-sparing"],
    references: [
      "McNeal JE. Am J Surg Pathol / Campbell Anatomy of the prostate",
      "EAU PCa — biomarkers",
      "Hinman / Walsh radical prostatectomy anatomy",
    ],
    answer: [
      { t: "h", v: "Embryology" },
      { t: "p", v: "At ~week 10–12, urogenital-sinus epithelium buds into surrounding androgen-dependent mesenchyme (urogenital sinus mesenchyme) under DHT (5α-reductase type 2) to form prostatic ducts. Skene glands are the female homologue. The verumontanum / ejaculatory ducts are Wolffian (mesonephric). Congenital absence of the prostate tracks with disorders of DHT / AR." },
      { t: "h", v: "McNeal zones (draw this)" },
      { t: "tbl", h: ["Zone", "% gland (young)", "Disease", "Surgical note"], r: [
        ["Peripheral (PZ)", "~70%", "70–80% of adenocarcinomas", "Posterolateral; NVB runs at 5 and 7 o’clock in the lateral pelvic fascia — nerve-sparing plane"],
        ["Transition (TZ)", "~5% young; the BPH zone", "20% of CaP; almost all BPH adenomas", "TURP / enucleation plane is the surgical capsule = compressed PZ"],
        ["Central (CZ)", "~25%", "~5% CaP; surrounds ejaculatory ducts", "Base tumours, seminal-vesicle invasion pathway"],
        ["Anterior fibromuscular stroma", "Non-glandular", "Rare cancer", "Retzius-sparing / anterior tumours hide here from DRE"],
        ["Preprostatic sphincter / periurethral glands", "Tiny", "Median lobe BPH from submucosal glands", "Bladder-neck issues"],
      ]},
      { t: "p", v: "Histologic zones vs anatomic lobes (Lowsley): lobes are a surgical/clinical language (median, lateral, anterior); zones are the biologic map. Median lobe = periurethral / TZ tissue projecting through the BN." },
      { t: "h", v: "Arterial supply" },
      { t: "ul", v: [
        "Inferior vesical artery (internal iliac) → prostatic arteries: urethral (Flocks) group at BN 1 and 11 o’clock (the TURP bleeders) and capsular group posterolateral with the NVB.",
        "Contributions: middle rectal, internal pudendal. Accessory pudendal arteries — preserve in RP for erectile function.",
        "Venous: Santorini dorsal venous complex over the striated sphincter — the RP first move after apical dissection planning; Millin / retropubic enucleation also meets DVC.",
      ]},
      { t: "h", v: "Lymphatic drainage" },
      { t: "p", v: "Primary: obturator, internal iliac, external iliac, sacral / presacral. Secondary: common iliac, para-aortic. Not primarily inguinal. PLND templates in PCa (limited vs extended to ureter crossing / common iliac) follow this map. Sentinel techniques exist but are not standard." },
      { t: "h", v: "Open RP surgical anatomy (Dec 15)" },
      { t: "ul", v: ["Endopelvic fascia, puboprostatic ligaments, DVC, apical rhabdosphincter (continence), NVB in lateral pelvic fascia (Walsh), Denonvilliers between prostate and rectum, SV/vas at the base, bladder neck, ureteric orifices 1 cm from BN", "Rocco posterior reconstruction, urethral length, nerve-sparing grades"] },
      { t: "h", v: "Median lobe in different operations" },
      { t: "ul", v: [
        "TURP / bipolar / HoLEP: identify the lobe, trench at 5 and 7, drop the lobe into the bladder, enucleate / resect last so it does not hide the ureteric orifices; HoLEP is excellent for large median lobes.",
        "Open Millin: enucleate with the rest of the adenoma after BN incision; stitch the BN 5 and 7 (trigonisation) to prevent retraction / obstruction.",
        "Simple robotic / lap: hitch the lobe, identify orifices (IV indigo / ICG), reconstruct BN.",
        "RP for cancer: a large median lobe makes BN sparing harder — reconstruct, do not leave adenoma.",
        "PAE: median lobe responds less reliably than lateral TZ — counsel.",
      ]},
      { t: "h", v: "PSA 7 ng/mL — surrogate / reflex markers" },
      { t: "p", v: "Total PSA 7 is in the grey zone (historically 4–10). Before biopsy, use pre-test probability (DRE, age, family, race, medications, prostatitis, MRI)." },
      { t: "tbl", h: ["Marker", "What it is", "Use at PSA ~7"], r: [
        ["% free PSA", "Free/total; <10% CaP-likely, >25% less likely", "Cheap reflex"],
        ["PSA density", "PSA / prostate volume; ≥0.15 concerning", "Use MRI or US volume"],
        ["PSA velocity / doubling", "Kinetics", "Better in surveillance than one-off"],
        ["phi ([-2]proPSA, free, total)", "phi >27–35 raises PCa probability", "Avoid unnecessary biopsy"],
        ["4Kscore (tPSA, fPSA, iPSA, hK2 + clinical)", "High-grade risk %", "Reduces biopsy; not a cancer volume map"],
        ["SelectMDx, ExoDx, Stockholm3, PCA3 (post-DRE urine)", "mRNA / panels", "PCA3 better known after negative biopsy"],
        ["mpMRI PI-RADS", "Anatomic surrogate", "Now the dominant ‘marker’ before first biopsy (EAU)"],
        ["ConfirmMDx (tissue)", "Epigenetic on negative cores", "After negative biopsy, not at first PSA 7"],
      ]},
      { t: "tip", k: "gold", v: "BPH is TZ; cancer is PZ. Draw McNeal. PSA 7 → density + %free + MRI, not an automatic TRUS biopsy in 2020s answers." },
    ],
  },
  {
    id: "pin-t3-lu177",
    topicId: "prostate",
    title: "PIN, T3 prostate cancer and Lu-177 PSMA",
    highYield: true,
    gold: false,
    tags: ["HGPIN", "T3", "Lu-177", "VISION", "PSMA"],
    exams: [
      { session: "June", year: 2022, marks: "4+3+3", stem: "Write a short note on PIN (Prostate Intraepithelial Neoplasia). Discuss the management of a 72 year old diabetic and hypertensive patient with stage 3 Ca prostate. Discuss the role of Lutetium 177 Radio nuclide in Ca prostate." },
    ],
    related: ["psma-lu", "pet-pca", "high-risk-pca", "mhspc", "crpc"],
    references: [
      "WHO GU — PIN / intraductal",
      "EAU / AUA locally advanced PCa",
      "VISION (Sartor NEJM 2021), TheraP",
      "STAMPEDE / RADICALS-HD",
    ],
    answer: [
      { t: "h", v: "PIN" },
      { t: "p", v: "Prostatic intraepithelial neoplasia is architecturally benign ducts lined by cytologically atypical cells with a still-present (patchy) basal layer (p63/CK5/6+). High-grade PIN (HGPIN) shares nuclear features with cancer. Low-grade PIN should not be reported. Isolated HGPIN on modern extended biopsy has only a modest risk of later cancer (10–20%) — it is no longer an automatic re-biopsy trigger; MRI and residual risk decide. Distinguish intraductal carcinoma (IDC-P): dense cribriform / comedonecrosis filling ducts, retains basal cells, marks aggressive cancer, treat as high-risk disease not as PIN." },
      { t: "h", v: "72-year-old diabetic hypertensive with stage III (T3) CaP" },
      { t: "p", v: "T3 = extraprostatic extension (T3a) or seminal-vesicle invasion (T3b). This is high-risk / locally advanced. Age 72 with comorbidity does not automatically mean ADT forever — life expectancy and Charlson matter." },
      { t: "ul", v: [
        "Stage: mpMRI, PSMA PET-CT (replaces bone scan + CT in many guidelines for high-risk), PSA, biopsy Gleason / ISUP, comorbidities, continence / erectile goals.",
        "If M0 on PSMA: options are (1) RT to prostate ± pelvis + long-term ADT 18–36 mo (EBRT, consider brachy boost in selected) (2) RP + extended PLND in a fit 72-year-old with resectable T3a, expecting adjuvant / early salvage RT ± ADT (RADICALS, RAVES, GETUG-AFU17 — early salvage is often enough if margins/PSA watched) (3) do not offer WW if high-risk and life expectancy >10 y.",
        "If N1: RT + long ADT ± abiraterone (STAMPEDE M0 N+ / high-risk) or surgery in highly selected.",
        "If the ‘stage 3’ actually hides M1: treat as mHSPC (ADT + ARPI ± docetaxel; metastasis-directed in oligomet).",
        "Diabetes / HTN: prefer GnRH antagonist (degarelix / relugolix) or carefully monitored agonist; watch metabolic syndrome of ADT; abiraterone needs prednisone and BP/K monitoring — choose enzalutamide / apalutamide / darolutamide with care (falls, cognition) or docetaxel if visceral. Involve cardiology.",
      ]},
      { t: "h", v: "Lu-177 PSMA" },
      { t: "p", v: "Lutetium-177 coupled to a PSMA ligand (PSMA-617 in VISION; PSMA I&T in other programmes) is a β-emitter radioligand. PSMA (FOLH1) is a transmembrane folate-hydrolase overexpressed on most PCa cells. The ligand binds, is internalised, and 177Lu delivers millimetre-range β radiation. Imaging gate: 68Ga/18F-PSMA PET must show PSMA-avid disease; FDG-discordant cold lesions are a TheraP caution." },
      { t: "ul", v: [
        "VISION (mCRPC after ARPI and taxane): 177Lu-PSMA-617 + SOC vs SOC: rPFS 8.7 vs 3.4 mo, OS 15.3 vs 11.3 mo.",
        "TheraP vs cabazitaxel: better PSA50 and fewer grade 3–4 AE.",
        "Toxicities: dry mouth (salivary PSMA), dry eye, fatigue, nausea, myelosuppression, rare renal. Not first-line mHSPC (trials ongoing: PSMAddition, UpFrontPSMA).",
        "Role in a T3 M0 72-year-old: none as primary therapy. Role is mCRPC (and evolving earlier).",
      ]},
      { t: "tip", k: "gold", v: "HGPIN ≠ cancer; IDC-P ≈ high-risk cancer. T3 M0: RT + long ADT or RP in the fit. Lu-177 is a VISION-era mCRPC drug, not a T3 drug." },
    ],
  },
  {
    id: "mpmri-pirads",
    topicId: "prostate",
    title: "mpMRI, PI-RADS 2.1 and MRI-targeted biopsy",
    highYield: true,
    gold: true,
    tags: ["PI-RADS", "mpMRI", "fusion", "PRECISION"],
    exams: [
      { session: "June", year: 2022, marks: "5+5", stem: "Discuss Multiparametric MRI status in the evaluation of Ca Prostate. Discuss the PIRAD 2.1 classification system and how it differs from earlier version." },
      { session: "Jun", year: 2018, marks: "10", stem: "Multi parametric magnetic resonance imaging (MRI): Its use in cancer prostate." },
      { session: "Dec", year: 2017, marks: "10", stem: "What are the techniques of using MRI in performing prostate biopsies?" },
      { session: "Jun", year: 2016, marks: "4+6", stem: "What is multi-parametric MRI? What are its indications in Urology?" },
      { session: "Jun", year: 2021, marks: "4+2+4", stem: "Describe role of mp-MRI in Carcinoma Prostate and its timing in relation to TRUS Biopsy. How the new version of PI-RADS score is different from earlier version?" },
      { session: "Jun", year: 2020, marks: "5+5", stem: "PI-RADS. Role of mp-MRI in management of carcinoma prostate." },
      { session: "Dec", year: 2021, marks: "5+5", stem: "Fusion MRI in prostate cancer. PSMA (prostate specific membrane antigen) PET-CT in prostate cancer." },
    ],
    related: ["trus-biopsy", "as-pca", "pet-pca", "prostate-anatomy-mcneal"],
    references: [
      "PI-RADS v2.1 (ACR 2019)",
      "PRECISION, PROMIS, MRI-FIRST, 4M",
      "EAU PCa 2025 — MRI before biopsy",
      "Campbell Imaging of PCa",
    ],
    answer: [
      { t: "p", v: "mpMRI is T2-weighted anatomy + diffusion-weighted imaging (DWI/ADC) + dynamic contrast enhancement (DCE), scored with PI-RADS, to detect clinically significant PCa (csPCa, usually ISUP ≥2). PROMIS: MRI sensitivity > TRUS biopsy for csPCa, NPV ~70–90% depending on prevalence. PRECISION: MRI-targeted biopsy vs standard 12-core: more csPCa, less insignificant cancer. EAU: offer MRI before first biopsy." },
      { t: "h", v: "Sequences and when to scan" },
      { t: "ul", v: [
        "T2: zonal anatomy, EPE, SV. DWI/ADC: the dominant sequence in PZ. DCE: rescue sequence when DWI is poor; needed for full mpMRI (biparametric = T2+DWI, no contrast — emerging).",
        "Timing vs biopsy: MRI before first biopsy (preferred). After biopsy wait ≥6–8 weeks (haemorrhage T1 shine-through). After negative biopsy MRI is mandatory before a second look. Staging MRI can follow a positive biopsy.",
        "Other urologic indications of mpMRI: AS eligibility/triggers, targeted focal therapy planning, recurrence after RT (with PET), surgical planning (NVB, apex), NIDDK-style prostatitis not a standard indication.",
      ]},
      { t: "h", v: "PI-RADS v2.1 — the score" },
      { t: "tbl", h: ["Score", "Meaning", "Action"], r: [
        ["1–2", "csPCa highly / unlikely", "Usually no immediate biopsy if quality MRI + low PSA-D; shared decision"],
        ["3", "Equivocal", "Biopsy if PSA-D ≥0.15 or other risk; PZ uses DWI, TZ uses T2 as dominant"],
        ["4", "csPCa likely", "Targeted + systematic biopsy"],
        ["5", "csPCa highly likely (or definite EPE)", "Biopsy; staging"],
      ]},
      { t: "h", v: "v2.1 vs v2 / v1" },
      { t: "ul", v: [
        "v1 (2012): sum of T2+DWI+DCE+spectroscopy — cumbersome.",
        "v2 (2015): dominant sequence concept (DWI in PZ, T2 in TZ); DCE only upgrades PZ 3→4; dropped spectroscopy; 5-point overall.",
        "v2.1 (2019): clarifies TZ (typical BPH nodules scored 2; atypical 3), DWI 2 vs 3 criteria, measurement of ADC, DCE ‘positive’ = early focal enhancement, revision of sector map (adds a posteromedial distal TZ etc.), typical BPH not overcalled as 4. Aim: fewer false-positive TZ 3s and more reproducible DWI.",
      ]},
      { t: "h", v: "MRI-biopsy techniques (Dec 17 / fusion)" },
      { t: "tbl", h: ["Method", "How", "Pearl"], r: [
        ["Cognitive fusion", "Operator aims TRUS at the MRI lesion using landmarks", "Cheap; operator-dependent"],
        ["Software MRI–TRUS fusion (rigid/elastic)", "Contour MRI, overlay live TRUS (Koelis, UroNav, Artemis)", "Documented targets; still miss registration error"],
        ["In-bore MRI biopsy", "Directly in the scanner", "Accurate, slow, costly, few cores"],
        ["Transperineal vs transrectal", "Template ± targeted; TP lower sepsis", "EAU moving to TP"],
      ]},
      { t: "p", v: "Always combine targeted cores (2–4 per lesion) with systematic cores in biopsy-naïve men (MRI-FIRST, 4M) — MRI misses ~10–15% of csPCa, often small / anterior / multifocal. After a negative MRI, biopsy if high PSA-D, high PSA, high risk." },
      { t: "tip", k: "gold", v: "MRI before first biopsy. PI-RADS 2.1: DWI rules PZ, T2 rules TZ, DCE only upgrades PZ 3. Targeted plus systematic. Fusion is a registration method, not a diagnosis." },
    ],
  },
  {
    id: "trus-biopsy",
    topicId: "prostate",
    title: "TRUS-guided prostate biopsy",
    highYield: false,
    gold: false,
    tags: ["TRUS", "sepsis", "transperineal"],
    exams: [
      { session: "Dec", year: 2014, marks: "10", stem: "TRUS guided prostate biopsy — instruments, patient-preparation, procedure and complications." },
    ],
    related: ["mpmri-pirads", "psa-screening"],
    references: ["EAU PCa biopsy", "AUA / AUA quality improvement sepsis", "Campbell Prostate biopsy"],
    answer: [
      { t: "ul", v: [
        "Instruments: 7.5 MHz biplane / end-fire probe, needle guide, 18G 25 cm spring gun, 16–20 cm cores, condom, local (periprostatic 1% lidocaine at NVB / apex), optional stepper for TP.",
        "Preparation: stop anticoagulants per risk, urine culture if UTI symptoms, informed sepsis / retention / haematuria / haematospermia / ED rare. TR: targeted prophylaxis by rectal swab or augmented (fluoroquinolone era is over — use ceftriaxone / aminoglycoside / fosfomycin per local antibiogram) plus enema optional. TP: standard peri-op dose, virtually no sepsis — preferred.",
        "Procedure (TR 12-core extended): left lateral, periprostatic block, cores from base/mid/apex parasagittal and lateral each side ± MRI targets. Label sites. Avoid urethra.",
        "Complications: haematuria 50% (days), haematospermia weeks, rectal bleed, retention 1–2%, vasovagal, UTI 2–5%, sepsis 1–3% TR (<<1% TP), rare osteomyelitis / fistula, needle-track seeding almost never.",
      ]},
      { t: "tip", k: "exam", v: "Say ‘transperineal is the 2020s default to kill sepsis’ even if the stem says TRUS." },
    ],
  },
  {
    id: "pet-pca",
    topicId: "prostate",
    title: "PET imaging in prostate cancer",
    highYield: true,
    gold: true,
    tags: ["PSMA", "choline", "fluciclovine", "FDG"],
    exams: [
      { session: "Dec", year: 2020, marks: "5+5", stem: "What are the different types of Positron Emission Tomography in men with prostate cancer? What is the role of each in cancer prostate?" },
      { session: "Jun", year: 2019, marks: "4+3+3", stem: "What is prostate specific membrane antigen (PSMA)? Discuss role of PSMA PET CT Scan in diagnosis and follow up of adenocarcinoma of prostate." },
      { session: "Jun", year: 2017, marks: "4+6", stem: "What is PSMA PET? What is its principle? What are its potential indications and limitations?" },
      { session: "Jun", year: 2015, marks: "10", stem: "Advantages and limitations of various PET scans used in cases of carcinoma prostate." },
      { session: "Dec", year: 2021, marks: "5", stem: "PSMA (prostate specific membrane antigen) PET-CT in prostate cancer." },
    ],
    related: ["psma-lu", "pin-t3-lu177", "bcr-penile-rehab", "oligomet-pca", "radionuclides-pca"],
    references: [
      "EAU PCa staging / BCR",
      "proPSMA (Hofman Lancet 2020)",
      "VISION / TheraP imaging gates",
      "Campbell Nuclear imaging",
    ],
    answer: [
      { t: "p", v: "PSMA is a type-II transmembrane glutamate carboxypeptidase (FOLH1, NAALADase) with enzymatic folate-hydrolase activity, overexpressed 100–1000× on PCa cell membranes (and on salivary, lacrimal, proximal tubule, ganglia, neo-vessels of some tumours). Ligands (HBED-CC for 68Ga-PSMA-11; DCFPyL 18F; PSMA-1007 18F) are internalised, trapping the positron emitter." },
      { t: "tbl", h: ["Tracer", "Principle", "Role", "Limitation"], r: [
        ["68Ga-PSMA-11 / 18F-DCFPyL / 18F-PSMA-1007", "PSMA ligand", "Primary staging high-risk (proPSMA > bone scan+CT); BCR at low PSA (detection ~40% at PSA 0.2–0.5, ~70% at 1.0); therapy selection for Lu-177; targeted salvage", "Urinary excretion (11, DCFPyL) hides pelvis — 1007 is hepatobiliary. False + ganglia, sarcoid, rib fractures, benign prostate. Occult PSMA-negative dedifferentiated CRPC"],
        ["11C-choline / 18F-fluorocholine", "Membrane phospholipid synthesis", "Historic BCR tracer; still used if no PSMA", "Needs on-site cyclotron for 11C; inferior to PSMA at PSA <1"],
        ["18F-fluciclovine (Axumin)", "Amino-acid (LAT1) transport", "FDA BCR; less urinary activity", "Inferior to PSMA in head-to-heads"],
        ["18F-FDG", "Glycolysis", "Little in hormone-sensitive PCa; useful in aggressive / neuroendocrine / PSMA-negative CRPC (TheraP dual-tracer)", "Not a staging tool for typical PCa"],
        ["18F-NaF", "Bone mineral", "Bone mets sensitivity", "No soft tissue; superseded by PSMA for most"],
        ["18F-FDHT / others", "AR imaging", "Research"],
      ]},
      { t: "ul", v: [
        "Not for routine low-risk staging. Does not replace mpMRI for intraprostatic localisation before biopsy (though PSMA-MRI is research-hot).",
        "Follow-up: rising PSA after RP/RT — PSMA PET guides metastasis-directed therapy and whether salvage fossa RT is rational (if PET-N0/M0, still irradiate the fossa at low PSA because micromets are below PET resolution).",
      ]},
      { t: "tip", k: "gold", v: "PSMA PET owns staging of high-risk and BCR. Quote proPSMA. FDG is for the angry, PSMA-cold CRPC clone." },
    ],
  },
  {
    id: "as-pca",
    topicId: "prostate",
    title: "Active surveillance in prostate cancer",
    highYield: true,
    gold: true,
    tags: ["AS", "ISUP 1", "PRIAS", "ProtecT"],
    exams: [
      { session: "Dec", year: 2022, marks: "5+5", stem: "How will you select a patient for active surveillance in prostate cancer disease? What are the components of Active surveillance protocol for prostate cancer disease and how frequently that is to be planned?" },
      { session: "Dec", year: 2018, marks: "3+4+3", stem: "Active surveillance in cancer prostate- Indications, follow up protocol and clinical outcome." },
      { session: "Dec", year: 2014, marks: "3+3+4", stem: "Patient selection, protocol and rationale of active surveillance for carcinoma prostate." },
    ],
    related: ["mpmri-pirads", "gleason", "psa-screening"],
    references: [
      "EAU / AUA / NCCN AS criteria",
      "PRIAS, Johns Hopkins, Toronto (Klotz), ProtecT",
      "Campbell Localised PCa",
    ],
    answer: [
      { t: "p", v: "Active surveillance (AS) is a curative-intent strategy: monitor closely and trigger treatment if the disease reclassifies. Watchful waiting is palliative (treat symptoms / ADT when they appear). ProtecT: at 15 y, prostate-cancer death was ~3% in all of surgery, RT and active monitoring for screen-detected localised disease — the rationale." },
      { t: "h", v: "Selection (EAU-favourable)" },
      { t: "ul", v: [
        "Ideal: ISUP 1 (GS 3+3), cT1–T2a, PSA <10, PSAD <0.15, ≤2–3 cores or ≤16% involvement, MRI PI-RADS ≤3 or targeted-negative, life expectancy ≥10 y (otherwise WW).",
        "Selected ISUP 2 (3+4) with low pattern-4 %, PSA <10, MRI concordant — unit-dependent; counsel higher conversion.",
        "Exclude: cribriform / IDC-P, ≥T2c, high PSAD, discordant MRI large PI-RADS 5, patient preference for immediate treatment, inability to follow protocol.",
        "Confirm with MRI + targeted/systematic biopsy if the diagnostic biopsy was TRUS-only.",
      ]},
      { t: "h", v: "Protocol — components and timing" },
      { t: "tbl", h: ["Item", "Cadence (typical PRIAS / EAU)"], r: [
        ["PSA", "3-monthly for 1–2 y then 6-monthly"],
        ["DRE", "Annually (and if PSA triggers)"],
        ["mpMRI", "Baseline; 12 months; then 1–3 yearly or on trigger"],
        ["Repeat biopsy", "Confirmatory within 12 months if no MRI-targeted first; then at 3 y / 5 y or on MRI/PSA trigger — many units now MRI-triggered rather than protocol 12-core forever"],
        ["Triggers to treat", "Reclassification to ISUP ≥2 (or ≥3), volume increase, PSA-DT <3 y (softer trigger), MRI progression (PRECISE score), patient choice"],
      ]},
      { t: "h", v: "Outcome" },
      { t: "ul", v: ["Metastasis and PCa-death <1–3% at 10–15 y in well-picked ISUP 1", "Conversion to active treatment 30–50% at 10 y — that is AS working, not failing", "Over-treatment avoided: continence and erection preserved in those who stay on AS"] },
      { t: "tip", k: "gold", v: "AS is for ISUP 1, MRI-concordant, compliant men. It is not WW. Confirmatory MRI ± biopsy in year 1 is the safety net." },
    ],
  },
  {
    id: "bcr-penile-rehab",
    topicId: "prostate",
    title: "BCR after radical prostatectomy and penile rehabilitation",
    highYield: true,
    gold: true,
    tags: ["BCR", "EAU BCR", "salvage RT", "penile rehab", "PDE5"],
    exams: [
      { session: "Dec", year: 2022, marks: "5+5", stem: "Management of biochemical recurrence after radical prostatectomy. Components of penile rehabilitation before and after radical prostatectomy." },
      { session: "Dec", year: 2015, marks: "4+6", stem: "Significance of rising PSA after radical prostatectomy and its management." },
      { session: "Dec", year: 2012, marks: "3+7", stem: "What is penile rehabilitation after radical prostatectomy? Discuss the various modalities used for penile rehabilitation?" },
    ],
    related: ["ppi", "pet-pca", "as-pca", "retzius-sparing"],
    references: [
      "EAU PCa BCR risk (EAU BCR Good/High)",
      "RADICALS-RT / RAVES / GETUG-AFU17 — early salvage",
      "ICS / ISSM penile rehab",
      "Campbell RP outcomes",
    ],
    answer: [
      { t: "h", v: "BCR definition and meaning" },
      { t: "p", v: "After RP, PSA should be undetectable by 4–6 weeks. EAU BCR: PSA ≥0.4 ng/mL and rising, though salvage RT is often offered from 0.1–0.2 if ultrasensitive trend is clear. A rising PSA means residual prostate cells — local fossa, nodes, distant, or benign glands — not automatically ‘metastatic death’." },
      { t: "ul", v: [
        "Prognosis: EAU BCR risk. Low-risk: PSA-DT >1 y AND pathologic ISUP <4. High-risk: PSA-DT ≤1 y OR ISUP 4–5. High-risk BCR drives metastases.",
        "PSMA PET at PSA ≥0.2 (detection still incomplete at 0.2). Negative PET does not exclude fossa micromets.",
        "Management: observation if old, low-risk, slow DT. Early salvage EBRT to the fossa (± nodes if PET+ or high-risk) at PSA <0.5 for best salvage. Add ADT 6 mo (GETUG-16) or longer if high-risk (RTOG 9601, but that trial started at higher PSA). SBRT to oligometastases (STOMP, ORIOLE, SABR-COMET logic) + treat the primary site. Do not start lifelong ADT for a PSA of 0.3 in a man you can still irradiate.",
      ]},
      { t: "h", v: "Penile rehabilitation" },
      { t: "p", v: "Even with nerve-sparing, neuropraxia for 6–24 months leads to cavernosal hypoxia, smooth-muscle apoptosis, fibrosis and veno-occlusive failure — a use-it-or-lose-it corpus. Rehab is the planned early use of erection-generating methods to preserve tissue, nocturnal tumescence and sexual confidence, starting before or within weeks of RP." },
      { t: "ul", v: [
        "Pre-op: baseline IIEF, PDE5 trial (if they work pre-op, nerves and arteries exist), vacuum device teaching, realistic timeline, partner, consider sperm banking if relevant. Optimise diabetes, smoking, testosterone if frankly hypogonadal.",
        "Intra-op: nerve-sparing when oncologically safe, athermal NVB, preserve accessory pudendals, Retzius-sparing / urethral length.",
        "Post-op: daily low-dose PDE5 (tadalafil 5 mg — REINVENT / REACTT mixed but widely used) or on-demand high dose when nerves wake; vacuum erection device daily from catheter removal; ICI (alprostadil / Trimix) if PDE5 fails, from ~6 weeks; intraurethral alprostadil (MUSE); combination. AUS/penile prosthesis at 12–24 months if unrecoverable ED (and after continence stable).",
        "Evidence is heterogeneous; the concept is standard of care counselling even if RCTs on ‘daily tadalafil forever’ are imperfect.",
      ]},
      { t: "tip", k: "gold", v: "Salvage RT early, at low PSA, beats adjuvant RT for most (RADICALS-RT). Rehab starts before the operation, not when the patient mentions ED at 18 months." },
    ],
  },
  {
    id: "crpc",
    topicId: "prostate",
    title: "CRPC mechanisms, AR-pathway drugs and abiraterone",
    highYield: true,
    gold: true,
    tags: ["CRPC", "AR-V7", "abiraterone", "enzalutamide", "darolutamide"],
    exams: [
      { session: "Dec", year: 2022, marks: "6+4", stem: "Describe briefly possible mechanisms for castration-resistance in prostate cancer. Enumerate newer 3rd generation anti-androgens and their role in CRPC." },
      { session: "Jun", year: 2018, marks: "10", stem: "Management of CRPC (Castrate-resistant prostate cancer)." },
      { session: "Dec", year: 2013, marks: "5+5", stem: "Describe mechanism of action and clinical uses of Abiraterone." },
      { session: "Dec", year: 2012, marks: "5+5", stem: "What are the different mechanisms for development of hormone insensitive prostate cancer? Describe mechanism of action and side effects of Abiraterone." },
      { session: "Jun", year: 2020, marks: "3+4+3", stem: "Abiraterone - mechanism of action. What hormones are reduced, and what hormones are increased in a patient on Abiraterone?" },
    ],
    related: ["mhspc", "stampede", "bone-mets-pca", "pin-t3-lu177"],
    references: [
      "EAU / NCCN mCRPC",
      "COU-AA-301/302, AFFIRM, PREVAIL, ARAMIS, PROSPER, SPARTAN, VISION, CARD, PROfound",
      "Campbell Androgen signalling",
    ],
    answer: [
      { t: "p", v: "Castration-resistant PCa is biochemical or radiographic progression with serum testosterone <50 ng/dL (1.7 nmol/L). The AR axis is usually still driving the tumour — hence AR-targeted drugs work after GnRH analogue failure." },
      { t: "h", v: "Mechanisms of castration resistance" },
      { t: "ul", v: [
        "Intratumoral steroidogenesis (CYP17) — the abiraterone rationale.",
        "AR overexpression / amplification (Xq12).",
        "AR point mutations (T877A, F876L) altering ligand specificity (flutamide, bicalutamide as agonists; some confer darolutamide/enza resistance).",
        "Splice variants (AR-V7) — ligand-independent; associated with poor response to abi/enza (not routinely used to gate therapy in all guidelines).",
        "Ligand-independent activation via growth-factor / PTEN–PI3K–AKT–mTOR / ETS fusions.",
        "Glucocorticoid-receptor takeover of AR transcriptome.",
        "Lineage plasticity / neuroendocrine transdifferentiation (Rb/p53 loss) — PSMA-low, FDG-high, platinum-sensitive.",
        "Clonal selection under ADT, DNA-repair deficient clones (BRCA2) — PARP target.",
      ]},
      { t: "h", v: "Abiraterone" },
      { t: "p", v: "Abiraterone acetate is a selective irreversible inhibitor of CYP17A1 (17α-hydroxylase and C17,20-lyase) in testis, adrenal and tumour. That blocks synthesis of androgens from pregnenolone/progesterone." },
      { t: "ul", v: [
        "Reduced: cortisol, DHEA, androstenedione, testosterone, estradiol.",
        "Increased: ACTH (loss of cortisol feedback) → mineralocorticoid precursors (DOC, corticosterone) → hypertension, hypokalaemia, fluid retention. Hence prednisone 5 mg BD (mCRPC) or 5 mg OD (mHSPC LATITUDE / STAMPEDE) to re-close the feedback loop.",
        "Uses: mCRPC pre- and post-docetaxel (COU-AA-302/301); mHSPC high-risk (LATITUDE, STAMPEDE); with olaparib in selected; not with food (take fasting) for the originator PK.",
        "AE: mineralocorticoid excess, LFT, cardiac, steroid AEs. Monitor K, BP, LFTs.",
      ]},
      { t: "h", v: "Third-generation AR antagonists (ARSi)" },
      { t: "tbl", h: ["Drug", "Trials / role", "Pearl"], r: [
        ["Enzalutamide", "AFFIRM (post-chemo), PREVAIL (pre), PROSPER (nmCRPC), ARCHES/ENZAMET (mHSPC)", "Seizure, falls, fatigue; no prednisone"],
        ["Apalutamide", "SPARTAN nmCRPC, TITAN mHSPC", "Rash, hypothyroidism"],
        ["Darolutamide", "ARAMIS nmCRPC, ARASENS mHSPC + docetaxel", "Low CNS penetration — fewer falls/seizures"],
      ]},
      { t: "p", v: "These bind AR with high affinity, block nuclear translocation and DNA binding (unlike bicalutamide). nmCRPC (M0 CRPC with PSA-DT ≤10 mo): any of the three prolongs MFS (SPARTAN/PROSPER/ARAMIS). mCRPC sequence: ARPI if not used in HSPC; docetaxel; cabazitaxel (CARD); 177Lu-PSMA (VISION); sipuleucel-T selected; radium-223 if bone-only symptomatic (ALSYMPCA); PARP if BRCA (PROfound, TRITON); pembrolizumab if MSI-H/TMB-high rare. Keep the GnRH analogue on." },
      { t: "tip", k: "gold", v: "CRPC is still AR-driven until it is neuroendocrine. Abiraterone = CYP17 block → androgens and cortisol down, mineralocorticoids up unless you give prednisone. Name ENZA / APA / DARO with one trial each." },
    ],
  },
  {
    id: "millin",
    topicId: "prostate",
    title: "Millin retropubic simple prostatectomy",
    highYield: false,
    gold: false,
    tags: ["Millin", "simple prostatectomy", "BPH"],
    exams: [
      { session: "Dec", year: 2021, marks: "2+6+2", stem: "Millins prostatectomy: Indications and patient selection. Steps of surgical procedure. Complications." },
    ],
    related: ["bph-complications", "lasers-bph", "prostatectomy-bnc"],
    references: ["Millin T. Lancet 1945", "Campbell Simple prostatectomy", "EAU BPH — prostate >80 mL"],
    answer: [
      { t: "p", v: "Millin (1945) is retropubic enucleation of BPH adenomas through a transverse capsular incision, as opposed to Freyer transvesical. Indications: prostate ≳80–100 mL with BOO, concomitant large bladder stones / diverticulum needing open treatment, failed or unavailable HoLEP, hip that cannot lithotomy. Today HoLEP / robotic simple prostatectomy have largely replaced open Millin in high-volume centres, but the steps remain a 10-mark." },
      { t: "ul", n: true, v: [
        "Pfannenstiel / midline, space of Retzius, ligate DVC if needed, identify BN and prostate.",
        "Transverse capsular incision on the anterior capsule distal to BN (not into the bladder — that would be Freyer).",
        "Find the plane between adenoma and surgical capsule; enucleate lobes with finger / scissors; deliver median lobe; haemostasis at 5 and 7 o’clock (urethral arteries).",
        "Trigonise / advance a BN flap into the prostatic fossa (Malament / vest sutures optional), 22–24F 3-way, irrigate, close capsule, drain Retzius.",
      ]},
      { t: "ul", v: ["Complications: haemorrhage, transfusion, TUR-like dilution if irrigant absorbed, incontinence (rare if apex respected), BNC, residual adenoma, UTI, wound, DVT, retrograde ejaculation (almost universal), ED uncommon vs RP, missed cancer in the capsule (incidental CaP 5–10%)"] },
    ],
  },
  {
    id: "bph-complications",
    topicId: "prostate",
    title: "BPH complications and chronic retention with CKD",
    highYield: true,
    gold: true,
    tags: ["BPH", "chronic retention", "POD", "Cr 4.6"],
    exams: [
      { session: "Dec", year: 2021, marks: "5+5", stem: "List the complications of BPH. Outline the management of a 46 years male with bilateral hydro-ureteronephrosis, post-void residual urine of 800ml and serum creatinine of 4.6 mg/dl." },
      { session: "Dec", year: 2020, marks: "5+5", stem: "Describe the complications of benign prostatic hyperplasia (BPH). What are the indications of pressure-flow study in a man with BPH?" },
    ],
    related: ["pod", "uds-boo-pfs", "millin", "lasers-bph", "alpha-5ari"],
    references: ["EAU Non-neurogenic Male LUTS", "Campbell BPH", "AUA BPH guideline"],
    answer: [
      { t: "h", v: "Complications of BPH" },
      { t: "ul", v: ["LUTS / QOL failure", "Acute urinary retention", "Chronic high-pressure or high-volume retention", "Overflow incontinence", "Recurrent UTI, bladder stones, haematuria from enlarged prostate", "Bladder decompensation (DU), diverticula, trabeculation", "Hydronephrosis, obstructive uropathy, CKD, hypertension", "Post-obstructive diuresis after relief", "Sexual: not causal ED but treatments cause retrograde ejaculation"] },
      { t: "h", v: "PFS indications in BPH (Dec 20)" },
      { t: "ul", v: ["Qmax >10 mL/s yet considering surgery", "Young men (<50–55)", "Neurologic disease / diabetes / prior failed TURP", "Incontinence, mixed picture", "Discrepancy between prostate size and symptoms", "Research / unusual pattern flow"] },
      { t: "h", v: "The 46-year-old with Cr 4.6, PVR 800, bilateral HDUN" },
      { t: "p", v: "This is obstructive uropathy until proven otherwise. Age 46 is young for simple BPH — also think stricture, neurogenic, bladder neck, prostate cancer, valves residual, hypocontractility." },
      { t: "flow", title: "High-pressure chronic retention", nodes: [
        { id: "a", kind: "start", label: "ABC, exam, ultrasound, VBG/K, ECG", to: ["b"] },
        { id: "b", kind: "action", label: "Gentle urethral catheter (or SPC if stricture). Expect POD. HDU if uremic / hyperK", to: ["c"] },
        { id: "c", kind: "action", label: "Replace 50–75% UO, monitor weight, Na K Mg, never 1:1 forever (see POD)", to: ["d"] },
        { id: "d", kind: "action", label: "Dialysis if refractory K / acidosis / fluid / uraemic symptoms", to: ["e"] },
        { id: "e", kind: "action", label: "Once stable: Cr plateau, PSA (after a week — catheter raises it), DRE, cystoscopy, consider UDS if the prostate looks innocent", to: ["f"] },
        { id: "f", kind: "end", label: "Definitive outlet surgery when fit (HoLEP/TURP/Millin) + CIC teaching if DU suspected. Do not TURP on day 0 with K 6.5" },
      ]},
      { t: "tip", k: "gold", v: "Drain first, operate later. Age 46 with Cr 4.6 is not a ‘routine TURP’ stem — exclude stricture/neurogenic and manage POD." },
    ],
  },
  {
    id: "ppi",
    topicId: "prostate",
    title: "Post-prostatectomy incontinence and mirabegron",
    highYield: true,
    gold: true,
    tags: ["PPI", "AUS", "male sling", "mirabegron"],
    exams: [
      { session: "Dec", year: 2021, marks: "5+3+2", stem: "Management of post radical prostatectomy incontinence. Pharmacokinetics of mirabegron, uses and side effects. European-Australian phase 3 trial on mirabegron." },
      { session: "Jun", year: 2019, marks: "4+6", stem: "Post prostatectomy urinary incontinence: Etiological factors and outline of management." },
      { session: "Dec", year: 2015, marks: "2+2+6", stem: "Post prostatectomy urinary incontinence: Etiology, its prevention and management." },
      { session: "Dec", year: 2016, marks: "4+6", stem: "Continence mechanisms in males. Outline the management of post prostatectomy incontinence." },
      { session: "Jun", year: 2018, marks: "10", stem: "Management of post prostatectomy incontinence." },
    ],
    related: ["continence-mechanism", "bcr-penile-rehab", "mirabegron", "retzius-sparing"],
    references: [
      "EAU Male incontinence / PPI",
      "ICS",
      "MASTER trial (AUS vs sling)",
      "SCORPIO mirabegron",
      "Campbell RP continence",
    ],
    answer: [
      { t: "h", v: "Male continence (brief — see functional topic)" },
      { t: "p", v: "After RP the BN and prostatic smooth sphincter are gone. Continence is rhabdosphincter + functional urethral length + pelvic floor + preserved support (puboprostatic, levator). Prevention: nerve-sparing, apical urethral length, Rocco, bladder-neck sparing when safe, no thermal injury, Retzius-sparing in selected, pelvic-floor training taught before surgery." },
      { t: "h", v: "PPI aetiology" },
      { t: "ul", v: ["Sphincter incompetence (the dominant)", "DO / urgency (pre-existing or de novo)", "BOO from anastomotic stricture", "Mixed, fistula (rare), overflow"] },
      { t: "h", v: "Management ladder" },
      { t: "ul", n: true, v: [
        "Wait 12 months (most recovery by 6–12) unless total incontinence with a ‘frozen’ sphincter — still rehab first.",
        "Supervised PFMT (the one conservative measure with evidence), weight, treat UTI, pad diary, ICIQ.",
        "Cystoscopy to exclude anastomotic stricture. UDS if atypical, radiation, mixed, before implant in some units.",
        "Drugs: duloxetine (off-label, SNRI) modest; antimuscarinic / mirabegron if urgency component.",
        "Male sling (AdVance-type retrourethral transobturator) for mild–moderate SUI, no RT, mobile sphincter, <3 pads. MASTER: AUS more reliable for severe.",
        "AUS (AMS 800) gold standard for moderate–severe PPI, post-RT, failed sling. Counselling: mechanical failure, erosion, infection, 5–10 y revision.",
        "Adjustable balloons (ProACT), salvage slings — secondary.",
      ]},
      { t: "h", v: "Mirabegron — PK, uses, AE, phase 3" },
      { t: "p", v: "Selective β3-agonist. Oral bioavailability ~29–35%, t½ ~50 h, steady state ~day 7, CYP3A4/2D6 + renal. Dose 25–50 mg OD (25 mg if CrCl 15–29). Uses: OAB wet/dry, urgency component of PPI, men on α-blockers, combination with solifenacin (BESIDE). AE: hypertension, tachycardia, UTI, nasopharyngitis; avoid if BP ≥180/110. European–Australian SCORPIO (Khullar Eur Urol 2013): 12-week RCT vs placebo and tolterodine; mirabegron 50 mg reduced incontinence episodes and micturitions vs placebo with dry-mouth rates at placebo level, unlike tolterodine." },
      { t: "tip", k: "gold", v: "PPI is a sphincter problem until a stricture or DO is shown. PFMT a year, then sling if mild and unradiated, AUS if not. Quote SCORPIO for mirabegron." },
    ],
  },
  {
    id: "lasers-bph",
    topicId: "prostate",
    title: "Lasers for BPH",
    highYield: true,
    gold: false,
    tags: ["HoLEP", "GreenLight", "ThuLEP", "PVP"],
    exams: [
      { session: "Jun", year: 2020, marks: "5+5", stem: "Property of various laser energy used for prostatectomy. Indications and contraindications, and complications of laser prostatectomy." },
      { session: "Dec", year: 2017, marks: "3+4+3", stem: "Discuss the different laser energies used for treatment of BPH, techniques, advantages and shortcomings." },
    ],
    related: ["mis-bph", "millin", "bph-complications"],
    references: ["EAU Male LUTS — lasers", "Smith's Endourology", "Gilling HoLEP"],
    answer: [
      { t: "tbl", h: ["Laser", "λ / medium", "Tissue effect", "BPH technique"], r: [
        ["Ho:YAG", "2140 nm, pulsed, fibre", "Water-absorbed, true cutting + haemostasis, fragments morcellated", "HoLEP / HoLRP — size-independent enucleation gold"],
        ["Tm:YAG (2 µm cw) / TFL", "1940–2013 nm", "Shallower than Ho, excellent vapourise-cut", "ThuLEP / ThuVEP"],
        ["KTP / LBO ‘GreenLight’", "532 nm", "Haemoglobin-absorbed, vaporisation", "PVP XPS 180 W — good on anticoagulation"],
        ["Diode (980/1318)", "variable", "Deep coagulation", "Higher stricture / incontinence caution"],
        ["Nd:YAG historic", "1064 nm", "Deep coag", "Abandoned as VLAP"],
      ]},
      { t: "ul", v: [
        "Indications: same as TURP; HoLEP preferred >80 mL; PVP if anticoagulation cannot stop; stones can be treated with Ho in the same sitting.",
        "Contraindications: as for TURP (untreated UTI, hip that cannot be positioned for some, prostate cancer if simple-prostatectomy intent without staging). No absolute laser-specific beyond equipment / morcellator safety.",
        "Complications: retrograde ejaculation, transient incontinence (HoLEP 5–10% early), capsular bleed, ureteric orifice injury, morcellation bladder injury (the feared HoLEP disaster), stricture, BNC, incomplete vaporisation with GreenLight in huge glands, dysuria after PVP.",
      ]},
      { t: "tip", k: "exam", v: "HoLEP = anatomical enucleation, any size. GreenLight = vaporisation, anticoagulated. Never morcellate without a full-bladder view." },
    ],
  },
  {
    id: "gleason",
    topicId: "prostate",
    title: "Gleason grades 3, 4, 5 and ISUP grade groups",
    highYield: true,
    gold: true,
    tags: ["Gleason", "ISUP", "Grade Group", "cribriform"],
    exams: [
      { session: "Jun", year: 2020, marks: "4+3+3", stem: "Histopathological features of Gleason grade 3, 4 & 5 carcinoma prostate." },
      { session: "Jun", year: 2014, marks: "5+5", stem: "What are Gleason's grades and score? Discuss its clinical significance." },
    ],
    related: ["as-pca", "high-risk-pca", "pin-t3-lu177"],
    references: ["ISUP 2014 / WHO 2016 Grade Groups (Epstein)", "Gleason 1966 / 2005 ISUP", "EAU PCa risk groups"],
    answer: [
      { t: "p", v: "Gleason pattern is architectural, not cytologic, on H&E at low-medium power. Score = most + second-most common pattern in RP; in biopsies, most + highest (any tertiary 5 is in the score). Grade Groups 1–5 (ISUP 2014) map 6 / 3+4 / 4+3 / 8 / 9–10." },
      { t: "tbl", h: ["Pattern", "Architecture", "Clinical"], r: [
        ["3", "Well-formed, separate glands that a pathologist can draw a circle around; variation in size OK", "GG1 (3+3) almost never mets; AS candidate"],
        ["4", "Fused glands, cribriform (worse), glomeruloid, poorly formed glands that are not artefactual", "4+3 (GG3) behaves closer to 8 than 3+4 (GG2). Cribriform / IDC-P = drop AS"],
        ["5", "No glandular differentiation: sheets, cords, single cells, comedonecrosis in solid nests", "GG4–5 high risk; ADT/RT/surgery multimodality"],
      ]},
      { t: "p", v: "Patterns 1–2 are not diagnosed on needle biopsy. Significance: risk grouping (EAU), AS eligibility, RT vs surgery counselling, ADT duration with RT (intermediate vs high), PLND decision, prognosis after RP (upgrading). Always report % pattern 4 and cribriform." },
      { t: "tip", k: "gold", v: "Gleason is architecture. 3 = discrete glands, 4 = fused/cribriform, 5 = no glands. Write Grade Group beside the score." },
    ],
  },
  {
    id: "oligomet-pca",
    topicId: "prostate",
    title: "Oligometastatic prostate cancer",
    highYield: true,
    gold: false,
    tags: ["oligomet", "MDT", "STAMPEDE RT", "SBRT"],
    exams: [
      { session: "Dec", year: 2019, marks: "3+7", stem: "Define oligometastases for carcinoma prostate. Discuss current management." },
    ],
    related: ["stampede", "mhspc", "pet-pca", "bone-mets-pca"],
    references: [
      "Hellman & Weichselbaum oligometastases",
      "STAMPEDE arm H (Parker Lancet 2018) prostate RT in low-volume M1",
      "STOMP, ORIOLE, PEACE-1, ARASENS",
      "EAU mHSPC",
    ],
    answer: [
      { t: "p", v: "Oligometastatic PCa is a limited metastatic burden in which local therapy to metastases (and usually to the primary) might delay intensification. Definitions vary: CHAARTED/STAMPEDE low-volume = no visceral AND <4 bone mets, none outside spine/pelvis; many MDT trials use ≤3–5 PET-avid lesions. PSMA PET inflates the N/M stage vs conventional imaging — say which you are using." },
      { t: "ul", v: [
        "Systemic: treat as mHSPC — ADT + ARPI (enza/apa/abi/darolutamide) ± docetaxel (ARASENS / PEACE-1 triplet in high-volume / fit). ADT alone is outdated.",
        "Primary RT in low-volume de-novo M1 (STAMPEDE arm H): OS benefit. Prostatectomy in oligomet is trial (g-RAMPP, TRoMbone) not routine.",
        "Metastasis-directed SBRT (STOMP, ORIOLE): ADT-free survival gain; OS not proven. Use to defer ADT in metachronous oligorecurrence after local therapy.",
        "Bone health, MDT, clinical trial enrolment.",
      ]},
      { t: "tip", k: "gold", v: "Low-volume de-novo: ADT + ARPI and irradiate the prostate (STAMPEDE H). Metachronous oligorecurrence: PSMA-guided SBRT is reasonable; it is not a licence to skip systemic therapy in de-novo high-volume disease." },
    ],
  },
  {
    id: "bone-mets-pca",
    topicId: "prostate",
    title: "Bone metastases, denosumab and ADT bone health",
    highYield: true,
    gold: false,
    tags: ["denosumab", "zoledronate", "SRE", "ADT", "RANK"],
    exams: [
      { session: "Dec", year: 2019, marks: "5+5", stem: "Discuss mechanism of bone metastasis and its management in case of carcinoma prostate." },
      { session: "Dec", year: 2013, marks: "5+5", stem: "Describe mechanisms of action of Denusumab and its clinical use." },
      { session: "Dec", year: 2014, marks: "5+5", stem: "Evaluation and management of bone complications due to androgen deprivation therapy in cancer prostate." },
    ],
    related: ["crpc", "mhspc", "radionuclides-pca", "oligomet-pca"],
    references: [
      "EAU PCa bone health",
      "Fizazi denosumab vs zoledronate Lancet 2011",
      "ALSYMPCA radium-223",
      "Endocrine Society / NCCN ADT bone",
    ],
    answer: [
      { t: "h", v: "Mechanism of bone metastasis" },
      { t: "p", v: "PCa bone mets are typically osteoblastic. Seeds (CXCR4, integrins) home to marrow. Osteoblasts are stimulated (ET-1, BMPs, Wnt, PSA-cleaved PTHrP). RANKL from osteoblasts still activates osteoclasts — a coupling that releases growth factors (TGF-β, IGFs) feeding tumour cells (vicious cycle). Hence osteoclast-targeted drugs still work in ‘blastic’ PCa." },
      { t: "h", v: "Management of bone mets" },
      { t: "ul", v: ["Control the cancer: ADT+ARPI±chemo, Lu-177, radium-223 if symptomatic bone-predominant mCRPC without visceral (ALSYMPCA OS benefit — do not combine with abi outside trials because of fracture signal)", "SRE prevention in mCRPC with bone mets: denosumab 120 mg SC q4wk or zoledronate 4 mg IV q4–12wk — denosumab delayed SRE better (Fizazi). Dental review first (ONJ).", "Pain: analgesia, RT (8 Gy single), surgical fixation of impending femur/cord", "Cord compression: MRI, steroids, decompress / RT"] },
      { t: "h", v: "Denosumab" },
      { t: "p", v: "Fully human IgG2 monoclonal antibody against RANKL. Prevents RANKL–RANK on osteoclast precursors → less resorption. Uses: (1) 60 mg SC/6 mo for ADT osteoporosis (HALT) (2) 120 mg/4 wk for SRE in bone mets (3) hypercalcaemia of malignancy if bisphosphonate-refractory / CKD. AE: hypocalcaemia (give Ca/vit D), ONJ, rebound vertebral fractures if stopped abruptly, atypical femur fracture, cellulitis. Not really nephrotoxic (advantage vs zoledronate in GFR 30–60) but watch Ca in CKD." },
      { t: "h", v: "ADT bone complications" },
      { t: "ul", v: ["Androgens → oestrogens in men; ADT accelerates bone loss 2–4%/y, osteoporosis, fracture. Also sarcopenia, falls.", "Evaluate: FRAX, DEXA at baseline and 1–2 y, vitamin D, Ca, fall history, height loss.", "Manage: exercise, Ca/vit D, stop smoking/alcohol, denosumab 60 mg/6 mo or alendronate / zoledronate yearly if osteoporotic or high FRAX. Treat the cancer rationally — intermittent ADT only if evidence-based setting."] },
      { t: "tip", k: "gold", v: "Blastic mets still need osteoclast blockade. Denosumab = anti-RANKL. Dental clearance before SRE-dose. ADT is a bone disease as well as a cancer therapy." },
    ],
  },
  {
    id: "stampede",
    topicId: "prostate",
    title: "STAMPEDE trial",
    highYield: true,
    gold: true,
    tags: ["STAMPEDE", "mHSPC", "abiraterone", "docetaxel", "M1 RT"],
    exams: [
      { session: "Dec", year: 2017, marks: "4+6", stem: "Stampede trial: Summarize its design and main findings." },
    ],
    related: ["mhspc", "oligomet-pca", "crpc", "high-risk-pca"],
    references: [
      "James ND, STAMPEDE platform — Lancet / Lancet Oncol / NEJM multiple arms",
      "EAU mHSPC",
    ],
    answer: [
      { t: "p", v: "STAMPEDE (MRC) is a multi-arm multi-stage platform RCT in high-risk M0 and M1 HSPC, all men receiving ADT as backbone, with contemporaneous controls. It is the most important modern PCa trial to name in an exam." },
      { t: "tbl", h: ["Arm", "Question", "Headline"], r: [
        ["A vs C docetaxel", "ADT ± 6-cycle docetaxel", "OS benefit in M1 (with CHAARTED)"],
        ["A vs G abi+pred", "ADT ± abiraterone", "Large OS benefit M1 and failure-free survival in high-risk M0; 2 years abi in M0"],
        ["H prostate RT in M1", "ADT ± prostate RT", "OS benefit in low-volume M1 only"],
        ["J abi + enza", "Dual AR", "No extra OS vs abi alone — toxicity"],
        ["Metformin / 177Lu / others", "Ongoing / metabolic", "Know it is a living platform"],
        ["SOGUG / PEACE / ARASENS not STAMPEDE", "Triplets", "Do not mix names"],
      ]},
      { t: "p", v: "Design pearls: MAMS allows dropping futile arms early; inclusion mixed M0 locally advanced (node / high-risk) and M1 — always quote the subgroup that drove OS. Docetaxel and abi both work; choice by comorbidity, volume, access. Prostate RT for low-volume M1 is a STAMPEDE H sentence you must write." },
      { t: "tip", k: "gold", v: "STAMPEDE = platform, ADT backbone, docetaxel OS in M1, abiraterone OS in M1, prostate RT OS in low-volume M1." },
    ],
  },
  {
    id: "mhspc",
    topicId: "prostate",
    title: "Hormone-sensitive metastatic prostate cancer — advances",
    highYield: true,
    gold: true,
    tags: ["mHSPC", "CHAARTED", "PEACE-1", "ARASENS", "LATITUDE"],
    exams: [
      { session: "Dec", year: 2018, marks: "10", stem: "Recent advances in management of hormone sensitive metastatic prostate cancer." },
    ],
    related: ["stampede", "crpc", "oligomet-pca", "high-risk-pca"],
    references: [
      "CHAARTED, STAMPEDE, LATITUDE, ENZAMET, ARCHES, TITAN, ARASENS, PEACE-1",
      "EAU / NCCN mHSPC 2024–25",
    ],
    answer: [
      { t: "p", v: "ADT monotherapy is obsolete for most mHSPC. Doublet (ADT+ARPI) is the floor; triplet (ADT+docetaxel+darolutamide or +abi) for fit high-volume / de-novo disease." },
      { t: "tbl", h: ["Trial", "Addition to ADT", "Who benefits"], r: [
        ["CHAARTED / STAMPEDE docetaxel", "Docetaxel 75 mg/m² ×6", "OS, especially high-volume"],
        ["LATITUDE / STAMPEDE abi", "Abiraterone + prednisone", "OS M1; high-risk LATITUDE definition"],
        ["ENZAMET / ARCHES", "Enzalutamide", "OS / rPFS"],
        ["TITAN", "Apalutamide", "OS"],
        ["ARASENS", "Docetaxel + darolutamide", "Triplet OS"],
        ["PEACE-1", "Docetaxel + abi ± RT", "Triplet OS in high-volume; RT to prostate in low-volume"],
      ]},
      { t: "ul", v: ["Volume: CHAARTED high-volume = visceral OR ≥4 bone with ≥1 extra-axial", "Give bone health, metformin/metabolic, relugolix as oral GnRH antagonist (HERO — less CV events vs leuprolide) as an advance", "Do not combine abi + enza (STAMPEDE J)", "Genetic testing for BRCA now influences later PARP but not immediate first shot"] },
      { t: "tip", k: "exam", v: "Write ‘doublet for all, triplet for fit high-volume, RT to prostate if low-volume’ and you have the 2018–2025 answer." },
    ],
  },
  {
    id: "high-risk-pca",
    topicId: "prostate",
    title: "High-risk prostate cancer",
    highYield: true,
    gold: false,
    tags: ["high-risk", "EAU", "ePLND", "ADT+RT"],
    exams: [
      { session: "Jun", year: 2017, marks: "4+6", stem: "What do you mean by high risk prostate cancer? Outline its management." },
    ],
    related: ["stampede", "pin-t3-lu177", "as-pca", "gleason"],
    references: ["EAU / NCCN / D’Amico risk", "STAMPEDE M0 abi", "Campbell Locally advanced PCa"],
    answer: [
      { t: "p", v: "D’Amico / EAU high-risk localised: PSA >20 OR ISUP ≥4 (GS ≥8) OR ≥cT2c/T3. Locally advanced: T3–T4 or N1. Very-high-risk NCCN: T3b–T4, primary pattern 5, or >4 cores GS8–10." },
      { t: "ul", v: [
        "Staging: mpMRI + PSMA PET (proPSMA).",
        "Fit M0: (1) EBRT + long-term ADT 18–36 mo ± brachy boost; add 2 y abiraterone if very high-risk M0 (STAMPEDE) (2) RP + ePLND in resectable disease, with adjuvant / early salvage RT ± ADT as pathology dictates. Discuss both in a multidisciplinary clinic.",
        "N1: treat as locally advanced — RT + long ADT ± abi; surgery only in selected.",
        "Not AS. Not ADT alone if radical therapy is possible.",
      ]},
    ],
  },
  {
    id: "psa-screening",
    topicId: "prostate",
    title: "PSA screening — problems, lead-time and length-time bias",
    highYield: true,
    gold: true,
    tags: ["PSA", "lead-time", "length-time", "ERSPC", "PLCO"],
    exams: [
      { session: "Dec", year: 2017, marks: "5+5", stem: "Explain lead time bias and length time bias in the context of PSA screening for prostate cancer." },
      { session: "Dec", year: 2011, marks: "10", stem: "What are the various problems in using PSA as a screening tool for prostate cancer?" },
    ],
    related: ["lead-length-bias", "molecular-markers-pca", "as-pca"],
    references: [
      "ERSPC, PLCO, ProtecT, CAP",
      "USPSTF / EAU early detection",
      "Campbell PSA",
    ],
    answer: [
      { t: "h", v: "Problems with PSA as a screening tool" },
      { t: "ul", v: [
        "Not cancer-specific: BPH, prostatitis, UTI, retention, ejaculation, instrument, 5ARI (halves PSA).",
        "Not sensitive for all PCa: high-grade can have modest PSA.",
        "Overdiagnosis of ISUP 1 that would never kill (ProtecT).",
        "Overtreatment harm: incontinence, ED, RT toxicity — the real cost of screening if AS is not used.",
        "Cut-off 4 ng/mL is arbitrary; age-specific, density, MRI improve but complicate a ‘screening test’.",
        "PLCO contamination (control arm PSA) vs ERSPC modest mortality benefit (NNS hundreds). CAP cluster RCT small effect.",
        "Health-system: biopsy sepsis, anxiety, cost. Shared decision, not population reflex testing.",
        "Lead-time and length-time bias make survival-from-diagnosis look better without changing death date (see below).",
      ]},
      { t: "h", v: "Lead-time bias" },
      { t: "p", v: "Screening brings the diagnosis earlier in the natural history. Survival measured from diagnosis lengthens by that lead time even if death occurs at the same calendar date. PSA can ‘improve 5-y survival’ purely by starting the clock earlier. True benefit requires a fall in disease-specific mortality in an RCT, not better survival statistics." },
      { t: "h", v: "Length-time bias" },
      { t: "p", v: "Slow-growing, low-grade cancers spend longer in a screen-detectable preclinical phase and are preferentially caught by periodic PSA. Aggressive cancers zoom through and present clinically between tests. Screen-detected cohorts are therefore enriched for indolent biology and look like they ‘survive longer’. Overdiagnosis of Gleason 6 is the clinical face of length-time bias." },
      { t: "tip", k: "gold", v: "PSA screening problems = specificity + overdiagnosis + harm. Lead-time = earlier clock. Length-time = slow cancers more visible. Only mortality RCTs (ERSPC) beat these biases." },
    ],
  },
  {
    id: "molecular-markers-pca",
    topicId: "prostate",
    title: "Molecular markers versus PSA in prostate cancer detection",
    highYield: false,
    gold: false,
    tags: ["PCA3", "phi", "4K", "ConfirmMDx"],
    exams: [
      { session: "Jun", year: 2016, marks: "5+5", stem: "Role of molecular markers in detection of prostate cancer. How do these markers differ from PSA in cancer detection?" },
    ],
    related: ["prostate-anatomy-mcneal", "psa-screening", "mpmri-pirads"],
    references: ["EAU PCa biomarkers", "FDA PCA3, phi, 4K, ExoDx"],
    answer: [
      { t: "p", v: "PSA is a kallikrein serine protease (KLK3) secreted by luminal cells — organ-specific, not cancer-specific. Molecular markers aim for cancer-specificity or high-grade-specificity to reduce unnecessary biopsy." },
      { t: "tbl", h: ["Marker", "Biology", "Vs PSA"], r: [
        ["%fPSA, phi, 4Kscore", "Kallikrein isoforms / proPSA", "Same family as PSA but ratios improve specificity in grey zone"],
        ["PCA3 (urine post-DRE)", "Non-coding RNA overexpressed in PCa", "Independent of prostate volume; better after negative biopsy"],
        ["SelectMDx (HOXC6, DLX1 urine)", "mRNA", "High-grade risk; MRI era competition"],
        ["ExoDx (exosomal RNA)", "No DRE needed", "First-biopsy decision"],
        ["ConfirmMDx", "GSTP1/APC/RASSF1 methylation on negative tissue", "Field effect; not a serum test"],
        ["MRI", "Anatomy", "Has out-competed many markers as the first add-on"],
      ]},
      { t: "p", v: "Difference: PSA is cheap, reproducible, continuous, useful for detection AND treatment monitoring AND BCR. Molecular markers are usually one-off biopsy-triage tests, cost more, are not for monitoring after RP, and still lack PSA’s longitudinal dynamic range. They complement, not replace, PSA." },
    ],
  },
  {
    id: "retzius-sparing",
    topicId: "prostate",
    title: "Retzius-sparing radical prostatectomy",
    highYield: false,
    gold: false,
    tags: ["Retzius", "Bocciardi", "continence"],
    exams: [
      { session: "Dec", year: 2017, marks: "10", stem: "Discuss the technique and advantages of Retzius-Sparing radical prostatectomy." },
    ],
    related: ["ppi", "prostate-anatomy-mcneal", "bcr-penile-rehab"],
    references: ["Galfano / Bocciardi technique", "EAU robotic RP", "Campbell RP"],
    answer: [
      { t: "p", v: "Retzius-sparing (posterior approach) RP, popularised by Galfano/Bocciardi, reaches the prostate through the pouch of Douglas, leaving the space of Retzius, puboprostatic ligaments, DVC, endopelvic fascia and anterior support untouched — theoretically better early continence." },
      { t: "ul", n: true, v: [
        "Trendelenburg, transperitoneal. Incise peritoneum at the vesicorectal pouch, develop SV/vas first (like a posterior-first Montsouris).",
        "Work toward the apex behind the prostate; urethra last. Anastomosis in a small hole; lymph nodes via separate peritoneal windows.",
        "Advantages: faster pad-free rates at 1 week–1 month in RCTs/meta-analyses; anterior anatomy preserved for salvage; less DVC bleeding.",
        "Disadvantages: learning curve, harder large median lobes / large prostates / anterior tumours, positive margins at the anterior base in some series, difficult anterior PLND exposure, not ideal after hernia mesh. Long-term oncologic equivalence likely if margins respected.",
      ]},
    ],
  },
  {
    id: "turp-hyponatraemia",
    topicId: "prostate",
    title: "TURP syndrome and hyponatraemia",
    highYield: true,
    gold: true,
    tags: ["TURP syndrome", "glycine", "hyponatraemia"],
    exams: [
      { session: "Dec", year: 2013, marks: "10", stem: "A 60 year old male had TURP with Monopolar cautery. What are the symptoms of Hyponatremia and how will you correct them?" },
    ],
    related: ["hyponatremia", "mis-bph"],
    references: ["European Hyponatraemia Guidelines", "Campbell TURP complications", "Adrogué–Madias"],
    answer: [
      { t: "p", v: "Monopolar TURP uses 1.5% glycine (200 mOsm, hypotonic, non-conductive). Opened venous sinuses absorb glycine irrigant → dilutional hyponatraemia, hypervolaemia, and glycine/ammonia neurotoxicity (visual, NMDA). Bipolar in saline largely prevents classic TURP syndrome but volume overload still occurs." },
      { t: "ul", v: [
        "Symptoms by Na: malaise/nausea ~130; headache/confusion 120–130; seizures/coma <120; plus TURP-specific: hypertension then collapse, bradycardia, wide QRS, visual loss, hypothermia, coagulopathy.",
        "Intra-op clues: unexplained BP rise, restlessness under spinal, desaturation, wide abdomen (extravasation).",
        "Stop resection, furosemide if overloaded, send ABG/Na/osmolality/ammonia, ITU.",
        "Severe neuro symptoms: 150 mL 3% hypertonic saline over 10–20 min, repeat to abort seizures. Then 4–6 mmol/L rise per 24 h if the hyponatraemia might be subacute; TURP is usually acute so 10 mmol/24 h is tolerated — still do not rocket to 140 in an hour.",
        "Supportive: airway, ignore glycine visual loss (transient), treat bradycardia. Hypertonic saline is for symptoms / Na <120, not for every 132.",
      ]},
      { t: "tip", k: "gold", v: "Monopolar + glycine + time + blood loss = TURP syndrome. Treat the brain with 3% saline, the volume with furosemide, and prevent it with bipolar/HoLEP and a 60-minute clock." },
    ],
  },
  {
    id: "alpha-5ari",
    topicId: "prostate",
    title: "Alpha-blockers and 5α-reductase inhibitors",
    highYield: true,
    gold: false,
    tags: ["tamsulosin", "dutasteride", "MTOPS", "CombAT"],
    exams: [
      { session: "Dec", year: 2013, marks: "3+7", stem: "Name the alpha blockers available in India. Give rationale of using alpha blockers with or without 5 alpha reductase inhibitor in a sexually active male with voiding LUTS." },
    ],
    related: ["bph-complications", "mis-bph"],
    references: ["EAU Male LUTS", "MTOPS, CombAT, REDUCE", "Campbell BPH medical therapy"],
    answer: [
      { t: "p", v: "α1-blockers used in India: tamsulosin 0.4 mg (α1A-selective), silodosin 8 mg (most α1A-selective), alfuzosin 10 mg XL, terazosin, prazosin, doxazosin. 5ARI: finasteride 5 mg (type 2), dutasteride 0.5 mg (type 1+2)." },
      { t: "ul", v: [
        "α-blocker: rapid (days) relaxation of stromal smooth muscle — any size prostate, for symptoms. Sexual: tamsulosin/silodosin cause anejaculation; non-selective cause hypotension. Does not shrink prostate or alter PSA (much) or prevent retention long-term as monotherapy in large glands.",
        "5ARI: apoptosis of epithelium, 20–30% volume drop at 6 months, PSA falls ~50% (double the measured PSA), less haematuria, fewer AUR/surgery (PLESS, MTOPS, CombAT) if prostate ≳30–40 mL or PSA ≳1.5.",
        "Sexually active man: start α-blocker for speed. Avoid silodosin if ejaculation matters; tamsulosin still often anejaculatory; alfuzosin kinder to ejaculation. Add 5ARI if gland large / PSA high / cannot wait for surgery — counsel reduced libido, ED, gynecomastia, and the ‘double the PSA’ rule. Combination is for large prostates, not for a 20 mL gland in a 50-year-old.",
        "Do not use 5ARI as chemoprevention (REDUCE: fewer cancers but signal of more HG tumours — detection bias debated).",
      ]},
    ],
  },
  {
    id: "mis-bph",
    topicId: "prostate",
    title: "Minimally invasive BPH treatments, PAE, bipolar vs monopolar physics",
    highYield: true,
    gold: false,
    tags: ["PAE", "Urolift", "Rezum", "bipolar", "monopolar"],
    exams: [
      { session: "Jun", year: 2016, marks: "3+3+4", stem: "Enumerate minimally invasive treatment options for BPH. Prostatic artery embolization-Technique. Compare monopolar vs bipolar TURP." },
      { session: "Jun", year: 2018, marks: "10", stem: "Physics of mono-polar and bi-polar cautery in management of BPH." },
      { session: "Dec", year: 2012, marks: "6+4", stem: "Discuss recent advances in non-invasive assessment of bladder outlet obstruction and prediction of outcomes following BPH surgery." },
    ],
    related: ["lasers-bph", "turp-hyponatraemia", "stents-bph", "uds-boo-pfs"],
    references: ["EAU Male LUTS", "UK-ROPE PAE", "Campbell Electrosurgery"],
    answer: [
      { t: "h", v: "MIS options" },
      { t: "ul", v: ["UroLift prostatic urethral lift — preserves ejaculation, small–moderate glands without big median lobe", "Rezum water-vapour / other thermal (TUNA/TUMT historic)", "iTIND, Optilume BPH, AquaBeam (robotic waterjet — not ‘office’)", "PAE", "Stents (see stents-bph)", "HoLEP/ThuLEP/PVP — endoscopic not office MIS"] },
      { t: "h", v: "PAE technique" },
      { t: "p", v: "IR: CTA map, femoral or radial access, superselective catheterisation of prostatic arteries (inferior vesical origin; dangerous anastomoses to rectum, penis, bladder), embolise with 100–500 µm microspheres until stasis. Local anaesthesia. Outcomes: IPSS improvement less than TURP (UK-ROPE), better ejaculation, failure/retreatment higher. Median lobe and huge glands less reliable. Complications: post-embolisation syndrome, non-target (rectal ulcer, penile, bladder necrosis — rare if superselective)." },
      { t: "h", v: "Monopolar vs bipolar physics" },
      { t: "tbl", h: ["", "Monopolar TURP", "Bipolar TURP / TURis"], r: [
        ["Circuit", "Current from loop → patient → return pad", "Current between loop and resectoscope sheath / second electrode; patient not the return"],
        ["Irrigant", "Non-conductive glycine/sorbitol/mannitol", "Isotonic saline"],
        ["TUR syndrome", "Classic glycine hyponatraemia", "Virtually none; volume overload still possible"],
        ["Cut / coag", "Need higher voltage to overcome glycine; deeper charring if poorly set", "Plasma corona at the loop; similar cut, often better coag"],
        ["Pad burns / arrhythmia", "Yes if pad fail / current through prosthesis", "Minimal stray current"],
        ["Efficacy", "Historic gold", "Equivalent IPSS/Qmax in RCTs; can resect longer; less hyponatraemia"],
      ]},
      { t: "h", v: "Non-invasive BOO assessment (Dec 12)" },
      { t: "ul", v: ["Uroflow + PVR (still first)", "Prostate volume, IPP, bladder wall thickness / UEBW on US", "Penile cuff test, condom catheter, near-infrared, Detrusor wall thickness ≥5 mm suggests BOO", "MRI / urodynamic nomograms research", "None fully replace PFS when the decision is knife vs not in an atypical man"] },
    ],
  },
  {
    id: "prostatectomy-bnc",
    topicId: "prostate",
    title: "Indications for simple prostatectomy, complications and bladder-neck contracture",
    highYield: false,
    gold: false,
    tags: ["BNC", "simple prostatectomy", "TURP Cx"],
    exams: [
      { session: "Jun", year: 2019, marks: "3+4+3", stem: "Indications for prostatectomy for symptomatic BPH. Enumerate major complications following prostatectomy for BPH. Management options for bladder neck contracture." },
    ],
    related: ["millin", "lasers-bph", "ppi", "bph-complications"],
    references: ["EAU Male LUTS", "Campbell TURP complications"],
    answer: [
      { t: "ul", v: [
        "Indications: refractory LUTS, AUR failed TWOC, recurrent infection/stones/haematuria of prostatic origin, obstructive uropathy, large diverticulum with BOO, patient choice after counselling. Size guides energy (TURP <80 mL, HoLEP any, open/robotic simple >80–100 if no HoLEP).",
        "Major Cx: bleeding/transfusion, TUR syndrome, perforation, sepsis, incontinence, ED (low), retrograde ejaculation, stricture, BNC, incomplete resection, mortality <0.3%, DVT, missed CaP.",
        "BNC: 1–5%, more after small glands aggressively resected at BN, or after RP (different entity). Presentation: poor stream months later, Qmax plateau. Cystoscopy confirms. Management: gentle dilation; cold-knife / bipolar incision at 12 or 5–7; Mitomycin / steroid injection in recalcitrant; Y-V / bladder-neck reconstruction rare; self-dilation / CIC; never aggressive deep TUR in a man you will make incontinent. After RP BNC: cautious incision, remember the sphincter is millimetres away.",
      ]},
    ],
  },
  {
    id: "stents-bph",
    topicId: "prostate",
    title: "Stents in BPH",
    highYield: false,
    gold: false,
    tags: ["Memokath", "urolume", "BPH stent"],
    exams: [
      { session: "Dec", year: 2011, marks: "10", stem: "What is the role of stents in the management of BPH." },
    ],
    related: ["mis-bph", "neuromod-metallic"],
    references: ["EAU Male LUTS — stents", "Campbell Temporary prostatic stents"],
    answer: [
      { t: "p", v: "Prostatic stents are a niche for men in retention who are unfit for any anaesthetic / ablation and who cannot or will not have a long-term catheter. They are not a first-line BPH therapy." },
      { t: "ul", v: [
        "Temporary: plastic / spiral (Porges, iTIND-like modern), biodegradable. Bridge after AUR or thermotherapy.",
        "Permanent: epithelialising UroLume (historic, encrustation, pain, difficult removal) — largely abandoned. Thermo-expandable Memokath sits across the prostatic urethra, removable.",
        "Complications: migration, encrustation, infection, perineal pain, failed emptying if DU, difficult explant.",
        "Modern ‘stent-adjacent’: UroLift implants are not stents but implants; iTIND is temporary. Mention and move on.",
      ]},
    ],
  },
  {
    id: "prostatitis",
    topicId: "prostate",
    title: "Prostatitis classification and management",
    highYield: false,
    gold: false,
    tags: ["NIH", "CP/CPPS", "NIDDK"],
    exams: [
      { session: "Jun", year: 2018, marks: "3+7", stem: "Classify prostatitis and outline its management." },
    ],
    related: ["cpps", "bph-complications"],
    references: ["NIH NIDDK prostatitis categories", "EAU Chronic pelvic pain", "Campbell Prostatitis"],
    answer: [
      { t: "tbl", h: ["NIH", "Name", "Management"], r: [
        ["I", "Acute bacterial", "Parenteral then oral (fluoroquinolone / co-trimoxazole) 2–4 wk, drain abscess if any, do NOT massage"],
        ["II", "Chronic bacterial (recurrent UTI, same bug)", "4–6 wk culture-driven FQ / TMP-SMX; consider biofilm / stones / TUR if recalcitrant"],
        ["III a/b", "CP/CPPS inflammatory / non-inflammatory (WBC in EPS or not)", "UPOINT phenotyping: urinary, psychosocial, organ, infection, neuro, tenderness — α-blocker, physio, amitriptyline, pelvic-floor, not endless antibiotics"],
        ["IV", "Asymptomatic inflammatory", "Incidental; treat only if infertility / PSA work-up context"],
      ]},
      { t: "p", v: "Meares–Stamey 4-glass is historic; 2-glass (VB3 vs midstream) is practical. Always think TB, cancer, stricture in atypical men." },
    ],
  },
  {
    id: "radionuclides-pca",
    topicId: "prostate",
    title: "Radionuclides in diagnosis and treatment of prostate cancer",
    highYield: false,
    gold: false,
    tags: ["bone scan", "radium-223", "PSMA", "Lu-177"],
    exams: [
      { session: "Dec", year: 2016, marks: "6+4", stem: "Various radio-nuclides used in the diagnosis and management of prostate cancer." },
      { session: "Dec", year: 2016, marks: "4+3+3", stem: "Enumerate different treatment modalities for localized, locally advanced and metastatic carcinoma of prostate." },
    ],
    related: ["pet-pca", "pin-t3-lu177", "bone-mets-pca", "nucs-uro-onc"],
    references: ["EAU PCa", "ALSYMPCA", "VISION", "proPSMA"],
    answer: [
      { t: "tbl", h: ["Nuclide", "Use"], r: [
        ["99mTc-MDP bone scan", "Historic M staging; superseded by PSMA PET in high-risk"],
        ["18F-NaF PET", "Sensitive bone PET"],
        ["68Ga / 18F PSMA PET", "Staging, BCR, Lu selection"],
        ["11C / 18F choline, 18F-fluciclovine", "BCR if no PSMA"],
        ["223Ra dichloride (α, bone-seeking)", "mCRPC bone-predominant, ALSYMPCA OS"],
        ["177Lu-PSMA-617 (β)", "VISION mCRPC"],
        ["225Ac-PSMA (α)", "Salvage / trial, xerostomia"],
        ["89Sr, 153Sm-EDTMP", "Historic palliation, marrow toxicity, no OS"],
      ]},
      { t: "p", v: "Localised: AS / RP / RT ± ADT. Locally advanced: RT + long ADT ± abi, or RP+ePLND. Metastatic: ADT+ARPI±docetaxel±prostate RT if low-volume; later Lu/Ra/PARP. One paragraph is enough for the Dec 16 modalities stem — point to mhspc / high-risk answers." },
    ],
  },
];
