import type { Master } from "../types";

export const renalSurgery: Master[] = [
  {
    id: "retroperitoneoscopic-nephrectomy",
    topicId: "renal-surgery",
    title: "Retroperitoneoscopic nephrectomy — steps, advantages, disadvantages",
    highYield: true,
    gold: true,
    tags: ["Gaur", "retroperitoneoscopy", "nephrectomy", "ports"],
    exams: [
      {
        session: "Jun",
        year: 2021,
        marks: "4+3+3",
        stem: "Discuss the steps of Retro-Peritoneoscopic Nephrectomy. What are the advantages and disadvantages of retro-Peritoneoscopic nephrectomy?",
      },
    ],
    related: ["gerota-fascia-approaches", "lap-nephrectomy-complications", "flank-vs-anterior"],
    references: [
      "Gaur DD. J Urol 1992 — balloon retroperitoneoscopy",
      "Campbell / Glenn's — Laparoscopic nephrectomy",
      "EAU Laparoscopy chapter / Hinman Atlas",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Position, balloon, ports, artery-then-vein, extraction 4 · Advantages 3 · Disadvantages 3. Draw the flank with 3–4 ports and the psoas as the floor." },
      { t: "h", v: "Indications" },
      { t: "p", v: "Simple nephrectomy (non-function, donor in some centres, xanthogranulomatous selected), radical nephrectomy for posterior/small-to-moderate tumours, adrenalectomy, pyeloplasty. Less ideal for very large tumours, IVC thrombus, or when a full ipsilateral lymphadenectomy / peritoneal survey is required." },
      { t: "h", v: "Steps" },
      { t: "ul", n: true, v: [
        "GA, Foley, orogastric tube. Lateral flank with table break, kidney rest up. Surgeon and camera behind the patient.",
        "Open (Hasson) access at the tip of the 12th rib (Petit’s triangle / Gaur point): 1.5 cm incision, split muscles, enter retroperitoneum by piercing the lumbodorsal fascia with a finger or haemostat. Confirm psoas and fat.",
        "Gaur balloon (fingerstall / commercial PDB) inflated with 500–800 mL saline under vision or finger guidance to create the space between psoas and Gerota. Deflate, insert 10–12 mm blunt balloon/Hasson camera port, close the fascia around it, insufflate 12–15 mmHg CO2.",
        "Secondary ports under vision: 10 mm at anterior axillary line 2 cm above iliac crest; 5 mm at subcostal posterior axillary line; optional 5 mm anterior subcostal for retraction. Identify landmarks: psoas floor, ureter/gonadal, Gerota, peritoneal reflection anteriorly (do not hole it).",
        "Find the ureter over psoas, retract it anteriorly to lift the lower pole. Dissect cranially to the hilum.",
        "Left: gonadal, lumbar, adrenal veins. Right: duodenum/IVC. Artery first (clips or stapler), then vein. Adrenal taken or spared depending on indication (simple vs radical, upper-pole tumour).",
        "Mobilise remaining attachments, divide ureter between clips. Bag the specimen; extract by extending a port (muscle-splitting). Drain optional. Desufflate under vision, close fascia of 10 mm ports.",
      ]},
      { t: "h", v: "Advantages" },
      { t: "ul", v: [
        "Never enters peritoneum — less ileus, no intraperitoneal spillage of urine/tumour/infected cyst, adhesions avoided. Ideal after previous laparotomy.",
        "Direct, posterior, short path to the renal hilum (especially right adrenal and posterior tumours).",
        "Lateral reflection of peritoneum keeps bowel out of the field without a fan retractor.",
        "Less CO2 / less shoulder-tip; possibly less hemodynamic insult in the obese (short instruments, no pannus).",
        "Extraction through the flank does not violate the peritoneal cavity.",
      ]},
      { t: "h", v: "Disadvantages" },
      { t: "ul", v: [
        "Small working space, steep learning curve, easy peritoneal rent that collapses the field.",
        "Orientation: psoas is the floor; newcomers lose the ureter or wander into the peritoneum / pleural reflection (12th rib).",
        "Limited for tumours >8–10 cm, bulky lymphadenopathy, IVC thrombus, and for inspecting the peritoneal cavity.",
        "Specimen extraction of a large kidney still needs a sizable flank incision (loses some ‘minimally invasive’ gain).",
        "Anatomic variants (horseshoe isthmus, malrotation) are harder. Right-side IVC injury is unforgiving in a small hole.",
        "Port-site ergonomics: swords crossing; robotic retroperitoneal access is an alternative.",
      ]},
      { t: "tip", k: "gold", v: "Psoas is the floor, balloon is Gaur, artery is first. Retroperitoneoscopy is the previous-laparotomy and posterior-tumour operation — not the 14 cm IVC-thrombus operation." },
    ],
  },
  {
    id: "pn-complications",
    topicId: "renal-surgery",
    title: "Partial nephrectomy — intra-operative, post-operative and long-term complications",
    highYield: true,
    gold: true,
    tags: ["PN", "NSS", "urinoma", "pseudoaneurysm", "CKD"],
    exams: [
      {
        session: "Jun",
        year: 2020,
        marks: "3+4+3",
        stem: "Intra-operative, post-operative and long term complications of partial nephrectomy.",
      },
    ],
    related: ["haemostatic-agents-lpn", "partial-nephrectomy-nss", "nephrometry-scores"],
    references: [
      "EAU RCC — PN complications",
      "Campbell — Surgery of the Kidney",
      "Clavien–Dindo / MIC score",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Intra-op 3 (bleed, entry into sinus, cold ischaemia, conversion, positive margin) · Early post-op 4 (bleed, urine leak, AKI, infection, VTE) · Long-term 3 (CKD, hernia, recurrence, HTN, proteinuria). Quote Clavien." },
      { t: "h", v: "Intra-operative" },
      { t: "ul", v: [
        "Haemorrhage: incomplete hilar clamp, missed accessory artery, venous back-bleed, cut into sinus/segmental vessel. Manage: raise pressure, additional clamp, suture ligate, convert, selective arterial clamp revision, balloon Fogarty in a segmental (rare).",
        "Collecting-system entry: expected in deep tumours — close with absorbable (3-0 vicryl), methylene-blue or ICG leak test, stent if large.",
        "Prolonged ischaemia: aim <25 min warm (or cold if predicted longer). Early unclamping, zero-ischaemia, ice slush (open).",
        "Tumour violation / positive margin: deeper re-resection or completion RN depending on residual parenchyma and pathology.",
        "Adjacent organ: pleura (pneumothorax — drain), spleen, pancreas (left), duodenum/IVC (right), ureter (stent).",
        "Pneumoperitoneum issues, gas embolism, port injury — generic lap.",
        "Conversion to RN or open: not a failure if oncologically indicated; report it.",
      ]},
      { t: "h", v: "Early post-operative" },
      { t: "tbl", h: ["Complication", "When / clue", "Action"], r: [
        ["Acute bleeding / haemodynamic instability", "0–24 h, drain haematocrit high", "Resuscitate, reverse coagulopathy, re-explore vs angioembolization"],
        ["Delayed haemorrhage / pseudoaneurysm / AVF", "Day 5–14, gross haematuria after discharge", "CT angio → superselective coils (not RN)"],
        ["Urine leak / urinoma / high drain output", "Day 2–7, drain Cr >> serum", "See haemostatic-agents master: catheter, stent/PCN, drain; rarely repair"],
        ["AKI", "Solitary kidney, prolonged clamp, rhabdo from positioning", "Support, avoid nephrotoxins; dialysis rare"],
        ["Infection / abscess", "Fever, collection", "Culture, drain, antibiotics"],
        ["ATELECTASIS / PE / DVT / MI / wound", "ERAS failures", "Standard"],
        ["Rhabdomyolysis (flank, obese, long)", "Very high CK, dark urine", "Fluids, bicarbonate debate, fasciotomy rare"],
      ]},
      { t: "h", v: "Long-term" },
      { t: "ul", v: [
        "CKD and proteinuria from parenchymal loss + ischaemia + comorbidity (the reason PN exists is to blunt this vs RN).",
        "Hypertension (renin from the ischaemic rim).",
        "Incisional / port-site hernia, flank bulge (intercostal nerve in open flank).",
        "Local recurrence (true vs missed satellite); contralateral tumour (VHL, multifocal).",
        "Stone in a closed calyx / infundibular stenosis after deep reconstruction.",
        "Chronic fistula, chronic pain, rare AVF high-output failure.",
      ]},
      { t: "tip", k: "gold", v: "The two ‘come-back’ complications of PN are delayed pseudoaneurysm (embolize) and urine leak (drain the urinary tract). Long-term, the complication you were trying to prevent is CKD." },
    ],
  },
  {
    id: "hydatid-kidney",
    topicId: "renal-surgery",
    title: "Renal hydatid — Echinococcus life cycle and operative steps",
    highYield: false,
    gold: false,
    tags: ["hydatid", "Echinococcus", "PAIR", "scolicide"],
    exams: [
      {
        session: "Jun",
        year: 2018,
        marks: "10",
        stem: "Describe life cycle of Echinococcus granulosus. Detail the operative steps of hydatid cyst of kidney.",
      },
    ],
    related: ["bosniak-cysts", "adpkd"],
    references: [
      "WHO-IWGE hydatid cyst classification",
      "Campbell — Parasitic diseases of the GU tract",
      "EAU Urological Infections (parasitic)",
    ],
    answer: [
      { t: "h", v: "Life cycle of Echinococcus granulosus" },
      { t: "ul", n: true, v: [
        "Definitive host: dog (and other canids). Adult tapeworm lives in small bowel; gravid proglottids release eggs in faeces.",
        "Eggs contaminate pasture; intermediate host (sheep, cattle, camel, goat — also human as accidental intermediate) ingests eggs.",
        "Oncospheres hatch, penetrate gut, travel via portal vein. Liver (70%) and lung (20%) filter most; a few escape to kidney (~2–4%), spleen, brain, bone.",
        "Larva becomes a hydatid cyst: outer pericyst (host), laminated ectocyst, inner germinal endocyst that buds brood capsules and protoscolices (‘hydatid sand’). Daughter cysts form from germinal layer.",
        "Cycle completes only if a dog eats hydatid-bearing viscera of the sheep. Humans are dead-end hosts.",
        "E. multilocularis (alveolar) is a different, infiltrative fox-cycle disease — not the classic renal hydatid.",
      ]},
      { t: "p", v: "Renal hydatid: usually a Bosniak-mimic cystic mass with daughter cysts (wheel-spoke), serology (ELISA/IHAT) supportive but not 100%, eosinophilia inconstant. Gharbi / WHO-IWGE US types CL, CE1–CE5 guide PAIR vs surgery." },
      { t: "h", v: "Pre-operative" },
      { t: "ul", v: [
        "Albendazole 10–15 mg/kg/d in 2 doses for 4–12 weeks peri-operatively (kills scolices, reduces tension and anaphylaxis/recurrence). Add praziquantel in some protocols.",
        "Exclude liver/lung cysts (CT chest-abdomen). Type-1 hypersensitivity preparedness (anaphylaxis kit).",
        "Vaccinate? No. Inform about possible nephrectomy if parenchyma destroyed.",
      ]},
      { t: "h", v: "Operative steps (open or laparoscopic cystopericystectomy / drainage)" },
      { t: "ul", n: true, v: [
        "Approach: flank extra-peritoneal or transperitoneal lap/robot — pack the field with scolicidal-soaked packs (0.5% cetrimide, 20% hypertonic saline, or 10% povidone-iodine; avoid formalin near collecting system — scleroses it. 95% alcohol used in PAIR, not in an open field next to veins).",
        "Isolate the kidney. Needle-aspirate a small volume, inject scolicide, wait 10–15 min.",
        "Open the pericyst, suck out contents with a closed system (spill = anaphylaxis + dissemination). Remove laminated membrane and daughter cysts intact if possible (endocystectomy).",
        "Inspect for a cysto-calyceal communication (methylene blue via ureteric catheter). If present, close it; leave a drain; consider stent. Do not inject scolicide into an open collecting system (toxic, stricture).",
        "Capitonage or omentoplasty of the residual cavity; or pericystectomy if a plane exists. Partial nephrectomy if polar. Nephrectomy if the kidney is destroyed / communicating extensively / concomitant thick infected cavity.",
        "Albendazole continued 1–3 months. Follow serology and imaging for recurrence.",
      ]},
      { t: "p", v: "PAIR (puncture, aspiration, injection, re-aspiration) is for WHO CE1/CE3a liver cysts mainly; selected isolated renal CE1 without communication. Surgery remains standard for renal disease because of communication risk." },
      { t: "tip", k: "gold", v: "Dog–sheep cycle, man is accidental. Albendazole before you cut. Scolicide in, sand out, never spill, never inject scolicide into the calyx." },
    ],
  },
  {
    id: "flank-vs-anterior",
    topicId: "renal-surgery",
    title: "Flank versus anterior approaches to the kidney",
    highYield: false,
    gold: false,
    tags: ["flank", "subcostal", "chevron", "thoracoabdominal"],
    exams: [
      {
        session: "Dec",
        year: 2015,
        marks: "5+5",
        stem: "Salient features of the flank and anterior approaches to the kidney.",
      },
    ],
    related: ["gerota-fascia-approaches", "retroperitoneoscopic-nephrectomy", "ivc-thrombus"],
    references: ["Hinman Atlas", "Glenn's Urologic Surgery", "Campbell — Surgical approaches to the kidney"],
    answer: [
      { t: "tbl", c: "Compare, then list variants", h: ["", "Flank (extra-peritoneal)", "Anterior (trans-peritoneal)"], r: [
        ["Position", "Lateral decubitus, table break, kidney rest, axillary roll", "Supine, slight bump on ipsilateral flank"],
        ["Incision", "11th/12th rib, subcostal flank, or dorsal lumbotomy", "Anterior subcostal, midline, chevron/rooftop, Mercedes, thoracoabdominal"],
        ["Plane", "Through latissimus, oblique muscles, lumbodorsal fascia; stay extra-peritoneal; 12th rib may be resected", "Through linea alba or rectus; right: Kocher the duodenum; left: Mattox / medial viscera rotation or trans-mesocolic"],
        ["Hilum", "Posterior and lateral — artery met first on the left", "Anterior — vein met first (right vein short on IVC)"],
        ["Best for", "Simple nephrectomy, pyeloplasty, stones (historical), small RN, posterior tumours, trauma when already in flank (rare)", "Large tumours, IVC thrombus, bilateral, trauma laparotomy, simultaneous intraperitoneal staging, transplant implant is iliac not this"],
        ["Pain / bulge", "Intercostal nerve injury → chronic bulge; pleural tear if supra-11", "Ileus, adhesions, wound dehiscence in the obese"],
        ["Limits", "IVC, contralateral abdomen, very large mass, simultaneous bowel work", "Posterior upper pole, previous peritonitis"],
      ]},
      { t: "h", v: "Flank salient technical points" },
      { t: "ul", v: [
        "Incision from posterior axillary line / lateral sacrospinalis toward the lateral rectus, over 11th or 12th rib. Resect 12th rib sub-periosteally if needed; sweep pleura up.",
        "Identify and preserve (if possible) the subcostal nerve. Enter Gerota from behind the kidney or along psoas.",
        "Nagamatsu osteoplastic flap and dorsal lumbotomy are historical extra-peritoneal variants.",
      ]},
      { t: "h", v: "Anterior salient technical points" },
      { t: "ul", v: [
        "Anterior subcostal (chevron if bilateral / large liver): from xiphoid toward 11th/12th tip, two finger-breadths below costal margin. Excellent for RN and adrenal.",
        "Midline: trauma, IVC, bilateral. Thoracoabdominal 8–10th interspace: suprahepatic IVC, massive upper pole — divide costal margin, take down diaphragm peripherally, chest tube.",
        "Right: Kocher manoeuvre exposes IVC and renal vein. Left: incise Toldt, stack colon medially; for aorta/IVC a full medial viscera rotation.",
      ]},
      { t: "tip", k: "gold", v: "Flank = extra-peritoneal, artery first, bulge later. Anterior = the big tumour and the IVC. Match the hole to the disease." },
    ],
  },
  {
    id: "haemostatic-agents-lpn",
    topicId: "renal-surgery",
    title: "Haemostatic agents, LPN haemostasis, and high drain output after NSS",
    highYield: true,
    gold: true,
    tags: ["Floseal", "Tisseel", "LPN", "urinoma", "drain"],
    exams: [
      {
        session: "Jun",
        year: 2016,
        marks: "3+7",
        stem: "Enumerate various hemostatic agents and tissue glues used in Urology. Techniques to obtain hemostasis during laparoscopic partial nephrectomy.",
      },
      {
        session: "Jun",
        year: 2014,
        marks: "5+5",
        stem: "Describe haemostatic agents used in urological practice. Describe the management of high drain output following laparoscopic left Nephron sparing surgery for upper polar tumour.",
      },
    ],
    related: ["pn-complications", "partial-nephrectomy-nss"],
    references: [
      "EAU RCC / Laparoscopy",
      "Campbell — Partial nephrectomy",
      "Smith's Endourology — haemostasis",
    ],
    answer: [
      { t: "h", v: "Haemostatic agents and tissue glues — classify" },
      { t: "tbl", h: ["Class", "Examples", "Mechanism / use"], r: [
        ["Mechanical / cellulose", "Surgicel (oxidised cellulose), Gelfoam (gelatin), cotton pledgets", "Scaffold + contact activation. Surgicel also mildly acidic antibacterial. Pledgets for parenchymal mattress sutures in PN."],
        ["Microfibrillar collagen", "Avitene", "Platelet aggregation. Dry field needed."],
        ["Polysaccharide / starch", "Arista AH", "Water absorption, concentrate clotting factors. Absorbable."],
        ["Mineral", "Bone wax, Ostene", "Not for kidney — thermal/foreign-body. Mention to exclude."],
        ["Active biologics (thrombin)", "Floseal (gelatin + human thrombin), Surgiflo, bovine thrombin", "Need a fibrinogen source (patient’s blood). Excellent for PN bed. Do not inject into vessels (DIC/emboli)."],
        ["Fibrin sealants (glue)", "Tisseel, Evicel, Quixil — human fibrinogen + thrombin ± factor XIII, aprotinin", "Polymerise to fibrin clot. Seal collecting system / parenchyma. Spray or drip. Viral inactivation; allergic to bovine aprotinin (Tisseel older)."],
        ["Synthetic glue", "Cyanoacrylate (Histoacryl), PEG hydrogel (Coseal, Duraseal), albumin-glutaraldehyde (BioGlue)", "BioGlue on aorta/IVC; avoid in collecting system (stricture). PEG swells — do not use in tight foramina."],
        ["Energy (not ‘agents’ but expected)", "Bipolar, Ligasure, Harmonic, argon-beam, monopolar spray, laser, radiofrequency/Habib, microwave in-situ", "LPN workhorses. Argon = eschar, watch venous embolism and pneumothorax."],
        ["Systemic", "TXA, DDAVP (uraemic plateleopathy), reverse heparin, platelets, FFP, PCC", "Adjuncts, not a substitute for a stitch."],
      ]},
      { t: "h", v: "Haemostasis during LPN / RAPN" },
      { t: "ul", n: true, v: [
        "Pre-op: hold anticoagulants, map vessels (CTA), consider selective arterial clamp / early unclamp / on-clamp with ice (open) / zero-ischaemia for polar tumours.",
        "Intra-op: raise pneumoperitoneum transiently to 20 mmHg to spot venous bleeders. Artery clamp ± vein. Cold cut or shears; enucleation along pseudocapsule reduces raw sinus.",
        "Two-layer reconstruction (renorrhaphy): inner running 3-0 barbed (V-Loc/Stratafix) on the sinus and collecting system; outer interrupted 0/2-0 with Hem-o-lok ‘sliding-clip’ (Benway) to compress parenchyma without tearing.",
        "Topical: Floseal in the crater before tying the outer layer; fibrin glue on the closed surface. Bolsters (Surgicel) under sutures in open PN.",
        "Early unclamping after inner layer — any bleeder is then oversewn under vision with the kidney perfused.",
        "Off-clamp / selective: for low nephrometry polar lesions.",
        "Bail-out: additional clip on a segmental, convert to open, or completion RN if the patient is bleeding out.",
      ]},
      { t: "h", v: "High drain output after laparoscopic left upper-polar NSS (Jun 14)" },
      { t: "p", v: "Define ‘high’: >100–200 mL/shift after day 1, or any volume with drain creatinine >> serum (urine) or drain haemoglobin approaching blood. Left upper pole specifically: pleura, pancreas tail, and collecting system (upper calyx) are the three neighbours." },
      { t: "flow", title: "Is the drain urine, blood, lymph, or pancreas?", nodes: [
        { id: "a", kind: "start", label: "Send drain: Cr, amylase/lipase, haematocrit, culture; CBC, vitals", to: ["b"] },
        { id: "b", kind: "decision", label: "Unstable or drain = blood?", to: ["c", "d"] },
        { id: "c", kind: "action", label: "Resuscitate → CT angio → embolize or re-explore" },
        { id: "d", kind: "decision", label: "Drain Cr >> serum?", to: ["e", "f"] },
        { id: "e", kind: "action", label: "Urine leak: Foley, ureteric stent ± PCN, keep drain, antibiotics if infected; most seal 1–3 weeks" },
        { id: "f", kind: "decision", label: "Drain amylase high?", to: ["g", "h"] },
        { id: "g", kind: "action", label: "Pancreatic leak: NPO, TPN/octreotide, drain, surgical gastro if needed" },
        { id: "h", kind: "end", label: "Lymph / serous: low-fat diet, keep drain, time" },
      ]},
      { t: "ul", v: [
        "Urine leak is the commonest after deep upper-pole PN. Do not pull the drain until output is low and Cr is serum-like; pulling early creates a urinoma. If output stays high, add a stent (or PCN if stent fails) and a bladder catheter to drop pressure.",
        "Delayed bleed day 5–14: haematuria ± drain blood — CT angio, embolize.",
        "Chyle (left, if nodes taken): milky, triglyceride >110 mg/dL — low-fat MCT diet, octreotide, rarely glue/ligate.",
        "Pleural effusion / hydrothorax: diaphragm injury — chest tube.",
      ]},
      { t: "tip", k: "gold", v: "Floseal + sliding-clip renorrhaphy is the LPN haemostasis sentence. High drain: send creatinine before you think. Urine leak = drain the urinary tract, not the surgeon’s sleep." },
    ],
  },
  {
    id: "lap-nephrectomy-complications",
    topicId: "renal-surgery",
    title: "Laparoscopic nephrectomy complications and left-side port map",
    highYield: true,
    gold: true,
    tags: ["laparoscopy", "ports", "complications", "left RN"],
    exams: [
      {
        session: "Jun",
        year: 2014,
        marks: "3+4+3",
        stem: "Enumerate various complications of laparoscopic nephrectomy. How would you diagnose and manage them? What are the preventive measures?",
      },
      {
        session: "Dec",
        year: 2011,
        marks: "6+4",
        stem: "Describe the complications specific to the laparoscopic approach in performing a left radical Nephrectomy. Draw a diagram for port-placement for a transperitoneal left laparoscopic radical nephrectomy with the patient in the lateral position.",
      },
    ],
    related: ["retroperitoneoscopic-nephrectomy", "flank-vs-anterior", "pn-complications"],
    references: [
      "EAU Laparoscopy / RCC",
      "Campbell — Laparoscopic nephrectomy",
      "Hinman Atlas — port templates",
    ],
    answer: [
      { t: "h", v: "Complications of laparoscopic nephrectomy — generic and specific" },
      { t: "tbl", h: ["Phase", "Complication", "Diagnosis", "Management", "Prevention"], r: [
        ["Access", "Visceral/vascular injury (Veress), gas embolism, pre-peritoneal insufflation", "CO2 ET rise then fall, mill-wheel, hypotension; blood on Veress", "Desufflate, left-lateral Durant, CPR, repair", "Hasson open access; Veress with tests; low initial flow"],
        ["Insufflation", "Hypercarbia, oliguria, reduced venous return, subcutaneous emphysema, capnothorax", "ABG, airway pressures", "Lower pressure, pause, chest drain if tension", "Pressure 12 mmHg, PEEP, experienced anaesthesia"],
        ["Left RN specific", "Splenic laceration, pancreatic tail injury, diaphragmatic tear, bowel (colon) injury, stapler on the SMA or aorta mistaken for renal artery, missed lumbar/circumaortic vein, adrenal-vein tear", "Blood, drain amylase, unexplained sepsis day 2–5 (missed bowel), left shoulder pain", "Splenorrhaphy/mesh/splenectomy; drain pancreas; repair bowel; vascular control — convert early", "Identify psoas, ureter, gonadal, then artery on the aorta; take down splenocolic/splenorenal carefully; CTA for vein variants"],
        ["Hilar", "Stapler misfire, clip dislodgement, AVF if artery+vein in one staple line (avoid)", "Flooding", "Pressure, extra stapler, conversion, Satinsky", "Artery and vein separate; visualise jaws empty of extras"],
        ["Extraction", "Bag rupture (tumour spill), port-site hernia, port-site metastasis (rare)", "Pathology, bulge", "Morcellate only in simple; oncologic extraction intact", "Endocatch, close 10 mm fascia"],
        ["Late", "Incisional hernia, CKD, adrenal insufficiency if bilateral, chyle leak (para-aortic nodes)", "Clinic", "As standard", "Clip lymphatics, spare adrenal if indicated"],
      ]},
      { t: "h", v: "Left transperitoneal RN — complications to emphasise (Dec 11)" },
      { t: "ul", v: [
        "Misidentification of SMA or aorta as the renal artery — catastrophic bowel ischaemia. Always see the renal artery leaving the hilum and confirm gonadal/ureter package first.",
        "Circumaortic / lumbar vein haemorrhage behind the left renal vein.",
        "Spleen and tail of pancreas during upper-pole / adrenal dissection.",
        "Descending colon mesenteric rent (devascularise the colon if you wander inside the mesentery instead of Toldt).",
        "Diaphragm / pleural injury at the upper pole.",
      ]},
      { t: "h", v: "Port map — transperitoneal left RN, 45–70° flank" },
      { t: "p", v: "Camera 10–12 mm para-rectus at or just above the umbilicus (or slightly lateral in the obese). Working 10–12 mm in the mid-clavicular line subcostal (right hand for a right-handed surgeon standing facing the back/abdomen). Working 5 mm in the anterior axillary line at or above the umbilicus. Optional 5 mm subxiphoid for liver/spleen lift (more often right-sided liver retractor; on the left a 5 mm in the flank for upper pole). Assistant 5 mm suprapubic / lower quadrant. Draw: kidney as an oval, three ports in a triangulation facing the hilum, camera at the umbilicus, instruments 8–10 cm apart. Robot: camera same, two 8 mm arms triangulated, 12 mm assistant right hand." },
      { t: "ul", v: [
        "Rule of triangulation: camera at the apex of a triangle whose base is the two working ports, all looking at the hilum, not at the kidney convexity.",
        "Stay off the midline aorta with the medial port — that is how the SMA gets stapled.",
        "In the lateral position the colon falls; your first move after ports is Toldt incision, stack the colon, find the gonadal vein and ride it to the renal vein.",
      ]},
      { t: "tip", k: "gold", v: "Left RN disasters are SMA, spleen, pancreas and the lumbar vein. Ports triangulate on the hilum. Convert while the field is still red, not black." },
    ],
  },
  {
    id: "utuc-surgery",
    topicId: "renal-surgery",
    title: "Surgical management of upper tract urothelial carcinoma",
    highYield: true,
    gold: true,
    tags: ["UTUC", "RNU", "kidney-sparing", "Lynch"],
    exams: [
      { session: "Dec", year: 2014, marks: "10", stem: "Surgical management of upper tract urothelial carcinoma." },
    ],
    related: ["rcc-who-subtypes", "pujo-endopyelotomy"],
    references: [
      "EAU UTUC guidelines",
      "Campbell — Urothelial tumours of the upper tract",
      "WHO GU / AJCC TNM",
    ],
    answer: [
      { t: "h", v: "Risk stratify first" },
      { t: "p", v: "EAU low-risk: unifocal, <2 cm, low-grade cytology/biopsy, non-invasive on CTU, no invasive variant histology. High-risk: the rest (multifocal, ≥2 cm, high-grade, hydronephrosis, variant histology, prior cystectomy for bladder cancer). Lynch / Lynch-like (MMR, MSH2) — ask family history, test tumour." },
      { t: "h", v: "Kidney-sparing surgery (low-risk, or imperative: solitary kidney, bilateral, CKD)" },
      { t: "ul", v: [
        "Ureteroscopic ablation (Ho:YAG) + biopsy. Second look 6–8 weeks. Strict surveillance (CTU + URS).",
        "Percutaneous resection for large low-grade pelvic tumours (tract seeding risk — discuss).",
        "Distal ureterectomy + reimplant / psoas hitch / Boari for distal ureteric tumours with a healthy proximal ureter and kidney, even some high-grade if staging is favourable and bladder cuff would otherwise be the only reason for RNU.",
        "Adjuvant instillation (MMC, BCG via PCN or refluxing stent) — evidence modest.",
      ]},
      { t: "h", v: "Radical nephroureterectomy (standard for high-risk)" },
      { t: "ul", v: [
        "Kidney, Gerota (adrenal spare unless involved), entire ureter, bladder cuff. Lymphadenectomy template: pelvis — pelvic nodes; proximal ureter/pelvis — hilar, para-aortic/paracaval, ipsilateral common iliac. Yield matters.",
        "Approach: laparoscopic/robotic kidney + open/lap/endoscopic cuff, or complete robotic. Open for large invasive, lymphadenopathy.",
        "Bladder cuff methods: extravesical (pluck is inferior if the intramural ureter is not taken), transvesical excision, endoscopic collar. Avoid the ‘pluck’ of an unsecured distal ureter (seeding).",
        "Frozen section of distal ureter if bladder preserved in imperative cases.",
      ]},
      { t: "h", v: "Peri-operative extras the examiner wants" },
      { t: "ul", v: [
        "Single post-op dose of intravesical MMC (or gemcitabine) within 48–72 h after RNU reduces bladder recurrence (ODMIT-C).",
        "Neoadjuvant cisplatin-based chemo for high-risk (POUT is adjuvant; neoadjuvant used by analogy to bladder — growing standard). Adjuvant platinum if not given before and pT2+ or N+ (POUT trial).",
        "Surveillance: cystoscopy + cytology + CTU as per EAU intensity; the remaining urothelium is the risk organ.",
      ]},
      { t: "tip", k: "gold", v: "Low-risk = kidney-sparing + obsessive surveillance. High-risk = RNU including the cuff + nodes + a shot of MMC in the bladder. Never pluck and pray." },
    ],
  },
  {
    id: "pujo-endopyelotomy",
    topicId: "renal-surgery",
    title: "PUJO — etiopathogenesis, evaluation, management and endopyelotomy",
    highYield: true,
    gold: true,
    tags: ["PUJO", "pyeloplasty", "endopyelotomy", "crossing vessel"],
    exams: [
      {
        session: "June",
        year: 2022,
        marks: "7+3",
        stem: "Discuss the etiopathogenesis, evaluation and management of PUJ obstruction. Describe the present role and status of Endo pyelotomy in the management of PUJ obstruction.",
      },
    ],
    related: ["pyeloplasty-types", "fusion-anomalies-horseshoe", "kidney-ascent-anh-sfu"],
    references: [
      "Campbell — Congenital PUJO / Adult PUJO",
      "EAU Paediatric / Urolithiasis",
      "Smith's Endourology — endopyelotomy",
    ],
    answer: [
      { t: "h", v: "Etiopathogenesis" },
      { t: "tbl", h: ["", "Mechanism"], r: [
        ["Intrinsic (primary)", "Interrupted circular muscle / excess longitudinal fibres at PUJ; aperistaltic adynamic segment. Embryologic (ureteric-bud / Wnt) "],
        ["Extrinsic", "Lower-pole crossing vessel (accessory anterior artery ± vein) tethering the PUJ; bands; high insertion; horseshoe isthmus; retrocaval ureter is a different entity (IVC)"],
        ["Secondary", "Stones, TB, iatrogenic (URS, PCNL, failed pyeloplasty), VUR (yo-yo), tumours, fibroepithelial polyp"],
        ["Functional", "High urine flow in diuresis unmasking a borderline PUJ; infection oedema"],
      ]},
      { t: "h", v: "Evaluation" },
      { t: "ul", v: [
        "Presentation: flank pain (Dietl’s crisis), infection, stones, incidental ANH, hypertension rare, haematuria after minor trauma (hydronephrotic kidney).",
        "US: hydronephrosis, parenchymal thickness, no dilated ureter (vs UVJO).",
        "Diuretic MAG3 (F−15): delayed drainage, T½ >20 min, cortical retention, split function. Whitaker if equivocal (pressure-flow >22 cm H2O).",
        "CTU / MRU: crossing vessel (mandatory before endopyelotomy), stones, horseshoe, tumour.",
        "IVU historical ‘ballooning with delayed nephrogram’. Retrograde pyelogram on table to define length of stricture.",
        "Paediatric: SFU grade, serial US, MAG3 if SFU 3–4 or dropping function.",
      ]},
      { t: "h", v: "Management" },
      { t: "ul", v: [
        "Observe: SFU 1–2, good function, no infection/pain — especially infants (many ‘obstructions’ improve).",
        "Gold standard reconstruction: dismembered Anderson–Hynes pyeloplasty (open, lap, robotic) — excise the adynamic segment, transpose anterior to a crossing vessel, spatulate, dependent anastomosis, stent 4–6 weeks. Success >90–95%.",
        "Foley Y-V, spiral flap (Culp–DeWeerd), Scardino–Prince vertical flap: long, dependent, wide pelvis — see pyeloplasty master.",
        "Vascular hitch (Hellström) alone: only if the PUJ is intrinsically normal after the vessel is lifted (intra-op Whitaker / peristalsis) — controversial, selected children.",
        "Nephrectomy: split function <10–15% after decompression, and a healthy mate, with infection or stones.",
        "Temporise: PCN or stent in infection, AKI, pregnancy.",
      ]},
      { t: "h", v: "Endopyelotomy — present role (2022 status)" },
      { t: "p", v: "Full-thickness incision of the PUJ through the lateral wall (endoscopic equivalent of Davis intubated ureterotomy) via antegrade (PCN) or retrograde (Acucise / Ho:YAG) approach, then prolonged stenting (6 weeks)." },
      { t: "ul", v: [
        "Requirements: short stricture <1–2 cm, no crossing vessel on CT angio/endoluminal US, reasonable function (>25%), no massive redundant pelvis, not horseshoe, not a child as first-line.",
        "Success 50–80% — clearly inferior to pyeloplasty as primary treatment. Better as salvage for a short secondary stricture after pyeloplasty (here it still has a niche, 60–70%).",
        "Acucise (cautery balloon) has declined because of vessel injury. Ho:YAG under vision is safer.",
        "Complications: bleeding (crossing vessel — the reason you image), urinoma, stent symptoms, failure.",
        "Current status: not first-line for primary PUJO in the robotic era. Reserve for selected secondary short, non-vascular, poor-surgical-candidate cases, or as a retrograde attempt before re-do pyeloplasty in a hostile abdomen.",
      ]},
      { t: "tip", k: "gold", v: "Primary PUJO = dismembered pyeloplasty, vessel anterior. Endopyelotomy is a lateral cut that you only make after proving there is no crossing vessel — and even then pyeloplasty is better." },
    ],
  },
  {
    id: "pyeloplasty-types",
    topicId: "renal-surgery",
    title: "Types of pyeloplasty, specific indications, trans-mesocolic approach",
    highYield: true,
    gold: false,
    tags: ["Anderson-Hynes", "Culp", "Foley", "trans-mesocolic"],
    exams: [
      { session: "Dec", year: 2017, marks: "5+5", stem: "Types of pyeloplasty and their indications in specific situations." },
      {
        session: "Dec",
        year: 2012,
        marks: "2+3+2+3",
        stem: "What is trans-mesocolic pyeloplasty? What are its advantages, indications and disadvantages?",
      },
    ],
    related: ["pujo-endopyelotomy", "fusion-anomalies-horseshoe"],
    references: [
      "Hinman Atlas — pyeloplasty flaps",
      "Campbell — PUJO",
      "Kumar / Indian series on trans-mesocolic lap pyeloplasty",
    ],
    answer: [
      { t: "tbl", c: "Match the operation to the pelvis", h: ["Operation", "Idea", "Indication"], r: [
        ["Anderson–Hynes dismembered", "Excise PUJ, spatulate ureter, anastomose to dependent pelvis; transpose anterior to crossing vessel", "Default primary PUJO, crossing vessel, most redo, horseshoe (plus isthmus management)"],
        ["Foley Y-V (non-dismembered)", "Y on pelvis, V advancement across PUJ", "High insertion, modest pelvis, NO crossing vessel (vessel would still tether)"],
        ["Culp–DeWeerd spiral flap", "Spiral pelvic flap down a long proximal ureteric stricture", "Long PUJ stricture with a large pelvis"],
        ["Scardino–Prince vertical flap", "Vertical pelvic flap", "Long stricture, large pelvis, alternative to Culp"],
        ["Heineke–Mikulicz (Fenger)", "Longitudinal cut, transverse close", "Very short, wide PUJ — largely abandoned (tension, poor spatulation)"],
        ["Davis intubated ureterotomy", "Leave a spatulated gap over a stent to regenerate", "Historical; endoscopic analogue is endopyelotomy"],
        ["Ureterocalicostomy", "Anastomose spatulated ureter to a lower-pole calyx (amputate lower pole parenchyma)", "Failed pyeloplasty, small intrarenal pelvis, infundibular stenosis, horseshoe with destroyed PUJ"],
        ["Hellström vascular hitch", "Move crossing vessel cephalad, leave PUJ", "Child, proven extrinsic-only, normal PUJ calibre"],
        ["Ileal interposition / autotransplant", "Replace long ureter", "Pan-ureteric stricture, not a first PUJO operation"],
      ]},
      { t: "h", v: "Trans-mesocolic pyeloplasty (Dec 12)" },
      { t: "p", v: "A laparoscopic/robotic left-sided approach in which the PUJ is reached through a window in the colonic mesentery (trans-mesocolic), rather than by reflecting the descending colon along Toldt (colo-epiploic / paracolic approach)." },
      { t: "ul", v: [
        "Indications: thin mesocolon, prominent extra-renal pelvis sitting in a mesenteric window (thin patients, many Indian/Asian series), primary PUJO, no prior retroperitoneal surgery.",
        "Advantages: less colon mobilisation, shorter operative time, less ileus, direct view of the pelvis, fewer port gymnastics, theoretically less colonic denervation.",
        "Disadvantages / contraindications: thick/fat mesentery (obese), mesenteric vessels (IMA branches, marginal artery of Drummond) at risk of injury → colonic ischaemia, limited space for a huge pelvis or crossing-vessel transposition, not for redo with adhesions, not for right side (mesentery of right colon is not the same window — right side is Kocher/Toldt). Learning curve: mistaking a mesenteric vein for the PUJ.",
        "Steps: tilt, identify the bulge of the pelvis through the mesocolon, window between colonic vessels, dismembered pyeloplasty as usual, close the window to prevent internal hernia.",
      ]},
      { t: "tip", k: "gold", v: "If there is a crossing vessel or a bad segment, dismember (Anderson–Hynes). Flaps are for long strictures with a roomy pelvis. Trans-mesocolic is a left-sided lap shortcut through a thin mesentery — do not take the IMA." },
    ],
  },
];
