import type { Master } from "../types";

export const renalAnatomy: Master[] = [
  {
    id: "kidney-anomalies-endourology",
    topicId: "renal-anatomy",
    title: "Developmental anomalies and surgical anatomy for endourology",
    highYield: true,
    gold: true,
    tags: ["embryology", "anomalies", "PCNL", "RIRS", "Brodel"],
    exams: [
      {
        session: "June",
        year: 2022,
        marks: "4+6",
        stem: "Describe the developmental anomalies of kidney. Discuss the surgical anatomy of kidney in respect to various endourological procedures.",
      },
    ],
    related: ["fusion-anomalies-horseshoe", "renal-vascular-anatomy", "pcnl-anatomy-access", "kidney-ascent-anh-sfu"],
    references: [
      "Campbell-Walsh-Wein Urology, 12th ed. Ch. Embryology and Anomalies of the Kidney",
      "Hinman Atlas of Urologic Surgery — renal topography",
      "Smith's Textbook of Endourology — calyceal anatomy and puncture",
      "Sampaio FJB. Intrarenal anatomy for PCNL",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map (10 marks)", v: "Anomalies 4: classify as number / ascent / fusion / rotation / cystic / vascular — one table, one line each. Endourology 6: Brodel line, calyceal orientation, infundibular angles, arterial segments, collecting-system relations to vessels, puncture and RIRS implications. Draw a mid-coronal kidney with anterior/posterior calyces." },
      { t: "h", v: "Developmental anomalies — classify, do not dump" },
      { t: "tbl", c: "Potter / Campbell grouping", h: ["Class", "Entity", "Key surgical pearl"], r: [
        ["Number", "Agenesis, supernumerary, renal unit duplication", "Unilateral agenesis: look for ipsilateral Wolffian/Müllerian anomaly (Zinner, uterine unicornis). Confirm contralateral compensatory hypertrophy before calling ‘solitary’."],
        ["Ascent / position", "Pelvic, iliac, abdominal, thoracic, crossed ectopia", "Ectopic kidney: anomalous short vessels from aorta/iliacs; PUJO and VUR common; lithiasis access is anterior and pelvic."],
        ["Fusion", "Horseshoe, pancake/discoid, L-shaped, sigmoid, crossed-fused", "Isthmus usually at L3–4, isthmic calyx faces medially; PUJ directed ventrally."],
        ["Rotation", "Incomplete (fetal), hyper-rotation, reverse rotation", "Hilum faces anterior in malrotation — ‘posterior’ calyx on IVU is not Brodel’s plane."],
        ["Form / cystic", "Multicystic dysplastic kidney, hypoplasia, ADPKD/ARPKD, calyceal diverticulum, infundibular stenosis", "MCDK involutes; do not confuse with PUJO on antenatal scans (see SFU)."],
        ["Vascular", "Aberrant/accessory polar arteries, early branching, circumaortic/retroaortic left renal vein, nutcracker", "Crossing vessel at PUJ; polar artery to lower-pole puncture; vein variants in donor/left RN."],
      ]},
      { t: "p", v: "Embryologic key: ureteric bud (wk 4, mesonephric duct) induces metanephric blastema. Ascent from S1–2 to L1 (wk 6–9) with medial rotation 90°. Blood supply sequential from iliacs then aorta; persistence of caudal vessels = accessory arteries. Failure of ascent, fusion of metanephroi across midline, or incomplete rotation produce the anomalies above." },
      { t: "h", v: "Surgical anatomy for endourology" },
      { t: "h", v: "Gross relations (write in 30 seconds)", l: 3 },
      { t: "ul", v: [
        "Right kidney lower (liver); both retroperitoneal, within Gerota. 12th rib crosses upper pole (right) / mid-zone (left).",
        "Hilum anterior→posterior: vein, artery, pelvis (VAP). On the left a second artery or lumbar vein may sit posterior.",
        "Pleural reflection: posterior 12th rib — upper-pole supra-12th puncture risks pneumothorax; stay below the posterior axillary line and below 11th rib when possible.",
      ]},
      { t: "h", v: "Calyceal anatomy — Sampaio (the table they want)", l: 3 },
      { t: "tbl", h: ["Feature", "Typical arrangement", "Endourologic implication"], r: [
        ["Anterior vs posterior calyces", "Right: anterior calyces lateral on IVU; left: more variable. In true lateral, posterior calyces point posterolateral ~20–30° to the frontal plane", "Prone PCNL: puncture posterior calyx along Brodel’s avascular plane. Supine (Galdakao-Valdivia): slightly more lateral puncture, still posterior papilla."],
        ["Brodel’s white line", "Longitudinal avascular plane just posterior to lateral convex border, between anterior and posterior arterial trees", "Ideal parenchymal tract. Too anterior = anterior segmental arteries; too posterior = posterior branch of renal artery (most common arterial injury in PCNL)."],
        ["Infundibulo-pelvic angle (IPA)", "Lower-pole IPA <45° and long infundibulum (>3 cm) predict SWL/RIRS failure (Elbahnasy)", "Steep IPA → PCNL or flexible URS with ureteric access sheath; consider lower-pole puncture even for pelvic stones."],
        ["Compound vs simple papillae", "Upper and lower poles often compound; mid-zone simple", "Compound papilla = safer, larger target; mid-calyceal puncture more likely to injure infundibular vessels."],
        ["Pelvicalyceal type (Sampaio A/B)", "A1: mid-zone drains to upper/lower; A2: mid has own major calyx; B: mid drains independently to pelvis or crossed", "Choose the calyx that gives a straight shot to the stone-bearing infundibulum; avoid crossing the pelvis blindly."],
      ]},
      { t: "h", v: "Arterial anatomy for puncture and partial nephrectomy", l: 3 },
      { t: "ul", v: [
        "Main renal artery → anterior and posterior divisions. Posterior division is a single branch in ~50% and supplies the entire posterior mid-zone — injury = major haemorrhage.",
        "Five Graves segments: apical, anterior-superior, anterior-inferior, inferior, posterior. Segmental arteries are end-arteries — no collateral between segments.",
        "Infundibular arteries run along anterior and posterior surfaces of infundibula; fornix puncture through papilla avoids them. Infundibular (not papillary) puncture is the classic cause of delayed A-V fistula / pseudoaneurysm.",
        "Accessory lower-pole artery: present in 20–30%; crossing vessel in PUJO; at risk in lower-pole PCNL if tract too medial.",
      ]},
      { t: "h", v: "Procedure-specific pearls", l: 3 },
      { t: "tbl", h: ["Procedure", "Anatomic rule"], r: [
        ["PCNL puncture", "Bull’s-eye or triangulation onto posterior papilla; tract through Brodel; 16–18G needle, 0.035\" wire; stay off the infundibular neck. Upper-pole: supra-12 only if needed for complete staghorn / PUJ access; screen for hydrothorax."],
        ["Mini-PCNL / Superperc", "Same papilla rule; smaller sheath does not forgive a wrong calyx. Multiple tracts through separate papillae, not through one infundibulum."],
        ["RIRS / fURS", "Access sheath to PUJ; lower-pole deflection limited by IPA and infundibular width. Relocate stone to upper/mid calyx (dust or basket). Intra-renal pressure <30–40 cm H2O to protect fornices."],
        ["SWL coupling", "Stone–skin distance, rib shadowing of upper pole, and lower-pole dependent anatomy determine clearance more than generator type."],
        ["Endopyelotomy", "Crossing vessel is usually anterior (errant posterior endopyelotomy is the disaster). Lateral full-thickness cut only after confirming no crossing vessel (CTA/endoluminal US)."],
        ["Laparoscopic / robotic PN", "Early branching (<1.5 cm) precludes safe main-artery clamp — selective segmental control. Vein variants (circumaortic) change left RN template."],
      ]},
      { t: "flow", title: "Choosing a PCNL calyx", nodes: [
        { id: "a", kind: "start", label: "Map stone on CT (prone or supine as you will operate)", to: ["b"] },
        { id: "b", kind: "decision", label: "Need straight access to PUJ / upper ureter / complete staghorn?", to: ["c", "d"] },
        { id: "c", kind: "action", label: "Upper-pole posterior calyx (accept supra-12 risk)", to: ["e"] },
        { id: "d", kind: "action", label: "Stone-bearing posterior calyx; add second tract if needed", to: ["e"] },
        { id: "e", kind: "decision", label: "Papilla visualised on air/contrast pyelogram?", to: ["f", "g"] },
        { id: "f", kind: "end", label: "Puncture papilla, dilate, confirm no infundibular blush" },
        { id: "g", kind: "warn", label: "Re-angle; do not force a fornix-to-infundibulum tract" },
      ]},
      { t: "tip", k: "gold", title: "Gold line", v: "Anomalies are classified by number, ascent, fusion, rotation and vessels. For endourology the only plane that matters is Brodel’s: puncture a posterior papilla, never an infundibulum. The posterior segmental artery is the vessel you bleed from." },
    ],
  },
  {
    id: "fusion-anomalies-horseshoe",
    topicId: "renal-anatomy",
    title: "Fusion anomalies and the diseased horseshoe kidney",
    highYield: true,
    gold: true,
    tags: ["horseshoe", "fusion", "staghorn", "PUJO", "embryology"],
    exams: [
      {
        session: "Jun",
        year: 2016,
        marks: "5+5",
        stem: "Enumerate the different types of fusion anomaly of kidney with diagrammatic representation of any two. Management of staghorn calculus in horse shoe kidney.",
      },
      {
        session: "Jun",
        year: 2021,
        marks: "4+4+2",
        stem: "Describe embryological development of kidney. Enumerate various fusion anomalies. What is diseased horseshoe kidney?",
      },
      {
        session: "Dec",
        year: 2014,
        marks: "10",
        stem: "Embryology and surgical importance of Horse-shoe kidney.",
      },
    ],
    related: ["kidney-anomalies-endourology", "horseshoe-staghorn", "pujo-endopyelotomy", "left-renal-vein"],
    references: [
      "Campbell-Walsh-Wein — Anomalies of the Upper Urinary Tract",
      "EAU Urolithiasis — anomalous kidneys",
      "Glenn's Urologic Surgery — horseshoe pyeloplasty / isthmus",
      "Boyce / Graves — isthmus anatomy",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "Embryology 2–3 · Fusion types with two diagrams 3 · Horseshoe anatomy/associations 2 · Diseased horseshoe + staghorn plan 3. Draw the horseshoe with isthmus, lower-pole fusion, ventrally directed PUJ and crossing isthmic vessels." },
      { t: "h", v: "Embryology of the kidney (write as a timeline)" },
      { t: "ul", n: true, v: [
        "Pronephros (wk 3): cervical, vestigial.",
        "Mesonephros (wk 4–8): thoracic/upper lumbar; mesonephric (Wolffian) duct persists in male.",
        "Metanephros (wk 5 onward): ureteric bud from mesonephric duct at wk 4–5 induces metanephric mesenchyme (WT1, GDNF–RET, PAX2).",
        "Ascent wk 6–9 from pelvis (S1–2) to lumbar fossa (L1); 90° medial rotation so hilum faces anteromedial.",
        "Blood supply ‘climbs’ — caudal branches involute; persistence = accessory/polar arteries.",
      ]},
      { t: "p", v: "Fusion anomalies occur when the metanephric blastemas meet in the pelvis before ascent (wk 4–6), usually because an umbilical artery or abnormal flexion apposes the lower poles. The isthmus then arrests ascent beneath the IMA (classic L3–4 lie)." },
      { t: "h", v: "Types of fusion anomaly (draw any two)" },
      { t: "tbl", h: ["Type", "Anatomy", "Diagram cue"], r: [
        ["Horseshoe (most common, 1:400–600)", "Lower-pole fusion 90–95%; isthmus parenchyma or fibrous; PUJs anterior", "U-shape across midline, isthmus over aorta/IVC, IMA hook"],
        ["Crossed fused ectopia", "Both units on one side, ureters insert orthotopically (one crosses midline)", "L- or S-shaped mass; crossed ureter"],
        ["Sigmoid / S-shaped", "Crossed fused with opposite rotation of the two pelves", "S curve; two pelves facing opposite ways"],
        ["L-shaped (lump on iliac)", "Superior pole of crossed kidney fused to lower pole of orthotopic", "Right angle mass over sacral promontory"],
        ["Disc / pancake / cake", "Extensive polar fusion into a single pelvic mass, often pelvic vessels", "Flat midline pelvic cake"],
        ["Unilateral fused (inferior ectopia)", "One kidney fused to the inferior pole of its mate, both on same side", "Vertical stacked kidneys"],
      ]},
      { t: "h", v: "Horseshoe kidney — surgical anatomy" },
      { t: "ul", v: [
        "Incidence 1:400–600; M>F; associated: PUJO (most common, 15–30%), stones, infection, VUR, hypospadias, bicornuate uterus, trisomy 18, Turner, VACTERL, retrocaval ureter rarely.",
        "Isthmus at L3–4, anterior to aorta/IVC, caudal to IMA. Isthmus has its own calyx in ~80% (isthmic calyx faces medially/caudally).",
        "Malrotation: calyces posterior, pelvis and PUJ anterior. Ureter drapes over isthmus — relative obstruction.",
        "Blood supply: multiple (2–5) arteries from aorta, IMA, iliacs, sacral — never assume a single hilum. Isthmic artery from aorta or IMA.",
        "Low-lying, poorly protected by ribs → more susceptible to blunt trauma (compression against spine).",
      ]},
      { t: "h", v: "What is a ‘diseased’ horseshoe kidney?" },
      { t: "p", v: "A horseshoe that has acquired pathology requiring treatment — not the fusion itself. Classic diseases: PUJO, urolithiasis (including staghorn), recurrent UTI/pyelonephritis, tumour (RCC, TCC, Wilms, carcinoid of isthmus — rare but exam-favourite), trauma, and rarely Renovascular hypertension from anomalous vessels." },
      { t: "h", v: "Staghorn calculus in horseshoe (Jun 16 part B)" },
      { t: "p", v: "Stone risk: stasis from high PUJ insertion + malrotated calyces + UTI. Metabolic work-up is still mandatory (hypercalciuria, hypocitraturia as in orthotopic kidneys)." },
      { t: "ul", v: [
        "Imaging: NCCT + contrast urography / CT angio to map vessels and isthmic calyx. MAG3 if PUJO suspected.",
        "SWL: possible for <1.5 cm in a dependent, well-drained calyx but clearance is poorer (high PUJ, medial lie). Not first-line for staghorn.",
        "RIRS: feasible for modest burden; steep deflection into medial/isthmic calyx is the limiter.",
        "PCNL is standard for staghorn. Patient prone or Galdakao-supine. Upper-pole posterior calyx is the preferred access (more posterior and lateral than expected; often supra-12). Tract is more posterior/medial because of malrotation — mind the isthmic vessels and the colon which lies more posterior.",
        "Second tract into isthmic or lower-pole calyx often needed. Flexible nephroscopy is essential.",
        "If concurrent PUJO: endopyelotomy is relatively contraindicated (crossing vessels + high insertion). Laparoscopic/robotic pyeloplasty ± isthmectomy / isthmus division is the reconstructive gold standard; simultaneous pyelolithotomy if burden modest.",
        "Open anatrophic nephrolithotomy / extended pyelolithotomy reserved for failed endourology or massive infundibular stenosis.",
        "Isthmus: divide only if it facilitates drainage or tumour/isthmic stone; oversew and cover. Do not divide casually — it has functioning parenchyma and an artery.",
      ]},
      { t: "flow", title: "Horseshoe staghorn", nodes: [
        { id: "a", kind: "start", label: "CT urography + angio map; culture; metabolic labs", to: ["b"] },
        { id: "b", kind: "decision", label: "PUJO present?", to: ["c", "d"] },
        { id: "c", kind: "action", label: "Robotic/lap pyeloplasty ± pyelolithotomy (or staged PCNL then pyeloplasty)", to: ["e"] },
        { id: "d", kind: "action", label: "PCNL via upper-pole posterior calyx ± second isthmic tract", to: ["e"] },
        { id: "e", kind: "end", label: "Second-look / RIRS residual; metabolic prevention" },
      ]},
      { t: "tip", k: "gold", v: "Horseshoe = failed ascent because the isthmus hooks under IMA. Pelvis is anterior, vessels are multiple, PUJO and stones are the diseases. For staghorn: upper-pole PCNL, not SWL; do not endopyelotomise a horseshoe." },
    ],
  },
  {
    id: "gerota-fascia-approaches",
    topicId: "renal-anatomy",
    title: "Gerota fascia, Indian pioneer of retroperitoneoscopy, nephrectomy approaches",
    highYield: true,
    gold: true,
    tags: ["Gerota", "Gaur", "flank", "nephrectomy", "retroperitoneoscopy"],
    exams: [
      {
        session: "Jun",
        year: 2019,
        marks: "3+1+6",
        stem: "Describe anatomy of Gerota's fascia. Who pioneered retro-peritoneoscopic surgery in India? Describe various surgical approaches for nephrectomy.",
      },
    ],
    related: ["retroperitoneoscopic-nephrectomy", "flank-vs-anterior", "lap-nephrectomy-complications"],
    references: [
      "Campbell-Walsh-Wein — Surgical Anatomy of the Retroperitoneum",
      "Gaur DD. Laparoscopic operative retroperitoneoscopy: use of a new device. J Urol 1992;148:1137–9",
      "Hinman / Glenn's — flank, thoracoabdominal, chevron, transperitoneal lap",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Gerota 3 (layers, attachments, contents) · Pioneer 1 (D.D. Gaur, balloon retroperitoneoscopy, 1992) · Approaches 6 as a table: indication, incision, advantage, danger. Draw a transverse section through L1." },
      { t: "h", v: "Anatomy of Gerota’s fascia" },
      { t: "p", v: "Gerota (renal) fascia is a condensation of retroperitoneal connective tissue that encloses the kidney, adrenal, perinephric fat and upper ureter. It is distinct from the true (fibrous) capsule of the kidney, which is on the parenchyma." },
      { t: "ul", v: [
        "Anterior leaf (Toldt / anterior perirenal fascia): fuses with contralateral fascia across midline in front of the great vessels, or blends with subperitoneal connective tissue. Relatively thin.",
        "Posterior leaf (Zuckerkandl / posterior perirenal fascia): thicker; fuses with fascia of psoas and quadratus lumborum, and with the lateroconal fascia.",
        "Lateroconal fascia: fusion of anterior and posterior leaves lateral to the kidney; continues as parietal peritoneum reflection. The pararenal (paranephric) fat of Gerota’s outer surface lies between lateroconal fascia and transversalis.",
        "Superior: encloses the adrenal; fuses with diaphragmatic fascia. This is why a radical nephrectomy can take the adrenal in one packet, and why retroperitoneal collections are limited cranially.",
        "Inferior: open / loosely closed around the ureter — blood, urine and pus track into the pelvis (psoas gutter). Clinically important in trauma and urinoma.",
        "Medial: posterior leaf fuses to the vertebral body / great-vessel adventitia. Anterior leaf crosses midline — explaining contralateral spread of urinoma/haematoma in some Grade IV injuries.",
      ]},
      { t: "tbl", h: ["Compartment", "Contents"], r: [
        ["Perirenal (inside Gerota)", "Kidney, adrenal, perinephric fat, proximal ureter, renal vessels"],
        ["Anterior pararenal", "Pancreas, D2–3, ascending/descending colon (behind peritoneum, in front of Gerota)"],
        ["Posterior pararenal", "Fat between Zuckerkandl fascia and transversalis; no organs"],
      ]},
      { t: "p", v: "Surgical relevance: radical nephrectomy = extra-Gerota dissection; simple nephrectomy / donor / pyeloplasty = intra-Gerota or on-capsule; partial nephrectomy uses the potential plane between capsule and fat (defatting) except over the tumour. In trauma, Gerota tamponades haematoma — opening it commits you to repair or nephrectomy." },
      { t: "h", v: "Pioneer of retroperitoneoscopic surgery in India" },
      { t: "p", v: "Dr Durga Das Gaur (D.D. Gaur), Mumbai. In 1992 he described balloon dilatation of the retroperitoneum (Gaur balloon — a surgical glove / fingerstall on a catheter) to create a working space without violating the peritoneum (J Urol 1992). This is the origin of modern retroperitoneoscopic nephrectomy, pyeloplasty and adrenalectomy in India and worldwide." },
      { t: "h", v: "Surgical approaches for nephrectomy" },
      { t: "tbl", c: "Match approach to indication", h: ["Approach", "Incision / access", "Best for", "Limitations"], r: [
        ["Flank / 11th or 12th rib (simple / extra-peritoneal)", "Lateral decubitus, 11th/12th rib tip to lateral rectus; rib resection optional", "Simple nephrectomy, pyeloplasty, stones historically", "Limited hilar / IVC / contralateral view; wound pain, bulge"],
        ["Anterior subcostal / chevron / midline", "Supine; unilateral subcostal or rooftop for bilateral / large mass", "Large tumours, IVC thrombus (with sternotomy/thoracoabdominal), trauma, bilateral", "Ileus, adhesions; longer recovery"],
        ["Thoracoabdominal (9th/10th interspace)", "Flank extended across costal margin into chest", "Massive upper-pole / adrenal / suprahepatic IVC thrombus", "Chest tube, pulmonary morbidity"],
        ["Transperitoneal laparoscopic / robotic", "45–70° flank; ports: camera para-rectus, working mid-clavicular and anterior axillary", "Most radical/simple nephrectomy, PN, donor", "Prior laparotomy, horseshoe isthmus, uncorrected coagulopathy"],
        ["Retroperitoneoscopic (Gaur)", "Flank, 12th rib tip balloon; camera at Petit’s triangle / tip of 12th", "Posterior tumours, prior abdominal surgery, morbid obesity (short direct hilum), right adrenal", "Small space, steep learning, limited for very large tumours (>10–12 cm) and IVC thrombus"],
        ["Lumbodorsal / Nagamatsu (historical)", "Dorsal osteoplastic flap", "Rarely used", "Superseded"],
      ]},
      { t: "h", v: "Principles common to all" },
      { t: "ul", v: [
        "Early vascular control: artery then vein (except some right RN where vein is short — still artery first conceptually). Adrenal vein, gonadal, lumbar, posterior lumbar tributaries on the left.",
        "Gerota plane for oncologic RN; intrafascial for simple / xanthogranulomatous / donor.",
        "Ureter divided last after vessels, or early if it helps retract (lap left RN).",
        "Lymphadenectomy not routine for low-stage RCC; template if nodes bulky (EAU).",
      ]},
      { t: "tip", k: "gold", v: "Gerota is closed above and open below. Radical = outside Gerota; simple = inside. The one-mark name is D.D. Gaur, balloon retroperitoneoscopy, 1992." },
    ],
  },
  {
    id: "kidney-ascent-anh-sfu",
    topicId: "renal-anatomy",
    title: "Kidney development and ascent, ANH pathophysiology, SFU grading",
    highYield: true,
    gold: true,
    tags: ["ascent", "ANH", "SFU", "embryology", "hydronephrosis"],
    exams: [
      {
        session: "Dec",
        year: 2021,
        marks: "2+3+5",
        stem: "Describe the development and ascent of kidney. Describe pathophysiology of antenatal hydronephrosis. Describe Society for Foetal Urology Grading system, its merits and demerits.",
      },
    ],
    related: ["fusion-anomalies-horseshoe", "pujo-endopyelotomy", "kidney-anomalies-endourology"],
    references: [
      "Campbell-Walsh-Wein — Paediatric Urology / Embryology",
      "Fernbach SK, Maizels M, Conway JJ. SFU grading. 1993",
      "Nguyen HT et al. UTD classification. J Pediatr Urol 2014",
      "EAU / ESPU Paediatric Urology guidelines — ANH",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Development/ascent 2 · ANH cascade 3 · SFU grades with a diagram 3 · merits/demerits vs UTD 2. Draw SFU 0–4 pelvicalyceal cartoons." },
      { t: "h", v: "Development and ascent" },
      { t: "ul", v: [
        "Three successive kidneys: pronephros, mesonephros, metanephros. Only metanephros is definitive.",
        "Ureteric bud (wk 4) from Wolffian duct contacts metanephric mesenchyme; reciprocal induction (GDNF–RET, WT1, PAX2, WNT9b) → nephrons and collecting system.",
        "Branching: ureteric bud → pelvis, major/minor calyces, collecting ducts (≈15 generations).",
        "Nephron formation continues to 36 weeks (≈1 million/kidney); no new nephrons after term — preterm / obstruction permanently reduces nephron mass.",
        "Ascent: from S1–2 pelvis to L1 lumbar fossa during wk 6–9, driven by caudal embryonic growth more than active migration. Simultaneous 90° medial rotation (hilum from anterior to medial).",
        "Vascular ‘ladder’: sequential aortic sprouts; caudal ones involute. Arrest of ascent = pelvic kidney; fusion during ascent = horseshoe; failed rotation = malrotated kidney with anterior pelvis.",
      ]},
      { t: "h", v: "Pathophysiology of antenatal hydronephrosis (ANH)" },
      { t: "p", v: "ANH = dilatation of the fetal renal collecting system, seen in 1–2% of pregnancies. It is a finding, not a diagnosis. Mechanisms:" },
      { t: "ul", v: [
        "Transient / physiologic: high fetal urine output (4–6× adult on a weight basis), compliant fetal pelvis, maternal hydration — majority resolve postnatally.",
        "Obstruction: PUJO (most common significant), UVJO / megaureter, PUV (bilateral + thick bladder + keyhole urethra in male), ureterocele, urethral atresia, cloacal anomalies.",
        "Reflux: VUR accounts for 10–20% of ANH; dilatation from back-pressure and, postnatally, pyelonephritis-scarring.",
        "Developmental: non-obstructive megaureter, prune belly, megacystis-megaureter.",
        "At nephron level: raised pelvic pressure → reduced renal blood flow (thromboxane A2, angiotensin II) → tubular apoptosis, interstitial fibrosis, impaired concentrating ability and renin-driven hypertension if severe/prolonged. Fetal urine is the main source of amniotic fluid after 16 weeks — bilateral severe ANH → oligohydramnios → Potter sequence (pulmonary hypoplasia, potter facies, limb deformities).",
      ]},
      { t: "tbl", h: ["APD (3rd trimester, commonly quoted)", "Likely significance"], r: [
        ["<7 mm (or SFU 1)", "Almost always physiologic; postnatal US at 1–4 weeks"],
        ["7–10 mm", "Follow; ~15% have PUJO/VUR"],
        [">10–15 mm", "Significant pathology more likely; early postnatal US + VCUG/MAG3 as indicated"],
        [">15 mm, or SFU 3–4, or parenchymal thinning, or bilateral / bladder involvement", "High risk; same-week postnatal US, infection prophylaxis debate, early functional study"],
      ]},
      { t: "h", v: "SFU grading (Fernbach, Maizels, Conway 1993)" },
      { t: "tbl", c: "Society for Fetal Urology — postnatal / fetal US", h: ["Grade", "Pelvis", "Calyces", "Parenchyma"], r: [
        ["0", "Intact", "Normal", "Normal"],
        ["1", "Slight dilatation", "Normal calyces", "Normal"],
        ["2", "Dilated", "Some calyceal dilatation (not all)", "Normal"],
        ["3", "Dilated", "All calyces dilated", "Normal thickness"],
        ["4", "Dilated", "All calyces dilated", "Thinned parenchyma"],
      ]},
      { t: "h", v: "Merits" },
      { t: "ul", v: [
        "Simple, universally taught, uses grey-scale US without specialised software.",
        "Incorporates parenchymal thinning (the variable that actually predicts function loss) — unlike APD alone.",
        "Good inter-observer agreement at the extremes (0–1 vs 4); useful for serial comparison.",
        "Correlates reasonably with need for pyeloplasty at grade 3–4.",
      ]},
      { t: "h", v: "Demerits" },
      { t: "ul", v: [
        "Subjective mid-grades (2 vs 3) — poor kappa; a ‘full’ pelvis without calyceal definition is graded inconsistently.",
        "Does not include ureteric dilatation, bladder wall, amniotic fluid, or laterality — so PUV and VUR are under-described.",
        "No APD measurement: a 25 mm pelvis with mild calyces may be SFU 2 yet more ominous than a 12 mm SFU 3.",
        "Not designed for postnatal cortical scars, duplex moieties, or cystic dysplasia.",
        "Superseded in many units by the Urinary Tract Dilatation (UTD A/P) classification (Nguyen 2014), which grades A0–A3 (antenatal) and P0–P3 (postnatal) using APD, calyces, parenchyma, ureter, bladder and amniotic fluid — more complete but more cumbersome.",
      ]},
      { t: "tip", k: "gold", v: "Ascent is wk 6–9, rotation 90°, IMA stops the horseshoe. ANH is pressure ± reflux ± physiology; oligohydramnios is the fetal-life threat. SFU 4 = thinned parenchyma — that is the line you quote; mention UTD as the modern rival." },
    ],
  },
  {
    id: "renal-vascular-anatomy",
    topicId: "renal-anatomy",
    title: "Renal vascular supply, anomalies and surgical importance",
    highYield: true,
    gold: true,
    tags: ["artery", "vein", "accessory", "PCNL", "donor", "PN"],
    exams: [
      {
        session: "Jun",
        year: 2021,
        marks: "3+3+4",
        stem: "Discuss the vascular supply of the kidney. Define its common anomalies. Define its importance with reference to various urological surgeries.",
      },
    ],
    related: ["left-renal-vein", "pcnl-anatomy-access", "partial-nephrectomy-nss", "kidney-anomalies-endourology"],
    references: [
      "Campbell-Walsh-Wein — Anatomy of the Upper Urinary Tract",
      "Graves FT. The anatomy of the intrarenal arteries. Br J Surg 1954",
      "Sampaio FJB. Vascular anatomy for PCNL / endourology",
      "EAU Renal transplantation / RCC surgery chapters",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Normal arterial + venous 3 · Anomalies table 3 · Surgery: PN, RN, donor, PCNL, pyeloplasty, transplant 4. Draw Graves’ five segments and Brodel’s line." },
      { t: "h", v: "Normal arterial supply" },
      { t: "ul", v: [
        "Paired renal arteries from aorta at L1–2, just below SMA. Right artery longer, passes behind IVC. Both pass behind the renal vein.",
        "Main artery divides at hilum into anterior (larger) and posterior divisions. Segmental arteries are end-arteries (Graves 1954): apical, anterior-superior, anterior-inferior, inferior (from anterior division) and posterior (from posterior division, often a single retropelvic branch).",
        "Segmental → interlobar (in sinus, along infundibula) → arcuate (corticomedullary) → interlobular → afferent arteriole → glomerulus → efferent → peritubular capillaries / vasa recta.",
        "Brodel’s avascular line: between anterior and posterior segmental trees, just posterior to the lateral convex border — the PCNL / anatrophic plane.",
        "Ureteric blood supply: upper third from renal artery, middle from gonadal/aorta/iliac, lower from superior vesical / uterine / vaginal — always anastomosing on the adventitia; preserve periureteric tissue in transplant and pyeloplasty.",
      ]},
      { t: "h", v: "Normal venous drainage" },
      { t: "ul", v: [
        "Stellate → interlobular → arcuate → interlobar → segmental veins, which unlike arteries freely anastomose (so venous ligation is more forgiving than arterial).",
        "Right renal vein: short (2–4 cm), no tributaries usually, directly to IVC.",
        "Left renal vein: long (6–10 cm), crosses anterior to aorta below SMA (nutcracker interval), receives adrenal, gonadal and lumbar/ascending lumbar (hemi-azygos) tributaries. This is why left donor nephrectomy is preferred and why left RN needs tributary control.",
      ]},
      { t: "h", v: "Common anomalies" },
      { t: "tbl", h: ["Anomaly", "Frequency / anatomy", "Surgical trap"], r: [
        ["Accessory / aberrant arteries", "25–30% (higher in horseshoe/ectopia). Accessory = extra hilar; aberrant = polar, often lower pole from aorta/iliac", "Lower-pole crossing vessel at PUJ; missed polar artery in donor/RN → bleeding or polar infarct; multiple arterial anastomoses in transplant"],
        ["Early branching", "First branch <1.5–2 cm from ostium", "Precludes a single stapler load in lap RN / donor; needs selective PN clamps"],
        ["Precaval right renal artery", "Artery anterior to IVC (rare)", "IVC dissection danger"],
        ["Multiple right veins / delayed confluence", "10–20%", "Stapler on right RN may leave a posterior vein; donor right vein already short"],
        ["Circumaortic left renal vein", "5–7%: preaortic + retroaortic limbs", "Leave the retroaortic limb; injury = retroperitoneal haemorrhage. Retroaortic-only vein 2–3% — sits in the aortic interspace, easily torn."],
        ["Retroaortic left renal vein", "2–3%", "Nutcracker-like; torn during LN dissection / left RN"],
        ["Nutcracker", "LRV compressed between SMA and aorta", "Haematuria, left varicocele; rare stent/transposition"],
        ["Arteriovenous fistula / malformation", "Congenital or post-biopsy/PCNL", "Embolize; high-output failure if large"],
      ]},
      { t: "h", v: "Importance by operation" },
      { t: "tbl", h: ["Operation", "Vascular point"], r: [
        ["Radical nephrectomy", "Artery first (prevents tumour engorgement). Left: gonadal, adrenal, lumbar veins. Circumaortic vein: control both limbs. Early branching: dissect into hilum before stapler."],
        ["Partial nephrectomy", "Selective segmental clamp (zero-ischaemia / early unclamping) needs 3-D CT arterial map. Polar accessory can be sacrificed only if the tumour is in that segment."],
        ["Donor nephrectomy", "Left preferred (long vein). Multiple arteries: reconstruct on bench (side-to-side pair, or separate implant). Early branch may force right-sided harvest. Preserve adrenal artery if taking left, or ligate cleanly."],
        ["Transplant implant", "End-to-side to external iliac; multiple arteries to separate punch holes or as a Carrel patch (deceased donor). Polar artery to lower pole also supplies ureter — losing it = distal ureteric necrosis."],
        ["PCNL", "Papillary puncture in Brodel plane. Posterior segmental artery hugs the posterior infundibulum — infundibular puncture → acute bleed or delayed pseudoaneurysm/AVF. Accessory lower-pole artery at risk with too-medial lower-pole tract."],
        ["Pyeloplasty", "Anterior crossing lower-pole vessel is translocated caudal to PUJ (vascular hitch / dismembered pyeloplasty anterior to vessel). Never cut a crossing artery."],
        ["IVC thrombectomy", "Lumbar veins, right gonadal, short hepatic veins; left renal vein tributaries if left tumour."],
        ["Embolization (trauma, AML, pre-op RN)", "Superselective from a segmental; coils/particles distal enough to spare parenchyma."],
      ]},
      { t: "tip", k: "gold", v: "Arteries are end-arteries; veins anastomose. 30% have an extra artery — it is usually the lower pole and it often feeds the ureter. Brodel is posterior-to-lateral; the posterior segmental artery is the PCNL bleeder." },
    ],
  },
  {
    id: "left-renal-vein",
    topicId: "renal-anatomy",
    title: "Left renal vein — embryology, anatomy and anomalies",
    highYield: true,
    gold: false,
    tags: ["vein", "circumaortic", "retroaortic", "nutcracker", "embryology"],
    exams: [
      {
        session: "Dec",
        year: 2016,
        marks: "3+4+3",
        stem: "Embryology, anatomy and anomalies of left renal vein.",
      },
    ],
    related: ["renal-vascular-anatomy", "ivc-thrombus", "lap-nephrectomy-complications"],
    references: [
      "Campbell-Walsh-Wein — Embryology of the IVC and renal veins",
      "Mathews R, Smith PA, Fishman EK, Marshall FF. Anomalies of the inferior vena cava and renal veins. J Urol",
      "Hinman Atlas — left radical nephrectomy",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Draw the three fetal venous systems (posterior cardinal, subcardinal, supracardinal) and the renal collar. Then adult LRV anatomy with three tributaries. Anomalies: circumaortic, retroaortic, duplication, nutcracker." },
      { t: "h", v: "Embryology (the renal collar)" },
      { t: "p", v: "The IVC and renal veins are remodelled from three paired veins (wk 6–8):" },
      { t: "ul", v: [
        "Posterior cardinal veins (dorsal, drain the body wall) — largely regress in the lumbar region.",
        "Subcardinal veins (ventromedial) — form the prerenal IVC (right subcardinal) and the gonadal/adrenal veins.",
        "Supracardinal veins (dorsomedial) — form the azygos / hemiazygos and the postrenal IVC (right supracardinal).",
      ]},
      { t: "p", v: "At the metanephric level the subcardinal and supracardinal veins interconnect ventral and dorsal to the aorta, forming a venous ring — the renal collar (circumaortic ring). Normally the ventral (preaortic, subcardinal) limb persists as the adult left renal vein and the dorsal (retroaortic, supracardinal) limb regresses. Persistence of both limbs = circumaortic LRV; persistence of only the dorsal limb = retroaortic LRV. The right renal vein is a short remnant of the right subcardinal–supracardinal anastomosis." },
      { t: "h", v: "Adult anatomy of the left renal vein" },
      { t: "ul", v: [
        "Length 6–10 cm (vs right 2–4 cm); diameter ~1.5–2 cm.",
        "Course: from left hilum, over the psoas, anterior to the aorta, immediately caudal to the SMA, into the IVC at L1–2. The SMA–aorta angle is the nutcracker interval.",
        "Tributaries (always list): left adrenal (superior), left gonadal (inferior), lumbar / ascending lumbar / hemiazygos (posterior). Occasional posterior lumbar is short and tears during retraction.",
        "Relations: pancreas and splenic vein anterior; aorta posterior; SMA superior. In nutcracker the vein is flattened, with distal hilar dilatation and left varicocele / haematuria.",
        "Surgical implication of length: left donor nephrectomy, splenorenal shunt, and (historically) left-to-right transposition.",
      ]},
      { t: "h", v: "Anomalies" },
      { t: "tbl", h: ["Anomaly", "Embryology", "Prevalence", "Surgical importance"], r: [
        ["Circumaortic LRV (persistence of collar)", "Preaortic + retroaortic limbs", "5–7%", "Two veins to ligate in left RN / donor. Retroaortic limb sits low (L3) and is easily missed; stapler on preaortic limb alone → haemorrhage. Retroaortic limb also at risk in aortic surgery and RPLND."],
        ["Retroaortic LRV (Type I or II)", "Dorsal limb only. Type I at L1–2; Type II caudal at L4–5 joining IVC/iliac", "2–3%", "Vein is posterior to aorta — torn by aortic cross-clamp, left RN, or lumbar dissection. May present as nutcracker."],
        ["Duplicated LRV (two preaortic)", "Incomplete coalescence", "Rare", "Both must be controlled"],
        ["Nutcracker syndrome", "Haemodynamic, not a true malformation; tight SMA–aortic angle / behind SMA", "Uncommon clinically", "Left flank pain, haematuria, varicocele, pelvic congestion. Diagnose on CTA/MRV + pressure gradient >3 mmHg. Treat conservatively first; stent or LRV transposition / autotransplant if refractory."],
        ["LRV draining to azygos / hemiazygos (with IVC interruption)", "Failed right subcardinal IVC; azygos continuation", "Rare; associated left IVC", "Transplant and IVC thrombus surgery become atypical"],
      ]},
      { t: "tip", k: "gold", v: "The fetal left renal vein is a collar around the aorta. Keep the ventral limb, lose the dorsal limb. If you keep both, you have a circumaortic vein — the posterior limb is the one that bleeds in left nephrectomy." },
    ],
  },
];
