import type { Master } from "../types";

export const renalTumors: Master[] = [
  {
    id: "rcc-who-subtypes",
    topicId: "renal-tumors",
    title: "RCC histologic subtypes, WHO classification, prognosis and screening",
    highYield: true,
    gold: true,
    tags: ["WHO", "clear cell", "papillary", "chromophobe", "TNM"],
    exams: [
      { session: "Dec", year: 2017, marks: "6+4", stem: "What are the pathological sub-types of renal cell carcinoma? What is their prognostic implication?" },
      {
        session: "June",
        year: 2022,
        marks: "4+3+3",
        stem: "Enumerate different histologic types of renal tumors with key features. Describe in brief the various associated familial syndromes. Discuss the cause and management of hypercalcemia in metastatic RCC.",
      },
      {
        session: "Jun",
        year: 2021,
        marks: "3+3+4",
        stem: "What are the histologic types of renal tumors? What is the mechanism of action of immune check point inhibitors? What is their status in the current treatment guidelines in renal tumors?",
      },
      { session: "Dec", year: 2012, marks: "6+4", stem: "Describe the pathological variants of renal cell carcinoma and their importance in deciding management of advanced malignancy." },
      { session: "Dec", year: 2013, marks: "5+5", stem: "Describe recent changes in histopathological classification and TNM staging in renal cell carcinoma (RCC)." },
      { session: "Dec", year: 2020, marks: "5+5", stem: "Describe the common histologic subtypes of renal cell carcinoma. What are the target populations where screening for renal cell carcinoma is indicated?" },
    ],
    related: ["rcc-tnm", "rcc-familial-vhl", "immune-checkpoint-rcc", "mtor-vegf-tki", "rcc-prognostic-markers"],
    references: [
      "WHO Classification of Urinary and Male Genital Tumours, 5th ed. 2022",
      "AJCC TNM 8th ed. / UICC",
      "EAU RCC guidelines",
      "Campbell-Walsh-Wein — Malignant renal tumors",
      "ISUP / WHO nucleolar grade (replaces Fuhrman)",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "WHO table with genetics, IHC, prognosis 6 · Familial list (pointer to VHL master) 1 · HyperCa 2 · Screening populations 1. Mention ISUP nucleolar grade and TNM 8 in the 2013 ‘recent changes’ stem." },
      { t: "h", v: "WHO 2022 adult renal epithelial tumours — the exam table" },
      { t: "tbl", h: ["Subtype", "~% / genetics", "Key morphology / IHC", "Prognosis / systemic implication"], r: [
        ["Clear-cell RCC", "75–80%. VHL 3p25 inactivation ± 3p21 (PBRM1, SETD2, BAP1). HIF–VEGF addicted", "Clear cytoplasm, delicate vasculature. CAIX diffuse box-like, CD10, vimentin. ISUP grade 1–4", "Most VEGF/IO-responsive. BAP1 / sarcomatoid worse. Backbone of IMDC trials"],
        ["Papillary RCC (WHO 2022: no longer rigidly type 1 vs 2; molecular groups)", "15%. MET 7q (PRCC1); type 2 historically FH, NRF2", "Papillae, foamy macrophages. AMACR+, CK7+ (esp. PRCC1). CAIX patchy", "PRCC1 indolent; FH-deficient aggressive (HLRCC). MET inhibitors investigational; IO/VEGF less predictable than ccRCC"],
        ["Chromophobe RCC", "5%. Multiple chromosomal losses; FLCN in Birt–Hogg–Dubé", "Plant-leaf raisin nuclei, pale cytoplasm, prominent membranes. CK7 diffuse, CD117+, Hale colloidal iron+", "Indolent; sarcomatoid transformation is the killer. Less VEGF-responsive; consider IO or chemo if sarcomatoid"],
        ["Oncocytoma (benign)", "5–7% of renal masses. Also FLCN", "Nested oncocytic cells, central scar. CD117+, CK7 focal. Need to distinguish from chromophobe", "Benign — see oncocytoma master"],
        ["Clear-cell papillary renal cell tumour (indolent)", "CK7+, CAIX cup-like (not box), high-molecular-weight CK", "WHO 2022 dropped ‘carcinoma’ — indolent", "Treat as very low risk"],
        ["Collecting-duct (Bellini) / SMARCB1-deficient medullary", "Rare. Sickle-cell trait for medullary", "Infiltrative, high-grade, central", "Dismal; platinum-gemcitabine / IO, not TKI first"],
        ["FH-deficient (HLRCC) RCC", "FH germline", "Large nucleoli with perinucleolar halo; 2SC+", "Aggressive; bevacizumab+erlotinib is a cited combination; mandatory family genetics"],
        ["SDH-deficient RCC", "SDHB/C/A germline", "Eosinophilic, cytoplasmic vacuoles, SDHB IHC loss", "Paraganglioma syndrome; avoid VEGF? data scarce"],
        ["TFE3 / TFEB / MITF translocation RCC", "Xp11.2 TFE3 (young, chemo history)", "PSF-TFE3; melanocytic markers sometimes", "Variable; children may do well; adults worse. IO emerging"],
        ["Mucinous tubular & spindle, tubulocystic, acquired-cystic disease RCC, eosinophilic solid & cystic (TSC), thyroid-like, ALK-rearranged, ELOC (TCEB1)", "Each rare", "WHO 2022 named entities", "Most indolent except some ALK / ESC in TSC"],
        ["Multilocular cystic renal neoplasm of LMP", "VHL-related architecture", "Cystic, low-grade clear cells in septa, no nodule", "Nephrectomy is overtreatment if recognised — PN / observe"],
        ["Sarcomatoid / rhabdoid change", "A phenotype, not a subtype — can overlay any", "ISUP 4", "IO (CheckMate 214 / 9ER) — not sunitinib alone"],
        ["Wilms, CCSK, mesoblastic, rhabdoid, lymphoma, sarcoma, mets", "Paediatric / other", "—", "Not adult RCC protocols"],
      ]},
      { t: "h", v: "Prognostic implication of subtype (Dec 17 / Dec 12)" },
      { t: "ul", v: [
        "Stage-for-stage, chromophobe and PRCC1 better than clear-cell; collecting-duct, medullary, FH-deficient, sarcomatoid worst.",
        "Systemic therapy: clear-cell = VEGF + PD-1 backbone. Non-clear: no single standard — cabozantinib, IO combinations, sunitinib; collecting-duct ~ urothelial platinum. Do not copy-paste CheckMate 214 onto medullary RCC.",
        "ISUP nucleolar grade (2012/WHO) replaced Fuhrman: grade 1–3 by nucleolar prominence, grade 4 = sarcomatoid/rhabdoid or anaplasia. Applies to clear-cell and papillary, not chromophobe (use two-tier if at all).",
        "Necrosis, microvascular invasion, sinus invasion, unfavourable subtypes all feed SSIGN / Leibovich / UISS scores.",
      ]},
      { t: "h", v: "‘Recent changes’ in classification and TNM (Dec 13 stem — bring forward to 2022)" },
      { t: "ul", v: [
        "WHO 2004 → 2016 → 2022: translocation RCC recognised; hybrid oncocytic in BHD; clear-cell papillary now a ‘tumour’ not carcinoma; papillary type 1/2 dropped as mandatory; new molecular entities (ELOC, ALK, SDH, FH, ESC).",
        "Fuhrman → ISUP/WHO nucleolar grade.",
        "TNM 7 (2009) → TNM 8 (2017): T1a ≤4 cm, T1b >4–7, T2a >7–10, T2b >10; T3a = fat or renal vein or pelvicalyceal system invasion (pelvicalyceal added); T3b = IVC below diaphragm; T3c = IVC above diaphragm or invasion of IVC wall; T4 = beyond Gerota or into ipsilateral adrenal by contiguity (adrenal mets are M1, not T). N1 = regional nodes (N2 dropped). M1 distant.",
      ]},
      { t: "h", v: "Familial syndromes (brief — full VHL/TSC masters exist)" },
      { t: "ul", v: ["VHL — ccRCC", "BHD (FLCN) — hybrid oncocytic, chromophobe", "HLRCC (FH) — aggressive PRCC-like", "HPRC (MET) — bilateral type-1 papillary", "TSC1/2 — AML ± ESC RCC", "SDH — SDH-deficient RCC + pheo", "Cowden (PTEN) — papillary", "Lynch — UTUC not RCC"], },
      { t: "h", v: "Hypercalcaemia in metastatic RCC (June 22)" },
      { t: "ul", v: [
        "Causes: PTHrP (true paraneoplastic, osteolytic-factor independent) > osteolytic bone mets > ectopic 1,25-D (rare) > immobilisation. PTHrP mimics PTH but PTH is low and PTHrP high.",
        "Clinical: bones, stones, groans, psychic overtones, short QT, polyuria (see basics hypercalcaemia).",
        "Management: fluids 3–4 L NS, then loop diuretic only if overloaded; IV bisphosphonate (zoledronate 4 mg) or denosumab if Cr high; calcitonin for 48 h bridge; steroids if 1,25-D; dialysis if refractory in CKD. Systemic Rx of the RCC (IO/TKI) is definitive. Cinacalcet not first-line here.",
      ]},
      { t: "h", v: "Screening populations (Dec 20) — there is no population screening" },
      { t: "ul", v: [
        "VHL, HPRC, BHD, HLRCC, TSC, SDH — protocolised MRI (not CT in the young) from the syndrome-specific age (VHL often from 15–18 y).",
        "ESRD / acquired cystic disease (especially >3 y dialysis) — annual US/MRI; transplant wait-list.",
        "Strong family history of RCC even without a named syndrome.",
        "Prior childhood irradiation, tuberous sclerosis, unexplained polycythaemia / Birt–Hogg skin findings.",
        "NOT smokers/obese as a mass-screening programme — incidental imaging is how most RCC is found.",
      ]},
      { t: "tip", k: "gold", v: "Clear-cell = VHL/VEGF/IO. Chromophobe and PRCC1 live longer. Collecting-duct and FH-deficient die faster and do not behave like sunitinib-era ccRCC. Grade is ISUP now. Screen syndromes and acquired cystic kidneys, not the nation." },
    ],
  },
  {
    id: "rcc-tnm",
    topicId: "renal-tumors",
    title: "TNM classification of RCC",
    highYield: true,
    gold: false,
    tags: ["TNM", "AJCC", "stage"],
    exams: [
      { session: "Dec", year: 2019, marks: "5+5", stem: "Write TNM classification of renal cell carcinoma. Write management of tumour thrombus in inferior vena cava at and above the level of hepatic veins." },
      { session: "Dec", year: 2013, marks: "5+5", stem: "Describe recent changes in histopathological classification and TNM staging in renal cell carcinoma (RCC)." },
    ],
    related: ["ivc-thrombus", "rcc-who-subtypes", "rcc-prognostic-markers"],
    references: ["AJCC 8th edition", "EAU RCC", "WHO GU 2022"],
    answer: [
      { t: "tbl", c: "AJCC / UICC 8th ed. (2017)", h: ["T", "Definition"], r: [
        ["Tx / T0", "Cannot assess / no primary"],
        ["T1a", "≤4 cm, limited to kidney"],
        ["T1b", ">4 cm and ≤7 cm, limited to kidney"],
        ["T2a", ">7 and ≤10 cm, limited to kidney"],
        ["T2b", ">10 cm, limited to kidney"],
        ["T3a", "Renal vein (including segmental muscle-containing branches) OR pelvicalyceal system OR perirenal / renal-sinus fat — but not beyond Gerota. Contiguous adrenal is T4, not T3a"],
        ["T3b", "IVC below diaphragm"],
        ["T3c", "IVC above diaphragm OR invasion of IVC wall"],
        ["T4", "Beyond Gerota OR contiguous invasion of ipsilateral adrenal"],
      ]},
      { t: "tbl", h: ["N / M", "Definition"], r: [
        ["N0", "No regional nodes"],
        ["N1", "Regional (hilar, para-aortic, paracaval, interaortocaval). N2 abolished"],
        ["M0 / M1", "No distant / distant including non-contiguous adrenal"],
      ]},
      { t: "tbl", h: ["Stage", "Grouping"], r: [
        ["I", "T1 N0 M0"],
        ["II", "T2 N0 M0"],
        ["III", "T3 any N, or T1–2 N1, M0"],
        ["IV", "T4 or M1"],
      ]},
      { t: "p", v: "IVC thrombus management is in the IVC master — T3c (hepatic veins / supra-diaphragmatic) needs liver mobilisation ± bypass, not a simple RN." },
      { t: "tip", k: "gold", v: "Sinus fat and renal-vein muscle-branch = T3a. Above diaphragm or wall invasion = T3c. Adrenal skip mets = M1." },
    ],
  },
  {
    id: "rcc-familial-vhl",
    topicId: "renal-tumors",
    title: "Familial renal tumours and von Hippel–Lindau disease",
    highYield: true,
    gold: true,
    tags: ["VHL", "3p25", "HIF", "belzutifan", "3 cm rule"],
    exams: [
      { session: "Jun", year: 2021, marks: "3+3+4", stem: "What are the hereditary/familial syndromes associated with renal tumours? Briefly describe features of von-Hippel Lindau disease. What are the principles of management of this disease?" },
      { session: "Dec", year: 2021, marks: "4+6", stem: "Discuss the role of von Hippel-Lindau (VHL) gene in renal cell carcinoma and management of renal cell carcinoma in von Hippel-Lindau disease." },
      { session: "June", year: 2022, marks: "5+5", stem: "Classify Von Hippel-Lindau disease, its malignant potential and list its extra-renal manifestations. Discuss management of RCC in VHL patients." },
    ],
    related: ["rcc-who-subtypes", "tsc-aml", "srm-management", "mtor-vegf-tki"],
    references: [
      "Campbell — Familial RCC / VHL",
      "EAU RCC — hereditary",
      "Lonser / Nielsen VHL reviews",
      "Belzutifan LITESPARK (NEJM)",
    ],
    answer: [
      { t: "h", v: "Familial renal-tumour syndromes" },
      { t: "tbl", h: ["Syndrome", "Gene", "Renal lesion", "Extra-renal"], r: [
        ["von Hippel–Lindau", "VHL 3p25", "ccRCC, cysts (multiple, bilateral, early)", "See below"],
        ["Birt–Hogg–Dubé", "FLCN 17p", "Hybrid oncocytic, chromophobe, oncocytoma", "Fibrofolliculomas, lung cysts, pneumothorax"],
        ["HPRC", "MET 7q proto-oncogene", "Bilateral type-1 papillary", "Almost kidney-only"],
        ["HLRCC (Reed)", "FH 1q", "Aggressive FH-deficient RCC, often solitary", "Cutaneous/uterine leiomyoma; high-grade RCC — operate early, do not observe 3 cm"],
        ["Tuberous sclerosis", "TSC1/9q, TSC2/16p", "AML, cysts, ESC RCC", "See TSC master"],
        ["SDH-related PGL/PCC", "SDHB > A/C/D", "SDH-deficient RCC", "Pheo/PGL, GIST"],
        ["Cowden", "PTEN", "Papillary RCC", "Breast/thyroid, hamartomas"],
        ["Hyperparathyroidism-jaw tumour", "CDC73 (parafibromin)", "Mixed, Wilms rare", "Fibromas, parathyroid carcinoma"],
      ]},
      { t: "h", v: "VHL gene in RCC" },
      { t: "ul", v: [
        "VHL protein is the substrate-recognition component of an E3 ubiquitin ligase that hydroxylates HIF-1α/HIF-2α (via PHDs in normoxia) and sends them to the proteasome.",
        "Biallelic VHL loss (germline + second hit in VHL disease; somatic in ~90% of sporadic ccRCC) → HIF-2α accumulates → VEGF, PDGF, TGF-α, EPO, GLUT1 → angiogenesis, proliferation, polycythaemia. This is why VEGF-TKIs and HIF-2α inhibitors (belzutifan) work.",
        "Co-drivers on 3p: PBRM1, SETD2, BAP1 (BAP1 worst).",
      ]},
      { t: "h", v: "Classification of VHL (clinical)" },
      { t: "tbl", h: ["Type", "Pheo", "RCC", "Other"], r: [
        ["1", "No (truncating mutations)", "High", "CNS/retinal haemangioblastoma, pancreatic cysts"],
        ["2A", "Yes (missense)", "Low", "HB + pheo"],
        ["2B", "Yes", "High", "HB + pheo + RCC"],
        ["2C", "Yes", "None", "Pheo only"],
      ]},
      { t: "h", v: "Extra-renal manifestations (list)" },
      { t: "ul", v: [
        "CNS haemangioblastoma (cerebellum, spine) — leading cause of death historically.",
        "Retinal angioma — vision; start screening in childhood.",
        "Phaeochromocytoma / paraganglioma (type 2) — always screen before elective surgery (anaesthetic disaster).",
        "Pancreatic cysts, serous cystadenoma, neuroendocrine tumours.",
        "Epididymal cystadenoma (bilateral → infertility), broad-ligament cysts.",
        "Endolymphatic sac tumour (ELSTs) — hearing, tinnitus.",
        "Renal and pancreatic cysts; simple skin lesions uncommon unlike BHD.",
      ]},
      { t: "h", v: "Principles of VHL management and of RCC in VHL" },
      { t: "ul", v: [
        "Lifelong multidisciplinary surveillance (VHL Alliance protocol): MRI brain/spine, retinal, plasma/urine metanephrines, MRI abdomen (NOT serial CT in the young).",
        "Renal: 3 cm rule — observe solid ccRCC until the largest lesion is ~3 cm, then nephron-sparing surgery (or ablation) aiming to resect/ablate all treatable lesions at that sitting. This balances metastatic risk (very low <3 cm in VHL) against the certainty of future tumours and eventual ESRD.",
        "Enucleation along the pseudocapsule is acceptable in VHL (unlike sporadic high-grade). Repeat PN / ablation as new lesions declare. RN only if the kidney is unreconstructable.",
        "HLRCC is the exception: do not apply the 3 cm rule — wide PN/RN promptly.",
        "Systemic: belzutifan (HIF-2α inhibitor) shrinks VHL-associated RCC, HB and pNET (FDA approved) — a game-changer for the unresectable / high-burden kidney. VEGF-TKIs if metastatic. Avoid sunitinib neoadjuvant as a routine (see preservation master).",
        "Never operate on a VHL patient without a recent pheo screen. Genetic cascade family testing.",
      ]},
      { t: "tip", k: "gold", v: "VHL = HIF-2α unleashed. 3 cm rule + repeated NSS + belzutifan. Type 2 has pheo; type 1 has RCC. HLRCC does not get the 3 cm courtesy." },
    ],
  },
  {
    id: "tsc-aml",
    topicId: "renal-tumors",
    title: "Tuberous sclerosis and angiomyolipoma",
    highYield: true,
    gold: true,
    tags: ["TSC", "AML", "mTOR", "everolimus", "Wunderlich"],
    exams: [
      {
        session: "Jun",
        year: 2021,
        marks: "3+3+4",
        stem: "What are the components of tuberous sclerosis syndrome? Discuss its importance for Urologists. Discuss management options for AML.",
      },
    ],
    related: ["rcc-familial-vhl", "mtor-vegf-tki", "renal-trauma-imaging-embolization"],
    references: [
      "International TSC Consensus 2012/2021",
      "EAU RCC — AML",
      "EXIST-2 everolimus for AML",
      "Campbell — Benign renal tumors",
    ],
    answer: [
      { t: "h", v: "TSC components (major / minor — quote a working set)" },
      { t: "p", v: "TSC1 (hamartin) / TSC2 (tuberin) inhibit mTORC1. Loss → mTOR hyperactivation (hence everolimus)." },
      { t: "tbl", h: ["Major", "Minor"], r: [
        ["≥3 hypomelanotic macules, angiofibromas, ungual fibromas, shagreen, multiple retinal hamartomas, cortical dysplasias, subependymal nodules, SEGA, cardiac rhabdomyoma, LAM, ≥2 AML", "Confetti skin, dental pits, intra-oral fibromas, retinal achromic patch, multiple renal cysts, non-renal hamartomas"],
      ]},
      { t: "p", v: "Definite TSC: 2 major, or 1 major + 2 minor, or a pathogenic TSC1/2 variant." },
      { t: "h", v: "Why the urologist cares" },
      { t: "ul", v: [
        "AML (bilateral, multiple, fat-rich or fat-poor) — haemorrhage (Wunderlich), pain, CKD from replacement of parenchyma / embolization / PN.",
        "Renal cysts; TSC2/PKD1 contiguous-gene deletion (16p13) → early cystic kidneys like ADPKD.",
        "RCC (including eosinophilic solid and cystic) — uncommon but real; fat-poor AML is the differential.",
        "mTOR drugs (everolimus) shrink AML and SEGA; they also impair wound healing and confer infection risk peri-op.",
        "LAM in women — pneumothorax, chylous ascites; oestrogen caution.",
        "Peri-operative: epilepsy drugs, behavioural issues, SEGA, cardiac rhabdomyoma in children.",
      ]},
      { t: "h", v: "AML management" },
      { t: "ul", v: [
        "Diagnosis: macroscopic fat on CT (−20 HU) without calcification is AML until proven otherwise. Fat-poor AML: MRI (India-ink, T2), biopsy if it would change care.",
        "Sporadic AML: observe if <4 cm and asymptomatic (size is a blunt tool — aneurysm >5 mm on CTA is a better bleed predictor). Offer treatment if 4–6 cm and growing, symptoms, childbearing age (rupture risk in pregnancy), or aneurysm >5 mm.",
        "Treatment options: (1) superselective embolization — first-line for haemorrhage and for elective volume reduction; post-embolization syndrome expected; may need repeat. (2) NSS / robotic PN / off-clamp for polar lesions, diagnostic uncertainty, failed embolization. (3) RN if shattered Wunderlich kidney. (4) Ablation for small fat-poor lesions. (5) Everolimus 10 mg (EXIST-2) for TSC-AML not requiring immediate surgery — 50% volume reduction; rebound on stopping. Sirolimus in LAM. (6) Avoid biopsy of typical fat-rich AML.",
        "Epithelioid AML: potentially malignant — surgical oncology rules, not observation.",
        "Acute Wunderlich: resuscitate, embolize, nephrectomy only if unstable and IR unavailable.",
      ]},
      { t: "tip", k: "gold", v: "TSC = mTOR on. AML: embolize bleeders, everolimus the TSC burden, operate when fat-poor or epithelioid or IR has failed. 4 cm is a tradition; aneurysm diameter is the better crystal ball." },
    ],
  },
  {
    id: "immune-checkpoint-rcc",
    topicId: "renal-tumors",
    title: "Checkpoint inhibitors and immunotherapy in RCC",
    highYield: true,
    gold: true,
    tags: ["PD-1", "CTLA-4", "nivo-ipi", "pembrolizumab", "IO"],
    exams: [
      {
        session: "Jun",
        year: 2021,
        marks: "3+3+4",
        stem: "What are the histologic types of renal tumors? What is the mechanism of action of immune check point inhibitors? What is their status in the current treatment guidelines in renal tumors?",
      },
      { session: "Jun", year: 2016, marks: "3+7", stem: "What are checkpoint inhibitors? Current status of Immunotherapy in renal cell carcinoma." },
    ],
    related: ["rcc-who-subtypes", "mtor-vegf-tki", "rcc-prognostic-markers"],
    references: [
      "CheckMate 214, KEYNOTE-426, CheckMate 9ER, CLEAR, COSMIC-313",
      "KEYNOTE-564 adjuvant pembrolizumab",
      "EAU / ESMO RCC 2024–2025",
      "Campbell — Systemic therapy of RCC",
    ],
    answer: [
      { t: "h", v: "What are checkpoint inhibitors?" },
      { t: "p", v: "Monoclonal antibodies that block inhibitory immune checkpoints, releasing tumour-reactive T cells. RCC is an immunogenic tumour (historically high-dose IL-2 / IFN-α produced durable remissions in a minority)." },
      { t: "tbl", h: ["Checkpoint", "Drug examples", "Physiology"], r: [
        ["CTLA-4 vs CD80/86 on APC (priming in node)", "Ipilimumab, tremelimumab", "Dampens priming; block → more effector T cells, more irAE"],
        ["PD-1 on T cell vs PD-L1/L2 on tumour / myeloid cells (peripheral)", "Nivolumab, pembrolizumab, cemiplimab", "Exhaustion reversal"],
        ["PD-L1", "Atezolizumab, avelumab, durvalumab", "Same axis from the tumour side"],
      ]},
      { t: "p", v: "Mechanism in one line: TCR sees antigen on MHC; CD28 co-stimulates; CTLA-4 and PD-1 put the brakes on. Antibodies take the brakes off. irAEs (colitis, hepatitis, hypophysitis, thyroid, pneumonitis, rash, adrenal) are the on-target cost — treat with holding the drug ± steroids, never infliximab for hepatitis." },
      { t: "h", v: "Current guideline status (ccRCC, IMDC)" },
      { t: "tbl", h: ["Setting", "Preferred (EAU/ESMO pattern)", "Evidence"], r: [
        ["mRCC first-line, IMDC intermediate/poor", "Nivo + ipi (CheckMate 214 — CR rate, durable OS) OR PD-1 + VEGF (pembro + axitinib KN-426; nivo + cabo 9ER; pembro + lenvatinib CLEAR)", "IO/IO for potential cure/durable CR; IO/TKI for high-volume, need for early ORR"],
        ["mRCC first-line, IMDC favourable", "IO/TKI or TKI monotherapy (pazopanib/sunitinib) if IO contraindicated; nivo-ipi less compelling in favourable-risk", "Favourable-risk still VEGF-sensitive"],
        ["Post-VEGF, IO-naive", "Nivolumab (CheckMate 025) or cabozantinib (METEOR) or lenvatinib + everolimus", "Historical"],
        ["Adjuvant, high-risk post-nephrectomy (pT2 high-grade / pT3–4 / N+ / completely resected M1)", "Pembrolizumab 1 y (KEYNOTE-564 DFS and OS benefit)", "IMmotion010 atezo negative; CheckMate 914 nivo-ipi mixed — pembro is the one to quote"],
        ["Sarcomatoid", "IO-containing combination mandatory", "Sunitinib era is over"],
        ["Non-clear", "No IO label as strong; still used. Cabozantinib, sunitinib, or trial. Collecting-duct: platinum"],
      ]},
      { t: "p", v: "PD-L1 IHC is NOT used to withhold IO in RCC (unlike some lung algorithms). Cytoreductive nephrectomy is no longer automatic (CARMENA) — offer after IO/TKI in responding IMDC intermediate patients selected by SURTIME logic, not up front in poor-risk." },
      { t: "tip", k: "gold", v: "PD-1 and CTLA-4 are the brakes. First-line metastatic ccRCC is IO-based in 2024. Adjuvant = pembrolizumab for KEYNOTE-564 risk. Quote 214, 426, 9ER, 564." },
    ],
  },
  {
    id: "renal-mass-biopsy",
    topicId: "renal-tumors",
    title: "Renal-mass biopsy — indications, technique, sensitivity, specificity",
    highYield: true,
    gold: false,
    tags: ["biopsy", "SRM", "sensitivity", "FNA"],
    exams: [
      { session: "Jun", year: 2017, marks: "4+3+3", stem: "Fine needle biopsy in renal tumors: Indications, technique and complications." },
      {
        session: "Jun",
        year: 2016,
        marks: "3+3+4",
        stem: "What are the indications of biopsy of renal mass? What is the sensitivity and specificity of a renal mass biopsy? What do the terms specificity and sensitivity mean?",
      },
    ],
    related: ["srm-management", "benign-renal-tumors-oncocytoma", "thermal-ablation-rcc"],
    references: ["EAU RCC — biopsy", "Campbell — Diagnosis of renal mass", "Richard / Jewett biopsy series (PMH)"],
    answer: [
      { t: "h", v: "Sensitivity and specificity (the 4-mark definition)" },
      { t: "ul", v: [
        "Sensitivity = TP / (TP + FN) = proportion of patients with disease whom the test correctly identifies. ‘Will the biopsy catch the cancers?’",
        "Specificity = TN / (TN + FP) = proportion of patients without disease whom the test correctly calls negative. ‘Will the biopsy wrongly call a benign mass cancer?’",
        "NPV/PPV depend on prevalence (SRM clinic vs metastatic work-up).",
      ]},
      { t: "h", v: "Performance of contemporary renal-mass biopsy" },
      { t: "ul", v: [
        "Core biopsy (18G, 2–4 cores, coaxial): diagnostic yield ~90%; sensitivity for malignancy 95–99%; specificity ~98–100% in modern series. Nondiagnostic 5–15% (cystic, necrotic, size <2 cm) — repeat biopsy often succeeds.",
        "FNA cytology alone: lower yield, poor grade/subtype; do not use FNA alone for SRM.",
        "Grade: under-graded vs nephrectomy in 50% of ISUP 1–2 — do not let a low-grade biopsy forbid treatment if imaging is aggressive.",
        "Oncocytoma vs chromophobe remains the IHC battleground (CK7, CD117, oncocytic hybrid).",
      ]},
      { t: "h", v: "Indications" },
      { t: "ul", v: [
        "Before ablation or active surveillance when histology would change the plan.",
        "Small enhancing mass in a comorbid / solitary-kidney / bilateral / familial setting.",
        "Unresectable / metastatic mass before systemic therapy (must prove RCC, subtype).",
        "Suspected lymphoma, abscess, TB, infarct, or metastasis from another primary (history of extra-renal cancer).",
        "Indeterminate Bosniak III in a frail patient.",
        "NOT routinely required before PN in a healthy patient with a typical enhancing solid mass (EAU: optional). NOT in a typical fat-rich AML. Avoid if it would not change surgery (e.g. young healthy T2 mass destined for RN/PN anyway) or if a cystic Bosniak IV is already a surgical disease.",
      ]},
      { t: "h", v: "Technique and complications" },
      { t: "ul", v: [
        "CT- or US-guided, coaxial 17G cannula, 18G cores from the solid enhancing component, avoid necrosis. Coaxial reduces tract seeding (now extremely rare with cores).",
        "Complications: haematoma / haematuria (common, self-limited), clinically significant bleed 1–2% (embolize if needed), A-V fistula, needle-tract seeding (historical with FNA of TCC — another reason to beware urothelial tumours), pneumothorax (upper pole), needle-site infection, needle-induced upstaging theoretically negligible, non-diagnostic sample.",
      ]},
      { t: "tip", k: "gold", v: "Sensitivity = catch disease; specificity = don’t invent it. 18G coaxial cores, yield 90%+, seed almost never. Biopsy to change a decision (AS, ablation, systemic, lymphoma), not as a ritual before every PN." },
    ],
  },
  {
    id: "nephrometry-scores",
    topicId: "renal-tumors",
    title: "Nephrometry scores — RENAL, PADUA and friends",
    highYield: true,
    gold: true,
    tags: ["RENAL", "PADUA", "C-index", "PN"],
    exams: [
      { session: "Jun", year: 2019, marks: "3+3+4", stem: "Discuss nephrometry score. Describe indications and principles of partial nephrectomy for renal cell carcinoma." },
      { session: "Dec", year: 2017, marks: "4+6", stem: "What are the various nephrometry scoring system for partial nephrectomy? Discuss RENAL nephrometry scoring system." },
      { session: "Dec", year: 2013, marks: "10", stem: "Describe 2 commonly used nephrometry scores for partial nephrectomy and its advantages." },
    ],
    related: ["partial-nephrectomy-nss", "srm-management", "pn-complications"],
    references: [
      "Kutikov & Uzzo. RENAL nephrometry. J Urol 2009",
      "Ficarra et al. PADUA. Eur Urol 2009",
      "Simmons C-index; DAP; Contact Surface Area; ABC",
      "EAU RCC",
    ],
    answer: [
      { t: "p", v: "Nephrometry = standardised CT/MRI scoring of tumour anatomy to predict PN complexity, ischaemia time, complications, and to communicate in MDT / papers. It does not replace judgement (comorbidity, solitary kidney, surgeon)." },
      { t: "h", v: "RENAL (Kutikov–Uzzo 2009) — the one to write in full" },
      { t: "tbl", c: "Each domain 1–3 points; suffix h if hilar", h: ["Letter", "1 pt", "2 pt", "3 pt"], r: [
        ["R — Radius (max diameter)", "≤4 cm", ">4 and <7 cm", "≥7 cm"],
        ["E — Exophytic/endophytic", "≥50% exophytic", "<50% exophytic", "Entirely endophytic"],
        ["N — Nearness to sinus / collecting system", "≥7 mm", ">4 and <7 mm", "≤4 mm"],
        ["A — Anterior/posterior", "A or P or X (descriptor, not scored)"],
        ["L — Location relative to polar lines*", "Entirely above/below", "Crosses polar line", ">50% of mass across polar line or crosses axial midline or entirely between polar lines"],
      ]},
      { t: "p", v: "*Polar lines: axial planes at the medial lips of the upper and lower poles. Score 4–6 low, 7–9 moderate, 10–12 high complexity. Add ‘h’ if the tumour touches the main artery or vein." },
      { t: "h", v: "PADUA (Ficarra 2009) — the second commonly used" },
      { t: "ul", v: [
        "Domains (1–3): (1) polar vs intermediate location, (2) exophytic ≥50 / <50 / endophytic, (3) renal rim lateral vs medial, (4) sinus involvement, (5) collecting-system involvement, (6) size ≤4 / 4–7 / ≥7. Score 6–7 low, 8–9 moderate, ≥10 high.",
        "More items on sinus/collecting system than RENAL; slightly better for urine-leak prediction in some series.",
      ]},
      { t: "h", v: "Other systems (enumerate for the ‘various’ stem)" },
      { t: "ul", v: ["C-index (Simmons): distance from kidney centre to tumour centre / tumour radius — centrality.", "DAP (diameter-axial-polar).", "Contact Surface Area, ABC (arterial-based complexity), Mayo adhesive probability (for sticky fat, not tumour).", "SPAAT, Zonal NePhRO."], },
      { t: "h", v: "Advantages" },
      { t: "ul", v: [
        "Common language between radiologist, urologist, trialist.",
        "Predicts warm ischaemia, blood loss, conversion, urine leak, Clavien ≥3 (not perfectly — c-index ~0.6–0.7).",
        "Allows case selection for trainees vs experts, and for ablation vs PN vs RN.",
        "Research end-point standardisation.",
        "Limitations: inter-observer variation, does not include body habitus, prior surgery, solitary kidney, or tumour biology (grade).",
      ]},
      { t: "p", v: "PN indications and principles sit in the NSS master — nephrometry is the pre-op map, not the indication." },
      { t: "tip", k: "gold", v: "RENAL = Radius, Exophytic, Nearness, Anterior, Location. 4–6 / 7–9 / 10–12. PADUA is the Italian twin. Quote Kutikov 2009." },
    ],
  },
  {
    id: "partial-nephrectomy-nss",
    topicId: "renal-tumors",
    title: "Partial nephrectomy — indications, technique, preservation, follow-up",
    highYield: true,
    gold: true,
    tags: ["PN", "NSS", "warm ischaemia", "enucleation"],
    exams: [
      { session: "Jun", year: 2019, marks: "3+3+4", stem: "Discuss nephrometry score. Describe indications and principles of partial nephrectomy for renal cell carcinoma." },
      { session: "Dec", year: 2012, marks: "2+4+4", stem: "Describe candidate selection, surgical approach and contemporary outcome of partial nephrectomy in relation to localized renal cell carcinoma (RCC)." },
      { session: "Dec", year: 2011, marks: "7+3", stem: "What are the recent advances in renal preservations during surgical management of renal cell carcinoma? What is the role of neo-adjuvant sunitinib in promoting renal preservation?" },
      { session: "Dec", year: 2018, marks: "3+4+3", stem: "Nephron sparing surgery in RCC - Indications, surgical technique and follow up." },
    ],
    related: ["nephrometry-scores", "srm-management", "pn-complications", "haemostatic-agents-lpn"],
    references: [
      "EAU / AUA RCC — PN is standard for T1",
      "Campbell — Partial nephrectomy",
      "Huang / Memorial Sloan Kettering CKD after RN vs PN",
      "EORTC 30904 (Van Poppel) — PN vs RN oncologic equivalence in T1",
    ],
    answer: [
      { t: "h", v: "Indications" },
      { t: "tbl", h: ["Category", "Examples"], r: [
        ["Elective", "T1a (standard of care), T1b when technically feasible, selected T2 in experienced hands"],
        ["Imperative / absolute", "Solitary kidney, bilateral tumours, CKD, VHL / familial, poor contralateral (stones, RAS, chronic pyelo)"],
        ["Relative", "Recurrent stone former, young, proteinuria, hypertension, diabetes, lithiasis risk, woman of childbearing age"],
      ]},
      { t: "p", v: "Oncologic: EORTC 30904 showed similar DSS for PN vs RN in ≤5 cm tumours with a slight local-recurrence trade-off; PN reduces CKD. RN remains for non-feasible tumours, locally advanced, or a destroyed remnant." },
      { t: "h", v: "Candidate selection" },
      { t: "ul", v: ["Nephrometry low/moderate for the average surgeon; high for a referral centre.", "Performance status, anticoagulant, body habitus.", "Normal contralateral function is elective; split MAG3 if in doubt.", "Biopsy optional."], },
      { t: "h", v: "Surgical principles / technique" },
      { t: "ul", n: true, v: [
        "Approach: open (complex, solitary, T2, redo), transperitoneal RAPN (default), retroperitoneal RAPN (posterior tumours), lap PN. Same cancer operation regardless of hole.",
        "Expose, defat except over tumour, intra-op US for endophytic. Control hilum (artery ± vein). Cold ischaemia (ice) if predicted clamp >25–30 min; otherwise warm. Early unclamp / selective / off-clamp for polar.",
        "Resection: sharp excision with a thin parenchymal margin, or enucleation along pseudocapsule (familial, low-grade). Frozen section not routine.",
        "Inner running suture on sinus/collecting system; outer sliding-clip renorrhaphy. Floseal. Leak test.",
        "Drain, stent if large collecting-system repair. Warm ischaemia target <25 min (every minute counts, but parenchyma volume lost is the bigger CKD driver).",
      ]},
      { t: "h", v: "Renal-preservation advances (Dec 11, still valid)" },
      { t: "ul", v: [
        "PN instead of RN for T1.",
        "Zero / superselective ischaemia, early unclamping, off-clamp.",
        "Cold ischaemia, intra-arterial cold perfusion, Ice-Ball.",
        "3-D models, near-infrared ICG to map perfusion and tumour (ICG hypofluorescence of RCC).",
        "Enucleation, robotic articulation for hilar tumours.",
        "Ablation (cryo, RFA, microwave) and SBRT for the unfit.",
        "Active surveillance of SRMs.",
        "Neoadjuvant TKI / IO to downsize — see below.",
      ]},
      { t: "h", v: "Neoadjuvant sunitinib to promote preservation?" },
      { t: "p", v: "Phase 2 series showed modest diameter reduction (~10–20%) in some locally advanced or imperative-PN cases, with occasional conversion of RN to PN. Toxicity (wound, bleed, delayed surgery 2–3 half-lives off drug), non-responders, and lack of phase 3 mean it is NOT standard. EAU: do not use neoadjuvant TKI routinely. IO neoadjuvant is a trial question. Use it only in a protocol for an unresectable or imperative-NSS case after MDT." },
      { t: "h", v: "Outcomes and follow-up" },
      { t: "ul", v: [
        "Positive margin ~2–8%; many do not recur (especially pT1 low-grade) — observe with imaging, do not rush to RN.",
        "Local recurrence 1–3%; DSS equivalent to RN in T1.",
        "Follow-up (EAU risk-adapted): low-risk — US/CT at 6 mo then alternate; intermediate/high — CT chest-abdomen 6-monthly for 2 y then annually to 5 y, then individualise. Labs: Cr/eGFR, Hb, LFTs. Chest is the metastatic site — always image it.",
      ]},
      { t: "tip", k: "gold", v: "T1 = PN if you can. Warm ischaemia <25 min, but grams of parenchyma matter more. Sunitinib neoadjuvant is a case-report, not a guideline." },
    ],
  },
  {
    id: "srm-management",
    topicId: "renal-tumors",
    title: "Small renal mass — definition, modalities, active surveillance",
    highYield: true,
    gold: true,
    tags: ["SRM", "AS", "T1a", "ablation", "PN"],
    exams: [
      { session: "Dec", year: 2021, marks: "2+8", stem: "Describe small renal mass (SRM). Discuss various management strategies for management of SRM." },
      { session: "Dec", year: 2016, marks: "2+4+4", stem: "Enumerate various modalities for the management of small renal masses. Their indications and outcome." },
      { session: "Jun", year: 2019, marks: "2+4+4", stem: "Indications, justifications and outline of active surveillance for small renal masses." },
      { session: "Jun", year: 2018, marks: "10", stem: "Management of small renal mass." },
      { session: "Dec", year: 2014, marks: "10", stem: "Current status of management of T1a renal mass." },
    ],
    related: ["renal-mass-biopsy", "thermal-ablation-rcc", "partial-nephrectomy-nss", "bosniak-cysts"],
    references: [
      "EAU / AUA localised RCC",
      "DISSRM registry — active surveillance",
      "Campbell — Incidental renal mass",
    ],
    answer: [
      { t: "p", v: "SRM = an enhancing renal mass ≤4 cm (T1a) without gross extra-renal disease. ~20% benign (oncocytoma, fat-poor AML), ~20% indolent, ~20% potentially aggressive. Most are now incidental." },
      { t: "h", v: "Modalities — enumerate, then match" },
      { t: "tbl", h: ["Modality", "Indication", "Outcome"], r: [
        ["Active surveillance", "Elderly/comorbid, <2–3 cm, low growth, patient preference after counselling; biopsy-proven oncocytoma/low-grade", "Metastasis <2% if growth <5 mm/y and size <3 cm (DISSRM). Delayed intervention 10–30%"],
        ["PN (open/lap/robot)", "Young, healthy, imperative NSS, T1a default in fit patients", "Gold oncologic + functional standard. Clavien ≥3 ~5–10%"],
        ["RN", "Unreconstructable T1a (hilar in a kidney not worth saving), non-function, surgeon/patient choice after counselling that PN is preferred", "Over-treatment of function; equivalent CSS in T1a"],
        ["Thermal ablation (cryo, RFA, MWA)", "≤3 cm, posterior/exophytic, comorbid, solitary kidney, after biopsy", "Local recurrence higher than PN (5–10%), salvage possible; EAU: offer for <3 cm"],
        ["SBRT / stereotactic", "Unfit, trial", "Emerging"],
        ["Systemic", "Not for localised SRM"],
      ]},
      { t: "h", v: "Active surveillance — indications, justification, outline (Jun 19)" },
      { t: "ul", v: [
        "Justification: competing-risk mortality exceeds RCC mortality in the elderly; 20% of SRMs are benign; growth kinetics predict behaviour; delayed PN remains feasible.",
        "Indications: limited life expectancy, high peri-op risk, SRM <2–3 cm, patient choice. Less suitable: young, >4 cm, infiltrative, growth >5 mm/year, systemic symptoms, preference for treatment.",
        "Outline: (1) counsel metastasis risk ~1–2%. (2) Optional biopsy. (3) Imaging (CT/MRI/contrast US) 3–6 monthly for 1 year, then 6–12 monthly. (4) Trigger to intervene: growth >5 mm/y, size crossing 3–4 cm, patient preference, stage migration. (5) Metastatic work-up if growth spurt. (6) Record in a registry mentality (DISSRM criteria: initial diameter, growth rate, Charlson).",
      ]},
      { t: "h", v: "Current status of T1a (Dec 14, still the law)" },
      { t: "p", v: "PN is the recommended default in the fit patient. AS is first-line to discuss in the frail. Ablation is an alternative for <3 cm. RN is the operation you should justify, not the other way round." },
      { t: "flow", title: "SRM decision", nodes: [
        { id: "a", kind: "start", label: "Enhancing mass ≤4 cm, staging negative", to: ["b"] },
        { id: "b", kind: "decision", label: "Fit for PN and prefers treatment?", to: ["c", "d"] },
        { id: "c", kind: "end", label: "RAPN / PN (biopsy optional)" },
        { id: "d", kind: "decision", label: "Comorbid / <3 cm / patient wants AS?", to: ["e", "f"] },
        { id: "e", kind: "end", label: "AS ± biopsy; intervene if growth" },
        { id: "f", kind: "end", label: "Ablation after biopsy, or RN if PN impossible" },
      ]},
      { t: "tip", k: "gold", v: "SRM ≤4 cm. 20% benign. Fit = PN. Frail = watch. Ablate the 3 cm posterior lump in the 80-year-old. RN needs a reason." },
    ],
  },
  {
    id: "thermal-ablation-rcc",
    topicId: "renal-tumors",
    title: "Thermal ablative therapies in RCC",
    highYield: false,
    gold: false,
    tags: ["RFA", "cryo", "microwave", "SBRT"],
    exams: [
      { session: "Dec", year: 2015, marks: "10", stem: "Current status of thermal ablative therapies in renal cell carcinoma." },
    ],
    related: ["srm-management", "renal-mass-biopsy", "partial-nephrectomy-nss"],
    references: ["EAU RCC — ablation", "AUA localised renal masses", "Campbell — Ablative therapies"],
    answer: [
      { t: "tbl", h: ["Modality", "Physics", "Pros", "Cons"], r: [
        ["Cryoablation", "Argon freeze / helium thaw, ice at −20 to −40 °C, 2 cycles; ice visible on CT", "Watch the ice ball, less urothelial injury, percutaneous or lap", "Bleed, crack, larger probe set, freeze–thaw time"],
        ["RFA", "Alternating current ~500 kHz, coagulative necrosis >60 °C", "Cheap, percutaneous, good for <3 cm exophytic", "Heat sink next to vessels, not MRI-visible in real time, urothelial stricture, incomplete at hilum"],
        ["Microwave", "Dielectric heating, faster, less heat-sink", "Larger/faster ablation", "Less long-term data than cryo/RFA historically; catching up"],
        ["HIFU / irreversible electroporation / SBRT / laser", "Non-thermal or focused", "Niche / trial", "Not standard"],
      ]},
      { t: "h", v: "Current status" },
      { t: "ul", v: [
        "EAU: offer thermal ablation for SRM <3 cm, especially comorbid, after biopsy. Counsel higher local recurrence than PN but low CSS impact because salvage works.",
        "Best: posterior, exophytic, ≥5–10 mm from collecting system / ureter (hydrodissection, pyeloperfusion with cold D5W for RFA).",
        "Follow-up: contrast CT/MRI at 3, 6, 12 months then annually — absence of enhancement = success. Residual enhancement in the bed at 3 months = incomplete → re-ablate.",
        "Complications: haemorrhage, haematoma, urine leak, ureteric stricture, nerve (genitofemoral) injury, bowel injury if no hydrodissection, skin burn, seed rare.",
        "Not for T2, infiltrative, urothelial, uncorrected coagulopathy, or a healthy young T1a who should have PN.",
      ]},
      { t: "tip", k: "gold", v: "Ablation is a <3 cm, comorbid, biopsied-mass tool. Cryo if you want to see the ice; RFA/MWA if you want a thin percutaneous stick. It is not a lazy PN." },
    ],
  },
  {
    id: "ivc-thrombus",
    topicId: "renal-tumors",
    title: "RCC with IVC thrombus — levels and operative strategy",
    highYield: true,
    gold: true,
    tags: ["IVC", "Mayo levels", "bypass", "Pringle", "left RCC"],
    exams: [
      { session: "Dec", year: 2017, marks: "10", stem: "Management of left side RCC with IVC thrombus." },
      { session: "Dec", year: 2015, marks: "10", stem: "Management of a patient of renal cell carcinoma with inferior vena cava thrombus." },
      { session: "Dec", year: 2019, marks: "5+5", stem: "Write TNM classification of renal cell carcinoma. Write management of tumour thrombus in inferior vena cava at and above the level of hepatic veins." },
      { session: "Dec", year: 2013, marks: "10", stem: "Discuss management of RCC with IVC thrombus reaching up to the diaphragm." },
    ],
    related: ["rcc-tnm", "flank-vs-anterior", "mtor-vegf-tki"],
    references: [
      "Neves–Zincke / Mayo IVC levels",
      "EAU RCC — locally advanced",
      "Campbell — Surgery of IVC thrombus",
      "Blute / Mayo surgical series",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Stage, IMDC, MRI/CT level, neoadjuvant only in a trial, then level-matched surgery. Draw Mayo 0–IV. Left side: long vein, lumbar, need to control the right renal vein too." },
      { t: "h", v: "Levels (Mayo / Neves–Zincke)" },
      { t: "tbl", h: ["Level", "Extent", "TNM", "Typical exposure"], r: [
        ["0", "Renal vein only", "T3a", "Standard RN"],
        ["I", "IVC <2 cm from ostium", "T3b", "Satinsky on IVC, no bypass"],
        ["II", "IVC below hepatic veins, >2 cm", "T3b", "Caudate mobilisation, liver pocket; Milking; Pringle optional"],
        ["III", "At / above hepatic veins but below diaphragm", "T3b/c", "Liver transplant manoeuvres (Piggyback), Pringle, possible in-line shunting / bypass"],
        ["IV", "Supradiaphragmatic / atrial", "T3c", "Sternotomy / CPB ± circulatory arrest; or trans-diaphragmatic without CPB in selected"],
      ]},
      { t: "h", v: "Work-up" },
      { t: "ul", v: [
        "CECT + MRI (MRI still best for bland vs tumour thrombus and cranial extent — last 24–48 h before surgery because thrombus grows). Doppler IVC. Echo if level III–IV (right-heart, PFO, embolus).",
        "Metastatic survey. IMDC. MDT: urology, liver/vascular, cardiac anaesthesia.",
        "Anticoagulate bland thrombus; tumour thrombus is not a warfarin indication per se but pulmonary embolus risk is real.",
        "Embolization of the kidney pre-op: optional, controversial (pain, does not shrink IVC thrombus reliably).",
        "Neoadjuvant TKI/IO: may downsize some thrombi (sunitinib/axitinib series) — not standard; delays a curable operation. Use if already metastatic or technically unresectable.",
      ]},
      { t: "h", v: "Principles of surgery (all levels)" },
      { t: "ul", n: true, v: [
        "Anterior exposure (chevron / midline ± sternotomy). Artery first (left: ligate artery in aorto-renal window) to shrink the thrombus.",
        "Sequence: artery → caudal IVC / contralateral vein control → cranial IVC control → ostium. Lumbar veins are the bleeders.",
        "Milk the thrombus down if mobile (level II–III) under TEE, then a cavotomy at the ostium. Inspect the lumen; resect wall if invaded (patch / graft).",
        "Never staple across tumour thrombus. Intra-op TEE for level III–IV.",
        "Lymphadenectomy of bulky nodes. Adrenal as indicated.",
      ]},
      { t: "h", v: "Left-sided RCC + IVC thrombus (Dec 17 extra)" },
      { t: "ul", v: [
        "Left renal vein is long: thrombus must cross the midline under the SMA to enter IVC. Control the right renal vein (the remaining kidney’s only outflow) before cavotomy.",
        "Left gonadal, adrenal, lumbar feed the vein — ligate. Circumaortic variants.",
        "Artery is behind the vein on the left — take it early from between aorta and IVC or from a posterior window.",
        "Bowel: full left medial viscera rotation or transperitoneal colon reflection.",
      ]},
      { t: "h", v: "At / above hepatic veins and to the diaphragm (Dec 13 / Dec 19)" },
      { t: "ul", v: [
        "Level III (hepatic veins, infra-diaphragmatic): mobilise the liver off the IVC (ligate short hepatics, piggy-back), Pringle manoeuvre, sometimes suprahepatic infra-diaphragmatic clamp. Primary cavotomy, extract, repair. Venovenous bypass (femoral–axillary or portal) if clamping time / haemodynamics demand.",
        "Level IV / atrial: cardiac team, CPB ± hypothermic circulatory arrest, or beating-heart extraction with TEE if a small floating atrial cap can be milked down. Diaphragm split if transabdominal-only experts (Ciancio manoeuvre) in selected III/low-IV.",
        "Bland thrombus distal in the IVC/iliacs: extract or trap with a clip/filter; anticoagulate post-op.",
        "Metastatic disease: cytoreductive RN + thrombectomy only if the patient is IMDC favourable/intermediate, thrombus is the symptomatic problem (Budd–Chiari, Budd-like, PE), and systemic therapy is lined up. Poor-risk metastatic = systemic first (CARMENA logic).",
      ]},
      { t: "p", v: "Outcomes: peri-op mortality 2–10% by level; CSS determined by stage/grade/mets not by the mere presence of thrombus if it is completely resected. Positive IVC-wall margin and mets drive failure." },
      { t: "tip", k: "gold", v: "Level dictates the team: I–II urologist, III bring a liver surgeon, IV bring a pump. Artery first, contralateral vein before you open the cava, TEE above the liver. Left side still has to cross the aorta." },
    ],
  },
  {
    id: "mtor-vegf-tki",
    topicId: "renal-tumors",
    title: "VEGF, TKI and mTOR therapy in RCC",
    highYield: true,
    gold: true,
    tags: ["sunitinib", "pazopanib", "cabozantinib", "everolimus", "IMDC"],
    exams: [
      { session: "Dec", year: 2017, marks: "5+5", stem: "Mechanism of action of m-TOR and VEGF inhibitor drugs in RCC." },
      { session: "Jun", year: 2015, marks: "10", stem: "Current status of targeted therapy in metastatic renal cell carcinoma." },
      { session: "Dec", year: 2013, marks: "10", stem: "In a metastatic RCC of clear cell, what would you prefer as first line - Tyrosine Kinase Inhibitor and why?" },
    ],
    related: ["immune-checkpoint-rcc", "rcc-who-subtypes", "rcc-familial-vhl"],
    references: [
      "Motzer sunitinib vs IFN (NEJM 2007)",
      "COMPARZ, METEOR, CheckMate 9ER, CLEAR, KEYNOTE-426",
      "RECORD-1 everolimus",
      "EAU / ESMO RCC",
    ],
    answer: [
      { t: "h", v: "VEGF axis inhibitors — mechanism" },
      { t: "p", v: "ccRCC is HIF–VEGF addicted (VHL loss). VEGF-A binds VEGFR2 on endothelium → angiogenesis. Drugs either trap VEGF (bevacizumab) or inhibit VEGFR tyrosine kinases (sunitinib, pazopanib, axitinib, cabozantinib, lenvatinib, tivozanib, sorafenib)." },
      { t: "tbl", h: ["Drug", "Targets", "Classic trial / role"], r: [
        ["Sunitinib", "VEGFR1–3, PDGFR, c-KIT, FLT3", "Motzer 2007 vs IFN — the original first-line TKI"],
        ["Pazopanib", "VEGFR, PDGFR, KIT", "COMPARZ non-inferior to sunitinib, better QoL"],
        ["Axitinib", "VEGFR1–3 potent", "AXIS second-line; now with pembro (KN-426)"],
        ["Cabozantinib", "VEGFR2, MET, AXL", "METEOR 2nd line; CABOSUN poor-risk; with nivo (9ER)"],
        ["Lenvatinib", "VEGFR, FGFR", "With everolimus (2nd) or pembro (CLEAR 1st)"],
        ["Tivozanib", "VEGFR", "TIVO-3; not universally available"],
        ["Bevacizumab", "VEGF-A ligand", "With IFN historically; with atezo IMmotion151 not practice-changing"],
        ["Sorafenib", "Raf / VEGFR", "TARGET — first anti-angiogenic RCC drug, now historical"],
      ]},
      { t: "h", v: "mTOR inhibitors — mechanism" },
      { t: "p", v: "mTORC1 (rapamycin target) sits downstream of PI3K–Akt and of nutrient/HIF signalling; in RCC it drives protein translation (4E-BP1, S6K), HIF translation, growth. Rapalogues (everolimus, temsirolimus) bind FKBP12 → inhibit mTORC1 (not mTORC2 — compensatory Akt activation is an escape). Temsirolimus (IV) improved OS in poor-risk (Hudes 2007) in the IFN era; everolimus oral (RECORD-1) after TKI. Combined with lenvatinib as a VEGF–mTOR pair. TSC-AML uses the same axis (EXIST-2)." },
      { t: "h", v: "First-line TKI for clear-cell mRCC — the Dec 13 stem, updated" },
      { t: "p", v: "In 2013 the honest answer was sunitinib (or pazopanib): level-1 OS/PFS vs IFN, oral, IMDC all-risk (temsirolimus if poor-risk). In 2024–26 the honest answer is: a TKI is no longer the preferred first-line monotherapy for most patients — PD-1 + TKI or nivo + ipi is. If a TKI alone is chosen (IO contraindication: autoimmune, transplant, poor access): cabozantinib (CABOSUN, MET activity) or pazopanib (COMPARZ QoL) over sunitinib. Favourable-risk IMDC still VEGF-responsive; poor-risk should not get sunitinib monotherapy if IO is available." },
      { t: "h", v: "Current status of targeted therapy (the modern paragraph)" },
      { t: "ul", v: [
        "TKIs remain the partner of PD-1 in first line and the backbone of later lines (cabozantinib, tivozanib, lenvatinib–everolimus).",
        "mTOR monotherapy is a later-line or combination (len–eve) option, plus the TSC/VHL niche.",
        "HIF-2α inhibitor belzutifan: VHL disease and now pretreated mRCC (LITESPARK-005).",
        "Cytoreductive nephrectomy: not before TKI in IMDC poor-risk (CARMENA). Deferred CN after response is individualised.",
      ]},
      { t: "ul", v: ["TKI AE: HTN, HFS, diarrhoea, hypothyroidism, fatigue, QT, hepatotoxicity (pazopanib), proteinuria.", "mTOR AE: stomatitis, hyperglycaemia, dyslipidaemia, pneumonitis, poor wound healing, infection."], },
      { t: "tip", k: "gold", v: "VEGF-TKI starves the HIF-driven vessels; mTOR starves the translation of HIF. 2013: sunitinib first. 2024: IO ± TKI first, cabozantinib the cleanest TKI-only answer." },
    ],
  },
  {
    id: "rcc-prognostic-markers",
    topicId: "renal-tumors",
    title: "Clinical, pathological and laboratory prognostic markers in RCC",
    highYield: true,
    gold: false,
    tags: ["IMDC", "MSKCC", "SSIGN", "Leibovich", "BAP1"],
    exams: [
      { session: "Dec", year: 2016, marks: "3+4+3", stem: "Clinical, pathological and laboratory prognostic markers in renal cell carcinoma." },
    ],
    related: ["rcc-who-subtypes", "rcc-tnm", "immune-checkpoint-rcc"],
    references: ["MSKCC Motzer, IMDC Heng", "SSIGN / Leibovich (Mayo)", "UISS (UCLA)", "EAU RCC"],
    answer: [
      { t: "tbl", h: ["Domain", "Markers"], r: [
        ["Clinical", "TNM stage (dominant), performance status (KPS/ECOG), symptoms (local vs systemic), time from diagnosis to systemic Rx <1 y, IMDC risk (see labs), nodal burden, sarcomatoid, brain/liver/bone mets (worse), cytoreductive eligibility, age/comorbidity (competing risk)"],
        ["Pathological", "T stage, N, ISUP/WHO grade, subtype (cc vs chromophobe vs collecting-duct), sarcomatoid/rhabdoid %, tumour necrosis, lymphovascular/sinus invasion, positive margin, adrenal, thrombus level (less than stage), BAP1/PBRM1/SETD2, PD-L1 (not used to withhold IO)"],
        ["Laboratory", "IMDC/Heng: anaemia, neutrophilia, thrombocytosis, Ca above ULN, KPS <80, diagnosis-to-treatment <1 y. MSKCC/Motzer: KPS, LDH >1.5×, Ca, Hb, interval <1 y. CRP, ALP, albumin, NLR, urine markers none standard. EPO/PTHrP as paraneoplastic burden"],
      ]},
      { t: "p", v: "IMDC 0 = favourable, 1–2 intermediate, ≥3 poor — used to pick nivo-ipi vs IO/TKI and to interpret CARMENA. SSIGN/Leibovich for post-op localised ccRCC surveillance intensity." },
      { t: "tip", k: "gold", v: "Stage, grade, subtype, PS. For metastatic quote IMDC (Hb, Ca, neutrophils, platelets, KPS, time). For resected ccRCC quote Leibovich/SSIGN." },
    ],
  },
  {
    id: "wilms-tumor",
    topicId: "renal-tumors",
    title: "Wilms tumour — staging, genetics, rests, COG vs SIOP",
    highYield: true,
    gold: true,
    tags: ["Wilms", "NWTS", "SIOP", "COG", "WT1", "nephrogenic rest"],
    exams: [
      { session: "Jun", year: 2020, marks: "3+2+5", stem: "What is the staging system of paediatric Wilms’ Tumour? What are nephrogenic rests? What is the role of nephrogenic rest in Wilms tumor?" },
      { session: "Jun", year: 2017, marks: "10", stem: "Current management of Wilms’ tumor." },
      { session: "Dec", year: 2017, marks: "10", stem: "Management of Wilm’s tumor in a 1 year old child." },
      { session: "Jun", year: 2018, marks: "4+6", stem: "Genetic abnormalities in Wilms’ tumour and outline its management." },
      { session: "Dec", year: 2015, marks: "5+5", stem: "Prognostic factors for children with Wilms’ tumor. Role of pre-operative chemotherapy in Wilms’ tumor." },
    ],
    related: ["rcc-who-subtypes", "rcc-familial-vhl"],
    references: [
      "COG / NWTS protocols",
      "SIOP-RTSG UMBRELLA",
      "Campbell Paediatric Oncology",
      "WHO GU — nephroblastoma",
    ],
    answer: [
      { t: "tip", k: "exam", v: "COG surgical staging vs SIOP post-chemo staging — say which. Genetics WT1/WT2/WTX/TP53. 1-year-old = COG up-front nephrectomy unless unresectable/bilateral/syndromic. Pre-op chemo is SIOP default and COG exception." },
      { t: "h", v: "Staging" },
      { t: "tbl", c: "NWTS/COG clinicopathologic (pre-chemo surgery)", h: ["Stage", "Definition"], r: [
        ["I", "Confined to kidney, complete resection, intact capsule, no rupture, vessels of sinus not involved, no biopsy before (except FNA in some versions)"],
        ["II", "Extra-renal but complete resection (capsule breach, sinus vessels, biopsy, local spillage confined to flank)"],
        ["III", "Residual or spillage: positive margin, nodes, peritoneal implants, tumour rupture, piecemeal, transected thrombus, biopsy (core) — residual abdomen"],
        ["IV", "Haematogenous mets (lung, liver, bone, brain) or extra-abdominal nodes"],
        ["V", "Bilateral renal at diagnosis (each side substaged)"],
      ]},
      { t: "p", v: "SIOP stages after 4 weeks pre-op vincristine/actinomycin: similar I–V but biopsy does not automatically make III, and necrotic tumour in nodes is recorded. Always state ‘COG stage’ or ‘SIOP stage’." },
      { t: "h", v: "Nephrogenic rests and their role" },
      { t: "p", v: "Nephrogenic rests = persistent embryonic metanephric blastema after 36 weeks. Precursor of Wilms. Perilobar (PLNR: periphery, OTCs, Beckwith–Wiedemann, hemihypertrophy) vs intralobar (ILNR: anywhere, WT1, WAGR, Denys–Drash). Nephroblastomatosis = diffuse or multiple rests. Role: (1) precursor lesion — rest → Wilms by further hits (WT1, β-catenin, 11p15); (2) marker of bilateral / metachronous risk — ILNR and nephroblastomatosis mandate contralateral inspection and intensive imaging; (3) overgrowth syndromes surveillance; (4) pathology must distinguish rest from residual Wilms after chemo (rests lack the triphasic invasion)." },
      { t: "h", v: "Genetics" },
      { t: "tbl", h: ["Locus / gene", "Syndrome / meaning"], r: [
        ["WT1 11p13", "WAGR (WT1+PAX6 — aniridia, GU, retardation), Denys–Drash (diffuse mesangial sclerosis, XY DSD), Frasier. ILNR. Stromal-predominant tumours"],
        ["WT2 11p15 IGF2/H19 (imprinting)", "Beckwith–Wiedemann, hemihypertrophy. PLNR. Isolated LOI of IGF2 in many sporadic Wilms"],
        ["WTX / AMER1 Xq11", "Somatic, ~20–30%"],
        ["CTNNB1 (β-catenin)", "Often with WT1"],
        ["TP53", "Anaplasia (unfavourable histology) — the chemo-resistant clone"],
        ["1q gain, 1p/16q LOH (COG)", "Adverse in favourable histology — intensifies chemo"],
        ["MYCN, SIX1/2, DROP2, DICER1 (cystic nephroma / PPB spectrum — not classic Wilms)", "Emerging"],
      ]},
      { t: "h", v: "Histology and prognostic factors" },
      { t: "ul", v: [
        "Favourable: triphasic blastemal/epithelial/stromal without anaplasia (~90%, OS >90%).",
        "Unfavourable: focal or diffuse anaplasia (TP53) — worse, needs intensified Rx. SIOP blastemal-type after chemo is also high-risk.",
        "Stage, age (>4 y slightly worse), tumour volume, 1p/16q LOH, 1q gain, metastatic burden (especially extra-pulmonary), rupture/spillage, incomplete resection, bilateral (function, not death).",
        "Anaplastic / SIOP high-risk histology drive radiotherapy and doxorubicin/etoposide/carboplatin/cyclophosphamide.",
      ]},
      { t: "h", v: "Management — current, and the 1-year-old" },
      { t: "ul", v: [
        "Work-up: US + Doppler (renal vein/IVC), CECT/MRI abdomen, chest CT, BP, urine catecholamines only to exclude neuroblastoma, coagulation (acquired von Willebrand), never biopsy a typical resectable unilateral mass in a COG centre.",
        "COG (North America, many Indian centres mixed): immediate nephrectomy if resectable, then stage + histology + biology → chemo ± flank/lung RT. Stage I FH, very low risk (age <2 y, <550 g) may be surgery only on study.",
        "SIOP (Europe): pre-op chemo 4 weeks VA (6 weeks if mets) then nephrectomy then stage. Benefits: less rupture, smaller tumour, more in-stage I. Costs: untreated rhabdoid/CCSK/neuroblastoma if you guessed wrong; staging after down-staging.",
        "1-year-old with a typical unilateral resectable mass: COG-style up-front radical nephrectomy (transperitoneal, inspect contralateral kidney, sample nodes — do not skip lymphadenectomy, it is staging not therapy), adrenal-sparing if possible, then VA ± doxorubicin per stage. SIOP-style pre-op chemo is acceptable if the mass is massive, IVC thrombus, or the child is unstable. Never a flank-only incision that cannot see the other kidney.",
        "Bilateral (stage V) / solitary kidney / syndromic: neoadjuvant chemo then NSS on the better side, delay nephrectomy, never up-front bilateral RN.",
        "Lung mets: chemo; RT to lung if incomplete response (COG).",
        "Follow-up: US/CXR intensive for 2 y then reducing; syndrome-specific contralateral surveillance if rests.",
      ]},
      { t: "h", v: "Role of pre-operative chemotherapy (Dec 15)" },
      { t: "ul", v: [
        "SIOP default: reduces intra-op rupture (Stage III spillage), increases stage I rate, treats occult mets, allows NSS in bilateral.",
        "COG uses it for unresectable, IVC above hepatic veins, bilateral, predisposition syndromes, and the very sick child.",
        "Disadvantage: treating a non-Wilms (rhabdoid, neuroblastoma, mesoblastic nephroma in a neonate — mesoblastic is surgery only, and a 1-month-old ‘Wilms’ is mesoblastic until proven otherwise). A 1-year-old is in the Wilms age (peak 3 y) so this trap is smaller than in neonates.",
      ]},
      { t: "tip", k: "gold", v: "Rests are the soil, WT1/11p15 the seed, TP53 the anaplasia. COG cuts then drugs; SIOP drugs then cuts. Sample the nodes. Bilateral = chemo then NSS. Neonate = mesoblastic, not Wilms." },
    ],
  },
  {
    id: "covid-nephropathy-mucor",
    topicId: "renal-tumors",
    title: "COVID nephropathy and renal mucormycosis",
    highYield: false,
    gold: false,
    tags: ["COVID", "mucor", "AKI", "amphotericin"],
    exams: [
      {
        session: "June",
        year: 2022,
        marks: "5+5",
        stem: "Covid Nephropathy. Describe the pathogenesis, evaluation and management of Covid Mucormycosis of kidney.",
      },
    ],
    related: ["aki-arf-urology", "ckd-classification-anaemia"],
    references: [
      "ISN COVID kidney reviews",
      "EAU / CDC mucormycosis",
      "Indian 2021 mucor epidemic literature",
    ],
    answer: [
      { t: "h", v: "COVID nephropathy" },
      { t: "ul", v: [
        "AKI in 20–40% of hospitalised / ICU COVID: pre-renal (sepsis, ventilation, abdominal pressure), ATN, collapsing FSGS (APOL1 high-risk alleles — ‘COVID-associated nephropathy / COVAN’), rhabdomyolysis, cytokine, thrombosis / TMA, cardiorenal, nephrotoxins (vancomycin, amphotericin later).",
        "SARS-CoV-2 tropism for ACE2 on proximal tubule and podocytes — direct infection is demonstrable but not the only story.",
        "Proteinuria, haematuria, collapsing glomerulopathy on biopsy. Dialysis logistics and anticoagulation for CRRT. ACE-i/ARB: do not stop routinely.",
        "Long COVID: persistent albuminuria, new CKD, vaccine-related MCD/IgA rare.",
      ]},
      { t: "h", v: "Renal mucormycosis — pathogenesis" },
      { t: "p", v: "Mucorales (Rhizopus, Mucor, Lichtheimia) are ubiquitous moulds. Spores germinate in hosts with diabetic ketoacidosis, glucocorticoids, neutropenia, transplant, iron overload / deferoxamine, and — the 2021 Indian signal — COVID + steroids + diabetes + industrial oxygen / humidifiers. The fungus is angio-invasive: hyphae invade arteries → thrombosis → black infarction. Isolated renal mucor is haematogenous or ascending; more often part of disseminated / rhino-orbito-cerebral disease." },
      { t: "h", v: "Evaluation" },
      { t: "ul", v: [
        "Clinical: fever, flank pain, anuria (bilateral), black necrotic urine rarely, poorly controlled diabetes after COVID, rhino-orbital clues.",
        "Labs: AKI, DKA, KOH/calcofluor on tissue — wide aseptate ribbon hyphae branching at 90°. Culture on Sabouraud (warn the lab — homogenising kills Mucor). Galactomannan is for Aspergillus, not Mucor. PCR/ITS on tissue.",
        "CT: enlarged infarcted non-enhancing kidney, peri-renal stranding, arterial thrombi, gas sometimes. Differential: emphysematous PN, infarct, xanthogranulomatous.",
        "Biopsy / nephrectomy specimen is often the diagnosis.",
      ]},
      { t: "h", v: "Management" },
      { t: "ul", n: true, v: [
        "Reverse host factors: stop steroids, control glucose, stop deferoxamine, reduce immunosuppression if possible.",
        "Antifungal: liposomal amphotericin B 5–10 mg/kg/d (first-line). Posaconazole or isavuconazole step-down / salvage. Echinocandins inactive. Deferasirox not recommended (trial harm).",
        "Urgent, wide surgical debridement — for isolated renal mucor this means nephrectomy of the infarcted kidney. Partial resection leaves fungus behind. Bilateral disease is a disaster (amphotericin + attempted salvage, dialysis).",
        "Source control of rhino-orbital disease concurrently. Anticoagulate only if bland thrombus without contraindication — the infarct is fungal vasculitis.",
        "Mortality remains high (30–50%+); early nephrectomy plus liposomal AmB is the urologic contribution.",
      ]},
      { t: "tip", k: "gold", v: "COVID kidney = ATN + collapsing FSGS in APOL1. Mucor = diabetic-steroid-COVID, angio-invasive, amphotericin plus take the dead kidney out." },
    ],
  },
  {
    id: "benign-renal-tumors-oncocytoma",
    topicId: "renal-tumors",
    title: "Benign renal tumours and oncocytoma",
    highYield: true,
    gold: false,
    tags: ["oncocytoma", "AML", "metanephric", "multilocular"],
    exams: [
      { session: "Jun", year: 2016, marks: "4+6", stem: "Benign tumors of the kidney. Macroscopic and microscopic features of oncocytoma." },
    ],
    related: ["tsc-aml", "srm-management", "renal-mass-biopsy", "rcc-who-subtypes"],
    references: ["WHO GU 2022", "Campbell — Benign renal tumors", "EAU RCC — oncocytic masses"],
    answer: [
      { t: "h", v: "Benign tumours of the kidney (list with one-line pearls)" },
      { t: "ul", v: [
        "Renal oncocytoma — commonest solid benign after AML; see below.",
        "AML — PEComa family; fat-rich vs fat-poor vs epithelioid (not always benign).",
        "Papillary adenoma — ≤15 mm, papillary, AMACR+; the benign counterpart of PRCC (WHO size cut-off).",
        "Metanephric adenoma — BRAF V600E, WT1+, BRAF IHC; surgical surprise in middle-aged women; always benign.",
        "Cystic nephroma / mixed epithelial stromal tumour (MEST) spectrum — adult women, DICER1 in some paediatric cystic nephroma.",
        "Multilocular cystic renal neoplasm of low malignant potential — not strictly benign but behaves so.",
        "Leiomyoma, haemangioma, lymphangioma, juxtaglomerular cell tumour (reninoma — young hypertensive, excised = cured), medullary fibroma (renomedullary interstitial-cell tumour, incidental), schwannoma, solitary fibrous tumour.",
        "Simple cyst, ADPKD cysts — not neoplasms.",
      ]},
      { t: "h", v: "Oncocytoma — macroscopy" },
      { t: "ul", v: [
        "Mahogany-brown, well-circumscribed, unencapsulated or pseudo-capsule, typically 3–6 cm.",
        "Central stellate scar in ~30–50% (especially larger) — the CT ‘spoke-wheel’ artery and scar are suggestive, not diagnostic (chromophobe and ccRCC can scar).",
        "No necrosis, no haemorrhage usually; rare sats. Can be multifocal / bilateral in BHD and in oncocytosis.",
      ]},
      { t: "h", v: "Oncocytoma — microscopy" },
      { t: "ul", v: [
        "Nests, tubules, islands of cells in a hypocellular myxoid/hyaline stroma.",
        "Cells: abundant granular eosinophilic cytoplasm (mitochondria packed — EM diagnosis historically), round central nuclei, even chromatin, small nucleoli. No raisinoid nuclei, no perinuclear halos (those are chromophobe).",
        "IHC: CD117/KIT+, CK7 negative or rare scattered cells (chromophobe is CK7 diffuse), vimentin−, Hale colloidal iron negative/focal (chromophobe diffuse).",
        "Genetics: CCND1 rearrangement; loss of 1, 14; not the multiple losses of chromophobe. BHD (FLCN) produces hybrid oncocytic tumours.",
        "The biopsy problem: oncocytic neoplasm, cannot exclude chromophobe — manage as SRM (AS is acceptable if imaging is classic and comorbidity high).",
      ]},
      { t: "tip", k: "gold", v: "Brown tumour, central scar, mitochondrial nests, CK7-negative, CD117-positive. Chromophobe is the malignant mimic — Hale iron and diffuse CK7 save you. Biopsy cannot always." },
    ],
  },
];
