import type { Master } from "../types";

export const renalTrauma: Master[] = [
  {
    id: "aast-renal-injury",
    topicId: "renal-trauma",
    title: "AAST renal injury grading and complex bilateral injury",
    highYield: true,
    gold: true,
    tags: ["AAST", "Grade IV", "NOM", "diabetes", "CKD"],
    exams: [
      {
        session: "June",
        year: 2022,
        marks: "4+6",
        stem: "Classify renal injuries. Describe the evaluation and management of a patient who has Grade 4 injury in one kidney and grade 2 injury in the opposite kidney, who is having type 1 diabetes and a serum creatinine of 2.3 mg %.",
      },
      {
        session: "Jun",
        year: 2014,
        marks: "4+6",
        stem: "What are the grades of renal injury? How do you manage Grade IV renal injury in a 40 years old female?",
      },
      {
        session: "Dec",
        year: 2022,
        marks: "5+5",
        stem: "Clinical grading system for renal trauma. Angio-embolization for renal trauma: Its role and complications.",
      },
    ],
    related: ["renal-trauma-imaging-embolization", "paediatric-renal-trauma", "gerota-fascia-approaches"],
    references: [
      "AAST Organ Injury Scale — Kidney, 1989; revision 2018 (Kozar / Santucci)",
      "EAU Urological Trauma guidelines",
      "Campbell-Walsh-Wein — Genitourinary Trauma",
      "World J Urol / AUA Urotrauma",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "AAST 2018 table 4 · Haemodynamic algorithm 2 · G4 management (NOM vs angio vs surgery) 2 · The diabetic Cr 2.3 bilateral case is a nephron-sparing sermon 2. Draw the 5-grade cartoons." },
      { t: "h", v: "AAST kidney injury scale (quote 2018 revision)" },
      { t: "p", v: "The 1989 Moore scale is still recognised; the 2018 revision moved all collecting-system injuries and segmental vascular injuries into Grade IV and reserved Grade V for shattered kidney or hilar avulsion. ‘Clinical grading’ in the Dec 22 stem = AAST (CT-based anatomic), not a separate bedside score. Haemodynamic status is the management axis, not the grade alone." },
      { t: "tbl", c: "AAST OIS kidney — 2018", h: ["Grade", "Imaging / operative criteria"], r: [
        ["I", "Subcapsular, non-expanding haematoma; parenchymal contusion. No laceration."],
        ["II", "Non-expanding perirenal haematoma confined to Gerota; cortical laceration ≤1 cm, no urinary extravasation."],
        ["III", "Parenchymal laceration >1 cm into cortex, no collecting-system rupture and no urinary extravasation. Any segmental vascular injury without contained haematoma expansion may be upgraded (2018)."],
        ["IV", "Parenchymal laceration into collecting system with urinary extravasation; or segmental renal artery/vein injury; or main renal artery/vein injury with contained haemorrhage; or thrombosis of a segmental vessel. Includes previously ‘G5 laceration through into collecting system’ that is not a shattered kidney."],
        ["V", "Shattered kidney (multiple lacerations, non-viable fragments) OR avulsion / occlusion of the main renal hilum (artery or vein) with a devascularised kidney."],
      ]},
      { t: "p", v: "Advance one grade for bilateral injuries up to Grade III (classic AAST footnote). In the June 22 stem you already have G4 + G2 — do not mechanically ‘upgrade’; manage the G4 and protect every nephron." },
      { t: "h", v: "Evaluation common to all grades" },
      { t: "ul", v: [
        "ATLS: ABC, blood on floor and four more, pelvic binder, eFAST. Kidney is never first if the abdomen is exsanguinating.",
        "Indications for renal imaging: see the imaging master. Gold test = CECT trauma protocol (arterial + portal venous ± delayed 5–10 min if laceration/fluid to show urine leak).",
        "Labs: CBC, Cr (baseline CKD in this diabetic), lactate, TEG, urine dip (haematuria is neither sensitive nor specific for grade).",
        "Absolute indication for immediate laparotomy: haemodynamic instability refractory to resuscitation with intraperitoneal haemorrhage. Relative: expanding retroperitoneal haematoma found at laparotomy for other injuries, main-vessel avulsion, ureteropelvic avulsion.",
      ]},
      { t: "h", v: "Grade IV in a 40-year-old woman (Jun 14)" },
      { t: "p", v: "Modern default is non-operative management (NOM) if she is stable." },
      { t: "ul", v: [
        "Stable, contained haematoma, even with urinary extravasation: bed rest, serial Hb, antibiotics if urine leak, stent or PCN only for expanding urinoma, fever, or obstruction. Most leaks seal by 48–72 h.",
        "Persistent arterial blush / pseudoaneurysm / AVF / ongoing transfusion need: angioembolization (superselective) — kidney-sparing gold standard.",
        "Unstable, failed embolization, or Grade V hilar injury: midline laparotomy, control aorta if needed, open Gerota only if the haematoma is expanding/pulsatile (otherwise leave Gerota closed). Reconstruct (renorrhaphy, partial nephrectomy, vascular repair) vs nephrectomy. Damage-control packing if coagulopathic.",
        "Collecting-system reconstruction if you are already open; otherwise endoscopic drainage.",
        "Follow-up: delayed CT if fever/falling haematocrit/ileus; DMSA later for function; BP (Page kidney, Goldblatt from scarring); pregnancy counselling is irrelevant acutely but ACE-i later if hypertensive.",
      ]},
      { t: "h", v: "June 22 case: G4 + G2, T1DM, Cr 2.3 mg/dL" },
      { t: "kpi", items: [
        { k: "Nephron status", v: "Already CKD (Cr 2.3 ≈ eGFR 25–35); both kidneys are precious" },
        { k: "G2 side", v: "Leave it alone — observation" },
        { k: "G4 side", v: "NOM ± embolize; nephrectomy is a last resort" },
        { k: "Diabetes", v: "Papillary ischaemia, infection, poor healing, contrast load" },
      ]},
      { t: "ul", v: [
        "Resuscitate, avoid hypotension (the G4 kidney and the CKD remnant will declare ATN).",
        "CECT with lowest reasonable contrast; delayed phase for leak. If Cr 2.3 and oliguric, weigh the diagnostic benefit — in instability you scan anyway.",
        "ITU, insulin sliding scale, culture, avoid NSAIDs/aminoglycosides.",
        "G2 kidney: observation, no drain, no exploration (exploration of a G2 to ‘have a look’ is how you lose the only good remnant).",
        "G4: aggressive NOM. Superselective embolization for blush rather than open surgery. Urinary extravasation: ureteric stent ± PCN; percutaneous urinoma drain if infected. Open surgery only for life-threatening bleed — then reconstruct (partial nephrectomy, pledgeted mattress, omental wrap, topical haemostats) rather than total nephrectomy whenever the back-table/hilar anatomy allows.",
        "If nephrectomy of the G4 side becomes necessary, the G2 kidney plus Cr 2.3 means RRT is likely — involve nephrology early, protect the remnant, delay contrast, plan dialysis access without ruining the non-dominant arm.",
        "Complications to name: delayed bleed day 5–14 (pseudoaneurysm — embolize), urinoma, abscess, Page kidney, hypertension, loss of function, fistula.",
      ]},
      { t: "flow", title: "G4 kidney, stable vs not", nodes: [
        { id: "a", kind: "start", label: "AAST G4 on CT", to: ["b"] },
        { id: "b", kind: "decision", label: "Shock despite blood products?", to: ["c", "d"] },
        { id: "c", kind: "action", label: "OR: midline, leave non-expanding Gerota; reconstruct > nephrectomy", note: "Hypertension of packing if damage-control" },
        { id: "d", kind: "decision", label: "Arterial blush / falling Hb?", to: ["e", "f"] },
        { id: "e", kind: "action", label: "Superselective angioembolization" },
        { id: "f", kind: "end", label: "NOM: rest, serial Hb, stent if symptomatic leak" },
      ]},
      { t: "h", v: "Angioembolization — role and complications (Dec 22 part b)" },
      { t: "ul", v: [
        "Role: stable or transient-responder with CT arterial blush, pseudoaneurysm, AVF, delayed haemorrhage, selected Grade IV–V, iatrogenic (PCNL/biopsy/PN) bleeds. Bridge to salvage in transient responders while the theatre is prepared. Success 80–95% in modern series; re-embolize before operating if the patient remains stable.",
        "Technique: femoral access, selective renal then superselective coaxial microcoils / particles / glue / foam to the bleeding segmental or interlobar artery. Proximal main-artery embolization is a ‘radiologic nephrectomy’ reserved for Grade V in a non-salvageable kidney with a normal contralateral kidney.",
        "Complications: puncture-site haematoma/pseudoaneurysm, contrast AKI (critical in Cr 2.3), non-target embolization (bowel, lower limb if coils migrate), post-embolization syndrome (fever, pain, leukocytosis 24–72 h — not infection), segmental infarct and later scar/hypertension, abscess in infarcted tissue, coil migration into collecting system (rare haematuria), failure requiring re-angio or surgery, radiation.",
      ]},
      { t: "tip", k: "gold", v: "Grade is anatomy; pulse is management. G1–III almost never need an operation. G4 is embolize-and-stent country. In a diabetic with Cr 2.3 and a G2 mate, losing the G4 kidney is starting dialysis — reconstruct or embolize." },
    ],
  },
  {
    id: "renal-trauma-imaging-embolization",
    topicId: "renal-trauma",
    title: "Imaging triggers, CT signs of major injury, IR vs open surgery",
    highYield: true,
    gold: true,
    tags: ["CT", "haematuria", "embolization", "RTA", "NOM"],
    exams: [
      {
        session: "Dec",
        year: 2020,
        marks: "3+3+4",
        stem: "What are the indications of renal imaging in a patient with renal injury? What are findings on CT scan that raise suspicion of major renal injury? What is the role of Angio embolization in renal trauma?",
      },
      {
        session: "Jun",
        year: 2020,
        marks: "5+5",
        stem: "Role of interventional radiology and indications of open surgery in management of renal trauma in a patient of road traffic accident.",
      },
    ],
    related: ["aast-renal-injury", "paediatric-renal-trauma", "contrast-locm-hocm"],
    references: [
      "EAU Urological Trauma 2024",
      "AAST / WSES–AAST kidney trauma guidelines",
      "Campbell — GU Trauma",
      "Morey AF et al. AUA Urotrauma",
    ],
    answer: [
      { t: "h", v: "Indications for renal imaging" },
      { t: "ul", v: [
        "Blunt trauma + gross haematuria.",
        "Blunt trauma + microscopic haematuria AND shock (SBP <90) at any time — classic Miller/McAninch criterion.",
        "Penetrating trauma to flank/abdomen/lower chest regardless of haematuria (haematuria may be absent in pedicle injury).",
        "High-energy mechanism even with clear urine: rapid deceleration (pedicle), fall from height, rib 10–12 fractures, lumbar transverse-process fracture, spine injury, blunt trauma in a child (see paediatric master — children tamponade poorly and bleed with microhaematuria).",
        "Pre-existing renal disease / solitary / anomalous kidney (horseshoe sits on the prominence of the spine).",
        "Persistent flank pain, falling haematocrit, delayed haematuria after initial clear urine (pseudoaneurysm).",
        "Intra-operative finding of a retroperitoneal haematoma of unknown grade.",
      ]},
      { t: "p", v: "Stable patients: CECT. Unstable patients: theatre, not CT. IVP ‘one-shot’ on table (2 mL/kg contrast, film at 10 min) only to confirm a contralateral kidney if you are about to remove one." },
      { t: "h", v: "CT findings that mean major (AAST IV–V) injury" },
      { t: "tbl", h: ["Finding", "Implication"], r: [
        ["Medial perirenal / perihilar haematoma, especially with no parenchymal laceration", "Pedicle / main-vein injury"],
        ["Non-enhancement of all or part of the kidney (cortical rim sign later)", "Main or segmental arterial occlusion / avulsion / thrombosis"],
        ["Active arterial extravasation (blush) on arterial phase, pooling on delayed", "Need for embolization or surgery"],
        ["Laceration through cortex, medulla into collecting system; contrast on delayed scans outside the collecting system", "Grade IV urine leak"],
        ["Multiple deep lacerations, floating fragments, ‘shattered’", "Grade V"],
        ["Circumferential haematoma expanding / >3.5 cm, or haematoma stripping Gerota with delayed blush", "Major vascular; NOM may fail"],
        ["Medial extravasation at PUJ, non-visualised distal ureter, intact parenchyma", "PUJ avulsion — surgery, not a stent trial alone if complete"],
        ["Devitalised fragment >25–50% plus contamination (bowel, pancreas)", "Higher failure of NOM, abscess"],
        ["Contrast in IVC / early venous filling", "AVF"],
        ["Delayed pseudoaneurysm (round enhancing sac in parenchyma on follow-up CT)", "Embolize"],
      ]},
      { t: "h", v: "Role of interventional radiology (RTA patient)" },
      { t: "ul", v: [
        "Primary: superselective angioembolization of bleeding segmental arteries in the stable or resuscitated patient with CT blush (Grade III–V).",
        "Delayed haemorrhage day 3–14 (pseudoaneurysm, AVF) — first-line.",
        "Damage-control adjunct: hybrid suite embolization of kidney, spleen, pelvis in polytrauma.",
        "Stent-graft of a main renal artery dissection in selected blunt pedicle injuries with a still-perfused kidney (short ischaemia time) — niche.",
        "Percutaneous drain of infected urinoma / abscess; PCN for PUJ leak.",
        "Not IR: complete hilar avulsion in a crashing patient, shattered kidney with uncorrectable shock, ureteric avulsion, abdominal hollow-viscus injury — those go to theatre.",
      ]},
      { t: "h", v: "Indications of open surgery in RTA renal trauma" },
      { t: "ul", v: [
        "Haemodynamic instability with evidence of ongoing retroperitoneal or intraperitoneal bleeding not controlled by (or not a candidate for) embolization.",
        "Expanding, pulsatile Gerota haematoma found at laparotomy for other injuries.",
        "Grade V main-hilar avulsion.",
        "Complete PUJ disruption.",
        "Failed embolization with ongoing transfusion.",
        "Peritonitis from associated bowel/pancreatic injury that already mandates laparotomy — kidney is then dealt with by the same incision (still avoid opening a stable haematoma).",
        "Renovascular hypertension / Page kidney is a delayed, rare operative indication; abscess after failed drainage.",
      ]},
      { t: "p", v: "Operative rules: midline, pack, central vascular control (renal artery on a loop or a Satinsky on the aorta/IVC in catastrophe), open Gerota only if committed, debride dead parenchyma, close collecting system with absorbable, pledgeted parenchymal sutures, omentum, drain. Nephrectomy if the patient is dying and the other kidney is known to exist (pre-op CT or one-shot IVP)." },
      { t: "tip", k: "gold", v: "Image gross haematuria, or micro + shock, or any penetrating flank. CT blush = IR. Shock = knife. A non-enhancing kidney with a medial haematoma is a pedicle until proven otherwise." },
    ],
  },
  {
    id: "paediatric-renal-trauma",
    topicId: "renal-trauma",
    title: "Renal trauma in a 9-year-old child",
    highYield: true,
    gold: false,
    tags: ["paediatric", "AAST", "NOM", "conservative"],
    exams: [
      {
        session: "Jun",
        year: 2016,
        marks: "5+5",
        stem: "Evaluation and management of renal trauma in a 9 year old child.",
      },
    ],
    related: ["aast-renal-injury", "renal-trauma-imaging-embolization"],
    references: [
      "EAU Paediatric Urology / Trauma",
      "Campbell Paediatric GU trauma",
      "APS A / ATLS paediatric",
      "AAST kidney OIS",
    ],
    answer: [
      { t: "h", v: "Why children are different" },
      { t: "ul", v: [
        "Kidney is larger relative to abdomen, less perinephric fat, weaker abdominal muscles, fetal lobulation persists — so a given blow grades higher.",
        "Ribs are pliable (less protection) yet transmit force.",
        "Congenital anomalies (PUJO, horseshoe, cyst) are over-represented in paediatric series presenting as ‘trauma’.",
        "Haematuria threshold: children can have major injury with only microhaematuria; imaging criteria are more liberal than in adults.",
        "NOM success is even higher than in adults (>80–90% of Grade I–IV). Nephrectomy rates should be very low in a paediatric centre.",
      ]},
      { t: "h", v: "Evaluation" },
      { t: "ul", v: [
        "ATLS paediatric: airway with C-spine, 20 mL/kg crystalloid boluses, blood early, avoid hypothermia.",
        "History: mechanism (handlebar, fall, RTA, sport, NAI — always consider non-accidental injury if history inconsistent).",
        "Imaging indications (EAU/paediatric): (1) any blunt trauma with ≥50 RBC/HPF or gross haematuria; (2) penetrating trauma; (3) high-energy deceleration even with a clear dipstick; (4) hypotension; (5) significant flank haematoma / lower-rib / lumbar-spine injury.",
        "CECT is the gold standard in the stable child; ‘as low as reasonably achievable’ dose. FAST is not sensitive for retroperitoneal injury. DMSA later for function, not acutely.",
        "Baseline Cr, blood bank, screen for anomaly (contralateral kidney).",
      ]},
      { t: "h", v: "Management" },
      { t: "ul", v: [
        "G I–III stable: strict rest, serial Hb, age-appropriate analgesia, bed-to-toilet once Hb stable; early feeding. No routine antibiotics unless urine leak / stent.",
        "G IV: NOM + interventional radiology (embolization) for blush, as in adults. Paediatric IR expertise required — transfer. Stent / PCN for symptomatic urinoma.",
        "Surgery: same absolute indications (unstable, hilar avulsion, PUJ disruption, failed IR). Reconstruct; partial nephrectomy; avoid nephrectomy of a reconstructable kidney. Midline laparotomy.",
        "Follow-up: restricted sport 6 weeks to 3 months depending on grade (no consensus — most Grade III–IV out of contact sport 6–12 weeks). Repeat US or CT if symptoms. BP checks for 1–2 years (Page / scar HTN). DMSA at 3–6 months. Counselling about solitary-kidney sport if nephrectomy done.",
        "NAI pathway if indicated. Tetanus. Associated urethral / bladder injuries in pelvic fracture — do not miss.",
      ]},
      { t: "tip", k: "gold", v: "Children: image more, operate less. Transfer G4 blush to a centre with paediatric IR. Think anomaly and think NAI." },
    ],
  },
];
