/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HighYieldRouteImport } from './routes/high-yield'
import { Route as RefsRouteImport } from './routes/refs'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as QQuestionIdRouteImport } from './routes/q.$questionId'
import { Route as TopicsTopicIdRouteImport } from './routes/topics.$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HighYieldRoute = HighYieldRouteImport.update({
  id: '/high-yield',
  path: '/high-yield',
  getParentRoute: () => rootRouteImport,
} as any)
const RefsRoute = RefsRouteImport.update({
  id: '/refs',
  path: '/refs',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const QQuestionIdRoute = QQuestionIdRouteImport.update({
  id: '/q/$questionId',
  path: '/q/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdRoute = TopicsTopicIdRouteImport.update({
  id: '/topics/$topicId',
  path: '/topics/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/high-yield': typeof HighYieldRoute
  '/refs': typeof RefsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/strategy': typeof StrategyRoute
  '/q/$questionId': typeof QQuestionIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/high-yield': typeof HighYieldRoute
  '/refs': typeof RefsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/strategy': typeof StrategyRoute
  '/q/$questionId': typeof QQuestionIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/high-yield': typeof HighYieldRoute
  '/refs': typeof RefsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/strategy': typeof StrategyRoute
  '/q/$questionId': typeof QQuestionIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/high-yield'
    | '/refs'
    | '/saved'
    | '/search'
    | '/strategy'
    | '/q/$questionId'
    | '/topics/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/high-yield'
    | '/refs'
    | '/saved'
    | '/search'
    | '/strategy'
    | '/q/$questionId'
    | '/topics/$topicId'
  id:
    | '__root__'
    | '/'
    | '/high-yield'
    | '/refs'
    | '/saved'
    | '/search'
    | '/strategy'
    | '/q/$questionId'
    | '/topics/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HighYieldRoute: typeof HighYieldRoute
  RefsRoute: typeof RefsRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  StrategyRoute: typeof StrategyRoute
  QQuestionIdRoute: typeof QQuestionIdRoute
  TopicsTopicIdRoute: typeof TopicsTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/high-yield': {
      id: '/high-yield'
      path: '/high-yield'
      fullPath: '/high-yield'
      preLoaderRoute: typeof HighYieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refs': {
      id: '/refs'
      path: '/refs'
      fullPath: '/refs'
      preLoaderRoute: typeof RefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$questionId': {
      id: '/q/$questionId'
      path: '/q/$questionId'
      fullPath: '/q/$questionId'
      preLoaderRoute: typeof QQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId': {
      id: '/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof TopicsTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HighYieldRoute: HighYieldRoute,
  RefsRoute: RefsRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  StrategyRoute: StrategyRoute,
  QQuestionIdRoute: QQuestionIdRoute,
  TopicsTopicIdRoute: TopicsTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
