import type { Master } from "../types";

export const sexual: Master[] = [
  {
    id: "erection-hemodynamics",
    topicId: "sexual",
    title: "Hemodynamics and mechanism of penile erection",
    highYield: true,
    gold: true,
    tags: ["erection", "NO", "cGMP", "veno-occlusive", "cavernosal artery"],
    exams: [
      { session: "Dec", year: 2021, marks: "6+4", stem: "Describe the mechanism of penile erection along with its hemodynamics. Discuss newer generation of PDE5 inhibitors." },
      { session: "Jun", year: 2016, marks: "3+3+4", stem: "Hemodynamics and mechanism of penile erection. Management of erectile dysfunction after radical prostatectomy." },
      { session: "Dec", year: 2017, marks: "5+5", stem: "Discuss the venous drainage of penis. Describe Veno-Occlusive mechanism of penile erection." },
      { session: "Dec", year: 2018, marks: "4+6", stem: "Blood supply of penis and diagnosis of arteriogenic erectile dysfunction." },
      { session: "Jun", year: 2018, marks: "10", stem: "Physiology of erection." },
    ],
    related: ["pde5", "ed-after-rp", "vasculogenic-ed", "penis-anatomy-ca"],
    references: [
      "Campbell-Walsh-Wein, Physiology of penile erection",
      "Lue TF. NEJM / J Sex Med — hemodynamic model",
      "ISSM / EAU Sexual and Reproductive Health",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "Draw: ICA → internal pudendal → common penile → cavernosal / dorsal / bulbourethral arteries. Helicine arteries. Sinusoids. Subtunical venules. NO → GC → cGMP → PKG → drop in Ca²⁺. Label flaccid vs erect pressures." },
      { t: "h", v: "Arterial supply" },
      { t: "ul", v: [
        "Anterior trunk of internal iliac → internal pudendal artery (Alcock's canal, medial to ischial tuberosity) → common penile artery after giving inferior rectal and perineal.",
        "Three terminal branches: (1) bulbourethral (bulbospongiosus, urethra, glans contribution), (2) dorsal artery of penis (skin, fascia, glans — lies between deep fascia and tunica, between dorsal nerve and deep dorsal vein), (3) cavernosal (deep) artery — enters corpus cavernosum at the crus and runs centrally, giving helicine arteries.",
        "Accessory pudendal arteries from external iliac / obturator / vesical — present in 20–25%; critical in nerve-sparing RP (Mulhall/Guillonneau). Injury → arteriogenic ED.",
        "Anastomoses: dorsal ↔ cavernosal at glans; circumflex arteries. This is why glans stays warm in proximal implant and why dorsal-artery sparing matters in hypospadias flaps.",
      ]},
      { t: "h", v: "Venous drainage (Dec 17)" },
      { t: "tbl", h: ["System", "Territory", "Route"], r: [
        ["Superficial", "Skin, Dartos", "Superficial dorsal vein → saphenous / femoral / rarely retropubic"],
        ["Intermediate", "Glans, corpus spongiosum, circumflex from cavernosa", "Deep dorsal vein (under Buck, in the groove) → periprostatic (Santorini) plexus → internal pudendal / vesical veins"],
        ["Deep", "Crura and proximal cavernosa", "Cavernosal and crural veins → internal pudendal vein"],
      ]},
      { t: "p", v: "Emissary veins pierce the tunica after receiving subtunical venules. Circumflex veins join the deep dorsal vein. There are no valves of clinical reliability — veno-occlusion is a mechanical compression phenomenon, not a valvular one." },
      { t: "h", v: "Hemodynamic phases (Lue)" },
      { t: "ul", n: true, v: [
        "Flaccid: high sympathetic tone, helicine arteries constricted, sinusoidal smooth muscle contracted, PO2 ~35 mmHg (venous), easy flow-through of emissary veins. Intracavernosal pressure (ICP) ~10–15 mmHg.",
        "Latent / filling: parasympathetic (pelvic nerve, S2–4) and non-adrenergic non-cholinergic (NANC) fibres fire. Arterial dilatation, ICP still near venous.",
        "Tumescent: sinusoidal relaxation, blood pools, ICP rises toward mean arterial pressure, elongation and girth.",
        "Full erection: ICP ≈ systolic − 10–20 mmHg. Subtunical venules are elongated and compressed against the tunica albuginea (veno-occlusive mechanism). Venous outflow falls to almost zero. Helicine arteries straighten.",
        "Rigid / skeletal: ischiocavernosus (pudendal somatic) contracts, ICP briefly 100–200+ mmHg — the rigid erection of penetration. Glans and spongiosum are not similarly trapped (thin tunica) — they remain compressible.",
        "Detumescence: sympathetic discharge (NE on α1) + PDE5 hydrolysis of cGMP → smooth muscle contraction, veins reopen. Three subphases: transient ICP rise (contracting muscle on a full penis), then rapid then slow detumescence.",
      ]},
      { t: "h", v: "Molecular mechanism" },
      { t: "ul", v: [
        "Initiation: psychogenic (thoracolumbar, T11–L2) and reflexogenic (pudendal afferents → S2–4) pathways converge. Hypothalamic MPOA, oxytocinergic PVN, and spinal generators.",
        "NANC nerves release nitric oxide (nNOS). Shear and acetylcholine on endothelium release more NO (eNOS) — maintenance.",
        "NO activates soluble guanylate cyclase: GTP → cGMP. cGMP → protein kinase G → (a) opens BK_Ca and K+ channels, (b) inhibits L-type Ca channels, (c) activates myosin-light-chain phosphatase. Cytosolic Ca²⁺ falls, myosin detaches, smooth muscle relaxes.",
        "PDE5 hydrolyses cGMP → GMP. PDE5 inhibitors are competitive at the catalytic site and require sexual stimulation (need some NO tone).",
        "RhoA/ROCK calcium-sensitisation keeps the flaccid state; its overactivity is a target in diabetic ED. PGE1 (intracavernosal) raises cAMP via adenylate cyclase — a parallel relaxant pathway (PDE5-independent).",
        "Testosterone permits NOS expression and PDE5 transcription — T replacement helps hypogonadal non-responders, does not treat eugonadal ED alone.",
      ]},
      { t: "h", v: "Veno-occlusive mechanism — the paragraph they want" },
      { t: "p", v: "Relaxation of trabecular smooth muscle allows the expanding sinusoids to push the subtunical venular plexus against the inelastic tunica albuginea, stretching and flattening the emissary veins as they pass obliquely through the tunica. Outflow resistance rises dramatically (veno-occlusion). Failure of this trap — Peyronie (inelastic plaque), ageing (degeneracy of tunica), distal-ligament injury, or incomplete smooth-muscle relaxation (arteriogenic / neuropathic / fibrotic) — produces venogenic / cavernosal ED. It is usually secondary, not a primary ‘leak’ of a vein that can be ligated with durable success." },
      { t: "tip", k: "gold", v: "Erection is arterial inflow + complete smooth-muscle relaxation + a competent tunica. Veins do not ‘close’; they are compressed. PDE5 only works if NO is being generated — hence the need for stimulation and the failure after complete cavernous-nerve resection." },
    ],
  },
  {
    id: "pde5",
    topicId: "sexual",
    title: "PDE5 inhibitors in urological practice",
    highYield: true,
    gold: true,
    tags: ["sildenafil", "tadalafil", "avanafil", "PDE5"],
    exams: [
      { session: "Dec", year: 2014, marks: "10", stem: "What are PDE-5 inhibitors? Describe mechanism of action, indications and side effects of PDE-5 inhibitors." },
      { session: "Dec", year: 2018, marks: "10", stem: "Phosphodiesterase inhibitors in Urological practice." },
      { session: "Dec", year: 2019, marks: "5+5", stem: "Mechanism of action and clinical use of Sildenafil." },
      { session: "Dec", year: 2020, marks: "3+3+2+2", stem: "What is nocturnal penile tumescence monitoring? What are its indications? Enumerate the pharmacological therapies available for erectile dysfunction. Write side effects of Sildenafil." },
      { session: "Dec", year: 2021, marks: "6+4", stem: "Describe the mechanism of penile erection along with its hemodynamics. Discuss newer generation of PDE5 inhibitors." },
    ],
    related: ["erection-hemodynamics", "ed-after-rp", "vasculogenic-ed", "non-pde5-oral", "priapism"],
    references: [
      "Campbell-Walsh-Wein, Pharmacotherapy of ED",
      "EAU Sexual and Reproductive Health 2024",
      "ISSM / Princeton consensus (cardiac safety)",
      "FDA labels: sildenafil, tadalafil, vardenafil, avanafil",
    ],
    answer: [
      { t: "p", v: "PDE5 inhibitors are competitive, reversible blockers of phosphodiesterase type 5, the enzyme that hydrolyses cGMP in cavernosal (and pulmonary, lower-tract) smooth muscle. They amplify NO–cGMP signalling; they do not create an erection in the absence of sexual stimulation / NANC firing." },
      { t: "h", v: "PDE family — why type 5" },
      { t: "p", v: "≥11 PDE families. PDE5 is abundant in corpus cavernosum, platelets, pulmonary vasculature and (clinically useful) prostate/bladder. PDE6 in retina (sildenafil visual AE — blue vision). PDE11 in skeletal muscle / testis (tadalafil myalgia, theoretical spermatogenesis concerns not borne out). Selectivity ratios explain the AE profiles." },
      { t: "tbl", c: "Agents — numbers examiners want", h: ["Drug", "Onset", "t½ / window", "Dose", "Food / pearls"], r: [
        ["Sildenafil (1998)", "30–60 min", "4 h / ~8–12 h", "25–100 mg (50 typical); 25 mg in elderly, CYP3A4, CrCl <30", "Fatty meal delays. Visual (PDE6). The prototype. Also PAH 20 mg TDS."],
        ["Vardenafil", "30–60 min", "4–5 h", "5–20 mg; ODT 10 mg", "QT caution with class IA/III. Fatty meal delays. ODT skips some first-pass."],
        ["Tadalafil", "30–120 min (often 45)", "17.5 h / 24–36 h ‘weekend’", "10–20 mg on-demand; 5 mg daily (2.5 if AE)", "Food-independent. Back pain/myalgia (PDE11). Daily dose licensed for BPH-LUTS ± ED (EAU). PAH 40 mg OD."],
        ["Avanafil (2nd/3rd gen)", "15–30 min", "6–17 h window ~6 h", "50–200 mg", "Fastest onset, fewer visual/myalgia data. Take 15 min pre-sex. CYP3A4."],
        ["Udenafil / lodenafil / mirodenafil", "regional", "—", "—", "Mention as available in some Asian markets"],
      ]},
      { t: "h", v: "Urologic indications beyond ED" },
      { t: "ul", v: [
        "ED of any organic / mixed / psychogenic cause — first-line oral (EAU/AUA) after lifestyle and CV risk.",
        "Post-RP penile rehabilitation (see dedicated card) — daily tadalafil 5 mg commonly used; evidence mixed but widely practised.",
        "BPH-LUTS: tadalafil 5 mg daily — similar IPSS drop to tamsulosin, useful if concurrent ED; can combine with 5-ARI.",
        "Stuttering (recurrent ischaemic) priapism: paradoxical daily PDE5 when flaccid (Burnett protocol) — NOT during an acute episode.",
        "Raynaud / secondary pulmonary hypertension — sildenafil/tadalafil (know they exist; not a urology prescription usually).",
        "Ureteric MET: tadalafil studied as adjunct to α-blocker; not first-line MET (α-blocker remains).",
        "Premature ejaculation with comorbid ED.",
      ]},
      { t: "h", v: "Contraindications and AE" },
      { t: "ul", v: [
        "Absolute: any nitrate (GTN, ISMN, nicorandil, poppers/amyl nitrite) — catastrophic hypotension. Wait 24 h after sildenafil/vardenafil, 48 h after tadalafil, before a nitrate. Riociguat (sGC stimulator) likewise.",
        "Caution: α-blockers (especially non-uroselective) — separate dosing, start low; CYP3A4 inhibitors (ritonavir, ketoconazole, grapefruit) — reduce dose; severe hepatic/renal impairment; resting hypotension; recent MI/stroke/unstable angina (Princeton III: sexual activity itself is the risk — stratify CV first).",
        "NAION (non-arteritic ischaemic optic neuropathy) — rare, shared vascular risk; stop and never restart if it occurs. Also sudden hearing loss.",
        "Common AE: flushing, headache, dyspepsia, rhinitis, dizziness. Sildenafil: chromatopsia, flashing lights. Tadalafil: myalgia, back pain. Priapism is uncommon with oral PDE5 alone — more with injection.",
        "Sildenafil specifics (Dec 19/20): headache 15%, flushing 10%, dyspepsia, nasal congestion, blue vision, hypotension, rare NAION, rare priapism. Drop in BP ~8/6 mmHg.",
      ]},
      { t: "h", v: "Newer-generation talking points (Dec 21)" },
      { t: "ul", v: [
        "Avanafil: faster Tmax, higher PDE5:PDE6 ratio → less visual, on-demand 15 min.",
        "Daily tadalafil 5 mg: steady-state, spontaneous sex, LUTS licence, endothelial conditioning hypothesis.",
        "ODT vardenafil, orodispersible sildenafil — no water, bypass some food effect.",
        "Topical / sGC stimulators / PDE5 + NO donors — pipeline; do not invent names.",
      ]},
      { t: "h", v: "NPT monitoring (Dec 20 stem — park it here)" },
      { t: "p", v: "Nocturnal penile tumescence and rigidity (NPTR, RigiScan) records nocturnal erections (usually 3–5/night in REM, lasting 10–20 min, tip rigidity >70% = functional). Indications: suspected psychogenic ED (normal NPT), medico-legal, to document residual nocturnal function after RP, research. Limitations: sleep quality, depression, first-night effect, not a vascular map. Stamp test / snap-gauge are crude bedside alternatives. A positive PDE5 trial plus good morning erections often makes NPT unnecessary." },
      { t: "tip", k: "gold", v: "PDE5i need NO. Nitrates are the one absolute. Tadalafil daily is the urologist's dual ED+LUTS drug. Avanafil is the ‘newer generation’ one-liner for onset." },
    ],
  },
  {
    id: "ed-after-rp",
    topicId: "sexual",
    title: "Erectile dysfunction after radical prostatectomy",
    highYield: true,
    gold: true,
    tags: ["penile rehabilitation", "cavernous nerve", "nerve-sparing"],
    exams: [
      { session: "Jun", year: 2016, marks: "3+3+4", stem: "Hemodynamics and mechanism of penile erection. Management of erectile dysfunction after radical prostatectomy." },
      { session: "Dec", year: 2022, marks: "5", stem: "Components of penile rehabilitation before and after radical prostatectomy." },
    ],
    related: ["erection-hemodynamics", "pde5", "penile-prosthesis"],
    references: [
      "Campbell-Walsh-Wein, Sexual function after pelvic surgery",
      "Mulhall / Montorsi rehabilitation literature",
      "EAU Prostate Cancer + Sexual and Reproductive Health",
      "REINVENT / REACTT tadalafil trials",
    ],
    answer: [
      { t: "h", v: "Why ED happens after RP" },
      { t: "ul", v: [
        "Cavernous-nerve neurapraxia (even with bilateral nerve-sparing) — neuropraxia for 6–24 months; NO drive is lost, PDE5 monotherapy may fail early.",
        "Accessory pudendal artery ligation, venous leak from prolonged flaccidity (smooth-muscle apoptosis, collagen, Peyronie-like shortening 1–3 cm), psychological catastrophising, incontinence, androgen deprivation if given.",
        "Predictors of recovery: age <60, good pre-op IIEF, bilateral nerve-spare, surgeon volume, no ADT, no diabetes/vascular disease. Recovery continues to 24–36 months — do not declare failure at 6 months after nerve-spare.",
      ]},
      { t: "h", v: "Prevention in the operating room" },
      { t: "ul", v: [
        "Patient selection for nerve-spare (oncologic safety first).",
        "Athermal technique near NVB (no energy within 5–7 mm), high anterior release, incremental nerve-spare, preserve accessory pudendals when oncologically safe.",
        "Pre-op counselling and baseline IIEF — rehabilitation starts before the incision (Dec 22).",
      ]},
      { t: "h", v: "Penile rehabilitation — components" },
      { t: "ul", n: true, v: [
        "Goal: keep cavernosal tissue oxygenated and stretched during the neurapraxic window to reduce fibrosis and length loss. Evidence for ‘rehabilitation vs on-demand’ is mixed (REACTT: daily tadalafil improved unassisted erection and stretched length but not the primary IIEF at 9 months after washout). Still standard of care in most centres.",
        "PDE5: tadalafil 5 mg daily starting when the catheter comes out (or at 4–6 weeks) for 6–12 months, plus on-demand 20 mg for sex. If no response by 3–6 months, do not wait — escalate.",
        "Intracavernosal alprostadil (PGE1) 2.5–20 µg, or bimix/trimix, 2–3×/week — works without nerves (cAMP). First in-office test dose. Risk of priapism and fibrosis.",
        "Intraurethral alprostadil (MUSE) — weaker, urethral pain.",
        "Vacuum erection device daily 5–10 min (without ring for rehab; with ring for sex) — best data for length preservation.",
        "Combination VED + PDE5 is pragmatic.",
        "Psychosexual therapy, partner involvement, treat incontinence first (clamps/pads destroy desire).",
        "Salvage: low-intensity shockwave is investigational after RP. Penile implant if unsatisfactory erections at 12–24 months (or earlier if non-nerve-spare and the patient wants certainty). Do not make a 55-year-old wait 3 years in a vacuum.",
      ]},
      { t: "tip", k: "gold", v: "Nerve-spare + time (24 months) + daily tadalafil ± VED ± injection. Implant is treatment, not defeat. Never start the conversation after the catheter comes out — it starts at consent for RP." },
    ],
  },
  {
    id: "vasculogenic-ed",
    topicId: "sexual",
    title: "ED in the 50-year-old diabetic and vasculogenic impotence",
    highYield: true,
    gold: false,
    tags: ["diabetes", "atherosclerosis", "penile Doppler", "ICI"],
    exams: [
      { session: "Dec", year: 2019, marks: "5+5", stem: "Evaluation of erectile dysfunction in 50-year old diabetic patient. Discuss management options for vasculogenic impotence." },
    ],
    related: ["erection-hemodynamics", "pde5", "non-pde5-oral", "penile-prosthesis"],
    references: [
      "EAU Sexual and Reproductive Health",
      "Princeton III / IV cardiac consensus",
      "AUA ED Guideline 2018",
      "Campbell-Walsh-Wein, Evaluation of ED",
    ],
    answer: [
      { t: "p", v: "Diabetes mellitus is the classic mixed vasculogenic + neuropathic + endocrine + psychological model of ED. Prevalence of ED in diabetics is 35–75%, onset 10–15 years earlier, PDE5 response is poorer (50–60% vs 70–80%). ED is a coronary-risk equivalent — the 50-year-old diabetic with ED has silent ischaemia until proven otherwise." },
      { t: "h", v: "Evaluation of the 50-year-old diabetic" },
      { t: "ul", v: [
        "Sexual: IIEF-5, onset gradual vs sudden (sudden suggests psychogenic or drug), morning erections, orgasm, ejaculation (RE common in diabetic autonomic neuropathy), libido (if low, think T / depression / relationship).",
        "CV: Princeton — can he walk a flight of stairs / 4 minutes of Bruce? If not, cardiology before any sex-drug. BP, lipids, smoking, OSA, BMI.",
        "Diabetic control: HbA1c, duration, retinopathy/CKD/neuropathy (stocking-glove, cremasteric, bulbocavernosus reflex), drugs (β-blockers, thiazides, spironolactone, antidepressants).",
        "Exam: femoral/foot pulses, hairless cold feet, Peyronie, testis volume, gynecomastia, phimosis (more common in diabetics — treat before injecting).",
        "Labs: morning total T (and SHBG/free T if borderline), lipids, glucose/HbA1c, Cr; TSH/prolactin if indicated. Do not skip T — hypogonadism coexists and blunts PDE5.",
        "Specialised (not first-line for everyone): penile duplex Doppler after ICI (see below), NPT if litigation/psychogenic question, neurophysiology rarely.",
      ]},
      { t: "h", v: "Penile Doppler — diagnosis of arteriogenic ED (Dec 18 overlap)" },
      { t: "ul", v: [
        "ICI with PGE1 10–20 µg (or bimix). Measure cavernosal PSV, EDV, RI at 5, 10, 15, 20 min.",
        "PSV ≥30–35 cm/s = adequate arterial inflow; <25 cm/s arteriogenic. 25–30 grey zone.",
        "EDV >5 cm/s and RI <0.75–0.8 after a rigid erection should have occurred = veno-occlusive dysfunction. If he never rigidifies, you cannot diagnose a leak (false positive).",
        "Asymmetry suggests unilateral pudendal / accessory pudendal disease.",
        "Selective pudendal angiography only if a young man with pelvic trauma / focal stenosis is a candidate for revascularisation (dorsal artery reimplantation, Michal). Not for the 50-year-old diabetic — his disease is diffuse endothelial.",
      ]},
      { t: "h", v: "Management of vasculogenic ED" },
      { t: "tbl", h: ["Rung", "What", "Note in the diabetic"], r: [
        ["Lifestyle / disease control", "Weight, exercise, stop smoking, HbA1c, BP, statins, CPAP, stop offending drugs", "The only disease-modifying step. Exercise improves PSV."],
        ["Correct T if hypogonadal", "Aim mid-normal; reassess PDE5 at 3 months", "Check PSA/Hct; fertility desire forbids T — use hCG/SERM"],
        ["PDE5i", "Tadalafil 5 mg daily often better than on-demand in diabetics (endothelial, LUTS, spontaneous)", "Start high-end dose; educate on stimulation, 6–8 attempts, empty stomach for sildenafil"],
        ["ICI / MUSE / VED", "PGE1, bimix, trimix; VED if needles refused", "Train in clinic. Autonomic neuropathy → higher priapism vigilance AND higher failure"],
        ["Shockwave (Li-ESWT)", "Low-intensity, vasculogenic responders", "EAU: weak evidence, selected non-responders; not a miracle in long DM"],
        ["Revascularisation", "Young, focal arterial lesion post-trauma", "Contraindicated in diabetic/atherosclerotic — exam answer ‘not this patient’"],
        ["Venous ligation / embolisation", "Highly selected pure leak, young", "High relapse; not for diabetic mixed ED"],
        ["Inflatable penile prosthesis", "Definitive when conservative fails or patient wants certainty", "Higher infection in DM — optimise HbA1c, no-touch, coated implants. Success >90% satisfaction."],
      ]},
      { t: "tip", k: "gold", v: "ED in a 50-year-old diabetic is a cardiology referral wearing a sexual-medicine coat. PDE5 daily, T if low, ICI next, implant when he is ready. Do not offer arterial bypass." },
    ],
  },
  {
    id: "non-pde5-oral",
    topicId: "sexual",
    title: "Non-PDE5 oral agents for erectile dysfunction",
    highYield: false,
    gold: false,
    tags: ["apomorphine", "yohimbine", "trazodone", "PT-141"],
    exams: [
      { session: "Dec", year: 2011, marks: "5+5", stem: "Classify oral agents used in the management of erectile dysfunction. Describe the role of non-PDE5 inhibitor oral drugs in managing erectile dysfunction." },
    ],
    related: ["pde5", "vasculogenic-ed"],
    references: [
      "Campbell-Walsh-Wein, Pharmacotherapy of ED",
      "EAU Sexual and Reproductive Health — on-demand therapies",
      "ISSM",
    ],
    answer: [
      { t: "h", v: "Classification of oral ED drugs" },
      { t: "ul", v: [
        "Peripheral, conditioners of cavernosal smooth muscle: PDE5 inhibitors (first-line).",
        "Central initiators: dopamine agonists (apomorphine SL), melanocortin agonists (bremelanotide / PT-141).",
        "Central conditioners: α2-antagonists (yohimbine), 5-HT modulators (trazodone), testosterone (permissive, not an aphrodisiac in eugonadal men).",
        "Others / obsolete / OTC: ginseng, L-arginine / citrulline, yohimbe bark, Korean red ginseng — evidence weak.",
      ]},
      { t: "tbl", h: ["Drug", "Mechanism", "Role today"], r: [
        ["Apomorphine SL 2–3 mg", "D2 agonist at PVN → oxytocinergic erection pathway. Onset 15–25 min.", "Works best in psychogenic / mild ED. Nausea, yawning, syncope. Inferior to PDE5. Withdrawn in many markets. Mention as the classic non-PDE5 oral."],
        ["Bremelanotide (PT-141) SC — not oral, but exam-adjacent", "MC3/MC4 agonist", "Licensed for HSDD in women in US; ED data exist. Nausea, hypertension."],
        ["Yohimbine 5.4 mg TDS", "Central α2-antagonist, increases NA and possibly NO", "Placebo-level in organic ED; modest in psychogenic. Hypertension, anxiety, tachycardia. Not recommended by EAU as standard."],
        ["Trazodone 50–200 mg nocte", "5-HT2 antagonist / α1 block; priapism is the notorious AE", "May help ED + depression + insomnia. Not a primary ED drug. Counsel priapism."],
        ["Testosterone", "Restores NOS/PDE5 transcription", "Only if documented hypogonadism. Combination with PDE5 in borderline T is evidence-based."],
        ["L-arginine 3–6 g / citrulline", "NO substrate", "Adjunct in mild ED; avoid with PDE5 in uncontrolled nitrate users? Generally safe. Evidence modest."],
        ["Phentolamine oral (Vasomax) / yohimbine combos", "α-block", "Abandoned for efficacy/hypotension."],
        ["Cabergoline / bupropion", "Dopaminergic", "Libido more than erection; hyperprolactinaemia is the cabergoline indication."],
      ]},
      { t: "h", v: "How to answer ‘role of non-PDE5 orals’" },
      { t: "ul", v: [
        "They are not first-line in 2020s guidelines. PDE5 transformed the field because it is effective in organic ED; apomorphine/yohimbine are not.",
        "Niches: PDE5 contraindicated (nitrate-dependent angina — but then sexual activity itself may be contraindicated), PDE5-intolerant, psychogenic ED, hypogonadism (T), depression (trazodone/bupropion chosen for the mood indication).",
        "Do not prescribe yohimbine as monotherapy for diabetic vasculogenic ED.",
        "Future: oral melanocortin, Rho-kinase inhibitors, topical sGC stimulators — one-line horizon.",
      ]},
      { t: "tip", k: "exam", v: "Classify peripheral vs central. Spend marks on apomorphine, yohimbine, trazodone, testosterone. Conclude that non-PDE5 orals are adjuncts, not replacements." },
    ],
  },
  {
    id: "ejaculatory-disorders",
    topicId: "sexual",
    title: "Ejaculatory disorders and classification of premature ejaculation",
    highYield: true,
    gold: false,
    tags: ["PE", "ISSM", "IELT", "retrograde", "anejaculation"],
    exams: [
      { session: "Jun", year: 2014, marks: "3+7", stem: "Enumerate various ejaculatory problems. Describe the role of pharmacotherapy in the management of premature ejaculation." },
      { session: "Jun", year: 2018, marks: "10", stem: "Classify premature ejaculation and describe its management." },
    ],
    related: ["pe-pharma", "anejaculation", "retrograde-ejaculation"],
    references: [
      "ISSM PE Guidelines",
      "EAU Sexual and Reproductive Health",
      "Waldinger / McMahon classification",
      "Campbell-Walsh-Wein, Disorders of ejaculation",
    ],
    answer: [
      { t: "h", v: "Enumerate ejaculatory problems (Jun 14)" },
      { t: "tbl", h: ["Disorder", "Definition"], r: [
        ["Premature ejaculation", "ISSM: IELT ≤1 min lifelong or ≤3 min acquired + lack of control + distress"],
        ["Delayed ejaculation / anejaculation", "Marked delay or absence of ejaculation despite adequate stimulation and erection"],
        ["Retrograde ejaculation", "Orgasm with semen directed to the bladder"],
        ["Anorgasmia", "No orgasm (emission may still occur — rare)"],
        ["Painful ejaculation (odynorgasmia)", "Prostatitis, EDO, Peyronie, antidepressant, post-herniorrhaphy"],
        ["Haematospermia", "Usually benign; SV/prostate/ED stones, inflammation, rarely tumour"],
        ["Anhedonic ejaculation", "Ejaculation without pleasure"],
        ["Post-orgasmic illness syndrome (POIS)", "Flu-like after orgasm — rare"],
        ["Low-volume / aspermia", "See infertility cards"],
        ["Orgasmic headache, post-orgasmic pain", "Mention"],
      ]},
      { t: "h", v: "Classify PE (Jun 18) — Waldinger four types" },
      { t: "tbl", h: ["Type", "IELT", "Onset", "Management emphasis"], r: [
        ["Lifelong (primary)", "≤1 min from first sexual experiences", "Neurobiological 5-HT", "SSRI daily or dapoxetine + topical; psychoeducation"],
        ["Acquired (secondary)", "Previously normal, now ≤3 min", "ED, prostatitis, thyroid, relationship", "Treat the cause; PDE5 if ED"],
        ["Natural variable", "Inconsistent, situational", "Normal variation", "Reassurance, not drugs first"],
        ["Subjective / premature-like", "IELT in the normal range (3–6 min) but the man is distressed", "Cognitive", "CBT, not SSRI as first move"],
      ]},
      { t: "p", v: "DSM-5 / ICD-11: about 1 min, 75% of occasions, 6 months, distress. Do not medicalise natural-variable PE." },
      { t: "h", v: "Management of PE — condensed (full pharmacology on the infertility PE card)" },
      { t: "ul", v: [
        "Behavioural: start–stop (Semans), squeeze (Masters & Johnson), pelvic-floor PT, condom, pre-coital masturbation. Best combined with drugs in lifelong PE.",
        "Pharmacologic first-line (EAU): on-demand dapoxetine 30–60 mg, or daily SSRI (paroxetine 10–40 mg most effective), or topical lidocaine–prilocaine. Clomipramine on-demand is an alternative.",
        "PDE5 if ED coexists — always treat ED first.",
        "Tramadol on-demand — second-line, dependence risk.",
        "Do not cut the dorsal nerve. Hyaluronic acid glans injection is investigational.",
        "Couple therapy when distress or avoidance dominates.",
      ]},
      { t: "tip", k: "gold", v: "Lifelong vs acquired vs natural-variable vs subjective. Drugs for the first two. Dapoxetine or paroxetine or topical. Treat ED first." },
    ],
  },
  {
    id: "anejaculation",
    topicId: "sexual",
    title: "Anejaculation — etiology, evaluation, treatment",
    highYield: true,
    gold: false,
    tags: ["anejaculation", "PVS", "eeJ", "SCI", "RPLND"],
    exams: [
      { session: "Jun", year: 2019, marks: "3+3+4", stem: "Etiology, evaluation and treatment of anejaculation." },
    ],
    related: ["retrograde-ejaculation", "ejaculatory-disorders", "rplnd", "sperm-retrieval"],
    references: [
      "Campbell-Walsh-Wein, Anejaculation and SCI fertility",
      "ISSM / EAU Sexual and Reproductive Health",
      "Ohl / Brackett PVS and EEJ series",
    ],
    answer: [
      { t: "p", v: "Anejaculation is the complete absence of antegrade and retrograde ejaculation (no sperm in post-orgasm urine) despite possible orgasm. It is failure of emission (sympathetic T10–L2, hypogastric nerve, deposition of semen into the posterior urethra) and/or of expulsion (pudendal somatic, rhythmic bulbospongiosus). Distinguish from RE (sperm in urine), delayed ejaculation, anorgasmia, and azoospermia with normal ejaculate." },
      { t: "h", v: "Etiology" },
      { t: "tbl", h: ["Group", "Examples"], r: [
        ["Neurogenic — spinal", "SCI (complete above T10 often loses emission; T10–L2 lesions hit the emission centre; sacral lesions hit expulsion but emission may persist), spina bifida, MS, transverse myelitis"],
        ["Neurogenic — peripheral / iatrogenic", "RPLND (even nerve-spare ~5–15% RE/anejaculation; non-spare historically 80%+), aortoiliac surgery, colorectal resection, diabetic autonomic neuropathy, retroperitoneal tumour/fibrosis"],
        ["Pharmacologic", "α-blockers (silodosin), antihypertensives, antipsychotics, SSRIs (delayed more than absent), antiandrogens"],
        ["Anatomic / obstructive", "Complete EDO, congenital SV/vas aplasia — these are aspermia/OA, not true neurogenic anejaculation, but present as dry orgasm"],
        ["Endocrine / psychogenic", "Severe hypogonadism; anorgasmia from anxiety, unique arousal pattern (idiosyncratic masturbation), relationship conflict — orgasm absent rather than emission failed"],
      ]},
      { t: "h", v: "Evaluation" },
      { t: "ul", v: [
        "History: SCI level, RPLND, drugs, orgasm present or not, nocturnal emissions, diabetes.",
        "Post-orgasm / post-stimulation urine for sperm — splits RE vs anejaculation.",
        "Exam: perineal sensation, BCR, cremasteric, anal tone (sacral integrity), vas palpable.",
        "T, FSH; TRUS if OA phenotype; MRI spine if unexplained.",
        "If fertility is the goal, do not spend months on exotic neurophysiology — move to PVS/EEJ/SSR.",
      ]},
      { t: "h", v: "Treatment" },
      { t: "ul", n: true, v: [
        "Stop the drug; switch silodosin → tamsulosin/alfuzosin if LUTS allow; imipramine/pseudoephedrine trial (helps RE more than true anejaculation).",
        "Psychogenic delayed ejaculation: sex therapy, stop SSRI or add bupropion, change stimulation pattern.",
        "Fertility — stepwise in SCI (Brackett): (1) Penile vibratory stimulation (Ferticare / Viberect) at the frenulum if the reflex arc T10–S4 is intact — best if lesion ≥T10. Ejaculation in 80% of T10-and-above complete injuries. Watch autonomic dysreflexia (nifedipine/nitro paste ready). (2) Midodrine 5–15 mg can convert PVS failures. (3) Electroejaculation (SE-II probe, general or sedation, stepwise voltage) — success >90% including lower lesions; rectal injury/AD risk. (4) If semen quality from PVS/EEJ is poor (SCI semen is often OAT, high ROS) or EEJ unavailable → PESA/TESA/TESE + ICSI.",
        "Post-RPLND: PVS often fails (peripheral sympathetic interruption); EEJ or SSR.",
        "Always freeze retrieved sperm. IUI possible if antegrade sample is decent after PVS; otherwise ICSI.",
      ]},
      { t: "tip", k: "gold", v: "Urine pellet splits RE from anejaculation. SCI fertility ladder: PVS → EEJ → surgical sperm. Have an AD protocol on the wall." },
    ],
  },
  {
    id: "transgender-mtf",
    topicId: "sexual",
    title: "Gender-affirming surgery — legal status in India and male-to-female procedure",
    highYield: true,
    gold: false,
    tags: ["transgender", "NALSA", "vaginoplasty", "WPATH"],
    exams: [
      { session: "Jun", year: 2021, marks: "2+3+3+2", stem: "A 24-year-male desires sex change surgery. What is the legal status of his demand at present in India? What will be the work-up required? How will you prepare such a person for surgery? Briefly describe the surgical procedure of male to female conversion." },
    ],
    related: ["transgender-ftm", "sperm-retrieval"],
    references: [
      "NALSA v Union of India (2014) 5 SCC 438",
      "Transgender Persons (Protection of Rights) Act 2019 and Rules 2020",
      "WPATH Standards of Care version 8",
      "Campbell-Walsh-Wein / EAU — gender-affirming surgery chapters",
      "ASRM fertility preservation in gender diverse people",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Tone", v: "This is a clinical and legal exam answer. Use gender-affirming language. No jokes. Quote NALSA and the 2019 Act. Surgery is not a legal prerequisite for identity recognition." },
      { t: "h", v: "Legal status in India (2 marks)" },
      { t: "ul", v: [
        "NALSA (2014): transgender persons have the right to self-identified gender (male, female, or third gender); Articles 14, 15, 19, 21. Hijra/trans communities recognised. Directed welfare measures. Surgery / hormones cannot be a precondition for legal gender recognition (self-identification principle).",
        "Transgender Persons (Protection of Rights) Act 2019 and Rules 2020: prohibition of discrimination in education, employment, healthcare, housing. Identification via a certificate of identity from the District Magistrate (Rules: based on self-declaration; change to male/female in records after surgery is an additional, criticised, pathway — mention the tension with NALSA).",
        "There is no criminal prohibition on gender-affirming surgery performed with informed consent by a competent adult. Conversion therapy is condemned by professional bodies; the Act forbids compelling medical procedures.",
        "Practical hospital pathway: institutional ethics / transgender health board, documented multidisciplinary assessment, not a ‘court order for surgery’ (a common wrong answer). Age of majority 18; parental/GMCD pathways for adolescents are ethically and legally more restricted — this stem is a 24-year-old.",
        "IPC / BNS sexual-offence language has lagged behind NALSA; do not let that derail the surgical consent discussion.",
      ]},
      { t: "h", v: "Work-up (3 marks)" },
      { t: "ul", v: [
        "Confirm persistent gender incongruence (ICD-11) / gender dysphoria (DSM-5-TR) by a qualified mental-health professional experienced in gender care (WPATH SOC8: assessment, not a ‘test’ the patient must pass). Screen depression, autism, psychosis, trauma — treat in parallel, do not use as a blanket veto.",
        "Capacity and informed consent: irreversible infertility, sexual function, complications, need for dilatation, cancer screening of residual organs, financial/social support.",
        "Medical: BMI, smoking (stop 3 months — flap/graft killer), HIV/viral serology, diabetes, thrombosis risk, prostate (remains in situ in MtoF — lifelong PSA discussion if family history), testicular exam.",
        "Endocrine: feminising hormones typically 12+ months before gonadectomy (estradiol ± anti-androgen: cyproterone, spironolactone, GnRH analogue). Check T suppression, E2 levels, prolactin, VTE risk, liver.",
        "Fertility preservation before hormones or orchidectomy: semen cryopreservation (first-line), or TESE if already suppressed (see infertility banking card). Document offer even if declined.",
        "Photography, baseline IIEF not required; pelvic exam not needed pre-MtoF. Urology + plastic surgery + psychiatry + endocrinology + social work = MDT.",
      ]},
      { t: "h", v: "Preparation for surgery (3 marks)" },
      { t: "ul", v: [
        "SOC8: typically ≥12 months of hormones unless medically contraindicated; living in the affirmed gender role is no longer a rigid 12-month ‘real-life test’ but social support is assessed.",
        "Smoking cessation, weight optimisation, VTE prophylaxis plan (hormones often paused peri-op — local protocol).",
        "Bowel prep if intestinal vaginoplasty planned; urology consent for prostate/urethra; stoma therapist if that route.",
        "Hair removal (electrolysis/laser) of penile-scrotal skin that will become neovagina — reduces intra-vaginal hair.",
        "Mental-health letter(s) per institutional policy; two-assessor model still used in many Indian centres.",
        "Post-op dilatation teaching, catheter/stent counselling, time off work, a safe house to recover (many patients are socially vulnerable — this is part of surgical planning).",
      ]},
      { t: "h", v: "Male-to-female genital surgery — salient steps (2 marks)" },
      { t: "ul", n: true, v: [
        "Penile-inversion vaginoplasty (gold-standard first-line in most centres): perineal approach. Bilateral orchidectomy. Penile disassembly: urethra spatulated and shortened to a female position, glans reduced to a neoclitoris on the dorsal neurovascular bundle (erotic sensation), corpora cavernosa excised (leave a small stump to avoid a dished mons). Penile skin (and often a scrotal full-thickness graft or peritoneal flap if length short) inverted to line the neovaginal cavity dissected between rectum and prostate (Denonvilliers). Labia majora from scrotum, minora from penile skin. Pack, catheter, drain.",
        "Alternatives / adjuncts: robotic peritoneal flap (Davydov-type) for depth; ileal or sigmoid vaginoplasty if revision or insufficient skin (mucus, colitis, diversion colitis, cancer risk lifelong).",
        "Ancillary: breast augmentation, facial feminisation, thyroid chondroplasty, voice surgery — usually staged, not same day.",
        "Complications to name: haemorrhage, rectal injury, neovaginal stenosis (dilatation for life), fistula (recto-neovaginal, urethro-neovaginal), flap necrosis, clitoral necrosis/insensitivity, spraying stream, VTE, residual erectile tissue, prostate cancer in remnants (rare).",
        "Follow-up: dilatation protocol, prostate care, neovaginal speculum exams, hormones lifelong after orchidectomy (estradiol monotherapy).",
      ]},
    ],
  },
  {
    id: "transgender-ftm",
    topicId: "sexual",
    title: "Gender-affirming surgery — evaluation and female-to-male steps",
    highYield: false,
    gold: false,
    tags: ["transgender", "phalloplasty", "metoidioplasty", "WPATH"],
    exams: [
      { session: "Jun", year: 2019, marks: "4+6", stem: "Evaluation for transgender surgery. Describe salient steps for female to male transgender surgery." },
    ],
    related: ["transgender-mtf", "penile-prosthesis"],
    references: [
      "WPATH SOC8",
      "NALSA 2014; Transgender Persons Act 2019",
      "EAU / Campbell gender-affirming surgery",
      "Monstrey / Chen phalloplasty series",
    ],
    answer: [
      { t: "h", v: "Evaluation (shared with MtoF card — emphasise differences)" },
      { t: "ul", v: [
        "MDT confirmation of gender incongruence, capacity, social support, mental-health stability. Legal: NALSA self-ID; 2019 Act certificate pathway.",
        "Fertility: oocyte or embryo cryopreservation before testosterone or hysterectomy/oophorectomy. Testosterone does not reliably contracept — counsel pregnancy risk if uterus in situ.",
        "Masculinising hormones: testosterone cypionate/enanthate/gel. Monitor Hct (erythrocytosis), lipids, liver, BP. Voice, clitoromegaly, body hair, amenorrhoea expected. 12+ months typical before genital surgery; chest surgery may precede that.",
        "Smoking, BMI (<30–35 preferred for free flap), diabetes, pelvic exam / cervical screening while uterus/cervix remain, breast imaging per residual tissue.",
        "Decide goals explicitly: chest only vs metoidioplasty vs phalloplasty ± urethral lengthening ± vaginectomy ± hysterectomy/BSO ± implant/scrotoplasty. Each add-on multiplies fistula risk. Do not bundle what the patient does not want.",
      ]},
      { t: "h", v: "Salient steps — FtoM (usually staged)" },
      { t: "tbl", h: ["Stage", "Procedure", "Notes"], r: [
        ["1. Chest", "Double-incision mastectomy + free nipple graft, or periareolar if small", "Most requested operation. Haematoma, nipple loss, dog-ears, need for revision contouring."],
        ["2. Reproductive", "Total hysterectomy ± BSO (lap/robotic), optional vaginectomy (colpectomy)", "Cancer risk reduction vs hormone/osteoporosis trade-off if ovaries removed. Vaginectomy if urethral lengthening planned (reduces fistula from vaginal remnant)."],
        ["3a. Metoidioplasty", "Release of hormonally enlarged clitoris (chordee release, urethral hook-up with labial flaps, scrotoplasty from labia majora ± testicular prostheses)", "Standing micturition possible in a majority; length typically 4–6 cm; no free flap; preserves erotic sensation; penetration often limited. Lower morbidity than phalloplasty."],
        ["3b. Phalloplasty", "Tube-in-tube free flap: radial forearm (RFFF, gold standard sensation via coaptation of lateral/medial antebrachial to dorsal clitoral/pudendal) or anterolateral thigh (ALT, more bulk, variable sensation) or abdominal pedicled flaps. Clitoris buried at the base for sensation. Anastomoses to femoral/deep inferior epigastric vessels. Urethral lengthening (pars fixa from labia + pars pendula from flap). Scrotoplasty. Later (6–12 months) inflatable or malleable implant and testicular prostheses once sensation and urethra stable.", "Standing void ~70–80% after revisions. Complications: flap loss, urethral fistula (30–50% before revisions), stricture, donor-site morbidity (RFFF graft), implant erosion (higher than cis-male IPP because no tunica)."],
      ]},
      { t: "p", v: "Do not perform phalloplasty and implant in one sitting. Urethral complications are the dominant morbidity — some patients elect a flap phallus without urethral lengthening and continue to sit to void. That is a valid, lower-morbidity choice and should be in the answer." },
      { t: "tip", k: "exam", v: "Evaluation = MDT + hormones + fertility + smoking/BMI. FtoM steps = chest, hysterectomy/BSO, metoidioplasty vs RFFF/ALT phalloplasty, delayed implant. Quote fistula rates honestly." },
    ],
  },
  {
    id: "priapism",
    topicId: "sexual",
    title: "Priapism — definition, types, diagnosis, treatment",
    highYield: true,
    gold: true,
    tags: ["ischaemic priapism", "stuttering", "sickle cell", "shunt", "phenylephrine"],
    exams: [
      { session: "Dec", year: 2021, marks: "5+5", stem: "Management of: Priapism in a 26 year old male. Swelling and redness of a hemi-scrotum in a 17 year old male." },
      { session: "Jun", year: 2020, marks: "2+2+2+2+2", stem: "Priapism: definition, causes, types, diagnosis, treatment." },
      { session: "Dec", year: 2020, marks: "2+8", stem: "What is stuttering priapism? Describe the surgical options in the management of ischemic priapism." },
      { session: "Dec", year: 2019, marks: "2+4+4", stem: "Discuss mechanism, evaluation and treatment of priapism in sickle cell disease." },
      { session: "Dec", year: 2014, marks: "2+(4+4)", stem: "Define priapism. Discuss diagnosis, and outline of management of priapism." },
    ],
    related: ["pde5", "acute-scrotum", "penile-prosthesis", "erection-hemodynamics"],
    references: [
      "AUA/SMSNA Priapism Guideline 2021/22",
      "EAU Sexual and Reproductive Health — priapism",
      "ISSM",
      "Campbell-Walsh-Wein, Priapism",
      "Burnett stuttering-priapism PDE5 protocol",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "Definition 1 · Types 2 · Ischaemic vs non-ischaemic blood gas 2 · 26-year-old algorithm (aspiration + phenylephrine → shunt → implant) 3 · Stuttering / sickle 2. The 17-year-old hemi-scrotum is torsion until proven otherwise — do not let priapism eat the whole paper." },
      { t: "h", v: "Definition" },
      { t: "p", v: "Priapism is a persistent penile erection that continues hours beyond, or is unrelated to, sexual stimulation. Practical emergency threshold for ischaemic priapism: ≥4 hours. The glans and spongiosum are typically soft in ischaemic cavernosal priapism; pain is the clinical hallmark of ischaemia." },
      { t: "h", v: "Types and causes" },
      { t: "tbl", h: ["Type", "Physiology", "Causes", "Urgency"], r: [
        ["Ischaemic (low-flow, veno-occlusive) — 95%", "Compartment syndrome of the cavernosa. Hypoxia, hypercarbia, acidosis. Smooth-muscle death by 24–48 h.", "Idiopathic; ICI (PGE1, papaverine, trimix); PDE5 + cocaine; antipsychotics (trazodone, chlorpromazine), anticoagulants, TPN (lipid), haematologic (sickle, CML, G6PD, thalassaemia), malignancy (pelvic, bladder, prostate), toxins (black widow, scorpion)", "Emergency — time is smooth muscle"],
        ["Non-ischaemic (high-flow, arterial)", "Unregulated arterial inflow, usually a cavernosal-artery laceration into a sinusoidal fistula. Blood is oxygenated; not painful.", "Perineal/penile trauma (straddle, kick), needle injury after ICI, rarely congenital", "Urgent evaluation, not a 4-hour emergency"],
        ["Stuttering (recurrent ischaemic)", "Repeated self-limiting ischaemic episodes, often nocturnal, in sickle-cell disease or idiopathic", "Sickle, idiopathic, neurological", "Prevent conversion to a major episode + treat each episode as ischaemic if ≥4 h"],
      ]},
      { t: "h", v: "Diagnosis" },
      { t: "ul", v: [
        "History: duration, pain, trauma, ICI/drugs, sickle, haematology, prior episodes. Exam: rigid painful cavernosa + soft glans = ischaemic; partially tumescent, painless, perineal bruise = high-flow.",
        "Cavernosal blood gas is the discriminator (AUA/EAU): ischaemic ≈ pO2 <30 mmHg, pCO2 >60, pH <7.25 (dark blood). Non-ischaemic ≈ arterial (pO2 >90, pH 7.4, bright). Colour Doppler: ischaemic = absent or minimal cavernosal flow; high-flow = high PSV, often a blush/fistula at the injury.",
        "FBC, reticulocytes, sickle solubility/Hb electrophoresis if not known, smear (CML), urine toxicology as indicated. Do not delay aspiration for an MRI. MRI later can estimate non-viable muscle if presentation is delayed (>24–48 h) and helps counsel immediate prosthesis.",
      ]},
      { t: "flow", title: "Ischaemic priapism — 26-year-old", nodes: [
        { id: "a", kind: "start", label: "Painful erection ≥4 h. Confirm ischaemic (gas ± Doppler)", to: ["b"] },
        { id: "b", kind: "action", label: "Analgesia, IV, stop offending drug, treat sickle in parallel (O2, hydrate, alkalinise, exchange transfusion — but do not wait on transfusion before decompression)", to: ["c"] },
        { id: "c", kind: "action", label: "Aspiration ± irrigation (19–21 G into lateral corpora, 3 / 9 o'clock, under LA; milking). Goal: bright blood and detumescence", to: ["d"] },
        { id: "d", kind: "action", label: "Intracavernosal phenylephrine 100–200 µg aliquots q3–5 min, max ~1 mg in 1 h. Monitor BP/ECG (hypertension, reflex bradycardia). Dilute 1 mg in 10 mL.", to: ["e"] },
        { id: "e", kind: "decision", label: "Detumescence?", to: ["f", "g"] },
        { id: "f", kind: "end", label: "Observe. Counsel ED risk. Stuttering prevention if recurrent" },
        { id: "g", kind: "decision", label: "Duration still <24 h and muscle likely viable?", to: ["h", "i"] },
        { id: "h", kind: "action", label: "Distal shunt (Winter / Ebbehoj / T-shunt ± tunnelling). If fails → proximal (Quackels corporospongiosal, Grayhack saphenous)", to: ["j"] },
        { id: "i", kind: "action", label: "Delayed presentation (>36–48 h) or failed shunts: immediate or delayed malleable implant (easier planes now; later IPP conversion)", to: ["j"] },
        { id: "j", kind: "end", label: "Follow-up ED, fibrosis, implant counselling" },
      ]},
      { t: "h", v: "Surgical options in ischaemic priapism (Dec 20)" },
      { t: "tbl", h: ["Shunt", "How", "Pearl"], r: [
        ["Winter", "Trucut / biopsy needle glans → corpora, several cores", "Bedside, often insufficient"],
        ["Ebbehoj", "Scalpel blade through glans into each corpus, twist", "Larger channel"],
        ["Al-Ghorab", "Open excision of a disc of tunica at the glans–corporal tips", "More definitive distal"],
        ["T-shunt (Brant/Burnett) ± Burnett tunnelling", "Glans stab into corpus, then rotate 90° (‘T’); Hegar dilators tunnel proximally", "Contemporary distal of choice; tunnelling for >24 h"],
        ["Quackels / Sacher", "Open corporospongiosal anastomosis along the midshaft", "Proximal; urethral fistula risk"],
        ["Grayhack", "Corpora to saphenous vein", "Historical proximal"],
        ["Barry", "Corpora to dorsal vein", "Rarely used"],
        ["Immediate prosthesis", "Malleable (or IPP) into fibrotic/non-viable corpora", "AUA option when duration long / MRI non-viable / shunt failed. Easier now than delayed into wood-hard corpora. Infection counselling."],
      ]},
      { t: "h", v: "Non-ischaemic management" },
      { t: "p", v: "Ice, time (50–60% close). Doppler localisation. Selective arterial embolisation with absorbable gel foam (temporary) first-line if persists; microcoil if recurs. Open ligation of the fistula last. Do not inject phenylephrine into a high-flow priapism as the primary plan — it is not a compartment syndrome. ED risk after embolisation is low with temporary agents." },
      { t: "h", v: "Stuttering priapism" },
      { t: "ul", v: [
        "Definition: recurrent self-limiting ischaemic episodes, often nocturnal, lasting <4 h, with risk of a major episode.",
        "Acute episode ≥4 h: treat as ischaemic.",
        "Prevention: (1) treat sickle aggressively (hydroxyurea, transfusion programme, avoid dehydration); (2) self-injection kit of phenylephrine for home if reliable; (3) anti-androgen / GnRH analogue / 5-ARI to suppress nocturnal erections — fertility and bone cost, not for a boy wanting paternity; (4) paradoxical daily PDE5 (sildenafil/tadalafil taken when flaccid, Burnett) — restores PDE5 regulation of cGMP, RCT-level signal in idiopathic/sickle; never during an acute ischaemic erection; (5) ketoconazole + prednisone short courses; (6) terbutaline oral evidence weak.",
      ]},
      { t: "h", v: "Sickle-cell priapism (Dec 19)" },
      { t: "p", v: "Mechanism: low PO2, acidosis and stasis polymerise HbS → sickling in sinusoids → vicious veno-occlusion. Often stuttering from adolescence. Evaluation: gas + Doppler as above, CBC, retic, HbS %, infection screen. Treatment: ABC, O2, aggressive IV hydration, analgesia, alkalinisation, urgent urologic decompression (aspiration + phenylephrine) in parallel with haematology (simple or exchange transfusion aiming HbS <30%). Transfusion alone is not a substitute for compartment release. Avoid ice-cold packs that may worsen sickling. Hydroxyurea and transfusion programmes for secondary prevention; PDE5 daily when flaccid; consider implant after failed shunts / established fibrosis. Fertility and ED counselling — recurrent sickle priapism is a leading cause of ED in young men in endemic regions." },
      { t: "h", v: "The other half of Dec 21 — 17-year-old red swollen hemi-scrotum" },
      { t: "p", v: "Treat as testicular torsion until proven otherwise (peak 12–18 years). History of sudden pain, nausea, high-riding testis, absent cremasteric, horizontal lie. Doppler only if it does not delay theatre. Explore, detorse, bilateral orchidopexy if viable; orchidectomy if infarcted, still pexy the contralateral. Differential: torsion of appendix testis (blue-dot, less systemic), epididymo-orchitis (sexually active — but 17-year-old still gets a scrotal explore if any doubt), incarcerated hernia, idiopathic scrotal oedema, Fournier (toxic, older, diabetic — not this stem), trauma, tumour with haemorrhage, HSP. See acute-scrotum card." },
      { t: "tip", k: "gold", v: "Ischaemic priapism is a compartment syndrome: gas, aspirate, phenylephrine, distal shunt, implant if late. High-flow is Doppler + embolise. Stuttering: prevent, and never give PDE5 during an acute episode. The 17-year-old scrotum is torsion." },
    ],
  },
];
