import type { Master } from "../types";

export const stones: Master[] = [
  {
    id: "caox-citrate",
    topicId: "stones",
    title: "Calcium oxalate stone formation and citrate / pH therapy",
    highYield: true,
    gold: true,
    tags: ["CaOx", "citrate", "Randall", "nucleation"],
    exams: [
      {
        session: "Dec",
        year: 2013,
        marks: "4+3+3",
        stem: "What is the process of formation of calcium oxalate stones? Describe the principles of citrate therapy and pH monitoring in treating patients with recurrent stones.",
      },
    ],
    related: ["inhibitors-promoters", "metabolic-evaluation", "acid-base-rta"],
    references: [
      "Campbell-Walsh-Wein — Urinary Lithiasis: Etiology, Epidemiology, and Pathogenesis",
      "EAU Urolithiasis",
      "Smith's Textbook of Endourology",
    ],
    answer: [
      { t: "h", v: "Process of CaOx stone formation" },
      { t: "ul", n: true, v: [
        "Supersaturation of urine with CaOx (relative supersaturation RSS >1) — driven by high Ca, high oxalate, low volume, low citrate. Oxalate molarity is a stronger driver than calcium (hence enteric hyperoxaluria is so lithogenic).",
        "Nucleation: homogeneous (rare) or heterogeneous on Randall’s plaque (interstitial hydroxyapatite at the papilla, from the basolateral side of the thin limb — Evan/Coe) or on Bellini-duct plugs (hyperoxaluria, distal RTA, brushite). Crystal–cell adhesion (annexin, hyaluronan, osteopontin as a double agent).",
        "Growth and aggregation: promoted by low urine output, bursts of supersaturation (post-prandial oxalate), and reduced electrostatic repulsion when citrate/magnesium are low.",
        "Retention: a nidus attached at a papilla grows into a fixed stone; free crystals would otherwise wash out (the ‘free-particle’ vs ‘fixed-particle’ debate — both operate).",
        "Two mineral phases: CaOx monohydrate (COM, whewellite, hard, black) and dihydrate (COD, weddellite, envelope crystals). Mixed CaOx–apatite common.",
      ]},
      { t: "h", v: "Citrate therapy — principles" },
      { t: "ul", v: [
        "Citrate complexes urinary calcium (soluble Ca-citrate) → lowers ionic Ca and CaOx/CaP RSS. It also inhibits aggregation and growth (crystal-surface poison).",
        "Alkali load: citrate metabolised to HCO3 → raises urine pH (useful for uric acid and cystine; caution in CaP / brushite / struvite where pH >6.5 promotes apatite).",
        "Intracellularly, alkali increases proximal citrate excretion (NaDC1 down) — so the urine citrate rise is more than the ingested citrate filtered.",
        "K-citrate preferred over Na-citrate (sodium load raises urine Ca). Typical 30–60 mEq/d in 2–3 doses, titrate to urine citrate >400 mg/d and pH 6.0–6.5 for CaOx/uric acid. Liquid or wax-matrix tablets.",
        "Indications: hypocitraturia, dRTA, chronic diarrhoea, thiazide-induced hypocitraturia, gouty diathesis / uric acid, cystine (urine pH 7–7.5), residual fragments after SWL.",
        "Monitor: 24-h citrate, Na, K, Ca, pH; serum K. Overshoot pH >7 in a CaP former is iatrogenic stone disease.",
      ]},
      { t: "h", v: "pH monitoring" },
      { t: "ul", v: [
        "Spot pH diary (electronic meter, not nitrazine paper if you can avoid it) fasting and post-prandial. 24-h mean pH.",
        "Targets: uric acid 6.0–6.5; cystine 7.0–7.5; CaOx ~6.0; never push >6.5 if the stone is brushite/apatite.",
        "Acid load (cranberry, betaine) has little role except in rare struvite adjuncts — prevention of struvite is antibiotics + clearance, not acidification (acetohydroxamic acid is historical).",
      ]},
      { t: "tip", k: "gold", v: "CaOx needs supersaturation, a Randall plaque and time. Citrate is a chelator plus alkali; potassium salt, pH 6.0–6.5, do not alkalinise a brushite former." },
    ],
  },
  {
    id: "inhibitors-promoters",
    topicId: "stones",
    title: "Inhibitors and promoters of urinary crystal formation",
    highYield: true,
    gold: false,
    tags: ["citrate", "osteopontin", "Tamm-Horsfall", "oxalate"],
    exams: [
      { session: "Dec", year: 2014, marks: "10", stem: "Inhibitors and promoters of crystal formation in urinary tract." },
      {
        session: "Jun",
        year: 2016,
        marks: "3+3+4",
        stem: "What are the inhibitors and promoters of crystal formation in urinary tract? How will you investigate a case of recurrent stone former?",
      },
    ],
    related: ["caox-citrate", "metabolic-evaluation"],
    references: ["Campbell Lithiasis pathogenesis", "EAU Urolithiasis"],
    answer: [
      { t: "tbl", h: ["", "Small ions / molecules", "Macromolecules"], r: [
        ["Inhibitors", "Citrate (Ca chelation), magnesium (complexes oxalate), pyrophosphate, zinc, phytate", "Osteopontin (uropontin), Tamm–Horsfall/uromodulin (inhibits aggregation if not polymerised by uric acid), bikunin, nephrocalcin, urinary prothrombin fragment 1, GAGs (heparan, chondroitin), calgranulin"],
        ["Promoters / drivers of RSS", "Calcium, oxalate, sodium (hypercalciuria via natriuresis), urate (salts out CaOx — epitaxy / adsorption), phosphate, low volume, high pH for CaP, low pH for uric acid/cystine, ammonium for struvite", "Matrix (uromodulin when aggregated), nanobacteria (historical), Randall plaque apatite, bacteria (urease)"],
      ]},
      { t: "p", v: "Osteopontin and THP are context-dependent: THP inhibits aggregation in health and can form a matrix nidus when precipitated. Uric acid promotes CaOx by adsorbing inhibitors and by heterogeneous nucleation." },
      { t: "h", v: "Investigating the recurrent stone former" },
      { t: "p", v: "See metabolic-evaluation master: stone analysis, two 24-h urines on home diet, serum Ca/PTH if Ca high, RTA screen, imaging for anatomic causes." },
      { t: "tip", k: "gold", v: "Citrate, magnesium, pyrophosphate, THP, osteopontin inhibit. Ca, oxalate, urate, volume contraction, urease promote. Recurrent = two 24-h urines plus a stone analysis." },
    ],
  },
  {
    id: "metabolic-evaluation",
    topicId: "stones",
    title: "Metabolic evaluation of urolithiasis — adult, child, hyperparathyroidism, hyperuricosuria",
    highYield: true,
    gold: true,
    tags: ["24-hour urine", "PTH", "hypercalciuria", "first-time"],
    exams: [
      { session: "Dec", year: 2018, marks: "10", stem: "Metabolic evaluation of urolithiasis." },
      {
        session: "Dec",
        year: 2021,
        marks: "4+4+2",
        stem: "Risk factors for calcium renal stones. Investigations in a case suspected to have primary hyperparathyroidism. Management of hyperuricosuria.",
      },
      { session: "Jun", year: 2014, marks: "5+5", stem: "When do you suspect hyperparathyroidism in a patient? How would you investigate such a patient?" },
      {
        session: "Dec",
        year: 2011,
        marks: "4+6",
        stem: "Describe the metabolic evaluation recommended in a 30 years old, first time renal stone former. What additional investigations would be required if the patient was 5 years old?",
      },
    ],
    related: ["caox-citrate", "hyperoxaluria", "uric-acid-radiolucent", "hyperparathyroidism-stones"],
    references: [
      "EAU Urolithiasis — metabolic work-up",
      "AUA Medical Management of Kidney Stones",
      "Campbell — Evaluation of the stone former",
    ],
    answer: [
      { t: "h", v: "Who gets a full work-up" },
      { t: "ul", v: [
        "All recurrent, all children, all solitary kidneys, all CKD/transplant, all non-CaOx (uric, cystine, struvite, brushite), all family history / bone disease / RTA / bowel disease / bariatric, occupational airline/military, patient preference after a first CaOx stone.",
        "First-time uncomplicated adult CaOx: at least stone analysis, basic serum (Cr, Ca, urate, HCO3, K), and a conversation about fluid/salt/protein. EAU now leans toward offering 24-h urine even after the first stone — justify either way.",
      ]},
      { t: "h", v: "30-year-old first-time former (Dec 11)" },
      { t: "ul", v: [
        "History: diet (salt, animal protein, spinach/nuts/tea, vitamin C megadose), fluid, occupation, bowel (IBD, bypass), drugs (topiramate, acetazolamide, protease inhibitors, triamterene, atazanavir, ceftriaxone, silica antacids), gout, family, UTI.",
        "Labs: serum Cr, electrolytes, Ca (repeat if high), phosphate, urate, HCO3, albumin, PTH if Ca high-normal/high, vitamin D. Urinalysis + pH + culture. Stone analysis (FTIR/XRD).",
        "Imaging: NCCT or KUB+US to document residual / anatomic (PUJO, calyceal diverticulum, horseshoe).",
        "Optional but high-yield: one or two 24-h urines ≥4 weeks after the acute episode, on habitual diet: volume, Cr (completeness), Ca, oxalate, citrate, uric acid, Na, K, Mg, phosphate, urea (protein), pH. Calculate supersaturation if the lab offers it.",
      ]},
      { t: "h", v: "Additional if the patient is 5 years old" },
      { t: "ul", v: [
        "All first-time children are high-risk: full 24-h (or spot Ca/Cr, oxalate/Cr if not toilet-trained) + serum + stone analysis + anatomic imaging.",
        "Genetic: cystinuria (urine cyanide-nitroprusside / amino acids), primary hyperoxaluria (urine oxalate very high, genetic AGXT/GRHPR/HOGA1), Dent (CLCN5, OCRL — LMW proteinuria, hypercalciuria), Bartter, dRTA, xanthinuria, APRT deficiency (2,8-DHA).",
        "Immobilisation, ketogenic diet, furosemide in neonates, UTI/struvite, metabolic syndrome rare at 5, congenital anomalies (PUJO, megaureter, PUV, bladder exstrophy).",
        "Paediatric dietitian; avoid thiazides as first move; high fluid, citrate.",
      ]},
      { t: "h", v: "Risk factors for calcium stones (Dec 21)" },
      { t: "ul", v: [
        "Low urine volume, hypercalciuria (absorptive I/II, renal leak, resorptive = HPT), hyperoxaluria (dietary, enteric, primary), hypocitraturia (RTA, diarrhoea, ACE-i, thiazide, hypokalaemia), hyperuricosuria, high sodium, high animal protein, obesity/MetS, hot climate, family history, anatomic stasis, medullary sponge, loop diuretics, vitamin D/Ca supplements taken wrong (between meals better), vitamin C >1–2 g, sarcoid.",
      ]},
      { t: "h", v: "Suspecting and investigating primary hyperparathyroidism" },
      { t: "ul", v: [
        "Suspect: high or high-normal Ca on two samples, stones (especially CaP / recurrent CaOx), nephrocalcinosis, bone pain, osteoporosis, pancreatitis, peptic symptoms, polyuria, family MEN1/2, lithium.",
        "Investigate: paired serum Ca + PTH (inappropriately normal or high PTH with high Ca = PTH-dependent). Phosphate low, chloride high, Cl:PO4 >33 classic. 24-h urine Ca (to exclude FHH: urine Ca/Cr clearance ratio <0.01, family, CaSR). 25-OH D (coexistent deficiency raises PTH). DEXA, eGFR. Localise only after biochemical diagnosis: sestamibi-SPECT, 4D-CT, US; do not ‘screen’ with sestamibi. Genetics if young, multi-gland, family (MEN1, RET, CDC73).",
        "Management of the stone former: parathyroidectomy if NIH/AAES criteria (age <50, stones, Cr clearance <60, Ca >1 mg above ULN, osteoporosis) — almost all stone formers qualify. Hydrate, avoid thiazides until Ca is fixed (they raise serum Ca). After cure, urine Ca falls; residual stones still need urologic Rx.",
      ]},
      { t: "h", v: "Hyperuricosuria management" },
      { t: "ul", v: [
        "Define: 24-h uric acid >800 mg ♂ / >750 mg ♀ (or >4 mmol/d).",
        "Diet: less purine (offal, anchovy, beer, fructose). Fluid. Alkalinise urine to 6.0–6.5 (K-citrate) — dissolves uric acid and reduces CaOx epitaxy.",
        "Allopurinol 100–300 mg (or febuxostat) if uric acid stones with hyperuricosuria, or CaOx with hyperuricosuria not fixed by diet, or gout / serum urate high. Titrate; HLA-B*5801 in Han Chinese (SJS).",
        "Do not alkalinise blindly if mixed CaP.",
      ]},
      { t: "tip", k: "gold", v: "First-time adult: analysis + serum Ca. Recurrent/child/solitary: two 24-h urines. High Ca + non-suppressed PTH = operate on the neck, not just the kidney." },
    ],
  },
  {
    id: "eswl-physics",
    topicId: "stones",
    title: "ESWL physics, generators, fragmentation predictors, contraindications, complications, steinstrasse",
    highYield: true,
    gold: true,
    tags: ["SWL", "spalling", "HM3", "steinstrasse", "coupling"],
    exams: [
      { session: "Jun", year: 2014, marks: "4+6", stem: "What is the physics of Extracorporeal Shock Wave Lithotripsy (ESWL)? Describe the factors predicting stone fragmentation with ESWL." },
      { session: "Dec", year: 2011, marks: "4+3+3", stem: "List the types and principle of various extracorporeal shock wave lithotripsy generators. What is spalling? What is super-focusing?" },
      {
        session: "Dec",
        year: 2022,
        marks: "5+5",
        stem: "Enumerate contra-indications for ESWL procedure for renal stones. How will you manage a 26 year male with 1.5 cm renal pelvic and 8 mm upper calyceal calculus in right kidney with no hydronephrosis?",
      },
      { session: "Jun", year: 2020, marks: "3+3+4", stem: "Contraindications and complications of ESWL, and management of the complications." },
      { session: "Jun", year: 2019, marks: "5+5", stem: "Describe the predictive factors for stone fragmentation & clearance following Shockwave Lithotripsy treatment of renal stones. Explain their respective importance." },
      { session: "Dec", year: 2019, marks: "5+5", stem: "Principles of shock-wave lithotripsy. Management of Steinstrasse." },
    ],
    related: ["lower-pole-stone", "energy-sources-lithotripsy", "pcnl-complications"],
    references: [
      "Smith's Endourology — SWL physics (Cleveland, McAteer, Lingeman)",
      "EAU Urolithiasis — SWL",
      "Campbell — SWL",
    ],
    answer: [
      { t: "h", v: "Physics of a shock wave" },
      { t: "p", v: "A shock wave is a short (<5 µs) acoustic pulse with a steep compressive peak (30–110 MPa) followed by a tensile trough (−5 to −15 MPa). Generated extra-corporeally, coupled through water/gel, focused on the stone. Fragmentation is mechanical, not thermal." },
      { t: "ul", v: [
        "Spalling (Hopkins): the compressive wave reflects at the stone–urine (far) interface as a tensile wave; rock fails in tension — chips fly off the distal surface.",
        "Squeezing / circumferential compression: wave in fluid is faster than in stone; the stone is squeezed around its equator and fails along nodes (Eisenmenger).",
        "Cavitation: tensile phase nucleates bubbles on the near surface; collapse jets pit the stone (important for residual dust). Over-rate firing (>1.5–2 Hz) stacks cavitation bubbles that shield subsequent shocks — hence slow rate (60–90/min) improves fragmentation.",
        "Super-focusing: internal reflection/refraction inside an irregular stone concentrates stress at caustics — additional cracks. Also used for the idea that a second focal maximum can occur inside the stone.",
        "Fatigue: cumulative microcracks over hundreds of shocks.",
      ]},
      { t: "h", v: "Generators" },
      { t: "tbl", h: ["Type", "Principle", "Pearls"], r: [
        ["Electrohydraulic (HM3 spark-gap)", "Underwater spark → plasma bubble → shock; ellipsoid reflector, F1 spark / F2 stone", "Gold-standard fragmentation, anaesthesia, large focal zone, more tissue effect"],
        ["Electromagnetic (EMSE, Dornier, Siemens)", "Coil + metal membrane; acoustic lens or parabolic reflector", "Workhorse; reproducible; smaller focal zone"],
        ["Piezoelectric", "Mosaic of crystals on a sphere fire in phase", "Anaesthesia-light, tiny focal zone, needs precise targeting, more shocks"],
        ["Electroconductive / others", "Modified EH with conductive solution", "Niche"],
      ]},
      { t: "p", v: "All have a focal zone (–6 dB volume). Coupling quality (no air bubbles in gel) is the most under-taught determinant of energy delivery." },
      { t: "h", v: "Predictors of fragmentation and clearance" },
      { t: "tbl", h: ["Factor", "Favourable", "Why it matters"], r: [
        ["Size", "<1–1.5 cm (EAU: SWL option ≤2 cm non-lower-pole)", "Shock number vs residual"],
        ["Location", "Pelvis, upper/mid calyx > lower pole", "IPA, infundibular width/length — Elbahnasy; lower pole needs gravity"],
        ["Density", "HU <900–1000; homogeneous", "COM, cystine, brushite resist; COD/struvite/uric acid fragment"],
        ["SSD (skin-to-stone)", "<10–12 cm", "Obesity attenuates"],
        ["Anatomy", "No obstruction, adequate IPA >45°, no diverticulum", "Fragments must pass"],
        ["Stone–gel coupling, rate 60–90/min, ramping", "Good coupling, slow rate, voltage ramping", "Cavitation and vasoconstriction (ramping is reno-protective)"],
        ["Composition", "Known uric acid (but alkalinise first), struvite", "Cystine/brushite/CaOx-mono = poor"],
        ["SSD/HU nomograms (TGI, KUB, Triple D)", "Low score", "Counsel SWL vs fURS/PCNL"],
      ]},
      { t: "h", v: "Contraindications" },
      { t: "ul", v: [
        "Absolute: pregnancy, uncorrected coagulopathy / antiplatelet that cannot be stopped, untreated UTI/sepsis, aortic/renal aneurysm in the focal zone, uncorrected obstruction distal to the stone (unless stented), inability to localise (morbid obesity, radiolucent without US/fluoroscopy).",
        "Relative: pacemaker/ICD (modern devices usually OK with programming), stone over bone, calyceal diverticulum, infundibular stenosis, lower-pole >1 cm, HU >1000, SSD >12 cm, cystine, child (possible with paediatric settings), calcified vessels, uncontrolled HTN (perinephric haematoma).",
      ]},
      { t: "h", v: "Complications and management" },
      { t: "ul", v: [
        "Steinstrasse (see below), renal colic, residual fragments (RFs), Steinstrasse sepsis.",
        "Perinephric / subcapsular haematoma (0.5–1%, higher if HTN): observe, embolize if expanding.",
        "Skin ecchymosis, haematuria (expected), splenic/hepatic/pancreatic injury (rare, left/right upper pole).",
        "Arrhythmia: ECG-gating on older machines.",
        "Hypertension / new-onset diabetes — historical HM3 association, not proven with modern machines.",
        "Failed fragmentation: restone with fURS/PCNL, do not endlessly re-SWL a cystine brick.",
      ]},
      { t: "h", v: "Steinstrasse" },
      { t: "p", v: "A column of fragments in the ureter after SWL (or PCNL), usually at the VUJ. Federmann/Coptcoat grades: I small particles, II larger leading fragment, III completely obstructing plaster." },
      { t: "ul", v: [
        "Prevention: stent if stone >1.5–2 cm or solitary kidney; limit stone burden per session; α-blocker MET after SWL.",
        "Asymptomatic, draining: observe + MET + imaging.",
        "Pain, fever, solitary kidney, rising Cr: urgent decompression (stent or PCN) then URS of the leading fragment. SWL to the leading (obstructing) fragment is an option if it is in the proximal ureter and the patient is afebrile.",
        "Do not bombard a febrile steinstrasse.",
      ]},
      { t: "h", v: "26-year-old, 1.5 cm pelvic + 8 mm upper-calyx, no HDN (Dec 22)" },
      { t: "p", v: "Options: (1) fURS/RIRS in one sitting for both — my preferred in a young patient who wants a single anaesthetic, especially if HU high. (2) SWL to pelvis first (good candidate if HU <900, SSD short) then SWL or observe the 8 mm. (3) Mini-PCNL if SWL/RIRS fail or stone is hard. No hydronephrosis means access for PCNL needs contrast/US skill. Counsel SFR, stent, radiation, cost. Culture, MET after SWL, KUB/US follow-up." },
      { t: "tip", k: "gold", v: "Shock = compression then tension; cavitation needs a slow rate. Spalling is far-wall tensile failure. HM3 is EH; modern machines EM. Steinstrasse: drain if septic, URS the leader." },
    ],
  },
  {
    id: "pcnl-anatomy-access",
    topicId: "stones",
    title: "PCNL access, calyceal and vascular anatomy, puncture technique",
    highYield: true,
    gold: true,
    tags: ["Brodel", "bulls-eye", "Sampaio", "puncture"],
    exams: [
      { session: "Dec", year: 2022, marks: "5+5", stem: "Define various PCN access techniques. How will you manage a 43 year male with post-PCNL hematuria after 1 week of PCN removal." },
      { session: "Dec", year: 2017, marks: "5+5", stem: "Vascular anatomy of kidney with specific relevance to PCNL." },
      { session: "Dec", year: 2014, marks: "10", stem: "Intra-renal vascular anatomy, calyceal anatomy and technique of puncture for PCNL." },
    ],
    related: ["renal-vascular-anatomy", "pcnl-complications", "kidney-anomalies-endourology"],
    references: [
      "Sampaio FJB — intrarenal anatomy",
      "Smith's Endourology — percutaneous access",
      "EAU Urolithiasis — PCNL",
    ],
    answer: [
      { t: "h", v: "Calyceal and vascular anatomy for PCNL" },
      { t: "p", v: "See also the renal-vascular and endourology-anatomy masters. Exam sentences:" },
      { t: "ul", v: [
        "Posterior papilla through Brodel’s avascular line. Anterior puncture hits the anterior segmental arteries and the peritoneal reflection/colon.",
        "Infundibular arteries hug the anterior and posterior surfaces of infundibula — a fornix/papillary puncture is safe; an infundibular puncture is how you get delayed haematuria (pseudoaneurysm/AVF).",
        "Posterior division of the renal artery is a single retropelvic branch in ~50% — the classic bleeder of an over-medial or infundibular tract.",
        "Upper-pole posterior calyx: straight shot to PUJ and most of the collecting system; pleural risk above 12th rib.",
        "Sampaio A1/A2/B mid-zone drainage types dictate whether a mid-calyceal puncture crosses a vessel-rich plane.",
      ]},
      { t: "h", v: "Puncture technique (generic)" },
      { t: "ul", n: true, v: [
        "Prone or supine (Galdakao-Valdivia). C-arm 0° and 30° toward surgeon (bull’s-eye) or biplanar. Retrograde ureteric catheter for air/contrast pyelogram (air outlines posterior calyces in prone).",
        "18G diamond needle onto the papilla. Two-step or one-step. 0.035\" hydrophilic then Amplatz super-stiff. Dilate (serial Amplatz, balloon, single-step mini).",
        "Confirm: urine, contrast in pelvis not extravasated, wire down the ureter if possible (‘through and through’).",
      ]},
      { t: "h", v: "Access techniques to define (Dec 22)" },
      { t: "tbl", h: ["Technique", "How", "Pearl"], r: [
        ["Bull’s-eye (triplanar fluoroscopy)", "C-arm aligned with needle so calyx is a bull’s-eye; advance in that plane; rotate C-arm 30° to see depth", "Classic prone"],
        ["Triangulation", "Two C-arm angles, needle at the intersection of two planes", "When bull’s-eye geometry is awkward"],
        ["US-guided", "Probe identifies posterior calyx; needle in-plane", "No radiation, dilated systems, transplant, paeds, supine"],
        ["Endovision / ‘endoscopic combined’ (ECIRS)", "fURS looks at the papilla while you puncture onto the light", "Supine, complex anatomy"],
        ["CT-guided / iPad fluoro overlay / robotic", "Selected malrotated, retrorenal colon, horseshoe", "Rare"],
        ["Retrograde puncture (Lawson / Lawson-Hunter)", "Deflecting wire from ureter through papilla then ‘inside-out’", "Historical / salvage"],
        ["Mini / Superperc / UMP access", "Smaller tract 10–20 Fr, often one-shot dilatation", "Same papilla rule"],
        ["Multiple tracts", "Separate papillae, not through one infundibulum", "Staghorn"],
      ]},
      { t: "p", v: "Delayed haematuria after tube removal is in the complications master: day 5–14 = pseudoaneurysm/AVF until proven otherwise → CT angio → embolize." },
      { t: "tip", k: "gold", v: "Papilla, Brodel, air in the posterior calyx. Infundibulum is forbidden. Delayed bleed is IR, not a ‘blind clot’." },
    ],
  },
  {
    id: "pcnl-complications",
    topicId: "stones",
    title: "PCNL complications — bleeding, hypotension, SIRS, delayed haematuria",
    highYield: true,
    gold: true,
    tags: ["PCNL", "SIRS", "pseudoaneurysm", "hydrothorax", "Clavien"],
    exams: [
      { session: "Jun", year: 2021, marks: "4+6", stem: "Enumerate the complications of PCNL. Briefly describe the management of each." },
      {
        session: "Dec",
        year: 2021,
        marks: "3+4+3",
        stem: "Causes of post PCNL hypotension. Patho-physiology of hypotension in each situation. Management of each situation.",
      },
      {
        session: "Dec",
        year: 2013,
        marks: "3+3+4",
        stem: "A 30 year old man underwent PCNL in the morning. In the afternoon, he has hypotension. Enumerate possible reasons and discuss management. Add a comment on Systemic Inflammatory Response Syndrome (SIRS).",
      },
      { session: "Dec", year: 2018, marks: "3+3+4", stem: "What are the complications of percutaneous nephrolithotomy and their prevention and management?" },
      {
        session: "Dec",
        year: 2011,
        marks: "3+3+4",
        stem: "What are causes of bleeding during a PCNL procedure? How can such bleeding be prevented? How would you manage persistent hematuria 6 days after a PCNL?",
      },
      {
        session: "Dec",
        year: 2022,
        marks: "5+5",
        stem: "Define various PCN access techniques. How will you manage a 43 year male with post-PCNL hematuria after 1 week of PCN removal.",
      },
    ],
    related: ["pcnl-anatomy-access", "pcnl-variants", "renal-trauma-imaging-embolization"],
    references: [
      "EAU Urolithiasis — PCNL complications",
      "CROES PCNL study",
      "Smith's Endourology",
      "Clavien–Dindo adapted for PCNL (de la Rosette)",
    ],
    answer: [
      { t: "tip", k: "exam", v: "List by Clavien / by phase (access, intra-op, early, delayed). Hypotension afternoon-of = bleed vs sepsis vs drug vs residual anaesthetic vs hydrothorax vs pack tamponade release. Day-6 haematuria = angioembolize." },
      { t: "h", v: "Complications — catalogue with prevention and management" },
      { t: "tbl", h: ["Complication", "Prevention", "Management"], r: [
        ["Failed access / lost tract", "Ureteric catheter, through-and-through wire, US+fluoro", "Re-puncture; stage"],
        ["Bleeding (intra-op)", "Papillary puncture, balloon not over-dilated, BP control, stop antiplatelets", "See below"],
        ["Collecting-system perforation / extravasation", "Don’t force Amplatz, low pressure", "Stop, stent/PCN, staged"],
        ["Fluid absorption / TUR-like", "Saline not glycine, low pressure, sheath bigger than scope (outflow)", "Diuretic, assess Na (if water used — never)"],
        ["Colon injury (retrorenal colon)", "CT, US, avoid extreme lateral puncture", "If retroperitoneal and recognised: conservative, stent, drain, NPO, Abx. Laparotomy if peritonitis"],
        ["Pleural injury / hydro-haemo-pneumothorax", "Below 12th when possible, post-op chest X-ray after supra-12", "Chest tube"],
        ["Spleen / liver / duodenum / pelvis injury", "Anatomy, US", "IR or open"],
        ["Sepsis / SIRS", "Culture, pre-op Abx, decompress pyonephrosis first, low pressure, stage struvite", "Sepsis bundle, ICU, drain"],
        ["Residual stone", "Flexible nephroscopy, ECIRS, CT", "Second look, RIRS, SWL"],
        ["Tube dislodgement, urine leak, peri-nephric abscess", "Secure tube, antegrade study before pull", "Restent, drain abscess"],
        ["Stricture, infundibular stenosis, PUJO", "Avoid infundibular trauma", "Endo-incision / pyeloplasty"],
        ["Death (rare, 0.05–0.1%)", "Selection, staging, IR backup", "—"],
      ]},
      { t: "h", v: "Intra-operative bleeding — causes, prevention, management" },
      { t: "ul", v: [
        "Causes: infundibular / medial puncture (arterial), over-dilatation tearing parenchyma, torn posterior segmental, venous sinus bleed (tamponades), tract in a malrotated/horseshoe kidney, coagulopathy, hypothermia, high BP, torn PUJ, through-and-through into hilum.",
        "Prevention: papilla, balloon 24–30 Fr not 34 if mini will do, two wires, don’t torque the sheath, correct coagulopathy, ramped tract, CT for colon and horseshoe vessels.",
        "Intra-op management: large Amplatz as tamponade, clamp the tube 5–10 min, Kaye tamponade balloon / Council catheter traction, coagulate with nephroscope, Fulgurate, stop the case and stage, transfusion, emergency angio if arterial pumping, open only if crashing and IR delayed.",
      ]},
      { t: "h", v: "Afternoon hypotension after morning PCNL (Dec 13 / Dec 21)" },
      { t: "tbl", h: ["Cause", "Pathophysiology", "Clues", "Management"], r: [
        ["Haemorrhage (tract, delayed arterial, occult peritoneum)", "Hypovolaemic shock", "Drain blood, falling Hb, tachycardia, flank swelling", "ABC, blood, clamp tube, CT angio, embolize / re-explore"],
        ["Sepsis / SIRS / bacteraemia", "Vasodilatation + leaky capillaries (distributive); endotoxin from infected stone", "Fever, warm shock, high lactate, known struvite", "Sepsis-6, cultures, ICU, vasopressors, ensure drainage"],
        ["Hydrothorax / tension pneumothorax (supra-12)", "Impaired venous return", "↓air entry, SpO2, CXR", "Chest tube"],
        ["Residual anaesthetic / regional / drugs (α-blockers, antihypertensives, fentanyl)", "Vasodilatation / bradycardia", "Dry field, normal Hb", "Fluids, atropine, hold drugs"],
        ["Water intoxication / hyponatraemia (if hypotonic irrigant — should never happen)", "Osmotic shift", "Na low, confusion", "Hypertonic saline"],
        ["Cardiac event / PE / anaphylaxis (antibiotic, latex)", "Cardiogenic / obstructive / anaphylactic", "ECG, trop, rash, ETCO2", "ALS pathways"],
        ["Retroperitoneal urine extravasation with vagal / under-resuscitation", "Third-space", "Ileus, high drain Cr", "Fluids, stent"],
      ]},
      { t: "h", v: "SIRS comment" },
      { t: "p", v: "SIRS = ≥2 of T >38 or <36, HR >90, RR >20 or PaCO2 <32, WBC >12 or <4 or bands. In PCNL it is driven by translocation of endotoxin/bacteria from an infected stone under irrigant pressure, not always a positive blood culture (bacteraemia ≠ SIRS ≠ sepsis). Prevention: pre-op culture, targeted Abx, treat pyonephrosis with PCN first, keep intra-renal pressure low (access sheath, mini with suction), stage if pus. Treatment: surviving-sepsis hour-1 bundle; source is already ‘drained’ if the tube is working — do not forget a blocked tube or contralateral obstruction." },
      { t: "h", v: "Haematuria 6–7 days after PCNL / after tube removal" },
      { t: "p", v: "This is a pseudoaneurysm or AVF of a segmental/interlobar artery until proven otherwise (classic window day 5–14). Venous bleeds present intra-op or immediately. Clot colic and falling Hb. Management: resuscitate, clamp any remaining tube, CT angiography, superselective coil embolization (success >90%). Re-embolize before nephrectomy. Bed rest, catheter if clot retention. Do not ‘watch’ a recurrent massive bleed." },
      { t: "tip", k: "gold", v: "Intra-op bleed: tamponade and stage. Afternoon shock: blood vs bugs vs chest. Day-6 bleed: coils, not comfort. SIRS is pressure plus infected stone." },
    ],
  },
  {
    id: "pcnl-variants",
    topicId: "stones",
    title: "Mini-PCNL, supine PCNL, tubeless PCNL and instruments",
    highYield: true,
    gold: true,
    tags: ["mini-PCNL", "supine", "tubeless", "Amplatz", "Swiss LithoClast"],
    exams: [
      { session: "Jun", year: 2018, marks: "10", stem: "Supine PCNL." },
      {
        session: "Dec",
        year: 2016,
        marks: "2+2+2+2+2",
        stem: "Instruments, surgical technique, clearance of stone fragments, advantages and limitations of Mini Percutaneous Nephrolithotomy (Mini PCNL).",
      },
      { session: "Jun", year: 2015, marks: "10", stem: "Devices and instruments used for percutaneous nephrolithotomy (PCNL)." },
      { session: "Dec", year: 2012, marks: "3+4+3", stem: "What are the indications, advantages and disadvantages of tubeless PCNL?" },
    ],
    related: ["pcnl-anatomy-access", "pcnl-complications", "energy-sources-lithotripsy"],
    references: [
      "Smith's Endourology",
      "EAU Urolithiasis",
      "Valdivia / Galdakao supine PCNL",
      "Helal / Jackman mini-perc; Superperc (Shah)",
    ],
    answer: [
      { t: "h", v: "Instruments and devices for PCNL (Jun 15)" },
      { t: "ul", v: [
        "Imaging: C-arm, US probe, (CT). Ureteric catheter 5–6 Fr + cystoscope. Contrast, air.",
        "Needles: 18G diamond/Chiba. Wires: hydrophilic 0.035, Amplatz super-stiff, nitinol safety.",
        "Dilatators: Alken metal telescopic, Amplatz sequential Teflon, balloon (NephroMax), single-step ‘one-shot’, screw (Mini).",
        "Sheaths: Amplatz 24–30 Fr standard; 16–20 Fr mini; 11–13 Fr ultra-mini; 4.8–8 Fr micro. Continuous-flow / suction sheaths (Superperc, ClearPetra).",
        "Scopes: 24–26 Fr rigid nephroscope; 12–18 Fr mini-nephroscope; flexible nephroscope/cystoscope for inspection.",
        "Energy: pneumatic (LithoClast), US (Olympus CyberWand, Swiss LithoClast Master combination), Ho:YAG, thulium fibre, ballistic, (EHL historical).",
        "Extraction: triradiate forceps, graspers, Nitinol baskets, suction.",
        "Exit: 16–22 Fr Malecot/Foley/nephrostomy, tubeless with 6 Fr stent, totally tubeless, haemostatic foam/sealant, Kaye balloon.",
        "Adjuncts: laser safety, pressure bags, warming, thromboprophylaxis, IR on call.",
      ]},
      { t: "h", v: "Mini-PCNL (Dec 16)" },
      { t: "ul", v: [
        "Definition: tract ≤20 Fr (commonly 16–18). Ultra-mini 11–13; micro 4.8–8 (optical puncture).",
        "Instruments: 12 Fr mini-nephroscope, 12–16 Fr sheath, Ho:YAG or pneumatic, suction tubing.",
        "Technique: same papillary puncture; single-step metal or screw dilatation; laser dust or fragment; suction (Superperc uses a paediatric ET-tube circuit to keep a collapsed-stone vacuum).",
        "Clearance: dust washes out the sheath; larger pieces suctioned; flexible scope through mini sheath or second-look. SFR for 1–2.5 cm comparable to standard in randomised data if you are patient; staghorn still wants a larger (or multi-mini) tract.",
        "Advantages: less bleeding, less pain, more tubeless, shorter stay, paediatric and diverticular stones, interpolar.",
        "Limitations: longer lasing time, higher intra-renal pressure if no suction (sepsis), poor for hard 4 cm stones, steep learning, flexible-scope exit not as roomy, cost of laser fibres.",
      ]},
      { t: "h", v: "Supine PCNL (Jun 18)" },
      { t: "p", v: "Valdivia (1998) and Galdakao-modified Valdivia (with legs up for simultaneous fURS = ECIRS). Patient supine, ipsilateral flank lifted 30–45°, puncture more lateral than prone." },
      { t: "ul", v: [
        "Advantages: airway (anaesthetist’s favourite), no prone-cardiorespiratory insult, simultaneous retrograde access (ECIRS), quick conversion to open, ergonomic for obese, transplant kidney (already iliac), bilateral possible.",
        "Disadvantages: smaller, more mobile kidney, bowel more at risk if too lateral, collecting system less ‘filled’ (needs ureteric occlusion), upper-pole supra-12 harder, surgeons trained prone have a learning curve, irrigant pools in the abdomen if there is a rent.",
        "Outcomes: CROES and meta-analyses — similar SFR and complications vs prone when the surgeon is past the curve. Choose the position you do well, and use supine when the chest or the ureteroscope demands it.",
      ]},
      { t: "h", v: "Tubeless PCNL (Dec 12)" },
      { t: "ul", v: [
        "Definition: no nephrostomy; a ureteric stent (tubeless) or nothing (totally tubeless) remains. A ‘mini-tubeless’ may use a 6–8 Fr overnight tube.",
        "Indications: uncomplicated puncture, single tract, complete clearance (or planned RIRS of tiny residual), no significant perforation, haemostasis satisfactory, no plan for second look, no active infection, no solitary kidney with doubt.",
        "Advantages: less pain, less leakage, shorter stay, no tube-related infection.",
        "Disadvantages / contraindications: cannot do a second-look through the tract, urinoma if unstented and perforated, delayed bleed harder to tamponade, not for residual staghorn, not after a bloody tract. Totally tubeless needs a perfect case.",
      ]},
      { t: "tip", k: "gold", v: "Mini = ≤20 Fr with suction if you can. Supine = ECIRS and the airway. Tubeless = reward for a dry, complete, single-tract case — not a religion." },
    ],
  },
  {
    id: "uric-acid-radiolucent",
    topicId: "stones",
    title: "Uric acid and other radiolucent stones",
    highYield: true,
    gold: true,
    tags: ["uric acid", "alkalinisation", "radiolucent", "2,8-DHA"],
    exams: [
      { session: "Jun", year: 2021, marks: "4+3+3", stem: "Etiology, metabolic workup and treatment of uric acid stones." },
      { session: "Jun", year: 2014, marks: "4+3+3", stem: "Describe the Aetio-pathogenesis, diagnosis and management of radiolucent stones." },
    ],
    related: ["metabolic-evaluation", "xanthine-oxidase", "caox-citrate"],
    references: ["EAU Urolithiasis", "Campbell Lithiasis", "Ngo / Assimos uric acid reviews"],
    answer: [
      { t: "h", v: "Radiolucent stones — differential" },
      { t: "tbl", h: ["Stone", "HU / clue", "pH", "Rx"], r: [
        ["Uric acid (commonest radiolucent)", "200–500 HU, no visible KUB stone, CT-visible", "<5.5", "Alkali ± allopurinol"],
        ["Ammonium acid urate", "IBD, laxative abuse, UTI", "Variable", "Fix bowel, alkali, Abx"],
        ["Xanthine", "Allopurinol over-treatment, HPRT", "—", "Stop excess allopurinol, fluids"],
        ["2,8-dihydroxyadenine (APRT deficiency)", "Child, ‘uric acid’ that does not alkali-dissolve", "—", "Allopurinol (yes), never alkali alone"],
        ["Matrix / protein", "Infection, mucin", "—", "PCNL, Abx"],
        ["Indinavir / atazanavir / ceftriaxone / sulpha", "Drug crystals; indinavir even CT-lucent", "—", "Stop/change drug"],
        ["Cystine is faintly radio-opaque", "Do not call it lucent", "—", "Alkali + tiopronin"],
      ]},
      { t: "h", v: "Uric acid — etiology" },
      { t: "ul", v: [
        "Persistently acid urine (the dominant mechanism — hepatic insulin resistance impairs ammoniagenesis in MetS) ± low volume ± hyperuricosuria (gout, myeloproliferative, TLS, diet, inborn HPRT / PRPP-synthetase).",
        "pKa of uric acid 5.35: at pH 5 almost all is insoluble free acid; at 6.5 mostly urate salt. Hence alkali dissolves stones in situ.",
      ]},
      { t: "h", v: "Work-up" },
      { t: "ul", v: ["Stone analysis if retrieved.", "Serum urate, Cr, HCO3, glucose/HbA1c, lipids (MetS).", "24-h: volume, uric acid, pH, citrate, Na, Ca (mixed stones).", "CT HU 200–500 + pH <5.5 is enough to start empiric dissolution with close imaging."], },
      { t: "h", v: "Treatment" },
      { t: "ul", v: [
        "Dissolution: K-citrate titrated to urine pH 6.5–7.0 (not >7 — CaP risk). Check pH diary. 80% of pure uric acid stones dissolve in 6–12 weeks if unobstructed.",
        "Obstructed / septic / pain: stent or PCN first, then alkali; or URS/PCNL if dissolution fails / mixed HU >600.",
        "Allopurinol if hyperuricosuria, gout, or high serum urate; not as monotherapy if the urine is still pH 5.",
        "Diet: less purine/fructose/alcohol, more fluid >2.5 L, weight loss. No need for extreme purine bans if pH is controlled.",
      ]},
      { t: "tip", k: "gold", v: "Radiolucent ≠ uric acid, but uric acid is the one you dissolve. Acid urine is the disease; allopurinol is the helper. 2,8-DHA fools you in children." },
    ],
  },
  {
    id: "energy-sources-lithotripsy",
    topicId: "stones",
    title: "Intracorporeal lithotripsy energy sources",
    highYield: true,
    gold: true,
    tags: ["Ho:YAG", "TFL", "pneumatic", "EHL", "ultrasonic"],
    exams: [
      {
        session: "Jun",
        year: 2021,
        marks: "4+2+4",
        stem: "Discuss management options for 16mm Calculus in the upper ureter with moderate HDUN in a 20 years old female. Enumerate energy sources for intracorporeal lithotripsy and their merits and demerits.",
      },
      { session: "Dec", year: 2018, marks: "10", stem: "Energy sources used to fragment renal stones and discuss their mechanism of action." },
      {
        session: "Dec",
        year: 2013,
        marks: "3+3+4",
        stem: "You are doing ureteroscopy for 1 cm lower ureteric stones. Describe mechanism of action, advantage and disadvantages of Laser, lithotrite and electro hydraulic lithotripsy.",
      },
    ],
    related: ["ureteric-stone-management", "eswl-physics", "rirs-controversies"],
    references: ["Smith's Endourology", "EAU Urolithiasis", "Campbell"],
    answer: [
      { t: "tbl", c: "Know mechanism + one advantage + one disaster each", h: ["Source", "Mechanism", "Merits", "Demerits"], r: [
        ["Ho:YAG 2100 nm", "Photothermal: water absorption, micro-explosion of stone water / vapor bubble; some photomechanical", "All compositions, flexible fibres, dust or fragment, safety distance ~1 mm, gold standard URS", "Slow on large bulk, retropulsion (pulse energy), fibre cost, ignition of wire, submucosal stone if contact with wall"],
        ["Thulium fibre laser (TFL) 1940 nm", "Higher water absorption, small fibres, very high frequency dusting", "Less retropulsion, finer dust, smaller fibre = better deflection", "Heat at high power/low flow, availability/cost"],
        ["Pneumatic / ballistic (Swiss LithoClast)", "Compressed-air projectile, jackhammer", "Fast, cheap, all stones, PCNL workhorse", "Retropulsion (URS — stone flies to kidney), rigid probe, not for flexible URS"],
        ["Ultrasonic", "Piezoelectric/magnetostrictive probe, 20–30 kHz, suction hollow probe", "Chews and sucks (PCNL), good for CaP/struvite", "Rigid, poor on some CaOx-mono/cystine, heat if no suction"],
        ["Combination US + pneumatic (LithoClast Master, ShockPulse, CyberWand)", "Both", "PCNL efficiency", "Bulk, cost"],
        ["EHL", "Spark at probe tip → plasma bubble shock", "Flexible, cheap historically", "Perforation, stray energy, largely abandoned in ureter"],
        ["Electrokinetic / Trilogy", "Electromagnetic projectile + US", "PCNL", "Cost"],
        ["SWL (extracorporeal)", "See ESWL master", "Non-invasive", "Not ‘intracorporeal’"],
      ]},
      { t: "h", v: "URS for 1 cm lower ureter — pick an energy" },
      { t: "p", v: "Ho:YAG (or TFL) in a 270 µm fibre is the default: controlled, less retropulsion than pneumatic, safe if you see a red beam on stone not wall. Pneumatic is fine in the distal ureter with a basket to prevent retropulsion (‘escape’). EHL: mention and discard (perforation)." },
      { t: "h", v: "16 mm upper ureter, moderate HDUN, 20-year-old woman (Jun 21)" },
      { t: "ul", v: [
        "Not SWL-first if the stone is 16 mm (borderline, hydronephrosis, young — better a single-stage URS/RIRS or antegrade if very impacted).",
        "Culture, stent if infected/obstructed then delayed URS; if afebrile, primary semi-rigid ± flexible URS with Ho:YAG, access sheath, relocate if needed.",
        "Impacted, failed retrograde: antegrade mini-PCNL / antegrade URS.",
        "Pregnancy is not the stem but she is of childbearing age — β-hCG before radiation.",
        "MET has no role at 16 mm. Laparoscopic ureterolithotomy is a last resort after failed endourology.",
      ]},
      { t: "tip", k: "gold", v: "Ureter = Ho:YAG/TFL. PCNL bulk = US + pneumatic. EHL perforates. 16 mm upper ureter in a young woman = URS/laser, not months of tamsulosin." },
    ],
  },
  {
    id: "ureteric-stone-management",
    topicId: "stones",
    title: "Ureteric stones — upper, intramural, MET",
    highYield: true,
    gold: true,
    tags: ["MET", "tamsulosin", "intramural", "URS"],
    exams: [
      { session: "Dec", year: 2014, marks: "10", stem: "Management options for a 9mm upper ureteral stone." },
      { session: "Jun", year: 2017, marks: "3+7", stem: "Clinical manifestations and management of 1.5 cm stone in intramural right ureter of a 30 year male." },
      { session: "Jun", year: 2018, marks: "10", stem: "Medical expulsive therapy of ureteric calculus." },
      { session: "Dec", year: 2015, marks: "5+5", stem: "Role of calcium channel blockers and alpha adrenergic blockers for stone expulsion therapy." },
    ],
    related: ["energy-sources-lithotripsy", "pregnancy-stone", "eswl-physics"],
    references: [
      "EAU Urolithiasis — MET, URS, SWL",
      "SUSPEND trial (Lancet 2015) / SPINNE",
      "AUA/EAU stone guidelines",
    ],
    answer: [
      { t: "h", v: "MET" },
      { t: "ul", v: [
        "Idea: relax distal-ureter smooth muscle (α1D > α1A dense at VUJ) ± calcium-channel blockade, plus analgesia, fluid, strain urine.",
        "α-blockers: tamsulosin 0.4 mg, silodosin 8 mg, alfuzosin. Best evidence for distal stones 5–10 mm. SUSPEND (UK) was negative overall (many small stones that pass anyway); meta-analyses still support a modest benefit for distal >5 mm. Counsel ejaculatory failure, hypotension.",
        "CCB: nifedipine 30 mg XL — older RCTs positive, less than tamsulosin in head-to-heads; headache, hypotension. EAU no longer prefers CCB over α-blockers.",
        "Adjuncts: NSAIDs (prostaglandin, pain, maybe expulsion), steroids (not routine), PDE5-i experimental, mirabegron emerging.",
        "Limits: not for fever, solitary kidney, intractable pain, stone >10 mm, pregnancy (nifedipine is used for tocolysis but α-blockers are category caution — prefer expectant/stent/URS).",
        "Duration: 4–6 weeks max with imaging; then URS.",
      ]},
      { t: "h", v: "9 mm upper ureteric stone (Dec 14)" },
      { t: "ul", v: [
        "Options: SWL in situ (good if visible, HU <900, no sepsis, kidney not completely obstructed), URS (semi-rigid may not reach; flexible URS + laser, high success, stent), push-back + PCNL/SWL (historical), laparoscopic ureterolithotomy (failed endourology).",
        "MET is optional analgesia; a 9 mm upper stone has a low spontaneous-passage rate (~30–50%).",
        "If hydronephrosis + infection: decompress first.",
        "Pick URS if you need a one-session SFR in a young professional; SWL if you want to avoid a stent and the stone is SWL-friendly.",
      ]},
      { t: "h", v: "1.5 cm intramural ureter, 30-year-old man (Jun 17)" },
      { t: "ul", v: [
        "Clinical: vesical tenesmus, strangury, frequency, terminal haematuria, referred testicular pain, hydronephrosis, UTI, rarely acute urinary retention from a ball-valve stone at the meatus.",
        "Diagnosis: CT, cystoscopy (bullous oedema, stone at orifice).",
        "Management: not MET (too big). Cystoscopic meatotomy / ureteric-orifice incision at 12 o’clock and extraction if the stone is visible at the meatus. Semi-rigid URS + laser with care of the intramural tunnel (reflux later, usually harmless). Basket extraction after fragmentation. Stent 1–2 weeks because the tunnel is swollen. Dormia without fragmentation is how you avulse the ureter — don’t. SWL poor (bone, oedema, cannot localise well).",
      ]},
      { t: "tip", k: "gold", v: "MET = tamsulosin for distal 5–10 mm, 4 weeks, not a septic patient. 9 mm upper = URS or SWL. 15 mm intramural = cystoscopic/URS extraction, not an α-blocker and a prayer." },
    ],
  },
  {
    id: "lower-pole-stone",
    topicId: "stones",
    title: "Lower-pole calyceal stones",
    highYield: true,
    gold: true,
    tags: ["lower pole", "IPA", "Elbahnasy", "RIRS", "mini-PCNL"],
    exams: [
      { session: "Jun", year: 2019, marks: "4+6", stem: "Discuss the options of management of a 13 mm sized kidney stone in lower pole calyx. Discuss the pros & cons of each options." },
      { session: "Dec", year: 2017, marks: "5+5", stem: "Management options for 1.5cm lower pole renal stone. Advantages & disadvantages of different modalities." },
    ],
    related: ["eswl-physics", "pcnl-variants", "rirs-controversies"],
    references: ["Lower Pole I / II trials (Albala, Pearle)", "EAU Urolithiasis", "Elbahnasy infundibulopelvic angle"],
    answer: [
      { t: "p", v: "Lower-pole stones fail SWL because fragments cannot climb a steep, long, narrow infundibulum (Elbahnasy: IPA <45°, infundibular length >3 cm, width <5 mm). Lower Pole I: PCNL >> SWL for 1–3 cm. Lower Pole II: URS ≈ SWL for ≤1 cm, both modest." },
      { t: "tbl", h: ["Modality", "Pros", "Cons", "Best for 13–15 mm"], r: [
        ["SWL", "Outpatient, no tube", "SFR 30–60% in LP; retreatment; steinstrasse; needs anatomy + HU + SSD in its favour", "Second-line if IPA wide, HU <800, SSD short"],
        ["fURS / RIRS", "No puncture, all compositions, day-care", "Deflection strain, residual dust, access-sheath sepsis, cost, staged if burden high", "Reasonable first in 1–1.5 cm if expert and IPA not terrible — relocate to upper pole then dust"],
        ["Mini-PCNL", "Highest SFR in one session", "Bleed, tract, admission", "The most honest first choice for 1.5 cm LP if you want it gone"],
        ["Standard PCNL", "SFR", "Overkill vs mini for 13 mm", "If coincidental anatomy needs a large tract"],
        ["Observe", "No harm if asymptomatic, <10 mm, sterile", "Growth, silent obstruction, infection", "Not for 13–15 mm in most 10-mark answers unless the patient is dying of something else"],
      ]},
      { t: "tip", k: "gold", v: "Lower pole is gravity plus IPA. 13–15 mm: mini-PCNL for SFR, RIRS if you can relocate, SWL only if the anatomy is kind." },
    ],
  },
  {
    id: "calyceal-diverticulum",
    topicId: "stones",
    title: "Calyceal diverticulum and diverticular calculi",
    highYield: false,
    gold: false,
    tags: ["diverticulum", "Dretler", "fulguration"],
    exams: [
      { session: "Dec", year: 2020, marks: "3+2+5", stem: "What is a calyceal diverticulum? Discuss the management of calyceal diverticular calculi." },
    ],
    related: ["lower-pole-stone", "pcnl-variants"],
    references: ["Campbell", "Smith's Endourology", "EAU Urolithiasis"],
    answer: [
      { t: "p", v: "A calyceal diverticulum is a non-secretory urothelium-lined outpouching of the collecting system, communicating through a narrow infundibulum, usually congenital (failed branching) and in the upper pole (anterior or posterior). Type I: from a minor calyx. Type II: from the pelvis/major calyx (Dretler). Stones form from stasis (~10–50% of diverticula); milk of calcium is classic." },
      { t: "p", v: "Diagnose on CTU / delayed IVU: contrast fills late; differential is hydrocalyx from infundibular stenosis (which has draining papillae)." },
      { t: "h", v: "Management of diverticular calculi" },
      { t: "ul", v: [
        "Asymptomatic milk-of-calcium: observe.",
        "Pain, infection, haematuria, growth: treat stone AND the communication.",
        "Posterior diverticulum: PCNL (often mini) — puncture the cavity (US/CT), clear stone, dilate or incise the neck (Ho:YAG), fulgurate the cavity lining to prevent re-fill. Highest SFR.",
        "Anterior / upper: fURS — identify the pin-hole (methylene blue, indigo), incise neck, dust stone, leave a stent across the neck. Limited if the ostium is invisible.",
        "Laparoscopic / robotic: unroofing + closure of the neck + ablation of lining — for anterior diverticula that failed endourology.",
        "SWL: fragments cannot leave a pin-hole — only if the neck is wide and you accept poor SFR.",
      ]},
      { t: "tip", k: "gold", v: "A diverticulum is a blind urothelial cave. Treat the stone and open or kill the cave. SWL is wishful." },
    ],
  },
  {
    id: "horseshoe-staghorn",
    topicId: "stones",
    title: "Staghorn calculus in a horseshoe kidney",
    highYield: true,
    gold: false,
    tags: ["horseshoe", "staghorn", "upper-pole puncture"],
    exams: [
      { session: "Jun", year: 2016, marks: "5", stem: "Management of staghorn calculus in horse shoe kidney." },
    ],
    related: ["fusion-anomalies-horseshoe", "pcnl-anatomy-access", "struvite-stones"],
    references: ["EAU Urolithiasis — anomalous kidneys", "Campbell", "Smith's Endourology"],
    answer: [
      { t: "p", v: "Full anatomic discussion lives in the fusion-anomalies master. For the stone paper: PCNL via a posterior upper-pole calyx is first-line for staghorn; malrotation puts the pelvis anterior and the colon posterior — CT plan is mandatory. Mini or standard, flexible nephroscopy into the isthmic calyx, second tract if needed. Concurrent PUJO is reconstructed by pyeloplasty, not endopyelotomy. SWL poor. Metabolic work-up still required." },
      { t: "tip", k: "gold", v: "Horseshoe staghorn: upper-pole PCNL, CT for colon and vessels, fix PUJO properly." },
    ],
  },
  {
    id: "struvite-stones",
    topicId: "stones",
    title: "Struvite stones — pathogenesis and management",
    highYield: true,
    gold: true,
    tags: ["struvite", "urease", "staghorn", "AHA"],
    exams: [
      { session: "Dec", year: 2016, marks: "5+5", stem: "Pathogenesis of struvite stone and its management." },
    ],
    related: ["pcnl-complications", "metabolic-evaluation", "acid-base-rta"],
    references: ["EAU Urolithiasis", "Campbell", "Griffith / Preminger infection stones"],
    answer: [
      { t: "h", v: "Pathogenesis" },
      { t: "p", v: "Struvite = magnesium ammonium phosphate hexahydrate (MgNH4PO4·6H2O), often mixed with carbonate apatite. Requires urease-positive infection (Proteus, Klebsiella, Providencia, Pseudomonas, Ureaplasma, Staphylococcus saprophyticus — NOT typical E. coli)." },
      { t: "ul", n: true, v: [
        "Urease: urea → 2 NH3 + CO2.",
        "NH3 + H2O → NH4+ + OH− → urine pH >7.2.",
        "CO2 → HCO3/CO3; PO4³− appears as pH rises; Mg²+ and Ca²+ precipitate → struvite + carbonate apatite.",
        "Biofilm on the stone: antibiotics cannot sterilise until the stone is gone. Rapid staghorn growth, matrix, ‘coffin-lid’ crystals.",
      ]},
      { t: "h", v: "Management" },
      { t: "ul", v: [
        "Complete surgical clearance is mandatory (PCNL ± flexible, anatrophic only if endourology fails). Residual = relapse.",
        "Culture-specific antibiotics peri-op and until the tract is dry; sometimes a short post-clearance course. Do not lifelong-suppress as a substitute for clearance.",
        "Acidification / AHA (acetohydroxamic acid, urease inhibitor): residual inaccessible stone, high side-effect (DVT, tremor) — rarely used.",
        "Metabolic work-up: many ‘struvite’ patients have a metabolic CaOx nidus.",
        "Correct obstruction, neurogenic bladder, fistulae. Surveillance imaging.",
      ]},
      { t: "tip", k: "gold", v: "Urease, pH >7.2, Proteus. If you leave a fragment you have failed. Antibiotics without a PCNL are a delay." },
    ],
  },
  {
    id: "hyperoxaluria",
    topicId: "stones",
    title: "Primary hyperoxaluria — types, presentation, management",
    highYield: true,
    gold: false,
    tags: ["PH1", "AGXT", "oxalobacter", "lumasiran"],
    exams: [
      { session: "Jun", year: 2019, marks: "3+3+4", stem: "Primary hyperoxaluria: Discuss types, presentation and management." },
      { session: "Jun", year: 2015, marks: "2+4+4", stem: "Types, pathophysiology and management of primary hyperoxaluria." },
    ],
    related: ["metabolic-evaluation", "caox-citrate"],
    references: [
      "OxalEurope / ERKNet PH guidelines",
      "Campbell",
      "Lumasiran ILLUMINATE trials",
    ],
    answer: [
      { t: "tbl", h: ["Type", "Gene / enzyme", "Clue"], r: [
        ["PH1 (80%)", "AGXT, liver peroxisomal alanine-glyoxylate aminotransferase. Glyoxylate → oxalate instead of glycine", "Infantile oxalosis, pyridoxine-responsive in ~30% (G170R, F152I)"],
        ["PH2", "GRHPR, glyoxylate reductase-hydroxypyruvate reductase", "Usually milder, no pyridoxine"],
        ["PH3", "HOGA1, 4-hydroxy-2-oxoglutarate aldolase (mito)", "Often childhood stones, may improve with age; HOG in urine"],
      ]},
      { t: "h", v: "Pathophysiology / presentation" },
      { t: "ul", v: [
        "Hepatic over-production of oxalate → urine oxalate often >1 mmol/1.73 m²/d (normal <0.5). CaOx supersaturation, nephrocalcinosis, ESRD, then systemic oxalosis (bone, retina, heart, vessels, livedo) once GFR <30–40 because oxalate is renal-cleared.",
        "Child with recurrent CaOx, nephrocalcinosis, family history, ESRD with living-donor transplant that fails from oxalate — think PH. Spot oxalate/Cr, 24-h oxalate, genetic panel; liver biopsy historical.",
      ]},
      { t: "h", v: "Management" },
      { t: "ul", v: [
        "Fluids 2–3 L/m², K-citrate, Mg, avoid vitamin C. Pyridoxine 5–10 mg/kg in PH1 pending genetics.",
        "RNAi: lumasiran (glycolate oxidase, PH1), nedosiran (hepatic LDH). Game-changers — quote them.",
        "Oxalobacter formigenes / oral oxalate-degrading enzymes: adjunct, mixed evidence.",
        "Dialysis (high-flux, daily) does not keep up with generation once in ESRD — hence combined liver-kidney transplant in PH1 (liver = enzyme replacement). Isolated kidney only in selected PH2/3 or pyridoxine-responsive PH1 with low plasma oxalate.",
        "Urologic: conservative stone Rx, avoid losing kidneys to PCNL sepsis.",
      ]},
      { t: "tip", k: "gold", v: "PH1 = AGXT, B6, lumasiran, liver+kidney when oxalosis looms. Infantile nephrocalcinosis is not ‘bad diet’." },
    ],
  },
  {
    id: "ftir-stone-analysis",
    topicId: "stones",
    title: "Stone analysis methods and FTIR",
    highYield: false,
    gold: false,
    tags: ["FTIR", "XRD", "wet chemistry"],
    exams: [
      { session: "Jun", year: 2017, marks: "3+7", stem: "Enumerate the methods of stone analysis. Fourier’s transform infra-red spectroscopy (FTIR) for stone analysis." },
    ],
    related: ["metabolic-evaluation", "uric-acid-radiolucent"],
    references: ["EAU Urolithiasis", "Hesse / Siener stone analysis", "Smith's Endourology"],
    answer: [
      { t: "ul", v: [
        "Wet chemical qualitative kits — cheap, inaccurate, obsolete for core.",
        "Infrared spectroscopy (FTIR) — workhorse.",
        "X-ray diffraction (XRD) — gold for crystalline structure; cannot see amorphous matrix.",
        "Polarising microscopy / morphoconstitutional analysis (Daudon) — surface + section + IR; predicts pathogenesis.",
        "SEM + energy-dispersive X-ray, thermogravimetry, NMR, CT HU (in vivo guess, not analysis).",
      ]},
      { t: "h", v: "FTIR" },
      { t: "p", v: "Molecules absorb infrared at characteristic bond-vibration wavelengths. A Michelson interferometer generates an interferogram of the sample (KBr pellet or ATR crystal); Fourier transform converts it to a spectrum (4000–400 cm⁻¹). Compare with a library (whewellite, weddellite, apatite, brushite, struvite, uric acid, cystine, drugs). Advantages: small sample, mixed stones, organic compounds, fast. Limitations: operator, library quality, amorphous content, cannot replace a 24-h urine. Always analyse the core and the surface separately if layered." },
      { t: "tip", k: "gold", v: "FTIR or XRD, never a colour chart. Analyse every first stone and every ‘different’ recurrence." },
    ],
  },
  {
    id: "pregnancy-stone",
    topicId: "stones",
    title: "Urinary tract in pregnancy and first-trimester ureteric stone",
    highYield: true,
    gold: true,
    tags: ["pregnancy", "US", "stent", "URS", "radiation"],
    exams: [
      {
        session: "Jun",
        year: 2016,
        marks: "4+6",
        stem: "Anatomical changes in urinary tract in pregnancy. Management of unilateral upper ureteric calculus in first trimester of pregnancy.",
      },
    ],
    related: ["ureteric-stone-management", "aki-arf-urology"],
    references: [
      "EAU Urolithiasis — pregnancy",
      "AUA / CUA pregnancy stone",
      "Campbell — Pregnancy urology",
    ],
    answer: [
      { t: "h", v: "Anatomic and physiologic changes" },
      { t: "ul", v: [
        "Dilatation of calyces, pelvis, ureters (right > left) from 6–10 weeks, peak 22–24, persists 6 weeks postpartum. Mechanical (gravid uterus, iliac vessels, dextrorotation) + progesterone atony. Physiological hydro is not obstruction — the ureter is dilated to the pelvic brim, not below.",
        "Bladder: capacity up, trigone pushed, frequency, stress leak.",
        "GFR +50%, RPF +75%, creatinine falls (a ‘normal’ 1.0 is abnormal). Physiologic hypocitraturia + hypercalciuria (placental 1,25-D) but increased inhibitors (citrate, magnesium, glycoproteins) and high volume — stone incidence only slightly up.",
        "Hyperchloraemic alkalosis mild; respiratory alkalosis from minute-volume.",
      ]},
      { t: "h", v: "Upper ureteric stone, first trimester" },
      { t: "ul", v: [
        "Diagnose with US (renal + transvaginal distal ureter) ± MRI without gadolinium. Low-dose CT is last resort and avoided in T1. KUB one-shot only if it will change a decision.",
        "50–80% pass with analgesia (paracetamol, opioids; NSAIDs contraindicated in T3, avoid in T1 if possible). MET: tamsulosin is off-label, data limited; many avoid in T1.",
        "Intervene if pain, fever, solitary kidney, AKI, or obstetric concern.",
        "Temporise: US-guided PCN or stent under US, no fluoro if possible. Stents encrust fast in pregnancy — change 4–6 weekly, miserable. PCN same.",
        "Definitive URS + Ho:YAG is safe in experienced hands in all trimesters when temporising fails (EAU). Shield the pelvis; obstetric team; DVT risk; anaesthesia (avoid NSAID, nitrous debate).",
        "SWL absolute contraindication. PCNL not in pregnancy. Open/lap last resort.",
        "First trimester extra: teratogenesis from radiation/anaesthesia is the fear — US-guided drainage plus delayed URS in T2 is a valid plan if she is stable.",
      ]},
      { t: "tip", k: "gold", v: "Pregnancy hydro is right-sided to the brim. Image with US/MRI. Drain with US; URS is allowed; SWL is not. Change stents monthly or just treat the stone." },
    ],
  },
  {
    id: "arf-calculous",
    topicId: "stones",
    title: "Acute renal failure due to calculous disease",
    highYield: true,
    gold: false,
    tags: ["AKI", "bilateral stones", "pyonephrosis"],
    exams: [
      { session: "Dec", year: 2018, marks: "10", stem: "Evaluation and management of acute renal failure due to calculous disease." },
    ],
    related: ["aki-arf-urology", "pcnl-complications", "struvite-stones"],
    references: ["EAU Urolithiasis / AKI", "KDIGO AKI", "Campbell"],
    answer: [
      { t: "ul", v: [
        "Mechanism: bilateral obstruction or obstruction of a solitary/transplant kidney; sepsis-ATN on obstruction; steinstrasse; sloughed papilla; encrusted stents; crystal nephropathy (orlistat oxalate, acyclovir, TLS urate — ‘calculous’ loosely).",
        "Life: K, pH, volume, sepsis. US/NCCT. Immediate decompression — PCN often better than stent in sepsis/hyperkalaemia (local skill). Dialyse before theatre if K/pH/volume demand it.",
        "After rescue: staged definitive stone Rx, metabolic work-up, never leave the other side unimaged.",
      ]},
      { t: "tip", k: "gold", v: "Calculous AKI is an obstructed solitary system until CT says otherwise. Drain first, stone second, dialysis if the potassium will not wait." },
    ],
  },
  {
    id: "bisphosphonates",
    topicId: "stones",
    title: "Bisphosphonates — indications and administration in urology",
    highYield: false,
    gold: false,
    tags: ["zoledronate", "denosumab", "hyperCa", "bone mets"],
    exams: [
      { session: "Dec", year: 2016, marks: "2+8", stem: "What are Bisphosphonates? Its indications and administration." },
    ],
    related: ["metabolic-evaluation", "rcc-who-subtypes", "endocrine-kidney-osteodystrophy"],
    references: ["EAU Prostate cancer / RCC supportive", "Endocrine Society hypercalcaemia"],
    answer: [
      { t: "p", v: "Pyrophosphate analogues that bind hydroxyapatite and inhibit osteoclast farnesyl-pyrophosphate synthase (nitrogenous: zoledronate, pamidronate, alendronate) or are metabolised to toxic ATP analogues (non-N: etidronate, clodronate). Net: less bone resorption, less urine calcium, lower serum Ca." },
      { t: "ul", v: [
        "Urologic indications: malignancy-related hypercalcaemia (RCC, prostate), castration-resistant prostate cancer bone mets (zoledronate 4 mg q 3–4 wk — denosumab 120 mg is an alternative), osteoporosis on ADT, rarely immobilisation hypercalciuria. Not a stone-prevention routine (they can cause low-turnover bone).",
        "Administration: zoledronate 4 mg IV over ≥15 min, eGFR-adjusted, dental check (ONJ), Ca/vitamin D replete, avoid in CrCl <30 (use denosumab or dialysis after). Flu-like acute-phase, hypocalcaemia, rare uveitis, AFF with long-term oral.",
      ]},
      { t: "tip", k: "gold", v: "Zoledronate is the urologist’s IV bone drug for hyperCa and CRPC mets. Check teeth and eGFR. Denosumab if the kidney is failing." },
    ],
  },
  {
    id: "xanthine-oxidase",
    topicId: "stones",
    title: "Xanthine oxidase inhibitors — allopurinol pharmacokinetics and urologic uses",
    highYield: true,
    gold: false,
    tags: ["allopurinol", "febuxostat", "TLS", "uric acid"],
    exams: [
      { session: "Dec", year: 2016, marks: "4+6", stem: "What are xanthine oxidase inhibitors? Indications of xanthine oxidase inhibitors in Urology and their side effects." },
      {
        session: "Jun",
        year: 2015,
        marks: "2+8",
        stem: "Enumerate xanthine oxidase inhibitors. Pharmacokinetics, pharmacodynamics, dosage and side effects of allopurinol.",
      },
    ],
    related: ["uric-acid-radiolucent", "metabolic-evaluation", "hyperoxaluria"],
    references: ["Goodman & Gilman", "EAU Urolithiasis", "AUA medical stone"],
    answer: [
      { t: "p", v: "Xanthine oxidase (XO) converts hypoxanthine → xanthine → uric acid. Inhibitors: allopurinol (and its metabolite oxypurinol), febuxostat (non-purine selective), topiroxostat (not widely available). Rasburicase is recombinant uricase (not an XO inhibitor) — mention to show you know." },
      { t: "h", v: "Allopurinol PK/PD" },
      { t: "ul", v: [
        "Oral bioavailability ~80%, t½ of parent 1–2 h, oxypurinol 15–30 h (once-daily). Renally cleared — dose-adjust in CKD.",
        "PD: suicide inhibition of XO; also weak effect on pyrimidine metabolism. Lowers serum and urine uric acid; urine xanthine rises (can form xanthine stones if overdosed in TLS/HPRT).",
        "Dose: start 100 mg, usual 200–300 mg daily; 400–600 mg in TLS prevention (or use rasburicase). Take after food, hydrate.",
      ]},
      { t: "h", v: "Urologic indications" },
      { t: "ul", v: ["Uric acid stones with hyperuricosuria.", "CaOx stones with hyperuricosuria after diet (Ettinger RCT).", "Gouty diathesis, tumour-lysis prophylaxis (haematology but urologists see urate sludge).", "2,8-DHA (APRT deficiency) — first-line.", "Lesch–Nyhan / HPRT — carefully, xanthine risk.", "Not first-line for uric acid if the only problem is pH 5 (alkali first)."], },
      { t: "h", v: "Side effects" },
      { t: "ul", v: ["Rash, pruritus; allopurinol hypersensitivity syndrome / SJS/TEN — HLA-B*5801 (Han Chinese, Thai, Korean) screen.", "Hepatitis, marrow suppression, drowsiness.", "Interaction: azathioprine/6-MP (life-threatening myelosuppression — 25% dose), ampicillin rash, warfarin.", "Febuxostat: CV signal (CARES), LFTs, use if allopurinol-intolerant and no unstable IHD."], },
      { t: "tip", k: "gold", v: "Allopurinol is for hyperuricosuria, 2,8-DHA and TLS — not a substitute for citrate in acidic urine. HLA-B*5801 and azathioprine are the two ways you kill a patient with it." },
    ],
  },
  {
    id: "diet-fluid-controversies",
    topicId: "stones",
    title: "Controversies of fluid and diet therapies for stone prevention",
    highYield: false,
    gold: false,
    tags: ["fluid", "calcium", "oxalate", "salt", "citrate"],
    exams: [
      { session: "Dec", year: 2014, marks: "10", stem: "Controversies of fluid and diet therapies for prevention of urolithiasis." },
    ],
    related: ["caox-citrate", "metabolic-evaluation"],
    references: ["Borghi NEJM fluid / diet RCTs", "EAU Urolithiasis", "AUA medical management"],
    answer: [
      { t: "tbl", h: ["Topic", "Dogma", "Controversy / evidence"], r: [
        ["Fluid volume", ">2.5–3 L urine/d", "Best-supported (Borghi). Type of fluid: water is enough; citrate drinks help; cola phosphoric acid may hurt; oxalate teas/juice mixed"],
        ["Dietary calcium", "Old advice was restriction", "Restriction raises urine oxalate (less Ca–oxalate binding in gut) and harms bone. 800–1200 mg with meals is protective (Borghi 2002). Supplements between meals may raise stone risk"],
        ["Oxalate", "Ban spinach, nuts, chocolate, tea", "Only matters in hyperoxalurics / enteric disease. Extreme bans are unsustainable; pair oxalate with dietary Ca"],
        ["Salt", "<5–6 g/d NaCl", "Natriuresis drives calciuria — less controversial than people think"],
        ["Animal protein", "Limit", "Acid load, uric acid, citrate down, calciuria up. Vegetarian vs balanced Mediterranean — both fine"],
        ["Citrate foods / lemonade", "Lemonade protocol", "Volume of lemon needed is large; K-citrate is more reliable if hypocitraturic"],
        ["Soft drinks / vitamin C", "Avoid", "Vitamin C >1 g → oxalate; cola maybe; coffee/beer were protective epidemiologically (not a prescription)"],
        ["Obesity / bariatric", "Lose weight", "Roux-en-Y causes enteric hyperoxaluria — gastric band / sleeve less so. A stone clinic must know the operation"],
        ["Thiazide + salt", "Thiazide for hypercalciuria", "Fails if salt intake remains high"],
      ]},
      { t: "tip", k: "gold", v: "The only uncontroversial diet is more water, normal calcium with meals, less salt and meat. Calcium restriction is the mistake that still walks into clinic." },
    ],
  },
  {
    id: "rirs-controversies",
    topicId: "stones",
    title: "Controversies in RIRS",
    highYield: true,
    gold: false,
    tags: ["RIRS", "access sheath", "dusting", "single-use", "sepsis"],
    exams: [
      { session: "Dec", year: 2014, marks: "10", stem: "Controversies in RIRS." },
    ],
    related: ["energy-sources-lithotripsy", "lower-pole-stone", "pcnl-variants"],
    references: ["EAU Urolithiasis", "Smith's Endourology", "CROES URS"],
    answer: [
      { t: "tbl", h: ["Controversy", "Sides", "Practical exam line"], r: [
        ["Size limit vs PCNL", "RIRS for 1–2 cm vs mini-PCNL", "≤1.5–2 cm RIRS; >2 cm mini-PCNL or staged RIRS — counsel SFR vs invasiveness"],
        ["Ureteric access sheath", "IRP down, multiple entries vs injury, stricture, cost", "Use a sheath for dusting/high-power; size 12/14; don’t force — prestent if tight"],
        ["Pre-stenting", "Passive dilatation vs extra procedure", "Not routine; yes after failed access or in a tight ureter / solitary kidney"],
        ["Dusting vs basketing", "Fine dust, no sheath trips vs residual dust, Stein-dust", "Pop-dusting + suction sheath; basket significant fragments"],
        ["Ho:YAG vs TFL", "Standard vs better dust, heat", "Both acceptable; watch irrigant temperature"],
        ["Reusable vs single-use scopes", "Cost per case vs downtime, sterility, deflection", "Single-use for tight economics of repair and for isolation cases"],
        ["Intra-renal pressure / sepsis", "Outflow vs speed", "Keep IRP low; Abx; stage if pus; don’t dust a struvite at 40 cm H2O"],
        ["Post-op stent", "Symptoms vs obstruction/steinstrasse", "Selective after uncomplicated distal URS; usual after RIRS with sheath/oedema"],
        ["Anticoagulation", "RIRS safer than PCNL on antiplatelet vs bleed", "Possible on aspirin; still reverse warfarin if you can"],
        ["Lower pole", "Relocate vs in-situ", "Relocate then treat — saves the scope"],
        ["Radiation / occupancy", "UL vs fluoroless", "ALARA, US, trained team"],
        ["Day-case / residual ‘insignificant’ fragments", "<4 mm dust", "Dust is not always innocent — image at 4–6 weeks"],
      ]},
      { t: "tip", k: "gold", v: "RIRS arguments are sheath, pressure, dust vs basket, and when to switch to mini-PCNL. Quote IRP and sepsis in every answer." },
    ],
  },
];
