import type { Master } from "../types";

export const testes: Master[] = [
  {
    id: "varicocele",
    topicId: "testes",
    title: "Varicocele — theories, MIS techniques, adolescent controversy, 45-year-old man",
    highYield: true,
    gold: true,
    tags: ["varicocele", "microsurgery", "adolescent", "infertility"],
    exams: [
      { session: "June", year: 2022, marks: "5+5", stem: "Discuss the etiopathogenesis and theories related to the development of Varicocele. Discuss the minimally invasive surgical techniques used for treatment of Varicocele." },
      { session: "Dec", year: 2014, marks: "10", stem: "Discuss the pathophysiological mechanism of varicocele-induced infertility. Mention the controversies in the management of adolescent varicocele." },
      { session: "Dec", year: 2016, marks: "5+5", stem: "Evaluation and management of varicocele in a 45 year old man." },
      { session: "Jun", year: 2021, marks: "5+5", stem: "Evaluation and management of varicocele. Describe various surgical techniques." },
    ],
    related: ["oat", "testicular-blood-supply", "chronic-orchalgia"],
    references: [
      "Campbell-Walsh-Wein, Varicocele",
      "EAU Male Infertility / Paediatric Urology",
      "AUA/ASRM Varicocele statements",
      "WHO varicocele and semen quality data",
    ],
    answer: [
      { t: "tip", k: "exam", title: "Examiner map", v: "Anatomy of left gonadal vein 1 · Theories 2 · How it hurts sperm 2 · Who to treat (adult vs adolescent vs 45-year-old) 2 · Techniques table with recurrence/hydrocele/artery-spare 3." },
      { t: "h", v: "Anatomy and epidemiology" },
      { t: "p", v: "A varicocele is an abnormal dilatation of the pampiniform plexus. Left-sided in ~90% (left gonadal vein → left renal vein at 90°; 8–10 cm longer course; nutcracker compression of LRV between SMA and aorta; absent/incompetent valves). Right gonadal vein → IVC. Isolated right varicocele is a red flag for retroperitoneal mass / situs / situs-inversus — image the retroperitoneum. Prevalence 15% of adult men, 35–40% of primary infertility, up to 80% of secondary infertility. Dubin–Amelar: Grade I Valsalva only, II palpable, III visible. Subclinical = Doppler-only; AUA/EAU do not treat subclinical varicoceles for fertility." },
      { t: "h", v: "Theories of development" },
      { t: "ul", v: [
        "Valvular incompetence of the gonadal vein (most accepted).",
        "Nutcracker: LRV compressed between SMA and aorta → left gonadal outflow obstruction. Distal nutcracker (LRV behind aorta) rarer.",
        "Right-angle insertion of left gonadal into LRV vs oblique right into IVC.",
        "Length and hydrostatic column (upright humans).",
        "Collateral overflow from adrenal/capsular veins.",
        "Secondary varicocele: obstruction of renal vein (tumour thrombus, nodes) — sudden, right, or elderly onset.",
      ]},
      { t: "h", v: "How varicocele causes infertility (Dec 14)" },
      { t: "ul", v: [
        "Scrotal hyperthermia (pampiniform counter-current cooler fails) → heat-labile enzymes, apoptosis of spermatocytes/spermatids.",
        "Reflux of adrenal/renal metabolites (catecholamines, prostaglandins) down the gonadal vein.",
        "Hypoxia and venous stasis.",
        "ROS / oxidative stress — the dominant modern pathway; raised SDF (DNA fragmentation), lipid peroxidation, poor motility and morphology (OAT pattern).",
        "Leydig-cell dysfunction → lower intratesticular T, sometimes serum T; link to hypogonadism in older men.",
        "Antisperm antibodies, epididymal dysfunction — lesser.",
        "Unilateral disease affects both testes via communicated venous pressure and shared thermal/ROS environment.",
      ]},
      { t: "h", v: "Evaluation" },
      { t: "ul", v: [
        "Standing, warm room, Valsalva. Prader volumes. Semen ×2 if fertility is the question. Morning T if hypogonadal symptoms or older man.",
        "Scrotal Doppler: vein >2.5–3 mm + reverse flow on Valsalva. Not required if Grade II–III is obvious.",
        "Adolescent: serial orchidometry / US volumes. 20% discrepancy is the usual intervention threshold when semen cannot be obtained.",
        "45-year-old: why is he here — pain, infertility (new partner), hypogonadism, or incidental? Do not operate on an incidental Grade I in a man who has finished his family and has no pain.",
      ]},
      { t: "tbl", c: "Who benefits from repair", h: ["Scenario", "Repair?"], r: [
        ["Palpable varicocele + infertility + abnormal semen, female partner potentially fertile", "Yes — AUA/EAU. Improves semen in 60–70%, pregnancy 30–50% (better than observation in meta-analyses of palpable disease). SDF falls."],
        ["Subclinical varicocele", "No"],
        ["Adolescent, palpable, >20% volume differential persistent, or pain, or abnormal semen if obtainable", "Yes, after observation of growth. Controversy: some catch up without surgery; overtreatment risk vs irreversible hypotrophy."],
        ["Adolescent, Grade III, equal volumes, no pain", "Observe 6–12 monthly. Grey zone — shared decision"],
        ["Pain attributed to varicocele after excluding other causes, failed conservative (support, NSAID)", "Yes, 50–80% pain relief; counsel failure"],
        ["45-year-old, completed family, no pain, normal T", "No"],
        ["45-year-old, symptomatic hypogonadism + large varicocele, wants to avoid TRT (or preserve residual fertility)", "Optional — T may rise 100–150 ng/dL; not a guarantee"],
        ["45-year-old with new partner / secondary infertility + OAT + palpable", "Yes, but female age dominates — do not delay ART >6–9 months if she is ≥35"],
        ["Azoospermia + palpable varicocele", "Selected (hypospermatogenesis) may see return of rare sperm; do not delay micro-TESE if female age high"],
      ]},
      { t: "h", v: "Surgical / MIS techniques (June 22, Jun 21)" },
      { t: "tbl", h: ["Approach", "Level", "Recurrence", "Hydrocele", "Pearl"], r: [
        ["Microsurgical subinguinal (Goldstein) — gold standard", "Below external ring, microscope 6–10×, spare artery (1–3) + lymphatics, ligate veins including gubernacular", "1–2%", "0.5–1%", "Best fertility outcomes. Testicular artery Doppler intra-op. Longer learning curve."],
        ["Inguinal (Ivanissevich)", "Inguinal canal", "5–15%", "3–5%", "Artery identifiable; more pain from muscle"],
        ["Open retroperitoneal Palomo (high)", "Above internal ring, mass ligation", "10–15% (misses collaterals)", "7–10%", "Artery often taken. Laparoscopic Palomo is the MIS analogue."],
        ["Laparoscopic Palomo (standard or artery-sparing)", "Transperitoneal, clip/ligate at internal ring. Lymph-spare with papavarine / methylene / ICG.", "3–6% artery-spare; lower if mass", "3–10% (falls if lymph-spare)", "Bilateral easy, paediatric MIS favourite. Misses external-spermatic / gubernacular veins. CO2, viscera."],
        ["Robot-assisted", "Same as lap", "Similar", "Similar", "Cost; no clear outcome win"],
        ["Percutaneous embolisation (coils, foam, glue) via IJ or femoral → renal → gonadal", "Vein origin", "5–15% (anatomic failure, recanalise)", "~0 hydrocele", "Local anaesthesia, no hydrocele (lymphatics untouched), radiation, coil migration, not for allergy to contrast. Salvage after surgical failure and for the unfit. Right side technically harder."],
        ["Sclerotherapy (Tauber antegrade)", "Scrotal vein cannulation", "10%", "Low", "European option"],
      ]},
      { t: "h", v: "Adolescent controversy — the paragraph" },
      { t: "p", v: "The testis is still growing. A large varicocele can cause ipsilateral hypotrophy that may not catch up. Semen analysis is often unavailable or ethically awkward in early adolescence. Treating all Grade III overtreats boys who would remain fertile; treating none risks irreversible hypotrophy and later infertility. Current compromise (EAU/AUA/AAP distilled): observe Grade I–II with equal volumes; repair if persistent >20% volume difference, pain, or (in Tanner V) abnormal semen. Use lymph-sparing Palomo laparoscopy or microsurgical subinguinal depending on surgeon. Do not embolise as first-line in a growing boy unless in a trial/expertise setting (recurrence, radiation)." },
      { t: "tip", k: "gold", v: "Treat palpable disease that is hurting fertility, growth or pain. Microsurgical subinguinal is the adult gold standard; lymph-sparing laparoscopic Palomo is the paediatric MIS workhorse. Subclinical = leave it." },
    ],
  },
  {
    id: "testicular-blood-supply",
    topicId: "testes",
    title: "Arterial supply of the testis and the blood–testis barrier",
    highYield: true,
    gold: true,
    tags: ["testicular artery", "BTB", "Sertoli", "varicocelectomy"],
    exams: [
      { session: "Dec", year: 2022, marks: "5+5", stem: "Describe briefly the arterial blood supply of testis. Briefly discuss about Blood-testis barrier, its anatomic and physiological correlates." },
    ],
    related: ["varicocele", "epididymis-vv", "gct-histology"],
    references: [
      "Campbell-Walsh-Wein, Anatomy of the testis",
      "Hinman Atlas",
      "Setchell / Dym — blood–testis barrier reviews",
    ],
    answer: [
      { t: "h", v: "Arterial supply — three arteries, one catchment" },
      { t: "tbl", h: ["Artery", "Origin", "Course", "Clinical"], r: [
        ["Testicular (internal spermatic)", "Aorta slightly below renal arteries (right longer, IVC overlap)", "Retroperitoneal, through inguinal canal in the cord, splits into internal (centripetal, trans-mediastinal) and inferior testicular branches at the posterior border. End arteries to parenchyma with some intraparenchymal anastomosis.", "Main supply. Spare at microsurgical varicocelectomy and at Fowler–Stephens (need collaterals). Origin injury in lymphadenectomy / horseshoe / Palomo."],
        ["Cremasteric (external spermatic)", "Inferior epigastric (external iliac)", "Along the cord, supplies coverings > parenchyma", "Collateral after high ligation of testicular artery (Fowler–Stephens stage 1)."],
        ["Artery to the vas (deferential)", "Inferior (sometimes superior) vesical, from internal iliac", "Along the vas, anastomoses at the caudal pole with testicular artery (caput/cauda epididymis arcade)", "The anastomosis that keeps the testis alive after Fowler–Stephens or after vasectomy + Palomo (do not combine casually — ‘testicular suicide’ if both testicular and deferential are lost)."],
      ]},
      { t: "ul", v: [
        "Intratesticular: centripetal arteries along septa toward mediastinum, then centrifugal recurrent branches. End-arterial — biopsy/TESE infarcts are real if careless.",
        "Transmediastinal artery visible on Doppler in 50% — avoid during biopsy.",
        "Capsular / tunica vasculosa is a surgical plane for micro-TESE (equatorial incision, stay in avascular windows under the microscope).",
        "Pampiniform plexus cools arterial blood (counter-current) by 2–4 °C — the physical basis of varicocele heat theory.",
        "Lymphatics: follow testicular artery to para-aortic/interaortocaval nodes — not inguinal (scrotal skin does). Hence inguinal orchidectomy with cord to the internal ring for GCT, and why scrotal violation complicates staging.",
      ]},
      { t: "h", v: "Blood–testis barrier (BTB)" },
      { t: "p", v: "The BTB is a physical, physiological and immunological barrier that sequesters post-meiotic germ cells from the immune system and controls the adluminal microenvironment. It is why post-pubertal germ cells (which appear after immune tolerance is established and express novel antigens) do not routinely trigger orchitis, and why many drugs/antibodies do not reach haploid cells." },
      { t: "ul", v: [
        "Anatomic site: specialised tight junctions (occludin, claudin-11, ZO-1, JAMs) between adjacent Sertoli cells at the basal third of the seminiferous epithelium — not primarily the capillary endothelium (testicular capillaries are actually relatively fenestrated in the interstitium). Myoid cells and the endothelium are adjunct, weaker layers.",
        "Two compartments: basal (spermatogonia, preleptotene spermatocytes — outside the BTB, accessible to blood-borne signals and the immune system) and adluminal (meiotic spermatocytes, spermatids, sperm — behind the BTB).",
        "Cyclic opening: preleptotene spermatocytes are ‘moved’ through the BTB at stages VIII–XI by a coordinated disassembly/reassembly (cytokine, testosterone, FSH, retinoic-acid dependent). This is unique among blood–tissue barriers.",
        "Physiologic correlates: (1) unique adluminal fluid — high K+, high androgen-binding protein, low glucose, specific pH; (2) immune privilege with local TGF-β, Fas ligand on Sertoli cells; (3) drug sanctuary — some chemo poorly penetrates (hence lingering germ cells after systemic therapy, and the converse — some gonadotoxins still kill basal spermatogonia); (4) breach by trauma, biopsy, torsion, infection, vasectomy → antisperm antibodies; (5) cadmium, heat, cytokines, gossypol disrupt claudins experimentally.",
        "Clinical: unexplained infertility with ASA after torsion/biopsy; why immunosuppressive privilege can be a niche for viruses (mumps orchitis after puberty is devastating); why testis is a leukaemia/lymphoma sanctuary in boys (need radiation/high-dose strategies historically).",
      ]},
      { t: "tip", k: "gold", v: "Three arteries (testicular, cremasteric, deferential) with a caudal arcade — that arcade is why Fowler–Stephens works and why vasectomy plus high Palomo is dangerous. BTB = Sertoli–Sertoli tight junctions, not the capillary." },
    ],
  },
  {
    id: "acute-scrotum",
    topicId: "testes",
    title: "Acute scrotum in adolescents and testicular torsion",
    highYield: true,
    gold: true,
    tags: ["torsion", "TWIST", "epididymo-orchitis", "appendix testis"],
    exams: [
      { session: "Jun", year: 2021, marks: "4+6", stem: "Discuss Aetio-pathogenesis of acute scrotum in adolescents and its respective management." },
      { session: "Dec", year: 2014, marks: "2+4+4", stem: "Clinical features, differential diagnosis and management of testicular torsion." },
    ],
    related: ["priapism", "chronic-orchalgia", "testicular-blood-supply"],
    references: [
      "EAU Paediatric Urology — acute scrotum",
      "Campbell-Walsh-Wein, Torsion",
      "AUA / ESPU statements",
    ],
    answer: [
      { t: "p", v: "Acute scrotum is a clinical syndrome of acute scrotal pain ± swelling/erythema. In adolescents the diagnosis that must not be missed is spermatic-cord torsion: viability falls after 6 hours and is uncommon after 24 hours. When in doubt, explore." },
      { t: "tbl", c: "Causes in adolescents", h: ["Cause", "Mechanism", "Clues", "Management"], r: [
        ["Intravaginal torsion of the cord (true testicular torsion)", "Bell-clapper (tunica vaginalis high investment) → testis free to twist. Peak 12–18 y. Also perinatal extravaginal.", "Sudden, nausea/vomit, high-riding, horizontal lie, absent cremasteric, midline raphe pulled, no relief with elevation (negative Prehn — unreliable)", "Immediate scrotal exploration. Manual detorsion (open-book, lateral) only if it does not delay theatre. Fix both sides."],
        ["Torsion of appendix testis / epididymis", "Pedunculated hydatid of Morgagni (Müllerian) twists. Peak 7–12 y.", "Blue-dot sign, localised upper-pole pain, cremasteric present, milder systemic", "NSAIDs, rest if diagnosis certain. Explore if any doubt."],
        ["Epididymo-orchitis", "Reflux, STI (gonorrhoea/chlamydia in sexually active), viral (mumps), coliforms if LUTS/anomaly", "Fever, LUTS, pyuria, Prehn may relieve, cremasteric present, Doppler hyperaemia", "Urine/NAAT, antibiotics (ceftriaxone + doxycycline if STI; enterics if not), scrotal support. Investigate the urinary tract in prepubertal / recurrent."],
        ["Incarcerated inguinal hernia", "Bowel in the sac", "Vomiting, irreducible groin+scrotum", "Urgent reduction / herniotomy"],
        ["Trauma / haematocele", "Rupture of tunica albuginea", "History, US disruption", "Explore if rupture / expanding"],
        ["Idiopathic scrotal oedema", "Allergic / cellulitic, 5–9 y", "Painless pink oedema extending to perineum, testis non-tender", "Antihistamine / observe"],
        ["Henoch–Schönlein (IgA)", "Vasculitis", "Purpura, joint, abdominal pain", "Supportive; urology if torsion still possible"],
        ["Tumour haemorrhage, Fournier, referred (ureteric stone)", "Various", "Age, toxicity, dipstick", "Cause-specific. Fournier is rare in healthy 17-year-olds."],
      ]},
      { t: "h", v: "Torsion — clinical and TWIST" },
      { t: "p", v: "TWIST score (hard testis 2, swelling 2, nausea/vomit 1, absent cremasteric 1, high riding 1): 0–2 low, 3–4 intermediate, ≥5 high. High score → theatre without Doppler. Intermediate → Doppler if immediately available. Low → observe / other diagnosis. Doppler: absent or high-resistance arterial flow, whirlpool sign of the cord. A reassuring Doppler does not override a high clinical suspicion — intermittent torsion exists." },
      { t: "h", v: "Operative management of torsion" },
      { t: "ul", n: true, v: [
        "Midline raphe or transverse scrotal incision, deliver, detorse (usually medial to lateral, but inspect the groove — detorse until colour returns).",
        "Warm sponge 5–10 min, assess viability (colour, Doppler, incision of tunica — bright bleeding). If non-viable: orchidectomy, send histology (missed tumour is rare but real).",
        "If viable: three-point dartos/tunica fixation with non-absorbable or delayed absorbable (eversion of tunica vaginalis, Jaboulay, reduces recurrence). Fix the contralateral testis in the same anaesthetic (bell-clapper is often bilateral) — counsel parents pre-op.",
        "Intermittent torsion: elective bilateral fixation after counselling.",
        "Perinatal extravaginal torsion: urgent if unilateral acute; delayed if clearly chronic ‘vanishing’ with contralateral fixation.",
      ]},
      { t: "tip", k: "gold", v: "Adolescent acute scrotum = torsion until you have a better story and a pink Doppler. Explore at 6 hours, fix both sides, do not send a TWIST-5 boy for a midday ultrasound slot." },
    ],
  },
  {
    id: "chronic-orchalgia",
    topicId: "testes",
    title: "Chronic orchalgia — causes and idiopathic management",
    highYield: false,
    gold: false,
    tags: ["orchialgia", "post-vasectomy", "spermatic cord denervation"],
    exams: [
      { session: "Dec", year: 2020, marks: "3+7", stem: "What are the causes of chronic orchalgia? How do you manage a patient with idiopathic orchalgia?" },
    ],
    related: ["varicocele", "epididymis-vv", "acute-scrotum"],
    references: [
      "Campbell-Walsh-Wein, Chronic scrotal pain",
      "EAU Chronic Pelvic Pain",
      "Levine microsurgical denervation series",
    ],
    answer: [
      { t: "p", v: "Chronic orchalgia / chronic scrotal content pain = intermittent or constant unilateral or bilateral testicular pain ≥3 months that interferes with quality of life. Idiopathic (chronic testicular pain syndrome) is a diagnosis of exclusion." },
      { t: "h", v: "Causes — classify" },
      { t: "ul", v: [
        "Post-surgical: vasectomy (congestive epididymitis, sperm granuloma, nerve entrapment — 1–6% chronic), hernia mesh, varicocelectomy, hydrocelectomy.",
        "Infective / inflammatory: chronic epididymitis, TB, brucella, STD, post-acute orchitis.",
        "Structural: varicocele, hydrocele, spermatocele, tumour (pain is uncommon — do not miss), microlithiasis is not a pain diagnosis, intermittent torsion, inguinal hernia.",
        "Referred: ureteric stone, mid-ureter, radiculopathy T10–L1, hip, AAA (older).",
        "Neuropathic / pelvic: pudendal neuralgia, CP/CPPS, pelvic-floor myofascial pain, diabetic neuropathy.",
        "Iatrogenic / other: trauma, scrotal violation, psychogenic / somatisation / depression (never the first or only label).",
        "Idiopathic after full work-up.",
      ]},
      { t: "h", v: "Evaluation before calling it idiopathic" },
      { t: "ul", v: [
        "History: vasectomy, mesh, LUTS, STI, back pain, pain with sitting (pudendal), relationship to ejaculation.",
        "Exam standing and supine, cord, epididymis, DRE, abdominal, spine. Scrotal US mandatory (tumour, occult torsion, varicocele).",
        "UA, NAAT if indicated, TB work-up if endemic / vasal beading. Do not give months of empiric fluoroquinolone without a diagnosis — this is how you create a pain + tendon-rupture patient.",
        "Diagnostic spermatic-cord block (10 mL 0.5% bupivacaine at the external ring): if pain vanishes, denervation may help; if it does not, surgery will not.",
      ]},
      { t: "h", v: "Idiopathic management — ladder" },
      { t: "ul", n: true, v: [
        "Education, scrotal support, activity modification, NSAID course, heat/cold, pelvic-floor physiotherapy (high yield when pelvic floor is tight).",
        "Neuropathic agents: amitriptyline 10–25 mg, gabapentin/pregabalin, duloxetine. Avoid long-term opioids.",
        "Treat CP/CPPS if NIH-III features (alpha-blocker, physio, not endless antibiotics).",
        "Spermatic-cord block series; consider pulsed radiofrequency in specialised units.",
        "Microsurgical subinguinal spermatic-cord denervation (MSCD, Levine): spare arterial supply, vas (or not — vasectomy if fertility complete), some lymphatics/veins; divide ilioinguinal contributions. Best if cord block predicted response. Success 70–80% significant relief in selected series. Hydrocele, atrophy, failure are the risks.",
        "Epididymectomy for post-vasectomy congested epididymis after failed conservative — mixed results.",
        "Vasectomy reversal for post-vasectomy pain — selected, fertility may return.",
        "Orchidectomy (inguinal) is last-resort and still fails in 20–50% because the pain has centralised — do not offer early. Psychological support throughout.",
      ]},
      { t: "tip", k: "exam", v: "Exclude tumour and intermittent torsion. Cord block predicts denervation. Climb the ladder; orchidectomy is not a 7-mark first move." },
    ],
  },
  {
    id: "gct-etiopath",
    topicId: "testes",
    title: "Testicular GCT — etiopathogenesis, Stage III NSGCT, BEP toxicity",
    highYield: true,
    gold: true,
    tags: ["GCNIS", "BEP", "IGCCCG", "NSGCT"],
    exams: [
      { session: "June", year: 2022, marks: "4+3+3", stem: "Discuss the etiopathogenesis and risk factors for the development of Ca testes. Describe the management of stage 3 Non seminomatous germ cell tumor. Outline the complications of BEP chemotherapy." },
    ],
    related: ["igcccg", "cs1-nsgct", "testis-markers", "rplnd", "fertility-gct"],
    references: [
      "Campbell-Walsh-Wein, Neoplasms of the testis",
      "EAU Testicular Cancer Guidelines",
      "IGCCCG 1997 and IGCCCG-Update 2021",
      "Williams / Einhorn BEP",
    ],
    answer: [
      { t: "h", v: "Etiopathogenesis and risk factors" },
      { t: "ul", v: [
        "Cell of origin: primordial germ cell / gonocyte that fails to differentiate, persisting as GCNIS (germ-cell neoplasia in situ, formerly ITGCN). GCNIS is the precursor of all type-II GCTs (seminoma and NSGCT) after puberty. Progression ~50% in 5 years if untreated.",
        "Testicular dysgenesis syndrome: cryptorchidism (RR 4–8, even the descended contralateral side is at risk), hypospadias, poor spermatogenesis share fetal origins (anti-androgenic / oestrogenic environment, genetics).",
        "Genetics: isochromosome 12p (i(12p)) is the hallmark of invasive GCT; KIT, KRAS, NANOG, OCT3/4 (POU5F1) in seminoma/GCNIS. Familial RR 4–10 (brother > father). Variants in KITLG, SPRY4, BAK1 (GWAS).",
        "Other risks: contralateral GCT (2–5%), infertility, atrophic testis, 45,X/46,XY and other DSD with Y material (gonadoblastoma → GCT), HIV (seminoma), cannabis association (weak), white ethnicity, tall stature. Microlithiasis alone is not a strong independent risk.",
        "Age: NSGCT peak 20–35, seminoma 30–45, spermatocytic tumour older (not GCNIS-derived, excellent).",
      ]},
      { t: "h", v: "Stage III NSGCT — definition and management" },
      { t: "p", v: "AJCC/UICC Stage III = regional nodes with S2–S3, or distant metastasis (non-regional nodes, lung, extra-pulmonary). IIIA = S1 + nodes/lung; IIIB = S2; IIIC = S3 or non-pulmonary visceral mets (liver, bone, brain) or mediastinal primary NSGCT. Management is risk-adapted chemotherapy first (not primary RPLND), then residual-mass surgery." },
      { t: "ul", n: true, v: [
        "Risk-stratify with IGCCCG (see next card). Good-risk Stage III (most IIIA): 3× BEP or 4× EP if bleomycin contraindicated. Intermediate (IIIB typical): 4× BEP. Poor-risk (IIIC): 4× BEP; VIP is an alternative if bleomycin unsafe; consider high-volume centres; primary high-dose chemo is not standard first-line outside trials (TIGER).",
        "Brain mets: still start systemic BEP; add stereotactic RT / surgery for residual or bleeding lesions. Do not delay chemo for whole-brain RT in NSGCT.",
        "Re-stage with CT ± markers at the end of chemo. Markers must normalise (or follow known half-lives: AFP 5–7 d, hCG 1–3 d). Rising markers = salvage (VeIP/TIP ± HD-CT), not RPLND alone.",
        "Residual retroperitoneal mass ≥1 cm after NSGCT chemo → PC-RPLND (40% necrosis/fibrosis, 40% teratoma, 10–20% viable GCT). Teratoma will not grow on chemo — it needs an operation. Residual lung/liver/mediastinal masses: resect if technically and if RP is controlled (or simultaneously in expert centres).",
        "If complete response (markers normal, no mass or <1 cm): surveillance. Relapse still salvageable.",
      ]},
      { t: "h", v: "BEP complications — write by drug" },
      { t: "tbl", h: ["Drug", "Signature toxicities", "Practical"], r: [
        ["Bleomycin", "Pulmonary fibrosis (cumulative >270–360 U), Raynaud, skin pigmentation, fever", "Stop if DLCO falls >25–30% or dry cough/crackles. Never give high-flow O2 casually in residual-mass surgery — bleomycin lung + FiO2 is a classic trap. G-CSF OK but avoid with concurrent bleomycin if possible (controversial)."],
        ["Etoposide (E)", "Myelosuppression, alopecia, secondary leukaemia (11q23, dose-related, 0.5–2%), neuropathy", "Nadir week 2. AML risk rises >2 g/m² cumulative."],
        ["Cisplatin (P)", "Nephrotoxicity, Mg wasting, ototoxicity (high-frequency, permanent), peripheral sensory neuropathy, emesis, infertility, cardiovascular late, Raynaud", "Hyperhydration + Mg. Audiometry. Neuropathy may be delayed. Secondary hypogonadism."],
        ["Regimen", "Neutropenic sepsis, thromboembolism, infertility (bank sperm before cycle 1), psychosocial", "Sperm banking is mandatory counselling. Cardiovascular follow-up lifelong. Second cancers (panc, colon, bladder, sarcoma) 1.5–2× at 20–30 y."],
      ]},
      { t: "tip", k: "gold", v: "Stage III NSGCT is chemo first, IGCCCG-dosed BEP, then operate teratoma/residual. Bank sperm before BEP. Do not give bleomycin and then a high FiO2 anaesthetic without a plan." },
    ],
  },
  {
    id: "igcccg",
    topicId: "testes",
    title: "IGCCCG risk groups and Stage IIIb NSGCT",
    highYield: true,
    gold: true,
    tags: ["IGCCCG", "good risk", "poor risk", "BEP"],
    exams: [
      { session: "Dec", year: 2021, marks: "5+5", stem: "Describe IGCCCG risk stratification for advanced germ cell tumours. Management of Stage III b NSGCT of testis." },
    ],
    related: ["gct-etiopath", "stage2-nsgct", "cs1-nsgct", "testis-markers"],
    references: [
      "IGCCCG JCO 1997",
      "IGCCCG-Update 2021 (JCO)",
      "EAU Testicular Cancer",
      "Campbell-Walsh-Wein",
    ],
    answer: [
      { t: "p", v: "IGCCCG (International Germ Cell Cancer Collaborative Group, 1997; updated 2021 with LDH as a continuous variable and better 5-year OS) stratifies metastatic GCT by primary site, metastases and marker amplitude. It applies after orchidectomy, to metastatic disease (not CS1)." },
      { t: "tbl", c: "NSGCT (includes mixed GCT with any non-seminoma component)", h: ["Risk", "Criteria (any of)", "5-y OS 1997 → 2021 update", "Chemo"], r: [
        ["Good (~60%)", "Testis or retroperitoneal primary AND no non-pulmonary visceral mets AND AFP <1000 ng/mL AND hCG <5000 IU/L AND LDH <1.5× ULN", "92% → ~95%", "3× BEP or 4× EP"],
        ["Intermediate (~25%)", "Testis/RP primary, no NPVM, AND any of AFP 1000–10,000, hCG 5000–50,000, LDH 1.5–10×", "80% → ~88%", "4× BEP"],
        ["Poor (~15%)", "Mediastinal primary OR non-pulmonary visceral mets (liver, bone, brain) OR AFP >10,000 OR hCG >50,000 OR LDH >10×", "48% → ~67% (improved)", "4× BEP (VIP if bleomycin contraindicated). High-volume centre."],
      ]},
      { t: "tbl", c: "Seminoma (AFP must be normal — else treat as NSGCT)", h: ["Risk", "Criteria", "Chemo"], r: [
        ["Good (~90%)", "Any primary, any marker (hCG/LDH), no non-pulmonary visceral mets", "3× BEP or 4× EP"],
        ["Intermediate", "Non-pulmonary visceral mets", "4× BEP"],
        ["Poor", "Does not exist in IGCCCG seminoma", "—"],
      ]},
      { t: "h", v: "Stage IIIb NSGCT" },
      { t: "p", v: "AJCC IIIb = N1–3 M0–1a S2, i.e. S2 markers (AFP 1000–10,000 or hCG 5000–50,000 or LDH 1.5–10×) with RP nodes and/or pulmonary mets, without extra-pulmonary visceral mets. This is IGCCCG intermediate-risk disease." },
      { t: "ul", v: [
        "Standard: 4 cycles of BEP (cisplatin 20 mg/m² D1–5, etoposide 100 mg/m² D1–5, bleomycin 30 U D1,8,15; q21d). If bleomycin unsafe (age, COPD, smoker, planned extensive thoracic surgery): 4× VIP or 4× EP is a compromise (EP is good-risk standard; for intermediate, BEP 4 is preferred).",
        "Do not debulk before chemo in marker-positive bulky NSGCT.",
        "Post-chemo: if markers normal and residual RP ≥1 cm → PC-RPLND. Residual extra-RP masses resected in selected patients. If markers persist → salvage chemo, not desperate surgery first (unless growing teratoma: masses grow, markers down — operate).",
        "Follow-up per EAU: intensive years 1–2 (relapse window), then de-escalate. Survivorship: hearing, renal, CV, second cancer, hypogonadism, fertility.",
      ]},
      { t: "tip", k: "gold", v: "Memorise the marker cut-offs 1,000 / 10,000 AFP and 5,000 / 50,000 hCG. IIIb = S2 = intermediate = 4 BEP then residual-mass surgery." },
    ],
  },
  {
    id: "cs1-nsgct",
    topicId: "testes",
    title: "Clinical Stage I NSGCT — surveillance vs chemo vs RPLND",
    highYield: true,
    gold: true,
    tags: ["CS1", "LVI", "BEP", "RPLND"],
    exams: [
      { session: "Jun", year: 2020, marks: "3+3+4", stem: "Indications, advantages and disadvantages of chemotherapy in Clinical Stage I NSGCT." },
      { session: "Dec", year: 2020, marks: "3+3+4", stem: "What are the treatment options for treatment of clinical stage I Non-seminoma germ cell tumor? What is their rationale? What are their advantages and disadvantages?" },
    ],
    related: ["igcccg", "rplnd", "gct-histology", "fertility-gct"],
    references: [
      "EAU Testicular Cancer — CS1 NSGCT",
      "SWENOTECA; Albers / German Testicular Cancer Study Group RPLND vs BEP",
      "Campbell-Walsh-Wein",
    ],
    answer: [
      { t: "p", v: "CS1 NSGCT = pT1–4 N0 M0 S0 after inguinal orchidectomy (markers normalised at expected half-life). Occult RP mets exist in ~30% overall: ~15% if LVI− (low risk), ~50% if LVI+ / pT2 (high risk). Three equal EAU options — the art is matching the man to the relapse-risk and the toxicity he will accept." },
      { t: "tbl", h: ["Option", "Rationale", "Relapse", "Advantages", "Disadvantages"], r: [
        ["Active surveillance (preferred for low-risk; acceptable for high-risk if compliant)", "Avoid treatment in the 50–85% who are already cured by orchidectomy. Salvage at relapse with 3× BEP is extremely effective (CSS >98%).", "15% LVI− / 50% LVI+", "No chemo toxicity, no ejaculatory loss, cheapest initially, fertility preserved", "Intensive CT (radiation), anxiety, 3× BEP if relapses (more chemo than adjuvant 1×), compliance critical. Not for the non-compliant or countries without reliable follow-up."],
        ["Adjuvant chemo: 1× BEP (standard) or 2× BEP (older)", "Treats occult micromets. 1× BEP drops relapse from 50% → ~3% in high-risk (SWENOTECA).", "~1–5%", "Highest chance of never relapsing; simple; fertility often recovers; no surgical ejaculatory risk", "Overtreatment of 50–85%. BEP toxicities (bleomycin lung, neuropathy, CV, second malignancy — smaller with 1 cycle but not zero). Salvage of the rare relapser is harder."],
        ["Primary nerve-sparing RPLND (template) at a high-volume centre", "Pathologic staging. If pN0, relapse <5–10% (usually pulmonary). If pN1 small-volume, may be therapeutic without chemo (30% still need chemo if pathology adverse).", "RP <1–2% if done well; overall 10%", "Avoids chemo in most; treats teratoma (chemo-blind) that would have been occult; staging gold standard", "Over-treatment of 50–85%; expert surgeon required (otherwise in-field recurrence); ileus, chyle, hernia, 5–10% RE even with nerve-spare; if pN+ may still need 2× BEP. Not first-line in most European pathways; more North American."],
      ]},
      { t: "h", v: "How to choose (write this)" },
      { t: "ul", v: [
        "LVI− / compliant / access to CT: surveillance is the EAU preferred default.",
        "LVI+ : offer 1× BEP or surveillance; RPLND if teratoma-heavy primary, relative chemo contraindication, or patient declines chemo and wants lowest RP-relapse.",
        "Vascular invasion, embryonal predominance (>50%), rete testis invasion — high-risk features (LVI is the strongest).",
        "Always: sperm bank before adjuvant BEP or RPLND, Tanner/T, contralateral exam, GCNIS discussion.",
      ]},
      { t: "tip", k: "gold", v: "CS1 NSGCT CSS is ~99% whichever path is chosen. The decision is about toxicity and compliance, not about survival. Quote LVI 50% vs 15% occult disease." },
    ],
  },
  {
    id: "gct-histology",
    topicId: "testes",
    title: "Histology of GCT, testis-sparing surgery, contralateral biopsy",
    highYield: true,
    gold: false,
    tags: ["WHO histology", "TSS", "GCNIS", "frozen section"],
    exams: [
      { session: "Dec", year: 2020, marks: "4+3+3", stem: "Describe the histological classification of testicular germ cell tumors. What are the indications of testis-sparing surgery in a patient with testicular neoplasm? What are the indications of contralateral testis biopsy in the same context?" },
    ],
    related: ["gct-etiopath", "testis-markers", "fertility-gct"],
    references: [
      "WHO Classification of GU tumours, 5th ed. 2022",
      "EAU Testicular Cancer — organ-sparing / contralateral biopsy",
      "Heidenreich TSS series",
    ],
    answer: [
      { t: "h", v: "WHO / practical histologic classification" },
      { t: "tbl", h: ["Group", "Entities", "Exam pearls"], r: [
        ["GCNIS-derived, type II", "Seminoma; NSGCT: embryonal carcinoma, yolk-sac tumour (post-pubertal), choriocarcinoma, teratoma (post-pubertal), mixed GCT, trophoblastic variants", "i(12p). Mixed is common. Any non-seminoma component → manage as NSGCT. AFP = yolk sac; hCG = syncytiotrophoblast / chorio."],
        ["Related", "Regressed (‘burnt-out’) GCT, GCNIS", "Metastatic GCT with a scar in the testis"],
        ["Non-GCNIS germ-cell", "Spermatocytic tumour (older men, excellent, rarely metastasises); prepubertal-type teratoma and yolk sac (different biology, no GCNIS, usually benign teratoma in child)", "Do not give BEP to a spermatocytic tumour"],
        ["Sex-cord / stromal", "Leydig, Sertoli, granulosa, unclassified", "10% malignant; TSS often appropriate"],
        ["Other", "Lymphoma (older, bilateral), mets, adenomatoid, epidermoid cyst, NET, paratesticular rhabdo/sarcoma, mesothelioma of tunica", "Lymphoma is the commonest testicular tumour >60 y"],
      ]},
      { t: "h", v: "Testis-sparing surgery (TSS)" },
      { t: "ul", v: [
        "Indications (EAU): (1) solitary testis or bilateral tumours; (2) high likelihood of benign lesion (small, well-circumscribed, negative markers, epidermoid, Leydig on frozen); (3) selected GCT in a solitary testis if tumour is small (classically ≤2 cm), easily resectable with a rim of normal parenchyma, negative frozen margins, and the man accepts possible local recurrence / completion orchidectomy / adjuvant XRT for GCNIS; (4) strong fertility / hormone-preservation wish in the above settings.",
        "Not for: normal contralateral testis + unequivocal GCT — radical inguinal orchidectomy remains standard (EAU).",
        "Technique: inguinal approach (not scrotal), cord occluded with a soft clamp / tourniquet, ice, frozen-section, tunica incision over the mass, bed biopsies for GCNIS, send the mass. If frozen = GCT and contralateral testis is normal → convert to radical orchidectomy. If GCNIS in the remnant → 18–20 Gy adjuvant RT (will sterilise the remnant — bank sperm first) or completion orchidectomy or close surveillance in selected fertility-seeking men.",
        "Onco-TESE at the same time if azoospermic.",
      ]},
      { t: "h", v: "Contralateral testicular biopsy" },
      { t: "p", v: "GCNIS prevalence in the contralateral testis is ~5% (higher if testis <12 mL, age <40, cryptorchidism). Biopsy (double biopsy, fix in Stieve/Bouin, OCT3/4 / PLAP / D2-40 IHC) allows 18–20 Gy RT that prevents a second GCT but causes sterility of that testis." },
      { t: "ul", v: [
        "EAU: offer contralateral biopsy in high-risk men — contralateral volume <12 mL, history of cryptorchidism, or age <40 with additional risk — at the time of orchidectomy. Not mandatory in all (US practice often skips routine biopsy and uses surveillance US).",
        "If GCNIS: counsel RT vs delayed orchidectomy vs surveillance (especially if fertility not yet banked / completed). RT 18–20 Gy in 10 fractions; androgen failure in a minority (Leydig more radioresistant than germ cells).",
        "Do not biopsy a contralateral testis that is clinically and sonographically normal in a low-risk man who will be followed — the number-needed-to-biopsy is high and fertility cost of RT is real.",
      ]},
      { t: "tip", k: "exam", v: "List seminoma vs NSGCT components + spermatocytic as the odd one. TSS = solitary testis / suspected benign / selected small GCT. Contralateral biopsy = high-risk only, because the treatment (RT) sterilises." },
    ],
  },
  {
    id: "testis-markers",
    topicId: "testes",
    title: "Tumour markers in testicular germ-cell tumours",
    highYield: true,
    gold: true,
    tags: ["AFP", "hCG", "LDH", "S stage", "miR-371"],
    exams: [
      { session: "Jun", year: 2019, marks: "10", stem: "Role of tumour markers in management of germ cell tumour of testis." },
      { session: "Dec", year: 2016, marks: "3+7", stem: "Tumor markers for testicular tumors and their clinical relevance." },
      { session: "Dec", year: 2018, marks: "4+3+3", stem: "Biomarkers of testicular cancer-Role in diagnosis, management and follow up." },
    ],
    related: ["igcccg", "gct-etiopath", "cs1-nsgct"],
    references: [
      "EAU Testicular Cancer",
      "AJCC 8th TNM S-staging",
      "IGCCCG",
      "miR-371a-3p literature (Dieckmann / Nappi)",
    ],
    answer: [
      { t: "tbl", c: "Classic serum markers", h: ["Marker", "Source", "Half-life", "Causes of elevation"], r: [
        ["AFP (α-fetoprotein)", "Yolk-sac; some embryonal. Never pure seminoma or choriocarcinoma or teratoma (mature).", "5–7 days", "GCT; hepatocellular ca; liver regeneration; pregnancy; infancy. If ‘seminoma’ has AFP → it is NSGCT."],
        ["β-hCG", "Syncytiotrophoblast (seminoma 10–30% modest; choriocarcinoma massive; embryonal moderate)", "24–36 h", "GCT; marijuana (mild); hypogonadism (pituitary hCG); immunoassay cross-talk. Very high hCG → chorio, hyperthyroidism (TSH homology), gynaecomastia."],
        ["LDH", "Bulk / GCT burden, not lineage-specific", "—", "Any necrosis, haemolysis, liver, muscle. Prognostic in IGCCCG, noisy in follow-up."],
        ["PLAP", "Seminoma / GCNIS (IHC more than serum)", "—", "Smokers — serum PLAP useless in smokers"],
      ]},
      { t: "h", v: "S-stage (AJCC) — after orchidectomy, using nadir" },
      { t: "ul", v: [
        "SX unknown; S0 normal; S1 AFP <1000, hCG <5000, LDH <1.5×; S2 AFP 1000–10,000, hCG 5000–50,000, LDH 1.5–10×; S3 above those. S-stage feeds Stage I vs IS vs II/III and IGCCCG.",
        "Wait for appropriate half-lives before declaring CS1. Persistent marker = Stage IS → treat as metastatic (chemo), not as a surgical failure of orchidectomy (unless a residual scrotal/cord mass explains it).",
      ]},
      { t: "h", v: "Role by phase of care" },
      { t: "ul", v: [
        "Diagnosis: do not delay orchidectomy for a marker; they support but do not replace histology. A man with a testicular mass and sky-high hCG still needs the testis off (and sperm bank, and contralateral exam) before or with chemo — except the rare immediately life-threatening choriocarcinoma syndrome / brain bleed where chemo starts same day.",
        "Staging / risk: IGCCCG cut-offs are marker-defined. Marker-only disease exists.",
        "During chemo: falling at half-life = responding. Plateau or rise = growing teratoma (mass up, markers down/stable — operate) vs chemoresistance (markers up — salvage).",
        "Post-chemo residual: normal markers + mass in NSGCT still needs PC-RPLND (≥1 cm) because of teratoma/viable GCT. Seminoma residual PET-negative <3 cm can be watched (SEMPET).",
        "Follow-up: AFP/hCG at each visit. Isolated LDH rise is a trap. Relapse can be marker-negative (teratoma, some seminoma) — need imaging too.",
        "Prognosis: extreme hCG — choriocarcinoma syndrome (bleed in lung/brain at start of chemo; consider staggered bleomycin and ICU).",
      ]},
      { t: "h", v: "Emerging: miR-371a-3p" },
      { t: "p", v: "Circulating microRNA (miR-371a-3p) has sensitivity/specificity far above AFP/hCG for viable GCT (not teratoma, not GCNIS reliably). Potential: CS1 risk, residual-mass viable GCT vs necrosis, earlier relapse. Not yet a replacement for PC-RPLND decisions in every guideline iteration — mention as the biomarker advance (Dec 18 ‘biomarkers’ stem)." },
      { t: "tip", k: "gold", v: "AFP never seminoma. Half-lives AFP 5–7 d, hCG 1–3 d. S2/S3 = IGCCCG intermediate/poor. Teratoma is marker-negative and chemo-blind." },
    ],
  },
  {
    id: "stage2-nsgct",
    topicId: "testes",
    title: "Stage II NSGCT — definition and management",
    highYield: true,
    gold: false,
    tags: ["Stage II", "RPLND", "BEP"],
    exams: [
      { session: "Dec", year: 2019, marks: "3+7", stem: "Define stage II non-seminomatous germ cell tumour and discuss management options." },
    ],
    related: ["igcccg", "rplnd", "cs1-nsgct", "gct-etiopath"],
    references: ["EAU Testicular Cancer", "AJCC 8th", "Campbell-Walsh-Wein"],
    answer: [
      { t: "p", v: "Stage II NSGCT = metastatic disease confined to retroperitoneal (regional) nodes, M0. IIA: nodes ≤2 cm (N1), S0–S1. IIB: >2–5 cm (N2), S0–S1. IIC: >5 cm (N3) or S2 with regional nodes. (If S3 or extra-RP mets → III.)" },
      { t: "tbl", h: ["Substage", "Preferred", "Alternative"], r: [
        ["IIA, markers negative, small nodes (equivocal 1 cm)", "Options: (1) 3× BEP or 4× EP then residual surgery if ≥1 cm; (2) primary nerve-spare RPLND (if true IIA, pN1 may avoid chemo; if pN0 you staged him). A short period of repeat imaging can sort inflammatory nodes in selected S0 IIA.", "Do not observe true marker-positive IIA."],
        ["IIA/IIB marker-positive or IIB", "3–4× BEP (good vs intermediate IGCCCG — most IIA/B are good-risk → 3 BEP) then PC-RPLND for residual ≥1 cm", "Primary RPLND only in specialised S0 IIA"],
        ["IIC", "Chemo first (almost always intermediate or bulky good-risk: 3–4 BEP) then PC-RPLND — residual is common and often teratoma", "Primary surgery inappropriate"],
      ]},
      { t: "p", v: "Post-chemo residual ≥1 cm in NSGCT is operated (full bilateral template in residual bulky disease; modified templates only in highly selected small unilateral residual at expert centres). Nerve-sparing when feasible. If residual viable GCT >10% in the specimen, adjuvant 2 cycles of EP/TIP is often given. Growing-teratoma syndrome: operate, do not escalate chemo." },
      { t: "tip", k: "exam", v: "Define IIA/IIB/IIC. IIA S0 can be RPLND or chemo; everything bulkier or marker-positive is chemo then residual-mass surgery." },
    ],
  },
  {
    id: "rplnd",
    topicId: "testes",
    title: "Lymphatic spread of testicular GCT and RPLND",
    highYield: true,
    gold: true,
    tags: ["RPLND", "template", "nerve-sparing", "PC-RPLND"],
    exams: [
      { session: "Jun", year: 2016, marks: "5+5", stem: "Lymphatic spread of testicular germ cell tumour. Role of RPLND in testicular tumour." },
    ],
    related: ["cs1-nsgct", "stage2-nsgct", "gct-etiopath", "anejaculation"],
    references: [
      "Campbell-Walsh-Wein, RPLND",
      "Donohue / Einhorn / Sheinfeld templates",
      "EAU Testicular Cancer",
    ],
    answer: [
      { t: "h", v: "Lymphatic spread" },
      { t: "ul", v: [
        "Testis lymphatics follow the gonadal vessels to the retroperitoneum, not to the inguinal nodes (inguinal only if scrotal violation, prior scrotal surgery, or tunica/scrotal invasion).",
        "Right testis: first-echelon = interaortocaval (and precaval, paracaval) at L1–3, around the right renal hilum. Crossing to the left occurs but usually after the primary landing zone is involved.",
        "Left testis: first-echelon = para-aortic (preaortic, left renal hilum) below the left renal vein. Crossover to the right is less common as a first step.",
        "Cranial spread: retrocrural, mediastinal, supraclavicular (Virchow) — more in advanced disease; thoracic duct.",
        "Caudal: iliac is not first-echelon unless cord involvement / scrotal violation / prior pelvic surgery — templates classically spare pelvis.",
        "Seminoma is more radiosensitive and more often purely lymphatic; NSGCT haematogenous (lung) earlier, and teratoma follows lymphatics as a chemo-resistant passenger.",
      ]},
      { t: "h", v: "RPLND — roles" },
      { t: "tbl", h: ["Setting", "Role"], r: [
        ["Primary RPLND in CS1 NSGCT", "Staging + therapy; nerve-spare modified template. High-volume centres. See CS1 card."],
        ["Primary RPLND in CS IIA S0 NSGCT", "Therapeutic for low-volume; avoid chemo if pN1 and no extra adverse features"],
        ["Post-chemo RPLND (NSGCT residual ≥1 cm)", "Mandatory consideration — necrosis vs teratoma vs viable GCT. Full bilateral template for residual bulky disease. The commonest current indication."],
        ["Seminoma residual", "Rarely; PET-positive or growing masses after chemo. Desperation RPLND is morbid (desmoplasia)."],
        ["Growing teratoma / late relapse", "Surgery is the treatment; late relapse often needs expert redo RPLND ± salvage chemo if viable GCT"],
        ["Desperation / salvage RPLND", "Marker-positive after salvage chemo — selected, if a resectable solitary site"],
      ]},
      { t: "h", v: "Technical pearls for the answer" },
      { t: "ul", v: [
        "Approach: midline transperitoneal (standard), thoracoabdominal (left high), or robotic/lap in selected primary CS1 (not for post-chemo bulky).",
        "Modified templates (Donohue): right = ureter to ureter including interaortocaval, from renal vessels to IMA / bifurcation; left = ureter to mid-aorta, renal to IMA. Full bilateral if post-chemo residual or grossly positive nodes.",
        "Nerve-sparing: preserve post-ganglionic sympathetic fibres (hypogastric plexus around aortic bifurcation, L2–4 chains lateral to aorta). Prospective nerve-spare → antegrade ejaculation ~90–95% in primary RPLND; post-chemo harder.",
        "Split-and-roll of lumbar vessels on the IVC/aorta. Lumbar arteries/veins ligated as needed.",
        "Complications: ileus, chylous ascites (fat-free diet, drain, TPN, somatostatin; lymphangiography/embolise if persistent), haemorrhage, ureteric injury, ventral hernia, RE, atelectasis, PE. Post-chemo: desmoplasia, especially after seminoma, and bleomycin lung + fluids/O2.",
      ]},
      { t: "tip", k: "gold", v: "Right lands interaortocaval, left para-aortic. Inguinal is wrong unless scrotal violation. PC-RPLND for NSGCT residual ≥1 cm is the money indication." },
    ],
  },
  {
    id: "fertility-gct",
    topicId: "testes",
    title: "Fertility preservation in testicular cancer",
    highYield: true,
    gold: false,
    tags: ["sperm banking", "onco-TESE", "BEP", "GCNIS RT"],
    exams: [
      { session: "Jun", year: 2017, marks: "10", stem: "Preservation of male fertility in cases with testicular tumor." },
    ],
    related: ["sperm-retrieval", "oat", "gct-histology", "cs1-nsgct"],
    references: [
      "EAU Testicular Cancer — fertility",
      "ASCO / ASRM fertility preservation",
      "Campbell-Walsh-Wein",
    ],
    answer: [
      { t: "p", v: "Half of GCT patients have abnormal semen at diagnosis (dysgenesis, contralateral GCNIS, tumour cytokines). BEP and retroperitoneal treatment add gonadotoxicity and ejaculatory failure. Fertility preservation is not optional counselling — it is part of Day-0 management, and it must not delay orchidectomy by more than 24–48 h." },
      { t: "ul", n: true, v: [
        "Before orchidectomy: offer semen cryopreservation (1–3 samples). If azoospermic or the only testis is being removed: onco-TESE at orchidectomy (from the tumour-bearing testis away from tumour, and/or contralateral if exploring). Do not wait 2 weeks for three samples if the tumour is exploding — one sample + onco-TESE is enough.",
        "Before chemo / RT / RPLND: bank if not already done. 1× BEP still warrants a bank (recovery usual but not guaranteed). Carboplatin AUC7 for seminoma CS1 — still offer a bank.",
        "If already on TRT for hypogonadism — stop; that is not this patient usually.",
        "During treatment: condoms (etoposide mutagenic); delay conception 12 months after BEP (sperm aneuploidy window) and 6–12 months after last treatment is a common counsel (evidence not perfect).",
        "Contralateral GCNIS RT 18–20 Gy will sterilise that testis — bank before RT, or offer onco-TESE first, or defer RT if actively trying with close US follow-up.",
        "Nerve-spare RPLND preserves emission; template and expertise matter. If RE/anejaculation: PVS/EEJ/SSR as on the anejaculation card.",
        "Post-treatment: semen analysis at 12–24 months before declaring permanent sterility; late recovery occurs. Hypogonadism → T replacement after the fertility plan is closed.",
        "Children conceived after GCT treatment do not have a clinically meaningful increase in congenital anomalies in large registries — reassure. PGT is not routine.",
        "If no sperm ever: donor, adoption, remaining child-free.",
      ]},
      { t: "tip", k: "gold", v: "Bank first, operate/chemo second. Onco-TESE at orchidectomy if the ejaculate is empty. RT for GCNIS is a sterilising dose — say so before the linear accelerator is booked." },
    ],
  },
  {
    id: "cuavd",
    topicId: "testes",
    title: "Unilateral absence of the vas deferens — embryology and associated anomalies",
    highYield: true,
    gold: false,
    tags: ["CUAVD", "CBAVD", "CFTR", "renal agenesis"],
    exams: [
      { session: "Dec", year: 2017, marks: "5+5", stem: "Embryology of unilateral absence of vas deferens and associated anomalies seen in this condition." },
    ],
    related: ["genetic-male-infertility", "obstructive-azoospermia", "ectopic-ureter"],
    references: [
      "Campbell-Walsh-Wein, Congenital anomalies of the vas",
      "EAU Male Infertility — CBAVD",
      "Schlegel / McCallum CUAVD vs CFTR series",
    ],
    answer: [
      { t: "h", v: "Embryology" },
      { t: "p", v: "The vas deferens, epididymis (corpus/cauda), seminal vesicle and ejaculatory duct derive from the Wolffian (mesonephric) duct. The ureteric bud arises from the mesonephric duct near the cloaca (weeks 4–5) and induces the metanephric mesenchyme to form the kidney. Hence a very early mesonephric insult (before or at ureteric-bud take-off) produces ipsilateral vasal aplasia AND ipsilateral renal agenesis / ectopia. A later, isolated, more caudal Wolffian lesion (or a CFTR-related luminal obliteration) can leave the kidney intact." },
      { t: "ul", v: [
        "Testis is from genital ridge + PGCs — therefore present and often fertile on that side (spermatogenesis intact; the block is conductive). The caput epididymis (efferent ducts) is mesonephric tubular remnants plus a contribution from the rete — often present as a caput remnant in CBAVD.",
        "CFTR-related CBAVD: bilateral, kidneys present, SV atretic, acidic azoospermic semen. CUAVD is only sometimes CFTR.",
      ]},
      { t: "h", v: "Associated anomalies" },
      { t: "tbl", h: ["Finding", "Why it matters"], r: [
        ["Ipsilateral renal agenesis (~20–80% of CUAVD depending on series; much higher than CBAVD)", "Renal US is mandatory. Solitary kidney counselling, protect the remaining kidney, avoid cavalier ureteroscopy on that side later."],
        ["Ipsilateral SV absence / hypoplasia, ectopic ureter remnant", "TRUS/MRI if infertility work-up"],
        ["Crossed fused ectopia, pelvic kidney", "Same mesonephric field defect"],
        ["CFTR mutations (~20–40% of CUAVD vs ~80% of CBAVD)", "Still test CFTR in CUAVD men who are infertile or have a contralateral vasal anomaly / OAT. Partner screen if a mutation is found."],
        ["Contralateral vasal atresia / epididymal obstruction / Zinner syndrome (SV cyst + ipsilateral renal agenesis + obstruction)", "Zinner = the symptomatic adult presentation of this embryology (pain, infertility, perineal cyst)"],
        ["Cryptorchidism, hernia, VACTERL-type associations — less specific", "Full GU exam"],
      ]},
      { t: "h", v: "Clinical actions" },
      { t: "ul", v: [
        "Palpate both vasa in every infertile man and every paediatric GU exam.",
        "CUAVD + normal contralateral vas + normal semen: incidental; image the kidney; CFTR optional.",
        "CUAVD + infertility: evaluate the contralateral side (partial obstruction, varicocele, testis) and CFTR; PESA from the side that produces sperm.",
        "Do not reconstruct an absent vas.",
      ]},
      { t: "tip", k: "gold", v: "Early mesonephric insult = no vas + no kidney. CFTR = no vas + yes kidney. Every CUAVD gets a renal ultrasound." },
    ],
  },
  {
    id: "sertoli-only",
    topicId: "testes",
    title: "Sertoli-cell-only syndrome (germinal cell aplasia)",
    highYield: false,
    gold: false,
    tags: ["SCOS", "NOA", "micro-TESE", "AZFa"],
    exams: [
      { session: "Dec", year: 2016, marks: "3+3+4", stem: "Clinical and laboratory findings and management of Sertoli cell only syndrome (Germinal cell aplasia)." },
    ],
    related: ["noa-genetics", "sperm-retrieval", "klinefelter"],
    references: [
      "Campbell-Walsh-Wein, Testicular histopathology in infertility",
      "EAU Male Infertility",
      "Schlegel micro-TESE in SCOS",
    ],
    answer: [
      { t: "p", v: "Sertoli-cell-only syndrome (SCOS, Del Castillo, germ-cell aplasia) is a histologic diagnosis: seminiferous tubules populated by Sertoli cells without germ cells, typically with reduced tubular diameter and Leydig-cell hyperplasia in the interstitium. It is a pattern, not a single disease. Focal SCOS with islands of spermatogenesis is common in idiopathic NOA — which is why a diagnostic biopsy without retrieval under-stages the testis and why micro-TESE can still find sperm." },
      { t: "h", v: "Clinical" },
      { t: "ul", v: [
        "Normal virilisation in post-pubertal acquired/idiopathic SCOS (Leydig cells work). Small-soft testes if congenital / Klinefelter / cryptorchid.",
        "Azoospermia. Libido usually preserved unless concurrent hypogonadism.",
        "History: idiopathic, chemo/XRT, cryptorchidism, AZFa, 46,XX testicular DSD, viral orchitis, torsion of a solitary testis.",
      ]},
      { t: "h", v: "Laboratory" },
      { t: "ul", v: [
        "FSH high (no inhibin B from germ/Sertoli interaction); inhibin B low; LH ± high; T normal or low-normal.",
        "Karyotype + Y-microdeletion mandatory. AZFa predicts uniform SCOS and zero retrieval. 47,XXY has SCOS-like histology with hyalinisation.",
        "Do not need a standalone biopsy to ‘prove’ SCOS if you are proceeding to micro-TESE — the wet prep is the biopsy.",
      ]},
      { t: "h", v: "Management" },
      { t: "ul", v: [
        "No drug restores germ cells in uniform SCOS.",
        "micro-TESE + ICSI: retrieval 20–40% because many ‘SCOS’ testes are mosaic. AZFa / 46,XX male: do not operate.",
        "Donor sperm, adoption, child-free. TRT if hypogonadal after the fertility plan.",
        "Genetic counselling as per NOA card.",
      ]},
      { t: "tip", k: "exam", v: "High FSH, azoospermia, small testes. Histology is a pattern. micro-TESE unless AZFa. Do not offer gonadotrophins (those are for HH)." },
    ],
  },
  {
    id: "epididymis-vv",
    topicId: "testes",
    title: "Epididymis anatomy and physiology; vasectomy reversal",
    highYield: true,
    gold: false,
    tags: ["epididymis", "vasovasostomy", "vasoepididymostomy"],
    exams: [
      { session: "Jun", year: 2015, marks: "3+3+4", stem: "Anatomy and physiology of epididymis. Surgical methods which are used for vasectomy reversal." },
    ],
    related: ["obstructive-azoospermia", "sperm-retrieval", "testicular-blood-supply"],
    references: [
      "Campbell-Walsh-Wein, Epididymis and vasectomy reversal",
      "Silber / Belker / Goldstein",
      "Hinman Atlas",
    ],
    answer: [
      { t: "h", v: "Anatomy" },
      { t: "ul", v: [
        "Caput, corpus, cauda. A single 5–6 m coiled tubule (4–6 m) of 0.2 mm diameter, invested in tunica. Efferent ductules (10–15) from rete testis → caput (the only segment with multiple tubules). Corpus and cauda = the single convoluted ductus epididymis → vas at the cauda (vas has a muscular wall and a star-shaped lumen).",
        "Blood: epididymal branches of testicular artery; cauda also from deferential artery. Lymph with testis (para-aortic). Nerve: sympathetic for emission.",
        "Appendices: appendix epididymis (Wolffian), appendix testis (Müllerian, hydatid of Morgagni) — torsion of the latter is the blue-dot.",
      ]},
      { t: "h", v: "Physiology" },
      { t: "ul", v: [
        "Transit 2–6 days. Caput: fluid resorption (70–90% of rete fluid) via aquaporins/estrogens — hence caput obstruction = ‘full’ caput. Corpus: maturation (motility acquisition, membrane remodelling, decapacitation factors, disulphide bonding of chromatin). Cauda: storage in a quiet, acidic, high-carnitine, high-glycerophosphocholine milieu; emission empties it.",
        "α-glucosidase in semen is an epididymal marker (low in OA at epididymis).",
        "Temperature and androgen (via luminal ABP and DHT) dependent. Varicocele and fever hit epididymal function as well as the testis.",
      ]},
      { t: "h", v: "Vasectomy reversal — methods" },
      { t: "ul", v: [
        "Counselling: obstructive interval, female age, prior children, antisperm Ab, need for ICSI anyway. Patency and pregnancy fall after 3, 8, 15 years but never to zero. Offer simultaneous sperm freeze.",
        "Vasovasostomy when proximal vas fluid has sperm or is copious/clear (Silber). Modified one-layer or two-layer 9-0/10-0 under the microscope; microdot alignment; no stent. Multilayer is about mucosa-to-mucosa, not the number of knots.",
        "Vasoepididymostomy when vasal fluid is thick and sperm-negative (epididymal blow-out from back-pressure, more likely with long obstructive interval). End-to-side 2- or 4-suture intussusception of a single epididymal tubule into the vas. Pick the lowest level that still has sperm.",
        "Inguinal vasectomy / hernia mesh: inguinal VV, sometimes crossed (trans-scrotal) VV if one abdominal vas is gone.",
        "Robotic reversal is a tool, not a new anastomosis.",
        "Follow-up semen at 6–8 weeks, then 3-monthly. Late stricture happens. If azoo after reversal → PESA/TESE/ICSI using the banked sample.",
      ]},
      { t: "tip", k: "gold", v: "Epididymis = one tubule, maturation + storage. Reversal = microscope, VV if sperm in the vas fluid, VE if not, and always freeze sperm." },
    ],
  },
];
