import type { TopicMeta } from "./types";

export const TOPICS: TopicMeta[] = [
  {
    id: "basics",
    title: "Basic principles",
    short: "POD, fluids, GFR, pneumoperitoneum",
    blurb: "Physiology, electrolytes, GFR, pneumoperitoneum and tumour biology that examiners recycle every paper.",
    chapter: "Campbell-Walsh-Wein · Physiology",
  },
  {
    id: "drugs",
    title: "Drugs in urology",
    short: "Antimuscarinics, antibiotics, diuretics",
    blurb: "Receptor pharmacology, stewardship and surgical prophylaxis as asked in 10-mark stems.",
    chapter: "EAU / AUA antimicrobial · Goodman & Gilman",
  },
  {
    id: "evaluation",
    title: "Urologic evaluation",
    short: "Imaging, UDS, contrast, PET",
    blurb: "From dual-energy CT and PSMA-PET to urodynamics, CIN and radiation protection.",
    chapter: "Campbell · Radiology · Wein Urodynamics",
  },
  {
    id: "lasers",
    title: "Lasers & energy",
    short: "Ho:YAG, Tm:YAG, GreenLight",
    blurb: "Physics, tissue interaction and comparative tables for BPH and stone lasers.",
    chapter: "Smith's Endourology",
  },
  {
    id: "laparoscopy",
    title: "Laparoscopy & robotics",
    short: "Da Vinci, NOTES, ERAS",
    blurb: "Platforms, haemostasis, simulation and the evidence versus laparoscopy.",
    chapter: "Glenn's · Hinman Atlas",
  },
  {
    id: "paediatric",
    title: "Paediatric urology",
    short: "PUV, VUR, ANH, hypospadias",
    blurb: "Antenatal hydronephrosis through valve bladder, reflux and DSD — gold-medal favourites.",
    chapter: "Campbell Paeds · EAU Paediatric",
  },
  {
    id: "infections",
    title: "Infections & inflammation",
    short: "Sepsis, GUTB, EPN, Fournier",
    blurb: "Septic shock, chyluria, UTI in pregnancy, emphysematous pyelonephritis and tuberculosis.",
    chapter: "Campbell Infection · WHO TB",
  },
  {
    id: "infertility",
    title: "Male infertility",
    short: "Azoospermia, TESE, WHO semen",
    blurb: "Work-up algorithms, retrieval techniques, genetics and cryopreservation.",
    chapter: "Campbell Andrology · WHO 6th semen",
  },
  {
    id: "sexual",
    title: "ED, orgasm & priapism",
    short: "PDE5, priapism, transgender",
    blurb: "Erection hemodynamics, PDE5, stuttering priapism and exam stems on gender-affirming surgery.",
    chapter: "Campbell Sexual function · ISSM",
  },
  {
    id: "testes",
    title: "Testis & scrotum",
    short: "GCT, torsion, varicocele",
    blurb: "IGCCCG, RPLND, acute scrotum and fertility preservation.",
    chapter: "Campbell Oncology · EAU Testis",
  },
  {
    id: "penis",
    title: "Penis",
    short: "Ca penis, Peyronie, hypospadias",
    blurb: "Inguinal dissection, organ-sparing, Peyronie's surgery and fracture penis.",
    chapter: "EAU Penile · Hinman",
  },
  {
    id: "renal-anatomy",
    title: "Renal embryology & anatomy",
    short: "Horseshoe, Gerota, vessels",
    blurb: "Fusion anomalies, Brodel's line and surgical anatomy for endourology.",
    chapter: "Hinman · Campbell Anatomy",
  },
  {
    id: "nephrology",
    title: "Nephrology for urologists",
    short: "CKD, RTA, RVHTN, hyperK",
    blurb: "Acid-base, osteodystrophy, Goldblatt models and contrast nephropathy.",
    chapter: "Brenner · Campbell",
  },
  {
    id: "renal-trauma",
    title: "Renal trauma",
    short: "AAST, embolization",
    blurb: "AAST grading, imaging triggers and angioembolization versus open repair.",
    chapter: "AAST · EAU Trauma",
  },
  {
    id: "renal-tumors",
    title: "Renal tumours",
    short: "RCC, VHL, Wilms, SRM",
    blurb: "WHO subtypes, nephrometry, IVC thrombus, IO, VHL and Wilms protocols.",
    chapter: "WHO GU · EAU RCC · COG/SIOP",
  },
  {
    id: "renal-surgery",
    title: "Renal surgery",
    short: "PN, PUJO, hydatid",
    blurb: "Retroperitoneoscopy, partial nephrectomy complications and pyeloplasty variants.",
    chapter: "Glenn's · Hinman",
  },
  {
    id: "stones",
    title: "Lithiasis & endourology",
    short: "PCNL, ESWL, MET, RIRS",
    blurb: "The largest repeat bank: PCNL bleeding, SWL physics, metabolic work-up and pregnancy stones.",
    chapter: "Smith's · EAU Urolithiasis",
  },
  {
    id: "ureter",
    title: "Ureter",
    short: "Injury, Boari, retrocaval",
    blurb: "Iatrogenic injury algorithms, reimplant, megaureter and ureteroscopy complications.",
    chapter: "Campbell Trauma · Hinman",
  },
  {
    id: "adrenal",
    title: "Adrenal",
    short: "Incidentaloma, pheo, Conn",
    blurb: "RAAS, NIH incidentaloma pathway, pheo prep and neuroblastoma.",
    chapter: "NIH / AACE · Campbell Adrenal",
  },
  {
    id: "functional",
    title: "Storage & emptying",
    short: "SUI, NGB, OAB, UDS",
    blurb: "Continence mechanics, slings, SCI bladder, DSD and sacral neuromodulation.",
    chapter: "ICS · Wein · EAU Incontinence",
  },
  {
    id: "bladder",
    title: "Urinary bladder",
    short: "NMIBC, BCG, diversion, trauma",
    blurb: "EORTC risk, BCG failure, Studer pouch, PLND templates and pelvic fracture bladder.",
    chapter: "EAU NMIBC/MIBC · Campbell",
  },
  {
    id: "prostate",
    title: "Prostate",
    short: "CaP, BPH, CRPC, mpMRI",
    blurb: "McNeal, PI-RADS, STAMPEDE, CRPC drugs, TURP hyponatraemia and PPI.",
    chapter: "EAU PCa · AUA BPH · Campbell",
  },
  {
    id: "urethra",
    title: "Urethra",
    short: "Stricture, PFUDD, BMG",
    blurb: "Bulbar options, non-transecting urethroplasty, PFUDD acute care and grafts.",
    chapter: "EAU Urethral · Jordan/McAninch",
  },
  {
    id: "transplant",
    title: "Renal transplant",
    short: "Rejection, donor, urologic Cx",
    blurb: "Work-up, HLA, ABMR, oliguria on day-0, laparoscopic donor and swap transplant.",
    chapter: "KDIGO · Campbell Transplant",
  },
  {
    id: "recent",
    title: "Recent advances",
    short: "Tissue engineering, RFA, nano",
    blurb: "Regenerative urology, cryotherapy, neuromodulation and nanotechnology stems.",
    chapter: "Campbell New tech · EAU",
  },
  {
    id: "stats",
    title: "Statistics & trials",
    short: "RCT, bias, t-test",
    blurb: "Blinding, allocation concealment, parametric tests and screening biases.",
    chapter: "Users' Guides · CASP",
  },
  {
    id: "misc",
    title: "Miscellaneous",
    short: "RPF, Botox, Clavien, ICG",
    blurb: "Retroperitoneal fibrosis, DVT, prune belly, apoptosis and nuclear medicine.",
    chapter: "Campbell · Clavien-Dindo",
  },
];
