import type { Master } from "../types";

export const ureter: Master[] = [
  {
    id: "ectopic-ureter",
    topicId: "ureter",
    title: "Ectopic ureter — embryology (single vs duplex) and management",
    highYield: true,
    gold: true,
    tags: ["Weigert-Meyer", "duplex", "ectopic ureter", "upper moiety"],
    exams: [
      { session: "Jun", year: 2017, marks: "5+5", stem: "Embryology of ectopic ureter in cases with single ureter and complete duplication of ureter." },
      { session: "Jun", year: 2015, marks: "6+4", stem: "Embryological basis of complete duplication of ureter. Management of the ectopic ureter in duplex kidney with non-functional upper moiety of the kidney." },
      { session: "Dec", year: 2018, marks: "3+3+4", stem: "Anatomy of lower ureter. Diagnosis and management of unilateral ectopic ureter." },
    ],
    related: ["megaureter", "cuavd", "ureteric-reimplant"],
    references: [
      "Campbell-Walsh-Wein, Anomalies of the ureter",
      "EAU Paediatric Urology — duplex and ectopic ureter",
      "Mackie–Stephens theory; Weigert–Meyer rule",
    ],
    answer: [
      { t: "tip", k: "exam", v: "Draw the Wolffian duct, ureteric bud take-off, and the Weigert–Meyer crossover. Single-system ectopic = earlier/more cranial bud problem + often a dysplastic kidney. Duplex ectopic = upper-moiety ureter inserts caudal and medial." },
      { t: "h", v: "Embryology — ureteric bud timing (Mackie–Stephens)" },
      { t: "p", v: "The ureteric bud arises from the mesonephric (Wolffian) duct at weeks 4–5 and meets the metanephric mesenchyme. The common excretory duct is absorbed into the urogenital sinus so the ureteric orifice migrates superolaterally onto the trigone while the mesonephric duct (vas/Gartner) migrates inferomedially toward the veru / vaginal vestibule. Buds that arise too cranial (late absorption) insert ectopically caudal/medial to the trigone and induce a poorly differentiated (upper) pole. Buds that arise too caudal insert laterally/cranially and have a short intramural tunnel → reflux (lower pole of duplex)." },
      { t: "h", v: "Complete duplication" },
      { t: "ul", v: [
        "Two ureteric buds (or one that bifurcates before the mesenchyme — incomplete duplication / Y-junction, both orifices on the trigone).",
        "Weigert–Meyer: the upper-moiety ureter drains caudal and medial to the lower-moiety orifice (it is the ‘ectopic’ one). The lower-moiety ureter is orthotopic but refluxes (short tunnel).",
        "Upper moiety: obstruction / ureterocele / ectopic insertion (female: urethra, vestibule, vagina, Gartner — continuous dribbling with otherwise normal voids because the lower moiety fills the bladder; male: posterior urethra, seminal vesicle, vas — never below the sphincter, so no continuous incontinence).",
        "Lower moiety: VUR, scarring, ‘drooping lily’ on IVP/MRU (the lower pole calyces are displaced by a poorly functioning dilated upper moiety).",
      ]},
      { t: "h", v: "Single-system ectopic ureter" },
      { t: "ul", v: [
        "The sole ureter inserts below the bladder neck / into Wolffian remnants. The kidney is often dysplastic, small, pelvic. Females: continuous incontinence with a dry-looking ‘normal’ voiding diary — classic 6-year-old always wet. Males: epididymitis, pelvic cyst (Zinner overlap), not continuous leak (sphincter below insertion).",
        "Associated: contralateral duplication, genital anomalies, CUAVD/renal agenesis field defects.",
      ]},
      { t: "h", v: "Anatomy of the lower ureter (Dec 18 part A)" },
      { t: "ul", v: [
        "Three physiologic narrowings: PUJ, iliac crossing, VUJinner mural. Waldeyer sheath, intramural 1.5–2.5 cm, intramural + submucosal tunnel 5:1 ratio prevents reflux.",
        "Blood: periureteral adventitial plexus from renal, gonadal, aorta, common iliac, vesical — stay on the ureter, do not skeletonise. Distal ureter from superior and inferior vesical; hence a psoas hitch/Boari still lives if the bladder pedicles are intact.",
        "Relations: vas/round ligament, uterine artery (water under the bridge — ureter under uterine artery at the isthmus), obliterated umbilical, broad ligament. This is why hysterectomy injures it here.",
      ]},
      { t: "h", v: "Diagnosis of unilateral ectopic ureter" },
      { t: "ul", v: [
        "History: continuous dribble in a girl with otherwise normal voids is pathognomonic until proven otherwise. Boys: infection, epididymitis, infertility later.",
        "Exam: vaginal introitus inspection, milk the urethra. Labs, culture.",
        "US: duplex, upper-pole hydro, poorly visualised dysplastic kidney (the kidney can be missed — ‘absent kidney’ + continuous wetness = look harder with MRU).",
        "MRU / urography: gold for the ectopic insertion and duplex anatomy. DMSA: function of the moiety (decides salvage vs heminephrectomy). MCUG: lower-moiety reflux. Cystoscopy + vaginoscopy: hemitrigone, ectopic orifice (often not found — do not require seeing it). Exam under anaesthesia.",
      ]},
      { t: "h", v: "Management of ectopic ureter with non-functional upper moiety (Jun 15)" },
      { t: "ul", v: [
        "If upper moiety function is negligible (DMSA <5–10%) and the child is wet / infected: laparoscopic/robotic or open upper-pole heminephroureterectomy, leaving a short stump. Care of the lower-moiety vessels (polar arteries). Stump reflux is uncommon if the stump is not massive; symptomatic stumps can be excised later.",
        "Alternative in selected: proximal ureteroureterostomy (upper-to-lower) or distal UU (end-to-side into the recipient ureter) — drains the ectopic system into the orthotopic ureter, spares a heminephrectomy, good if there is residual function or if heminephrectomy risk to lower pole is high. The distal ectopic stump still may need attention if it refluxes / sepses.",
        "If the moiety functions: ureteral reimplantation (tapered if mega) or UU. Ureterocele: see paediatric — puncture in the septic neonate, later reconstruction.",
        "Single-system ectopic into vagina with a tiny dysplastic kidney: laparoscopic nephroureterectomy cures the drip.",
        "Always image the contralateral system before removing anything.",
      ]},
      { t: "tip", k: "gold", v: "Weigert–Meyer: upper moiety = ectopic caudal-medial; lower = reflux. A wet girl with a ‘solitary’ kidney still has an ectopic dysplastic moiety until MRU says otherwise." },
    ],
  },
  {
    id: "megaureter",
    topicId: "ureter",
    title: "Megaureter — clinical features, surgery, principles",
    highYield: true,
    gold: false,
    tags: ["POM", "adynamic segment", "tapering", "reimplant"],
    exams: [
      { session: "Jun", year: 2021, marks: "5+5", stem: "What are the clinical features of Mega-Ureter? Describe surgical approaches and principles." },
    ],
    related: ["ectopic-ureter", "ureteric-reimplant"],
    references: [
      "EAU Paediatric Urology — megaureter",
      "Campbell-Walsh-Wein, Megaureter",
      "Pfister–Hendren / King / Starr tapering",
    ],
    answer: [
      { t: "p", v: "Megaureter = ureter dilated ≥7 mm (fetal / paediatric US definition; adults obviously larger). It is a description, not a diagnosis. Smith / King / Pfister–Hendren classification: refluxing, obstructed, non-refluxing non-obstructed, and combined refluxing-obstructed; each primary (intrinsic) or secondary (to bladder outlet, neurogenic, prune belly, stones, stricture)." },
      { t: "h", v: "Clinical features" },
      { t: "ul", v: [
        "Antenatal hydroureteronephrosis (commonest current presentation of primary obstructive megaureter, POM).",
        "Infants: UTI, sepsis, failure to thrive, haematuria, a flank/lower-quadrant mass (the ureter itself), stones in a stagnant system.",
        "Older: pain, recurrent UTI, haematuria, hypertension if scarred, incidental.",
        "Secondary: symptoms of PUV, neuropathic bladder, urethral stricture, stone, TB, schisto, tumour — always exclude BOO before labelling primary.",
        "Exam: abdomen, spine, genitalia, BP, growth. Labs: Cr (especially bilateral / solitary), culture.",
      ]},
      { t: "h", v: "Evaluation (to sort reflux vs obstruction vs neither)" },
      { t: "ul", v: [
        "US: ureteral diameter, calyceal dilatation, parenchyma, bladder wall, residual, contralateral kidney.",
        "MCUG: VUR grade, PUV, bladder.",
        "MAG3 diuretic renogram: obstructed vs dilated non-obstructed; split function. The adynamic juxtavesical segment of POM is the hold-up.",
        "MRU if anatomy unclear. Cystoscopy + RGP rarely.",
      ]},
      { t: "h", v: "Natural history and when to operate" },
      { t: "p", v: "Most primary megaureters, especially non-obstructed / non-refluxing and many POMs, improve in the first 2–3 years as the adynamic segment matures. Operate for: breakthrough febrile UTI on prophylaxis, split function <40% and falling, increasing dilatation, stones, pain, parental/social failure of conservative care. Temporary drainage (JJ or PCN) for sepsis, not as definitive therapy." },
      { t: "h", v: "Surgical principles" },
      { t: "ul", n: true, v: [
        "Treat the bladder first if secondary (valves, CIC + anticholinergic, reduction cystoplasty is last).",
        "Refluxing megaureter: reimplant with a 5:1 tunnel; taper if the ureter is too fat to make a tunnel (a wide ureter in a short tunnel will reflux).",
        "Obstructed POM: excision of the adynamic distal segment + tapering + reimplant (Politano–Leadbetter, Cohen, Lich–Gregoir with tapering — Cohen is versatile). Hendren (extravesical excision of the aperistaltic segment) historically.",
        "Tapering: Starr (infolding, preserves blood) vs Hendren/Kalicinski (excisional tapering of the lateral anti-mesenteric wall — never medial, the vessels run medially). Taper only the distal 5–8 cm that will live in the tunnel; a pan-tapered ureter dies. Stapled Kalicinski folding is an option.",
        "If function of that kidney is <10–15% and the other kidney is healthy: nephroureterectomy rather than heroic reconstruction.",
        "Infant alternative: refluxing ureterostomy / end-cutaneous ureterostomy as a temporising diversion, later undiversion. Distal ureteral side-to-side ‘refluxing reimplant’ (end-cutaneous in the bladder) as a temporising internal diversion in small infants (Lee / Kaefer) — exam one-liner.",
        "Lap/robotic extravesical reimplant ± tapering in older children and adults, high-volume centres.",
        "Follow-up: US, MAG3, culture, BP. Persistent dilatation is allowed if function and infections are good.",
      ]},
      { t: "tip", k: "gold", v: "Megaureter is a description. Exclude the bladder. Most POM is watched. Surgery = cut the adynamic bit, taper laterally, 5:1 reimplant." },
    ],
  },
  {
    id: "ureteric-injury",
    topicId: "ureter",
    title: "Ureteric injury — causes, early vs delayed, gynae, URS avulsion",
    highYield: true,
    gold: true,
    tags: ["iatrogenic", "hysterectomy", "avulsion", "AAST", "Boari"],
    exams: [
      { session: "Jun", year: 2017, marks: "3+7", stem: "Enumerate the causes of upper ureteral injury. What is the early and the delayed management of ureteral injuries?" },
      { session: "Jun", year: 2019, marks: "2+(4+4)", stem: "Classify iatrogenic ureteral injuries. Diagnosis and outline of management of ureteral injuries during obstetrical & gynaecological surgery." },
      { session: "Dec", year: 2011, marks: "5+5", stem: "How would you diagnose a ureteric injury in the first few post-operative days after an abdominal hysterectomy? What is the algorithm for managing such injuries?" },
      { session: "Jun", year: 2020, marks: "6+4", stem: "Mechanism of occurrence of ureteric avulsion during uretero-renoscopy, with the help of line diagrams. What are the possible management options?" },
      { session: "Jun", year: 2018, marks: "10", stem: "Management of ureteric avulsion during uretero-renoscopy procedure." },
      { session: "Dec", year: 2021, marks: "7+3", stem: "Management of ureteral injuries and complications of ileal ureter." },
    ],
    related: ["boari-flap", "ureteric-reimplant", "ileal-ureter", "urs-complications"],
    references: [
      "EAU Urological Trauma / Iatrogenic ureteric injury",
      "AUA Urotrauma",
      "Campbell-Walsh-Wein, Ureteral trauma",
      "AAST ureter injury grades",
    ],
    answer: [
      { t: "h", v: "Causes and classification" },
      { t: "tbl", h: ["Setting", "How"], r: [
        ["Gynaecologic (most common iatrogenic, 50–70%)", "TAH/TLH, radical hysterectomy, Caesarean (especially repeat, broad-ligament bleeding), pelvic floor, endometriosis, fibroids. Site: uterine-artery crossing, infundibulopelvic ligament, vaginal cuff / cardinal ligament."],
        ["Colorectal / vascular / spine", "Low anterior resection, AAA, aortoiliac, lumbar disc — left ureter more."],
        ["Urologic", "URS (perforation, avulsion), RPLND, PUJO, stone, bladder surgery, pelvic LND, radiation later"],
        ["Trauma", "Penetrating (gun, stab) > blunt (deceleration PUJ avulsion in children, pelvic fracture distal)."],
        ["Endometriosis / tumour / TB / radiation", "May declare as delayed stricture / fistula"],
      ]},
      { t: "p", v: "AAST: I haematoma; II laceration <50% circumference; III >50%; IV complete transection <2 cm devascularisation; V complete + >2 cm avascular. Mechanism: ligation, kinking, crush (clamp), transection, resection, thermal (Ligasure/monopolar delayed necrosis 3–14 days), ischaemic stripping, perforation, avulsion, intramural oedema from URS." },
      { t: "h", v: "Intra-operative recognition (gynae)" },
      { t: "ul", v: [
        "Prevention: know the water-under-the-bridge, stay at the cervix, identify ureter before clamping IP ligament, cystoscopy with dye at the end of TLH (standard in many units).",
        "If suspected on table: inspect, give methylene blue / indigo / ICG IV, cystoscopy for jets, on-table RGP. Immediate repair over a stent by a urologist is the best outcome — do not ‘wait and see’ a transected ureter.",
      ]},
      { t: "h", v: "Diagnosis in the first days after hysterectomy (Dec 11)" },
      { t: "ul", v: [
        "Clues: loin pain, fever, ileus, ascites / drain fluid (creatinine of the fluid ≫ serum), anuria if bilateral, vaginal watery leak (ureterovaginal fistula, typically day 5–14, especially thermal), rising Cr, hydronephrosis on US, haematuria (inconstant).",
        "Drain / pad fluid creatinine, US, CT urography (the diagnostic workhorse — contrast extravasation, urinoma, ligation = cut-off without extravasation), cystoscopy + RGP, vaginal speculum. MCUG if vesicovaginal also possible (laparoscopic hysterectomy can injure both).",
        "Do not delay imaging because she is ‘only day 2’.",
      ]},
      { t: "flow", title: "Post-hysterectomy ureteric injury", nodes: [
        { id: "a", kind: "start", label: "Suspect (pain, leak, hydronephrosis, drain Cr)", to: ["b"] },
        { id: "b", kind: "action", label: "CTU ± cystoscopy/RGP. Resuscitate sepsis, drain urinoma (PCN or interventional)", to: ["c"] },
        { id: "c", kind: "decision", label: "Recognised <72 h, patient well, tissues friendly?", to: ["d", "e"] },
        { id: "d", kind: "end", label: "Immediate reconstruction (see options by level) + stent + drain" },
        { id: "e", kind: "decision", label: "Delayed recognition / thermal / infected urinoma / unstable?", to: ["f"] },
        { id: "f", kind: "action", label: "PCN ± attempt antegrade/retrograde stent. If stented and partial, trial of 6 weeks then restudy", to: ["g"] },
        { id: "g", kind: "end", label: "Elective reconstruction at 6–12 weeks when inflammation settled. Fistula: same — proximal diversion then repair or one-stage in selected" },
      ]},
      { t: "h", v: "Reconstruction by level (early or delayed — same menu)" },
      { t: "tbl", h: ["Level", "Options"], r: [
        ["Distal (below iliac, the gynae zone) — most", "Ureteroneocystostomy (Lich–Gregoir / Politano) ± psoas hitch. Boari if more length needed. Do NOT spatulate into a radiated, ischaemic, short bit and hope. Debride to bleeding ureter."],
        ["Mid", "Uretero-ureterostomy (spatulated, tension-free, stent, drain) if both ends healthy and a short gap. Transuretero-ureterostomy (TUU) if the ipsilateral bladder is hostile. Boari + hitch can reach mid."],
        ["Upper / PUJ", "UU if short; ureterocalycostomy; ileal ureter; renal autotransplant; rarely nephrectomy if the other kidney is perfect and the patient unstable / kidney badly damaged."],
        ["Complete loss, hostile pelvis, radiation", "Ileal ureter, autotransplant, or nephrectomy. Buccal ureteroplasty for short strictures in expert hands."],
      ]},
      { t: "p", v: "Principles: spatulate, mucosa-to-mucosa, no tension, stent, drain, preserve adventitia, refluxing anastomosis acceptable in adults if that is what tension-free requires, never leave a ligature on and ‘refer tomorrow’ without diversion." },
      { t: "h", v: "URS avulsion (Jun 20 / Jun 18)" },
      { t: "p", v: "Mechanism: the scabbard / intussusception injury. A basketed stone or a tight intramural/UPJ is pulled with the ureteroscope; the mucosa then full thickness gives way, and the ureter intussuscepts off its adventitia — ‘the ureter comes out on the scope’ (complete avulsion) or a mucosal sleeve strips (mucosal avulsion). Risk: oversized sheath in a virgin ureter, force, proximal basket without unroofing, cup-biopsy yank, male intramural, stone burden, previous scar, using the basket as a tractor. Draw: scope + basket in upper ureter → resistance at PUJ/iliac → telescoping of mucosa → complete discontinuity with a proximal ureter held only by a thread of adventitia or lying free." },
      { t: "ul", v: [
        "Prevention: safety wire, unsheath the stone or laser it, do not pull a large intact stone, prestent the tight ureter and come back, use a small scope, UAS only after dilatation is honest.",
        "Immediate: stop. Leave a wire if it is still in the true lumen (often it is not). PCN. Do not convert a mucosal scrape into a nephrectomy with repeated passes.",
        "Complete avulsion, recognised at once, clean, short, patient well: immediate UU / reimplant / Boari as level dictates, by an experienced open/lap surgeon — not a 2 a.m. first-time Boari if you can PCN and return in daylight. Long-gap proximal avulsion: PCN, delayed ileal ureter or autotransplant. Delayed recognition (urinoma, sepsis): drain, PCN, reconstruct later.",
        "Mucosal sleeve avulsion with continuity: stent 2–6 weeks, restudy; stricture rate is high — be ready to reconstruct.",
      ]},
      { t: "tip", k: "gold", v: "Gynae injury is distal: hitch and reimplant. Delayed diagnosis = PCN now, reconstruct later. URS avulsion = PCN, do not re-endoscope the hanging ureter, reconstruct at the right time by level." },
    ],
  },
  {
    id: "ureteric-reimplant",
    topicId: "ureter",
    title: "Ureteric reimplantation — indications, techniques, results",
    highYield: true,
    gold: true,
    tags: ["Cohen", "Lich-Gregoir", "Politano-Leadbetter", "psoas hitch"],
    exams: [
      { session: "Dec", year: 2018, marks: "10", stem: "Different techniques of ureteric re-implantation." },
      { session: "Dec", year: 2021, marks: "2+6+2", stem: "Ureteric reimplantation: indications for surgery. Different techniques of ureteric reimplantation. Complications and long-term results." },
    ],
    related: ["ureteric-injury", "boari-flap", "megaureter", "ectopic-ureter"],
    references: [
      "Campbell-Walsh-Wein, Ureteroneocystostomy",
      "Hinman Atlas",
      "EAU Paediatric VUR / Trauma",
    ],
    answer: [
      { t: "h", v: "Indications" },
      { t: "ul", v: [
        "VUR: breakthrough febrile UTI, declining function, parental preference after failed endoscopic, duplex lower moiety, adult reflux with recurrent pyelo.",
        "Distal ureteric injury / stricture / fistula (post-hysterectomy, URS, stone, TB, endometriosis, tumour after distal ureterectomy for UTUC).",
        "Megaureter (after excision of adynamic segment), ectopic ureter with function, ureterocele reconstruction, transplant ureter, bladder diverticulectomy involving the orifice, re-do after failed reimplant.",
      ]},
      { t: "h", v: "Principles common to all" },
      { t: "ul", v: ["Tension-free, spatulated, well-vascularised ureter", "Submucosal tunnel ~5:1 times the ureteral diameter (Paquin)", "No twist, no kinking at the hiatus", "Bladder that empties (fix BOO/NGB first)", "Stent in adults / re-do / tapered; often no stent in straightforward paediatric Cohen", "Drain"] },
      { t: "tbl", c: "Techniques — know one extra- and one intra-vesical well enough to operate on paper", h: ["Operation", "Type", "How", "Pearl"], r: [
        ["Lich–Gregoir", "Extravesical", "Detrusor trough 4–5 cm, ureter dropped in, detrusor closed over", "Fast, no bladder open, less haematuria. Bilateral = urinary retention risk (detrusor denervation) — stage or do Cohen. Adult distal injury workhorse with hitch."],
        ["Politano–Leadbetter", "Intravesical, combined", "New hiatus higher, ureter brought through a submucosal tunnel to a new neocystostomy; old hiatus closed", "Anatomic orthotopic. Risk of obstruction if the hiatus is too high / kinks. Classic paediatric."],
        ["Cohen cross-trigonal", "Intravesical", "Tunnel across the trigone to the contralateral side", "Versatile, good for duplex (common sheath), megaureters, re-do. Later retrograde access is harder (warn the future endourologist). Very popular."],
        ["Glenn–Anderson", "Intravesical", "Advance the orifice distally along the same side", "Needs enough trigone; limited gain"],
        ["Gil-Vernet trigonoplasty", "Intravesical", "Medialise both orifices", "Historical, modest"],
        ["Psoas hitch + UNCX", "Bladder mobilisation", "Bladder dome sutured to psoas tendon (avoid genitofemoral nerve, avoid ureter itself), then Lich or Politano", "Gains 3–5 cm. Distal injury gold with Boari."],
        ["Boari flap", "See dedicated card", "Bladder flap tube to mid-ureter", "Gains 10–15 cm"],
        ["TUU", "End-to-side to contralateral ureter", "When bladder unusable on that side", "Puts both kidneys on one ureter — stone/stricture later is a disaster. Consent."],
        ["Endoscopic STING / HIT / Double HIT", "Not a reimplant but the comparator", "Dx/HA submucosal", "VUR first-line in many children; not for a transected ureter"],
        ["Lap/robotic Lich", "Extravesical", "Same as open, pneumovesicum Cohen also described", "Adult distal stricture / injury in high-volume robotic units"],
      ]},
      { t: "h", v: "Complications and long-term" },
      { t: "ul", v: [
        "Obstruction (oedema, kink, ischaemia, too tight tunnel) — early PCN/stent; late revision.",
        "Persistent / contralateral reflux (high voiding pressure missed).",
        "Haematuria, clot retention (intravesical), leak, fistula, UTI, stone on a non-absorbable hitch suture.",
        "Retention after bilateral extravesical (neuropraxia of pelvic plexus) — CIC, recovers weeks to months.",
        "Genitofemoral neuralgia after psoas hitch.",
        "Malignancy is not increased by Cohen. Pregnancy is fine. Success >90–95% for primary VUR reimplant; lower for radiated / re-do / TB.",
      ]},
      { t: "tip", k: "gold", v: "Paquin 5:1. Cohen is the exam all-rounder. Distal injury in adults = psoas hitch + extravesical reimplant. Fix the bladder first." },
    ],
  },
  {
    id: "boari-flap",
    topicId: "ureter",
    title: "Boari flap ureteroneocystostomy",
    highYield: true,
    gold: false,
    tags: ["Boari", "psoas hitch", "mid ureter"],
    exams: [
      { session: "Dec", year: 2016, marks: "4+6", stem: "Principles and surgical technique of ureteral reconstruction with Boari’s bladder flap." },
      { session: "Jun", year: 2014, marks: "4+6", stem: "What are the surgical methods for the management of lower ureteral injuries? Describe the indications and technique of Boari flap ureteroplasty." },
    ],
    related: ["ureteric-injury", "ureteric-reimplant", "ileal-ureter"],
    references: [
      "Campbell-Walsh-Wein / Hinman — Boari",
      "EAU Trauma",
    ],
    answer: [
      { t: "p", v: "Boari (1894) = a full-thickness bladder flap, tubularised, to bridge a mid/distal ureteric gap that a psoas hitch alone will not span. Combined hitch + Boari is the usual modern construct. Reach: typically to the pelvic brim / lower lumbar ureter (10–15 cm depending on bladder capacity)." },
      { t: "h", v: "Indications" },
      { t: "ul", v: ["Mid or long distal ureteric loss (iatrogenic, stricture, TB, endometriosis, distal ureterectomy for UTUC) when UU would be under tension and ileum/autotransplant is overkill", "Failed reimplant with a short ureter", "Selected radiation injuries if the bladder itself is healthy — if the bladder is contracted/radiated, Boari is the wrong flap (use ileum)"] },
      { t: "h", v: "Prerequisites / principles" },
      { t: "ul", v: [
        "Bladder capacity ≥200–250 mL, not neuropathic-hostile, not small-capacity TB/radiated brick.",
        "Flap base ≥4 cm (wider than apex) so the blood supply (superior vesical branches in the lateral bladder wall) is not a triangle of death. Length:width never starving.",
        "Tension-free spatulated anastomosis, stent, drain, psoas hitch to take tension off the anastomosis, refluxing or anti-reflux tunnel at the flap tip (anti-reflux is optional in adults; a tight tunnel in a tubular flap can obstruct).",
        "Ureter spatulated, adventitia preserved. Retroperitonealise if possible.",
      ]},
      { t: "h", v: "Steps" },
      { t: "ul", n: true, v: [
        "Supine, midline or Gibson. Identify and debride the healthy proximal ureter, stay atraumatic, sling.",
        "Fill the bladder. Mark a posterolateral flap based at the dome/lateral wall, base ≥4 cm, length = gap + 2 cm, apex ≥3 cm. Incise full thickness.",
        "Psoas hitch of the posterolateral bladder to the psoas tendon with 2-0 absorbable/Vicryl (avoid genitofemoral nerve lying on psoas, avoid femoral nerve deeper). This advances the base of the flap.",
        "Tubularise the flap over a 14–16 Fr catheter with running absorbable, mucosa inverted. Anastomose spatulated ureter to the apex (end-to-end or end-to-side), 4-0/5-0 PDS, over a 6–7 Fr stent. Optional submucosal tunnel.",
        "Close the bladder in two layers, leak-test, drain, catheter 7–10 days, stent 4–6 weeks, then cystogram + nephrostogram if a PCN is present.",
      ]},
      { t: "h", v: "Complications" },
      { t: "ul", v: ["Flap ischaemia / leak / urinoma", "Stricture at the ureter–flap anastomosis (the usual late failure)", "Reflux, UTI, stones", "Reduced bladder capacity / LUTS", "Genitofemoral pain", "Fistula"] },
      { t: "p", v: "Lower-injury menu if the stem asks: stent (partial), UNCX, hitch+UNCX, Boari, TUU, ileal ureter, autotransplant, nephrectomy. Boari sits between hitch and ileum." },
      { t: "tip", k: "gold", v: "Base wider than apex, hitch the bladder, tube the flap, spatulate the ureter, stent. Do not Boari a 100 mL radiated bladder." },
    ],
  },
  {
    id: "ileal-ureter",
    topicId: "ureter",
    title: "Ileal ureter — management context and complications",
    highYield: true,
    gold: false,
    tags: ["ileal ureter", "hyperchloraemic acidosis", "mucus"],
    exams: [
      { session: "Dec", year: 2021, marks: "7+3", stem: "Management of ureteral injuries and complications of ileal ureter." },
    ],
    related: ["ureteric-injury", "boari-flap", "ureteral-stents"],
    references: [
      "Campbell-Walsh-Wein, Ileal ureter (Goodwin / Boxer)",
      "EAU Trauma / Reconstruction",
    ],
    answer: [
      { t: "p", v: "The injury half of this stem is on the ureteric-injury card. Ileal ureter is the long-gap / pan-ureteric reconstruction when hitch+Boari, UU, and TUU cannot reach, the bladder is usable, and the kidney is worth saving (TB pan-stricture, radiation, multiple URS injuries, recurrent transitional-cell after distal ureterectomy, retroperitoneal fibrosis after failed stents, avulsion with a long dead ureter)." },
      { t: "h", v: "Essentials of the operation (so complications make sense)" },
      { t: "ul", v: [
        "Isoperistaltic 15–25 cm of distal ileum, ≥15–20 cm from IC valve, on a generous mesentery, tapered sometimes over a 16 Fr (Yang–Monti / spiral Monti if mesentery is short — more anastomoses). Proximal ileum-to-renal pelvis / spatulated ureter; distal into bladder (refluxing is standard — a tunnelled ileum obstructs). Stent/PCN. Never use ileum if Cr is chronically >2–2.5 mg/dL (metabolic disaster) — then autotransplant or nephrectomy or conduit.",
        "Exclude bowel anastomosis from the retroperitoneum. Appendix is an alternative in children (Mitrofanoff-like ureteric substitute) rarely.",
      ]},
      { t: "h", v: "Complications" },
      { t: "tbl", h: ["Problem", "Why / what to do"], r: [
        ["Hyperchloraemic metabolic acidosis", "Ileal mucosa reabsorbs urinary NH4+/Cl−, secretes HCO3−. Worse if long segment, residual urine, poor GFR. Oral alkali, CIC if the bladder does not empty, consider J-pouch/taper. Contraindicate if GFR low."],
        ["Mucus obstruction / retention", "Mucin from goblet cells. Hydration, vitamin C / N-acetylcysteine washes (evidence modest), regular voiding, irrigation if reconstructed bladder."],
        ["Bacteriuria / recurrent UTI / stones (struvite, mucus nidus)", "Refluxing ileum + mucus. Culture-directed; never endless FQ. Treat obstruction."],
        ["Anastomotic stricture (renal or vesical end)", "Ischaemia, tension. Stent, redo, PCN."],
        ["Fistula, leak, urinoma, ileus, anastomotic bowel leak", "Early surgical. Drain Cr."],
        ["B12 / bile-salt diarrhoea if terminal ileum abused", "Keep 15–20 cm of TI. Replace B12 if deficient."],
        ["Elongation / ‘ileal loop syndrome’, mucus bladder stones", "Follow-up cystoscopy / imaging. Taper/revise."],
        ["Malignancy (adenocarcinoma of ileum exposed to urine)", "Late, rare, more in conduits/pouches after 10–15 y. Do not oversell but mention surveillance of haematuria."],
        ["Mucus in the bladder, LUTS, nocturnal incontinence", "Bladder cycling, alkali, time"],
        ["Ischaemic loss of the whole segment", "Too-short mesentery, twist — nephrostomy, later redo or nephrectomy"],
      ]},
      { t: "tip", k: "exam", v: "Ileal ureter is for long-gap with a decent GFR and a decent bladder. Quote hyperchloraemic acidosis, mucus, UTI/stones, anastomotic stricture, B12. Do not put ileum in a Cr 3.5 patient." },
    ],
  },
  {
    id: "retrocaval-ureter",
    topicId: "ureter",
    title: "Retrocaval / preureteral vena cava",
    highYield: true,
    gold: true,
    tags: ["retrocaval", "preureteral IVC", "subcardinal", "S-shaped"],
    exams: [
      { session: "Jun", year: 2018, marks: "10", stem: "Development of retrocaval ureter and its management." },
      { session: "Dec", year: 2012, marks: "5+2+3", stem: "Discuss the embryology, supported with diagram, of pre-ureteral vena cava, its types and surgical management." },
      { session: "Dec", year: 2015, marks: "3+3+2+2", stem: "Pre-ureteral venacava: anatomy, embryology, clinical presentation, indications for intervention." },
    ],
    related: ["ureteric-injury", "ectopic-ureter"],
    references: [
      "Campbell-Walsh-Wein, Anomalies of the IVC / ureter",
      "Bateson–Atkinson types",
      "Hinman",
    ],
    answer: [
      { t: "p", v: "The correct embryologic name is preureteral vena cava (the IVC is in the wrong place, not the ureter). Almost always right-sided. The right ureter passes posterior to the IVC then emerges medially, describing a reverse-J or S on IVP, with obstruction at the IVC crossing." },
      { t: "h", v: "Embryology (draw the three paired veins)" },
      { t: "p", v: "The infrahepatic IVC is normally formed from the right subcardinal vein. Posterior cardinal veins lie dorsal to the developing ureters; subcardinals lie ventral. If the right posterior cardinal persists as the infrahepatic IVC (instead of the subcardinal), the ureter is trapped dorsal to the IVC — preureteral cava. Left-sided and bilateral forms occur with situs / duplicated IVC / circumaortic renal collar (nutcracker overlap)." },
      { t: "tbl", h: ["Type (Bateson–Atkinson / Kenawi–Williams)", "Appearance", "Obstruction"], r: [
        ["Type I (low, common, S-shaped / fish-hook)", "Crossing at L3, marked medial swing, hydronephrosis", "Usually symptomatic"],
        ["Type II (high, sickle / reverse-J)", "Crossing at the renal pelvis, gentle curve", "Often less obstructed"],
      ]},
      { t: "h", v: "Clinical presentation" },
      { t: "ul", v: ["Age 20–40, right loin pain, UTI, stones, haematuria, incidental hydro. Rarely infants.", "IVP/CTU: S or reverse-J, medialised mid-ureter behind the IVC, delayed nephrogram. MAG3 for obstruction vs baggy. CT is diagnostic (the ureter is behind the cava)."] },
      { t: "h", v: "When to intervene" },
      { t: "ul", v: ["Pain, recurrent infection, stones, obstructed MAG3 with falling function, not a merely pretty S-curve with a happy kidney."] },
      { t: "h", v: "Surgery" },
      { t: "ul", v: [
        "Standard: transect the ureter (usually just lateral to the IVC), transpose anterior to the cava, spatulated UU (Anderson–Hynes-style if PUJ is involved in type II), stent. The IVC is not moved. Laparoscopic/robotic UU is the modern default.",
        "If the segment behind the cava is atretic / a stone nest: excise that bit.",
        "Nephrectomy if the kidney is dead.",
        "Do not ‘uncoil’ without dividing — the ureter is not long enough and the cava is not a sling you slip off.",
      ]},
      { t: "tip", k: "gold", v: "The cava persisted from the posterior cardinal; the ureter is innocent. Type I S-shape is the surgical one. Transposed UU in front of the IVC, nowadays laparoscopic." },
    ],
  },
  {
    id: "urs-complications",
    topicId: "ureter",
    title: "Ureteroscopy complications — prevention and management",
    highYield: true,
    gold: false,
    tags: ["URS", "avulsion", "sepsis", "stricture", "Steinstrasse"],
    exams: [
      { session: "Dec", year: 2016, marks: "10", stem: "Complications of ureteroscopy and its management." },
      { session: "Dec", year: 2012, marks: "3+(4+3)", stem: "Enumerate complications of uretero-renoscopy. Describe steps to prevent and manage these complications." },
    ],
    related: ["ureteric-injury", "ureteral-stents", "ureter-filling-defect"],
    references: [
      "EAU Urolithiasis / CROES URS complications",
      "Smith's Endourology",
      "AUA/EAU URS best practice",
    ],
    answer: [
      { t: "p", v: "Modern URS complication rate: overall 10–20%, significant 2–5%, avulsion <0.5%, sepsis 1–5% (higher if infected stones / no culture). Classify intra-operative vs early vs late; or Clavien." },
      { t: "tbl", h: ["Complication", "Prevent", "Manage"], r: [
        ["Failure to access / mucosal false passage", "Safety wire, hydrophilic wire, don't push against a wall, prestent 1–2 weeks if virgin tight ureter", "Stop, stent, come back. Do not make a second lumen."],
        ["Perforation (contrast extravasation)", "No force, laser not fibre-to-wall, basket under vision", "Stent 2–4 weeks. PCN if stent fails. Reconstruct if complete."],
        ["Mucosal sleeve / complete avulsion", "See avulsion card — no tractor baskets, prestent", "PCN, delayed reconstruction"],
        ["Bleeding / obscured vision", "Careful, treat UTI, avoid lasering a vessel on the papilla blindly", "Wait, increase irrigation modestly, stent, rarely embolise a torn iliac (very rare)"],
        ["Lost / broken stone, broken basket, broken laser fibre", "Don't close the basket on a too-large stone, inspect devices", "Laser the basket wires, go to PCNL if the stone is now proximal and huge, open last"],
        ["Ureteric stricture (1–3%, higher after perforation/impacted stone)", "Gentle, stent after complex cases, treat infection", "Endoscopic dilatation / laser incision if short; UU / reimplant / Boari / buccal if long or ischaemic"],
        ["Sepsis / SIRS", "Pre-op culture, Abx, low-pressure (UAS, automated pumps with limit), don't operate a pyonephrosis — PCN first, residual stone later", "Sepsis bundle, culture, drain the system (stent or PCN), ICU"],
        ["Steinstrasse after URS/ESWL", "Fragment small, stent if large burden", "Conservative if asymptomatic; URS the leader fragment; PCN if obstructed/septic"],
        ["Vesicoureteric reflux after dilatation of intramural ureter", "Usually transient", "Observe"],
        ["Stent colic, forgotten stent, encrustation", "Stent register, α-blocker, shortest dwell", "See stents card"],
        ["Thermal laser injury, ureteric ischaemia from UAS too big", "UAS 12/14 only if the ureter accepts; 10/12 otherwise; skip UAS", "Stent, later stricture work"],
        ["Anaesthetic / DVT / rhabdomyolysis (long flexible URS)", "Time, padding, VTE", "Standard"],
      ]},
      { t: "h", v: "A prevention paragraph that scores" },
      { t: "ul", v: [
        "Culture every URS; treat bacteriuria. Infected obstructed kidney is a decompression, not a laser.",
        "Safety wire. Prestent the unyielding ureter (AUA: staged URS is not a failure).",
        "UAS to lower intra-renal pressure (sepsis, rupture) but never force a 14/16 sheath.",
        "Laser settings: dusting vs fragmentation by stone, fibre on stone not urothelium, pop-dusting with a chamber.",
        "Basket only fragments that fit; open the ureter, not the basket.",
        "Screen-out: pregnant, anticoagulant unreversed for a high-risk stone (or use a dusting-only strategy), untreated UTI.",
      ]},
      { t: "tip", k: "gold", v: "The two that kill: sepsis (culture, pressure, drain) and avulsion (never pull). Prestenting is prevention, not defeat." },
    ],
  },
  {
    id: "ureter-filling-defect",
    topicId: "ureter",
    title: "Filling defect in the left ureter on IVP",
    highYield: false,
    gold: false,
    tags: ["UTUC", "radiolucent stone", "clot", "sloughed papilla"],
    exams: [
      { session: "Jun", year: 2017, marks: "10", stem: "How do you proceed to diagnose and manage a case with suspicion of filling defect in left ureter seen on intravenous Urogram (IVP)?" },
    ],
    related: ["urs-complications", "ureteral-stents"],
    references: [
      "EAU Upper tract urothelial carcinoma / Urolithiasis",
      "Campbell-Walsh-Wein, UTUC diagnosis",
    ],
    answer: [
      { t: "p", v: "A ureteric filling defect on IVP is a radiological finding, not a diagnosis. Work it as: stone vs tumour vs clot vs infection vs artefact, on the left, with the kidney's life in mind." },
      { t: "h", v: "Differential" },
      { t: "ul", v: [
        "Radiolucent stone (uric acid, xanthine, indinavir — indinavir is also CT-lucent), matrix.",
        "UTUC (papillary filling defect, goblet / Bergman's sign — a dilated ureter below a tumour as the catheter coils, shouldering).",
        "Blood clot (trauma, tumour, TCC, stone, papillary necrosis, anticoagulated).",
        "Sloughed papilla (diabetes, analgesic, sickle, obstruction, infection — a triangular defect that may itself obstruct).",
        "Fungus ball (candida, diabetic, stent).",
        "Air (iatrogenic, fistula).",
        "Oedema / stricture / TB / schisto (more irregular, not a discrete lucency).",
        "Crossing vessel / vascular impression, peristalsis (repeat film, fluoroscopy), overlying gas (oblique films).",
        "Metastasis, endometriosis, amyloid — rare.",
      ]},
      { t: "h", v: "Diagnostic sequence" },
      { t: "ul", n: true, v: [
        "History: pain (stone/clot/papilla) vs painless haematuria (UTUC), smoking, Balkan/aristolochic, Lynch, gout, diabetes, analgesic, sickle, anticoagulation, TB, fungus risk, prior stones.",
        "Exam, urine dip/cytology/FISH, culture, eGFR, uric acid, clotting.",
        "NCCT KUB: uric acid stones are still dense (HU 200–400) even if IVP-lucent; indinavir and matrix are not. CTU (excretory) is the modern replacement of IVP — wall thickening, enhancement, synchronous bladder tumour, hydronephrosis.",
        "Cystoscopy (always — UTUC pairs with bladder TCC) ± RGP (better characterisation, washing for cytology), ureteroscopy with biopsy / basket of the lesion under vision, selective cytology.",
        "If clot: restudy after a period / treat the bleeding cause. If papilla: look at all papillae, metabolic work-up. If fungus: culture, amphotericin irrigation / systemic, remove stent.",
      ]},
      { t: "h", v: "Management once you know what it is" },
      { t: "ul", v: [
        "Uric acid stone: alkalinisation (K-citrate, pH 6.5–7.2) can dissolve; if obstructed/septic — drain first. URS if it fails.",
        "UTUC: risk-stratify (EAU). Low-risk small unifocal low-grade: kidney-sparing (URS ablation, distal ureterectomy). High-risk: radical nephroureterectomy with bladder cuff, template LND. Multidisciplinary, Lynch testing.",
        "Clot: irrigation, correct coagulopathy, treat the source.",
        "Sloughed papilla: endoscopic extraction if obstructing; address the cause.",
        "Never laser a ‘stone’ that is actually a sessile TCC without biopsies.",
      ]},
      { t: "tip", k: "exam", v: "IVP filling defect → history + NCCT/CTU + cytology + cystoscopy + URS. Name uric acid, UTUC, clot, papilla, fungus. Bergman's sign = tumour." },
    ],
  },
  {
    id: "ureteral-stents",
    topicId: "ureter",
    title: "Ureteral stents, metallic stents and ureteral access sheaths",
    highYield: true,
    gold: false,
    tags: ["JJ stent", "metallic stent", "UAS", "biofilm", "forgotten stent"],
    exams: [
      { session: "Dec", year: 2015, marks: "5+5", stem: "Advances in ureteral stent design and their advantages and disadvantages." },
      { session: "Jun", year: 2014, marks: "2+5+3", stem: "What are the indications, technique and problems of metallic ureteral stent?" },
      { session: "Jun", year: 2014, marks: "10", stem: "Write a short note on ureteral sheath." },
    ],
    related: ["urs-complications", "ileal-ureter", "ureteric-injury"],
    references: [
      "Smith's Endourology",
      "EAU Urolithiasis — stents and UAS",
      "AUA White Paper on UAS / stents",
    ],
    answer: [
      { t: "h", v: "Stent design — what has actually changed" },
      { t: "ul", v: [
        "Material: polyurethane, silicone (softer, less encrustation, more friction on insertion), Percuflex, copolymer. Hydrophilic coating for insertion. Heparin / diamond-like carbon / silver / triclosan coatings to cut biofilm — modest clinical wins.",
        "Geometry: double-J (pigtail) remains the standard; multi-length ‘one size’ stents; tail stents / distal loops to reduce bladder irritability; magnetic distal ends for office removal; stringed stents after URS (patient-removal).",
        "Dual-durometer: stiff shaft, soft coils. Side holes vs groove (Tria) for flow around encrustation. Anti-reflux valves — mixed evidence.",
        "Drug-eluting (paclitaxel, ketorolac) — experimental / limited.",
        "Metallic: see below. Resonance (tight-coiled, no lumen, urine flows around), Memokath (thermo-expandable nickel-titanium), Allium, UVENTA, iStent — chronic malignant or benign strictures.",
        "Biodegradable stents: polylactic/polyglycolic — not yet routine because of unreliable degradation and obstruction.",
      ]},
      { t: "tbl", h: ["Advance", "Advantage", "Disadvantage"], r: [
        ["Soft silicone / tail / magnetic", "Less LUTS, easier removal", "Migration, cost, not for tight malignant strictures"],
        ["Hydrophilic / coating", "Easier placement, less biofilm in vitro", "Cost; clinical UTI reduction modest"],
        ["Metallic Resonance / Memokath", "12-month dwell, malignant compression", "Cost, encrustation, difficult removal, haematuria, not MRI-simple (check alloy), overgrowth of tumour"],
        ["Stringed stent", "No cystoscopy removal", "Dysuria, accidental pull, infection"],
        ["Biodegradable", "No removal", "Not ready for prime time"],
      ]},
      { t: "h", v: "Metallic stents (Jun 14)" },
      { t: "ul", v: [
        "Indications: malignant extrinsic compression (cervix, prostate, nodes, retroperitoneal) where frequent JJ changes are morbid; selected benign strictures in the surgically unfit (transplant ureter, radiation) after failed polymer stents. Not a first-line after a straightforward URS.",
        "Technique (Resonance as the exam type): retrograde or antegrade over a wire, inner introducer, coil placed so the loops sit in pelvis and bladder, fluoroscopic confirmation. Memokath: flush with 40–45 °C water to expand the proximal bulb, cool with ice-water to remove.",
        "Problems: cost, encrustation/obstruction (still happens, especially if hyperuricosuric / infected), migration, tissue hyperplasia, difficult extraction (Resonance needs a strong pull under anaesthetic), haematuria, UTI, pain, tumour ingrowth (covered vs uncovered), forgotten-stent phenomenon if the 12-month recall fails, not for an undrained sepsis (no lumen in Resonance — flow is extra-luminal; sepsis with mucus/clot can still obstruct).",
      ]},
      { t: "h", v: "Ureteral access sheath (Jun 14 short note)" },
      { t: "p", v: "A hydrophilic coaxial sheath (inner dilator + outer sheath) placed over a wire to the proximal ureter / PUJ to allow repeated atraumatic passage of a flexible ureteroscope, low-pressure irrigation, and extraction of fragments." },
      { t: "ul", v: [
        "Sizes: 10/12, 11/13, 12/14, 13/15 Fr; lengths 35–55 cm. Choose the smallest that admits the scope with outflow. 12/14 is the historical default; 10/12 reduces ureteric injury in virgin ureters.",
        "Advantages: lower intra-renal pressure (sepsis, rupture, pain), better vision, shorter operative time for stone-burden cases, protects the ureter from multiple passes, allows dust extraction.",
        "Problems / complications: ureteric wall injury (traction/ischaemia — Traxer grade 0–4, up to 50% superficial, 5–15% deep if oversized), stricture, failure to place (prestent and restage), reduced outflow if the scope occupies the lumen, not needed for every simple distal URS, cost, theoretically less ‘natural’ deflection of the scope at the lower pole (modern slim scopes have reduced this).",
        "Technique: two wires (safety + working), dilate intramural if needed, never force, keep the distal end just below PUJ (not in a calyx), limit dwell, exit under vision, stent if injury > grade 1 or the case was long.",
        "Contraindications: unyielding ureter, active untreated infection as the sole plan (drain first), tight anastomosis (transplant — careful).",
      ]},
      { t: "h", v: "Forgotten polymer stent — always mention" },
      { t: "p", v: "Encrustation, stone, sepsis, renal failure, litigation. Prevention: stent register, patient card, string where appropriate. Management: multimodal — cystolithotripsy of the bladder coil, URS/PCNL of the renal coil, PCN if obstructed, extracorporeal lithotripsy adjunct. Never pull a calcified stent." },
      { t: "tip", k: "gold", v: "Polymer JJ for weeks; metallic for months of malignant compression; UAS to lower pressure, never to force a 14 Fr sheath up a virgin ureter. Register every stent." },
    ],
  },
];
